import { chromium } from "playwright";
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
const ROOT = process.cwd();
const HOST = "front-door.localhost", ORIGIN = `http://${HOST}:3001`;
const ADMIN="87a6e699-3622-4869-8843-d0867456c0dd", RINCON="6069a466-1445-42df-a64e-cf37ecdc1b99", JOBS="af3bfff6-a255-41e5-9ac2-879d53816163";
const b = await chromium.launch({headless:true});
const c = await b.newContext({viewport:{width:1600,height:1000}});
await c.addCookies([{name:"matrx-active-org",value:`${ADMIN}:${RINCON}`,domain:HOST,path:"/"}]);
const p = await c.newPage();
const rpc=[];
p.on("request",r=>{const u=r.url(); if(u.includes("/rest/v1/rpc/")) rpc.push({t:Date.now(),n:u.split("/rpc/")[1].split("?")[0]});});
const n=randomBytes(16).toString("hex");
writeFileSync(resolve(ROOT,`.dev-login-nonce.${HOST}`), n+"\n");
await p.goto(`${ORIGIN}/api/dev-login?nonce=${n}&next=%2Fdata-v2`,{waitUntil:"domcontentloaded",timeout:180000});
const who = await p.evaluate(async () => (await fetch("/api/whoami")).json());
if(!who?.email) throw new Error("no identity");
console.log("signed in as", who.email);
await p.waitForTimeout(2000);
rpc.length=0;
const t0=Date.now();
await p.goto(`${ORIGIN}/data-v2/${JOBS}`,{waitUntil:"domcontentloaded",timeout:180000});
const samples=[];
for(let i=0;i<300;i++){
  const s=await p.evaluate(()=>{
    const t=Array.from(document.querySelectorAll("table")).sort((a,b)=>b.querySelectorAll("tbody tr").length-a.querySelectorAll("tbody tr").length)[0];
    if(!t) return null;
    const heads=Array.from(t.querySelectorAll("thead th")).map(h=>h.innerText.trim().toUpperCase());
    const ci=heads.findIndex(h=>h.includes("CUSTOMER"));
    const rows=Array.from(t.querySelectorAll("tbody tr"));
    if(ci<0) return {rows:rows.length,ci,heads};
    const cells=rows.map(r=>(r.children[ci]?.innerText||"").trim());
    return {rows:rows.length,ci,loading:cells.filter(x=>/^Loading/.test(x)).length,empty:cells.filter(x=>x==="").length,sample:cells.slice(0,4)};
  });
  samples.push({ms:Date.now()-t0,...(s||{})});
  if(s&&s.rows>0&&s.ci>=0&&s.loading===0&&s.empty<s.rows) break;
  await p.waitForTimeout(100);
}
await p.screenshot({path:"tmp/relmeasure-final.png"});
console.log("URL", p.url(), "| body head:", (await p.evaluate(()=>document.body.innerText.slice(0,300))));
const last=samples[samples.length-1];
console.log("FINAL", JSON.stringify(last));
const firstRows=samples.find(s=>s.rows>0);
const firstHead=samples.find(s=>s.ci>=0);
const firstLoading=samples.find(s=>s.loading>0);
console.log("first rows@",firstRows?.ms,"CUSTOMER col@",firstHead?.ms,"loading seen@",firstLoading?.ms);
console.log("rpc after nav:",rpc.length, JSON.stringify(rpc.reduce((m,r)=>((m[r.n]=(m[r.n]??0)+1),m),{})));
console.log("record_read count:", rpc.filter(r=>r.n==="record_read"||r.n==="read_record").length);
await b.close();
