// GENERATED — do not edit by hand.
//
// Every `platform.feature_knob` key that is read from INSIDE the database (a
// function body or a view), with the function(s) that read it. Regenerate with
// `pnpm generate:knob-database-consumers`; the census itself is measured live
// from `pg_proc`/`pg_views` by `check:settings-orphans`'s IN-DB tier, and
// `pnpm check:knob-database-consumers` FAILS when this file no longer matches
// the live database.
//
// WHY the settings UI needs it: a knob resolved by a trigger has no call site
// any source grep can find, so the hand-kept audit in `disposition.ts` would
// call a working setting "Not connected yet" (DD-183).

export const KNOB_DATABASE_CONSUMERS: Readonly<Record<string, readonly string[]>> = {
  "access.indexed_by_default.agent": ["ai.propose_translation_cell", "custom._action_check", "custom._entity_custom_fields_guard", "custom._value_envelope", "custom.action_run", "custom.enrich_due", "custom.enrich_land", "platform._stamp_actor_tier", "platform.dd166_table_rung_scope_rows_ok", "platform.feature_knob_set", "platform.provision", "platform.seed_list_landing_tab_knob", "platform.seed_shown_to_default_knob", "platform.v_feature_knob_overdue", "public.admin_spend_breakdown", "public.agx_exemplar_approve"],
  "access.indexed_by_default.app": ["public.admin_spend_breakdown"],
  "access.indexed_by_default.fc_set": ["iam.entity_read_expr", "platform.seed_shown_to_default_knob"],
  "access.indexed_by_default.note": ["custom._ctx_store_type", "custom.enrich_land", "custom.table_from_example", "custom.work_decide_many", "hr._enroll_pay_period_rows", "hr.attendance_exception_resolve", "hr.leave_wf_validate", "hr.pay_period_transition", "hr.timesheet_get", "hr.wf_resolve_approvers", "ops.check_items_apply_run", "platform.provision", "platform.provision_batch"],
  "access.indexed_by_default.record": ["campaign_watch.ramp_consumer", "custom._context_copy_fence", "custom._ctx_store_type", "custom._decorations_check", "custom._entity_custom_fields_guard", "custom._merge_field_shape_guard", "custom._record_row_defaults", "custom._record_rule_uses", "custom._row_control_columns", "custom._table_shape_guard", "custom._value_envelope", "custom.action_run", "custom.context_tag_copy_batch", "custom.doc_render_document", "custom.enrich_due", "custom.enrich_land", "custom.inbox_remind_tick", "custom.io_import_rows", "custom.io_outbox_broadcast_stmt", "custom.levels_of", "custom.may_invite_outside", "custom.migrate_delete", "custom.portal_admits", "custom.record_delete", "custom.scope_member_reaches", "custom.share_grant", "custom.shared_only_disagreements", "custom.table_archive", "custom.table_share_outside", "custom.table_share_outside_grant", "custom.table_share_outside_invite", "custom.table_sync", "custom.view_record_order_set", "custom.work_list", "custom.work_slots_declare", "iam.access_arms_from_sources", "iam.accessible_entity_ids", "iam.entity_read_expr", "iam.has_access_for_base", "iam.may_touch_field_itself", "iam.member_level_justified", "iam.publish_binding_create", "iam.publish_to_world", "iam.record_visible_in_org", "platform._context_tag_copy_fence", "platform._context_tag_follow_to_the_copy", "platform.cutover_copy_differences", "platform.enforce_relation_edge"],
  "agent_exemplars.max_approved_per_agent": ["public.agx_exemplar_approve"],
  "ai.translation.agent_confidence_threshold": ["ai.propose_translation_cell"],
  "api_keys.personal_key_max_age_days": ["iam.personal_api_key_create"],
  "billing.new_signup_free_months": ["billing._signup_free_months"],
  "billing.new_signup_free_plan": ["billing._signup_free_months"],
  "billing.usage_near_ratio": ["billing._points_usage_state"],
  "checks.check_run_trash_days": ["ops.check_items_apply_run"],
  "checks.fix_breaker_min": ["ops.check_items_apply_run"],
  "checks.fix_breaker_share": ["ops.check_items_apply_run"],
  "communication.notice_link_names_its_organization": ["communication._dm_action_names_its_organization", "platform._assist_action_names_its_organization", "platform.link_carries_its_organization"],
  "content.document.autosave_version_keep_days": ["content.thin_autosave_versions", "content.type_settings"],
  "content.document.large_body_chars": ["content.document_get", "content.type_settings"],
  "content.document.max_inline_data_uri_bytes": ["content._document_refuse_inline_data_uri", "content.type_settings"],
  "context.follow_batch_rows": ["custom.context_tag_copy_batch"],
  "continued_access.access_cutoff_days": ["platform.continued_access_state"],
  "continued_access.portal_enabled": ["platform.continued_access_state"],
  "continued_access.verification_consent_enabled": ["public.hr_my_verification_consents", "public.hr_verification_consent"],
  "copy.max_auth_lock_ms": ["custom.io_import_rows"],
  "custom.accessible_entity_ids_guard": ["iam.accessible_entity_ids", "iam.record_visible_in_org"],
  "custom.action_run_records_max": ["custom.action_run"],
  "custom.agent_context_value_cap_bytes": ["custom.agent_context_value_cap"],
  "custom.agent_schema_changes": ["custom.agent_change_approval", "custom.enrich_normalize"],
  "custom.archive_confirm_over": ["custom.table_archive"],
  "custom.back_links": ["custom._inverse_key_default", "custom.field_declare", "custom.reverse_columns"],
  "custom.batch_items_max": ["custom.pipeline_move_many", "custom.work_decide_many"],
  "custom.closed_custom_field_tables": ["custom._entity_custom_fields_guard"],
  "custom.consumer_chat_seeding_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_checkout_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_education_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_extension_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_grid_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_retirement_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_saved_ai_outputs_enabled": ["campaign_watch.ramp_consumer"],
  "custom.consumer_scopes_enabled": ["campaign_watch.ramp_consumer"],
  "custom.containment_depth_ceiling": ["custom._containment_guard", "custom._resolve_choice_words", "custom.containment_depth_ceiling", "history.who_could_see"],
  "custom.context_copy_following": ["context._follow_to_the_copy", "custom._context_copy_fence", "platform._context_tag_copy_fence", "platform._context_tag_follow_to_the_copy"],
  "custom.cross_organization_links": ["custom._table_move_plan", "custom.assert_organization_wall", "custom.cross_organization_links_open", "custom.relation_target_card", "custom.relation_value_target_ok", "platform.enforce_relation_edge"],
  "custom.decision_undo_seconds": ["custom.work_inbox"],
  "custom.decoration_rules_max": ["custom._decorations_check"],
  "custom.decorations_max_bytes": ["custom.table_decorate"],
  "custom.document_letterhead": ["custom.doc_letterhead"],
  "custom.document_max_bytes": ["custom.size_refusal"],
  "custom.enrichment_batch_ceiling": ["custom.enrich_due"],
  "custom.enrichment_confidence_floor": ["custom.enrich_normalize"],
  "custom.enrichment_cost_cap_cents": ["custom.enrich_due", "custom.enrich_land", "custom.enrich_normalize"],
  "custom.enrichment_model": ["custom.enrich_normalize"],
  "custom.enrichment_sensitivity_ceiling": ["custom.enrich_normalize"],
  "custom.entity_types_guard": ["iam.converge_legacy_column"],
  "custom.example_rows_max": ["custom.table_from_example"],
  "custom.field_sensitivity_levels": ["iam.field_sensitivity_level"],
  "custom.form_draft_days": ["custom.form_draft_save"],
  "custom.form_draft_max_bytes": ["custom.form_draft_save"],
  "custom.form_draft_saves_per_hour": ["custom.form_draft_save"],
  "custom.form_redirect_domains": ["custom.form_redirect_domains", "custom.form_redirect_refusal"],
  "custom.inbound_domain": ["custom.inbound_declare", "custom.inbound_domain"],
  "custom.inbox_reminder_after_days": ["custom.inbox_remind_tick"],
  "custom.outside_invite_who": ["custom.may_invite_outside", "custom.table_share_outside"],
  "custom.protected_field_rules": ["custom.protected_field_rule"],
  "custom.provenance_retention_days": ["custom.provenance_prune", "custom.provenance_retention_days", "public.prune_high_volume_logs"],
  "custom.row_action_steps_max": ["custom._action_check"],
  "custom.row_actions_max": ["custom._action_check"],
  "custom.scope_members_admitted": ["custom.portal_admits", "custom.scope_member_reaches"],
  "custom.scopes_written_in_the_store": ["custom.context_writer", "platform._cutover_seam_apply"],
  "custom.signup_provisioning_guard": ["iam._default_organization_is_a_membership", "iam._guard_last_organization_membership"],
  "custom.table_record_ceiling": ["custom.table_capacity", "custom.table_record_ceiling"],
  "custom.table_webhooks_max": ["custom.table_webhook_declare"],
  "custom.view_record_order_max": ["custom.view_record_order_set"],
  "cutover.readiness_writes_cap": ["platform.cutover_copy_differences"],
  "data_lifecycle.policy_settling_hours": ["platform.retention_settling_interval"],
  "data_tables.older_tables_moved": ["platform._cutover_seam_apply"],
  "database.canonical_audit.refresh_enabled": ["audit.refresh_tick"],
  "database.canonical_audit.refresh_every_minutes": ["audit.refresh_tick"],
  "dated_changes.notice_hours": ["platform.dated_changes_for_attention"],
  "dated_changes.remind_days": ["platform.dated_change_create", "platform.dated_changes_for_attention"],
  "drill.finding.ai_usage_executions.bursts.repeat_burst": ["platform.drill_def__ai_usage_executions", "public.admin_spend_breakdown"],
  "drill.finding.ai_usage_executions.context_heavy.context_heavy_tokens": ["platform.drill_def__ai_usage_executions", "public.admin_spend_breakdown"],
  "drill.finding.ai_usage_executions.hogs.hog_share_pct": ["platform.drill_def__ai_usage_executions", "public.admin_spend_breakdown"],
  "drill.finding.ai_usage_executions.looped.iteration_heavy": ["platform.drill_def__ai_usage_executions", "public.admin_spend_breakdown"],
  "drill.finding.ai_usage.spikes.spike_multiplier": ["platform.drill_def__ai_usage", "public.admin_spend_breakdown"],
  "drill.groups_per_level": ["platform._drill_compile"],
  "drill.text_dimension_max_distinct": ["platform._drill_resolve"],
  "esign.campaign.batch_size": ["public.esign_campaign_generate"],
  "esign.campaign.max_audience": ["public.esign_campaign_enroll", "public.esign_create_campaign"],
  "esign.certificate.sign_payload": ["esign.generate_certificate"],
  "esign.consent.disclosure_id": ["esign._act_load"],
  "esign.consent.require_preview": ["esign._act_consent", "esign.resolve_config_snapshot"],
  "esign.delegation.allowed": ["custom._entity_custom_fields_guard", "esign._act_delegate", "esign.resolve_config_snapshot", "hr.punch_record", "public.hr_directory_list"],
  "esign.download.url_ttl_seconds": ["esign.resolve_config_snapshot"],
  "esign.expiry_days.sensitive": ["esign.resolve_config_snapshot"],
  "esign.expiry_days.standard": ["esign.resolve_config_snapshot", "platform.provision", "platform.provision_validate"],
  "esign.hash.algorithm": ["esign.resolve_config_snapshot"],
  "esign.outsider.session.ttl_minutes.esign_signer": ["esign.resolve_config_snapshot"],
  "esign.outsider.verification.default_factor.esign_signer": ["esign.resolve_config_snapshot"],
  "esign.reminder.cadence_days": ["esign.resolve_config_snapshot"],
  "esign.reminder.max_count": ["esign.resolve_config_snapshot"],
  "esign.reminder.quiet_hours": ["communication.person_notification_window", "communication.sms_notification_gate", "esign.resolve_config_snapshot"],
  "esign.retention.default_trigger": ["esign.resolve_config_snapshot"],
  "esign.signature.allow_drawn": ["esign.config_set", "esign.resolve_config_snapshot"],
  "esign.signature.allow_typed": ["esign.config_set", "esign.resolve_config_snapshot"],
  "esign.signing_order.default": ["custom._value_envelope", "platform._drill_compile", "platform._drill_question_problems", "platform._drill_resolve", "platform.drill_definition_problems", "platform.provision", "platform.provision_validate", "public.esign_create_envelope", "public.hr_directory_list"],
  "extensibility.custom_entities.max_definitions_per_org": ["platform._custom_entity_definition_guard"],
  "extensibility.custom_entities.max_records_per_definition": ["platform._custom_record_guard"],
  "extensibility.custom_fields.ai_exposure_default": ["platform.extensibility_knob"],
  "extensibility.custom_fields.enabled": ["platform.extensibility_knob"],
  "extensibility.custom_fields.max_custom_bytes_per_row": ["platform.extensibility_knob", "platform.validate_custom_row"],
  "extensibility.custom_fields.max_fields_per_target": ["platform._custom_field_definition_guard", "platform.extensibility_knob"],
  "extensibility.custom_fields.max_keys_per_row": ["platform.validate_custom_row"],
  "extensibility.custom_fields.max_option_label_chars": ["platform._custom_field_definition_guard"],
  "extensibility.custom_fields.max_options_per_select": ["platform._custom_field_definition_guard"],
  "extensibility.custom_fields.promoted_indexes_per_target": ["platform.promote_custom_field_index"],
  "extensibility.custom_fields.validation_mode": ["platform.extensibility_knob", "platform.validate_custom_row"],
  "extensibility.user_tables.history_retention_floor_days": ["history.retention_floor_days", "history.retention_floor_raise", "public.udt_dataset_row_versions_trim_scoped"],
  "hr.access.break_glass_grant_ttl_minutes": ["public.hr_break_glass"],
  "hr.access.comp_visibility_for_managers": ["public.hr_employee_profile"],
  "hr.access.employee_can_see_own_access_log": ["public.hr_access_audit_query"],
  "hr.access.manager_visibility_depth": ["hr._desired_grants_for_employment", "hr._l1_is_manager_of", "hr.capability"],
  "hr.approvals.delegation_max_depth": ["public.hr_authority_delegation_request"],
  "hr.approvals.delegation_max_horizon_days": ["public.hr_authority_delegation_request"],
  "hr.approvals.top_of_chart_approver": ["hr.can_approve"],
  "hr.employees.adjusted_service_date_rule": ["hr.rehire_service_dates", "platform.knob_write_door_for"],
  "hr.employees.contractor_directory_visible": ["iam.team_members_resolved", "public.hr_directory_list"],
  "hr.employees.directory_shows_hire_date": ["hr.employee_by_party", "public.hr_directory_list"],
  "hr.employees.directory_shows_manager": ["hr.employee_by_party", "public.hr_directory_list"],
  "hr.employees.disclosure_existence_statements": ["hr.leave_calendar", "public.hr_org_chart"],
  "hr.employees.display_name_rule": ["hr.employee_display_name"],
  "hr.employees.duplicate_scan_fields": ["public.hr_duplicate_scan"],
  "hr.employees.employee_number_format": ["hr._l1_next_employee_number"],
  "hr.employees.org_chart_history_enabled": ["public.hr_org_chart"],
  "hr.employees.position_change_requires_approval": ["public.hr_position_change"],
  "hr.employees.verification_consent_expiry_days": ["public.hr_my_verification_consents", "public.hr_verification_request_create"],
  "hr.employees.verification_letter_default_kind": ["public.hr_verification_request_create"],
  "hr.hiring.eeo_min_cell": ["hr._door_spec", "hr.eeo_aggregate"],
  "hr.jurisdiction_rules.config_violation_action": ["hr.validate_org_config"],
  "hr.jurisdiction_rules.missing_fact_behavior": ["hr.resolve_rules"],
  "hr.leave.allow_retroactive_request": ["hr.leave_wf_validate"],
  "hr.leave.balance_projection_horizon_days": ["hr.leave_project_balance"],
  "hr.leave.case_certification_due_days": ["hr.leave_case_open"],
  "hr.leave.case_return_reminder_days": ["hr._leave_lead_days"],
  "hr.leave.day_hours_basis": ["hr.leave_wf_validate"],
  "hr.leave.holiday_inside_leave": ["hr.leave_day_hours"],
  "hr.leave.request_min_notice_days": ["hr.leave_wf_validate"],
  "hr.leave.retroactive_request_max_days": ["hr.leave_wf_validate"],
  "hr.leave.who_is_out_shows_type": ["hr.leave_calendar"],
  "hr.leave.who_is_out_visible_to_peers": ["hr.leave_calendar"],
  "hr.onboarding.access_shutoff_mode": ["hr._employment_expiry", "hr.sync_membership_to_employment"],
  "hr.relations.complaint_subject_excluded_default": ["public.hr_incident_create"],
  "hr.relations.corrective_action_ack_due_days": ["public.hr_corrective_action_issue"],
  "hr.relations.incident_escalation_target": ["public.hr_incident_assign", "public.hr_incident_create"],
  "hr.time_and_attendance.attestation_due_hours_after_period_end": ["hr.timecard_attestation_sweep"],
  "hr.time_and_attendance.attestation_statement": ["hr._enroll_pay_period_rows", "hr._timecard_reject_reopen", "hr.pay_period_transition", "hr.timesheet_get"],
  "hr.time_and_attendance.employee_attestation_required": ["hr._enroll_pay_period_rows", "hr.pay_period_transition"],
  "hr.time_and_attendance.geo_required_web_punch": ["hr.punch_record"],
  "hr.time_and_attendance.ip_verification_mode": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_confirm_dismiss_seconds": ["hr._kiosk_device_config", "public.hr_kiosk_punch"],
  "hr.time_and_attendance.kiosk_cross_location_punch": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_enabled": ["public.hr_kiosk_claim_pairing"],
  "hr.time_and_attendance.kiosk_heartbeat_seconds": ["hr._kiosk_device_config"],
  "hr.time_and_attendance.kiosk_lockout_minutes": ["hr.verify_employment_pin"],
  "hr.time_and_attendance.kiosk_max_clock_skew_seconds": ["hr._kiosk_device_config"],
  "hr.time_and_attendance.kiosk_pending_recheck_seconds": ["public.hr_kiosk_authenticate", "public.hr_kiosk_session_heartbeat"],
  "hr.time_and_attendance.kiosk_pin_length": ["hr._kiosk_device_config", "public.hr_kiosk_pin_reset", "public.hr_set_employment_pin"],
  "hr.time_and_attendance.kiosk_pin_max_attempts": ["hr.verify_employment_pin"],
  "hr.time_and_attendance.kiosk_session_ttl_hours": ["public.hr_kiosk_authenticate"],
  "hr.time_and_attendance.kiosk_session_ttl_minutes": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_time_authority": ["hr.punch_record"],
  "hr.time_and_attendance.max_geo_accuracy_m": ["hr.punch_record"],
  "hr.time_and_attendance.near_duplicate_punch_window_seconds": ["hr.punch_record", "hr.punch_register"],
  "hr.time_and_attendance.pairing_code_ttl_minutes": ["hr.kiosk_pairing_code_create"],
  "hr.time_and_attendance.punch_enabled_worker_classes": ["hr._time_punch_enabled_worker_classes", "hr.clock_state", "hr.punch_record", "platform.knob_delete_refuses_a_live_reader"],
  "hr.time_and_attendance.require_break_attestation": ["hr.clock_state"],
  "hr.time_and_attendance.web_punch_enabled": ["hr.clock_state", "hr.punch_record"],
  "hr.time_and_attendance.web_punch_ip_allowlist": ["hr.punch_record"],
  "hr.workflow.default_step_sla_hours": ["hr.wf_activate_step"],
  "hr.workflow.delegation_principal_retains": ["hr.wf_resolve_approvers"],
  "hr.workflow.delegation_reason_required": ["hr.wf_delegate"],
  "hr.workflow.failure_result_window_hours": ["hr._wf_apply", "hr.wf_activate_step"],
  "hr.workflow.inbox_bulk_max": ["hr.wf_bulk_decide", "hr.wf_inbox"],
  "hr.workflow.inbox_default_sort": ["hr.wf_inbox"],
  "hr.workflow.inbox_page_size": ["hr.wf_inbox", "hr.wf_pending"],
  "hr.workflow.inbox_project_tasks": ["hr._wf_project_step"],
  "hr.workflow.inbox_show_waiting": ["hr._wf_waiting_visible"],
  "hr.workflow.tick_batch_max": ["hr.wf_tick"],
  "hr.workflow.timeout_warning_lead_hours": ["hr.wf_activate_step", "hr.wf_tick"],
  "infrastructure.provisioning.defer_base_contract_fks": ["platform.provision_defer_base_fks"],
  "infrastructure.provisioning.lock_budget_ms": ["platform.provisioning_lock_budget_ms"],
  "infrastructure.provisioning.sign_in_freeze_grab_ms": ["platform.sign_in_freeze_grab_ms"],
  "marketing.run_console.run_history_page_size": ["public.admin_list_run_history"],
  "meet.share_with_attendees_after_meeting": ["communication._meet_audience_after_end", "communication._meet_audience_after_recording", "iam.audience_kinds"],
  "meet.share_with_attendees_permission": ["communication._meet_audience_after_end", "communication._meet_audience_after_recording", "iam.audience_kinds"],
  "personal_staff.reply_part_wait_seconds": ["communication.sms_reply_part_wait_seconds"],
  "platform.access.account_takeover_reason_min_chars": ["public.org_admin_take_over_account", "public.org_admin_take_over_member_records"],
  "platform.reachability.selfheal_pause": ["platform.heal_reachability_drift"],
  "platform.realtime_broadcast_enabled": ["custom.io_outbox_broadcast_stmt", "platform.realtime_topic_admits"],
  "platform.soft_delete_cascade.batch_rows": ["platform.soft_delete_cascade_step"],
  "platform.soft_delete_cascade.batch_rows_max": ["platform.soft_delete_cascade_step"],
  "platform.soft_delete_cascade.batch_target_ms": ["platform.soft_delete_cascade_step"],
  "platform.soft_delete_cascade.drain_budget_ms": ["platform.soft_delete_cascade_drain"],
  "platform.soft_delete_cascade.inline_assoc_rows": ["platform._gc_entity_associations"],
  "platform.soft_delete_cascade.inline_budget_ms": ["platform._cascade_soft_delete"],
  "platform.soft_delete_cascade.step_budget_ms": ["platform.soft_delete_cascade_drain", "platform.soft_delete_cascade_step"],
  "platform.spend_explorer.context_heavy_tokens": ["public.admin_spend_breakdown"],
  "platform.spend_explorer.hog_share_pct": ["public.admin_spend_breakdown"],
  "platform.spend_explorer.iteration_heavy": ["public.admin_spend_breakdown"],
  "platform.spend_explorer.repeat_burst": ["public.admin_spend_breakdown"],
  "platform.spend_explorer.spike_multiplier": ["public.admin_spend_breakdown"],
  "records.agent_outputs.keep_on_person_edit": ["custom._output_person_wrote", "custom._value_envelope"],
  "records.confirmation.agent_write_born_confirmed": ["platform._stamp_actor_tier"],
  "records.confirmation.confirm_on_human_edit": ["content_ir.edit_kind_instance_value"],
  "records.confirmation.table_allows_born_confirmed": ["platform._stamp_actor_tier"],
  "scheduler.alarms.failing_streak": ["scheduler.system_schedule_alarms"],
  "scheduler.alarms.overdue_grace_minutes": ["scheduler.system_schedule_alarms"],
  "seo.ai_autonomy.proposal_keyword_cap": ["seo.fn_autonomy_propose_stamp"],
  "seo.ai_autonomy.timeout_apply_cap": ["seo.fn_autonomy_apply_timed_out"],
  "seo.keyword_value.baseline_score": ["seo.fn_value_baseline", "seo.set_value_settings", "seo.value_settings_scope"],
  "seo.multi_location.max_attribution_km": ["seo.gsc_keyword_locations"],
  "seo.multi_location.single_location_fallback": ["seo.gsc_keyword_locations"],
  "seo.situational_stamps.stale_after_hours": ["seo.fn_situational_sites_owing", "seo.situational_refresh_status"],
  "table_api.exact_count_max": ["platform._drill_compile"],
  "table_api.standard_tables": ["platform.api_facts"],
  "users.guest_retention.active_days": ["public.run_guest_retention"],
  "users.guest_retention.batch_limit": ["public.run_guest_retention"],
  "users.guest_retention.idle_days": ["public.run_guest_retention"],
};

/** The database function(s) that read this key, or `null` when none do. */
export function databaseConsumersOf(fullKey: string): readonly string[] | null {
  const readers = KNOB_DATABASE_CONSUMERS[fullKey];
  return readers && readers.length > 0 ? readers : null;
}

// ───────────────────────────────────────────────────────────────────────────
// DD-211 — WHICH RUNGS the database can actually answer a key with.
//
// `overridable_by` says which rungs the PICKER offers. This says which rungs a
// reader NAMES in `p_scopes` — the only way a rung other than `organization`
// or `user` can change an answer. A key offered at a rung nobody names is a
// control that saves a value nothing honours (law 4 from the other side), which
// is what `records.confirmation.agent_write_born_confirmed`'s `agent` rung was
// until DD-211.
//
// Only keys with a call site whose feature and key are WRITTEN OUT appear here:
// a body that resolves them from variables tells us nothing, and guessing would
// be worse than saying nothing.
// ───────────────────────────────────────────────────────────────────────────

export const KNOB_RUNG_CONSUMERS: Readonly<Record<string, readonly string[]>> = {
  "hr.employees.adjusted_service_date_rule": ["employer_profile", "location", "pay_group"],
  "hr.onboarding.access_shutoff_mode": ["employer_profile", "location", "pay_group"],
  "records.agent_outputs.keep_on_person_edit": ["table"],
  "records.confirmation.agent_write_born_confirmed": ["agent", "table"],
  "records.confirmation.confirm_on_human_edit": ["table"],
  "records.confirmation.table_allows_born_confirmed": ["agent", "table"],
};

/** The rungs in `overridable_by` this key's database readers CANNOT answer with. */
export function unreachableRungsFor(
  fullKey: string,
  overridableBy: readonly string[],
): readonly string[] {
  const named = KNOB_RUNG_CONSUMERS[fullKey];
  if (!named) return [];  // nothing readable to measure against — never guess
  return overridableBy.filter(
    (kind) => !RUNGS_ALWAYS_REACHABLE.includes(kind) && !named.includes(kind),
  );
}

/** `organization` and `user` are knob_resolve's own parameters: always reachable. */
export const RUNGS_ALWAYS_REACHABLE: readonly string[] = ["organization", "user"];
