// GENERATED — do not edit by hand.
//
// Every `platform.feature_knob` key that is read from INSIDE the database (a
// function body or a view), with the function(s) that read it. Regenerate with
// `pnpm generate:knob-database-consumers`; the census itself is measured live
// from `pg_proc`/`pg_views` by `check:settings-orphans`'s IN-DB tier.
//
// WHY the settings UI needs it: a knob resolved by a trigger has no call site
// any source grep can find, so the hand-kept audit in `disposition.ts` would
// call a working setting "Not connected yet" (DD-183).

export const KNOB_DATABASE_CONSUMERS: Readonly<Record<string, readonly string[]>> = {
  "agent_exemplars.max_approved_per_agent": ["public.agx_exemplar_approve"],
  "continued_access.access_cutoff_days": ["platform.continued_access_state"],
  "continued_access.portal_enabled": ["platform.continued_access_state"],
  "continued_access.verification_consent_enabled": ["public.hr_my_verification_consents", "public.hr_verification_consent"],
  "data_lifecycle.policy_settling_hours": ["platform.retention_settling_interval"],
  "esign.campaign.batch_size": ["public.esign_campaign_generate"],
  "esign.campaign.max_audience": ["public.esign_campaign_enroll", "public.esign_create_campaign"],
  "esign.certificate.sign_payload": ["esign.generate_certificate"],
  "esign.consent.disclosure_id": ["esign._act_load"],
  "esign.consent.require_preview": ["esign._act_consent", "esign.resolve_config_snapshot"],
  "esign.delegation.allowed": ["esign._act_delegate", "esign.resolve_config_snapshot", "hr.punch_record", "public.hr_directory_list"],
  "esign.download.url_ttl_seconds": ["esign.resolve_config_snapshot"],
  "esign.expiry_days.sensitive": ["esign.resolve_config_snapshot"],
  "esign.expiry_days.standard": ["esign.resolve_config_snapshot"],
  "esign.hash.algorithm": ["esign.resolve_config_snapshot"],
  "esign.outsider.session.ttl_minutes.esign_signer": ["esign.resolve_config_snapshot"],
  "esign.outsider.verification.default_factor.esign_signer": ["esign.resolve_config_snapshot"],
  "esign.reminder.cadence_days": ["esign.resolve_config_snapshot"],
  "esign.reminder.max_count": ["esign.resolve_config_snapshot"],
  "esign.reminder.quiet_hours": ["esign.resolve_config_snapshot"],
  "esign.retention.default_trigger": ["esign.resolve_config_snapshot"],
  "esign.signature.allow_drawn": ["esign.config_set", "esign.resolve_config_snapshot"],
  "esign.signature.allow_typed": ["esign.config_set", "esign.resolve_config_snapshot"],
  "esign.signing_order.default": ["public.esign_create_envelope", "public.hr_directory_list"],
  "extensibility.custom_entities.max_definitions_per_org": ["platform._custom_entity_definition_guard"],
  "extensibility.custom_entities.max_fields_per_definition": ["platform._custom_field_definition_guard", "platform.extensibility_knob"],
  "extensibility.custom_entities.max_records_per_definition": ["platform._custom_record_guard", "platform.extensibility_knob"],
  "extensibility.custom_entities.record_name_backfill_batch": ["platform.backfill_record_names"],
  "extensibility.custom_entities.search_enabled": ["platform.extensibility_knob"],
  "extensibility.custom_fields.ai_exposure_default": ["platform.extensibility_knob"],
  "extensibility.custom_fields.enabled": ["platform.extensibility_knob"],
  "extensibility.custom_fields.max_custom_bytes_per_row": ["platform.extensibility_knob", "platform.validate_custom_row"],
  "extensibility.custom_fields.max_fields_per_target": ["platform._custom_field_definition_guard", "platform.extensibility_knob"],
  "extensibility.custom_fields.max_keys_per_row": ["platform.validate_custom_row"],
  "extensibility.custom_fields.max_option_label_chars": ["platform._custom_field_definition_guard"],
  "extensibility.custom_fields.max_options_per_select": ["platform._custom_field_definition_guard"],
  "extensibility.custom_fields.promoted_indexes_per_target": ["platform.promote_custom_field_index"],
  "extensibility.custom_fields.validation_mode": ["platform.extensibility_knob", "platform.validate_custom_row"],
  "hr.access.break_glass_grant_ttl_minutes": ["public.hr_break_glass"],
  "hr.access.comp_visibility_for_managers": ["public.hr_employee_profile"],
  "hr.access.employee_can_see_own_access_log": ["public.hr_access_audit_query"],
  "hr.access.manager_visibility_depth": ["hr._desired_grants_for_employment", "hr._l1_is_manager_of", "hr.capability"],
  "hr.approvals.delegation_max_depth": ["public.hr_authority_delegation_request"],
  "hr.approvals.delegation_max_horizon_days": ["public.hr_authority_delegation_request"],
  "hr.approvals.top_of_chart_approver": ["hr.can_approve"],
  "hr.employees.adjusted_service_date_rule": ["hr.rehire_service_dates"],
  "hr.employees.contractor_directory_visible": ["public.hr_directory_list"],
  "hr.employees.directory_shows_hire_date": ["hr.employee_by_party", "public.hr_directory_list"],
  "hr.employees.directory_shows_manager": ["hr.employee_by_party", "public.hr_directory_list"],
  "hr.employees.disclosure_existence_statements": ["hr.leave_calendar", "public.hr_org_chart"],
  "hr.employees.display_name_rule": ["public.hr_employee_update"],
  "hr.employees.duplicate_scan_fields": ["public.hr_duplicate_scan"],
  "hr.employees.employee_number_format": ["hr._l1_next_employee_number"],
  "hr.employees.org_chart_history_enabled": ["public.hr_org_chart"],
  "hr.employees.position_change_requires_approval": ["public.hr_position_change"],
  "hr.employees.verification_consent_expiry_days": ["public.hr_my_verification_consents", "public.hr_verification_request_create"],
  "hr.employees.verification_letter_default_kind": ["public.hr_verification_request_create"],
  "hr.hiring.eeo_min_cell": ["hr._door_spec", "hr.eeo_aggregate"],
  "hr.jurisdiction_rules.config_violation_action": ["hr.validate_org_config"],
  "hr.jurisdiction_rules.missing_fact_behavior": ["hr.resolve_rules"],
  "hr.leave.allow_retroactive_request": ["hr.leave_wf_validate"],
  "hr.leave.balance_projection_horizon_days": ["hr.leave_project_balance"],
  "hr.leave.case_certification_due_days": ["hr.leave_case_open"],
  "hr.leave.case_return_reminder_days": ["hr._leave_lead_days"],
  "hr.leave.day_hours_basis": ["hr.leave_wf_validate"],
  "hr.leave.holiday_inside_leave": ["hr.leave_day_hours"],
  "hr.leave.request_min_notice_days": ["hr.leave_wf_validate"],
  "hr.leave.retroactive_request_max_days": ["hr.leave_wf_validate"],
  "hr.leave.who_is_out_shows_type": ["hr.leave_calendar"],
  "hr.leave.who_is_out_visible_to_peers": ["hr.leave_calendar"],
  "hr.onboarding.access_shutoff_mode": ["hr._employment_expiry", "hr.sync_membership_to_employment"],
  "hr.relations.complaint_subject_excluded_default": ["public.hr_incident_create"],
  "hr.relations.corrective_action_ack_due_days": ["public.hr_corrective_action_issue"],
  "hr.relations.incident_escalation_target": ["public.hr_incident_assign", "public.hr_incident_create"],
  "hr.time_and_attendance.attestation_due_hours_after_period_end": ["hr.timecard_attestation_sweep"],
  "hr.time_and_attendance.attestation_statement": ["hr._enroll_pay_period_rows", "hr._timecard_reject_reopen", "hr.pay_period_transition", "hr.timesheet_get"],
  "hr.time_and_attendance.employee_attestation_required": ["hr._enroll_pay_period_rows", "hr.pay_period_transition"],
  "hr.time_and_attendance.geo_required_web_punch": ["hr.punch_record"],
  "hr.time_and_attendance.ip_verification_mode": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_confirm_dismiss_seconds": ["hr._kiosk_device_config", "public.hr_kiosk_punch"],
  "hr.time_and_attendance.kiosk_cross_location_punch": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_enabled": ["public.hr_kiosk_claim_pairing"],
  "hr.time_and_attendance.kiosk_heartbeat_seconds": ["hr._kiosk_device_config"],
  "hr.time_and_attendance.kiosk_lockout_minutes": ["hr.verify_employment_pin"],
  "hr.time_and_attendance.kiosk_max_clock_skew_seconds": ["hr._kiosk_device_config"],
  "hr.time_and_attendance.kiosk_pending_recheck_seconds": ["public.hr_kiosk_authenticate", "public.hr_kiosk_session_heartbeat"],
  "hr.time_and_attendance.kiosk_pin_length": ["hr._kiosk_device_config", "public.hr_kiosk_pin_reset", "public.hr_set_employment_pin"],
  "hr.time_and_attendance.kiosk_pin_max_attempts": ["hr.verify_employment_pin"],
  "hr.time_and_attendance.kiosk_session_ttl_hours": ["public.hr_kiosk_authenticate"],
  "hr.time_and_attendance.kiosk_session_ttl_minutes": ["hr.punch_record"],
  "hr.time_and_attendance.kiosk_time_authority": ["hr.punch_record"],
  "hr.time_and_attendance.max_geo_accuracy_m": ["hr.punch_record"],
  "hr.time_and_attendance.near_duplicate_punch_window_seconds": ["hr.punch_record", "hr.punch_register"],
  "hr.time_and_attendance.pairing_code_ttl_minutes": ["hr.kiosk_pairing_code_create"],
  "hr.time_and_attendance.punch_enabled_worker_classes": ["hr.clock_state", "hr.punch_record"],
  "hr.time_and_attendance.require_break_attestation": ["hr.clock_state"],
  "hr.time_and_attendance.web_punch_enabled": ["hr.clock_state", "hr.punch_record"],
  "hr.time_and_attendance.web_punch_ip_allowlist": ["hr.punch_record"],
  "hr.time_and_attendance.web_punch_ip_verification": ["hr.punch_record"],
  "hr.workflow.default_step_sla_hours": ["hr.wf_activate_step"],
  "hr.workflow.delegation_principal_retains": ["hr.wf_resolve_approvers"],
  "hr.workflow.delegation_reason_required": ["hr.wf_delegate"],
  "hr.workflow.failure_result_window_hours": ["hr._wf_apply", "hr.wf_activate_step"],
  "hr.workflow.inbox_bulk_max": ["hr.wf_bulk_decide", "hr.wf_inbox"],
  "hr.workflow.inbox_default_sort": ["hr.wf_inbox"],
  "hr.workflow.inbox_page_size": ["hr.wf_inbox", "hr.wf_pending"],
  "hr.workflow.inbox_project_tasks": ["hr._wf_project_step"],
  "hr.workflow.inbox_show_waiting": ["hr.wf_pending"],
  "hr.workflow.tick_batch_max": ["hr.wf_tick"],
  "hr.workflow.timeout_warning_lead_hours": ["hr.wf_activate_step", "hr.wf_tick"],
  "platform.access.emergency_door_justification_min_chars": ["iam._door_min_chars"],
  "platform.access.emergency_door_ttl_minutes": ["iam._door_ttl_minutes"],
  "records.confirmation.agent_write_born_confirmed": ["platform._stamp_actor_tier"],
  "records.confirmation.confirm_on_human_edit": ["content_ir.edit_kind_instance_value"],
  "records.confirmation.table_allows_born_confirmed": ["platform._stamp_actor_tier"],
  "seo.ai_autonomy.proposal_keyword_cap": ["seo.fn_autonomy_propose_stamp"],
  "seo.ai_autonomy.timeout_apply_cap": ["seo.fn_autonomy_apply_timed_out"],
  "seo.keyword_value.baseline_score": ["seo.fn_value_baseline", "seo.set_value_settings", "seo.value_settings_scope"],
  "seo.multi_location.max_attribution_km": ["seo.gsc_keyword_locations"],
  "seo.multi_location.single_location_fallback": ["seo.gsc_keyword_locations"],
  "seo.situational_stamps.stale_after_hours": ["seo.fn_situational_sites_owing", "seo.situational_refresh_status"],
};

/** The database function(s) that read this key, or `null` when none do. */
export function databaseConsumersOf(fullKey: string): readonly string[] | null {
  const readers = KNOB_DATABASE_CONSUMERS[fullKey];
  return readers && readers.length > 0 ? readers : null;
}
