/**
 * features/files/utils/folder-conventions.ts
 *
 * Canonical folder paths for every feature that uploads on behalf of the
 * user. The rule is simple: **organize files the way a user would expect to
 * find them.** When a user opens `/files`, they should be able to
 * point at a folder and say "that's where X goes" without us explaining it.
 *
 * Two buckets:
 *
 *  1. Visible folders — real, user-facing. Files go here when the user
 *     produced them, uploaded them, or attached them to something. Names are
 *     human-readable (Title Case) because they're shown in the tree.
 *
 *  2. Hidden folders (leading `.`) — ephemeral / infrastructure files the
 *     user doesn't need to see or manage. Auto-collapsed in the UI. These
 *     should be rare; only use them for true transients (short-lived URL
 *     staging, drafts) and prefer deletion on completion.
 *
 * Every consumer migration should pick its folder from this file or add a
 * new constant here — do NOT hand-roll folder paths at call sites.
 *
 * This file is also the source of truth for the **default visibility** of
 * every folder — see `resolveDefaultVisibility` near the bottom. Callers
 * should pick visibility based on render context, not user role: anything
 * rendered on a public page (org logo, podcast cover, agent-app icon)
 * defaults to `"public"` so it gets a CDN URL; anything user-scoped
 * (chat attachment, task attachment, ephemeral temp) stays `"private"`.
 */

import type { Visibility } from "@/features/files/types";

// ---------------------------------------------------------------------------
// Static (feature-level) folders
// ---------------------------------------------------------------------------

export const CloudFolders = {
  // ── Visible / user-managed ────────────────────────────────────────────

  /** Top-level "Images" drawer. */
  IMAGES: "Images",
  /** Images pasted/attached inside a chat. */
  IMAGES_CHAT: "Images/Chat",
  /** Screenshots dragged or pasted into the app. */
  IMAGES_SCREENSHOTS: "Images/Screenshots",
  /** User avatars / profile images. */
  IMAGES_AVATARS: "Images/Avatars",
  /** Images generated by AI tools. */
  IMAGES_GENERATED: "Images/Generated",

  /** Top-level "Audio" drawer. */
  AUDIO: "Audio",
  /** User-initiated audio recordings (voice-to-text, voice pad, etc.). */
  AUDIO_RECORDINGS: "Audio/Recordings",
  /** Podcast asset uploads. */
  AUDIO_PODCASTS: "Audio/Podcasts",

  /**
   * Static app assets (sounds, hero images, model-card thumbnails, demo
   * data) owned by an admin service account and rendered globally.
   * Always public — CDN URL is the goal. Source of truth for the
   * static-asset migration (see scripts/migrate-public-assets-to-cdn.ts).
   */
  APP_ASSETS: "App Assets",

  /** Top-level documents (PDF, DOCX, etc.). */
  DOCUMENTS: "Documents",
  /** PDF-specific drawer. */
  DOCUMENTS_PDFS: "Documents/PDFs",

  /** Top-level code files (scripts, snippets). */
  CODE: "Code",
  /** Code saved via the code-editor window. */
  CODE_EDITOR: "Code/Editor",

  /** Generic AI-generated outputs. */
  GENERATED: "Generated",

  /** Files attached to agent apps, keyed by app id at runtime. */
  AGENT_APPS: "Agent Apps",

  /** Files attached to tasks, keyed by task id at runtime. */
  TASK_ATTACHMENTS: "Task Attachments",

  /** Files attached to War Room tiles, keyed by tile id at runtime. */
  WAR_ROOM: "War Room",

  /** Files dropped into a chat composer (pre-send or history). */
  CHAT_ATTACHMENTS: "Chat Attachments",

  /** Slack-imported files. */
  SLACK_IMPORTS: "Slack Imports",

  /** Web-scrape captures (HTML snapshots, exported markdown). */
  SCRAPED_CONTENT: "Scraped Content",

  // ── Shared assets / org-scoped public surfaces ─────────────────────────

  /**
   * Org-scoped shared assets — logos, hero images, anything an
   * organization renders on a public surface. Keyed by org id at
   * runtime (e.g. `Shared Assets/orgs/<org-id>`). Always public —
   * the CDN URL is the rendering target.
   */
  SHARED_ASSETS_ORGS: "Shared Assets/orgs",

  /**
   * OG / social-preview covers for HTML pages the user publishes.
   * Lives under Shared Assets so all org/public-surface previews
   * share one CDN-backed bucket.
   */
  HTML_PAGES_OG: "Shared Assets/html-pages",

  // ── App-asset subfolders ───────────────────────────────────────────────

  /**
   * Favicons rendered by prompt-app / agent-app standalone pages.
   * Always public — favicon requests are anonymous.
   */
  PROMPT_APPS_FAVICONS: "App Assets/prompt-apps/favicons",

  /**
   * Per-block assets attached to agent blocks (icons, illustrations,
   * inline media). Keyed by block id at runtime via
   * `folderForAgentBlock(blockId)`.
   */
  AGENT_BLOCKS: "Agent Apps/blocks",

  // ── Canvas / image-editor ──────────────────────────────────────────────

  /**
   * Cover images rendered on canvas social/share surfaces. Public so
   * the share-card OG image is a stable CDN URL.
   */
  CANVAS_COVERS: "Images/Canvas/Covers",

  /**
   * Source images the user is editing in the image studio. Private —
   * these are the user's working files, NOT public render targets.
   * Outputs that the user explicitly publishes land elsewhere.
   */
  IMAGES_EDITED_SOURCES: "Images/Edited/Sources",

  // ── Hidden / ephemeral ─────────────────────────────────────────────────
  // All hidden roots live under ".matrx-tmp/" so the tree has a single
  // ignorable folder rather than many. Callers that use these MUST delete
  // the file when done.

  /** Root for all ephemeral cloud-files work. Hidden in the tree. */
  TMP: ".matrx-tmp",
  /** Short-lived audio files staged for URL-based transcription. */
  TMP_TRANSCRIPTS: ".matrx-tmp/transcripts",
  /** Upload-in-progress staging (future use). */
  TMP_UPLOADS: ".matrx-tmp/uploads",

  // ── System / infrastructure ────────────────────────────────────────────
  // Owned and populated by the Python backend (not the user). These rows
  // exist in `cld_files` / `cld_folders` so they have asset IDs, but they
  // must NEVER appear in the user-facing tree.
  //
  // The Phase 1b/1c "SOCIAL_BASELINE" backfill (2026-05-16) created
  // `cld_files` rows under `system-files/variants/<file_id>/<og|thumb|tiny|page1_url>.jpg`
  // — three to four rows per source file. The cascade was cleaned up
  // server-side on 2026-05-16 (migrations 012/013); the tree RPCs now
  // exclude `parent_file_id IS NOT NULL` and `file_path LIKE
  // 'system-files/%'`. The FE keeps `isSystemPath` as a defensive guard
  // at every tree boundary (loadUserFileTree, loadFolderContents,
  // realtime middleware). See from_python/UPDATES.md §9 (2026-05-16).

  /** Root for backend-owned infrastructure files (variants, posters, etc.). */
  SYSTEM_FILES: "system-files",
  /** SOCIAL_BASELINE variant storage: og.jpg / thumb.jpg / tiny.jpg / page1_url.jpg. */
  SYSTEM_VARIANTS: "system-files/variants",
  /**
   * Backend "generations" registry root — every AI generation (image,
   * video, audio/TTS) the server materializes lands under
   * `generations/<images|video|audio>/...`. Backend-owned; mirrors the
   * server's `cld_is_system_path()` (which treats `system-files` AND
   * `generations` as system). Never shown in the user tree.
   */
  GENERATIONS: "generations",

  /**
   * Recorded audio captured by the Transcripts / voice features. As of
   * 2026-06-14 the backend relocates every `origin: "transcripts"` upload
   * here, UNDER the hidden `system-files/` root — one
   * `recording_<iso>_<rand>.webm` per capture (80+ for an active user).
   * Because it's under `system-files/`, `isSystemPath` already hides it
   * from the tree, folder views, AND Recents — no separate predicate
   * needed. Managed exclusively via the Transcripts UI (by `cld_files.id`).
   * See docs/files/transcript-recordings-system-relocation.md.
   */
  TRANSCRIPT_RECORDINGS: "system-files/transcripts/Recordings",

  /**
   * LEGACY user-namespace location for transcript recordings, before the
   * 2026-06-14 backend relocation to `system-files/transcripts/...`. Kept
   * ONLY as a defensive Recents guard: the backend is supposed to relocate
   * every `origin: "transcripts"` upload, but a straggler with correct
   * metadata was still observed landing here in prod, so we keep filtering
   * this path out of Recents until the backend hook is airtight.
   */
  TRANSCRIPT_RECORDINGS_LEGACY: "Transcripts/Recordings",

  // ── System-managed user content (browsable, but NOT in Recents) ─────────
  // Lives under USER roots (so it stays visible in the Files browser), but
  // is machine-named, high-volume, and background-produced — so it must
  // never pollute the Recents stream (your "entire reality" on open).

  /**
   * Per-tool generated image variants — `tool-images/<id>/v/<name>.jpg`,
   * multiple sizes per source. Machine-produced output, excluded from
   * Recents (see `isSystemManagedContentPath`).
   */
  TOOL_IMAGES: "tool-images",
} as const;

// ---------------------------------------------------------------------------
// Dynamic folder builders — for entity-scoped subfolders.
// ---------------------------------------------------------------------------

/**
 * Files attached to a specific task.
 *   folderForTask("abc-123") → "Task Attachments/abc-123"
 */
export function folderForTask(taskId: string): string {
  return `${CloudFolders.TASK_ATTACHMENTS}/${taskId}`;
}

/**
 * Files attached to a specific War Room tile.
 *   folderForWarRoomTile("abc-123") → "War Room/abc-123"
 */
export function folderForWarRoomTile(tileId: string): string {
  return `${CloudFolders.WAR_ROOM}/${tileId}`;
}

/**
 * Files attached to a specific chat / conversation.
 *   folderForConversation("xyz") → "Chat Attachments/xyz"
 */
export function folderForConversation(conversationId: string): string {
  return `${CloudFolders.CHAT_ATTACHMENTS}/${conversationId}`;
}

/**
 * Assets for a specific agent app (favicon, icons, etc.).
 *   folderForAgentApp("abc") → "Agent Apps/abc"
 */
export function folderForAgentApp(appId: string): string {
  return `${CloudFolders.AGENT_APPS}/${appId}`;
}

/**
 * Per-podcast episode assets.
 */
export function folderForPodcast(podcastId: string): string {
  return `${CloudFolders.AUDIO_PODCASTS}/${podcastId}`;
}

/**
 * Per-org shared assets.
 *   folderForOrg("org-abc") → "Shared Assets/orgs/org-abc"
 */
export function folderForOrg(orgId: string): string {
  return `${CloudFolders.SHARED_ASSETS_ORGS}/${orgId}`;
}

/**
 * Per-agent-block assets (icons, illustrations, attached media).
 *   folderForAgentBlock("blk_123") → "Agent Apps/blocks/blk_123"
 */
export function folderForAgentBlock(blockId: string): string {
  return `${CloudFolders.AGENT_BLOCKS}/${blockId}`;
}

// ---------------------------------------------------------------------------
// Predicates
// ---------------------------------------------------------------------------

/** True if the folder is under `.matrx-tmp/` (user-hidden). */
export function isHiddenFolder(folderPath: string): boolean {
  return (
    folderPath === CloudFolders.TMP || folderPath.startsWith(".matrx-tmp/")
  );
}

/**
 * True if `path` (a `cld_files.file_path` or `cld_folders.folder_path`)
 * points at a backend-owned system / infrastructure row that must NEVER
 * surface in the user's tree.
 *
 * Today this covers:
 *  - `system-files` / `system-files/...` — backfilled SOCIAL_BASELINE
 *    variant rows (og/thumb/tiny/page1_url) and their per-source-file
 *    folders. ~3–4 rows per uploaded image, ~10k+ for active accounts.
 *  - `generations` / `generations/...` — the backend AI-generation
 *    registry root (image/video/audio output). Mirrors the server's
 *    `cld_is_system_path()`, which treats BOTH `system-files` and
 *    `generations` as system; the tree RPC already drops these, this is
 *    the FE-side parity guard at every other tree boundary.
 *  - `.matrx-tmp` / `.matrx-tmp/...` — ephemeral staging the user
 *    shouldn't see or manage.
 *
 * The predicate is intentionally path-based (not `derivation_kind` or
 * `parent_file_id`) because the Python backfill didn't populate those
 * fields on variant rows. Once they do, we'll add data-shape signals
 * here and drop the path heuristic.
 *
 * Pass either a file path or a folder path — both follow the same
 * convention (system paths are prefix-rooted).
 */
export function isSystemPath(path: string | null | undefined): boolean {
  if (!path) return false;
  return (
    path === CloudFolders.SYSTEM_FILES ||
    path.startsWith(`${CloudFolders.SYSTEM_FILES}/`) ||
    path === CloudFolders.GENERATIONS ||
    path.startsWith(`${CloudFolders.GENERATIONS}/`) ||
    path === CloudFolders.TMP ||
    path.startsWith(`${CloudFolders.TMP}/`)
  );
}

/**
 * True when a path holds **system-managed user content** — files that
 * legitimately belong to the user and stay browsable in the Files tree,
 * but are machine-named, background-produced, and high-volume, so they
 * must never appear in the Recents stream.
 *
 * Distinct from `isSystemPath` (fully-hidden backend infra) and
 * `isGeneratedContentPath` (AI output under legacy user roots): these are
 * predefined output folders under USER roots that a user CAN open on
 * purpose but should not see flooding their first screen.
 *
 *  - `tool-images/<id>/v/...` — per-tool generated image variants.
 *  - `Transcripts/Recordings/...` — LEGACY recording location. Recordings
 *    now live under `system-files/transcripts/...` (hidden by `isSystemPath`),
 *    but the backend relocation hook has been seen to miss uploads that
 *    carry the correct `origin: "transcripts"` metadata, so we keep this
 *    legacy path as a defensive Recents guard. (Loud-recovery note: a file
 *    actually present here means a backend relocation miss.)
 */
export function isSystemManagedContentPath(
  path: string | null | undefined,
): boolean {
  if (!path) return false;
  const roots = [
    CloudFolders.TOOL_IMAGES, // "tool-images"
    CloudFolders.TRANSCRIPT_RECORDINGS_LEGACY, // "Transcripts/Recordings" (defensive)
  ];
  return roots.some((root) => path === root || path.startsWith(`${root}/`));
}

/**
 * True when a path holds system- or AI-generated content rather than something
 * the user created or uploaded by hand. Distinct from `isSystemPath` (which is
 * the backend-owned `system-files/` infra namespace): these live under USER
 * roots for legacy reasons — the Image Studio writes generated variants to
 * `Images/Generated/...` and agent-block assets land under `Agent Apps/blocks`
 * / `Images/agent-blocks`. The durable fix is migrating these writers to the
 * backend `generations/` registry root (tracked separately); until then this
 * predicate keeps that output out of Recents by path.
 */
export function isGeneratedContentPath(
  path: string | null | undefined,
): boolean {
  if (!path) return false;
  const roots = [
    CloudFolders.IMAGES_GENERATED, // "Images/Generated"
    CloudFolders.GENERATED, // "Generated"
    CloudFolders.AGENT_BLOCKS, // "Agent Apps/blocks"
    "Images/agent-blocks", // legacy agent-block image output
  ];
  return roots.some((root) => path === root || path.startsWith(`${root}/`));
}

/**
 * True when a file/folder path must be excluded from the **Recents** stream.
 * Recents is for things the user actually worked on — never background output.
 * Covers:
 *  - backend infra (`isSystemPath`: `system-files/` — which now includes
 *    transcript recordings at `system-files/transcripts/...` — `generations/`,
 *    `.matrx-tmp/`),
 *  - system/AI-generated user-root content (`isGeneratedContentPath`:
 *    `Images/Generated`, `Generated`, agent-block assets), and
 *  - system-managed user-root content (`isSystemManagedContentPath`:
 *    `tool-images` variants + the legacy `Transcripts/Recordings` guard) —
 *    high-volume machine-named files that flood Recents but stay browsable
 *    in the tree.
 */
export function isExcludedFromRecents(
  path: string | null | undefined,
): boolean {
  return (
    isSystemPath(path) ||
    isGeneratedContentPath(path) ||
    isSystemManagedContentPath(path)
  );
}

/**
 * True if the folder path matches one of our canonical conventions (either
 * visible or hidden). Useful for UI that wants to show a pretty icon next
 * to known folders.
 */
export function isConventionalFolder(folderPath: string): boolean {
  const all = Object.values(CloudFolders) as string[];
  return all.includes(folderPath);
}

// ---------------------------------------------------------------------------
// Reverse-lookup helpers — used by e.g. FileIcon to render a special badge
// for well-known folders.
// ---------------------------------------------------------------------------

/**
 * Maps a CloudFolders constant → human-friendly description for tooltips /
 * empty states. Extend as needed.
 */
export const CloudFolderDescriptions: Record<string, string> = {
  [CloudFolders.IMAGES]: "All your images, organized.",
  [CloudFolders.IMAGES_CHAT]: "Images shared in chat.",
  [CloudFolders.IMAGES_SCREENSHOTS]: "Screenshots you pasted or dragged in.",
  [CloudFolders.IMAGES_AVATARS]: "Profile pictures and avatars.",
  [CloudFolders.IMAGES_GENERATED]: "AI-generated images.",
  [CloudFolders.AUDIO]: "Audio files.",
  [CloudFolders.AUDIO_RECORDINGS]: "Voice recordings.",
  [CloudFolders.AUDIO_PODCASTS]: "Podcast assets.",
  [CloudFolders.APP_ASSETS]: "Static app assets shared across the platform.",
  [CloudFolders.DOCUMENTS]: "Documents and reports.",
  [CloudFolders.DOCUMENTS_PDFS]: "PDFs.",
  [CloudFolders.CODE]: "Code files.",
  [CloudFolders.GENERATED]: "Files produced by AI tools.",
  [CloudFolders.AGENT_APPS]: "Assets attached to your agent apps.",
  [CloudFolders.TASK_ATTACHMENTS]: "Files attached to tasks.",
  [CloudFolders.CHAT_ATTACHMENTS]: "Files shared in conversations.",
  [CloudFolders.SLACK_IMPORTS]: "Files imported from Slack.",
  [CloudFolders.SCRAPED_CONTENT]: "Captures from the web scraper.",
  [CloudFolders.SHARED_ASSETS_ORGS]: "Organization-scoped shared assets.",
  [CloudFolders.HTML_PAGES_OG]: "OG covers for HTML pages.",
  [CloudFolders.PROMPT_APPS_FAVICONS]: "Favicons for prompt-app pages.",
  [CloudFolders.AGENT_BLOCKS]: "Per-block agent app assets.",
  [CloudFolders.CANVAS_COVERS]: "Canvas social cover images.",
  [CloudFolders.IMAGES_EDITED_SOURCES]: "Source images for the image studio.",
  [CloudFolders.TMP]: "Internal temporary workspace (hidden).",
};

// ---------------------------------------------------------------------------
// Default visibility per folder
//
// Source of truth for "what visibility should this upload land with?" when
// the caller hasn't picked one explicitly. Order matters — we longest-prefix
// match against `folderPath` so e.g. `Shared Assets/feedback-images` wins
// over a generic `Shared Assets/` rule.
//
// Public defaults are for content rendered on public pages or shared
// surfaces (logos, podcasts, app icons, feedback screenshots that admin
// reviews). Private defaults are for user-scoped content (chat, task,
// ephemeral). When in doubt, default to private and let the caller opt in.
// ---------------------------------------------------------------------------

const DEFAULT_VISIBILITY_RULES: ReadonlyArray<{
  prefix: string;
  visibility: Visibility;
}> = [
  // Most-specific rules first — longest-prefix wins.
  { prefix: "Shared Assets/feedback-images", visibility: "public" },
  { prefix: CloudFolders.SHARED_ASSETS_ORGS, visibility: "public" },
  { prefix: CloudFolders.HTML_PAGES_OG, visibility: "public" },
  { prefix: CloudFolders.PROMPT_APPS_FAVICONS, visibility: "public" },
  { prefix: CloudFolders.AGENT_BLOCKS, visibility: "public" },
  { prefix: CloudFolders.CANVAS_COVERS, visibility: "public" },
  { prefix: CloudFolders.APP_ASSETS, visibility: "public" },
  { prefix: CloudFolders.IMAGES_AVATARS, visibility: "public" },
  { prefix: CloudFolders.AUDIO_PODCASTS, visibility: "public" },
  { prefix: CloudFolders.AGENT_APPS, visibility: "public" },
  { prefix: "Shared Assets", visibility: "public" },

  // IMAGES_EDITED_SOURCES is private — these are the user's working
  // source files for the image studio, not public render targets.
  { prefix: CloudFolders.IMAGES_EDITED_SOURCES, visibility: "private" },
  { prefix: CloudFolders.IMAGES_GENERATED, visibility: "private" },
  { prefix: CloudFolders.CHAT_ATTACHMENTS, visibility: "private" },
  { prefix: CloudFolders.TASK_ATTACHMENTS, visibility: "private" },
  { prefix: CloudFolders.WAR_ROOM, visibility: "private" },
  { prefix: CloudFolders.SLACK_IMPORTS, visibility: "private" },
  { prefix: CloudFolders.SCRAPED_CONTENT, visibility: "private" },
  { prefix: "Private Assets", visibility: "private" },
  { prefix: CloudFolders.TMP, visibility: "private" },
];

/**
 * Resolve the default visibility for a given folder path. Longest-prefix
 * match against `DEFAULT_VISIBILITY_RULES`; falls back to `"private"` for
 * any folder not in the table. Use at upload sites that don't have an
 * obvious context-driven choice.
 */
export function resolveDefaultVisibility(folderPath: string): Visibility {
  const normalized = folderPath.replace(/^\/+|\/+$/g, "");
  let best: { prefix: string; visibility: Visibility } | null = null;
  for (const rule of DEFAULT_VISIBILITY_RULES) {
    if (
      normalized === rule.prefix ||
      normalized.startsWith(`${rule.prefix}/`)
    ) {
      if (!best || rule.prefix.length > best.prefix.length) {
        best = rule;
      }
    }
  }
  return best?.visibility ?? "private";
}
