"use client";

/**
 * features/image-manager/components/BrandedUploadTab.tsx
 *
 * "Branded Upload" surface: drop a single high-res image and have the
 * server generate every variant we need across the app — social cover,
 * OG card, thumbnail, tiny icon, etc. Each preset (`social`, `cover`,
 * `avatar`, `logo`, `favicon`, `square`) lays down a different variant
 * mix, all written to `Images/<folder>/<uuid>/` so they show up grouped
 * in the user's Files tree.
 *
 * Variants returned by `<ImageAssetUploader>` are pushed into the
 * SelectedImagesProvider as `type: "public"` `ImageSource`s so callers
 * can immediately reference them (e.g. set the new variants as a
 * podcast cover, app logo, OG image, etc).
 */

import React, { useMemo, useState } from "react";
import {
  ChevronRight,
  Image as ImageIcon,
  type LucideIcon,
  Sparkles,
} from "lucide-react";
import { cn } from "@/lib/utils";
import {
  BottomSheet,
  BottomSheetBody,
  BottomSheetHeader,
} from "@/components/official/bottom-sheet/BottomSheet";
import {
  ImageAssetUploader,
  type ImageUploaderResult,
  type ImagePreset,
} from "@/components/official/ImageAssetUploader";
import { useSelectedImages } from "@/components/image/context/SelectedImagesProvider";

interface PresetOption {
  id: ImagePreset;
  label: string;
  description: string;
  /** Hint surfacing folder convention to the user. */
  folder: string;
  icon: LucideIcon;
  iconColor: string;
}

const PRESETS: PresetOption[] = [
  {
    id: "social",
    label: "Social",
    description:
      "Full kit — 1400² cover, 1200×630 OG card, 400² thumb, 128² tiny.",
    folder: "social",
    icon: Sparkles,
    iconColor: "text-fuchsia-500",
  },
  {
    id: "cover",
    label: "Cover",
    description: "Single 1200×630 OG / Twitter card.",
    folder: "covers",
    icon: ImageIcon,
    iconColor: "text-sky-500",
  },
  {
    id: "avatar",
    label: "Avatar",
    description: "Round-friendly 400 / 128 / 48 variants.",
    folder: "avatars",
    icon: ImageIcon,
    iconColor: "text-violet-500",
  },
  {
    id: "logo",
    label: "Logo",
    description: "App / org logo at 512 / 200 / 64.",
    folder: "logos",
    icon: ImageIcon,
    iconColor: "text-emerald-500",
  },
  {
    id: "favicon",
    label: "Favicon",
    description: "Site favicon at 192 / 64.",
    folder: "favicons",
    icon: ImageIcon,
    iconColor: "text-amber-500",
  },
  {
    id: "square",
    label: "Square",
    description: "Single 1024² square (no extra variants).",
    folder: "square",
    icon: ImageIcon,
    iconColor: "text-rose-500",
  },
];

export function BrandedUploadTab() {
  const [presetId, setPresetId] = useState<ImagePreset>("social");
  const [lastResult, setLastResult] = useState<ImageUploaderResult | null>(
    null,
  );
  const [presetSheetOpen, setPresetSheetOpen] = useState(false);
  const { addImage, clearImages, selectionMode } = useSelectedImages();

  const preset = useMemo(
    () => PRESETS.find((p) => p.id === presetId) ?? PRESETS[0],
    [presetId],
  );
  const PresetIcon = preset.icon;

  const handleComplete = (result: ImageUploaderResult | null) => {
    setLastResult(result);
    if (!result) return;

    if (selectionMode === "single") clearImages();

    const variantUrls: Array<[label: string, url: string | null]> = [
      ["primary", result.image_url ?? result.primary_url],
      ["og", result.og_image_url],
      ["thumb", result.thumbnail_url],
      ["tiny", result.tiny_url],
    ];

    for (const [label, url] of variantUrls) {
      if (!url) continue;
      addImage({
        type: "public",
        url,
        id: `branded:${result.preset}:${label}:${url}`,
        metadata: {
          title: `${preset.label} · ${label}`,
          description: `Generated by ImageAssetUploader (${result.preset})`,
          variant: label,
          preset: result.preset,
        },
      });
      if (selectionMode === "single") break;
    }
  };

  return (
    <div className="h-full overflow-auto overscroll-contain p-3 md:p-4 space-y-4">
      {/* Preset chip row */}
      <button
        type="button"
        onClick={() => setPresetSheetOpen(true)}
        className="flex min-h-[48px] w-full items-center gap-3 rounded-lg border border-border bg-card px-3 text-left md:hidden"
      >
        <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted/60">
          <PresetIcon className={cn("h-4 w-4", preset.iconColor)} />
        </span>
        <span className="min-w-0 flex-1">
          <span className="block text-sm font-semibold">{preset.label}</span>
          <span className="block truncate text-xs text-muted-foreground">
            {preset.description}
          </span>
        </span>
        <ChevronRight className="h-4 w-4 text-muted-foreground" />
      </button>

      <div className="hidden flex-wrap gap-1.5 md:flex">
        {PRESETS.map((opt) => {
          const Icon = opt.icon;
          const active = opt.id === presetId;
          return (
            <button
              key={opt.id}
              type="button"
              onClick={() => setPresetId(opt.id)}
              className={cn(
                "inline-flex items-center gap-1.5 h-7 px-2.5 rounded-full text-xs font-medium border transition-colors",
                active
                  ? "bg-primary text-primary-foreground border-primary"
                  : "bg-card border-border text-foreground hover:bg-accent",
              )}
            >
              <Icon
                className={cn("h-3 w-3", active ? "" : opt.iconColor)}
              />
              {opt.label}
            </button>
          );
        })}
      </div>

      <p className="text-xs text-muted-foreground">{preset.description}</p>

      <ImageAssetUploader
        preset={preset.id}
        folder={preset.folder}
        onComplete={handleComplete}
        label={`${preset.label} upload`}
        visibility="public"
      />

      {lastResult ? (
        <div className="rounded-lg border border-success/30 bg-success/5 px-3 py-2 text-xs text-success">
          Variants saved — added to your selection. Find them under{" "}
          <span className="font-mono">Images/{preset.folder}/&lt;uuid&gt;/</span>
          .
        </div>
      ) : null}

      <BottomSheet
        open={presetSheetOpen}
        onOpenChange={setPresetSheetOpen}
        title="Branded preset"
      >
        <BottomSheetHeader
          title="Branded preset"
          trailing={
            <button
              type="button"
              onClick={() => setPresetSheetOpen(false)}
              className="min-h-[44px] px-1 text-[15px] text-primary active:opacity-70"
            >
              Done
            </button>
          }
        />
        <BottomSheetBody className="px-4 pb-5">
          <div className="overflow-hidden rounded-xl border border-border bg-card/60">
            {PRESETS.map((opt, index) => {
              const Icon = opt.icon;
              const active = opt.id === presetId;
              return (
                <button
                  key={opt.id}
                  type="button"
                  onClick={() => {
                    setPresetId(opt.id);
                    setPresetSheetOpen(false);
                  }}
                  className={cn(
                    "flex min-h-[56px] w-full items-center gap-3 px-3 text-left",
                    index > 0 && "border-t border-border",
                    active ? "text-primary" : "text-foreground",
                  )}
                >
                  <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-muted/60">
                    <Icon className={cn("h-4 w-4", opt.iconColor)} />
                  </span>
                  <span className="min-w-0 flex-1">
                    <span className="block text-[15px] font-medium">
                      {opt.label}
                    </span>
                    <span className="block truncate text-xs text-muted-foreground">
                      {opt.description}
                    </span>
                  </span>
                  {active ? (
                    <span className="text-xs text-primary">Current</span>
                  ) : null}
                </button>
              );
            })}
          </div>
        </BottomSheetBody>
      </BottomSheet>
    </div>
  );
}
