import { chromium } from "playwright";
import { resolve } from "node:path";
import { signIn, setOrganization, sleep } from "../lib/seat-browser.mjs";
const ORIGIN = "http://reldisp2.localhost:3001";
const OUT = resolve(process.cwd(), "../common-docs/operations/for-arman/2026-09-21");
const JOBS = "af3bfff6-a255-41e5-9ac2-879d53816163";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1680, height: 1000 } });
await signIn(page, ORIGIN, process.env.AI_ADMIN_USERNAME, process.env.AI_ADMIN_PASSWORD, "admin");
await setOrganization(page, "Rincon Plumbing Co");
await page.keyboard.press("Escape");
await page.evaluate(() => { for (const id of ["#menu-group-organization","#shell-sidebar-toggle"]) { const e=document.querySelector(id); if(e instanceof HTMLInputElement && e.checked) e.click(); } });
await page.goto(`${ORIGIN}/data-v2/${JOBS}?view=kanban`, { waitUntil: "domcontentloaded", timeout: 120000 });
await sleep(11000);
console.log("selects on the page:", await page.evaluate(() => Array.from(document.querySelectorAll("select")).map(s=>({label:s.getAttribute("aria-label"), opts:Array.from(s.options).map(o=>o.textContent)}))));
const set = await page.evaluate(() => {
  const s = Array.from(document.querySelectorAll("select")).find(x => Array.from(x.options).some(o => (o.textContent??"").trim()==="Status"));
  if (!s) return false;
  const opt = Array.from(s.options).find(o => (o.textContent??"").trim()==="Status");
  const setter = Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype, "value")?.set;
  setter?.call(s, opt.value);
  s.dispatchEvent(new Event("change", { bubbles: true }));
  return true;
});
console.log("set the group-by select to Status:", set);
await sleep(12000);
await page.screenshot({ path: resolve(OUT, "reldisp-06-board-after.png") });
const t = await page.evaluate(() => document.body.innerText);
console.log("board still empty-state?", t.includes("A kanban board needs a Field"));
console.log("board carries joined customer words:", (t.match(/[A-Z][a-z]+ [A-Z][a-z]+, [A-Z][a-z]+/g)??[]).slice(0,8));
console.log("board card titles:", (t.match(/RPC-\d+/g)??[]).slice(0,6));
const i = t.indexOf("Group by");
console.log("EXCERPT:", JSON.stringify(t.slice(i, i+700)));
await browser.close();
