import { chromium } from "playwright";
import { resolve } from "node:path";
import { signIn, setOrganization, sleep } from "../lib/seat-browser.mjs";
const ORIGIN = "http://reldisp2.localhost:3001";
const OUT = resolve(process.cwd(), "../common-docs/operations/for-arman/2026-09-21");
const EXPERIMENTS = "7929e197-cba4-4128-8445-870209dd0335";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1680, height: 1000 } });
await signIn(page, ORIGIN, process.env.AI_ADMIN_USERNAME, process.env.AI_ADMIN_PASSWORD, "admin");
await setOrganization(page, "Kessler Lab for Applied Microbial Ecology");
await page.keyboard.press("Escape");
await page.evaluate(() => { for (const id of ["#menu-group-organization","#shell-sidebar-toggle"]) { const e=document.querySelector(id); if(e instanceof HTMLInputElement && e.checked) e.click(); } });
await page.goto(`${ORIGIN}/data-v2/${EXPERIMENTS}`, { waitUntil: "domcontentloaded", timeout: 120000 });
await sleep(11000);
await page.evaluate(() => { const bs=Array.from(document.querySelectorAll("button")).filter(x=>(x.textContent??"").trim()==="Settings"); bs[bs.length-1]?.click(); });
await sleep(3500);
await page.evaluate(() => { const b=Array.from(document.querySelectorAll("button")).find(x=>(x.textContent??"").trim()==="Add a field"); b?.click(); });
await sleep(4500);
await page.screenshot({ path: resolve(OUT, "reldisp-kessler-02-new-field.png") });
const t = await page.evaluate(()=>document.body.innerText);
const i = t.indexOf("What it holds");
console.log("PANEL:", JSON.stringify(t.slice(Math.max(0,i-300), i+900)));
console.log("---- selects ----", await page.evaluate(()=>Array.from(document.querySelectorAll("select")).map(s=>({label:s.getAttribute("aria-label"), opts:Array.from(s.options).map(o=>(o.textContent??"").trim())}))));
console.log("---- buttons with a kind-ish word ----");
console.table(await page.evaluate(()=>Array.from(document.querySelectorAll("button,[role='option'],[role='radio']")).map(b=>({text:(b.textContent??"").trim().slice(0,40),label:b.getAttribute("aria-label")})).filter(c=>/point|record|text|choice|link|relation/i.test(c.text+" "+(c.label??""))).slice(0,25)));
await browser.close();
