/**
 * Moved to `@ai-matrx/design-system/tap-target/ai-buttons` (P16). This path re-exports the package so existing
 * app imports keep resolving to the ONE implementation.
 */
export {
  AnthropicTapButton,
  AudioLinesTapButton,
  ByteDanceTapButton,
  CanopyTapButton,
  CerebrasTapButton,
  ClaudeTapButton,
  CodeGenerationTapButton,
  CpuTapButton,
  DeepSeekTapButton,
  ElevenLabsTapButton,
  FastinoTapButton,
  FluxTapButton,
  GeminiTapButton,
  GoogleTapButton,
  GrokTapButton,
  GroqTapButton,
  HuggingFaceTapButton,
  IdeogramTapButton,
  ImageGenerationTapButton,
  KuaishouTapButton,
  LlamaTapButton,
  LumaTapButton,
  MetaTapButton,
  MicrosoftTapButton,
  MiniMaxTapButton,
  MistralTapButton,
  MoonshotTapButton,
  NvidiaTapButton,
  OpenAITapButton,
  PerplexityTapButton,
  PowerTapButton,
  QwenTapButton,
  RecraftTapButton,
  ReplicateTapButton,
  RunwayTapButton,
  TextGenerationTapButton,
  TogetherTapButton,
  TranscriptionTapButton,
  TranslationTapButton,
  VideoGenerationTapButton,
  WanTapButton,
  WandSparklesTapButton,
  XTweetTapButton,
  XaiTapButton,
  ZaiTapButton,
} from "@ai-matrx/design-system/tap-target/ai-buttons";
export type {
  AITapButtonProps,
} from "@ai-matrx/design-system/tap-target/ai-buttons";
