/**
 * features/files/devices/honest-states.ts
 *
 * THE ONE HONEST-STATE VOCABULARY, as the browser renders it.
 *
 * The values and the TITLES are not ours to invent: they are generated by the
 * sync engine into `crates/matrx-sync/contracts/honest_states.json`
 * (matrx-local), which is the single input to SPEC-ENGINE §3.6's tables, to
 * `files.sync_mappings.state`'s CHECK constraint, and to this file. The app,
 * the tray and this browser list must all say the same sentence about the same
 * condition — that is the whole point of the enum.
 *
 * 🚨 The guard is `honest-states-parity.ts` — `pnpm check:honest-states-parity`,
 * run by CI and by the release gates, with `:self-test` proving it can still go
 * red. It diffs the values, titles and remedy actions below against the engine
 * artifact, both directions. It does NOT read the live CHECK constraint: that
 * constraint is generated from the same artifact by SPEC-SERVER's own test,
 * which is the half aidream owns.
 *
 * What IS ours: the remedy SENTENCE the browser shows, and whether the browser
 * can perform the remedy at all. Most remedies are physical acts on a machine
 * (grant a folder permission, free disk space) — for those the browser says
 * plainly which device must do it and offers no button, because a button that
 * cannot work is the dead control law 4 forbids. The daemon's own
 * `state_reason` always wins over our sentence when it is present.
 */

/** Where the browser can act, and how. */
export type RemedyKind =
  | { kind: "none" }
  /** The browser writes `desired_state = 'active'`. */
  | { kind: "resume"; label: string }
  /** Link out (plan page, etc.). */
  | { kind: "link"; label: string; href: string }
  /** Nothing the browser can do — say where it must happen. */
  | { kind: "on_device"; label: string };

export interface HonestState {
  /** The enum value written into `files.sync_mappings.state`. */
  value: string;
  /** VERBATIM from the engine artifact. Never reworded here. */
  title: string;
  /** The artifact's remedy identifier, or null. */
  remedyAction: string | null;
  /** Our fallback sentence, shown when the daemon sent no `state_reason`. */
  detail: string;
  /** What the browser offers. */
  remedy: RemedyKind;
  /** Tone for the badge. */
  tone: "neutral" | "active" | "warning" | "danger";
}

/** Where a user buys more storage (the one purchasable surface today). */
export const PLAN_PAGE_HREF = "/pricing";

const ON_DEVICE = (what: string): RemedyKind => ({
  kind: "on_device",
  label: what,
});

/**
 * Mapping-scoped states — the exact set SPEC-SERVER's CHECK is generated from
 * (SPEC-ENGINE §3.6 table (c)), plus `daemon_older_than_app`, which table (b)
 * marks "also mapping-scoped".
 */
export const MAPPING_STATES: readonly HonestState[] = [
  {
    value: "pending",
    title: "Waiting to start",
    remedyAction: null,
    detail: "This folder is registered. Sync starts when the device checks in.",
    remedy: { kind: "none" },
    tone: "neutral",
  },
  {
    value: "idle",
    title: "Up to date",
    remedyAction: null,
    detail: "Everything here matches the cloud.",
    remedy: { kind: "none" },
    tone: "active",
  },
  {
    value: "scanning",
    title: "Checking for changes",
    remedyAction: null,
    detail: "Comparing this folder against the cloud.",
    remedy: { kind: "none" },
    tone: "active",
  },
  {
    value: "syncing",
    title: "Syncing",
    remedyAction: null,
    detail: "Files are moving between this folder and the cloud.",
    remedy: { kind: "none" },
    tone: "active",
  },
  {
    value: "paused",
    title: "Paused",
    remedyAction: "resume_mapping",
    detail: "Nothing is syncing here until you resume it.",
    remedy: { kind: "resume", label: "Resume" },
    tone: "warning",
  },
  {
    value: "removing",
    title: "Removing this folder from sync",
    remedyAction: null,
    detail: "The device is unregistering this folder.",
    remedy: { kind: "none" },
    tone: "neutral",
  },
  {
    value: "removed",
    title: "Removed from sync",
    remedyAction: null,
    detail: "This folder is no longer synced. Your files were left in place.",
    remedy: { kind: "none" },
    tone: "neutral",
  },
  {
    value: "needs_conflict_resolution",
    title: "Some files need you to choose a version",
    remedyAction: "resolve_conflicts",
    detail:
      "Two versions of the same file were edited. Both copies are safe; choose which to keep in AI Matrx on that device.",
    remedy: ON_DEVICE("Resolve on the device"),
    tone: "warning",
  },
  {
    value: "root_missing",
    title: "The synced folder is missing",
    remedyAction: "relocate_folder",
    detail:
      "The folder is gone from this device — moved, renamed, or on a disk that is not attached. Nothing was deleted from the cloud.",
    remedy: ON_DEVICE("Relocate it on the device"),
    tone: "danger",
  },
  {
    value: "suspended_marker_missing",
    title: "Sync stopped: the folder marker is gone",
    remedyAction: "confirm_folder_identity",
    detail:
      "AI Matrx cannot confirm this is the same folder it was syncing, so it stopped rather than guess.",
    remedy: ON_DEVICE("Confirm the folder on the device"),
    tone: "danger",
  },
  {
    value: "suspended_mass_delete",
    title: "Sync stopped: an unusually large deletion was detected",
    remedyAction: "review_mass_delete",
    detail:
      "A large share of this folder disappeared at once. Nothing has been deleted from the cloud while you review it.",
    remedy: ON_DEVICE("Review it on the device"),
    tone: "danger",
  },
  {
    value: "suspended_disk_full",
    title: "Sync stopped: not enough free disk space",
    remedyAction: "free_disk_space",
    detail: "Downloads stopped so the disk does not fill up completely.",
    remedy: ON_DEVICE("Free space on the device"),
    tone: "danger",
  },
  {
    value: "admission_revoked",
    title: "This folder can no longer be synced",
    remedyAction: "review_admission",
    detail:
      "The folder now breaks one of the rules for a synced folder — it overlaps another mapping, sits inside another cloud service's folder, or is somewhere AI Matrx will not sync.",
    remedy: ON_DEVICE("Choose another folder on the device"),
    tone: "danger",
  },
  {
    value: "permission_denied",
    title: "AI Matrx is not allowed to read this folder",
    remedyAction: "grant_folder_access",
    detail:
      "The operating system is refusing access. Grant AI Matrx permission to this folder on that device.",
    remedy: ON_DEVICE("Grant access on the device"),
    tone: "danger",
  },
  {
    value: "watcher_exhausted",
    title:
      "Live folder watching ran out of system watches; checking on a timer",
    remedyAction: "raise_inotify_watches",
    detail:
      "Changes still sync, just on a timer instead of instantly. Raising fs.inotify.max_user_watches on that machine restores instant watching.",
    remedy: ON_DEVICE("Raise the watch limit on the device"),
    tone: "warning",
  },
  {
    value: "over_quota",
    title: "Your storage is full",
    remedyAction: "manage_storage",
    detail:
      "Uploads are paused until there is room. Downloads still work, and nothing was lost.",
    remedy: { kind: "link", label: "Get more storage", href: PLAN_PAGE_HREF },
    tone: "danger",
  },
  {
    value: "disk_low",
    title: "This disk is nearly full",
    remedyAction: "free_disk_space",
    detail: "Sync keeps going for now, but it will stop if the disk fills.",
    remedy: ON_DEVICE("Free space on the device"),
    tone: "warning",
  },
  {
    value: "polling_fallback",
    title: "Live updates unavailable, checking every minute",
    remedyAction: null,
    detail:
      "The live connection to this device is down, so changes arrive within a minute instead of instantly.",
    remedy: { kind: "none" },
    tone: "warning",
  },
  {
    value: "sign_in_needed",
    title: "Sign in to keep syncing",
    remedyAction: "sign_in",
    detail:
      "This device lost its sign-in and cannot reach your files. Open AI Matrx on it and sign in again.",
    remedy: ON_DEVICE("Sign in on the device"),
    tone: "danger",
  },
  {
    value: "signed_out",
    title: "Signed out",
    remedyAction: "sign_in",
    detail:
      "Someone signed out of AI Matrx on this device. Sync stays off until they sign back in.",
    remedy: ON_DEVICE("Sign in on the device"),
    tone: "warning",
  },
  {
    value: "credential_store_unavailable",
    title: "The system keychain is unavailable",
    remedyAction: "retry_credential_store",
    detail:
      "AI Matrx cannot reach the keychain on that device, so it cannot hold its sign-in.",
    remedy: ON_DEVICE("Unlock the keychain on the device"),
    tone: "danger",
  },
  {
    value: "offline",
    title: "Offline — retrying",
    remedyAction: "retry_now",
    detail: "This device cannot reach AI Matrx. It keeps retrying on its own.",
    remedy: { kind: "none" },
    tone: "warning",
  },
  {
    value: "daemon_older_than_app",
    title: "Sync is older than this app and is restarting",
    remedyAction: "restart_sync",
    detail: "The device is bringing its sync engine up to date by itself.",
    remedy: { kind: "none" },
    tone: "neutral",
  },
];

const BY_VALUE = new Map(MAPPING_STATES.map((s) => [s.value, s]));

/**
 * The state to render. An UNKNOWN value is never swallowed: the daemon is
 * allowed to be newer than this browser build, and a screen that silently
 * shows nothing is worse than one that says it does not recognise the word.
 */
export function describeMappingState(value: string | null): HonestState {
  if (!value)
    return {
      value: "unknown",
      title: "No state reported yet",
      remedyAction: null,
      detail: "No device has reported on this folder yet.",
      remedy: { kind: "none" },
      tone: "neutral",
    };
  return (
    BY_VALUE.get(value) ?? {
      value,
      title: `Unrecognised state: ${value}`,
      remedyAction: null,
      detail:
        "The sync engine on that device reported a state this version of the web app does not know yet. Update AI Matrx here, or read the detail the device sent.",
      remedy: { kind: "none" },
      tone: "warning",
    }
  );
}

/**
 * How long without a heartbeat before a device is "silent" (C14: the browser
 * derives this from `app_instances.last_seen` staleness; there is no
 * device-level column). Presentation threshold, reviewed 2026-09-15 — the
 * desktop heartbeats on a minute cadence, so fifteen minutes is far past any
 * normal gap without crying wolf over a laptop lid.
 */
export const DEVICE_SILENT_AFTER_MS = 15 * 60 * 1000;

/**
 * THE ONE SENTENCE A FOLDER ROW SAYS (folder-sync L5-2).
 *
 * A state is an OBSERVATION with a timestamp, and most of the titles are in
 * the present tense ("Files are moving between this folder and the cloud").
 * Rendering one of those beside a card that already says "Silent since 6 days
 * ago" puts two contradictory claims on one card — which is the screen lying,
 * even though each half came from a real column.
 *
 * So the freshness of `last_seen_at` decides the tense. Past the silence
 * threshold the row stops asserting anything in the present and says what was
 * last reported and when; the engine's own `state_reason` is dropped in that
 * case for the same reason (it is a present-tense sentence about a moment six
 * days ago). The badge is prefixed the same way, so a glance cannot mislead
 * either.
 */
export interface MappingReport {
  state: HonestState;
  /** True when the observation is too old to be spoken in the present tense. */
  stale: boolean;
  /** What the badge shows. The enum TITLE is never reworded, only prefixed. */
  badge: string;
  /** The ONE sentence under the row. */
  sentence: string;
  tone: HonestState["tone"];
}

/** "6 days", "3 hours", "12 minutes" — the age of an observation. */
function ageLabel(ms: number): string {
  const minutes = Math.max(1, Math.round(ms / 60_000));
  if (minutes < 60) return `${minutes} minute${minutes === 1 ? "" : "s"}`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours} hour${hours === 1 ? "" : "s"}`;
  const days = Math.round(hours / 24);
  return `${days} day${days === 1 ? "" : "s"}`;
}

export function describeMappingReport(input: {
  state: string | null;
  /** The daemon's own remedy sentence, when it sent one. */
  stateReason: string | null;
  /** `files.sync_mappings.last_seen_at` — when this observation was made. */
  lastSeenAt: string | null;
  /** The shared clock. */
  now: number;
}): MappingReport {
  const state = describeMappingState(input.state);
  const seenMs = input.lastSeenAt ? new Date(input.lastSeenAt).getTime() : null;
  const age = seenMs === null || Number.isNaN(seenMs) ? null : input.now - seenMs;
  const stale = age === null || age > DEVICE_SILENT_AFTER_MS;

  if (!stale)
    return {
      state,
      stale: false,
      badge: state.title,
      sentence: input.stateReason ?? state.detail,
      tone: state.tone,
    };

  if (age === null)
    return {
      state,
      stale: true,
      badge: `Last reported · ${state.title}`,
      sentence: `This device has never said when it looked at this folder, so “${state.title}” is not a claim about right now.`,
      tone: state.tone === "active" ? "warning" : state.tone,
    };

  return {
    state,
    stale: true,
    badge: `Last reported · ${state.title}`,
    sentence: `Nothing has been heard from this folder for ${ageLabel(age)}. “${state.title}” is the last thing this device reported, not what is happening now.`,
    // A present-tense "everything is fine" tone over a stale observation is
    // the same lie in colour, so an otherwise-active row goes amber.
    tone: state.tone === "active" || state.tone === "neutral" ? "warning" : state.tone,
  };
}
