import { createRequire } from "node:module";
import { execSync } from "node:child_process";
const { chromium } = createRequire("/Users/armanisadeghi/code/matrx-frontend/package.json")("playwright");
const S = process.env.S;
const TABLE = "c1aabdc0-4d94-42d4-9ddc-91b68ef9c0a7";
const PATH = `/data/${TABLE}?view=grid&sort=reset_date%3Aasc&hide=%5B%22fable%22%2C%22handoffs%22%5D`;
const login = execSync(`pnpm -s dev-login /`, { cwd: "/Users/armanisadeghi/code/matrx-frontend" }).toString().match(/http:\/\/\S+/)[0];
const host = new URL(login).origin;
const b = await chromium.launch({ headless: true });
const p = await b.newPage({ viewport: { width: 1500, height: 900 } });
p.on("pageerror", (e) => console.log("pageerror", e.message.slice(0, 160)));
await p.goto(login, { waitUntil: "domcontentloaded", timeout: 240000 });
await p.waitForTimeout(3000);
await p.goto(host + PATH, { waitUntil: "domcontentloaded", timeout: 240000 });
if (p.url().includes("__dev-walk")) { await p.getByText("Resume this preview").click(); await p.waitForTimeout(3000); }
await p.locator("tr[data-row-id]").first().waitFor({ timeout: 150000 });
await p.waitForTimeout(2500);
const read = () => p.evaluate(() => [...document.querySelectorAll("tr[data-row-id]")].map((r) => ({ id: r.getAttribute("data-row-id"), date: r.querySelector('[data-matrx-cell-col="reset_date"]')?.innerText.trim() ?? "?", who: (r.querySelector('[data-matrx-cell-col="account"]')?.innerText.replace(/\s+/g, " ").trim().slice(2, 28) ?? ""), top: Math.round(r.getBoundingClientRect().top) })));
const show = (rows) => rows.map((r, i) => `${i} ${r.id.slice(0, 8)} ${r.date} | ${r.who}`).join("\n");
const before = await read();
console.log(show(before));
await p.screenshot({ path: S + "/live-before.png" });
const head = p.locator('thead th', { hasText: "RESET DATE" }).first();
await head.click(); await p.waitForTimeout(2500);
let rows = await read();
console.log("SORTED ASC\n" + show(rows.slice(0, 8)));
const K = 5, target = rows[K];
const orig = target.date;
console.log("TARGET", K, target.id.slice(0, 8), orig);
const cell = () => p.locator(`tr[data-row-id="${target.id}"] [data-matrx-cell-col="reset_date"]`);
await cell().click();
await p.keyboard.press("Enter");
await p.waitForTimeout(600);
await p.keyboard.press("Control+a"); await p.keyboard.press("Meta+a");
await p.keyboard.type("9/1/2026 7:00 AM");
await p.keyboard.press("Enter");
// watch the row for a glide + highlight
const watch = await p.evaluate((id) => new Promise((resolve) => {
  const seen = { anim: 0, idx: [] };
  const t0 = performance.now();
  const tick = () => {
    const trs = [...document.querySelectorAll("tr[data-row-id]")];
    const i = trs.findIndex((r) => r.getAttribute("data-row-id") === id);
    if (seen.idx[seen.idx.length - 1] !== i) seen.idx.push(i);
    const tr = trs[i];
    if (tr) seen.anim = Math.max(seen.anim, tr.getAnimations().length, ...[...tr.children].map((c) => c.getAnimations().length));
    if (performance.now() - t0 < 4000) requestAnimationFrame(tick); else resolve(seen);
  };
  tick();
}), target.id);
console.log("WATCH", JSON.stringify(watch));
await p.screenshot({ path: S + "/live-after.png" });
rows = await read();
const now = rows.findIndex((r) => r.id === target.id);
console.log("AFTER EDIT idx", now, rows[now]?.date, "\n" + show(rows.slice(0, 4)));
const notice = await p.evaluate(() => document.querySelector("[data-records-undo-notice], [role=status]")?.innerText ?? "");
console.log("NOTICE", JSON.stringify(notice.slice(0, 120)));
const selected = await p.locator(`tr[data-row-id="${target.id}"] [data-matrx-cell-selected]`).count();
console.log("SELECTED after move", selected);
// Undo
await p.locator("[data-records-undo]").first().click();
await p.waitForTimeout(3000);
rows = await read();
const back = rows.findIndex((r) => r.id === target.id);
console.log("AFTER UNDO idx", back, JSON.stringify(rows[back]?.date), "orig", JSON.stringify(orig), back === K && rows[back].date === orig ? "RESTORED" : "NOT RESTORED");
await b.close();
