import { chromium } from 'playwright';
import path from 'path';
const OUT = '/Users/armanisadeghi/code/common-docs/operations/for-arman/2026-09-27/phase1-walk-2';
(async () => {
  const userDataDir = '/Users/armanisadeghi/code/matrx-frontend/.walk-profile';
  const context = await chromium.launchPersistentContext(userDataDir, { headless: true, viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  page.setDefaultTimeout(20000);
  await page.goto('http://localhost:3001/knowledge/library', { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(2000);
  await page.fill('input[placeholder*="Search Sources" i]', 'BBC News');
  await page.waitForTimeout(2000);
  await page.screenshot({ path: path.join(OUT, '07e-search-bbc.png') });
  await page.click('table tbody tr:first-child');
  await page.waitForTimeout(4000);
  await page.click('text=Attached to');
  await page.waitForTimeout(1500);
  await page.screenshot({ path: path.join(OUT, '07f-source-attached-to.png') });
  console.log('url', page.url());
  await context.close();
})();
