import { chromium } from 'playwright';
import path from 'path';
const OUT = '/Users/armanisadeghi/code/common-docs/operations/for-arman/2026-09-27/phase1-walk-2';
const BASE = 'http://localhost:3001';
(async () => {
  const userDataDir = '/Users/armanisadeghi/code/matrx-frontend/.walk-profile';
  const context = await chromium.launchPersistentContext(userDataDir, { headless: true, viewport: { width: 1440, height: 900 } });
  const page = await context.newPage();
  page.setDefaultTimeout(20000);
  await page.goto(`${BASE}/knowledge/library`, { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(2500);
  await page.click('text=Add');
  await page.waitForTimeout(500);
  await page.click('text=Paste a web address');
  await page.waitForTimeout(1000);
  const urlInput = await page.$('input[type="url"], input[placeholder*="URL" i], input[placeholder*="http" i], input[placeholder*="web address" i]');
  await urlInput.click();
  await urlInput.fill('https://example.com');
  await page.waitForTimeout(300);
  const btn = await page.$('button:has-text("Read the page")');
  const disabled = await btn.getAttribute('disabled');
  console.log('button disabled attr:', disabled);
  await btn.click({ force: true });
  console.log('clicked');
  await page.waitForTimeout(8000);
  await page.screenshot({ path: path.join(OUT, '05b-scrape-after-click.png') });
  await context.close();
})();
