// features/mandates/feature-intelligence/feature-icons.ts
//
// The icon each feature wears on the /intelligence directory — the same mark
// the app uses for that part of the product where one exists (nav-data). A
// feature missing here shows the neutral Boxes icon; add it beside its label in
// registry.ts. Never INTELLIGENCE_ICON (reserved for Intelligence itself).

import {
  AppWindow,
  Archive,
  AudioLines,
  BadgeCheck,
  BookA,
  BookOpen,
  Boxes,
  CalendarDays,
  Camera,
  ClipboardCheck,
  Clapperboard,
  Code2,
  Database,
  Eye,
  Factory,
  FileSearch,
  FileText,
  FlaskConical,
  FolderKanban,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Headphones,
  History,
  Image,
  Images,
  Laptop,
  Layers,
  Library,
  Lightbulb,
  ListTodo,
  Mail,
  MessageCircle,
  MessageSquareQuote,
  MessagesSquare,
  Mic,
  Network,
  Newspaper,
  NotepadText,
  PackagePlus,
  PanelsTopLeft,
  Plug,
  Puzzle,
  Radar,
  Repeat,
  ScanText,
  Search,
  Shapes,
  Share2,
  Smartphone,
  SquareTerminal,
  Swords,
  Table,
  TrendingUp,
  Users,
  Video,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { AGENT_ICON } from "@/components/icons/domain-icons";

const FEATURE_ICONS: Readonly<Record<string, LucideIcon>> = {
  chat: MessageCircle,
  notes: NotepadText,
  research: FileSearch,
  flashcards: Layers,
  education: GraduationCap,
  podcast: Headphones,
  marketing: TrendingUp,
  content_plan: CalendarDays,
  data: Table,
  crm: Handshake,
  sms: Smartphone,
  war_room: Swords,
  scraper: Globe,
  voice: Mic,
  transcript_studio: AudioLines,
  masterwork: BookOpen,
  commerce_intake: PackagePlus,
  product_capture: Camera,
  personal_staff: Users,
  tasks: ListTodo,
  projects: FolderKanban,
  surfaces_client: PanelsTopLeft,
  mandates: Plug,
  content_ir: Shapes,
  agent_apps: Puzzle,
  code_editor: Code2,
  messaging: Mail,
  conversation: MessagesSquare,
  ambient: Radar,
  alchemy: FlaskConical,
  dictionary: BookA,
  tool_viz: Wrench,
  orchestras: Network,
  workflow: Workflow,
  growth_loop: Repeat,
  media: Clapperboard,
  rag: Database,
  knowledge: Library,
  pdf: FileText,
  vision_interview: Lightbulb,
  hindsight: History,
  meet: Video,
  coding_session: SquareTerminal,
  proof_runs: BadgeCheck,
  distillation: FlaskConical,
  // Features with jobs but no places map yet.
  shortcut: Zap,
  app: Puzzle,
  local: Laptop,
  ner: ScanText,
  masterworks: BookOpen,
  cms: Newspaper,
  extend: AppWindow,
  google: Search,
  image_pipeline: Images,
  image: Image,
  transcripts: AudioLines,
  audio: AudioLines,
  evaluators: ClipboardCheck,
  kg: Share2,
  memory: Archive,
  observability: Eye,
  agent_factory: Factory,
  feedback: MessageSquareQuote,
  foundry: Factory,
  mermaid: GitBranch,
  orchestration: Network,
  records: Database,
  tools: Wrench,
  web: Globe,
  agents: AGENT_ICON,
};

export function featureIcon(feature: string): LucideIcon {
  return FEATURE_ICONS[feature] ?? Boxes;
}
