"use client";

/**
 * The Note tile: the REAL notes core (`NoteWorkspace` — the mode switch, the
 * note's tools, `NoteContentEditor` with its toolbar, menus, AI actions and
 * the `matrx-user/notes` agent surface, `NoteMetadataBar`, the save strip and
 * version history), in a notes instance of its own (`board-note:<tileId>`).
 *
 * Getting to a note goes through the notes feature's own paths
 * (`noteTilePlan`, ./work-sources.ts):
 *   - a new tile starts a note exactly as /notes "New note" does — a
 *     client-only draft in the Draft folder, filed under the organization the
 *     notes resolver names (it asks when none is set), with no row until the
 *     first words (so empty notes never pile up in Notes);
 *   - text to become a note (a paste, an agent's `board_add_tile`) is created
 *     at once with that content through `NotesAPI.create`, the one
 *     create-with-content path;
 *   - a draft whose page was reloaded before its first words is started again
 *     under the same id; one that was saved meanwhile is opened.
 * A NEW tile never waits on the network or on the organization: the draft is in the store (and the
 * editor on screen) on the tile's first render. Its Draft folder and its organization are settled
 * behind it (`placeAutogeneratedNote`): the active organization when one is set, else the resolver's
 * answer (it waits for boot and asks when none is set — it never picks one for the person). A
 * draft that is saved before that lands keeps the row it has; saving with no organization yet
 * fails closed (`requireOrganizationContext`).
 * Nothing here renders a note itself.
 */

import { useEffect, useEffectEvent, useRef, useState } from "react";
import { RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ErrorNotice } from "@ai-matrx/design-system";
import { useAppDispatch, useAppSelector, useAppStore } from "@/lib/redux/hooks";
import { NoteWorkspace } from "@/features/notes/components/NoteWorkspace";
import { NoteTitleField } from "@/features/notes/components/NoteTitleField";
import { useNewNoteOrganization } from "@/features/notes/hooks/useNewNoteOrganization";
import { initializeAutogeneratedNote, placeAutogeneratedNote } from "@/features/notes/redux/thunks";
import { createAutogeneratedNote } from "@/features/notes/redux/slice";
import { selectOrganizationId } from "@/lib/redux/slices/appContextSlice";
import { selectNoteById } from "@/features/notes/redux/selectors";
import { NotesAPI } from "@/features/notes/service/notesApi";
import type { ItemBodyProps, TitleFieldProps } from "./types";
import { useBoardOrganizationId } from "./board-organization";
import {
  isEntity,
  noteDraftSource,
  noteLabelFromText,
  noteSource,
  noteTilePlan,
} from "./work-sources";

/** The folder /notes files a new note in. */
const NEW_NOTE_FOLDER = "Draft";
/** The title a blank note tile carries until it is named (the catalog's `startNew`). */
const DEFAULT_TILE_TITLE = "Note";

type Failure = { reason: string; cancelled: boolean };

export function NoteItemBody({ tileId, source, title, onSource }: ItemBodyProps) {
  const dispatch = useAppDispatch();
  const store = useAppStore();
  const resolveOrganization = useNewNoteOrganization();
  const boardOrganizationId = useBoardOrganizationId();
  const instanceId = `board-note:${tileId}`;
  const plan = noteTilePlan(source);
  const noteId = plan && (plan.step === "open" || plan.step === "draft") ? plan.noteId : null;
  const record = useAppSelector((s) => (noteId ? selectNoteById(noteId)(s) : undefined));

  const [failure, setFailure] = useState<Failure | null>(null);
  const [attempt, setAttempt] = useState(0);
  // One preparation at a time per tile (StrictMode re-runs effects; refs survive).
  const preparing = useRef<string | null>(null);

  const report = (err: unknown) => {
    preparing.current = null;
    console.error("[board/note] could not prepare the note", { tileId, err });
    setFailure({ reason: err instanceof Error ? err.message : String(err), cancelled: false });
  };

  /** Start a client-only draft — the /notes "New note" path. */
  const startDraft = async (id: string, restoring = false, label?: string) => {
    // Bringing a draft back after a reload is not creating a note: it files
    // under the board's own organization and never asks which one. A NEW
    // draft still goes through the resolver (the gate asks when none is set).
    const organizationId = restoring && boardOrganizationId ? boardOrganizationId : await resolveOrganization();
    const userId = store.getState().userAuth?.id;
    if (!userId) throw new Error("Sign in before starting a note.");
    await dispatch(
      initializeAutogeneratedNote({
        id,
        userId,
        organizationId,
        instanceId,
        destination: { kind: "create", name: NEW_NOTE_FOLDER, organizationId },
        ...(label ? { label } : {}),
      }),
    ).unwrap();
  };

  const prepare = useEffectEvent(async (key: string) => {
    if (!plan || preparing.current === key) return;
    preparing.current = key;
    switch (plan.step) {
      case "create-from-seed": {
        const label = noteLabelFromText(plan.seed);
        // Filed under the board's own organization (a starter's note is the board's, never another workspace's).
        const organizationId = boardOrganizationId ?? (await resolveOrganization());
        const note = await NotesAPI.create({
          label,
          content: plan.seed,
          folder_name: NEW_NOTE_FOLDER,
          tags: [],
          organization_id: organizationId,
        });
        onSource(noteSource(source, note.id), label);
        break;
      }
      case "start-draft": {
        const id = crypto.randomUUID();
        // A tile named before its note exists (an agent's `title`) names the draft too.
        const named = title.trim() && title.trim() !== DEFAULT_TILE_TITLE ? title.trim() : undefined;
        const userId = store.getState().userAuth?.id;
        if (!userId) throw new Error("Sign in before starting a note.");
        // In the store NOW: no organization lookup, no folder read. The placement effect finishes it.
        const organizationId = selectOrganizationId(store.getState()) ?? "";
        dispatch(
          createAutogeneratedNote({
            id,
            userId,
            folder: null,
            organizationId,
            instanceId,
            ...(named ? { label: named } : {}),
          }),
        );
        onSource(noteDraftSource(source, id, named));
        break;
      }
      case "draft": {
        // Still in this session's store: nothing to do.
        if (store.getState().notes?.notes?.[plan.noteId]) break;
        // A reload: saved meanwhile → open it; never saved → start it again.
        const saved = await NotesAPI.getById(plan.noteId, { failureMode: "throw" });
        if (saved) onSource(noteSource(source, plan.noteId));
        else await startDraft(plan.noteId, true, isEntity(source, "note") ? source.meta?.label : undefined);
        break;
      }
      case "open":
        break;
    }
    preparing.current = null;
  });

  const planKey = plan
    ? plan.step === "create-from-seed"
      ? `seed:${plan.seed}`
      : plan.step === "start-draft"
        ? "new"
        : `${plan.step}:${plan.noteId}`
    : "none";
  useEffect(() => {
    // Failures land in the callback (never a synchronous state write).
    prepare(`${planKey}#${attempt}`).catch(report);
  }, [planKey, attempt]);

  // A new draft is on screen before its organization and Draft folder are settled; settle them
  // now, once per note (a person who moves a draft out of "Draft" is not sent back).
  const placed = useRef<string | null>(null);
  const needsPlacement = plan?.step === "draft" && record?._isAutogenerated === true && !record.folder_id;
  const draftOrganizationId = record?.organization_id ?? "";
  useEffect(() => {
    if (!needsPlacement || !noteId || placed.current === `${noteId}#${attempt}`) return;
    placed.current = `${noteId}#${attempt}`;
    const userId = store.getState().userAuth?.id;
    if (!userId) return;
    (async () => {
      const organizationId = draftOrganizationId || (await resolveOrganization());
      await dispatch(placeAutogeneratedNote({ id: noteId, userId, organizationId, folderName: NEW_NOTE_FOLDER })).unwrap();
    })().catch(report);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- placed ref gates the run; report/resolveOrganization are stable per mount
  }, [needsPlacement, noteId, attempt]);

  // The draft got its first words (it has a row now): the tile refers to a
  // real note from here on. And the tile is named after its note (renamed in
  // the metadata bar, the "…" menu or by an agent). One write for both, so
  // neither overwrites the other with a stale source.
  const materialized = plan?.step === "draft" && record !== undefined && record._isAutogenerated !== true;
  const label = record?.label?.trim() || null;
  const sync = useEffectEvent(() => {
    const next = materialized && plan?.step === "draft" ? noteSource(source, plan.noteId) : source;
    const nextTitle = label && label !== title ? label : undefined;
    if (next !== source || nextTitle) onSource(next, nextTitle);
  });
  useEffect(() => {
    sync();
  }, [materialized, label]);

  if (failure) {
    return (
      <div className="flex h-full flex-col bg-card p-3">
        <ErrorNotice
          size="compact"
          title={failure.cancelled ? "No workspace chosen" : "This note could not be started"}
          message={failure.reason}
          operation="Start a note on the board"
          actions={
            <Button icon={<RotateCcw />} variant="outline" onClick={() => {
                setFailure(null);
                setAttempt((n) => n + 1);
              }}>
              Try again
            </Button>
          }
        />
      </div>
    );
  }

  const ready = plan?.step === "open" || (plan?.step === "draft" && record !== undefined);
  if (!noteId || !ready) {
    return (
      <div className="flex h-full flex-col gap-2 bg-card px-4 py-3" aria-busy="true" aria-label="Starting the note">
        <div className="h-3.5 w-2/3 animate-pulse rounded bg-muted" />
        <div className="h-3 w-full animate-pulse rounded bg-muted" />
        <div className="h-3 w-5/6 animate-pulse rounded bg-muted" />
        <div className="h-3 w-1/2 animate-pulse rounded bg-muted" />
      </div>
    );
  }

  // The tile's header names the note (NoteTileTitle) — the note leaves its own title out.
  return <NoteWorkspace instanceId={instanceId} noteId={noteId} title="host" />;
}

/**
 * The Note tile's header title: the note's own click-to-rename title once the
 * note is in the store (a rename there renames the note, and the body's label
 * sync names the tile); the plain tile title until then.
 */
export function NoteTileTitle({ source, title }: TitleFieldProps) {
  const plan = noteTilePlan(source);
  const noteId = plan && (plan.step === "open" || plan.step === "draft") ? plan.noteId : null;
  const loaded = useAppSelector((s) => (noteId ? selectNoteById(noteId)(s) !== undefined : false));
  if (!noteId || !loaded) return <p className="truncate text-sm font-medium text-foreground">{title}</p>;
  // Clipped: in a narrow header the field shrinks, never paints over the chips beside it.
  return (
    <div className="flex min-w-0 flex-1 overflow-hidden">
      <NoteTitleField noteId={noteId} className="-ml-1" />
    </div>
  );
}

