/**
 * types-freshness — the single biggest check. The generated
 * `types/database.types.ts` IS the frontend's schema assumption; if it drifts
 * from the live DB, every typed query is silently lying.
 *
 * Compares the generated Tables (per schema the FE generates) against the live
 * snapshot:
 *   • live table absent from the generated types  → STALE   (regenerate)
 *   • generated table absent from the live DB      → ORPHAN  (moved/dropped → regenerate)
 *   • a whole live+exposed schema the FE never generates → coverage gap
 *
 * CRITICAL: database.types.ts is AUTOGENERATED. Every finding carries that flag
 * so the report screams "do NOT hand-edit — run `pnpm db-types`." Hand-editing
 * the file is worthless: the next `pnpm db-types` overwrites it. The DB is the
 * source of truth.
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { registerCheck } from "../context";
import { classifyGenerated } from "../generated-files";
import { parseGeneratedTypes } from "../db-types-parse";
import type { Context, Finding } from "../types";

const TYPES_REL = "types/database.types.ts";

function check(ctx: Context): Finding[] {
  const { snapshot: snap } = ctx;
  // Degraded snapshots (derived FROM the types) can't judge the types — skip.
  if (snap.provenance === "none" || snap.provenance === "db-types") return [];

  const typesPath = join(ctx.root, TYPES_REL);
  if (!existsSync(typesPath)) {
    return [
      {
        check: "types-freshness",
        severity: "error",
        message: `${TYPES_REL} is missing — the FE has no generated DB types.`,
        location: TYPES_REL,
        fix: "Run `pnpm db-types`.",
        generated: classifyGenerated(TYPES_REL)!,
      },
    ];
  }

  const gen = parseGeneratedTypes(readFileSync(typesPath, "utf8"));
  const info = classifyGenerated(TYPES_REL)!;
  const findings: Finding[] = [];
  const mk = (severity: "error" | "warn", message: string, fix?: string): Finding => ({
    check: "types-freshness",
    severity,
    message,
    location: TYPES_REL,
    fix,
    generated: info,
  });

  // The FE only generates the schemas in its db-types --schema list; judge those.
  for (const schema of [...ctx.dbTypesSchemas].sort()) {
    const liveTables = snap.tables.get(schema);
    const genTables = gen.tables.get(schema) ?? new Set<string>();

    if (!liveTables || liveTables.size === 0) {
      // Schema is generated but has no live tables (dropped/renamed) — orphan whole schema.
      if (genTables.size) {
        findings.push(
          mk(
            "error",
            `schema "${schema}" is in the db-types list and present in the generated types (${genTables.size} table(s)) but has NO live tables (dropped/renamed?).`,
            `Remove \`--schema ${schema}\` from db-types if the schema is gone, then run \`pnpm db-types\`.`,
          ),
        );
      }
      continue;
    }

    if (genTables.size === 0) {
      findings.push(
        mk(
          "error",
          `schema "${schema}" has ${liveTables.size} live table(s) but is ENTIRELY MISSING from the generated types.`,
          "Run `pnpm db-types` (the types are stale or the schema was just added).",
        ),
      );
      continue;
    }

    for (const t of [...liveTables].sort())
      if (!genTables.has(t))
        findings.push(mk("error", `live table "${schema}.${t}" is MISSING from the generated types (stale).`, "Run `pnpm db-types`."));

    const liveViews = snap.views.get(schema) ?? new Set<string>();
    for (const t of [...genTables].sort())
      if (!liveTables.has(t) && !liveViews.has(t))
        findings.push(
          mk(
            "error",
            `generated type "${schema}.${t}" has no live table (moved/dropped) — the type is an orphan.`,
            "Run `pnpm db-types`.",
          ),
        );
  }

  // Coverage gap: a live, PostgREST-exposed schema with tables the FE never generates.
  if (snap.exposedSchemas.size)
    for (const schema of [...snap.exposedSchemas].sort()) {
      if (schema === "graphql_public") continue;
      const liveTables = snap.tables.get(schema);
      if (liveTables && liveTables.size && !ctx.dbTypesSchemas.has(schema))
        findings.push(
          mk(
            "warn",
            `live+exposed schema "${schema}" (${liveTables.size} table(s)) is NOT in the db-types --schema list — the FE generates no types for it.`,
            `Add \`--schema ${schema}\` to the db-types script, then run \`pnpm db-types\`.`,
          ),
        );
    }

  return findings;
}

registerCheck("types-freshness", check);
