/**
 * TS ↔ Python parity for the deterministic SERP metrics.
 *
 * The fixture (`__fixtures__/meta-metrics-parity.json`) is GENERATED by the
 * Python implementation (`aidream packages/matrx-scraper/matrx_scraper/
 * meta_metrics.py`) — this test proves the TypeScript evaluator produces
 * byte-identical numbers, flags, and issue strings for every sample. If this
 * test fails, one side changed without the other: fix BOTH implementations in
 * the same unit of work and regenerate the fixture (command in the fixture's
 * git history / the section-canonicalization skill).
 */

import { evaluateMetaTitle, evaluateMetaDescription } from "./metrics";
import parityFixtures from "./__fixtures__/meta-metrics-parity.json";

interface PythonFieldMetrics {
  pixel_width: number;
  character_count: number;
  desktop_ok: boolean;
  mobile_ok: boolean;
  seo_length_ok: boolean;
  too_short: boolean;
  issues: string[];
  title_ok?: boolean;
  description_ok?: boolean;
}

interface ParityFixture {
  text: string;
  title: PythonFieldMetrics;
  description: PythonFieldMetrics;
}

const fixtures = parityFixtures as ParityFixture[];

describe("meta metrics TS ↔ Python parity", () => {
  it("fixture file is non-trivial", () => {
    expect(fixtures.length).toBeGreaterThanOrEqual(10);
  });

  it.each(fixtures.map((f) => [f.text, f] as const))(
    "title metrics match Python for %j",
    (_text, fixture) => {
      const ts = evaluateMetaTitle(fixture.text);
      expect(ts.pixelWidth).toBe(fixture.title.pixel_width);
      expect(ts.charCount).toBe(fixture.title.character_count);
      expect(ts.desktopOk).toBe(fixture.title.desktop_ok);
      expect(ts.mobileOk).toBe(fixture.title.mobile_ok);
      expect(ts.seoLengthOk).toBe(fixture.title.seo_length_ok);
      expect(ts.tooShort).toBe(fixture.title.too_short);
      expect(ts.ok).toBe(fixture.title.title_ok);
      expect(ts.issues).toEqual(fixture.title.issues);
    },
  );

  it.each(fixtures.map((f) => [f.text, f] as const))(
    "description metrics match Python for %j",
    (_text, fixture) => {
      const ts = evaluateMetaDescription(fixture.text);
      expect(ts.pixelWidth).toBe(fixture.description.pixel_width);
      expect(ts.charCount).toBe(fixture.description.character_count);
      expect(ts.desktopOk).toBe(fixture.description.desktop_ok);
      expect(ts.mobileOk).toBe(fixture.description.mobile_ok);
      expect(ts.seoLengthOk).toBe(fixture.description.seo_length_ok);
      expect(ts.tooShort).toBe(fixture.description.too_short);
      expect(ts.ok).toBe(fixture.description.description_ok);
      expect(ts.issues).toEqual(fixture.description.issues);
    },
  );
});
