import { chromium } from 'playwright';
const LOGIN_URL = 'http://acquisition-frontier.localhost:3001/api/dev-login?nonce=5dd9766554c1795bdb66c7a888fc7c61&next=/masterwork';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await context.newPage();
await page.goto(LOGIN_URL, { waitUntil: 'load', timeout: 30000 });
await page.waitForTimeout(1500);
console.log('final url', page.url());
const whoami = await page.evaluate(async () => (await fetch('/api/whoami')).json());
console.log('whoami:', JSON.stringify(whoami));
await context.storageState({ path: '/private/tmp/claude-501/-Users-armanisadeghi-code/97ce06fb-fe43-496b-8c0d-08baed25bfa7/scratchpad/verify3/state.json' });
await browser.close();
