import { chromium } from 'playwright';
const RULEBOOK_URL = 'http://acquisition-frontier.localhost:3001/masterwork/03cb27e4-887b-4138-8b2b-39f6c38fcd5a';
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, storageState: '/private/tmp/claude-501/-Users-armanisadeghi-code/97ce06fb-fe43-496b-8c0d-08baed25bfa7/scratchpad/verify3/state.json' });
const page = await context.newPage();
await page.goto(RULEBOOK_URL, { waitUntil: 'load', timeout: 30000 });
await page.waitForTimeout(2000);
await page.screenshot({ path: '/private/tmp/claude-501/-Users-armanisadeghi-code/97ce06fb-fe43-496b-8c0d-08baed25bfa7/scratchpad/verify3/mobile_fullpage.png', fullPage: true });
const bodyText = await page.evaluate(() => document.body.innerText);
console.log(bodyText.slice(0, 3000));
await browser.close();
