export {
  type JsonKindSignal,
  type KindTextOptions,
  ALL_KIND_SPELLINGS,
  JSON_KIND_SPELLINGS,
  hasJsonKindKey,
  hasDetectionOnlyKindKey,
  withoutZeroWidth,
  isJson5Language,
  hasKindKey,
  hasExoticKindKey,
  hasKindKeyAnySpelling,
  isKindSlug,
  firstKindSlug,
  endsInPartialKindKey,
  withoutLeadingJsonComments,
  jsonKindSignal,
  json5AsJson,
  pythonReprAsJson,
  hasPythonKindKey,
  pythonBalancedEnd,
  normalizeKindSpellings,
  type KindSpellingFamily,
  type KindSpellingRegion,
  mayHoldKindKey,
  scanKindSpellingRegions,
  BARE_REGION_GRAMMAR_BUDGET,
  bareRegionBreaksIntoProse,
  kindObjectProseBreak,
  type GrammarDialect,
  type KindGrammarVerdict,
  kindGrammar,
  regionJson,
  closedJson,
  valueCarriesKind,
  textCarriesKind,
  isKindJsonText,
  rootKindSlug,
  isJsonFenceLanguage,
  quotedSourceRanges,
  isQuotedSourceXmlBlock,
  frontMatterEnd,
  markdownCarriesKind,
} from "@ai-matrx/content-ir/surfaces";
