// Every live mandate key (mandate.definition, deleted_at is null) on 2026-09-26,
// minus the `shortcut.*` (207) and `app.*` (96) bulk, represented by two each.
// The placement guard proves each one lands on a real registry node.
export const LIVE_MANDATE_KEYS_2026_09_26: readonly string[] = `
agent_apps.auto_create agent_apps.auto_create_lightning agent_apps.metadata
agent_apps.prompt_app_dev agent_factory.structure_builder alchemy.prepare_content
ambient.page_guidance ambient.spoken_summary audio.live_music audio.speech chat.cx_default
chat.default_new_chat chat.quick_audio_plan chat.quick_fair_news chat.quick_flashcards
chat.quick_image chat.quick_org_chart chat.quick_research chat.quick_showcase
chat.quick_writing_partner chat.response_mode_brainstorm chat.response_mode_data
chat.response_mode_research chat.response_mode_video cms.content_writing cms.publish_review
cms.seo_metadata cms.site_editing cms.theme_design code_editor.code_edit
code_editor.dynamic_context_edit code_editor.prompt_app_ui_edit
coding_session.conversation_responder coding_session.managed_translation_reference
commerce_intake.assess_value commerce_intake.extract_vision commerce_intake.grading
commerce_intake.instant_analysis commerce_intake.refute_no_value commerce_intake.research_product
commerce_intake.segment_photos commerce_intake.verify_enrichment
content_gate.section_relevance_decision content_ir.component_artisan content_ir.kind_architect
content_ir.kind_component_builder content_ir.kind_creator content_plan.branch_purpose
content_plan.brief_writer content_plan.deepen_page content_plan.entity_attacher
content_plan.entity_curator content_plan.family_namer content_plan.keyword_strategist
content_plan.merge_wave content_plan.p3_family content_plan.p4_write content_plan.p5_review
content_plan.p6_build content_plan.p6_build.about content_plan.p6_build.blog
content_plan.p6_build.comparison content_plan.p6_build.contact content_plan.p6_build.faq
content_plan.p6_build.guide content_plan.p6_build.home content_plan.p6_build.index
content_plan.p6_build.location content_plan.p6_build.pillar content_plan.p6_build.pricing
content_plan.p6_build.service content_plan.plan_reviewer content_plan.research_wave.audience_journey
content_plan.research_wave.competitor_coverage content_plan.research_wave.keyword_value
content_plan.route_picker content_plan.shape_planner conversation.action_auditor
conversation.decision_ledger conversation.drift_auditor conversation.label_agent_run
conversation.label_chat conversation.outcome_summarizer conversation.vision_extractor
conversation.vision_interviewer crm.journalist_beat_analyst crm.media_list_ranker
crm.outreach_draft_reviewer crm.outreach_personalization_coach crm.outreach_personalization_writer
crm.outreach_pitch_writer crm.outreach_recipient_shortlister crm.outreach_reply_drafter
crm.outreach_strategy crm.party_kind_judge crm.save_contact data.formula_writing data.page_guidance
data.row_action dictionary.workspace_guide distillation.timeline_distiller
distillation.timeline_unfolder docproc.content_structure education.admin_guidance
education.analytics_narrate education.audio_study_guidance education.card_image_generator
education.card_image_prompt_writer education.card_image_qc_judge education.card_image_web_source
education.classes_guidance education.creator_guidance education.data_guidance
education.exam_prep_guidance education.family_guidance education.fastfire_guidance
education.features_guidance education.flashcards_guidance education.game_guidance
education.grade_handwritten education.grade_work_guidance education.kit_title
education.learn_guidance education.levels_guidance education.library_guidance
education.media_guidance education.memory_generate education.memory_guidance education.memory_hint
education.mind_maps_guidance education.mindmap_generate education.notes_generate
education.notes_guidance education.offline_guidance education.page_guidance education.plan_generate
education.planner_guidance education.practice_oral_guidance education.practice_tests_guidance
education.progress_guidance education.quiz_deepen_item education.quiz_generate
education.quiz_generate_from_source education.quizzes_guidance education.spoken_practice_design
education.spoken_practice_design_language education.spoken_practice_grade
education.spoken_practice_grade_pronunciation education.spoken_practice_review
education.start_guidance education.study_aids_guidance education.study_pack_flashcards
education.study_pack_lessons education.study_pack_notes education.study_pack_quiz
education.study_pack_v2_flashcards education.study_pack_v2_lessons education.study_pack_v2_notes
education.study_pack_v2_quiz education.subjects_guidance education.summaries_guidance
education.summarize education.tutor_guidance education.tutor_message education.voice_tutor
evaluators.comparative_judge evaluators.rubric_judge extend.browser_chat extend.pattern_from_data
extend.structured_extractor feedback.item_triage_decision flashcards.enrich_card
flashcards.expand_card flashcards.generate_cards flashcards.generate_from_source
flashcards.grade_spoken flashcards.grade_typed_answer flashcards.help_live flashcards.helper_tts
flashcards.make_quiz_items flashcards.micro_coach flashcards.review_batch
flashcards.spoken_front_tts flashcards.verify_against_source foundry.planner
google.channel_video_plan google.desk_work google.traffic_change_explanation
growth_loop.quality_analyze growth_loop.quality_brief growth_loop.quality_crawl
growth_loop.quality_fill growth_loop.quality_measure growth_loop.quality_plan
growth_loop.quality_publish growth_loop.quality_realize growth_loop.quality_research
growth_loop.quality_serve growth_loop.quality_suggest growth_loop.quality_writeback
growth_loop.supervisor hindsight.crystallizer hindsight.replay_judge hindsight.reviewer
human_decisions.fallback_decider image_pipeline.concept image_pipeline.prompt_write
image_pipeline.qc_judge image.generate iteration.architect iteration.diagnostic iteration.root_cause
iteration.thinking_display kg.cluster_namer kg.ner_extractor knowledge.document_verifier
knowledge.qa_generator knowledge.section_summarizer local.answer_question
local.chat_persona_brainstorm local.chat_persona_code_review local.chat_persona_explain_simply
local.chat_persona_helpful local.chat_persona_spoken_replies local.chat_persona_summarize
local.chat_persona_transcript_polish local.cloud_chat local.cloud_chat_reply local.confidential_chat
local.explain_code local.extract_action_items local.improve_writing local.polish_style_action_items
local.polish_style_bullets local.polish_style_custom local.polish_style_formal
local.polish_style_light_cleanup local.polish_style_meeting_notes local.polish_style_standard
local.polish_transcript local.raw_completion local.summarize_text local.tool_calling_chat
mandate_outcome.goal_clause_extraction mandate_outcome.goal_fitness_decision mandate.goal_writer
mandates.holder_draft marketing.endowment_analysis marketing.endowment_portfolio
marketing.image_prompt marketing.page_image marketing.page_image_all_in_one marketing.video_metadata
masterwork.approach_selector masterwork.audition_judge masterwork.bad_draft
masterwork.bad_example_probe masterwork.case_oracle masterwork.checkup_auditor
masterwork.coherence_partner masterwork.conductor masterwork.corpus_cleaner
masterwork.corpus_synthesizer masterwork.counterparty masterwork.critique_distiller
masterwork.draft_triage masterwork.drip_distiller masterwork.drip_question
masterwork.elicitation_judge masterwork.exception_hunter masterwork.exemplar_distiller
masterwork.faithfulness_judge masterwork.intake_designer masterwork.markup_distiller
masterwork.meeting_scavenger masterwork.monologue_distiller masterwork.outcome_judge
masterwork.pairwise_judge masterwork.prediction_boundary masterwork.prediction_distiller
masterwork.relationship_auditor masterwork.rule_improver masterwork.rulebook_auditor
masterwork.scout masterwork.sealed_case_oracle masterwork.sort_case_writer masterwork.sort_distiller
masterwork.source_distiller masterwork.teach_back_distiller masterwork.teach_back_explainer
masterwork.template.chief_edit masterwork.template.chief_generate masterwork.template.editor
masterwork.template.maker masterwork.timeline_distiller masterwork.timeline_segmenter
masterwork.transcript_distiller masterwork.transcript_shortlister masterwork.triad_distiller
masterwork.triad_generator masterwork.understudy masterwork.unfolding_judge
masterworks.bench.a2_loop masterworks.bench.calibration_decoy masterworks.bench.consensus
masterworks.bench.extract masterworks.bench.judge masterworks.bench.panel masterworks.bench.raw_arm
masterworks.vanilla_arm.answer_from_facts masterworks.vanilla_arm.best_work
masterworks.vanilla_arm.outcome_case masterworks.vanilla_arm.professional_help
media_catalog.item_vetting_decision media.youtube_analyzer meet.live_intelligence meet.live_notes
meet.transcription meet.wrap_up memory.observer memory.reflector mermaid.diagram_editing
messaging.action_item_extraction messaging.conversation_catch_up messaging.conversation_summary
messaging.reply_drafting ner.deep_chunk_extractor ner.document_orienter ner.entity_canonicalizer
ner.finisher ner.item_proposer ner.magic_moment_detector ner.scope_proposer ner.scope_slot_filler
ner.suggestion_reviewer ner.sweep_scope_discoverer ner.sweep_scope_reference_finder
ner.sweep_value_miner notes.organizer notes.page_guidance observability.tool_trace_pattern_detection
observability.tool_trace_triage orchestras.role_describer
orchestration.tool_failure_standoff_decision org_riverside_clinic.patient_intake_summary
organization.referral_letter_drafter organization.supplier_invoice_checker
patrol.purpose_canary_20260829225707 pdf.chunk_clean_ocr_text pdf.chunk_flashcards_json
pdf.chunk_flashcards_typescript pdf.content_cleaner personal_staff.escalation
personal_staff.front_line personal.site_visit_follow_up_email podcast_client.blog_writer
podcast_client.show_notes podcast_client.topic_ideas podcast_client.web_content_extractor
podcast_client.youtube_research podcast.audience_adapter podcast.audio_dialogue
podcast.audio_english podcast.audio_persian podcast.chapter_marker podcast.content_extractor
podcast.deep_research podcast.image_v1 podcast.image_v2 podcast.image_v3 podcast.image_v4
podcast.image_v5 podcast.image_v6_feature podcast.image_v6_feature_prompt podcast.live_rewrite
podcast.metadata podcast.multihost_script podcast.post_prep_expansion
podcast.post_prep_fact_checking podcast.post_prep_summarization podcast.post_prep_translation
podcast.race_frontier podcast.relevance_gate podcast.roundtable_script podcast.script_educational
podcast.script_news podcast.script_persian podcast.solo_script podcast.title_optimizer
podcast.video_v1 podcast.video_v2 product_capture.instant_analysis projects.creation_guide
proof_runs.judge purpose.writer rag_kinds.grounded_synthesis rag.chunk_contextualizer
rag.grounded_synthesis rag.grounding_claim_extract rag.grounding_judge rag.hyde_generator
rag.image_caption rag.pdf_page_cleaner rag.query_expander records.enrichment
research_client.output_blog research_client.output_brand_profile
research_client.output_competitive_landscape research_client.output_gap_analysis
research_client.output_literature_review research_client.output_reputation_business
research_client.output_reputation_personal research_client.output_seo research_client.output_slides
research.auto_tagger research.condenser_1 research.condenser_2 research.coverage_audit
research.cross_cutting_tags research.document_assembly research.keyword_synthesis research.report
research.report_updater research.source_authority research.source_triage_decision
research.structured_page_summary research.suggest_setup research.tag_consolidation
research.topic_deep_research scraper.fact_check scraper.keyword_analysis scraper.page_fetch_verdict
seo.ai_visibility_decision_analyst seo.backlink_analysis seo.backlink_context_assessor
seo.backlink_work_planner seo.business_model_verdict seo.competitor_classifier
seo.competitor_opportunity_autopsy seo.competitor_page_autopsy seo.coverage_analyst
seo.digital_pr_reputation_adjudicator seo.evidence_workbench seo.finding_fixer
seo.guidelines_drafter seo.ideal_customer_profile seo.keyword_classifier seo.keyword_expander
seo.keyword_researcher seo.keyword_serp_intent_analyst seo.landscape_brief seo.map_author
seo.map_curation seo.money_map seo.offering_extraction seo.offering_valuation seo.page_analyzer
seo.page_intent_proposer seo.page_keyword_mapper seo.page_mapper seo.press_source_request_responder
seo.press_story_analyst seo.session_rule_writer seo.session_stamp_proposer seo.site_intake
seo.site_link_authority_router seo.site_strategist seo.starter_pack_proposer
seo.strategy.site_brief.generate seo.topic_assigner seo.topic_curation sms.owner_beta
surfaces_client.binding_mapper tasks.triage tool_viz.component_generator tools.summarize_content
transcript_studio.document_edit transcript_studio.scribe_live transcripts.clean_with_context
transcripts.clean_with_context_variable transcripts.clean_without_context vision_interview.adversary
vision_interview.amplifier vision_interview.answer_tracker vision_interview.archaeologist
vision_interview.architect vision_interview.cartographer vision_interview.requirements_author
vision_interview.scribe vision_interview.sounding_board vision_interview.transcript_cleaner
vision_interview.vision_author voice.communicator voice.gemini_live voice.intro voice.owner_beta
war_room.master war_room.room war_room.thread web.endpoint_family_judge wfparity.text_summary
workflow.complex_research.keyword_synthesis workflow.complex_research.page_summary
workflow.complex_research.report workflow.conductor workflow.deep_research.keyword_synthesis
workflow.extract_namer workflow.plan_design workflow.plan_input_kind_authoring
workflow.plan_node_type_recommender workflow.plan_notes_writer workflow.plan_output_kind_authoring
workflow.recovery_advisor workflow.run_assist_suggester workflow.step_intelligence workflow.steward
workflow.steward.agent_run workflow.steward.data workflow.steward.decision
workflow.steward.user_input workflow.wizard.agent_run zzz.fixr3_34d6aba702ba shortcut.generate_image
shortcut.summarize_content app.flashcard_generator app.city_explorer
`.split(/\s+/).filter(Boolean);
