-- content_ir_quiz_trust_envelope.sql
-- Registry correction (2026-08-25, feedback 499a460f): the quiz kinds carry
-- the per-question grounding the live Assessment Quiz agents already emit
-- (trust / depth / topic / rubric / acceptable_answers / points), plus a
-- nullable correct_answer for written_response items — the same correction
-- flashcard_set got on 2026-08-22. `ai.agent.produce` binds the KIND schema
-- above the agent's own, so the missing fields were silently deleted on every
-- kind-bound run (live proof: study_pack_v2 run 46c935e8, 10 questions, zero
-- trust keys). Re-emitted through the ONE sanctioned emitter
-- (scripts/shape/emit-kind-rows.ts). Idempotent; strictly additive
-- (every legacy field keeps its exact live type and requiredness, except
-- correct_answer/description which only WIDEN to nullable).
begin;

update content_ir.kind_definition set
  data = '[{"name":"title","required":true,"type":"string"},{"name":"description","nullable":true,"type":"string"},{"name":"questions","required":true,"type":"array"},{"name":"additionalDetails","type":"inline_object","fields":[],"open":true}]'::jsonb,
  emitted_block_schema = '{"type":"object","properties":{"title":{"type":"string"},"description":{"type":["string","null"]},"questions":{"type":"array","items":{"$ref":"#/$defs/quiz_question"}},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_set"}},"required":["__kind","title","questions"],"additionalProperties":false,"$defs":{"quiz_question":{"type":"object","properties":{"type":{"type":"string"},"question":{"type":"string"},"options":{"type":"array","items":{"type":"string"}},"correct_answer":{"type":["string","null"]},"explanation":{"type":"string"},"acceptable_answers":{"type":["array","null"],"items":{"type":"string"}},"rubric":{"type":["string","null"]},"depth":{"type":"string"},"topic":{"type":["string","null"]},"points":{"type":"number"},"trust":{"$ref":"#/$defs/trust_envelope"},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_question"}},"required":["__kind","type","question","correct_answer"],"additionalProperties":false},"trust_envelope":{"type":"object","properties":{"confidence":{"type":"string","enum":["grounded","inferred","not_in_material"],"description":"How well the claim is supported by the provided material."},"groundedIn":{"type":["string","null"],"description":"Human-readable description of the material the answer is grounded in."},"citations":{"type":"array","items":{"$ref":"#/$defs/citation"},"description":"Supporting citations."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"trust_envelope"}},"required":["__kind","confidence"],"additionalProperties":false},"citation":{"type":"object","properties":{"sourceId":{"type":"string","description":"Stable identifier of the cited source."},"sourceKind":{"type":"string","enum":["document","chunk","section","file","url","scope","transcript","web"],"description":"What kind of source this citation points at."},"locator":{"type":["string","null"],"description":"Position within the source (page, timestamp, heading)."},"excerpt":{"type":["string","null"],"description":"Short verbatim quote supporting the claim."},"title":{"type":["string","null"],"description":"Human-readable source title."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"citation"}},"required":["__kind","sourceId","sourceKind"],"additionalProperties":false}}}'::jsonb,
  emitted_json_schema = '{"type":"object","properties":{"title":{"type":"string"},"description":{"type":["string","null"]},"questions":{"type":"array","items":{"$ref":"#/$defs/quiz_question"}},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_set"}},"required":["__kind","title","questions"],"additionalProperties":false,"$defs":{"quiz_question":{"type":"object","properties":{"type":{"type":"string"},"question":{"type":"string"},"options":{"type":"array","items":{"type":"string"}},"correct_answer":{"type":["string","null"]},"explanation":{"type":"string"},"acceptable_answers":{"type":["array","null"],"items":{"type":"string"}},"rubric":{"type":["string","null"]},"depth":{"type":"string"},"topic":{"type":["string","null"]},"points":{"type":"number"},"trust":{"$ref":"#/$defs/trust_envelope"},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_question"}},"required":["__kind","type","question","correct_answer"],"additionalProperties":false},"trust_envelope":{"type":"object","properties":{"confidence":{"type":"string","enum":["grounded","inferred","not_in_material"],"description":"How well the claim is supported by the provided material."},"groundedIn":{"type":["string","null"],"description":"Human-readable description of the material the answer is grounded in."},"citations":{"type":"array","items":{"$ref":"#/$defs/citation"},"description":"Supporting citations."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"trust_envelope"}},"required":["__kind","confidence"],"additionalProperties":false},"citation":{"type":"object","properties":{"sourceId":{"type":"string","description":"Stable identifier of the cited source."},"sourceKind":{"type":"string","enum":["document","chunk","section","file","url","scope","transcript","web"],"description":"What kind of source this citation points at."},"locator":{"type":["string","null"],"description":"Position within the source (page, timestamp, heading)."},"excerpt":{"type":["string","null"],"description":"Short verbatim quote supporting the claim."},"title":{"type":["string","null"],"description":"Human-readable source title."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"citation"}},"required":["__kind","sourceId","sourceKind"],"additionalProperties":false}}}'::jsonb,
  emitted_fingerprint = '1zk-p85rs1t4ctqf'
where kind = 'quiz_set' and deleted_at is null;

update content_ir.kind_definition set
  data = '[{"name":"type","required":true,"type":"string"},{"name":"question","required":true,"type":"string"},{"name":"options","type":"string[]"},{"name":"correct_answer","required":true,"nullable":true,"type":"string"},{"name":"explanation","type":"string"},{"name":"acceptable_answers","nullable":true,"type":"string[]"},{"name":"rubric","nullable":true,"type":"string"},{"name":"depth","type":"string"},{"name":"topic","nullable":true,"type":"string"},{"name":"points","type":"number"},{"name":"trust","type":"object"},{"name":"additionalDetails","type":"inline_object","fields":[],"open":true}]'::jsonb,
  emitted_block_schema = '{"type":"object","properties":{"type":{"type":"string"},"question":{"type":"string"},"options":{"type":"array","items":{"type":"string"}},"correct_answer":{"type":["string","null"]},"explanation":{"type":"string"},"acceptable_answers":{"type":["array","null"],"items":{"type":"string"}},"rubric":{"type":["string","null"]},"depth":{"type":"string"},"topic":{"type":["string","null"]},"points":{"type":"number"},"trust":{"$ref":"#/$defs/trust_envelope"},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_question"}},"required":["__kind","type","question","correct_answer"],"additionalProperties":false,"$defs":{"trust_envelope":{"type":"object","properties":{"confidence":{"type":"string","enum":["grounded","inferred","not_in_material"],"description":"How well the claim is supported by the provided material."},"groundedIn":{"type":["string","null"],"description":"Human-readable description of the material the answer is grounded in."},"citations":{"type":"array","items":{"$ref":"#/$defs/citation"},"description":"Supporting citations."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"trust_envelope"}},"required":["__kind","confidence"],"additionalProperties":false},"citation":{"type":"object","properties":{"sourceId":{"type":"string","description":"Stable identifier of the cited source."},"sourceKind":{"type":"string","enum":["document","chunk","section","file","url","scope","transcript","web"],"description":"What kind of source this citation points at."},"locator":{"type":["string","null"],"description":"Position within the source (page, timestamp, heading)."},"excerpt":{"type":["string","null"],"description":"Short verbatim quote supporting the claim."},"title":{"type":["string","null"],"description":"Human-readable source title."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"citation"}},"required":["__kind","sourceId","sourceKind"],"additionalProperties":false}}}'::jsonb,
  emitted_json_schema = '{"type":"object","properties":{"type":{"type":"string"},"question":{"type":"string"},"options":{"type":"array","items":{"type":"string"}},"correct_answer":{"type":["string","null"]},"explanation":{"type":"string"},"acceptable_answers":{"type":["array","null"],"items":{"type":"string"}},"rubric":{"type":["string","null"]},"depth":{"type":"string"},"topic":{"type":["string","null"]},"points":{"type":"number"},"trust":{"$ref":"#/$defs/trust_envelope"},"additionalDetails":{"type":"object","properties":{},"required":[],"additionalProperties":true},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"quiz_question"}},"required":["__kind","type","question","correct_answer"],"additionalProperties":false,"$defs":{"trust_envelope":{"type":"object","properties":{"confidence":{"type":"string","enum":["grounded","inferred","not_in_material"],"description":"How well the claim is supported by the provided material."},"groundedIn":{"type":["string","null"],"description":"Human-readable description of the material the answer is grounded in."},"citations":{"type":"array","items":{"$ref":"#/$defs/citation"},"description":"Supporting citations."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"trust_envelope"}},"required":["__kind","confidence"],"additionalProperties":false},"citation":{"type":"object","properties":{"sourceId":{"type":"string","description":"Stable identifier of the cited source."},"sourceKind":{"type":"string","enum":["document","chunk","section","file","url","scope","transcript","web"],"description":"What kind of source this citation points at."},"locator":{"type":["string","null"],"description":"Position within the source (page, timestamp, heading)."},"excerpt":{"type":["string","null"],"description":"Short verbatim quote supporting the claim."},"title":{"type":["string","null"],"description":"Human-readable source title."},"__kind":{"type":"string","description":"Block discriminator for render pipeline.","const":"citation"}},"required":["__kind","sourceId","sourceKind"],"additionalProperties":false}}}'::jsonb,
  emitted_fingerprint = '1mw-1ss62s7pg2med'
where kind = 'quiz_question' and deleted_at is null;

-- quiz_set -> quiz_question edge (idempotent; may already exist)
insert into content_ir.kind_edge (parent_definition_id, field_name, child_definition_id, position, organization_id, created_by, updated_by)
select p.id, 'questions', c.id, 0, p.organization_id, p.created_by, p.created_by
from content_ir.kind_definition p, content_ir.kind_definition c
where p.kind = 'quiz_set' and p.deleted_at is null
  and c.kind = 'quiz_question' and c.deleted_at is null
  and not exists (
    select 1 from content_ir.kind_edge e
    where e.parent_definition_id = p.id and e.field_name = 'questions'
      and e.child_definition_id = c.id);

-- quiz_question -> trust_envelope edge
insert into content_ir.kind_edge (parent_definition_id, field_name, child_definition_id, position, organization_id, created_by, updated_by)
select p.id, 'trust', c.id, null, p.organization_id, p.created_by, p.created_by
from content_ir.kind_definition p, content_ir.kind_definition c
where p.kind = 'quiz_question' and p.deleted_at is null
  and c.kind = 'trust_envelope' and c.deleted_at is null
  and not exists (
    select 1 from content_ir.kind_edge e
    where e.parent_definition_id = p.id and e.field_name = 'trust'
      and e.child_definition_id = c.id);

commit;
