-- DD-169 batch 3 (dd169_batch3_public_d) — public 4/4
--
-- The 608 `authenticated`-executable SECURITY DEFINER functions B-64 left on
-- platform.definer_client_grant_grandfather run as the owner, so RLS does not apply
-- inside them and a grandfather row is the ABSENCE of a decision. This file decides
-- 102 of them: 88 DECLARED as doors (each one's body resolves the caller, and
-- gate_predicate records the literal D6 asserts is still present), and
-- 14 CLOSED (no client call site in any of the four repos, no RLS policy and no
-- security_invoker path that a client role evaluates — so the client EXECUTE grant is
-- removed outright). Every grandfather row named here is deleted; the matching entries
-- leave scripts/impl-doors/grandfather-allowlist.json in the same commit (D2c/D2d).

insert into platform.client_callable_door (schema_name, function_name, identity_args, reason, declared_by, gate_predicate)
values
 ('public','hr_verification_deliver','p_id uuid, p_method text, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_verification_deny','p_id uuid, p_basis text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_verification_generate_apply','p_letter_id uuid, p_file_id uuid, p_snapshot jsonb, p_generated_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_verification_request_create','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_wf_bulk_decide','p_step_ids uuid[], p_decision text, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_bulk_decide` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_bulk_decide'),
 ('public','hr_wf_cancel','p_instance_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_cancel` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_cancel'),
 ('public','hr_wf_decide','p_step_id uuid, p_decision text, p_reason text, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 16 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_decide` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_decide'),
 ('public','hr_wf_delegate','p_to_holder_kind text, p_to_holder_id uuid, p_action_type text, p_scope_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_delegate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_delegate'),
 ('public','hr_wf_escalate','p_step_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_escalate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_escalate'),
 ('public','hr_wf_for_target','p_target_token text, p_target_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_for_target` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_for_target'),
 ('public','hr_wf_inbox','p_scope text, p_employment_id uuid, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 25 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_inbox` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_inbox'),
 ('public','hr_wf_instance','p_instance_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_instance` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_instance'),
 ('public','hr_wf_reassign_step','p_step_id uuid, p_to_employment_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_reassign_step` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_reassign_step'),
 ('public','hr_wf_record_result','p_step_id uuid, p_result jsonb, p_verified boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_record_result` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_record_result'),
 ('public','hr_wf_resolve_failure','p_failure_id uuid, p_action text, p_note text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_resolve_failure` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_resolve_failure'),
 ('public','hr_wf_resubmit','p_instance_id uuid, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_resubmit` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_resubmit'),
 ('public','hr_wf_withdraw','p_instance_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.wf_withdraw` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.wf_withdraw'),
 ('public','industry_assign_org','p_organization_id uuid, p_industry_id uuid, p_is_primary boolean, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','industry_curator_grant','p_user uuid, p_industry uuid, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','industry_curator_revoke','p_user uuid, p_industry uuid, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','industry_set_active','p_industry uuid, p_active boolean, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','industry_unassign_org','p_organization_id uuid, p_industry_id uuid, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','industry_upsert','p_slug text, p_name text, p_facet text, p_parent_id uuid, p_default_template_id uuid, p_description text, p_sort_order integer, p_actor uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','inv_create','p_target_type text, p_target_id uuid, p_email text, p_role text, p_org_id uuid, p_invited_user_id uuid, p_expires_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','inv_get_managed','p_invitation_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 10 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam._managed_invitation` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam._managed_invitation'),
 ('public','inv_list','p_target_type text, p_target_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','inv_resend','p_invitation_id uuid, p_expires_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 11 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','inv_revoke','p_invitation_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','league_set_opt_in','p_opted_in boolean, p_display_name text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','library_grant_provenance','p_store uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','library_grant_provenance_batch','p_stores uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','list_scope_type_items','p_scope_type_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','list_scope_types','p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','list_scopes','p_org_id uuid, p_type_id uuid, p_parent_scope_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','masterwork_improvement_summary','p_mandate_keys text[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `m.mandate_key like ''masterwork.%''` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','m.mandate_key like ''masterwork.%'''),
 ('public','mbr_add','p_container_type text, p_container_id uuid, p_user_id uuid, p_organization_id uuid, p_role text, p_status text, p_metadata jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','mbr_count','p_container_type text, p_container_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','mbr_for_user','p_container_type text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 13 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','mbr_list','p_container_type text, p_container_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_org_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_org_access'),
 ('public','mbr_list_for_user','p_user_id uuid, p_container_type text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_org_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_org_access'),
 ('public','mbr_list_with_users','p_container_type text, p_container_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','mbr_remove','p_container_type text, p_container_id uuid, p_user_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','mbr_update_role','p_container_type text, p_container_id uuid, p_user_id uuid, p_role text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','org_admin_get_member','p_org_id uuid, p_user_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_org_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_org_admin'),
 ('public','org_admin_list_audit','p_org_id uuid, p_limit integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_org_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_org_admin'),
 ('public','org_admin_list_member_resources','p_org_id uuid, p_user_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_org_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_org_admin'),
 ('public','org_admin_list_members','p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_org_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_org_admin'),
 ('public','org_admin_overview','p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_org_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_org_admin'),
 ('public','org_create','p_name text, p_slug text, p_description text, p_logo_url text, p_logo_file_id uuid, p_website text, p_settings jsonb, p_abbreviation text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','org_module_custom_value_add','p_org_id uuid, p_module_key text, p_namespace text, p_value text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','org_module_custom_value_policy_set','p_org_id uuid, p_module_key text, p_members_can_add boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','org_module_custom_value_remove','p_org_id uuid, p_module_key text, p_namespace text, p_value text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','org_module_custom_values','p_org_id uuid, p_module_key text, p_namespace text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','provision_mcp_server','p_slug text, p_name text, p_vendor text, p_category mcp_server_category, p_transport mcp_transport, p_auth_strategy mcp_auth_strategy, p_endpoint_url text, p_description text, p_icon_url text, p_color text, p_docs_url text, p_website_url text, p_status mcp_server_status, p_is_official boolean, p_oauth_scopes text[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `platform.upsert_unit_purpose` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','platform.upsert_unit_purpose'),
 ('public','rag_library_list','p_limit integer, p_offset integer, p_search text, p_status_filter text, p_source_kind text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','rag_library_summary_totals','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','rag_source_has_library_grant','p_source_kind text, p_source_id text, p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; reached through other database objects only. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','reply_to_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','review_org_share','p_permission_id uuid, p_status text, p_note text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','revoke_share_link','p_link_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','sch_enqueue_manual_run','p_task_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','search_files','p_user_id uuid, p_query text, p_limit integer, p_offset integer, p_mime_prefix text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','search_scopes','p_org_id uuid, p_query text, p_type_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','search_users_intelligent','search_term text, current_user_id uuid, max_results integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','send_user_review_message','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','seo_rank_target_list_facets','p_scope text, p_org_id uuid, p_search text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.seo_rank_target_list_scoped` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.seo_rank_target_list_scoped'),
 ('public','seo_rank_target_list_scope_counts','p_search text, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','set_context_value','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 15 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','set_org_module_setting','p_org_id uuid, p_module_key text, p_members_can_add boolean, p_requires_approval boolean, p_default_permission text, p_auto_ingest boolean, p_is_scopeable boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','setting_access_request_create','p_org_id uuid, p_setting_key text, p_setting_label text, p_setting_href text, p_action_key text, p_action_payload jsonb, p_message text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','setting_access_request_decide','p_request_id uuid, p_decision text, p_note text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','shx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.shx_list_scoped` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.shx_list_scoped'),
 ('public','shx_list_scope_counts','p_search text, p_deep boolean, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','transfer_organization_ownership','org_id uuid, current_owner_id uuid, new_owner_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','udt_bulk_write','p_table_id uuid, p_operations jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','udt_change_field_type','p_table_id uuid, p_field_id uuid, p_new_type field_data_type, p_strategy text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','udt_upsert_cell','p_table_id uuid, p_row_id uuid, p_field_name text, p_value jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','udt_upsert_row','p_table_id uuid, p_row_id uuid, p_data jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','update_scope_type','p_type_id uuid, p_label_singular text, p_label_plural text, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_color text, p_slug text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','update_user_list','p_list_id uuid, p_list_name character varying, p_description text, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','update_user_table_config','p_table_id uuid, p_table_updates jsonb, p_field_updates jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `workbench.udt_dataset_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','workbench.udt_dataset_access'),
 ('public','update_user_table_default_sort','p_table_id uuid, p_sort_field text, p_sort_direction text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','update_user_table_metadata','p_table_id uuid, p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `workbench.udt_dataset_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','workbench.udt_dataset_access'),
 ('public','upsert_mcp_connection','p_server_id uuid, p_config_id uuid, p_transport mcp_transport, p_endpoint_override text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','user_can_read_data_store_via_grant','p_user uuid, p_store uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; reached through other database objects only. The caller is resolved inside the body by `public.user_can_read_via_library_grant` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.user_can_read_via_library_grant'),
 ('public','version_list','p_token text, p_id uuid, p_limit integer, p_offset integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_access'),
 ('public','version_restore','p_token text, p_id uuid, p_version integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 12 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_access'),
 ('public','version_snapshot','p_token text, p_id uuid, p_version integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_access');

-- CLOSED: no client caller anywhere. The grant goes, not just the stand-down.
revoke execute on function public."hr_wf_publish_definition"(p_definition_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_wf_request"(p_flow_key text, p_target_token text, p_target_id uuid, p_organization_id uuid, p_payload jsonb, p_subject_employment_id uuid, p_as_draft boolean, p_idempotency_key text) from public, anon, authenticated;
revoke execute on function public."hr_wf_submit"(p_instance_id uuid) from public, anon, authenticated;
revoke execute on function public."is_org_admin_for"(p_user_id uuid, p_org_id uuid) from public, anon, authenticated;
revoke execute on function public."pin_prompt_app_to_version"(p_app_id uuid, p_version_id uuid) from public, anon, authenticated;
revoke execute on function public."prune_old_versions"(p_file_id uuid, p_keep integer) from public, anon, authenticated;
revoke execute on function public."udt_dataset_row_versions_trim"() from public, anon, authenticated;
revoke execute on function public."update_user_own_feedback"(p_feedback_id uuid, p_description text, p_feedback_type text) from public, anon, authenticated;
revoke execute on function public."user_form_profile_append_to_array"(p_user_id uuid, p_column text, p_item jsonb) from public, anon, authenticated;
revoke execute on function public."user_form_profile_set_custom_field"(p_user_id uuid, p_key text, p_value jsonb) from public, anon, authenticated;
revoke execute on function public."version_current"(p_token text, p_id uuid) from public, anon, authenticated;
revoke execute on function public."version_diff"(p_token text, p_id uuid, p_from integer, p_to integer) from public, anon, authenticated;
revoke execute on function public."version_diff_current"(p_token text, p_id uuid, p_from integer) from public, anon, authenticated;
revoke execute on function public."version_prune"(p_token text, p_id uuid, p_keep integer) from public, anon, authenticated;

delete from platform.definer_client_grant_grandfather g
 where (g.schema_name, g.function_name, g.identity_args) in (
   ('public','hr_verification_deliver','p_id uuid, p_method text, p_payload jsonb'),
   ('public','hr_verification_deny','p_id uuid, p_basis text'),
   ('public','hr_verification_generate_apply','p_letter_id uuid, p_file_id uuid, p_snapshot jsonb, p_generated_at timestamp with time zone'),
   ('public','hr_verification_request_create','p_payload jsonb'),
   ('public','hr_wf_bulk_decide','p_step_ids uuid[], p_decision text, p_reason text'),
   ('public','hr_wf_cancel','p_instance_id uuid, p_reason text'),
   ('public','hr_wf_decide','p_step_id uuid, p_decision text, p_reason text, p_payload jsonb'),
   ('public','hr_wf_delegate','p_to_holder_kind text, p_to_holder_id uuid, p_action_type text, p_scope_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_reason text'),
   ('public','hr_wf_escalate','p_step_id uuid, p_reason text'),
   ('public','hr_wf_for_target','p_target_token text, p_target_id uuid'),
   ('public','hr_wf_inbox','p_scope text, p_employment_id uuid, p_filters jsonb'),
   ('public','hr_wf_instance','p_instance_id uuid'),
   ('public','hr_wf_publish_definition','p_definition_id uuid'),
   ('public','hr_wf_reassign_step','p_step_id uuid, p_to_employment_id uuid, p_reason text'),
   ('public','hr_wf_record_result','p_step_id uuid, p_result jsonb, p_verified boolean'),
   ('public','hr_wf_request','p_flow_key text, p_target_token text, p_target_id uuid, p_organization_id uuid, p_payload jsonb, p_subject_employment_id uuid, p_as_draft boolean, p_idempotency_key text'),
   ('public','hr_wf_resolve_failure','p_failure_id uuid, p_action text, p_note text'),
   ('public','hr_wf_resubmit','p_instance_id uuid, p_payload jsonb'),
   ('public','hr_wf_submit','p_instance_id uuid'),
   ('public','hr_wf_withdraw','p_instance_id uuid, p_reason text'),
   ('public','industry_assign_org','p_organization_id uuid, p_industry_id uuid, p_is_primary boolean, p_actor uuid'),
   ('public','industry_curator_grant','p_user uuid, p_industry uuid, p_actor uuid'),
   ('public','industry_curator_revoke','p_user uuid, p_industry uuid, p_actor uuid'),
   ('public','industry_set_active','p_industry uuid, p_active boolean, p_actor uuid'),
   ('public','industry_unassign_org','p_organization_id uuid, p_industry_id uuid, p_actor uuid'),
   ('public','industry_upsert','p_slug text, p_name text, p_facet text, p_parent_id uuid, p_default_template_id uuid, p_description text, p_sort_order integer, p_actor uuid'),
   ('public','inv_create','p_target_type text, p_target_id uuid, p_email text, p_role text, p_org_id uuid, p_invited_user_id uuid, p_expires_at timestamp with time zone'),
   ('public','inv_get_managed','p_invitation_id uuid'),
   ('public','inv_list','p_target_type text, p_target_id uuid'),
   ('public','inv_resend','p_invitation_id uuid, p_expires_at timestamp with time zone'),
   ('public','inv_revoke','p_invitation_id uuid'),
   ('public','is_org_admin_for','p_user_id uuid, p_org_id uuid'),
   ('public','league_set_opt_in','p_opted_in boolean, p_display_name text'),
   ('public','library_grant_provenance','p_store uuid'),
   ('public','library_grant_provenance_batch','p_stores uuid[]'),
   ('public','list_scope_type_items','p_scope_type_id uuid'),
   ('public','list_scope_types','p_org_id uuid'),
   ('public','list_scopes','p_org_id uuid, p_type_id uuid, p_parent_scope_id uuid'),
   ('public','masterwork_improvement_summary','p_mandate_keys text[]'),
   ('public','mbr_add','p_container_type text, p_container_id uuid, p_user_id uuid, p_organization_id uuid, p_role text, p_status text, p_metadata jsonb'),
   ('public','mbr_count','p_container_type text, p_container_ids uuid[]'),
   ('public','mbr_for_user','p_container_type text'),
   ('public','mbr_list','p_container_type text, p_container_id uuid'),
   ('public','mbr_list_for_user','p_user_id uuid, p_container_type text'),
   ('public','mbr_list_with_users','p_container_type text, p_container_id uuid'),
   ('public','mbr_remove','p_container_type text, p_container_id uuid, p_user_id uuid'),
   ('public','mbr_update_role','p_container_type text, p_container_id uuid, p_user_id uuid, p_role text'),
   ('public','org_admin_get_member','p_org_id uuid, p_user_id uuid'),
   ('public','org_admin_list_audit','p_org_id uuid, p_limit integer'),
   ('public','org_admin_list_member_resources','p_org_id uuid, p_user_id uuid'),
   ('public','org_admin_list_members','p_org_id uuid'),
   ('public','org_admin_overview','p_org_id uuid'),
   ('public','org_create','p_name text, p_slug text, p_description text, p_logo_url text, p_logo_file_id uuid, p_website text, p_settings jsonb, p_abbreviation text'),
   ('public','org_module_custom_value_add','p_org_id uuid, p_module_key text, p_namespace text, p_value text'),
   ('public','org_module_custom_value_policy_set','p_org_id uuid, p_module_key text, p_members_can_add boolean'),
   ('public','org_module_custom_value_remove','p_org_id uuid, p_module_key text, p_namespace text, p_value text'),
   ('public','org_module_custom_values','p_org_id uuid, p_module_key text, p_namespace text'),
   ('public','pin_prompt_app_to_version','p_app_id uuid, p_version_id uuid'),
   ('public','provision_mcp_server','p_slug text, p_name text, p_vendor text, p_category mcp_server_category, p_transport mcp_transport, p_auth_strategy mcp_auth_strategy, p_endpoint_url text, p_description text, p_icon_url text, p_color text, p_docs_url text, p_website_url text, p_status mcp_server_status, p_is_official boolean, p_oauth_scopes text[]'),
   ('public','prune_old_versions','p_file_id uuid, p_keep integer'),
   ('public','rag_library_list','p_limit integer, p_offset integer, p_search text, p_status_filter text, p_source_kind text'),
   ('public','rag_library_summary_totals','p_organization_id uuid'),
   ('public','rag_source_has_library_grant','p_source_kind text, p_source_id text, p_org_id uuid'),
   ('public','reply_to_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
   ('public','review_org_share','p_permission_id uuid, p_status text, p_note text'),
   ('public','revoke_share_link','p_link_id uuid'),
   ('public','sch_enqueue_manual_run','p_task_id uuid'),
   ('public','search_files','p_user_id uuid, p_query text, p_limit integer, p_offset integer, p_mime_prefix text'),
   ('public','search_scopes','p_org_id uuid, p_query text, p_type_id uuid'),
   ('public','search_users_intelligent','search_term text, current_user_id uuid, max_results integer'),
   ('public','send_user_review_message','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
   ('public','seo_rank_target_list_facets','p_scope text, p_org_id uuid, p_search text'),
   ('public','seo_rank_target_list_scope_counts','p_search text, p_filters jsonb'),
   ('public','set_context_value','p_payload jsonb'),
   ('public','set_org_module_setting','p_org_id uuid, p_module_key text, p_members_can_add boolean, p_requires_approval boolean, p_default_permission text, p_auto_ingest boolean, p_is_scopeable boolean'),
   ('public','setting_access_request_create','p_org_id uuid, p_setting_key text, p_setting_label text, p_setting_href text, p_action_key text, p_action_payload jsonb, p_message text'),
   ('public','setting_access_request_decide','p_request_id uuid, p_decision text, p_note text'),
   ('public','shx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean'),
   ('public','shx_list_scope_counts','p_search text, p_deep boolean, p_filters jsonb'),
   ('public','transfer_organization_ownership','org_id uuid, current_owner_id uuid, new_owner_id uuid'),
   ('public','udt_bulk_write','p_table_id uuid, p_operations jsonb'),
   ('public','udt_change_field_type','p_table_id uuid, p_field_id uuid, p_new_type field_data_type, p_strategy text'),
   ('public','udt_dataset_row_versions_trim',''),
   ('public','udt_upsert_cell','p_table_id uuid, p_row_id uuid, p_field_name text, p_value jsonb'),
   ('public','udt_upsert_row','p_table_id uuid, p_row_id uuid, p_data jsonb'),
   ('public','update_scope_type','p_type_id uuid, p_label_singular text, p_label_plural text, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_color text, p_slug text'),
   ('public','update_user_list','p_list_id uuid, p_list_name character varying, p_description text, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb'),
   ('public','update_user_own_feedback','p_feedback_id uuid, p_description text, p_feedback_type text'),
   ('public','update_user_table_config','p_table_id uuid, p_table_updates jsonb, p_field_updates jsonb'),
   ('public','update_user_table_default_sort','p_table_id uuid, p_sort_field text, p_sort_direction text'),
   ('public','update_user_table_metadata','p_table_id uuid, p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean'),
   ('public','upsert_mcp_connection','p_server_id uuid, p_config_id uuid, p_transport mcp_transport, p_endpoint_override text'),
   ('public','user_can_read_data_store_via_grant','p_user uuid, p_store uuid'),
   ('public','user_form_profile_append_to_array','p_user_id uuid, p_column text, p_item jsonb'),
   ('public','user_form_profile_set_custom_field','p_user_id uuid, p_key text, p_value jsonb'),
   ('public','version_current','p_token text, p_id uuid'),
   ('public','version_diff','p_token text, p_id uuid, p_from integer, p_to integer'),
   ('public','version_diff_current','p_token text, p_id uuid, p_from integer'),
   ('public','version_list','p_token text, p_id uuid, p_limit integer, p_offset integer'),
   ('public','version_prune','p_token text, p_id uuid, p_keep integer'),
   ('public','version_restore','p_token text, p_id uuid, p_version integer'),
   ('public','version_snapshot','p_token text, p_id uuid, p_version integer'));

do $$
declare n int; m int;
begin
  select count(*) into n from platform.definer_client_grant_grandfather
   where (schema_name, function_name, identity_args) in (

     ('public','hr_verification_deliver','p_id uuid, p_method text, p_payload jsonb'),
     ('public','hr_verification_deny','p_id uuid, p_basis text'),
     ('public','hr_verification_generate_apply','p_letter_id uuid, p_file_id uuid, p_snapshot jsonb, p_generated_at timestamp with time zone'),
     ('public','hr_verification_request_create','p_payload jsonb'),
     ('public','hr_wf_bulk_decide','p_step_ids uuid[], p_decision text, p_reason text'),
     ('public','hr_wf_cancel','p_instance_id uuid, p_reason text'),
     ('public','hr_wf_decide','p_step_id uuid, p_decision text, p_reason text, p_payload jsonb'),
     ('public','hr_wf_delegate','p_to_holder_kind text, p_to_holder_id uuid, p_action_type text, p_scope_id uuid, p_starts_at timestamp with time zone, p_ends_at timestamp with time zone, p_reason text'),
     ('public','hr_wf_escalate','p_step_id uuid, p_reason text'),
     ('public','hr_wf_for_target','p_target_token text, p_target_id uuid'),
     ('public','hr_wf_inbox','p_scope text, p_employment_id uuid, p_filters jsonb'),
     ('public','hr_wf_instance','p_instance_id uuid'),
     ('public','hr_wf_publish_definition','p_definition_id uuid'),
     ('public','hr_wf_reassign_step','p_step_id uuid, p_to_employment_id uuid, p_reason text'),
     ('public','hr_wf_record_result','p_step_id uuid, p_result jsonb, p_verified boolean'),
     ('public','hr_wf_request','p_flow_key text, p_target_token text, p_target_id uuid, p_organization_id uuid, p_payload jsonb, p_subject_employment_id uuid, p_as_draft boolean, p_idempotency_key text'),
     ('public','hr_wf_resolve_failure','p_failure_id uuid, p_action text, p_note text'),
     ('public','hr_wf_resubmit','p_instance_id uuid, p_payload jsonb'),
     ('public','hr_wf_submit','p_instance_id uuid'),
     ('public','hr_wf_withdraw','p_instance_id uuid, p_reason text'),
     ('public','industry_assign_org','p_organization_id uuid, p_industry_id uuid, p_is_primary boolean, p_actor uuid'),
     ('public','industry_curator_grant','p_user uuid, p_industry uuid, p_actor uuid'),
     ('public','industry_curator_revoke','p_user uuid, p_industry uuid, p_actor uuid'),
     ('public','industry_set_active','p_industry uuid, p_active boolean, p_actor uuid'),
     ('public','industry_unassign_org','p_organization_id uuid, p_industry_id uuid, p_actor uuid'),
     ('public','industry_upsert','p_slug text, p_name text, p_facet text, p_parent_id uuid, p_default_template_id uuid, p_description text, p_sort_order integer, p_actor uuid'),
     ('public','inv_create','p_target_type text, p_target_id uuid, p_email text, p_role text, p_org_id uuid, p_invited_user_id uuid, p_expires_at timestamp with time zone'),
     ('public','inv_get_managed','p_invitation_id uuid'),
     ('public','inv_list','p_target_type text, p_target_id uuid'),
     ('public','inv_resend','p_invitation_id uuid, p_expires_at timestamp with time zone'),
     ('public','inv_revoke','p_invitation_id uuid'),
     ('public','is_org_admin_for','p_user_id uuid, p_org_id uuid'),
     ('public','league_set_opt_in','p_opted_in boolean, p_display_name text'),
     ('public','library_grant_provenance','p_store uuid'),
     ('public','library_grant_provenance_batch','p_stores uuid[]'),
     ('public','list_scope_type_items','p_scope_type_id uuid'),
     ('public','list_scope_types','p_org_id uuid'),
     ('public','list_scopes','p_org_id uuid, p_type_id uuid, p_parent_scope_id uuid'),
     ('public','masterwork_improvement_summary','p_mandate_keys text[]'),
     ('public','mbr_add','p_container_type text, p_container_id uuid, p_user_id uuid, p_organization_id uuid, p_role text, p_status text, p_metadata jsonb'),
     ('public','mbr_count','p_container_type text, p_container_ids uuid[]'),
     ('public','mbr_for_user','p_container_type text'),
     ('public','mbr_list','p_container_type text, p_container_id uuid'),
     ('public','mbr_list_for_user','p_user_id uuid, p_container_type text'),
     ('public','mbr_list_with_users','p_container_type text, p_container_id uuid'),
     ('public','mbr_remove','p_container_type text, p_container_id uuid, p_user_id uuid'),
     ('public','mbr_update_role','p_container_type text, p_container_id uuid, p_user_id uuid, p_role text'),
     ('public','org_admin_get_member','p_org_id uuid, p_user_id uuid'),
     ('public','org_admin_list_audit','p_org_id uuid, p_limit integer'),
     ('public','org_admin_list_member_resources','p_org_id uuid, p_user_id uuid'),
     ('public','org_admin_list_members','p_org_id uuid'),
     ('public','org_admin_overview','p_org_id uuid'),
     ('public','org_create','p_name text, p_slug text, p_description text, p_logo_url text, p_logo_file_id uuid, p_website text, p_settings jsonb, p_abbreviation text'),
     ('public','org_module_custom_value_add','p_org_id uuid, p_module_key text, p_namespace text, p_value text'),
     ('public','org_module_custom_value_policy_set','p_org_id uuid, p_module_key text, p_members_can_add boolean'),
     ('public','org_module_custom_value_remove','p_org_id uuid, p_module_key text, p_namespace text, p_value text'),
     ('public','org_module_custom_values','p_org_id uuid, p_module_key text, p_namespace text'),
     ('public','pin_prompt_app_to_version','p_app_id uuid, p_version_id uuid'),
     ('public','provision_mcp_server','p_slug text, p_name text, p_vendor text, p_category mcp_server_category, p_transport mcp_transport, p_auth_strategy mcp_auth_strategy, p_endpoint_url text, p_description text, p_icon_url text, p_color text, p_docs_url text, p_website_url text, p_status mcp_server_status, p_is_official boolean, p_oauth_scopes text[]'),
     ('public','prune_old_versions','p_file_id uuid, p_keep integer'),
     ('public','rag_library_list','p_limit integer, p_offset integer, p_search text, p_status_filter text, p_source_kind text'),
     ('public','rag_library_summary_totals','p_organization_id uuid'),
     ('public','rag_source_has_library_grant','p_source_kind text, p_source_id text, p_org_id uuid'),
     ('public','reply_to_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
     ('public','review_org_share','p_permission_id uuid, p_status text, p_note text'),
     ('public','revoke_share_link','p_link_id uuid'),
     ('public','sch_enqueue_manual_run','p_task_id uuid'),
     ('public','search_files','p_user_id uuid, p_query text, p_limit integer, p_offset integer, p_mime_prefix text'),
     ('public','search_scopes','p_org_id uuid, p_query text, p_type_id uuid'),
     ('public','search_users_intelligent','search_term text, current_user_id uuid, max_results integer'),
     ('public','send_user_review_message','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
     ('public','seo_rank_target_list_facets','p_scope text, p_org_id uuid, p_search text'),
     ('public','seo_rank_target_list_scope_counts','p_search text, p_filters jsonb'),
     ('public','set_context_value','p_payload jsonb'),
     ('public','set_org_module_setting','p_org_id uuid, p_module_key text, p_members_can_add boolean, p_requires_approval boolean, p_default_permission text, p_auto_ingest boolean, p_is_scopeable boolean'),
     ('public','setting_access_request_create','p_org_id uuid, p_setting_key text, p_setting_label text, p_setting_href text, p_action_key text, p_action_payload jsonb, p_message text'),
     ('public','setting_access_request_decide','p_request_id uuid, p_decision text, p_note text'),
     ('public','shx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean'),
     ('public','shx_list_scope_counts','p_search text, p_deep boolean, p_filters jsonb'),
     ('public','transfer_organization_ownership','org_id uuid, current_owner_id uuid, new_owner_id uuid'),
     ('public','udt_bulk_write','p_table_id uuid, p_operations jsonb'),
     ('public','udt_change_field_type','p_table_id uuid, p_field_id uuid, p_new_type field_data_type, p_strategy text'),
     ('public','udt_dataset_row_versions_trim',''),
     ('public','udt_upsert_cell','p_table_id uuid, p_row_id uuid, p_field_name text, p_value jsonb'),
     ('public','udt_upsert_row','p_table_id uuid, p_row_id uuid, p_data jsonb'),
     ('public','update_scope_type','p_type_id uuid, p_label_singular text, p_label_plural text, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_color text, p_slug text'),
     ('public','update_user_list','p_list_id uuid, p_list_name character varying, p_description text, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb'),
     ('public','update_user_own_feedback','p_feedback_id uuid, p_description text, p_feedback_type text'),
     ('public','update_user_table_config','p_table_id uuid, p_table_updates jsonb, p_field_updates jsonb'),
     ('public','update_user_table_default_sort','p_table_id uuid, p_sort_field text, p_sort_direction text'),
     ('public','update_user_table_metadata','p_table_id uuid, p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean'),
     ('public','upsert_mcp_connection','p_server_id uuid, p_config_id uuid, p_transport mcp_transport, p_endpoint_override text'),
     ('public','user_can_read_data_store_via_grant','p_user uuid, p_store uuid'),
     ('public','user_form_profile_append_to_array','p_user_id uuid, p_column text, p_item jsonb'),
     ('public','user_form_profile_set_custom_field','p_user_id uuid, p_key text, p_value jsonb'),
     ('public','version_current','p_token text, p_id uuid'),
     ('public','version_diff','p_token text, p_id uuid, p_from integer, p_to integer'),
     ('public','version_diff_current','p_token text, p_id uuid, p_from integer'),
     ('public','version_list','p_token text, p_id uuid, p_limit integer, p_offset integer'),
     ('public','version_prune','p_token text, p_id uuid, p_keep integer'),
     ('public','version_restore','p_token text, p_id uuid, p_version integer'),
     ('public','version_snapshot','p_token text, p_id uuid, p_version integer'));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_d): % grandfather row(s) named here survived', n; end if;
  select count(*) into m from platform.client_callable_door
   where declared_by = 'DD-169 batch 3 / B-75';
  if m < 88 then raise exception 'DD-169 batch 3 (dd169_batch3_public_d): expected at least 88 new door rows, found %', m; end if;
  -- every CLOSED function really lost every client grant
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where (ns.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) in (

     ('public','hr_wf_publish_definition','p_definition_id uuid'),
     ('public','hr_wf_request','p_flow_key text, p_target_token text, p_target_id uuid, p_organization_id uuid, p_payload jsonb, p_subject_employment_id uuid, p_as_draft boolean, p_idempotency_key text'),
     ('public','hr_wf_submit','p_instance_id uuid'),
     ('public','is_org_admin_for','p_user_id uuid, p_org_id uuid'),
     ('public','pin_prompt_app_to_version','p_app_id uuid, p_version_id uuid'),
     ('public','prune_old_versions','p_file_id uuid, p_keep integer'),
     ('public','udt_dataset_row_versions_trim',''),
     ('public','update_user_own_feedback','p_feedback_id uuid, p_description text, p_feedback_type text'),
     ('public','user_form_profile_append_to_array','p_user_id uuid, p_column text, p_item jsonb'),
     ('public','user_form_profile_set_custom_field','p_user_id uuid, p_key text, p_value jsonb'),
     ('public','version_current','p_token text, p_id uuid'),
     ('public','version_diff','p_token text, p_id uuid, p_from integer, p_to integer'),
     ('public','version_diff_current','p_token text, p_id uuid, p_from integer'),
     ('public','version_prune','p_token text, p_id uuid, p_keep integer'))
     and (has_function_privilege('authenticated', p.oid, 'EXECUTE')
       or has_function_privilege('anon', p.oid, 'EXECUTE')
       or has_function_privilege('public', p.oid, 'EXECUTE'));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_d): % closed function(s) still hold a client EXECUTE grant', n; end if;
end $$;
