-- DD-169 batch 3 (dd169_batch3_public_a) — public 1/4
--
-- The 608 `authenticated`-executable SECURITY DEFINER functions B-64 left on
-- platform.definer_client_grant_grandfather run as the owner, so RLS does not apply
-- inside them and a grandfather row is the ABSENCE of a decision. This file decides
-- 104 of them: 93 DECLARED as doors (each one's body resolves the caller, and
-- gate_predicate records the literal D6 asserts is still present), and
-- 11 CLOSED (no client call site in any of the four repos, no RLS policy and no
-- security_invoker path that a client role evaluates — so the client EXECUTE grant is
-- removed outright). Every grandfather row named here is deleted; the matching entries
-- leave scripts/impl-doors/grandfather-allowlist.json in the same commit (D2c/D2d).

insert into platform.client_callable_door (schema_name, function_name, identity_args, reason, declared_by, gate_predicate)
values
 ('public','accept_scope_suggestion','p_suggestion_id uuid, p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','add_data_row_to_user_table','p_table_id uuid, p_data jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `workbench.udt_dataset_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','workbench.udt_dataset_access'),
 ('public','add_feedback_comment','p_feedback_id uuid, p_author_type text, p_author_name text, p_content text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_access_planner_snapshot','p_schema text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_configure_entity_access','p_schema text, p_table text, p_token text, p_label text, p_mode text, p_parent_type text, p_fk_column text, p_notes text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_delete_catalog_entry','p_app text, p_kind text, p_key text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_delete_relationship_rule','p_source_type text, p_target_type text, p_label text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_entity_types_list','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_exposure_audit_rows','p_resource_type text, p_exposure text, p_search text, p_include_deleted boolean, p_limit integer, p_offset integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_exposure_audit_summary','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_list_app_instances','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_manage_organization_membership','p_action text, p_org_id uuid, p_user_id uuid, p_role text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_model_catalog','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_model_offerings','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_promote','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_public_exposure_report','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_reachability_containers','p_type text, p_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_reachability_contents','p_type text, p_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_rebuild_reachability','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_recent_activity','p_limit integer, p_action_prefix text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_relationship_problems','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_relationship_rules','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_relationship_system_status','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.admin_unregistered_pairs` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.admin_unregistered_pairs'),
 ('public','admin_reply_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_set_access_planner_exclusion','p_schema text, p_table text, p_excluded boolean, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_set_association_enforcement','p_enabled boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_set_entity_type_active','p_token text, p_is_active boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_set_entity_type_agent_writable','p_token text, p_agent_writable boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_shareable_registry_defaults','p_token text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_shareable_registry_list','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_taxonomy_delete','p_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_unregistered_pairs','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_update','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_update_app_config','p_app text, p_schema_version integer, p_min_supported_app_version text, p_config jsonb, p_expected_updated_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_upsert_catalog_entry','p_app text, p_kind text, p_key text, p_schema_version integer, p_payload jsonb, p_artifact_url text, p_artifact_sha256 text, p_artifact_size_bytes bigint, p_min_app_version text, p_is_active boolean, p_sort_order integer, p_notes text, p_expected_updated_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','admin_upsert_entity_type','p_token text, p_schema_name text, p_table_name text, p_label text, p_base_tier smallint, p_is_versioned boolean, p_has_soft_delete boolean, p_is_listed boolean, p_is_component boolean, p_is_module boolean, p_category text, p_default_scopeable boolean, p_default_visibility text, p_default_members_can_add boolean, p_default_needs_approval boolean, p_default_auto_ingest boolean, p_rls_variant text, p_is_active boolean, p_notes text, p_reference_pickable boolean, p_title_column text, p_content_role text, p_reference_category text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_upsert_relationship_rule','p_source_type text, p_target_type text, p_container_side text, p_conveys_max permission_level, p_is_active boolean, p_label text, p_notes text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','admin_upsert_shareable_resource','p_resource_type text, p_schema_name text, p_table_name text, p_display_label text, p_url_path_template text, p_id_column text, p_owner_column text, p_is_public_column text, p_rls_uses_has_permission boolean, p_is_active boolean, p_content_role text, p_notes text, p_is_scopeable boolean, p_is_link_shareable boolean, p_public_columns text[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.is_super_admin` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.is_super_admin'),
 ('public','agx_create_agent_from_template','p_template_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_create_shortcut','p_agent_id uuid, p_label text, p_category_id uuid, p_user_id uuid, p_organization_id uuid, p_project_id uuid, p_task_id uuid, p_use_latest boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_duplicate_agent','p_agent_id uuid, p_as_system boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 12 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_duplicate_version','p_version_id uuid, p_as_system boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_get_access_level','p_agent_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_archived text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public.agx_list_scoped` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public.agx_list_scoped'),
 ('public','agx_list_scope_counts','p_search text, p_deep boolean, p_archived text, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_purge_versions','p_agent_id uuid, p_keep_count integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_history_counts','p_agent_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_report','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_report_admin','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_scan','p_agent_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_scan_admin','p_agent_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_update_all_to_active','p_agent_id uuid, p_mode text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','agx_usage_update_to_active','p_usage_type text, p_usage_id uuid, p_mode text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','apply_template','p_template_id uuid, p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','apply_template_by_key','p_template_key text, p_org_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.role` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.role'),
 ('public','assoc_link','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text, p_label text, p_position integer, p_metadata jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','assoc_unlink','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','check_file_rate_limit','p_actor_id uuid, p_kind text, p_limit integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','close_feedback_item','p_id uuid, p_status text, p_admin_notes text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','create_context_item','p_scope_type_id uuid, p_key text, p_display_name text, p_value_type context_value_type, p_description text, p_category text, p_fetch_hint context_fetch_hint, p_sensitivity context_sensitivity, p_tags text[], p_slug text, p_sort_order smallint, p_allowed_reference_types text[], p_max_items integer, p_allowed_scope_type_ids uuid[], p_reference_source jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','create_new_user_table_dynamic','p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean, p_initial_fields jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','create_scope_type','p_org_id uuid, p_label_singular text, p_label_plural text, p_parent_type_id uuid, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_default_variable_keys text[], p_color text, p_slug text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `iam.has_org_access` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','iam.has_org_access'),
 ('public','create_tasks_bulk','p_items jsonb, p_project_id uuid, p_organization_id uuid, p_scope_ids uuid[], p_entity_type text, p_entity_id uuid, p_metadata jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','create_user_list','p_list_name character varying, p_description text, p_user_id uuid, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','creator_claim_handle','p_handle text, p_display_name text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','creator_get_mine','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','creator_handle_available','p_handle text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','creator_set_public','p_public boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','creator_update_profile','p_display_name text, p_tagline text, p_bio text, p_avatar_url text, p_links jsonb, p_featured jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','crm_detect_merge_candidates','p_org uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','cx_canvas_save_user_version','p_user_id uuid, p_canvas_id uuid, p_title text, p_content jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','delete_scope','p_scope_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','delete_scope_type','p_type_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','dm_get_or_create_direct_conversation','p_user1_id uuid, p_user2_id uuid, p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_approve','p_class uuid, p_user uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_assign','p_class uuid, p_token text, p_resource uuid, p_due date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_assignments','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_by_code','p_code text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_grant','p_class uuid, p_user uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_join','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_join_by_code','p_code text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_join_code','p_class uuid, p_action text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_leave','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_progress_overview','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_remove','p_class uuid, p_user uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_request','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_roster','p_class uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_set_access','p_class uuid, p_access_mode text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public._edu_is_owner` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public._edu_is_owner'),
 ('public','edu_class_student_progress','p_class uuid, p_user uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_class_unassign','p_class uuid, p_token text, p_resource uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `public._edu_is_owner` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','public._edu_is_owner'),
 ('public','edu_coppa_gate','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_delete_study_data','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','edu_export_study_data','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()');

-- CLOSED: no client caller anywhere. The grant goes, not just the stand-down.
revoke execute on function public."accept_context_item_suggestion"(p_suggestion_id uuid) from public, anon, authenticated;
revoke execute on function public."admin_heal_hr_grant_drift"() from public, anon, authenticated;
revoke execute on function public."admin_heal_reachability_drift"() from public, anon, authenticated;
revoke execute on function public."admin_set_containment_edge"(p_child_type text, p_parent_type text, p_fk_column text, p_enabled boolean, p_notes text) from public, anon, authenticated;
revoke execute on function public."admin_set_shareable_active"(p_resource_type text, p_is_active boolean) from public, anon, authenticated;
revoke execute on function public."auth_is_org_admin"(user_id uuid, org_id uuid) from public, anon, authenticated;
revoke execute on function public."auth_is_org_member"(user_id uuid, org_id uuid) from public, anon, authenticated;
revoke execute on function public."auth_is_org_owner"(user_id uuid, org_id uuid) from public, anon, authenticated;
revoke execute on function public."container_resource_counts"(p_column text, p_container_id uuid) from public, anon, authenticated;
revoke execute on function public."count_user_files"(p_user_id uuid, p_include_folders boolean, p_include_deleted boolean) from public, anon, authenticated;
revoke execute on function public."creator_connect_status"() from public, anon, authenticated;

delete from platform.definer_client_grant_grandfather g
 where (g.schema_name, g.function_name, g.identity_args) in (
   ('public','accept_context_item_suggestion','p_suggestion_id uuid'),
   ('public','accept_scope_suggestion','p_suggestion_id uuid, p_organization_id uuid'),
   ('public','add_data_row_to_user_table','p_table_id uuid, p_data jsonb'),
   ('public','add_feedback_comment','p_feedback_id uuid, p_author_type text, p_author_name text, p_content text'),
   ('public','admin_access_planner_snapshot','p_schema text'),
   ('public','admin_configure_entity_access','p_schema text, p_table text, p_token text, p_label text, p_mode text, p_parent_type text, p_fk_column text, p_notes text'),
   ('public','admin_delete_catalog_entry','p_app text, p_kind text, p_key text'),
   ('public','admin_delete_relationship_rule','p_source_type text, p_target_type text, p_label text'),
   ('public','admin_entity_types_list',''),
   ('public','admin_exposure_audit_rows','p_resource_type text, p_exposure text, p_search text, p_include_deleted boolean, p_limit integer, p_offset integer'),
   ('public','admin_exposure_audit_summary',''),
   ('public','admin_heal_hr_grant_drift',''),
   ('public','admin_heal_reachability_drift',''),
   ('public','admin_list_app_instances',''),
   ('public','admin_manage_organization_membership','p_action text, p_org_id uuid, p_user_id uuid, p_role text'),
   ('public','admin_model_catalog',''),
   ('public','admin_model_offerings',''),
   ('public','admin_promote','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb'),
   ('public','admin_public_exposure_report',''),
   ('public','admin_reachability_containers','p_type text, p_id uuid'),
   ('public','admin_reachability_contents','p_type text, p_id uuid'),
   ('public','admin_rebuild_reachability',''),
   ('public','admin_recent_activity','p_limit integer, p_action_prefix text'),
   ('public','admin_relationship_problems',''),
   ('public','admin_relationship_rules',''),
   ('public','admin_relationship_system_status',''),
   ('public','admin_reply_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
   ('public','admin_set_access_planner_exclusion','p_schema text, p_table text, p_excluded boolean, p_reason text'),
   ('public','admin_set_association_enforcement','p_enabled boolean'),
   ('public','admin_set_containment_edge','p_child_type text, p_parent_type text, p_fk_column text, p_enabled boolean, p_notes text'),
   ('public','admin_set_entity_type_active','p_token text, p_is_active boolean'),
   ('public','admin_set_entity_type_agent_writable','p_token text, p_agent_writable boolean'),
   ('public','admin_set_shareable_active','p_resource_type text, p_is_active boolean'),
   ('public','admin_shareable_registry_defaults','p_token text'),
   ('public','admin_shareable_registry_list',''),
   ('public','admin_taxonomy_delete','p_id uuid'),
   ('public','admin_unregistered_pairs',''),
   ('public','admin_update','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb'),
   ('public','admin_update_app_config','p_app text, p_schema_version integer, p_min_supported_app_version text, p_config jsonb, p_expected_updated_at timestamp with time zone'),
   ('public','admin_upsert_catalog_entry','p_app text, p_kind text, p_key text, p_schema_version integer, p_payload jsonb, p_artifact_url text, p_artifact_sha256 text, p_artifact_size_bytes bigint, p_min_app_version text, p_is_active boolean, p_sort_order integer, p_notes text, p_expected_updated_at timestamp with time zone'),
   ('public','admin_upsert_entity_type','p_token text, p_schema_name text, p_table_name text, p_label text, p_base_tier smallint, p_is_versioned boolean, p_has_soft_delete boolean, p_is_listed boolean, p_is_component boolean, p_is_module boolean, p_category text, p_default_scopeable boolean, p_default_visibility text, p_default_members_can_add boolean, p_default_needs_approval boolean, p_default_auto_ingest boolean, p_rls_variant text, p_is_active boolean, p_notes text, p_reference_pickable boolean, p_title_column text, p_content_role text, p_reference_category text'),
   ('public','admin_upsert_relationship_rule','p_source_type text, p_target_type text, p_container_side text, p_conveys_max permission_level, p_is_active boolean, p_label text, p_notes text'),
   ('public','admin_upsert_shareable_resource','p_resource_type text, p_schema_name text, p_table_name text, p_display_label text, p_url_path_template text, p_id_column text, p_owner_column text, p_is_public_column text, p_rls_uses_has_permission boolean, p_is_active boolean, p_content_role text, p_notes text, p_is_scopeable boolean, p_is_link_shareable boolean, p_public_columns text[]'),
   ('public','agx_create_agent_from_template','p_template_id uuid'),
   ('public','agx_create_shortcut','p_agent_id uuid, p_label text, p_category_id uuid, p_user_id uuid, p_organization_id uuid, p_project_id uuid, p_task_id uuid, p_use_latest boolean'),
   ('public','agx_duplicate_agent','p_agent_id uuid, p_as_system boolean'),
   ('public','agx_duplicate_version','p_version_id uuid, p_as_system boolean'),
   ('public','agx_get_access_level','p_agent_id uuid'),
   ('public','agx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_archived text'),
   ('public','agx_list_scope_counts','p_search text, p_deep boolean, p_archived text, p_filters jsonb'),
   ('public','agx_purge_versions','p_agent_id uuid, p_keep_count integer'),
   ('public','agx_usage_history_counts','p_agent_id uuid'),
   ('public','agx_usage_report',''),
   ('public','agx_usage_report_admin',''),
   ('public','agx_usage_scan','p_agent_id uuid'),
   ('public','agx_usage_scan_admin','p_agent_id uuid'),
   ('public','agx_usage_update_all_to_active','p_agent_id uuid, p_mode text'),
   ('public','agx_usage_update_to_active','p_usage_type text, p_usage_id uuid, p_mode text'),
   ('public','apply_template','p_template_id uuid, p_org_id uuid'),
   ('public','apply_template_by_key','p_template_key text, p_org_id uuid'),
   ('public','assoc_link','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text, p_label text, p_position integer, p_metadata jsonb'),
   ('public','assoc_unlink','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text'),
   ('public','auth_is_org_admin','user_id uuid, org_id uuid'),
   ('public','auth_is_org_member','user_id uuid, org_id uuid'),
   ('public','auth_is_org_owner','user_id uuid, org_id uuid'),
   ('public','check_file_rate_limit','p_actor_id uuid, p_kind text, p_limit integer'),
   ('public','close_feedback_item','p_id uuid, p_status text, p_admin_notes text'),
   ('public','container_resource_counts','p_column text, p_container_id uuid'),
   ('public','count_user_files','p_user_id uuid, p_include_folders boolean, p_include_deleted boolean'),
   ('public','create_context_item','p_scope_type_id uuid, p_key text, p_display_name text, p_value_type context_value_type, p_description text, p_category text, p_fetch_hint context_fetch_hint, p_sensitivity context_sensitivity, p_tags text[], p_slug text, p_sort_order smallint, p_allowed_reference_types text[], p_max_items integer, p_allowed_scope_type_ids uuid[], p_reference_source jsonb'),
   ('public','create_new_user_table_dynamic','p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean, p_initial_fields jsonb'),
   ('public','create_scope_type','p_org_id uuid, p_label_singular text, p_label_plural text, p_parent_type_id uuid, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_default_variable_keys text[], p_color text, p_slug text'),
   ('public','create_tasks_bulk','p_items jsonb, p_project_id uuid, p_organization_id uuid, p_scope_ids uuid[], p_entity_type text, p_entity_id uuid, p_metadata jsonb'),
   ('public','create_user_list','p_list_name character varying, p_description text, p_user_id uuid, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb'),
   ('public','creator_claim_handle','p_handle text, p_display_name text'),
   ('public','creator_connect_status',''),
   ('public','creator_get_mine',''),
   ('public','creator_handle_available','p_handle text'),
   ('public','creator_set_public','p_public boolean'),
   ('public','creator_update_profile','p_display_name text, p_tagline text, p_bio text, p_avatar_url text, p_links jsonb, p_featured jsonb'),
   ('public','crm_detect_merge_candidates','p_org uuid'),
   ('public','cx_canvas_save_user_version','p_user_id uuid, p_canvas_id uuid, p_title text, p_content jsonb'),
   ('public','delete_scope','p_scope_id uuid'),
   ('public','delete_scope_type','p_type_id uuid'),
   ('public','dm_get_or_create_direct_conversation','p_user1_id uuid, p_user2_id uuid, p_organization_id uuid'),
   ('public','edu_class_approve','p_class uuid, p_user uuid'),
   ('public','edu_class_assign','p_class uuid, p_token text, p_resource uuid, p_due date'),
   ('public','edu_class_assignments','p_class uuid'),
   ('public','edu_class_by_code','p_code text'),
   ('public','edu_class_grant','p_class uuid, p_user uuid'),
   ('public','edu_class_join','p_class uuid'),
   ('public','edu_class_join_by_code','p_code text'),
   ('public','edu_class_join_code','p_class uuid, p_action text'),
   ('public','edu_class_leave','p_class uuid'),
   ('public','edu_class_progress_overview','p_class uuid'),
   ('public','edu_class_remove','p_class uuid, p_user uuid'),
   ('public','edu_class_request','p_class uuid'),
   ('public','edu_class_roster','p_class uuid'),
   ('public','edu_class_set_access','p_class uuid, p_access_mode text'),
   ('public','edu_class_student_progress','p_class uuid, p_user uuid'),
   ('public','edu_class_unassign','p_class uuid, p_token text, p_resource uuid'),
   ('public','edu_coppa_gate',''),
   ('public','edu_delete_study_data',''),
   ('public','edu_export_study_data',''));

do $$
declare n int; m int;
begin
  select count(*) into n from platform.definer_client_grant_grandfather
   where (schema_name, function_name, identity_args) in (

     ('public','accept_context_item_suggestion','p_suggestion_id uuid'),
     ('public','accept_scope_suggestion','p_suggestion_id uuid, p_organization_id uuid'),
     ('public','add_data_row_to_user_table','p_table_id uuid, p_data jsonb'),
     ('public','add_feedback_comment','p_feedback_id uuid, p_author_type text, p_author_name text, p_content text'),
     ('public','admin_access_planner_snapshot','p_schema text'),
     ('public','admin_configure_entity_access','p_schema text, p_table text, p_token text, p_label text, p_mode text, p_parent_type text, p_fk_column text, p_notes text'),
     ('public','admin_delete_catalog_entry','p_app text, p_kind text, p_key text'),
     ('public','admin_delete_relationship_rule','p_source_type text, p_target_type text, p_label text'),
     ('public','admin_entity_types_list',''),
     ('public','admin_exposure_audit_rows','p_resource_type text, p_exposure text, p_search text, p_include_deleted boolean, p_limit integer, p_offset integer'),
     ('public','admin_exposure_audit_summary',''),
     ('public','admin_heal_hr_grant_drift',''),
     ('public','admin_heal_reachability_drift',''),
     ('public','admin_list_app_instances',''),
     ('public','admin_manage_organization_membership','p_action text, p_org_id uuid, p_user_id uuid, p_role text'),
     ('public','admin_model_catalog',''),
     ('public','admin_model_offerings',''),
     ('public','admin_promote','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb'),
     ('public','admin_public_exposure_report',''),
     ('public','admin_reachability_containers','p_type text, p_id uuid'),
     ('public','admin_reachability_contents','p_type text, p_id uuid'),
     ('public','admin_rebuild_reachability',''),
     ('public','admin_recent_activity','p_limit integer, p_action_prefix text'),
     ('public','admin_relationship_problems',''),
     ('public','admin_relationship_rules',''),
     ('public','admin_relationship_system_status',''),
     ('public','admin_reply_user_review','p_feedback_id uuid, p_message text, p_sender_name text, p_image_file_ids uuid[]'),
     ('public','admin_set_access_planner_exclusion','p_schema text, p_table text, p_excluded boolean, p_reason text'),
     ('public','admin_set_association_enforcement','p_enabled boolean'),
     ('public','admin_set_containment_edge','p_child_type text, p_parent_type text, p_fk_column text, p_enabled boolean, p_notes text'),
     ('public','admin_set_entity_type_active','p_token text, p_is_active boolean'),
     ('public','admin_set_entity_type_agent_writable','p_token text, p_agent_writable boolean'),
     ('public','admin_set_shareable_active','p_resource_type text, p_is_active boolean'),
     ('public','admin_shareable_registry_defaults','p_token text'),
     ('public','admin_shareable_registry_list',''),
     ('public','admin_taxonomy_delete','p_id uuid'),
     ('public','admin_unregistered_pairs',''),
     ('public','admin_update','target_user_id uuid, target_level admin_level, target_permissions jsonb, target_metadata jsonb'),
     ('public','admin_update_app_config','p_app text, p_schema_version integer, p_min_supported_app_version text, p_config jsonb, p_expected_updated_at timestamp with time zone'),
     ('public','admin_upsert_catalog_entry','p_app text, p_kind text, p_key text, p_schema_version integer, p_payload jsonb, p_artifact_url text, p_artifact_sha256 text, p_artifact_size_bytes bigint, p_min_app_version text, p_is_active boolean, p_sort_order integer, p_notes text, p_expected_updated_at timestamp with time zone'),
     ('public','admin_upsert_entity_type','p_token text, p_schema_name text, p_table_name text, p_label text, p_base_tier smallint, p_is_versioned boolean, p_has_soft_delete boolean, p_is_listed boolean, p_is_component boolean, p_is_module boolean, p_category text, p_default_scopeable boolean, p_default_visibility text, p_default_members_can_add boolean, p_default_needs_approval boolean, p_default_auto_ingest boolean, p_rls_variant text, p_is_active boolean, p_notes text, p_reference_pickable boolean, p_title_column text, p_content_role text, p_reference_category text'),
     ('public','admin_upsert_relationship_rule','p_source_type text, p_target_type text, p_container_side text, p_conveys_max permission_level, p_is_active boolean, p_label text, p_notes text'),
     ('public','admin_upsert_shareable_resource','p_resource_type text, p_schema_name text, p_table_name text, p_display_label text, p_url_path_template text, p_id_column text, p_owner_column text, p_is_public_column text, p_rls_uses_has_permission boolean, p_is_active boolean, p_content_role text, p_notes text, p_is_scopeable boolean, p_is_link_shareable boolean, p_public_columns text[]'),
     ('public','agx_create_agent_from_template','p_template_id uuid'),
     ('public','agx_create_shortcut','p_agent_id uuid, p_label text, p_category_id uuid, p_user_id uuid, p_organization_id uuid, p_project_id uuid, p_task_id uuid, p_use_latest boolean'),
     ('public','agx_duplicate_agent','p_agent_id uuid, p_as_system boolean'),
     ('public','agx_duplicate_version','p_version_id uuid, p_as_system boolean'),
     ('public','agx_get_access_level','p_agent_id uuid'),
     ('public','agx_list_facets','p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_archived text'),
     ('public','agx_list_scope_counts','p_search text, p_deep boolean, p_archived text, p_filters jsonb'),
     ('public','agx_purge_versions','p_agent_id uuid, p_keep_count integer'),
     ('public','agx_usage_history_counts','p_agent_id uuid'),
     ('public','agx_usage_report',''),
     ('public','agx_usage_report_admin',''),
     ('public','agx_usage_scan','p_agent_id uuid'),
     ('public','agx_usage_scan_admin','p_agent_id uuid'),
     ('public','agx_usage_update_all_to_active','p_agent_id uuid, p_mode text'),
     ('public','agx_usage_update_to_active','p_usage_type text, p_usage_id uuid, p_mode text'),
     ('public','apply_template','p_template_id uuid, p_org_id uuid'),
     ('public','apply_template_by_key','p_template_key text, p_org_id uuid'),
     ('public','assoc_link','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text, p_label text, p_position integer, p_metadata jsonb'),
     ('public','assoc_unlink','p_source_type text, p_source_id uuid, p_target_type text, p_target_id uuid, p_role text'),
     ('public','auth_is_org_admin','user_id uuid, org_id uuid'),
     ('public','auth_is_org_member','user_id uuid, org_id uuid'),
     ('public','auth_is_org_owner','user_id uuid, org_id uuid'),
     ('public','check_file_rate_limit','p_actor_id uuid, p_kind text, p_limit integer'),
     ('public','close_feedback_item','p_id uuid, p_status text, p_admin_notes text'),
     ('public','container_resource_counts','p_column text, p_container_id uuid'),
     ('public','count_user_files','p_user_id uuid, p_include_folders boolean, p_include_deleted boolean'),
     ('public','create_context_item','p_scope_type_id uuid, p_key text, p_display_name text, p_value_type context_value_type, p_description text, p_category text, p_fetch_hint context_fetch_hint, p_sensitivity context_sensitivity, p_tags text[], p_slug text, p_sort_order smallint, p_allowed_reference_types text[], p_max_items integer, p_allowed_scope_type_ids uuid[], p_reference_source jsonb'),
     ('public','create_new_user_table_dynamic','p_table_name text, p_description text, p_is_public boolean, p_authenticated_read boolean, p_initial_fields jsonb'),
     ('public','create_scope_type','p_org_id uuid, p_label_singular text, p_label_plural text, p_parent_type_id uuid, p_icon text, p_description text, p_sort_order smallint, p_max_assignments smallint, p_default_variable_keys text[], p_color text, p_slug text'),
     ('public','create_tasks_bulk','p_items jsonb, p_project_id uuid, p_organization_id uuid, p_scope_ids uuid[], p_entity_type text, p_entity_id uuid, p_metadata jsonb'),
     ('public','create_user_list','p_list_name character varying, p_description text, p_user_id uuid, p_is_public boolean, p_authenticated_read boolean, p_public_read boolean, p_items jsonb'),
     ('public','creator_claim_handle','p_handle text, p_display_name text'),
     ('public','creator_connect_status',''),
     ('public','creator_get_mine',''),
     ('public','creator_handle_available','p_handle text'),
     ('public','creator_set_public','p_public boolean'),
     ('public','creator_update_profile','p_display_name text, p_tagline text, p_bio text, p_avatar_url text, p_links jsonb, p_featured jsonb'),
     ('public','crm_detect_merge_candidates','p_org uuid'),
     ('public','cx_canvas_save_user_version','p_user_id uuid, p_canvas_id uuid, p_title text, p_content jsonb'),
     ('public','delete_scope','p_scope_id uuid'),
     ('public','delete_scope_type','p_type_id uuid'),
     ('public','dm_get_or_create_direct_conversation','p_user1_id uuid, p_user2_id uuid, p_organization_id uuid'),
     ('public','edu_class_approve','p_class uuid, p_user uuid'),
     ('public','edu_class_assign','p_class uuid, p_token text, p_resource uuid, p_due date'),
     ('public','edu_class_assignments','p_class uuid'),
     ('public','edu_class_by_code','p_code text'),
     ('public','edu_class_grant','p_class uuid, p_user uuid'),
     ('public','edu_class_join','p_class uuid'),
     ('public','edu_class_join_by_code','p_code text'),
     ('public','edu_class_join_code','p_class uuid, p_action text'),
     ('public','edu_class_leave','p_class uuid'),
     ('public','edu_class_progress_overview','p_class uuid'),
     ('public','edu_class_remove','p_class uuid, p_user uuid'),
     ('public','edu_class_request','p_class uuid'),
     ('public','edu_class_roster','p_class uuid'),
     ('public','edu_class_set_access','p_class uuid, p_access_mode text'),
     ('public','edu_class_student_progress','p_class uuid, p_user uuid'),
     ('public','edu_class_unassign','p_class uuid, p_token text, p_resource uuid'),
     ('public','edu_coppa_gate',''),
     ('public','edu_delete_study_data',''),
     ('public','edu_export_study_data',''));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_a): % grandfather row(s) named here survived', n; end if;
  select count(*) into m from platform.client_callable_door
   where declared_by = 'DD-169 batch 3 / B-75';
  if m < 93 then raise exception 'DD-169 batch 3 (dd169_batch3_public_a): expected at least 93 new door rows, found %', m; end if;
  -- every CLOSED function really lost every client grant
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where (ns.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) in (

     ('public','accept_context_item_suggestion','p_suggestion_id uuid'),
     ('public','admin_heal_hr_grant_drift',''),
     ('public','admin_heal_reachability_drift',''),
     ('public','admin_set_containment_edge','p_child_type text, p_parent_type text, p_fk_column text, p_enabled boolean, p_notes text'),
     ('public','admin_set_shareable_active','p_resource_type text, p_is_active boolean'),
     ('public','auth_is_org_admin','user_id uuid, org_id uuid'),
     ('public','auth_is_org_member','user_id uuid, org_id uuid'),
     ('public','auth_is_org_owner','user_id uuid, org_id uuid'),
     ('public','container_resource_counts','p_column text, p_container_id uuid'),
     ('public','count_user_files','p_user_id uuid, p_include_folders boolean, p_include_deleted boolean'),
     ('public','creator_connect_status',''))
     and (has_function_privilege('authenticated', p.oid, 'EXECUTE')
       or has_function_privilege('anon', p.oid, 'EXECUTE')
       or has_function_privilege('public', p.oid, 'EXECUTE'));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_a): % closed function(s) still hold a client EXECUTE grant', n; end if;
end $$;
