-- DD-169 batch 3 (dd169_batch3_public_c) — public 3/4
--
-- The 608 `authenticated`-executable SECURITY DEFINER functions B-64 left on
-- platform.definer_client_grant_grandfather run as the owner, so RLS does not apply
-- inside them and a grandfather row is the ABSENCE of a decision. This file decides
-- 104 of them: 83 DECLARED as doors (each one's body resolves the caller, and
-- gate_predicate records the literal D6 asserts is still present), and
-- 21 CLOSED (no client call site in any of the four repos, no RLS policy and no
-- security_invoker path that a client role evaluates — so the client EXECUTE grant is
-- removed outright). Every grandfather row named here is deleted; the matching entries
-- leave scripts/impl-doors/grandfather-allowlist.json in the same commit (D2c/D2d).

insert into platform.client_callable_door (schema_name, function_name, identity_args, reason, declared_by, gate_predicate)
values
 ('public','hr_directory_list','p_organization_id uuid, p_filter jsonb, p_limit integer, p_offset integer, p_sort text, p_direction text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 26 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_duplicate_scan','p_organization_id uuid, p_probe jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 15 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_emergency_contact_upsert','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employee_by_party','p_organization_id uuid, p_party_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.employee_by_party` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.employee_by_party'),
 ('public','hr_employee_create','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 12 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employee_invite','p_employee_id uuid, p_email text, p_expires_at timestamp with time zone','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employee_profile','p_employee_id uuid, p_as_of date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 14 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employee_update','p_employee_id uuid, p_patch jsonb, p_expected_version integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employment_history','p_employee_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_employment_set_pay_group','p_employment_id uuid, p_pay_group_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr._l1_write_gate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr._l1_write_gate'),
 ('public','hr_engagement_upsert','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_external_identity_upsert','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_incident_advance','p_incident_id uuid, p_state text, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_incident_party_add','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_invite_accept','p_token text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_jurisdiction_rule_set_status','p_rule_id uuid, p_new_status text, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.jurisdiction_rule_set_status` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.jurisdiction_rule_set_status'),
 ('public','hr_jurisdiction_rules_admin_data','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.jurisdiction_rules_admin_data` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.jurisdiction_rules_admin_data'),
 ('public','hr_kiosk_device_list','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.kiosk_device_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.kiosk_device_list'),
 ('public','hr_kiosk_device_set_capture','p_device_id uuid, p_require_photo boolean, p_require_geo boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.kiosk_device_set_capture` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.kiosk_device_set_capture'),
 ('public','hr_kiosk_device_set_trust','p_device_id uuid, p_trust_state text, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.kiosk_device_set_trust` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.kiosk_device_set_trust'),
 ('public','hr_kiosk_pairing_code_create','p_organization_id uuid, p_device_name text, p_location_id uuid, p_device_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.kiosk_pairing_code_create` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.kiosk_pairing_code_create'),
 ('public','hr_knob_clear','p_organization_id uuid, p_feature text, p_key text, p_scope_kind text, p_scope_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_knob_index','p_organization_id uuid, p_overridden_only boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_knob_set','p_organization_id uuid, p_feature text, p_key text, p_value jsonb, p_scope_kind text, p_scope_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_law_portal_data','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.law_portal_data` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.law_portal_data'),
 ('public','hr_leave_adjust','p_employment_id uuid, p_leave_policy_id uuid, p_direction text, p_hours numeric, p_reason_category text, p_note text, p_confirm_below_floor boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 5 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_adjust` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_adjust'),
 ('public','hr_leave_balances','p_organization_id uuid, p_scope text, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_balances` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_balances'),
 ('public','hr_leave_balances_export','p_organization_id uuid, p_scope text, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_balances_export` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_balances_export'),
 ('public','hr_leave_calendar','p_organization_id uuid, p_from date, p_to date, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_calendar` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_calendar'),
 ('public','hr_leave_calendar_ics','p_organization_id uuid, p_from date, p_to date, p_filters jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_calendar_ics` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_calendar_ics'),
 ('public','hr_leave_enroll','p_leave_policy_id uuid, p_employment_ids uuid[], p_effective_from date, p_override_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_enroll` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_enroll'),
 ('public','hr_leave_ledger_export','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_ledger_export` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_ledger_export'),
 ('public','hr_leave_ledger_view','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_ledger_view` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_ledger_view'),
 ('public','hr_leave_policy_floors','p_organization_id uuid, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_policy_floors` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_policy_floors'),
 ('public','hr_leave_policy_list','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_policy_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_policy_list'),
 ('public','hr_leave_policy_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 10 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_policy_save` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_policy_save'),
 ('public','hr_leave_policy_validate','p_organization_id uuid, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_policy_validate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_policy_validate'),
 ('public','hr_leave_request_cancel','p_request_id uuid, p_reason text, p_hours numeric','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_request_cancel` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_request_cancel'),
 ('public','hr_leave_request_preview','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_request_preview` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_request_preview'),
 ('public','hr_leave_request_submit','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb, p_reason_category_id uuid, p_reason_note text, p_leave_case_id uuid, p_idempotency_key text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.leave_request_submit` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.leave_request_submit'),
 ('public','hr_member_employee_links','p_organization_id uuid, p_user_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.member_employee_links` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.member_employee_links'),
 ('public','hr_module_set_enabled','p_organization_id uuid, p_enabled boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_my_compensation','p_employment_id uuid, p_as_of date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.my_compensation` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.my_compensation'),
 ('public','hr_my_context','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 22 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_my_time_off','p_employment_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 11 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.my_time_off` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.my_time_off'),
 ('public','hr_my_verification_consents','','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_org_chart','p_organization_id uuid, p_on date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 11 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_org_jurisdiction_rule_deactivate','p_organization_id uuid, p_rule_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.org_jurisdiction_rule_deactivate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.org_jurisdiction_rule_deactivate'),
 ('public','hr_org_jurisdiction_rule_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.org_jurisdiction_rule_save` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.org_jurisdiction_rule_save'),
 ('public','hr_org_jurisdiction_rule_set_applies','p_organization_id uuid, p_rule_class text, p_jurisdiction_key text, p_applies boolean, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.org_jurisdiction_rule_set_applies` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.org_jurisdiction_rule_set_applies'),
 ('public','hr_org_summary','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_overtime_preapproval_create','p_employment_id uuid, p_covers_from timestamp with time zone, p_covers_to timestamp with time zone, p_requested_hours numeric, p_request_kind text, p_reason_category_id uuid, p_reason_note text, p_shift_ids uuid[]','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.overtime_preapproval_create` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.overtime_preapproval_create'),
 ('public','hr_overtime_preapproval_get','p_preapproval_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.overtime_preapproval_get` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.overtime_preapproval_get'),
 ('public','hr_overtime_preapproval_list','p_filters jsonb, p_page jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.overtime_preapproval_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.overtime_preapproval_list'),
 ('public','hr_pay_group_upsert','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr._l1_settings_gate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr._l1_settings_gate'),
 ('public','hr_pay_period_generate','p_pay_group_id uuid, p_through_date date','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.pay_period_generate` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.pay_period_generate'),
 ('public','hr_pay_period_get','p_pay_period_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 10 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.pay_period_get` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.pay_period_get'),
 ('public','hr_pay_period_list','p_filters jsonb, p_page jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.pay_period_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.pay_period_list'),
 ('public','hr_pay_period_transition','p_pay_period_id uuid, p_to_state text, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.pay_period_transition` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.pay_period_transition'),
 ('public','hr_payroll_export_list','p_organization_id uuid, p_pay_period_id uuid, p_limit integer','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_pending_change_cancel','p_kind text, p_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_pending_changes','p_employment_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; reads; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_position_change','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_punch_correct','p_punch_ids uuid[], p_new_values jsonb, p_reason text, p_category uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.punch_correct` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.punch_correct'),
 ('public','hr_punch_record','p_employment_id uuid, p_kind text, p_occurred_at timestamp with time zone, p_source text, p_idempotency_key text, p_kiosk_session_id uuid, p_geo jsonb, p_photo_file_id uuid, p_attestation jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.punch_record` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.punch_record'),
 ('public','hr_punch_register','p_filters jsonb, p_page jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.punch_register` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.punch_register'),
 ('public','hr_punch_void','p_punch_id uuid, p_reason text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 2 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.punch_void` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.punch_void'),
 ('public','hr_recompute_apply','p_employment_id uuid, p_workweek jsonb, p_intervals jsonb, p_engine jsonb, p_idempotency_key text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.recompute_apply` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.recompute_apply'),
 ('public','hr_restricted_get','p_token text, p_id uuid, p_purpose text, p_justification text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 7 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr._door_get` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr._door_get'),
 ('public','hr_restricted_list','p_token text, p_filter jsonb, p_limit integer, p_cursor text, p_purpose text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 6 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr._door_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr._door_list'),
 ('public','hr_restricted_note_add','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_self_update','p_token text, p_id uuid, p_patch jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 19 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_separation_record','p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 9 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_set_employment_pin','p_employment_id uuid, p_pin text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_ssn_probe_authorize','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_ssn_store','p_employee_id uuid, p_ciphertext bytea, p_key_id text, p_hmac bytea, p_last4 text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 1 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_structure_list','p_organization_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 19 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_structure_upsert','p_kind text, p_payload jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()'),
 ('public','hr_time_adjustment_create','p_employment_id uuid, p_original_pay_period_id uuid, p_work_date date, p_earning_code_id uuid, p_hours_delta numeric, p_amount_delta numeric, p_reason_category_id uuid, p_reason_note text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.time_adjustment_create` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.time_adjustment_create'),
 ('public','hr_time_adjustment_list','p_filters jsonb, p_page jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.time_adjustment_list` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.time_adjustment_list'),
 ('public','hr_timesheet_get','p_employment_id uuid, p_pay_period_id uuid','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 8 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.timesheet_get` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.timesheet_get'),
 ('public','hr_timesheet_period_grid','p_pay_period_id uuid, p_filters jsonb, p_page jsonb','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 4 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `hr.timesheet_period_grid` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','hr.timesheet_period_grid'),
 ('public','hr_verification_consent','p_id uuid, p_granted boolean, p_note text','Signed-in door (DD-169 batch 3, B-75). SECURITY DEFINER; writes; 3 client call site(s) found across matrx-frontend / aidream / matrx-extend / matrx-local. The caller is resolved inside the body by `auth.uid()` — that literal is what D6 checks is still there. Triaged from the 608 grandfathered signed-in definers B-64 left behind; `anon` holds no EXECUTE on it.','DD-169 batch 3 / B-75','auth.uid()');

-- CLOSED: no client caller anywhere. The grant goes, not just the stand-down.
revoke execute on function public."hr_emergency_contact_remove"(p_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_employee_grant_missing_membership"(p_employee_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_employer_profile_update"(p_payload jsonb) from public, anon, authenticated;
revoke execute on function public."hr_establishment_upsert"(p_payload jsonb) from public, anon, authenticated;
revoke execute on function public."hr_holiday_upsert"(p_payload jsonb) from public, anon, authenticated;
revoke execute on function public."hr_incident_assign"(p_incident_id uuid, p_employment_id uuid, p_reason text) from public, anon, authenticated;
revoke execute on function public."hr_leave_case_entitlement"(p_case_id uuid, p_as_of date) from public, anon, authenticated;
revoke execute on function public."hr_leave_case_get"(p_case_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_leave_case_list"(p_organization_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_leave_case_open"(p_employment_id uuid, p_case_kind text, p_continuity text, p_starts_on date, p_entitlement_hours numeric, p_entitlement_measure text, p_expected_return_on date, p_runs_concurrent_with_pto boolean, p_concurrent_policy_ids uuid[], p_leave_request_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_leave_policy_deactivate"(p_leave_policy_id uuid, p_disposition text, p_migrate_to_policy_id uuid, p_note text) from public, anon, authenticated;
revoke execute on function public."hr_mint_investigation_token"(p_incident_id uuid, p_investigator_email text, p_investigator_name text, p_reason text) from public, anon, authenticated;
revoke execute on function public."hr_mint_records_request_token"(p_request_id uuid, p_delivery_address text, p_scope text[], p_reason text) from public, anon, authenticated;
revoke execute on function public."hr_reporting_line_upsert"(p_payload jsonb) from public, anon, authenticated;
revoke execute on function public."hr_resolve_rules"(p_organization_id uuid, p_jurisdiction_key text, p_as_of date, p_classes text[]) from public, anon, authenticated;
revoke execute on function public."hr_role_assign"(p_employment_id uuid, p_role_key text, p_scope_kind text, p_scope_id uuid, p_scope_employment_ids uuid[], p_effective_from date, p_effective_to date, p_reason text) from public, anon, authenticated;
revoke execute on function public."hr_role_revoke"(p_assignment_id uuid, p_reason text) from public, anon, authenticated;
revoke execute on function public."hr_structure_deactivate"(p_kind text, p_id uuid) from public, anon, authenticated;
revoke execute on function public."hr_tax_registration_upsert"(p_payload jsonb) from public, anon, authenticated;
revoke execute on function public."hr_time_rounding_config_check"(p_organization_id uuid, p_rounding_minutes integer, p_rounding_mode text, p_jurisdiction_keys text[], p_as_of date) from public, anon, authenticated;
revoke execute on function public."hr_transfer"(p_payload jsonb) from public, anon, authenticated;

delete from platform.definer_client_grant_grandfather g
 where (g.schema_name, g.function_name, g.identity_args) in (
   ('public','hr_directory_list','p_organization_id uuid, p_filter jsonb, p_limit integer, p_offset integer, p_sort text, p_direction text'),
   ('public','hr_duplicate_scan','p_organization_id uuid, p_probe jsonb'),
   ('public','hr_emergency_contact_remove','p_id uuid'),
   ('public','hr_emergency_contact_upsert','p_payload jsonb'),
   ('public','hr_employee_by_party','p_organization_id uuid, p_party_id uuid'),
   ('public','hr_employee_create','p_payload jsonb'),
   ('public','hr_employee_grant_missing_membership','p_employee_id uuid'),
   ('public','hr_employee_invite','p_employee_id uuid, p_email text, p_expires_at timestamp with time zone'),
   ('public','hr_employee_profile','p_employee_id uuid, p_as_of date'),
   ('public','hr_employee_update','p_employee_id uuid, p_patch jsonb, p_expected_version integer'),
   ('public','hr_employer_profile_update','p_payload jsonb'),
   ('public','hr_employment_history','p_employee_id uuid'),
   ('public','hr_employment_set_pay_group','p_employment_id uuid, p_pay_group_id uuid'),
   ('public','hr_engagement_upsert','p_payload jsonb'),
   ('public','hr_establishment_upsert','p_payload jsonb'),
   ('public','hr_external_identity_upsert','p_payload jsonb'),
   ('public','hr_holiday_upsert','p_payload jsonb'),
   ('public','hr_incident_advance','p_incident_id uuid, p_state text, p_payload jsonb'),
   ('public','hr_incident_assign','p_incident_id uuid, p_employment_id uuid, p_reason text'),
   ('public','hr_incident_party_add','p_payload jsonb'),
   ('public','hr_invite_accept','p_token text'),
   ('public','hr_jurisdiction_rule_set_status','p_rule_id uuid, p_new_status text, p_reason text'),
   ('public','hr_jurisdiction_rules_admin_data',''),
   ('public','hr_kiosk_device_list','p_organization_id uuid'),
   ('public','hr_kiosk_device_set_capture','p_device_id uuid, p_require_photo boolean, p_require_geo boolean'),
   ('public','hr_kiosk_device_set_trust','p_device_id uuid, p_trust_state text, p_reason text'),
   ('public','hr_kiosk_pairing_code_create','p_organization_id uuid, p_device_name text, p_location_id uuid, p_device_id uuid'),
   ('public','hr_knob_clear','p_organization_id uuid, p_feature text, p_key text, p_scope_kind text, p_scope_id uuid'),
   ('public','hr_knob_index','p_organization_id uuid, p_overridden_only boolean'),
   ('public','hr_knob_set','p_organization_id uuid, p_feature text, p_key text, p_value jsonb, p_scope_kind text, p_scope_id uuid'),
   ('public','hr_law_portal_data','p_organization_id uuid'),
   ('public','hr_leave_adjust','p_employment_id uuid, p_leave_policy_id uuid, p_direction text, p_hours numeric, p_reason_category text, p_note text, p_confirm_below_floor boolean'),
   ('public','hr_leave_balances','p_organization_id uuid, p_scope text, p_filters jsonb'),
   ('public','hr_leave_balances_export','p_organization_id uuid, p_scope text, p_filters jsonb'),
   ('public','hr_leave_calendar','p_organization_id uuid, p_from date, p_to date, p_filters jsonb'),
   ('public','hr_leave_calendar_ics','p_organization_id uuid, p_from date, p_to date, p_filters jsonb'),
   ('public','hr_leave_case_entitlement','p_case_id uuid, p_as_of date'),
   ('public','hr_leave_case_get','p_case_id uuid'),
   ('public','hr_leave_case_list','p_organization_id uuid'),
   ('public','hr_leave_case_open','p_employment_id uuid, p_case_kind text, p_continuity text, p_starts_on date, p_entitlement_hours numeric, p_entitlement_measure text, p_expected_return_on date, p_runs_concurrent_with_pto boolean, p_concurrent_policy_ids uuid[], p_leave_request_id uuid'),
   ('public','hr_leave_enroll','p_leave_policy_id uuid, p_employment_ids uuid[], p_effective_from date, p_override_reason text'),
   ('public','hr_leave_ledger_export','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date'),
   ('public','hr_leave_ledger_view','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date'),
   ('public','hr_leave_policy_deactivate','p_leave_policy_id uuid, p_disposition text, p_migrate_to_policy_id uuid, p_note text'),
   ('public','hr_leave_policy_floors','p_organization_id uuid, p_payload jsonb'),
   ('public','hr_leave_policy_list','p_organization_id uuid'),
   ('public','hr_leave_policy_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean'),
   ('public','hr_leave_policy_validate','p_organization_id uuid, p_payload jsonb'),
   ('public','hr_leave_request_cancel','p_request_id uuid, p_reason text, p_hours numeric'),
   ('public','hr_leave_request_preview','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb'),
   ('public','hr_leave_request_submit','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb, p_reason_category_id uuid, p_reason_note text, p_leave_case_id uuid, p_idempotency_key text'),
   ('public','hr_member_employee_links','p_organization_id uuid, p_user_ids uuid[]'),
   ('public','hr_mint_investigation_token','p_incident_id uuid, p_investigator_email text, p_investigator_name text, p_reason text'),
   ('public','hr_mint_records_request_token','p_request_id uuid, p_delivery_address text, p_scope text[], p_reason text'),
   ('public','hr_module_set_enabled','p_organization_id uuid, p_enabled boolean'),
   ('public','hr_my_compensation','p_employment_id uuid, p_as_of date'),
   ('public','hr_my_context','p_organization_id uuid'),
   ('public','hr_my_time_off','p_employment_id uuid'),
   ('public','hr_my_verification_consents',''),
   ('public','hr_org_chart','p_organization_id uuid, p_on date'),
   ('public','hr_org_jurisdiction_rule_deactivate','p_organization_id uuid, p_rule_id uuid'),
   ('public','hr_org_jurisdiction_rule_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean'),
   ('public','hr_org_jurisdiction_rule_set_applies','p_organization_id uuid, p_rule_class text, p_jurisdiction_key text, p_applies boolean, p_reason text'),
   ('public','hr_org_summary','p_organization_id uuid'),
   ('public','hr_overtime_preapproval_create','p_employment_id uuid, p_covers_from timestamp with time zone, p_covers_to timestamp with time zone, p_requested_hours numeric, p_request_kind text, p_reason_category_id uuid, p_reason_note text, p_shift_ids uuid[]'),
   ('public','hr_overtime_preapproval_get','p_preapproval_id uuid'),
   ('public','hr_overtime_preapproval_list','p_filters jsonb, p_page jsonb'),
   ('public','hr_pay_group_upsert','p_payload jsonb'),
   ('public','hr_pay_period_generate','p_pay_group_id uuid, p_through_date date'),
   ('public','hr_pay_period_get','p_pay_period_id uuid'),
   ('public','hr_pay_period_list','p_filters jsonb, p_page jsonb'),
   ('public','hr_pay_period_transition','p_pay_period_id uuid, p_to_state text, p_reason text'),
   ('public','hr_payroll_export_list','p_organization_id uuid, p_pay_period_id uuid, p_limit integer'),
   ('public','hr_pending_change_cancel','p_kind text, p_id uuid, p_reason text'),
   ('public','hr_pending_changes','p_employment_id uuid'),
   ('public','hr_position_change','p_payload jsonb'),
   ('public','hr_punch_correct','p_punch_ids uuid[], p_new_values jsonb, p_reason text, p_category uuid'),
   ('public','hr_punch_record','p_employment_id uuid, p_kind text, p_occurred_at timestamp with time zone, p_source text, p_idempotency_key text, p_kiosk_session_id uuid, p_geo jsonb, p_photo_file_id uuid, p_attestation jsonb'),
   ('public','hr_punch_register','p_filters jsonb, p_page jsonb'),
   ('public','hr_punch_void','p_punch_id uuid, p_reason text'),
   ('public','hr_recompute_apply','p_employment_id uuid, p_workweek jsonb, p_intervals jsonb, p_engine jsonb, p_idempotency_key text'),
   ('public','hr_reporting_line_upsert','p_payload jsonb'),
   ('public','hr_resolve_rules','p_organization_id uuid, p_jurisdiction_key text, p_as_of date, p_classes text[]'),
   ('public','hr_restricted_get','p_token text, p_id uuid, p_purpose text, p_justification text'),
   ('public','hr_restricted_list','p_token text, p_filter jsonb, p_limit integer, p_cursor text, p_purpose text'),
   ('public','hr_restricted_note_add','p_payload jsonb'),
   ('public','hr_role_assign','p_employment_id uuid, p_role_key text, p_scope_kind text, p_scope_id uuid, p_scope_employment_ids uuid[], p_effective_from date, p_effective_to date, p_reason text'),
   ('public','hr_role_revoke','p_assignment_id uuid, p_reason text'),
   ('public','hr_self_update','p_token text, p_id uuid, p_patch jsonb'),
   ('public','hr_separation_record','p_payload jsonb'),
   ('public','hr_set_employment_pin','p_employment_id uuid, p_pin text'),
   ('public','hr_ssn_probe_authorize','p_organization_id uuid'),
   ('public','hr_ssn_store','p_employee_id uuid, p_ciphertext bytea, p_key_id text, p_hmac bytea, p_last4 text'),
   ('public','hr_structure_deactivate','p_kind text, p_id uuid'),
   ('public','hr_structure_list','p_organization_id uuid'),
   ('public','hr_structure_upsert','p_kind text, p_payload jsonb'),
   ('public','hr_tax_registration_upsert','p_payload jsonb'),
   ('public','hr_time_adjustment_create','p_employment_id uuid, p_original_pay_period_id uuid, p_work_date date, p_earning_code_id uuid, p_hours_delta numeric, p_amount_delta numeric, p_reason_category_id uuid, p_reason_note text'),
   ('public','hr_time_adjustment_list','p_filters jsonb, p_page jsonb'),
   ('public','hr_time_rounding_config_check','p_organization_id uuid, p_rounding_minutes integer, p_rounding_mode text, p_jurisdiction_keys text[], p_as_of date'),
   ('public','hr_timesheet_get','p_employment_id uuid, p_pay_period_id uuid'),
   ('public','hr_timesheet_period_grid','p_pay_period_id uuid, p_filters jsonb, p_page jsonb'),
   ('public','hr_transfer','p_payload jsonb'),
   ('public','hr_verification_consent','p_id uuid, p_granted boolean, p_note text'));

do $$
declare n int; m int;
begin
  select count(*) into n from platform.definer_client_grant_grandfather
   where (schema_name, function_name, identity_args) in (

     ('public','hr_directory_list','p_organization_id uuid, p_filter jsonb, p_limit integer, p_offset integer, p_sort text, p_direction text'),
     ('public','hr_duplicate_scan','p_organization_id uuid, p_probe jsonb'),
     ('public','hr_emergency_contact_remove','p_id uuid'),
     ('public','hr_emergency_contact_upsert','p_payload jsonb'),
     ('public','hr_employee_by_party','p_organization_id uuid, p_party_id uuid'),
     ('public','hr_employee_create','p_payload jsonb'),
     ('public','hr_employee_grant_missing_membership','p_employee_id uuid'),
     ('public','hr_employee_invite','p_employee_id uuid, p_email text, p_expires_at timestamp with time zone'),
     ('public','hr_employee_profile','p_employee_id uuid, p_as_of date'),
     ('public','hr_employee_update','p_employee_id uuid, p_patch jsonb, p_expected_version integer'),
     ('public','hr_employer_profile_update','p_payload jsonb'),
     ('public','hr_employment_history','p_employee_id uuid'),
     ('public','hr_employment_set_pay_group','p_employment_id uuid, p_pay_group_id uuid'),
     ('public','hr_engagement_upsert','p_payload jsonb'),
     ('public','hr_establishment_upsert','p_payload jsonb'),
     ('public','hr_external_identity_upsert','p_payload jsonb'),
     ('public','hr_holiday_upsert','p_payload jsonb'),
     ('public','hr_incident_advance','p_incident_id uuid, p_state text, p_payload jsonb'),
     ('public','hr_incident_assign','p_incident_id uuid, p_employment_id uuid, p_reason text'),
     ('public','hr_incident_party_add','p_payload jsonb'),
     ('public','hr_invite_accept','p_token text'),
     ('public','hr_jurisdiction_rule_set_status','p_rule_id uuid, p_new_status text, p_reason text'),
     ('public','hr_jurisdiction_rules_admin_data',''),
     ('public','hr_kiosk_device_list','p_organization_id uuid'),
     ('public','hr_kiosk_device_set_capture','p_device_id uuid, p_require_photo boolean, p_require_geo boolean'),
     ('public','hr_kiosk_device_set_trust','p_device_id uuid, p_trust_state text, p_reason text'),
     ('public','hr_kiosk_pairing_code_create','p_organization_id uuid, p_device_name text, p_location_id uuid, p_device_id uuid'),
     ('public','hr_knob_clear','p_organization_id uuid, p_feature text, p_key text, p_scope_kind text, p_scope_id uuid'),
     ('public','hr_knob_index','p_organization_id uuid, p_overridden_only boolean'),
     ('public','hr_knob_set','p_organization_id uuid, p_feature text, p_key text, p_value jsonb, p_scope_kind text, p_scope_id uuid'),
     ('public','hr_law_portal_data','p_organization_id uuid'),
     ('public','hr_leave_adjust','p_employment_id uuid, p_leave_policy_id uuid, p_direction text, p_hours numeric, p_reason_category text, p_note text, p_confirm_below_floor boolean'),
     ('public','hr_leave_balances','p_organization_id uuid, p_scope text, p_filters jsonb'),
     ('public','hr_leave_balances_export','p_organization_id uuid, p_scope text, p_filters jsonb'),
     ('public','hr_leave_calendar','p_organization_id uuid, p_from date, p_to date, p_filters jsonb'),
     ('public','hr_leave_calendar_ics','p_organization_id uuid, p_from date, p_to date, p_filters jsonb'),
     ('public','hr_leave_case_entitlement','p_case_id uuid, p_as_of date'),
     ('public','hr_leave_case_get','p_case_id uuid'),
     ('public','hr_leave_case_list','p_organization_id uuid'),
     ('public','hr_leave_case_open','p_employment_id uuid, p_case_kind text, p_continuity text, p_starts_on date, p_entitlement_hours numeric, p_entitlement_measure text, p_expected_return_on date, p_runs_concurrent_with_pto boolean, p_concurrent_policy_ids uuid[], p_leave_request_id uuid'),
     ('public','hr_leave_enroll','p_leave_policy_id uuid, p_employment_ids uuid[], p_effective_from date, p_override_reason text'),
     ('public','hr_leave_ledger_export','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date'),
     ('public','hr_leave_ledger_view','p_employment_id uuid, p_leave_policy_id uuid, p_as_of date'),
     ('public','hr_leave_policy_deactivate','p_leave_policy_id uuid, p_disposition text, p_migrate_to_policy_id uuid, p_note text'),
     ('public','hr_leave_policy_floors','p_organization_id uuid, p_payload jsonb'),
     ('public','hr_leave_policy_list','p_organization_id uuid'),
     ('public','hr_leave_policy_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean'),
     ('public','hr_leave_policy_validate','p_organization_id uuid, p_payload jsonb'),
     ('public','hr_leave_request_cancel','p_request_id uuid, p_reason text, p_hours numeric'),
     ('public','hr_leave_request_preview','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb'),
     ('public','hr_leave_request_submit','p_employment_id uuid, p_leave_policy_id uuid, p_starts_on date, p_ends_on date, p_day_parts jsonb, p_reason_category_id uuid, p_reason_note text, p_leave_case_id uuid, p_idempotency_key text'),
     ('public','hr_member_employee_links','p_organization_id uuid, p_user_ids uuid[]'),
     ('public','hr_mint_investigation_token','p_incident_id uuid, p_investigator_email text, p_investigator_name text, p_reason text'),
     ('public','hr_mint_records_request_token','p_request_id uuid, p_delivery_address text, p_scope text[], p_reason text'),
     ('public','hr_module_set_enabled','p_organization_id uuid, p_enabled boolean'),
     ('public','hr_my_compensation','p_employment_id uuid, p_as_of date'),
     ('public','hr_my_context','p_organization_id uuid'),
     ('public','hr_my_time_off','p_employment_id uuid'),
     ('public','hr_my_verification_consents',''),
     ('public','hr_org_chart','p_organization_id uuid, p_on date'),
     ('public','hr_org_jurisdiction_rule_deactivate','p_organization_id uuid, p_rule_id uuid'),
     ('public','hr_org_jurisdiction_rule_save','p_organization_id uuid, p_payload jsonb, p_accept_warnings boolean'),
     ('public','hr_org_jurisdiction_rule_set_applies','p_organization_id uuid, p_rule_class text, p_jurisdiction_key text, p_applies boolean, p_reason text'),
     ('public','hr_org_summary','p_organization_id uuid'),
     ('public','hr_overtime_preapproval_create','p_employment_id uuid, p_covers_from timestamp with time zone, p_covers_to timestamp with time zone, p_requested_hours numeric, p_request_kind text, p_reason_category_id uuid, p_reason_note text, p_shift_ids uuid[]'),
     ('public','hr_overtime_preapproval_get','p_preapproval_id uuid'),
     ('public','hr_overtime_preapproval_list','p_filters jsonb, p_page jsonb'),
     ('public','hr_pay_group_upsert','p_payload jsonb'),
     ('public','hr_pay_period_generate','p_pay_group_id uuid, p_through_date date'),
     ('public','hr_pay_period_get','p_pay_period_id uuid'),
     ('public','hr_pay_period_list','p_filters jsonb, p_page jsonb'),
     ('public','hr_pay_period_transition','p_pay_period_id uuid, p_to_state text, p_reason text'),
     ('public','hr_payroll_export_list','p_organization_id uuid, p_pay_period_id uuid, p_limit integer'),
     ('public','hr_pending_change_cancel','p_kind text, p_id uuid, p_reason text'),
     ('public','hr_pending_changes','p_employment_id uuid'),
     ('public','hr_position_change','p_payload jsonb'),
     ('public','hr_punch_correct','p_punch_ids uuid[], p_new_values jsonb, p_reason text, p_category uuid'),
     ('public','hr_punch_record','p_employment_id uuid, p_kind text, p_occurred_at timestamp with time zone, p_source text, p_idempotency_key text, p_kiosk_session_id uuid, p_geo jsonb, p_photo_file_id uuid, p_attestation jsonb'),
     ('public','hr_punch_register','p_filters jsonb, p_page jsonb'),
     ('public','hr_punch_void','p_punch_id uuid, p_reason text'),
     ('public','hr_recompute_apply','p_employment_id uuid, p_workweek jsonb, p_intervals jsonb, p_engine jsonb, p_idempotency_key text'),
     ('public','hr_reporting_line_upsert','p_payload jsonb'),
     ('public','hr_resolve_rules','p_organization_id uuid, p_jurisdiction_key text, p_as_of date, p_classes text[]'),
     ('public','hr_restricted_get','p_token text, p_id uuid, p_purpose text, p_justification text'),
     ('public','hr_restricted_list','p_token text, p_filter jsonb, p_limit integer, p_cursor text, p_purpose text'),
     ('public','hr_restricted_note_add','p_payload jsonb'),
     ('public','hr_role_assign','p_employment_id uuid, p_role_key text, p_scope_kind text, p_scope_id uuid, p_scope_employment_ids uuid[], p_effective_from date, p_effective_to date, p_reason text'),
     ('public','hr_role_revoke','p_assignment_id uuid, p_reason text'),
     ('public','hr_self_update','p_token text, p_id uuid, p_patch jsonb'),
     ('public','hr_separation_record','p_payload jsonb'),
     ('public','hr_set_employment_pin','p_employment_id uuid, p_pin text'),
     ('public','hr_ssn_probe_authorize','p_organization_id uuid'),
     ('public','hr_ssn_store','p_employee_id uuid, p_ciphertext bytea, p_key_id text, p_hmac bytea, p_last4 text'),
     ('public','hr_structure_deactivate','p_kind text, p_id uuid'),
     ('public','hr_structure_list','p_organization_id uuid'),
     ('public','hr_structure_upsert','p_kind text, p_payload jsonb'),
     ('public','hr_tax_registration_upsert','p_payload jsonb'),
     ('public','hr_time_adjustment_create','p_employment_id uuid, p_original_pay_period_id uuid, p_work_date date, p_earning_code_id uuid, p_hours_delta numeric, p_amount_delta numeric, p_reason_category_id uuid, p_reason_note text'),
     ('public','hr_time_adjustment_list','p_filters jsonb, p_page jsonb'),
     ('public','hr_time_rounding_config_check','p_organization_id uuid, p_rounding_minutes integer, p_rounding_mode text, p_jurisdiction_keys text[], p_as_of date'),
     ('public','hr_timesheet_get','p_employment_id uuid, p_pay_period_id uuid'),
     ('public','hr_timesheet_period_grid','p_pay_period_id uuid, p_filters jsonb, p_page jsonb'),
     ('public','hr_transfer','p_payload jsonb'),
     ('public','hr_verification_consent','p_id uuid, p_granted boolean, p_note text'));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_c): % grandfather row(s) named here survived', n; end if;
  select count(*) into m from platform.client_callable_door
   where declared_by = 'DD-169 batch 3 / B-75';
  if m < 83 then raise exception 'DD-169 batch 3 (dd169_batch3_public_c): expected at least 83 new door rows, found %', m; end if;
  -- every CLOSED function really lost every client grant
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where (ns.nspname, p.proname, pg_get_function_identity_arguments(p.oid)) in (

     ('public','hr_emergency_contact_remove','p_id uuid'),
     ('public','hr_employee_grant_missing_membership','p_employee_id uuid'),
     ('public','hr_employer_profile_update','p_payload jsonb'),
     ('public','hr_establishment_upsert','p_payload jsonb'),
     ('public','hr_holiday_upsert','p_payload jsonb'),
     ('public','hr_incident_assign','p_incident_id uuid, p_employment_id uuid, p_reason text'),
     ('public','hr_leave_case_entitlement','p_case_id uuid, p_as_of date'),
     ('public','hr_leave_case_get','p_case_id uuid'),
     ('public','hr_leave_case_list','p_organization_id uuid'),
     ('public','hr_leave_case_open','p_employment_id uuid, p_case_kind text, p_continuity text, p_starts_on date, p_entitlement_hours numeric, p_entitlement_measure text, p_expected_return_on date, p_runs_concurrent_with_pto boolean, p_concurrent_policy_ids uuid[], p_leave_request_id uuid'),
     ('public','hr_leave_policy_deactivate','p_leave_policy_id uuid, p_disposition text, p_migrate_to_policy_id uuid, p_note text'),
     ('public','hr_mint_investigation_token','p_incident_id uuid, p_investigator_email text, p_investigator_name text, p_reason text'),
     ('public','hr_mint_records_request_token','p_request_id uuid, p_delivery_address text, p_scope text[], p_reason text'),
     ('public','hr_reporting_line_upsert','p_payload jsonb'),
     ('public','hr_resolve_rules','p_organization_id uuid, p_jurisdiction_key text, p_as_of date, p_classes text[]'),
     ('public','hr_role_assign','p_employment_id uuid, p_role_key text, p_scope_kind text, p_scope_id uuid, p_scope_employment_ids uuid[], p_effective_from date, p_effective_to date, p_reason text'),
     ('public','hr_role_revoke','p_assignment_id uuid, p_reason text'),
     ('public','hr_structure_deactivate','p_kind text, p_id uuid'),
     ('public','hr_tax_registration_upsert','p_payload jsonb'),
     ('public','hr_time_rounding_config_check','p_organization_id uuid, p_rounding_minutes integer, p_rounding_mode text, p_jurisdiction_keys text[], p_as_of date'),
     ('public','hr_transfer','p_payload jsonb'))
     and (has_function_privilege('authenticated', p.oid, 'EXECUTE')
       or has_function_privilege('anon', p.oid, 'EXECUTE')
       or has_function_privilege('public', p.oid, 'EXECUTE'));
  if n <> 0 then raise exception 'DD-169 batch 3 (dd169_batch3_public_c): % closed function(s) still hold a client EXECUTE grant', n; end if;
end $$;
