-- DRIFT-AUDIT RESIDUE (2026-08-21, item 1 of 3) — take the illegal `visibility`
-- columns off the two `plan` COMPONENTS.
--
-- THE RULE BROKEN. db-rules §6d-1 THE COMPONENT OWNERSHIP LAW: *a component has
-- no owner column, NO OWN VISIBILITY, and its access IS its parent's.* A
-- component that carries `visibility` has a second, competing access authority
-- that nothing consults — `platform.create_entity_table` refuses
-- `p_visibility <> 'none'` on a component for exactly this reason.
--
-- WHY THESE TWO HAVE IT. `aidream/db/migrations/0344_plan_node_artifact_step.sql`
-- hand-rolled both tables (the create-as-entity-then-flip dance that was the
-- only way to make a component before 0364) roughly FIVE HOURS before the
-- Component Ownership Law was ruled on 2026-08-14. They are two of the four
-- stray-visibility components the db-rules historical note counts; the other two
-- (`crm.contact_candidate`, `seo.backlink_change_event`) are NOT touched here —
-- they are separately owned and separately scoped.
--
-- ============================================================================
-- THE VARIANT WAS RE-JUDGED FIRST, NOT ASSUMED — `component` IS CORRECT
-- ============================================================================
-- db-rules §6d-1 corollary: *if a sub-row needs its own owner with independent
-- access, it is NOT a component* — so the variant is checked BEFORE the column
-- is dropped, because dropping `visibility` off a mis-classified entity would be
-- the real defect. Verified live 2026-08-21:
--
--   1. BOTH have a real composition parent in `platform.entity_relationships`:
--        plan_node_artifact -> plan_node via node_id  (kind='composition')
--        plan_node_step     -> plan_node via node_id  (kind='composition')
--      `node_id` is NOT NULL on both, so no row can exist outside a plan node.
--   2. Their live policies are ALREADY the canonical component shape — the
--      parent-set form from the 2026-08-13 structural repair
--      (`node_id IN (SELECT unnest(iam.accessible_entity_ids('plan_node', …)))`)
--      and NOT ONE of them mentions `created_by`. Nothing reads `visibility`.
--   3. There is NO `pub_read` policy on either table, and never was — so the
--      column has never been able to expose a row to `anon`. Dropping it removes
--      no anon lane because none exists.
--   4. Neither is independently addressable: they are per-node pipeline state
--      (`node_step` = one pipeline step's status/attempts/error; `node_artifact`
--      = one step's output document). The frontend reads them only through the
--      node they hang off (`features/marketing/content-plan/`), the server
--      writes them only from the page/site pipelines. No surface asks for an
--      artifact or a step without already holding its node.
--   Conclusion: they are components of `plan_node`, the registration is right,
--   and the `visibility` column is the thing that does not belong.
--
-- ============================================================================
-- CONSUMER SWEEP — ZERO READERS (both repos, per changeover doctrine §8a)
-- ============================================================================
-- Swept `aidream`, `matrx-frontend`, `matrx-extend`, `matrx-local`,
-- `matrx-sandbox` for every reference to these two tables and then for
-- `visibility` within each hit:
--
--   * aidream `db/models/plan.py`, `db/managers/plan/node_{artifact,step}.py`,
--     `db/helpers/auto_config_plan.py` — GENERATED by `db/generate.py`. The
--     `load_/filter_node_*_by_visibility` helpers exist only because the column
--     does; they have ZERO call sites anywhere in any repo (grepped). They
--     disappear on the regen that accompanies this migration.
--   * aidream `services/content_plan/{generator,page_pipeline,site_pipeline,
--     artifacts,page_seo_plan,cms_fill}.py` — the real writers. None of them
--     sets or reads `visibility`; every insert relies on the column default.
--   * matrx-frontend `types/database.types.ts` — GENERATED by `pnpm db-types`.
--   * matrx-frontend `features/marketing/content-plan/**` — the real readers.
--     No runtime reference. The ONE hand-written mention in either repo is a
--     TEST FIXTURE, `lib/pipeline-progress.test.ts`, which builds a full
--     `PlanNodeStepRow` literal and therefore carries `visibility: "internal"`;
--     it is removed in the same commit as this migration, because after the
--     type regen it becomes a TS excess-property error.
--
--   Not one behavioural consumer. Nothing branches on the value.
--
-- ============================================================================
-- NO INFORMATION IS LOST
-- ============================================================================
-- Live census before this ran: `plan.node_artifact` 185 rows, `plan.node_step`
-- 167 rows, and EVERY ONE of the 352 is `visibility='internal'` — the column
-- default, never once overridden by anything. The column holds one constant, so
-- dropping it destroys no distinction that was ever drawn.
--
-- `entity_types.default_visibility` is set NULL for both tokens to match: NULL
-- is what 151 of the 190 live components carry, and it is what
-- `create_entity_table(p_visibility => 'none')` writes.
--
-- AFTERWARDS the migration re-runs `iam.apply_rls(...,'component')` so the
-- policy set is regenerated from the post-drop shape rather than left as the
-- residue of the old one (the generator only emits `pub_read` when a
-- `visibility` column exists — here it emitted none before and emits none now),
-- and asserts `iam.canonical_certify_ok` on both tokens, RAISING if either is
-- not clean. Certification is inside the transaction: a table that would not
-- certify does not get its column dropped.
--
--
-- 🚨 NOTE FOR THE NEXT AUDITOR — THE GATE IS BLIND TO THIS CLASS.
-- `iam.verify_canonical('plan','node_artifact','plan_node_artifact','component')`
-- reported `visibility  PASS` WHILE the illegal column was still there, and both
-- tokens returned `iam.canonical_certify_ok = true` BEFORE this migration ran.
-- The `visibility` check only asserts that a visibility column, if present, is
-- of type `platform.visibility`; it does not assert that a COMPONENT has none.
-- That is why this residue survived every conformance sweep and had to be found
-- by reading `create_entity_table`'s guardrails instead. Certification passing
-- is not evidence a component is clean of §6d-1 violations. Also confirmed live:
-- no view, no function body, and no index anywhere references either column.
--
-- Idempotent: DROP COLUMN IF EXISTS + regenerate + assert.

BEGIN;

ALTER TABLE plan.node_artifact DROP COLUMN IF EXISTS visibility;
ALTER TABLE plan.node_step     DROP COLUMN IF EXISTS visibility;

UPDATE platform.entity_types
   SET default_visibility = NULL
 WHERE token IN ('plan_node_artifact', 'plan_node_step');

SELECT iam.apply_rls('plan', 'node_artifact', 'plan_node_artifact', 'component');
SELECT iam.apply_rls('plan', 'node_step',     'plan_node_step',     'component');

DO $$
DECLARE
  v_table text;
BEGIN
  FOREACH v_table IN ARRAY ARRAY['node_artifact', 'node_step'] LOOP
    IF EXISTS (SELECT 1
                 FROM information_schema.columns
                WHERE table_schema = 'plan'
                  AND table_name = v_table
                  AND column_name = 'visibility') THEN
      RAISE EXCEPTION 'visibility column survived the drop on plan.%', v_table;
    END IF;
  END LOOP;

  IF NOT iam.canonical_certify_ok('plan', 'node_artifact', 'plan_node_artifact') THEN
    RAISE EXCEPTION 'plan_node_artifact does not certify canonical after the drop';
  END IF;
  IF NOT iam.canonical_certify_ok('plan', 'node_step', 'plan_node_step') THEN
    RAISE EXCEPTION 'plan_node_step does not certify canonical after the drop';
  END IF;
END $$;

COMMIT;
