-- CONTEXT BUNDLES — a saved, named, reusable answer to "what does this agent
-- get to see?"
--
-- Before this table, every research output was fed one blob: the assembled
-- report. A topic holds far more (search results, scraped pages, page
-- analyses, keyword syntheses, tag consolidations, media), and different jobs
-- want different slices — a brand profile wants people-bearing pages and rich
-- search results; a gap analysis wants the inventory itself; a literature
-- review wants full bodies ordered by authority. A bundle is that curation,
-- saved once and reused.
--
-- WHY RULES, NOT ID LISTS: `selectors` stores *rules* (kind + filter + order +
-- limit), with explicit ids only when a human hand-picked rows. A frozen id
-- list rots the moment the pipeline runs again and adds sources — the bundle
-- would silently keep feeding yesterday's research.
--
-- `entity_id IS NULL` = a TEMPLATE: a bundle that applies to any topic. That is
-- how a system bundle ("Brand Profile inputs") ships once and resolves against
-- whichever topic is running. `entity_id` set = a bundle saved for one topic.
--
-- No FK on entity_id: the column is polymorphic by design (entity_type names
-- the canonical entity token), so the constraint cannot be expressed. Lists
-- always filter by (entity_type, entity_id), so an orphan is invisible rather
-- than misleading.
--
-- Canonical model: this is an ENTITY (token `research_context_bundle`) — it is
-- shareable on its own and outlives any one topic, so it is NOT a component of
-- rs_topic. RLS is generated by iam.apply_rls; never hand-written.
--
-- Idempotent. Apply then: notify pgrst, 'reload schema'; pnpm db-types.

CREATE TABLE IF NOT EXISTS research.rs_context_bundle (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Canonical entity token this bundle curates ('research_topic' today).
  entity_type     text NOT NULL DEFAULT 'research_topic',
  -- NULL = reusable template; set = saved for that one entity instance.
  entity_id       uuid,

  name            text NOT NULL,
  description     text,
  -- Stable key for idempotent seeding of system bundles.
  slug            text,

  -- ResourceSelector[] — see features/research/resources/types.ts
  selectors       jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- Array<{ variable, kinds[] }> — which resources fill which agent variable.
  bindings        jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- { maxTokens } — the ceiling the resolver enforces (and reports against).
  budget          jsonb,

  -- Optional default agent this bundle was authored for.
  agent_id        uuid REFERENCES agent.definition(id) ON DELETE SET NULL,
  is_system       boolean NOT NULL DEFAULT false,

  organization_id uuid,
  created_by      uuid,
  updated_by      uuid,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  version         integer NOT NULL DEFAULT 1,
  visibility      platform.visibility NOT NULL DEFAULT 'personal',
  deleted_at      timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS rs_context_bundle_slug_key
  ON research.rs_context_bundle (slug) WHERE slug IS NOT NULL;
CREATE INDEX IF NOT EXISTS rs_context_bundle_entity_idx
  ON research.rs_context_bundle (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS rs_context_bundle_owner_idx
  ON research.rs_context_bundle (created_by);
CREATE INDEX IF NOT EXISTS rs_context_bundle_system_idx
  ON research.rs_context_bundle (is_system) WHERE is_system;

-- Platform base-entity behaviour (updated_at/version bump + actor stamping).
DROP TRIGGER IF EXISTS _touch_row ON research.rs_context_bundle;
CREATE TRIGGER _touch_row BEFORE INSERT OR UPDATE ON research.rs_context_bundle
  FOR EACH ROW EXECUTE FUNCTION platform._touch_row();
DROP TRIGGER IF EXISTS _stamp_actor ON research.rs_context_bundle;
CREATE TRIGGER _stamp_actor BEFORE INSERT OR UPDATE ON research.rs_context_bundle
  FOR EACH ROW EXECUTE FUNCTION platform._stamp_actor();

INSERT INTO platform.entity_types
  (token, schema_name, table_name, label, default_visibility,
   is_component, is_versioned, has_soft_delete, is_active, is_listed, category,
   title_column)
SELECT 'research_context_bundle', 'research', 'rs_context_bundle',
       'Research Context Bundle', 'personal', false, false, true, true, true,
       'research', 'name'
WHERE NOT EXISTS (
  SELECT 1 FROM platform.entity_types WHERE token = 'research_context_bundle'
);

SELECT iam.apply_rls('research', 'rs_context_bundle', 'research_context_bundle', 'entity');

GRANT SELECT, INSERT, UPDATE, DELETE ON research.rs_context_bundle TO authenticated;
GRANT ALL ON research.rs_context_bundle TO service_role;

NOTIFY pgrst, 'reload schema';
