-- GSC ingestion-health coverage index.
--
-- `seo.gsc_ingestion_health` computes MIN(date), MAX(date), and
-- COUNT(DISTINCT date) across every non-search-appearance GSC profile for one
-- site.  The general GSC read index is ordered (site_id, dimension_profile,
-- date), which cannot stream distinct dates across profiles and made this
-- lightweight health banner exceed the statement timeout on large sites.
--
-- A canceled concurrent build leaves an invalid index with the same name.
-- Recovery and creation must be separate migrations because PostgreSQL will
-- not execute two CONCURRENTLY statements in one implicit transaction.
DROP INDEX CONCURRENTLY IF EXISTS seo.idx_seo_sperf_gsc_health_coverage;
