-- Surface sync: matrx-public/p — every /p render path now emits the surface
-- (built-in shells + fully_custom via useAgentApp, no-shell apps via CustomComponentRenderer).
-- Emitted by: pnpm tsx scripts/emit-surface-sync-sql.ts --surface matrx-public/p

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-public/p', 'app_id', 'App ID', 'UUID of the published `app.definition` row being run (`app.id`). Always available — the page 404s before rendering if the slug/id does not resolve to a published, public app.', 'string', true, 36, 100, true, 'app_identity'),
('matrx-public/p', 'app_slug', 'App slug', 'The app''s public URL slug (`app.slug`), as used in `/p/[slug]`. Always available.', 'string', true, 40, 110, true, 'app_identity'),
('matrx-public/p', 'app_name', 'App name', 'Display name of the app (`app.name`). Always available.', 'string', true, 60, 120, true, 'app_identity'),
('matrx-public/p', 'agent_id', 'Bound agent ID', 'UUID of the `agent.definition` the app is bound to (`app.agent_id`) — the agent `launchAgentExecution` runs on submit. Always available.', 'string', true, 36, 130, false, 'app_identity'),
('matrx-public/p', 'agent_version_id', 'Pinned agent version ID', 'UUID of the pinned `agx_version` row when the app is NOT configured to use_latest (`app.agent_version_id`). Empty when the app tracks the agent''s latest published version.', 'string', false, 36, 140, false, 'app_identity'),
('matrx-public/p', 'shell_kind', 'Shell kind', 'Which top-level UI shell renders the app (`app.shell_kind`) — e.g. "chat", "form_to_result", "widget", "fully_custom". Always available. `?embed=widget` forces "widget" regardless of the row''s configured kind.', 'string', true, 16, 150, false, 'app_identity'),
('matrx-public/p', 'is_authenticated', 'Visitor is signed in', 'True when the visitor has a real Supabase session; false for an anonymous guest identified only by fingerprint. Always available.', 'boolean', true, 5, 200, true, 'visitor'),
('matrx-public/p', 'guest_fingerprint_id', 'Guest fingerprint ID', 'Browser fingerprint identifying an anonymous visitor across runs (`X-Fingerprint-ID`), used in place of a user id for guest rate limiting. Empty once the visitor is authenticated or before the fingerprint has resolved.', 'string', false, 40, 210, false, 'visitor'),
('matrx-public/p', 'guest_runs_remaining', 'Guest runs remaining', 'Free executions left for this anonymous guest before signup is required (from `useGuestLimit`). Meaningless once `is_authenticated` is true.', 'number', false, 2, 220, false, 'visitor'),
('matrx-public/p', 'user_input', 'User message', 'Free-text message the visitor typed for this run, passed as `runtime.userInput` to the agent. Empty for apps whose custom UI collects only form variables and no chat-style message.', 'string', false, 300, 300, true, 'run_input'),
('matrx-public/p', 'form_variable_values', 'Form variable values', 'The visitor''s submitted form values, validated and coerced against `app.variable_schema` (string/number/boolean per field, required fields defaulted or flagged). Object keyed by variable name. Empty object for apps with no declared variables.', 'object', false, 400, 310, true, 'run_input'),
('matrx-public/p', 'conversation_id', 'Conversation ID', 'UUID of the `cx_conversation` row created for this run, captured synchronously via `onConversationCreated` right after the launcher creates it. Empty until the visitor''s first submit of this page view.', 'string', false, 36, 400, true, 'run_state'),
('matrx-public/p', 'run_status', 'Run status', 'Status of the active/most-recent execution''s request: "streaming", "complete", "error", or empty before any run has started this page view.', 'string', false, 12, 410, false, 'run_state'),
('matrx-public/p', 'response_text', 'Response text', 'Accumulated streamed text of the current/most recent run, read live from Redux (`selectAccumulatedText`). Empty before the first run completes any output.', 'string', false, 2000, 420, false, 'run_state'),
('matrx-public/p', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-public/p', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-public/p', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-public/p', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-public/p', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'Public Agent App', value_groups = '[{"key":"app_identity","label":"App identity","sortOrder":100,"description":"Which published app.definition row is running and the agent it is bound to."},{"key":"visitor","label":"Visitor","sortOrder":200,"description":"Who is running the app: a signed-in user or an anonymous guest identified by browser fingerprint, plus the guest run-limit state."},{"key":"run_input","label":"Run input","sortOrder":300,"description":"What the visitor supplied for this run: the free-text message and the form variable values validated against the app''s variable_schema."},{"key":"run_state","label":"Run state","sortOrder":400,"description":"The resulting conversation and the live/streamed outcome of the current or most recent execution."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'All five /p render paths now emit (built-in shells + fully_custom via useAgentApp, no-shell apps via CustomComponentRenderer). Two gaps remain: (1) no live agent-binding / Matrx-vs-matrix verification against an anonymous session; (2) on the shell paths the launch happens at mount, so the run_input values (user_input, form_variable_values) are EMPTY in the mapped launch scope — the visitor fills the form after the instance exists, and the later submit goes through smartExecute, which does not re-run value_mappings. Agents bound to run_input values get them live only from the Agents-chrome Run path. Binding run_input at submit needs a scope-refresh seam in the execution system.', url_pattern = '/p', intro = '<surface_intro>
You are bound to a PUBLISHED, PUBLIC agent app running for an anonymous or newly-arrived visitor at /p/[slug] — not the app''s builder/owner. App identity tells you which app.definition row and which agent are running. Visitor tells you whether this person is signed in or an anonymous guest tracked only by browser fingerprint, and how many free guest runs remain — anonymous guests are the common case here, never assume a logged-in user. Run input is what THIS visitor just submitted (a typed message and/or form variable values validated against the app''s schema); read it as their actual request, not a template. Run state is the resulting conversation and the live/streamed response for their run.
Treat this like any first-contact interaction with a stranger: no prior context about this person exists beyond what is declared here.
</surface_intro>', updated_at = now() WHERE name = 'matrx-public/p';
