-- Guard: manifest surfaces missing a ui_surface row
SELECT s.name FROM (VALUES ('matrx-user/ai-results'), ('matrx-user/education-audio-study'), ('matrx-user/education-game'), ('matrx-user/education-learn'), ('matrx-user/education-progress'), ('matrx-user/image-uploader'), ('matrx-user/canvas-viewer'), ('matrx-user/observational-memory'), ('matrx-user/agent-gate'), ('matrx-user/agent-run-history'), ('matrx-admin/users'), ('matrx-admin/knowledge'), ('matrx-admin/kind-registry'), ('matrx-admin/skills')) AS s(name) LEFT JOIN ui.ui_surface u ON u.name = s.name WHERE u.name IS NULL;

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-user/ai-results', 'selected_conversation_id', 'Selected conversation ID', 'UUID of the past conversation/run the user has selected. Empty when none is selected.', 'string', false, 36, 300, true, 'general'),
('matrx-user/ai-results', 'selected_conversation_title', 'Selected conversation title', 'Title of the selected past run. Empty when none is selected.', 'string', false, 80, 310, true, 'general'),
('matrx-user/ai-results', 'selected_conversation_agent_id', 'Selected run agent ID', 'UUID of the agent that produced the selected run. Empty when none is selected.', 'string', false, 36, 320, true, 'general'),
('matrx-user/ai-results', 'selected_conversation_agent_name', 'Selected run agent name', 'Name of the agent that produced the selected run. Empty when none is selected.', 'string', false, 60, 325, true, 'general'),
('matrx-user/ai-results', 'selected_conversation_message_count', 'Selected run message count', 'Number of messages in the selected run. Zero when none is selected.', 'number', false, 5, 330, true, 'general'),
('matrx-user/ai-results', 'selected_run_status', 'Selected run status', '"complete", "error", "cancelled", etc. — final status of the selected run. Empty when none is selected.', 'string', false, 12, 335, true, 'general'),
('matrx-user/ai-results', 'last_run_text', 'Last run output', 'Text of the final assistant message in the selected run. Empty when none is selected.', 'string', false, 2000, 340, true, 'general'),
('matrx-user/ai-results', 'agent_filter', 'Agent filter', 'Array of agent IDs the history view is currently filtered to. Empty array when unfiltered.', 'array', false, 200, 360, true, 'general'),
('matrx-user/ai-results', 'grouping_mode', 'Grouping mode', 'How the history list is currently grouped (e.g. "agent", "date", "none"). Empty when default.', 'string', false, 12, 365, true, 'general'),
('matrx-user/ai-results', 'search_query', 'Search query', 'Active history search string. Empty when the search box is blank.', 'string', false, 60, 370, true, 'general'),
('matrx-user/ai-results', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/ai-results', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/ai-results', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/ai-results', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/ai-results', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/education-audio-study', 'view', 'Current view', 'Which Audio Study view is open: "list" (the saved-studies home), "new" (the generation composer), "detail" (one study open — player or live run), or "review" (a live spoken quiz session). Always present when the surface emits at all — the read-only `/[id]/edit` access-gate route renders the same detail view and reports "detail".', 'string', true, 6, 300, true, 'tool_view'),
('matrx-user/education-audio-study', 'library_loaded', 'Library loaded', 'True once the saved audio studies have finished loading on the list view. False while still in flight — do not describe the library as empty until this is true. Absent on the other views.', 'boolean', false, 5, 300, true, 'audio_library'),
('matrx-user/education-audio-study', 'audio_count', 'Saved audio studies', 'How many audio studies the learner can see, after RLS filtering. 0 when the library is genuinely empty. Only present on the list view once loaded.', 'number', false, 3, 310, true, 'audio_library'),
('matrx-user/education-audio-study', 'audio_library', 'Audio library', 'Every saved audio study on the list view, as { id, title, format, source_title, status } — status is ''ready'' | ''error'' | in-progress. Empty array when the learner has none. Only present on the list view.', 'array', false, 900, 320, true, 'audio_library'),
('matrx-user/education-audio-study', 'request_source_kind', 'Source kind', 'Which source mode the composer is in: "deck" (build audio from one of the learner''s flashcard decks) or "topic" (build it from free text they type). Only present on the new view.', 'string', false, 5, 300, true, 'generation_request'),
('matrx-user/education-audio-study', 'request_deck_id', 'Selected deck', 'UUID of the flashcard deck the audio will be built from. Absent when the composer is in topic mode or no deck has been picked yet.', 'string', false, 36, 310, true, 'generation_request'),
('matrx-user/education-audio-study', 'request_topic', 'Topic', 'The free-text topic the learner typed to build audio from (e.g. "The causes of the French Revolution"). Absent in deck mode or while the box is still empty.', 'string', false, 60, 320, true, 'generation_request'),
('matrx-user/education-audio-study', 'request_format', 'Format', '"overview" (narrated walkthrough), "debate" (two opposing voices), or "panel" (multi-host roundtable). Always present on the new view — the composer opens on "overview" by default.', 'string', false, 8, 330, true, 'generation_request'),
('matrx-user/education-audio-study', 'request_host_count', 'Host count', 'How many voices the produced audio will use — 2 by default, 3-6 for a panel. Always present on the new view.', 'number', false, 1, 340, true, 'generation_request'),
('matrx-user/education-audio-study', 'request_adaptive', 'Target weak areas', 'True when the "target my weak areas" option is checked (deck mode only) — biases the produced audio toward concepts the learner has been struggling with, from FSRS study history. Always present in deck mode on the new view; meaningless in topic mode.', 'boolean', false, 5, 350, true, 'generation_request'),
('matrx-user/education-audio-study', 'generation_request', 'Generation request', 'The whole composer state as one object — source kind, the deck id or typed topic, format, host count, and the weak-areas toggle. The composite twin of the values above; present on the new view whenever any of them is.', 'object', false, 260, 360, true, 'generation_request'),
('matrx-user/education-audio-study', 'available_decks', 'Available decks', 'The flashcard decks offered in the composer''s deck picker, each with its id and name. Empty array when the learner has no decks; absent until the picker''s list has loaded. Only present on the new view.', 'array', false, 1200, 370, true, 'generation_request'),
('matrx-user/education-audio-study', 'record_loaded', 'Study loaded', 'True once the open audio study''s row has finished loading on the detail view. False while it is in flight or when the id is missing/denied — in which case the record values below are absent. Absent on the other views.', 'boolean', false, 5, 300, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_id', 'Audio study id', 'UUID of the audio study the learner has open (its `education.study_media` row id). Present on the detail view from the first render, before the row itself has loaded.', 'string', false, 36, 310, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_title', 'Audio study title', 'Title of the open audio study, as generated and stored. Absent until the row has loaded.', 'string', false, 60, 320, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_format', 'Format', '"overview", "debate", "panel", or "review" — the format this study was generated in. Absent until the row has loaded.', 'string', false, 8, 330, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_status', 'Study status', '"ready" once produced audio exists, "error" if generation failed, otherwise still generating. Absent until the row has loaded.', 'string', false, 9, 340, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_is_ready', 'Playback ready', 'True when a durable audio file (or a produced episode) exists and the ready player renders. False while a run is live/being recovered, in which case the page shows the streaming generation view instead. Absent until the row has loaded.', 'boolean', false, 5, 350, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_is_owner', 'Viewer owns this study', 'True when the current user owns the open audio study and therefore sees the regenerate / share / delete controls. False for a shared viewer listening to someone else''s audio. Absent until access has resolved.', 'boolean', false, 5, 360, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_source_kind', 'Built from', '"deck" or "topic" — what the open study was generated from. Absent until the row has loaded.', 'string', false, 5, 370, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_source_title', 'Source name', 'Human name of the deck or topic the open study was built from, shown as "from …" above the title. Absent when the stored row recorded no source title.', 'string', false, 50, 380, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_source_id', 'Source id', 'UUID of the deck the open study was built from. Absent for a free-text topic source, which has no record to point at.', 'string', false, 36, 390, false, 'audio_record'),
('matrx-user/education-audio-study', 'run_status', 'Live run status', 'The streaming generation run''s status when the study is not yet ready — "running", "error", or absent once `audio_is_ready` is true (the page renders the durable player instead). Absent on the ready path and until the row has loaded.', 'string', false, 8, 400, true, 'audio_record'),
('matrx-user/education-audio-study', 'audio_confidence', 'Grounding confidence', 'How well the open study is grounded in real source material — "grounded" when built from a deck with citations, "inferred" when built from a typed topic. Absent when the row carries no trust envelope.', 'string', false, 10, 300, true, 'audio_trust'),
('matrx-user/education-audio-study', 'audio_citations', 'Cited sources', 'The passages the open study is grounded in, from its stored trust envelope. Empty array for an inferred (topic-built) study. Derived evidence — never authored on this page.', 'array', false, 400, 310, false, 'audio_trust'),
('matrx-user/education-audio-study', 'review_phase', 'Review phase', '"setup" (picking a deck), "asking" (question read aloud), "answering" (learner speaking), "grading" (spoken answer being graded), "result" (verdict shown), or "summary" (session complete). No emitter mounts this surface on /education/audio-study/review yet, so this value is currently NEVER emitted at runtime — declared for when that gap closes.', 'string', false, 9, 300, true, 'review_session'),
('matrx-user/education-audio-study', 'review_deck_id', 'Review deck', 'UUID of the flashcard deck the live review session is drawing questions from. Not currently emitted — see review_phase.', 'string', false, 36, 310, true, 'review_session'),
('matrx-user/education-audio-study', 'review_card_index', 'Review progress', '0-based index of the card currently being asked, out of the session''s card count. Not currently emitted — see review_phase.', 'number', false, 2, 320, true, 'review_session'),
('matrx-user/education-audio-study', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/education-audio-study', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/education-audio-study', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/education-audio-study', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/education-audio-study', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/education-game', 'view', 'Current view', 'Which Study Games route the learner is on: "home" (the hub — streak, league, badges, and the three primary actions), "host" (the room-creation composer), "join" (the room-code entry), "solo" (a live single-player run), or "play" (a live multiplayer room). Always present when the surface emits at all — "solo" and "play" currently never emit (see manifest header).', 'string', true, 4, 300, true, 'tool_view'),
('matrx-user/education-game', 'host_source_kind', 'Room source kind', '"due" (the learner''s cross-deck due queue — the adaptive default) or "set" (one specific flashcard deck). Only present on the host view.', 'string', false, 3, 300, true, 'host_setup'),
('matrx-user/education-game', 'host_source_set_id', 'Selected deck', 'UUID of the flashcard deck picked as the room''s question source. Absent when host_source_kind is "due" or no deck has been picked yet.', 'string', false, 36, 310, true, 'host_setup'),
('matrx-user/education-game', 'host_source_set_name', 'Selected deck name', 'Name of the currently selected deck. Absent when host_source_kind is "due" or no deck is picked.', 'string', false, 40, 320, true, 'host_setup'),
('matrx-user/education-game', 'host_available_sets', 'Available decks', 'The learner''s flashcard decks offered in the host picker, each with id, name, and whether it is private (only the host can load its cards — a cross-account room needs a shared/public deck). Empty array when they have none; absent until the picker''s list has loaded. Only present on the host view.', 'array', false, 1200, 330, true, 'host_setup'),
('matrx-user/education-game', 'host_max_players', 'Max players', 'The room-size cap the room will be created with, from the education.game_room_size entitlement (shown before hosting, per the TRUST mandate — never a mid-workflow ambush). Always present on the host view.', 'number', false, 2, 340, true, 'host_setup'),
('matrx-user/education-game', 'host_creating', 'Creating room', 'True while the Create room button''s request is in flight. Absent on the other views.', 'boolean', false, 5, 350, true, 'host_setup'),
('matrx-user/education-game', 'join_code', 'Room code', 'The 5-character room code the learner has typed so far (uppercased as they type). Empty string before they type anything. Only present on the join view.', 'string', false, 5, 300, true, 'join_room'),
('matrx-user/education-game', 'join_error', 'Join error', 'The validation or lookup error shown under the code field — e.g. a too-short code or "No open room with that code." Absent whenever there is no error, which is the normal case.', 'string', false, 40, 310, true, 'join_room'),
('matrx-user/education-game', 'join_joining', 'Joining room', 'True while the room lookup is in flight. Absent on the other views.', 'boolean', false, 5, 320, true, 'join_room'),
('matrx-user/education-game', 'solo_source_set_id', 'Solo deck', 'UUID of the deck the solo-arcade run is drawing questions from, when launched with a ?set= deep link. Not currently emitted — see manifest header.', 'string', false, 36, 300, true, 'solo_session'),
('matrx-user/education-game', 'solo_score', 'Solo score', 'The learner''s running score in the live solo-arcade session. Not currently emitted — see manifest header.', 'number', false, 4, 310, true, 'solo_session'),
('matrx-user/education-game', 'room_id', 'Room id', 'UUID of the multiplayer room the learner is in on /education/game/play/[roomId]. Not currently emitted — see manifest header.', 'string', false, 36, 300, true, 'room_session'),
('matrx-user/education-game', 'room_phase', 'Room phase', 'Which stage the live room is in — lobby, playing, or results. Not currently emitted — see manifest header.', 'string', false, 7, 310, true, 'room_session'),
('matrx-user/education-game', 'room_player_count', 'Players in room', 'How many players are currently in the room (host + joiners), from Broadcast presence. Not currently emitted — see manifest header.', 'number', false, 2, 320, true, 'room_session'),
('matrx-user/education-game', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/education-game', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/education-game', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/education-game', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/education-game', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/education-learn', 'view', 'Current view', 'Which public reader page is open: "index" (the study-guide library at /education/learn) or "article" (one open guide at /education/learn/[...slug]). Declared for completeness; NOT currently emitted at runtime — see the manifest header.', 'string', false, 7, 300, true, 'reader_view'),
('matrx-user/education-learn', 'guide_count', 'Published guide count', 'How many study guides are published and listed on the index. Zero is possible before the first guide ships. Only meaningful on the index view.', 'number', false, 3, 300, true, 'guide_library'),
('matrx-user/education-learn', 'guide_library', 'Guide library', 'Every published study guide listed on the index, as { title, summary, href }, in the order the index server-computes them. Only meaningful on the index view.', 'array', false, 2000, 310, true, 'guide_library'),
('matrx-user/education-learn', 'article_slug', 'Guide slug', 'URL path of the open guide under /education/learn (may contain ''/'' for hierarchy, e.g. ''biology/cell-structure''). Only meaningful on the article view.', 'string', false, 30, 300, true, 'guide_article'),
('matrx-user/education-learn', 'article_title', 'Guide title', 'Headline of the open guide, rendered as the page''s <h1>. Only meaningful on the article view.', 'string', false, 60, 310, true, 'guide_article'),
('matrx-user/education-learn', 'article_summary', 'Guide summary', 'Short summary of the open guide, shown as the hero lede and used verbatim as the meta description. Only meaningful on the article view.', 'string', false, 200, 320, true, 'guide_article'),
('matrx-user/education-learn', 'article_subject', 'Guide subject', 'The subject slug the open guide belongs to (e.g. ''biology''), when set. Absent for a guide with no subject assigned.', 'string', false, 12, 330, true, 'guide_article'),
('matrx-user/education-learn', 'article_keywords', 'Guide keywords', 'SEO keywords stored on the open guide. Empty array when none were set.', 'array', false, 100, 340, true, 'guide_article'),
('matrx-user/education-learn', 'article_updated', 'Guide updated', 'The author-controlled content date shown to readers as ''Updated'', in YYYY-MM-DD form.', 'string', false, 10, 350, true, 'guide_article'),
('matrx-user/education-learn', 'article_sections', 'Guide body', 'The open guide''s article body — the full parsed EduSection[] the page renders (prose, feature-grid, steps, status-cards, stat-bar, faq, cta blocks). The whole content a visitor is reading. Large; bindable-only.', 'array', false, 6000, 360, false, 'guide_article'),
('matrx-user/education-learn', 'article_related', 'Related links', 'The open guide''s conversion cross-links — { tools?, subjects?, exams? } slug arrays — deciding which app tools and hub pages the page funnels the reader into.', 'object', false, 160, 370, true, 'guide_article'),
('matrx-user/education-learn', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/education-learn', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/education-learn', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/education-learn', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/education-learn', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/education-progress', 'view', 'Current view', 'Which Progress view is open: "dashboard" (the cross-mode analytics dashboard) or "learning_gain" (the pre/post learning-gain report). Always present.', 'string', true, 13, 300, true, 'progress_view'),
('matrx-user/education-progress', 'analytics_loading', 'Analytics loading', 'True while the cross-mode analytics are still being fetched/folded on the dashboard view. While true, the summary values below are absent. Absent on the learning_gain view.', 'boolean', false, 5, 300, true, 'analytics_summary'),
('matrx-user/education-progress', 'analytics_error', 'Analytics error', 'The error message shown when the analytics fetch failed. Absent on the happy path (the common case) and on the learning_gain view.', 'string', false, 80, 310, true, 'analytics_summary'),
('matrx-user/education-progress', 'analytics_has_data', 'Has data', 'True once the learner has studied enough for the analytics to be meaningful. False for a brand-new learner with an empty spine — in which case the numeric fields below are still present but all-zero, and no AI narrative is generated. Absent while loading and on the learning_gain view.', 'boolean', false, 5, 320, true, 'analytics_summary'),
('matrx-user/education-progress', 'overall_stats', 'Overall stats', 'The learner''s folded cross-mode totals as one object — { studied, mastered, learning, struggling, dueNow, totalAttempts, correctAttempts, accuracyPct, bestStreak }. accuracyPct is null when totalAttempts is 0. Absent while loading and on the learning_gain view.', 'object', false, 160, 330, true, 'analytics_summary'),
('matrx-user/education-progress', 'mode_stats', 'Stats by mode', 'Per-study-mode breakdown (flashcards, quizzes, practice tests, …), each the same shape as overall_stats plus { itemType, label }. Empty array for a mode the learner hasn''t tried. Absent while loading and on the learning_gain view.', 'array', false, 900, 340, true, 'analytics_summary'),
('matrx-user/education-progress', 'weak_topics', 'Weak topics', 'Per-topic breakdown for the topic-bearing mode (flashcards), weakest first — each { topic, count, masteryPct, struggling }. Empty array when there isn''t enough topic-tagged data yet. Absent while loading and on the learning_gain view.', 'array', false, 700, 350, true, 'analytics_summary'),
('matrx-user/education-progress', 'total_minutes', 'Total study minutes', 'Total minutes studied across all sessions and modes. Absent while loading and on the learning_gain view.', 'number', false, 4, 360, true, 'analytics_summary'),
('matrx-user/education-progress', 'session_count', 'Session count', 'Total number of study sessions recorded. Absent while loading and on the learning_gain view.', 'number', false, 3, 370, true, 'analytics_summary'),
('matrx-user/education-progress', 'current_streak', 'Current streak', 'Current daily study streak in days (from study_streak — distinct from any per-item mastery streak). Absent while loading and on the learning_gain view.', 'number', false, 3, 380, true, 'analytics_summary'),
('matrx-user/education-progress', 'accuracy_trend', 'Accuracy trend', 'How accuracy is moving week over week — { direction: "improving" | "flat" | "declining", recentPct, priorPct, weeks }. Absent when there isn''t enough history to compute a trend, while loading, and on the learning_gain view.', 'object', false, 90, 390, true, 'analytics_summary'),
('matrx-user/education-progress', 'gain_teaser_available', 'Learning-gain teaser available', 'True when the dashboard has a learning-gain report to tease (linking to the learning_gain view). Absent while loading and on the learning_gain view.', 'boolean', false, 5, 400, true, 'analytics_summary'),
('matrx-user/education-progress', 'narrative_loading', 'Narrative generating', 'True while the AI narrator is producing the headline/insights/recommendations. Absent on the learning_gain view. The dashboard auto-narrates once when analytics_has_data is true and overall_stats.studied is at least 3.', 'boolean', false, 5, 300, true, 'analytics_narrative'),
('matrx-user/education-progress', 'narrative_error', 'Narrative error', 'Error from the narration attempt, if any. Absent on the happy path — narration is optional chrome, so a failure here does not affect the numeric analytics. Absent on the learning_gain view.', 'string', false, 80, 310, true, 'analytics_narrative'),
('matrx-user/education-progress', 'narrative_headline', 'Narrative headline', 'The AI narrator''s one-line summary of the learner''s current standing. Absent before narration has run, while it is loading, on an error, and on the learning_gain view.', 'string', false, 90, 320, true, 'analytics_narrative'),
('matrx-user/education-progress', 'narrative_insights', 'Narrative insights', 'Grounded observations from the narrator, each { title, detail, severity: "good" | "watch" | "urgent" }. Absent under the same conditions as narrative_headline.', 'array', false, 600, 330, true, 'analytics_narrative'),
('matrx-user/education-progress', 'narrative_recommendations', 'Narrative recommendations', 'Prioritized next actions from the narrator, each { action, why, targetKind, topic }, where targetKind is one of "review" | "weak_area" | "learn" | "quiz" | "practice_test" or null. Absent under the same conditions as narrative_headline. This is the surface''s own best answer to "what should I study next" — read it before improvising a recommendation.', 'array', false, 500, 340, true, 'analytics_narrative'),
('matrx-user/education-progress', 'gain_loading', 'Report loading', 'True while the learning-gain report is still being fetched on the learning_gain view. Absent on the dashboard view.', 'boolean', false, 5, 300, true, 'gain_report'),
('matrx-user/education-progress', 'gain_error', 'Report error', 'Error message when the report failed to load. Absent on the happy path and on the dashboard view.', 'string', false, 80, 310, true, 'gain_report'),
('matrx-user/education-progress', 'gain_pairs', 'Baseline→post pairs', 'Every subject with a complete baseline+post measurement, each { subject, subjectLabel, baseline: {score, takenAt}, post: {score, takenAt}, delta, normalizedGain }. Empty array when the learner has no complete pairs yet (the report shows an empty state). Absent while loading and on the dashboard view.', 'array', false, 900, 320, true, 'gain_report'),
('matrx-user/education-progress', 'gain_overall_delta', 'Overall delta', 'Mean baseline→post score delta across all paired subjects (0..1, can be negative). Null when there are no complete pairs. Absent while loading and on the dashboard view.', 'number', false, 6, 330, true, 'gain_report'),
('matrx-user/education-progress', 'gain_overall_normalized', 'Overall normalized gain', 'Mean normalized gain (Hake''s g) across subjects where it''s defined (0..1) — the share of what was left to learn that was actually learned. Null when undefined for every subject. Absent while loading and on the dashboard view.', 'number', false, 6, 340, true, 'gain_report'),
('matrx-user/education-progress', 'gain_is_seed', 'Sample data', 'True when the report is showing SEED FIXTURES, not the learner''s real measurements — because the underlying P1 assessment-engine table isn''t live yet or the learner has no real pairs. When true, describe the numbers as illustrative, never as the learner''s actual results. Absent while loading and on the dashboard view.', 'boolean', false, 5, 350, true, 'gain_report'),
('matrx-user/education-progress', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/education-progress', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/education-progress', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/education-progress', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/education-progress', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/image-uploader', 'preset', 'Asset preset', 'Asset preset governing the produced variants (e.g. "social"). Always populated while the window is mounted (defaults to "social").', 'string', true, 12, 300, true, 'upload_config'),
('matrx-user/image-uploader', 'target_folder', 'Target folder', 'Storage folder the opener directed the upload into. Absent when the opener left the preset default.', 'string', false, 30, 310, true, 'upload_config'),
('matrx-user/image-uploader', 'uploader_title', 'Uploader title', 'Window/field title the opener supplied (what the image is FOR, e.g. ''Cover image''). Absent when the opener supplied none.', 'string', false, 30, 320, true, 'upload_config'),
('matrx-user/image-uploader', 'uploader_description', 'Uploader description', 'Helper text the opener supplied, shown above the uploader. Absent when the opener supplied none.', 'string', false, 100, 330, true, 'upload_config'),
('matrx-user/image-uploader', 'current_url', 'Current image URL', 'URL of the image currently occupying the slot being replaced (the ''before'' image). Absent when the slot is empty.', 'string', false, 120, 340, true, 'upload_config'),
('matrx-user/image-uploader', 'allow_url_paste', 'URL paste allowed', 'True when the user may paste an image URL instead of uploading a file. Always populated while the window is mounted (defaults true).', 'boolean', true, 5, 350, true, 'upload_config'),
('matrx-user/image-uploader', 'has_upload_result', 'Has upload result', 'True once an image has been uploaded (or pasted) in this window and a result is pending hand-back. Always populated while the window is mounted.', 'boolean', true, 5, 400, true, 'upload_result'),
('matrx-user/image-uploader', 'result_primary_url', 'Result primary URL', 'Primary variant URL of the uploaded asset. Absent until an upload completes.', 'string', false, 120, 410, true, 'upload_result'),
('matrx-user/canvas-viewer', 'share_token', 'Share token', 'Resolved share token of the canvas currently displayed. Empty when no canvas has been resolved yet (the empty state).', 'string', false, 12, 300, true, 'general'),
('matrx-user/canvas-viewer', 'token_input', 'Resolver input', 'Raw text in the footer resolver bar (a pasted link or token) before resolution. Empty when untouched.', 'string', false, 80, 310, false, 'general'),
('matrx-user/canvas-viewer', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/canvas-viewer', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/canvas-viewer', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/canvas-viewer', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/canvas-viewer', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/observational-memory', 'selected_conversation_id', 'Selected conversation ID', 'UUID of the conversation whose memory is inspected in the detail pane. Empty when none is selected.', 'string', false, 36, 300, true, 'memory_state'),
('matrx-user/observational-memory', 'conversation_ids', 'Conversations with memory activity', 'Array of conversation UUIDs listed in the sidebar — every conversation this session has seen observational-memory activity for. Empty array when none.', 'array', false, 800, 310, false, 'memory_state'),
('matrx-user/observational-memory', 'memory_enabled', 'Memory enabled', 'True when observational memory is enabled for the selected conversation. Absent when no conversation is selected.', 'boolean', false, 5, 320, true, 'memory_state'),
('matrx-user/observational-memory', 'memory_degraded', 'Memory degraded', 'True when the selected conversation''s memory pipeline is in a degraded state. Absent when no conversation is selected.', 'boolean', false, 5, 330, true, 'memory_state'),
('matrx-user/observational-memory', 'memory_counters', 'Memory counters', 'Event/cost counters for the selected conversation''s memory activity (event totals, cost). Absent when no conversation is selected.', 'object', false, 300, 340, false, 'memory_state'),
('matrx-user/observational-memory', 'memory_metadata', 'Memory metadata', 'The persisted `observational_memory` metadata block for the selected conversation (the memory content itself). Absent when none is persisted. Can be large — bind explicitly when needed.', 'object', false, 2000, 350, false, 'memory_state'),
('matrx-user/observational-memory', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/observational-memory', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/observational-memory', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/observational-memory', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/observational-memory', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/agent-gate', 'conversation_id', 'Conversation ID', 'UUID of the conversation instance the gate is holding. Always present — the window is only ever opened for a specific conversation.', 'string', true, 36, 300, true, 'general'),
('matrx-user/agent-gate', 'agent_name', 'Agent name', 'Display name of the agent whose run is gated. Empty while the instance has not resolved its agent.', 'string', false, 40, 310, true, 'general'),
('matrx-user/agent-gate', 'pre_execution_message', 'Pre-execution message', 'The message the agent configured to show at the gate (what it wants from the user before running). Empty when the agent set none.', 'string', false, 300, 320, true, 'general'),
('matrx-user/agent-gate', 'bypass_gate_seconds', 'Bypass countdown seconds', 'Auto-advance countdown configured for this gate; the gate continues on its own after this many seconds unless the user interacts. Absent/zero when no bypass is configured.', 'number', false, 3, 330, false, 'general'),
('matrx-user/agent-gate', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/agent-gate', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/agent-gate', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/agent-gate', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/agent-gate', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/agent-run-history', 'agent_id', 'Agent ID', 'UUID of the agent whose run history is listed. Empty when no agent has been picked yet.', 'string', false, 36, 300, true, 'general'),
('matrx-user/agent-run-history', 'selected_conversation_id', 'Selected conversation ID', 'UUID of the past conversation open in the display pane. Empty when none is selected.', 'string', false, 36, 310, true, 'general'),
('matrx-user/agent-run-history', 'conversation_count', 'Conversation count', 'Number of past conversations loaded for the selected agent, across all versions. Absent until an agent is picked.', 'number', false, 4, 320, true, 'general'),
('matrx-user/agent-run-history', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/agent-run-history', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/agent-run-history', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/agent-run-history', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/agent-run-history', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/users', 'user_count', 'Total user count', 'Number of accounts currently loaded from `/api/admin/users` into the table (before any client-side search/filter). Zero while the initial fetch is in flight or if it returns no rows.', 'number', true, 5, 100, true, 'roster'),
('matrx-admin/users', 'roster_sample', 'Roster sample', 'The first several loaded accounts, each with { id, email, display_name, admin_level, providers, email_confirmed, onboarding_completed, organizations }, for shape inspection. Bindable, not auto-context — live user PII. Empty array before the first successful load.', 'array', true, 2000, 110, false, 'roster'),
('matrx-admin/users', 'roster_load_error', 'Roster load error', 'The error message from the last failed `/api/admin/users` fetch. Absent when the load succeeded or hasn''t run yet.', 'string', false, 120, 120, true, 'roster'),
('matrx-admin/users', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/users', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/users', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/users', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/users', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/knowledge', 'knowledge_section', 'Knowledge section', 'Which child of the Knowledge admin family is active: "cms_agents", "kg_cost", "kg_inspector", "podcasts_shows", "podcasts_show_detail", "podcasts_episode_detail", or "research_system". Always present — each emitter declares which one it is.', 'string', true, 20, 100, true, 'navigation'),
('matrx-admin/knowledge', 'cms_sites', 'CMS sites', 'Every client site (id, slug, name, domain, is_active, agent_write_policy, has_data_api_key) loaded on the CMS Agent Activity page. Present only on knowledge_section=cms_agents.', 'array', false, 2500, 200, false, 'cms_agents'),
('matrx-admin/knowledge', 'cms_activity_filter', 'CMS activity filter', 'The Activity tab''s current filter: { siteId, entityType, actor }, each ''all'' or a specific value. Present only on cms_agents.', 'object', false, 100, 210, true, 'cms_agents'),
('matrx-admin/knowledge', 'cms_activity_log', 'CMS activity log', 'The polled activity feed rows (id, created_at, actor, activity_type, description, user_email) matching cms_activity_filter. Present only on cms_agents; empty array when no matches.', 'array', false, 3500, 220, false, 'cms_agents'),
('matrx-admin/knowledge', 'cms_selected_site_id', 'CMS selected site', 'UUID of the site whose page tree/assets the Pages/Assets tabs show (defaults to the first loaded site). Present only on cms_agents.', 'string', false, 36, 225, true, 'cms_agents'),
('matrx-admin/knowledge', 'cms_site_pages', 'CMS site page tree', 'Pages of cms_selected_site_id (id, slug, route, title, category, page_type, is_published, has_draft, sort_order), grouped by category. Present only on cms_agents.', 'array', false, 4000, 230, false, 'cms_agents'),
('matrx-admin/knowledge', 'cms_pending_exceptions', 'CMS pending exceptions', 'Content-validation exceptions with status ''pending'' on the Approvals tab (id, rule_id, node_path, excerpt, fix_hint, severity, note). Present only on cms_agents; empty array when none are pending.', 'array', false, 2500, 235, false, 'cms_agents'),
('matrx-admin/knowledge', 'cms_selected_site_assets', 'CMS selected site assets', 'Media assets of cms_selected_site_id (id, file_name, file_type, mime_type, file_size, alt_text, folder, used_in_pages) on the Assets tab. Present only on cms_agents.', 'array', false, 3000, 240, false, 'cms_agents'),
('matrx-admin/knowledge', 'kg_cost_summary', 'KG cost summary', 'The dashboard''s six KPI tiles: spend_today_usd, spend_7d_usd, orgs_over_80pct, pending_batches, ner_coverage_pct, batch_savings_7d_usd. Present only on kg_cost.', 'object', false, 200, 300, true, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_org_rows', 'KG cost org leaderboard', 'Per-org auto-RAG spend rows (organization_id, organization_name, daily_auto_rag_budget_usd, daily_auto_rag_cost_used_usd, percent_used, last_charge_at), up to 200. Present only on kg_cost.', 'array', false, 4000, 310, false, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_batch_rows', 'KG cost pending batches', 'In-flight provider batch rows (id, provider, kind, organization_name, status, est_cost_usd, poll_count, next_poll_at), up to 100. Present only on kg_cost.', 'array', false, 3500, 320, false, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_open_org_id', 'KG cost open org', 'organization_id of the org whose detail dialog is open. Absent when no org drill-down is open.', 'string', false, 36, 330, true, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_org_detail', 'KG cost org detail', 'Detail payload for kg_cost_open_org_id: { budget_usd, used_today_usd, window_start, daily_series, top_sources, batch_summary } plus the org''s auto-RAG toggle state (enabled, indexNonPdf, suggestionSweeps). Absent when no org drill-down is open.', 'object', false, 1500, 335, true, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_open_batch_id', 'KG cost open batch', 'id of the batch whose detail dialog is open. Absent when no batch drill-down is open.', 'string', false, 36, 340, true, 'kg_cost'),
('matrx-admin/knowledge', 'kg_cost_batch_detail', 'KG cost batch detail', 'Detail payload for kg_cost_open_batch_id: adds purpose, cost_usd, tokens_in, tokens_out, error, metadata, completed_at to the batch row. Absent when no batch drill-down is open.', 'object', false, 800, 345, true, 'kg_cost'),
('matrx-admin/knowledge', 'kg_inspector_tab', 'KG inspector tab', 'Which of the three tabs is active: "entities", "mentions", or "edges". Present only on kg_inspector.', 'string', false, 10, 400, true, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_inspector_selected_entity', 'KG inspector selected entity', 'The entity the admin drilled into: { id, name, kind }. Drives the Mentions tab. Absent until an entity/edge endpoint is clicked.', 'object', false, 150, 405, true, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_entities_filter', 'KG entities filter', 'Entities tab filter/sort state: { kind, q, page, sortKey, sortDir }. Present only when kg_inspector_tab is entities.', 'object', false, 150, 410, true, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_entities', 'KG entities', 'Entity rows matching kg_entities_filter (id, kind, canonical_name, organization_id, mention_count, source_count, confidence_avg), up to 200. Present only when kg_inspector_tab is entities.', 'array', false, 6000, 415, false, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_mentions', 'KG entity mentions', 'Source mentions of kg_inspector_selected_entity (chunk_id, source_kind, source_id, snippet, span_start, span_end, confidence), paginated. Present only when kg_inspector_tab is mentions.', 'array', false, 4000, 420, false, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_edges_filter', 'KG edges filter', 'Edges tab filter/sort state: { orgId, edgeKind, sortKey, sortDir }. Present only when kg_inspector_tab is edges.', 'object', false, 100, 425, true, 'kg_inspector'),
('matrx-admin/knowledge', 'kg_edges', 'KG top edges', 'Graph edges matching kg_edges_filter (id, kind, src_name, src_kind, dst_name, dst_kind, weight), up to 200. Present only when kg_inspector_tab is edges.', 'array', false, 5000, 430, false, 'kg_inspector'),
('matrx-admin/knowledge', 'podcast_shows', 'Podcast shows', 'Every show (id, slug, title, author, is_published, created_at) loaded on the Shows list. Present only on podcasts_shows.', 'array', false, 3000, 500, false, 'podcasts'),
('matrx-admin/knowledge', 'podcast_shows_search', 'Podcast shows search', 'The Shows list''s search text (URL-persisted, filters title/slug/author/id client-side). Empty when unset. Present only on podcasts_shows.', 'string', false, 30, 505, true, 'podcasts'),
('matrx-admin/knowledge', 'podcast_current_show_id', 'Active show ID', 'UUID of the show open on a show-detail page, or "new" on the create form. Present only on podcasts_show_detail.', 'string', false, 36, 510, true, 'podcasts'),
('matrx-admin/knowledge', 'podcast_current_show', 'Active show', 'Full show record: { id, slug, title, description, image_url, author, is_published, rss_settings }. Absent when podcast_current_show_id is "new" and nothing has been saved yet.', 'object', false, 1000, 515, true, 'podcasts'),
('matrx-admin/knowledge', 'podcast_current_show_episodes', 'Active show''s episodes', 'Episodes belonging to podcast_current_show_id (id, slug, title, episode_number, duration_seconds, is_published), newest data first. Present only on podcasts_show_detail; empty array before the first episode.', 'array', false, 3500, 520, false, 'podcasts'),
('matrx-admin/knowledge', 'podcast_active_panel', 'Podcast detail panel', '"show" (settings form) or "episodes" (episode list), URL-persisted sub-tab of the show detail page. Present only on podcasts_show_detail.', 'string', false, 10, 525, true, 'podcasts'),
('matrx-admin/knowledge', 'podcast_current_episode_id', 'Active episode ID', 'UUID of the episode open on the episode-detail page, or "new" on the create form. Present only on podcasts_episode_detail.', 'string', false, 36, 530, true, 'podcasts'),
('matrx-admin/knowledge', 'podcast_current_episode', 'Active episode', 'Full episode record: { id, show_id, title, description, audio_url, video_url, display_mode, episode_number, duration_seconds, speakers, script, chapters, is_published }. Absent when podcast_current_episode_id is "new" and nothing has been saved yet.', 'object', false, 4000, 535, false, 'podcasts'),
('matrx-admin/knowledge', 'research_admin_tab', 'Research admin tab', 'Which of the three tabs is active: "templates", "agents" (the agent-wiring dashboard), or "projects". Present only on research_system.', 'string', false, 10, 600, true, 'research_system'),
('matrx-admin/knowledge', 'research_templates', 'Research templates', 'Research templates (id, name, description, is_system, keyword_templates, default_tags, agent_config — the seven agent-role keys like page_summary_agent_id, research_report_agent_id — autonomy_level). Present only on research_system.', 'array', false, 6000, 610, false, 'research_system'),
('matrx-admin/knowledge', 'research_builtin_agents', 'Research builtin agents', 'Builtin agent id/name pairs used to resolve each agent_config slot to a readable name in the templates and agent-wiring views.', 'array', false, 1000, 615, false, 'research_system'),
('matrx-admin/knowledge', 'research_topics', 'Research topics/projects', 'Research topic rows on the Projects tab (id, name, status, template_id, autonomy_level, linked project id via association edge), up to 50. Present only on research_system.', 'array', false, 2500, 620, false, 'research_system'),
('matrx-admin/knowledge', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/knowledge', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/knowledge', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/knowledge', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/knowledge', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/kind-registry', 'kind_registry_section', 'Kind registry section', 'Which sub-route is active: "catalog" (list/board/export), "detail" (one kind''s [kind] page), or "build" (the agent-assisted builder). Always present — each emitter declares which one it is.', 'string', true, 8, 100, true, 'navigation'),
('matrx-admin/kind-registry', 'catalog_tab', 'Catalog tab', 'Which of the three catalog-page tabs is active: "catalog" (table), "board" (status board), or "export" (schema/reference-graph explorer). Present only on kind_registry_section=catalog.', 'string', false, 8, 200, true, 'catalog'),
('matrx-admin/kind-registry', 'kind_catalog_rows', 'Kind catalog rows', 'Every declared kind (kind, label, family, isActive, version, visibility, componentCount, surfaceCount, exampleCount, and per-asset-column status cells: definition/example/gate_structural/component/skill/content_block/surface). Present only on kind_registry_section=catalog.', 'array', false, 8000, 210, false, 'catalog'),
('matrx-admin/kind-registry', 'kind_catalog_totals', 'Kind catalog totals', 'Header summary counts: total kinds, active count, red findings count, yellow findings count, drifted-row count (live DB vs committed snapshot). Present only on kind_registry_section=catalog.', 'object', false, 150, 220, true, 'catalog'),
('matrx-admin/kind-registry', 'kind_catalog_facets', 'Kind catalog facets', 'Table facet filters: { activeFacet: "all"|"on"|"off", issueFacet: "all"|"red"|"drift" }. Present only when catalog_tab is "catalog".', 'object', false, 60, 230, true, 'catalog'),
('matrx-admin/kind-registry', 'current_kind', 'Active kind', 'The kind slug (content_ir.kind_definition.kind, e.g. "topic_ideas") shown on the [kind] detail page — this is a slug, not a UUID. Present only on kind_registry_section=detail.', 'string', false, 24, 300, true, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_tab', 'Kind detail tab', 'Which of the 7 detail tabs is active: "preview", "examples", "assets", "try-input", "gate", "schema", or "inputs". Present only on kind_registry_section=detail.', 'string', false, 10, 305, true, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_summary', 'Kind detail summary', 'Header fields for current_kind: { id, kind, label, isActive, version, visibility, updatedAt }. Present only on kind_registry_section=detail.', 'object', false, 250, 310, true, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_schema', 'Kind detail schema', 'The kind''s field data and emitted JSON Schema: { fieldData, emittedJsonSchema }. Shown on the Schema tab. Present only on kind_registry_section=detail; either half may be null if not yet defined.', 'object', false, 3000, 315, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_doctor_row', 'Kind detail doctor status', 'Per-asset-column status (definition/example/gate_structural/component/skill/content_block/surface) for current_kind, same shape as one kind_catalog_rows entry. Present only on kind_registry_section=detail.', 'object', false, 500, 320, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_components', 'Kind detail components', 'kind_component rows for current_kind (id, platform, role, componentKey, source, isActive, isDefault). Present only on kind_registry_section=detail; empty array if none are registered.', 'array', false, 800, 325, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_surfaces', 'Kind detail surfaces', 'kind_surface rows for current_kind (id, surfaceType, token, parserStrategy, streaming, isActive). Present only on kind_registry_section=detail; empty array if none are registered.', 'array', false, 600, 330, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_skills', 'Kind detail skills', 'Skills that teach current_kind (skill teaching summaries). Present only on kind_registry_section=detail; empty array if none teach this kind.', 'array', false, 600, 335, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_examples', 'Kind detail examples', 'kind_example rows for current_kind (id, label, description, is_canonical, source, validation_status, kind_version, updated_at) — the Examples tab. Present only on kind_registry_section=detail; empty array before the first example is added.', 'array', false, 2500, 340, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_detail_canonical_example_data', 'Kind detail canonical example data', 'The `data` payload of current_kind''s canonical example (falls back to the newest example when none is marked canonical). Used by the Preview tab. Absent when no examples exist yet.', 'object', false, 2000, 345, false, 'kind_detail'),
('matrx-admin/kind-registry', 'kind_builder_structure', 'Kind builder structure', 'The raw data structure the admin pasted into the builder (JSON, a row sample, or a free-text field list) — becomes the core of the kind_architect prompt. Empty string before anything is typed. Present only on kind_registry_section=build.', 'string', false, 800, 400, true, 'kind_builder'),
('matrx-admin/kind-registry', 'kind_builder_notes', 'Kind builder direction notes', 'Optional free-text notes on style, interaction, or agent-trigger behavior the admin wants baked into the new kind. Empty string when unset. Present only on kind_registry_section=build.', 'string', false, 300, 410, true, 'kind_builder'),
('matrx-admin/kind-registry', 'kind_builder_architect_agent_id', 'Kind architect agent ID', 'The resolved agent id for the content_ir.kind_architect slot that will run when the admin presses Start. Absent when the slot fails to resolve.', 'string', false, 36, 420, true, 'kind_builder'),
('matrx-admin/kind-registry', 'kind_builder_can_start', 'Kind builder can start', 'True when kind_builder_structure is non-empty AND the architect agent slot resolved — mirrors the page''s own Start-button enablement. Present only on kind_registry_section=build.', 'boolean', false, 5, 430, true, 'kind_builder'),
('matrx-admin/kind-registry', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/kind-registry', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/kind-registry', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/kind-registry', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/kind-registry', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/skills', 'skills_section', 'Skills admin mode', 'Which mode the skills admin page is in: "list" (browser), "detail" (viewing a skill), "create" (new skill form), "ingest", or "categories". Always present — each emitter declares which one it is.', 'string', true, 8, 100, true, 'navigation'),
('matrx-admin/skills', 'skills_list', 'Skills list', 'Every loaded skill (id, skillId, label, description, skillType, iconName, allowedTools, triggerPatterns, platformTargets, version, categoryId, isActive, isSystem, isPublic, sortOrder). Present on skills_section=list.', 'array', false, 8000, 200, false, 'skills_registry'),
('matrx-admin/skills', 'skills_stats', 'Skills stats', 'Summary counts over skills_list: { total, system, public, personal }. Present on skills_section=list.', 'object', false, 60, 210, true, 'skills_registry'),
('matrx-admin/skills', 'skills_search', 'Skills search', 'The browser''s search text, matched against label/skillId/description client-side. Empty string when unset. Present on skills_section=list.', 'string', false, 30, 220, true, 'skills_registry'),
('matrx-admin/skills', 'skills_scope_filter', 'Skills scope filter', '"all", "system", "public", or "personal" — the browser''s visibility filter. Present on skills_section=list.', 'string', false, 10, 230, true, 'skills_registry'),
('matrx-admin/skills', 'skills_category_filter', 'Skills category filter', 'The category id the browser is filtered to, or "all". Present on skills_section=list.', 'string', false, 36, 240, true, 'skills_registry'),
('matrx-admin/skills', 'selected_skill_id', 'Selected skill ID', 'id of the skill being viewed/edited, from ?open=<skillId> or a browser row click. Absent on skills_section=list before any selection, and on ingest/categories.', 'string', false, 36, 300, true, 'skill_selection'),
('matrx-admin/skills', 'selected_skill', 'Selected skill', 'The full saved skill record for selected_skill_id: { skillId, label, description, skillType, body, allowedTools, triggerPatterns, disableAutoInvocation, platformTargets, version, categoryId, isActive, isSystem, isPublic }. Absent when skills_section=create (nothing saved yet) or no skill is selected.', 'object', false, 3000, 310, true, 'skill_selection'),
('matrx-admin/skills', 'skill_categories', 'Skill categories', 'The full category tree (id, categoryKey, label, parentCategoryId, sortOrder, isActive, userId — null userId means a system category). Present on skills_section=categories, and used to label skills_list''s categoryId elsewhere.', 'array', false, 2500, 400, false, 'skill_categories'),
('matrx-admin/skills', 'ingest_paths_text', 'Ingest paths', 'The multiline textarea of filesystem paths (one per line, #-comments stripped) the admin is about to dry-run or apply. Empty string before anything is typed. Present on skills_section=ingest.', 'string', false, 200, 500, true, 'skill_ingest'),
('matrx-admin/skills', 'ingest_status', 'Ingest status', '"idle", "loading", "ready", or "error" — the state of the last dry-run/apply call. Present on skills_section=ingest.', 'string', false, 8, 510, true, 'skill_ingest'),
('matrx-admin/skills', 'ingest_report', 'Ingest report', 'The last dry-run or apply result: { parsed, created, updated, unchanged, errors, roots, skills: [{ skillId, sourcePath, category, status, id }] }. Absent before the first dry-run/apply of the session.', 'object', false, 3000, 520, false, 'skill_ingest'),
('matrx-admin/skills', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/skills', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/skills', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/skills', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/skills', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'AI Results', value_groups = '[{"key":"general","label":"General","sortOrder":850},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'quickChatHistory', url_pattern = '/ai-results', intro = '<surface_intro>
You are on AI Results — a cross-agent conversation history browser in a floating window. The sidebar lists past runs across every accessible agent (grouped by date or agent, filterable by agent and search); selecting one shows it read-only in the main pane. selected_conversation_id identifies the open run; last_run_text is its final assistant reply. Agents bound here help the user find, judge, or summarize past runs — they do not operate on a live run.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/ai-results';
UPDATE ui.ui_surface SET label = 'Audio Study', value_groups = '[{"key":"tool_view","label":"Tool view","sortOrder":100,"description":"Which of the Audio Study views the learner is on. Read this first — it tells you which of the other groups carry values at all."},{"key":"audio_library","label":"Audio library","sortOrder":200,"description":"The audio studies the learner owns or can see, as listed on the tool''s home page."},{"key":"generation_request","label":"Generation request","sortOrder":300,"description":"The composer on /education/audio-study/new — source, format, and options. Nothing here is generated yet."},{"key":"audio_record","label":"Audio study","sortOrder":400,"description":"The open audio study''s identity, playback readiness, and live-generation run state."},{"key":"audio_trust","label":"Grounding","sortOrder":500,"description":"What the open audio study was built from and how confident that grounding is. Derived evidence — never authored here."},{"key":"review_session","label":"Audio review session","sortOrder":600,"description":"Read-only state of a live spoken review session on /education/audio-study/review. No emitter is mounted here yet — see the manifest header."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + three emitters (list, new, detail) shipped, targeting a live DB row that previously had no manifest at all. NOT yet: DB sync has not been run; the Audio Review live-voice session (/education/audio-study/review) declares review_* values but has no SurfaceRuntimeProvider mount (its phase machine deserves its own pass, see manifest header); this surface declares no write targets (composer fields are consumed by a single metered, human-pressed Generate button — same judgment as education-memory) and no agent roles; no data-surface-value Locate anchors are tagged; no live-agent-run verification or Matrx-vs-matrix test has been performed.', url_pattern = '/education/audio-study', intro = '<surface_intro>
You are in Audio Study at /education/audio-study — the tool that turns flashcard decks or topics into produced audio (a narrated overview, a two-voice debate, or a multi-host panel), plus a separate live spoken-review mode. Read `view` FIRST — it is "list", "new", "detail", or "review", and it decides which other values are even present.
On "list" you see the learner''s saved audio studies (`audio_library`, `audio_count`). Wait for `library_loaded` before calling the library empty.
On "new" the learner is composing a generation request: `request_source_kind` is "deck" or "topic", `request_format` is overview/debate/panel, and `generation_request` carries the whole composer state including host count and the weak-areas toggle. Nothing has been generated yet, and generating spends a metered allowance, so help them decide what to ask for — suggest a format, a sharper topic, or which deck is worth turning into audio — and leave the Generate button to them.
On "detail" one stored study is open. `audio_is_ready` tells you whether the durable player is showing or a live run is still producing (`run_status`). `audio_confidence` and `audio_citations` are derived grounding evidence — cite them, never claim to change them.
"review" is a live spoken quiz session (mic capture, spoken grading) built on separate machinery; this surface currently emits nothing there, so treat any review_* value you see as stale/absent until told otherwise.
You cannot WRITE anything here — this surface declares no write targets, and nothing on the detail view is editable (the learner''s path to different audio is Regenerate, which routes back to /new).
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/education-audio-study';
UPDATE ui.ui_surface SET label = 'Study Games', value_groups = '[{"key":"tool_view","label":"Tool view","sortOrder":100,"description":"Which of the Study Games routes the learner is on. Read this first — it tells you which of the other groups carry values at all."},{"key":"host_setup","label":"Host setup","sortOrder":200,"description":"The room-creation composer on /education/game/host — what source players will be quizzed from, and the room-size entitlement."},{"key":"join_room","label":"Join room","sortOrder":300,"description":"The join composer on /education/game/join — the code the learner is typing."},{"key":"solo_session","label":"Solo session","sortOrder":400,"description":"Read-only state of a live solo-arcade run on /education/game/solo. No emitter is mounted here yet — see the manifest header."},{"key":"room_session","label":"Multiplayer room","sortOrder":500,"description":"Read-only state of a live multiplayer room on /education/game/play/[roomId]. No emitter is mounted here yet — see the manifest header."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + three emitters (home, host, join) shipped, targeting a live DB row that previously had no manifest at all. NOT yet: DB sync has not been run; the solo-arcade and live-multiplayer views (SoloArcadeImpl / MultiplayerGameImpl, both dynamic({ssr:false}) real-time game engines) declare solo_*/room_* values but have no SurfaceRuntimeProvider mount (deliberately deferred, see manifest header); no write targets, agent roles, or config namespaces are declared; no data-surface-value Locate anchors are tagged; no live-agent-run verification or Matrx-vs-matrix test has been performed.', url_pattern = '/education/game', intro = '<surface_intro>
You are in Study Games at /education/game — play-as-review: every question in every mode is scheduled by the same spaced-repetition engine as the rest of the app. Read `view` FIRST — it is "home", "host", "join", "solo", or "play", and it decides which other values are even present.
On "home" the learner sees their streak, weekly league standing, badges, and three entry points: Solo Arcade, Host a game, Join a game. Nothing here is editable.
On "host" they are composing a room: `host_source_kind` is "due" (their cross-deck due queue, the adaptive default) or "set" (one specific deck, from `host_available_sets`); a private deck can''t be used for a cross-account room, which the picker itself flags. `host_max_players` is the entitlement-capped room size, shown before creating. The learner still presses Create room.
On "join" they are typing a 5-character room code (`join_code`); `join_error` explains a bad or unknown code.
"solo" and "play" are live game engines (timers, live scoring, and for "play" a realtime multiplayer room) that this surface currently emits NOTHING from — treat any solo_*/room_* value you see as stale/absent until told otherwise.
You cannot WRITE anything here — no write targets are declared, and creating/joining a room is a real side effect the learner triggers themselves.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/education-game';
UPDATE ui.ui_surface SET label = 'Study guides', value_groups = '[{"key":"reader_view","label":"Reader view","sortOrder":100,"description":"Which of the two public study-guide pages the visitor is on — the index or one open article."},{"key":"guide_library","label":"Guide library","sortOrder":200,"description":"The index page''s list of every published study guide (/education/learn)."},{"key":"guide_article","label":"Open guide","sortOrder":300,"description":"The full content of the one published study guide open on the article page (/education/learn/[...slug])."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'stub', readiness_note = 'Manifest-only, never audited against a live runtime: the vocabulary is declared from a code read of EducationLearnPage / LearnArticlePage / LearnArticle.tsx (all Server Components), but NO SurfaceRuntimeProvider is mounted anywhere in this path and none can be without either converting genuinely-static SEO content to a client component or adding a thin client shell purely to host the provider — see the manifest header for the real decision this needs. DB sync has not been run. No write targets (this is a public reader page, nothing is authored here — authoring lives on matrx-user/education-learn-authoring). No agent roles, no Locate anchors, no live-agent verification.', url_pattern = '/education/learn', intro = '<surface_intro>
You are on the PUBLIC study-guide reader at /education/learn — free, SEO-facing explainer articles, anonymous and server-rendered. This is not the authoring surface (that is a separate super-admin surface) and not a study session; it is what any visitor, signed in or not, reads.
On the index (`view: "index"`) `guide_library` lists every published guide. On an article (`view: "article"`) `article_sections` is the full body the reader is looking at, with `article_title`/`article_summary` as the header and `article_related` naming which app tools and hubs the page funnels toward.
This surface currently emits NOTHING at runtime — see readinessNote. Treat any value here as declared vocabulary for future binding, not as live data you can rely on today.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/education-learn';
UPDATE ui.ui_surface SET label = 'Progress', value_groups = '[{"key":"progress_view","label":"Progress view","sortOrder":100,"description":"Which of the two Progress views the learner is on — read this first, it decides which other groups are populated."},{"key":"analytics_summary","label":"Analytics summary","sortOrder":200,"description":"The dashboard view''s folded cross-mode stats — overall mastery/accuracy, per-mode breakdown, weak topics, streak, and trend."},{"key":"analytics_narrative","label":"AI narrative","sortOrder":300,"description":"The dashboard view''s AI-generated summary of the analytics above — a headline, grounded insights, and prioritized recommendations. Derived evidence; regenerated on demand."},{"key":"gain_report","label":"Learning-gain report","sortOrder":400,"description":"The learning_gain view''s pre/post measured-improvement report — per-subject deltas and the overall normalized gain."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + both emitters (dashboard, learning_gain) shipped, targeting a live DB row that previously had no manifest at all. NOT yet: DB sync has not been run; no write targets are declared (every value here is derived evidence — correctly so, nothing on either view is editable); no agent roles or config namespaces are declared; no data-surface-value Locate anchors are tagged; no live-agent-run verification or Matrx-vs-matrix test has been performed; the guardian/family progress view (StudentProgressView, a different data path over a linked student''s spine) is explicitly OUT of scope for this manifest — see header.', url_pattern = '/education/progress', intro = '<surface_intro>
You are on the Progress surface at /education/progress — the learner''s own cross-mode study analytics: mastery, accuracy, weak areas, trends, and a pre/post learning-gain report. Everything here is READ-ONLY derived evidence computed from the learner''s real attempt history; there is nothing to author on either view.
Read `view` first — it is "dashboard" or "learning_gain".
On "dashboard": `overall_stats` and `mode_stats` are the folded totals; `weak_topics` names what needs work; `accuracy_trend` says whether things are improving; `current_streak` and `total_minutes`/`session_count` round out the picture. `analytics_has_data` is false for a brand-new learner — don''t describe an empty spine as "struggling". Once there''s enough data, an AI narrator runs automatically: `narrative_headline`, `narrative_insights`, and especially `narrative_recommendations` are the surface''s own best answer to "what should I study next" — read them before improvising a suggestion, and prefer them over re-deriving your own from the raw stats.
On "learning_gain": `gain_pairs` holds each subject''s baseline→post measurement; `gain_overall_delta` and `gain_overall_normalized` are the headline numbers ("prove it makes you smarter"). Check `gain_is_seed` FIRST — while the underlying assessment-engine table isn''t live, this report shows labeled SAMPLE data, and you must describe it as illustrative, never as the learner''s actual results.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/education-progress';
UPDATE ui.ui_surface SET label = 'Image Uploader', value_groups = '[{"key":"upload_config","label":"Upload configuration","sortOrder":100,"description":"How the opener configured this upload capture."},{"key":"upload_result","label":"Upload result","sortOrder":200,"description":"The uploaded asset, once an upload has completed."}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'imageUploaderWindow', url_pattern = '/image-uploader', intro = '<surface_intro>
You are in the floating Image Uploader window — an ephemeral asset-intake surface a caller spawned to collect one image (file upload or URL paste) and hand its variant URLs back. Upload configuration tells you what the image is for and how it will be processed; Upload result carries the produced asset once an upload has completed. There is no text content here.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/image-uploader';
UPDATE ui.ui_surface SET label = 'Canvas Viewer', value_groups = '[{"key":"general","label":"General","sortOrder":850},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'canvasViewerWindow', url_pattern = '/canvas-viewer', intro = '<surface_intro>
You are on the Canvas Viewer — a floating window for viewing a SHARED canvas by token or link. share_token identifies the canvas being displayed; when it is empty the user has not resolved one yet. The canvas content itself is rendered read-only from the share token.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/canvas-viewer';
UPDATE ui.ui_surface SET label = 'Memory Inspector', value_groups = '[{"key":"memory_state","label":"Memory state","sortOrder":100,"description":"The selected conversation''s observational-memory status and data."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'observationalMemoryWindow', url_pattern = '/observational-memory', intro = '<surface_intro>
You are on the Memory Inspector — an admin floating window for auditing the Observational Memory feature. The sidebar lists every conversation with memory activity this session; the detail pane shows the selected conversation''s memory state: whether it is enabled, degraded, its counters/cost, and the persisted memory metadata itself. This is a diagnostic surface — help the admin interpret memory behavior; never fabricate memory content.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/observational-memory';
UPDATE ui.ui_surface SET label = 'Agent Gate', value_groups = '[{"key":"general","label":"General","sortOrder":850},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'agentGateWindow', url_pattern = '/agents/gate', intro = '<surface_intro>
You are on the Agent Gate — the pre-execution checkpoint shown before an agent run proceeds. The gated agent''s pre_execution_message tells the user what it needs; the user types a reply (or the bypass countdown auto-advances) and the run continues in the downstream window. conversation_id identifies the pending run.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/agent-gate';
UPDATE ui.ui_surface SET label = 'Agent Run History', value_groups = '[{"key":"general","label":"General","sortOrder":850},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', overlay_id = 'agentRunHistoryWindow', url_pattern = '/agents/run-history', intro = '<surface_intro>
You are on Agent Run History — a floating window for reviewing an agent''s past runs. The sidebar groups the agent''s conversations by agent version (newest first); the pane shows the selected conversation. Agents here help the user find, summarize, or compare past runs of the agent identified by agent_id.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/agent-run-history';
UPDATE ui.ui_surface SET label = 'Users & Access — Accounts', value_groups = '[{"key":"roster","label":"Account roster","sortOrder":100,"description":"The user accounts currently loaded and visible in the Accounts table, and the table''s loading/error state."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'emitter wired, browser verification pending', url_pattern = '/administration/users', intro = '<surface_intro>
This is an ADMIN surface: the Users & Access hub landing tab at /administration/users, the canonical account roster for the whole platform.

One row per Supabase auth user, merged with profile info and admin level, in a sortable/filterable table. user_count is the total loaded; roster_sample is a few rows for shape inspection (bindable only — live account PII).

What you may safely do: summarize the roster, flag accounts needing attention (unconfirmed email, not onboarded, no admin level where expected), and help the admin decide who to contact. You never send an email, magic link, password reset, or in-app message yourself — those are admin button presses on this page, not something you can trigger from context.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/users';
UPDATE ui.ui_surface SET label = 'Knowledge Admin', value_groups = '[{"key":"navigation","label":"Knowledge navigation","sortOrder":100,"description":"Which child tool of the Knowledge admin family is active."},{"key":"cms_agents","label":"CMS agent activity","sortOrder":200,"description":"Fleet-wide CMS agent/human activity feed, per-site page tree, agent write policy, and the validation-exception approvals queue."},{"key":"kg_cost","label":"KG cost","sortOrder":300,"description":"Auto-ingest spend KPIs, per-org cost leaderboard, in-flight provider batches, and drill-down detail for a selected org or batch."},{"key":"kg_inspector","label":"KG inspector","sortOrder":400,"description":"Read-only browser over knowledge-graph entities, their source mentions, and the edges between them."},{"key":"podcasts","label":"Podcasts admin","sortOrder":500,"description":"Show list, the active show''s settings and episode list, and a single episode''s full record."},{"key":"research_system","label":"Research system admin","sortOrder":600,"description":"Research templates (including per-role agent_config wiring), the agent-wiring dashboard, and the topic/project overview."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'stub', readiness_note = 'Manifest-only — vocabulary audited against the live pages, no runtime emitter wired yet. /administration/knowledge itself is a static link directory (no data, no values). growth-loop is deliberately excluded (its own pillar/doctrine). Wiring an emitter per child is real follow-up work: cms-agents has 5 concurrently-mounted panels, kg-cost/kg-inspector/podcasts/research-system each have their own filter+pagination+selection state.', url_pattern = '/administration/knowledge', intro = '<surface_intro>
This is an ADMIN surface: the Knowledge admin family at /administration/knowledge, covering five unrelated super-admin tools that happen to live under one hub.

knowledge_section tells you which one is active: "cms_agents" (fleet-wide CMS agent/human activity feed, per-site page tree, agent write policy, validation-exception approvals), "kg_cost" (auto-ingest spend KPIs, per-org leaderboard, in-flight provider batches), "kg_inspector" (read-only knowledge-graph entity/mention/edge browser), "podcasts_shows"/"podcasts_show_detail"/"podcasts_episode_detail" (podcast show and episode CRUD), or "research_system" (research templates, per-role agent wiring, topic/project overview).

Only the values matching the current knowledge_section are populated — everything else is absent, not stale. Treat all rows here as live production data: summarize, diagnose, explain, but never republish verbatim at scale. This surface has no write targets yet — real mutation UI exists on several children (CMS policy editor, KG-cost auto-ingest toggles, podcast forms, research-template editors) but nothing is wired for agent writes.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/knowledge';
UPDATE ui.ui_surface SET label = 'Kind Registry Admin', value_groups = '[{"key":"navigation","label":"Kind registry navigation","sortOrder":100,"description":"Which sub-route of the kind registry admin is active."},{"key":"catalog","label":"Kind catalog","sortOrder":200,"description":"The list of every declared kind and its per-asset status (definition, example, gate, component, skill, content_block, surface)."},{"key":"kind_detail","label":"Kind detail","sortOrder":300,"description":"One kind''s full record: schema, examples, components, surfaces, skills, and doctor status, on the [kind] detail page."},{"key":"kind_builder","label":"Kind builder","sortOrder":400,"description":"The agent-assisted kind builder: the pasted data structure and direction notes an admin composes before handing off to the kind_architect agent."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Kind builder emitter is wired and real (structure/notes/architect resolution/can-start). The catalog table and per-kind [kind] detail page are real, live-fetched data with no emitter yet — both have significant internal state (MatrxDataTable facets/column filters; 7 detail tabs each with their own sub-component) left for a follow-up pass.', url_pattern = '/administration/utilities/kind-registry', intro = '<surface_intro>
This is an ADMIN surface: the Shape System console at /administration/utilities/kind-registry, over content_ir.kind_definition / kind_surface / kind_component / kind_example.

kind_registry_section tells you which sub-route is active: "catalog" (the full list of kinds with per-asset status — catalog_tab picks table/board/export), "detail" (current_kind''s schema, examples, components, surfaces, skills, doctor status — kind_detail_tab picks which tab), or "build" (a blank composer where the admin pastes a data structure plus optional direction notes, which become the prompt handed to the kind_architect agent).

On the builder, you may draft or refine kind_builder_structure and kind_builder_notes directly — that IS the intended workflow (an agent helping shape the prompt before the human presses Start). Nothing here executes automatically: the kind_architect agent run itself is a separate floating window the admin opens by pressing Start, not something you trigger.

Only the values matching the current kind_registry_section are populated — everything else is absent, not stale.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/kind-registry';
UPDATE ui.ui_surface SET label = 'Skills Admin', value_groups = '[{"key":"navigation","label":"Skills admin navigation","sortOrder":100,"description":"Which mode of the skills admin console is active."},{"key":"skills_registry","label":"Skills registry","sortOrder":200,"description":"The loaded skill list, its summary stats, and the browser''s search/scope/category filters."},{"key":"skill_selection","label":"Selected skill","sortOrder":300,"description":"The skill the admin drilled into, when any."},{"key":"skill_categories","label":"Skill categories","sortOrder":400,"description":"The category tree used to group skills."},{"key":"skill_ingest","label":"Skill ingest","sortOrder":500,"description":"The filesystem ingest panel''s input paths and the last dry-run/apply report."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'stub', readiness_note = 'Manifest-only — vocabulary audited against the live pages, no runtime emitter wired yet. SkillDetailEditor already has agent-writable draft fields behind useSurfaceWriteHandlers, but only when mounted with a surfaceName prop; the admin page mounts it without one today.', url_pattern = '/administration/agents/skills', intro = '<surface_intro>
This is an ADMIN surface: the super-admin skills registry console at /administration/agents/skills, over skill.definition. It sees and edits every skill (system, public, personal) — distinct from matrx-user/connections-skills, the end-user vertical scoped to one user''s own skills.

skills_section tells you which mode is active: "list" (the full browser with search/scope/category filters), "detail" (a saved skill''s full record), "create" (an unsaved new-skill form), "ingest" (bulk-load SKILL.md files from the filesystem, with a dry-run/apply report), or "categories" (the category tree used to group skills).

Only the values matching the current skills_section are populated — everything else is absent, not stale. This surface has no write targets yet.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/skills';
