-- Guard: manifest surfaces missing a ui_surface row
SELECT s.name FROM (VALUES ('matrx-admin/cx-dashboard'), ('matrx-admin/applications'), ('matrx-admin/agent-apps')) AS s(name) LEFT JOIN ui.ui_surface u ON u.name = s.name WHERE u.name IS NULL;

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-admin/cx-dashboard', 'dashboard_section', 'Dashboard section', 'Which tab of the CX dashboard is active: "overview", "conversations", "conversation_detail", "requests", "request_detail", "usage", or "errors". Always present — derived from the route.', 'string', true, 18, 100, true, 'dashboard_nav'),
('matrx-admin/cx-dashboard', 'overview_kpis', 'Overview KPIs', 'The full Overview-tab payload: totals (conversations, requests, messages, tool calls), cost/token aggregates, error/pending/max-tokens counts, and the models_used / tool_usage / daily_stats breakdown arrays. Present only on the Overview tab.', 'object', false, 4000, 200, false, 'overview'),
('matrx-admin/cx-dashboard', 'overview_total_conversations', 'Total conversations', 'Overview-tab total conversation count for the current timeframe filter. Present only on the Overview tab.', 'number', false, 6, 210, true, 'overview'),
('matrx-admin/cx-dashboard', 'overview_total_cost', 'Total cost', 'Overview-tab total cost (USD) for the current timeframe filter. Present only on the Overview tab.', 'number', false, 8, 220, true, 'overview'),
('matrx-admin/cx-dashboard', 'overview_error_count', 'Error count', 'Overview-tab count of requests that errored, plus overview_error_rate for the ratio. Present only on the Overview tab.', 'number', false, 5, 230, true, 'overview'),
('matrx-admin/cx-dashboard', 'overview_error_rate', 'Error rate', 'Overview-tab error rate as a 0-1 fraction of total requests. Present only on the Overview tab.', 'number', false, 6, 235, true, 'overview'),
('matrx-admin/cx-dashboard', 'conversation_list_results', 'Conversation list', 'The current page of the Conversations table: one entry per conversation with id, title, status, message_count, model_name, provider, parent_conversation_id, and created_at. Present only on the Conversations list tab.', 'array', false, 3000, 300, false, 'conversations'),
('matrx-admin/cx-dashboard', 'conversation_list_total', 'Conversation list total', 'Total conversation count matching the current filters (across all pages), shown next to the list heading. Present only on the Conversations list tab.', 'number', false, 6, 310, true, 'conversations'),
('matrx-admin/cx-dashboard', 'current_conversation_id', 'Active conversation ID', 'UUID of the conversation shown on the conversation detail page. Absent on the list tab.', 'string', false, 36, 320, true, 'conversations'),
('matrx-admin/cx-dashboard', 'current_conversation', 'Active conversation', 'Summary of the conversation on the detail page: { id, title, status, model_name, provider, message_count, parent_conversation_id, config, variables, overrides, metadata, created_at, updated_at }. Absent on the list tab.', 'object', false, 1200, 325, true, 'conversations'),
('matrx-admin/cx-dashboard', 'current_conversation_messages', 'Active conversation messages', 'Every message in the conversation shown on the detail page, in order, with role, content blocks, and timestamps. Bindable rather than auto-context — can be large. Absent on the list tab; empty array if the conversation has no messages.', 'array', false, 8000, 330, false, 'conversations'),
('matrx-admin/cx-dashboard', 'current_conversation_user_requests', 'Active conversation''s requests', 'User requests belonging to the conversation shown on the detail page, with { id, status, iterations, total_tool_calls, total_cost, total_tokens }. Absent on the list tab; empty array if none exist yet.', 'array', false, 1500, 335, false, 'conversations'),
('matrx-admin/cx-dashboard', 'current_conversation_children', 'Active conversation''s sub-agent children', 'Child conversations forked from the one shown on the detail page (sub-agent runs), with { id, title, model_name, message_count }. Absent on the list tab; empty array if none exist.', 'array', false, 800, 340, false, 'conversations'),
('matrx-admin/cx-dashboard', 'request_list_results', 'Request list', 'The current page of the Requests table: one entry per user request with id, conversation_id, conversation_title, status, finish_reason, iterations, total_tool_calls, total_tokens, total_cost, model_name, created_at. Present only on the Requests list tab.', 'array', false, 3500, 400, false, 'requests'),
('matrx-admin/cx-dashboard', 'request_list_total', 'Request list total', 'Total user-request count matching the current filters (across all pages). Present only on the Requests list tab.', 'number', false, 6, 410, true, 'requests'),
('matrx-admin/cx-dashboard', 'current_request_id', 'Active request ID', 'UUID of the user request shown on the request detail page. Absent on the list tab.', 'string', false, 36, 420, true, 'requests'),
('matrx-admin/cx-dashboard', 'current_user_request', 'Active user request', 'Summary of the user request on the detail page: { id, conversation_id, conversation_title, status, finish_reason, iterations, total_tool_calls, total_input_tokens, total_output_tokens, total_cached_tokens, total_tokens, total_cost, total_duration_ms, api_duration_ms, error, model_name, provider, created_at, completed_at }. Absent on the list tab.', 'object', false, 1200, 425, true, 'requests'),
('matrx-admin/cx-dashboard', 'current_request_api_iterations', 'Active request''s API iterations', 'The individual model-call iterations (`cx_request` rows) that make up the user request on the detail page, each with { iteration, model_name, input_tokens, output_tokens, cached_tokens, cost, api_duration_ms, finish_reason }. Bindable rather than auto-context. Absent on the list tab.', 'array', false, 2500, 430, false, 'requests'),
('matrx-admin/cx-dashboard', 'current_request_tool_calls', 'Active request''s tool calls', 'Tool calls made during the user request on the detail page, each with { tool_name, tool_type, status, is_error, error_type, error_message, arguments, output, cost_usd, duration_ms }. The single most useful value for a debugging agent on this page. Absent on the list tab; empty array if no tools were called.', 'array', false, 4000, 435, false, 'requests'),
('matrx-admin/cx-dashboard', 'current_request_cost_verification', 'Active request''s cost verification', 'Server-computed cost cross-check for the user request on the detail page: whether the stored total_cost matches a recomputation from token counts, and the discrepancy if not (`has_discrepancy`). Absent on the list tab.', 'object', false, 300, 440, false, 'requests'),
('matrx-admin/cx-dashboard', 'usage_analytics', 'Usage analytics', 'The Usage & Cost tab''s full payload: total_requests plus by_day / by_provider / by_model cost and token breakdowns. Present only on the Usage tab.', 'object', false, 3000, 500, false, 'usage'),
('matrx-admin/cx-dashboard', 'usage_total_requests', 'Usage total requests', 'Total API request count backing the Usage tab''s charts for the current filters. Present only on the Usage tab.', 'number', false, 6, 510, true, 'usage'),
('matrx-admin/cx-dashboard', 'error_pending_count', 'Pending (stuck) request count', 'Number of user requests stuck in "pending" status (a known Python-side bug the Errors tab flags explicitly). Present only on the Errors tab.', 'number', false, 5, 600, true, 'errors'),
('matrx-admin/cx-dashboard', 'error_max_tokens_count', 'Max-tokens-hit count', 'Number of requests whose finish_reason is "max_tokens" on the Errors tab. Present only on the Errors tab.', 'number', false, 5, 610, true, 'errors'),
('matrx-admin/cx-dashboard', 'error_request_count', 'Errored request count', 'Number of user requests with a non-null error or status "error" on the Errors tab. Present only on the Errors tab.', 'number', false, 5, 620, true, 'errors'),
('matrx-admin/cx-dashboard', 'error_pending_requests', 'Pending requests', 'The pending (stuck) user requests listed on the Errors tab, each with { id, conversation_title, total_tokens, total_cost, created_at }. Bindable rather than auto-context. Present only on the Errors tab; empty array when none are pending.', 'array', false, 1500, 630, false, 'errors'),
('matrx-admin/cx-dashboard', 'error_tool_calls', 'Tool call errors', 'Tool calls that errored, listed on the Errors tab, each with { tool_name, tool_type, error_type, error_message, created_at }. Bindable rather than auto-context. Present only on the Errors tab; empty array when none exist.', 'array', false, 2000, 635, false, 'errors'),
('matrx-admin/cx-dashboard', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/cx-dashboard', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/cx-dashboard', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/cx-dashboard', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/cx-dashboard', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/applications', 'active_tab', 'Active tab', 'Which tab of the Applications hub is showing: "overview", "configuration", "catalogs", "installations", or "history". Derived from the pathname under /administration/applications. Always present.', 'string', true, 14, 100, true, 'hub'),
('matrx-admin/applications', 'application_count', 'Application count', 'Number of distinct applications known to the hub — the union of apps with a config row, a catalog entry, or an installed instance. Absent outside the Overview tab.', 'number', false, 2, 200, true, 'overview'),
('matrx-admin/applications', 'applications_overview_summary', 'Applications overview summary', 'One entry per known application: app slug, schema version, minimum supported version, config URL/flag counts, catalog totals (total/active/kinds), and fleet totals (total/recent/below-minimum/unreported). Absent outside the Overview tab.', 'array', false, 2000, 210, false, 'overview'),
('matrx-admin/applications', 'fleet_below_minimum_total', 'Fleet below minimum (total)', 'Sum, across every application, of installed instances reporting a version below that application''s published min_supported_app_version — the number the destructive banner names. Absent outside the Overview tab.', 'number', false, 3, 220, true, 'overview'),
('matrx-admin/applications', 'config_row_count', 'Configuration row count', 'Number of app_config rows loaded into the Configuration tab''s table. Absent outside the Configuration tab.', 'number', false, 2, 300, true, 'configuration'),
('matrx-admin/applications', 'config_rows_summary', 'Configuration rows summary', 'One entry per app_config row: app slug, schema_version, min_supported_app_version, updated_at, updated_by. Bindable rather than auto-context — the full config JSONB is not included here. Absent outside the Configuration tab.', 'array', false, 1500, 310, false, 'configuration'),
('matrx-admin/applications', 'config_editor_view', 'Configuration editor view', 'Client-side view mode of the Configuration tab: "list" (table), "edit" (an existing app open in the editor), or "new" (creating a row). Absent outside the Configuration tab.', 'string', false, 5, 320, true, 'configuration'),
('matrx-admin/applications', 'config_editor_app', 'Configuration editor app', 'App slug currently open in the Configuration editor. Empty when config_editor_view is "list" or "new". Absent outside the Configuration tab.', 'string', false, 20, 330, true, 'configuration'),
('matrx-admin/applications', 'catalog_selected_app', 'Catalog selected application', 'App slug the Catalogs tab''s app selector is currently filtered to (defaults to the DEFAULT_CATALOG_APP constant). Absent outside the Catalogs tab.', 'string', false, 20, 400, true, 'catalogs'),
('matrx-admin/applications', 'catalog_entry_count', 'Catalog entry count', 'Number of catalog_entries rows belonging to catalog_selected_app. Absent outside the Catalogs tab.', 'number', false, 3, 410, true, 'catalogs'),
('matrx-admin/applications', 'catalog_kind_summary', 'Catalog kind summary', 'One entry per catalog kind for the selected app: slug, label, registered status, total entries, active entries. Absent outside the Catalogs tab.', 'array', false, 1500, 420, false, 'catalogs'),
('matrx-admin/applications', 'catalog_view', 'Catalog editor view', 'Client-side view mode of the Catalogs tab: "kinds" (dashboard), "kind" (one kind''s table), "edit" (an existing entry open), or "new" (creating an entry). Absent outside the Catalogs tab.', 'string', false, 5, 430, true, 'catalogs'),
('matrx-admin/applications', 'catalog_selected_kind', 'Catalog selected kind', 'Kind slug currently open (catalog_view "kind", "edit", or "new"). Empty when catalog_view is "kinds". Absent outside the Catalogs tab.', 'string', false, 20, 440, true, 'catalogs'),
('matrx-admin/applications', 'catalog_selected_entry_id', 'Catalog selected entry id', 'UUID of the catalog_entries row open in the editor (catalog_view "edit" only). Absent otherwise, and outside the Catalogs tab.', 'string', false, 36, 450, true, 'catalogs'),
('matrx-admin/applications', 'installation_app', 'Installations application', 'The single application the Installations tab''s fleet belongs to (app_instances is single-app; the DEFAULT_APPLICATION constant). Absent outside the Installations tab.', 'string', false, 20, 500, true, 'installations'),
('matrx-admin/applications', 'installation_count', 'Installation count', 'Number of checked-in app_instances rows loaded into the Installations table. Absent outside the Installations tab.', 'number', false, 3, 510, true, 'installations'),
('matrx-admin/applications', 'installation_below_min_count', 'Installations below minimum', 'Number of installed instances whose reported app_version is below installation_min_supported_version. Absent outside the Installations tab.', 'number', false, 3, 520, true, 'installations'),
('matrx-admin/applications', 'installation_min_supported_version', 'Installations minimum supported version', 'The live min_supported_app_version published in app_config for installation_app, used as the compliance line for every row. Absent outside the Installations tab; null when the application has no configuration row.', 'string', false, 12, 530, true, 'installations'),
('matrx-admin/applications', 'history_entry_count', 'History entry count', 'Number of merged timeline entries currently loaded (configuration + catalog changes combined, newest first). Absent outside the History tab.', 'number', false, 3, 600, true, 'history'),
('matrx-admin/applications', 'history_fetch_limit', 'History fetch limit', 'Per-source row cap currently in effect (starts at 100; widens by the same amount each time the admin clicks Load more). Absent outside the History tab.', 'number', false, 4, 610, true, 'history'),
('matrx-admin/applications', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/applications', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/applications', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/applications', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/applications', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/agent-apps', 'admin_section', 'Admin section', 'Which sub-route is rendering: "dashboard", "apps", "edit", "categories", "executions", "analytics", or "rate_limits". Always present — each emitter declares its own value.', 'string', true, 10, 100, true, 'navigation'),
('matrx-admin/agent-apps', 'dashboard_total_apps', 'Dashboard: total apps', 'Total agent-app count shown on the dashboard stat tiles. Absent outside the dashboard section.', 'number', false, 4, 150, true, 'dashboard'),
('matrx-admin/agent-apps', 'dashboard_published_count', 'Dashboard: published count', 'Number of apps with status=published. Absent outside the dashboard section.', 'number', false, 4, 160, true, 'dashboard'),
('matrx-admin/agent-apps', 'dashboard_featured_count', 'Dashboard: featured count', 'Number of apps with is_featured=true. Absent outside the dashboard section.', 'number', false, 4, 170, true, 'dashboard'),
('matrx-admin/agent-apps', 'dashboard_verified_count', 'Dashboard: verified count', 'Number of apps with is_verified=true. Absent outside the dashboard section.', 'number', false, 4, 180, true, 'dashboard'),
('matrx-admin/agent-apps', 'dashboard_featured_apps', 'Dashboard: featured apps', 'Up to 6 published+featured apps shown in the ''Featured apps'' preview row (id, name, slug, status). Bindable rather than auto-context. Absent outside the dashboard section; empty array when none are featured.', 'array', false, 600, 190, false, 'dashboard'),
('matrx-admin/agent-apps', 'dashboard_recent_apps', 'Dashboard: recently updated apps', 'Up to 6 apps sorted by updated_at desc, shown in the ''Recently updated'' preview row. Bindable rather than auto-context. Absent outside the dashboard section.', 'array', false, 600, 195, false, 'dashboard'),
('matrx-admin/agent-apps', 'apps_list_total_count', 'Apps list: total count', 'Total apps loaded (before column filters are applied). Absent outside the apps-list section.', 'number', false, 4, 200, true, 'apps_list'),
('matrx-admin/agent-apps', 'apps_list_filtered_count', 'Apps list: filtered count', 'Number of rows visible after the current column filters are applied. Absent outside the apps-list section.', 'number', false, 4, 205, true, 'apps_list'),
('matrx-admin/agent-apps', 'apps_list_filters', 'Apps list: active filters', 'The column filter state: name/slug/creator text filters, status/category multi-select, featured/verified tri-state. Absent outside the apps-list section.', 'object', false, 300, 210, true, 'apps_list'),
('matrx-admin/agent-apps', 'apps_list_sort', 'Apps list: sort', 'Which column the table is sorted by and the direction (asc/desc). Absent outside the apps-list section.', 'object', false, 30, 220, true, 'apps_list'),
('matrx-admin/agent-apps', 'apps_list_rows', 'Apps list: rows', 'The filtered+sorted apps table rows: id, name, slug, status, category, creator_email, is_featured, is_verified, total_executions, unique_users_count, success_rate, total_cost, updated_at. Bindable rather than auto-context — this can be hundreds of rows. Absent outside the apps-list section.', 'array', false, 4000, 230, false, 'apps_list'),
('matrx-admin/agent-apps', 'selected_app_id', 'Selected app id', 'UUID of the agent app open in the admin edit shell (edit/[id]). Absent outside the edit section.', 'string', false, 36, 300, true, 'app_detail'),
('matrx-admin/agent-apps', 'selected_app_summary', 'Selected app summary', 'Identity of the app being edited: name, slug, category, creator_email, tagline, description, status. Absent outside the edit section.', 'object', false, 600, 310, true, 'app_detail'),
('matrx-admin/agent-apps', 'selected_app_analytics', 'Selected app analytics', 'Aggregate counters for the app being edited: total_executions, unique_users_count, success_rate, total_cost. Absent outside the edit section.', 'object', false, 120, 320, true, 'app_detail'),
('matrx-admin/agent-apps', 'selected_app_tab', 'Selected app: active tab', '"admin" (moderation + metadata) or "code" (component-code editor) — which tab of the edit shell is open. Absent outside the edit section.', 'string', false, 6, 330, true, 'app_detail'),
('matrx-admin/agent-apps', 'selected_app_timestamps', 'Selected app timestamps', 'created_at, updated_at, published_at, last_execution_at for the app being edited. published_at/last_execution_at may be null. Absent outside the edit section.', 'object', false, 150, 340, true, 'app_detail'),
('matrx-admin/agent-apps', 'categories_list', 'Categories list', 'Every agent-app category row: id, name, description, icon, sort_order. Bindable rather than auto-context. Absent outside the categories section.', 'array', false, 1200, 400, false, 'categories'),
('matrx-admin/agent-apps', 'categories_count', 'Categories count', 'Number of categories loaded. Absent outside the categories section.', 'number', false, 3, 405, true, 'categories'),
('matrx-admin/agent-apps', 'categories_search', 'Categories search text', 'Text currently typed in the category search box. Absent outside the categories section; empty string when untouched.', 'string', false, 20, 410, true, 'categories'),
('matrx-admin/agent-apps', 'selected_category', 'Selected category', 'The category open in the right-hand edit panel: id, name, description, icon, sort_order. Absent when no category is selected or outside the categories section.', 'object', false, 250, 420, true, 'categories'),
('matrx-admin/agent-apps', 'category_has_unsaved_changes', 'Category has unsaved changes', 'True when the selected category''s edit form has been changed but not yet saved. Absent when no category is selected.', 'boolean', false, 5, 430, true, 'categories'),
('matrx-admin/agent-apps', 'executions_active_tab', 'Executions: active tab', '"executions" or "errors" — which tab of the Executions & Errors page is open. Absent outside the executions section.', 'string', false, 10, 500, true, 'executions'),
('matrx-admin/agent-apps', 'executions_rows', 'Execution rows', 'Loaded execution log rows: success, app_name/slug, task_id, user/fingerprint/ip identifier, tokens_used, cost, execution_time_ms, created_at. Bindable rather than auto-context; up to 500 rows. Absent outside the Executions tab.', 'array', false, 5000, 510, false, 'executions'),
('matrx-admin/agent-apps', 'executions_stats', 'Execution stats', 'total/success/failed counts over the currently loaded execution rows. Absent outside the Executions tab.', 'object', false, 40, 520, true, 'executions'),
('matrx-admin/agent-apps', 'executions_app_filter', 'Executions app filter', 'Text filter applied to the execution rows by app name/slug/id. Absent outside the Executions tab; empty when untouched.', 'string', false, 20, 530, true, 'executions'),
('matrx-admin/agent-apps', 'executions_success_filter', 'Executions success filter', '"all", "success", or "failed" — the outcome filter applied to the loaded execution rows. Absent outside the Executions tab.', 'string', false, 7, 535, true, 'executions'),
('matrx-admin/agent-apps', 'errors_rows', 'Error rows', 'Loaded app-execution error rows: resolved, error_type, app_name/slug, error_message, created_at. Bindable rather than auto-context; up to 500 rows. Absent outside the Errors tab.', 'array', false, 4000, 540, false, 'executions'),
('matrx-admin/agent-apps', 'errors_stats', 'Error stats', 'total/resolved/unresolved counts over the currently loaded error rows. Absent outside the Errors tab.', 'object', false, 40, 550, true, 'executions'),
('matrx-admin/agent-apps', 'errors_resolved_filter', 'Errors resolved filter', '"all", "resolved", or "unresolved" — the resolution filter applied to the loaded error rows. Absent outside the Errors tab.', 'string', false, 10, 560, true, 'executions'),
('matrx-admin/agent-apps', 'selected_error', 'Selected error', 'The error open in the detail dialog: error_type, error_message, error_code, app_name/slug, variables_sent, expected_variables, error_details, resolved, created_at. Absent when no error is open.', 'object', false, 1200, 570, false, 'executions'),
('matrx-admin/agent-apps', 'analytics_totals', 'Analytics: platform totals', 'Sum across every loaded app: totalExecutions, totalUniqueUsers, totalCost, totalTokens. Absent outside the analytics section.', 'object', false, 100, 100, true, 'analytics'),
('matrx-admin/agent-apps', 'analytics_overall_success_rate', 'Analytics: overall success rate', 'Execution-weighted success rate across all apps, as a percentage (0-100). Absent outside the analytics section.', 'number', false, 6, 110, true, 'analytics'),
('matrx-admin/agent-apps', 'analytics_per_app_rows', 'Analytics: per-app rows', 'Per-app aggregates shown in the performance list: name, slug, status, is_featured, is_verified, total_executions, unique_users_count, success_rate, avg_execution_time_ms, total_cost, last_execution_at. Bindable rather than auto-context. Absent outside the analytics section.', 'array', false, 4000, 120, false, 'analytics'),
('matrx-admin/agent-apps', 'rate_limits_rows', 'Rate limit rows', 'Loaded rate-limit rows: app_name/slug, identifier (user_id/ip_address/fingerprint), is_blocked, execution_count, first/last_execution_at, blocked_until, blocked_reason. Bindable rather than auto-context; up to 500 rows. Absent outside the rate-limits section.', 'array', false, 5000, 600, false, 'rate_limits'),
('matrx-admin/agent-apps', 'rate_limits_stats', 'Rate limit stats', 'total/blocked/active/users/ips counts over the currently loaded rate-limit rows. Absent outside the rate-limits section.', 'object', false, 60, 610, true, 'rate_limits'),
('matrx-admin/agent-apps', 'rate_limits_filters', 'Rate limit filters', 'The active column filters: appName/identifier text filters, identifierType (user/ip/fingerprint), blocked tri-state (defaults to ''blocked''). Absent outside the rate-limits section.', 'object', false, 120, 620, true, 'rate_limits'),
('matrx-admin/agent-apps', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/agent-apps', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/agent-apps', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/agent-apps', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/agent-apps', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'CX Dashboard', value_groups = '[{"key":"dashboard_nav","label":"Dashboard navigation","sortOrder":100,"description":"Which tab of the CX dashboard the admin is currently on."},{"key":"overview","label":"Overview KPIs","sortOrder":200,"description":"Aggregate metrics shown on the Overview tab: totals, costs, tokens, error rates, per-model and per-tool breakdowns, daily trend."},{"key":"conversations","label":"Conversations","sortOrder":300,"description":"The Conversations list (with its filters) and, on a detail page, the active conversation''s messages, sub-agent children, and user requests."},{"key":"requests","label":"User requests","sortOrder":400,"description":"The Requests list (with its filters) and, on a detail page, the active user request''s API iterations, tool calls, and cost verification."},{"key":"usage","label":"Usage & cost","sortOrder":500,"description":"Usage/cost analytics broken out by day, provider, and model."},{"key":"errors","label":"Errors & issues","sortOrder":600,"description":"Pending (stuck) requests, max-tokens hits, and tool-call errors surfaced on the Errors tab."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/chat/cx-dashboard', intro = '<surface_intro>
This is an ADMIN surface: the CX (customer experience) dashboard at /administration/chat/cx-dashboard, a read-only super-admin console over the cx_* chat tables.

It has five tabs plus two detail pages, all read via dashboard_section: "overview" (aggregate KPIs, cost/token trends, model and tool usage), "conversations" (paginated conversation list) and "conversation_detail" (one conversation''s messages, sub-agent children, and requests), "requests" (paginated user-request list) and "request_detail" (one request''s API iterations, tool calls, and cost verification), "usage" (cost/token analytics by day/provider/model), and "errors" (pending/stuck requests, max-tokens hits, tool-call errors).

Only the values matching the current dashboard_section are populated — everything else is absent, not stale. Treat every row and field here as live production data: summarize, diagnose, and explain it, but never republish it verbatim at scale. You never execute anything on this surface — it has no write path.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/cx-dashboard';
UPDATE ui.ui_surface SET label = 'Applications', value_groups = '[{"key":"hub","label":"Applications hub","sortOrder":100,"description":"Which of the five tabs the admin is currently on."},{"key":"overview","label":"Overview","sortOrder":200,"description":"Per-application summary cards: config/catalog/fleet counts and the below-minimum-version warning."},{"key":"configuration","label":"Configuration","sortOrder":300,"description":"Remote runtime configuration rows (app_config) and which one, if any, is open in the editor."},{"key":"catalogs","label":"Catalogs","sortOrder":400,"description":"Remote catalog entries (catalog_entries) for the selected application, grouped by kind, and the editor view."},{"key":"installations","label":"Installations","sortOrder":500,"description":"The installed fleet (app_instances) and its standing against the live minimum supported version."},{"key":"history","label":"History","sortOrder":600,"description":"The merged configuration + catalog audit timeline and how far back it currently loads."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/applications', intro = '<surface_intro>
This is an ADMIN surface: the Applications hub at /administration/applications — the console governing every shipped Matrx CLIENT (desktop, browser extension, mobile), not user-created agent apps. Five tabs: Overview, Configuration, Catalogs, Installations, History.

active_tab tells you which tab the admin is on right now and is always present. On Overview, applications_overview_summary and fleet_below_minimum_total describe every known application''s config/catalog/fleet standing. On Configuration, config_rows_summary lists the remote runtime config for each application and config_editor_view/config_editor_app say whether one is open for editing. On Catalogs, catalog_kind_summary breaks down remote catalog entries by kind for catalog_selected_app, and catalog_view/catalog_selected_kind/catalog_selected_entry_id track the drill-down. On Installations, the fleet is compared against installation_min_supported_version, with installation_below_min_count naming instances running unsupported builds. On History, history_entry_count and history_fetch_limit describe the merged audit timeline window.

Only the values matching active_tab are populated — each tab mounts its own nested emitter, so everything belonging to another tab is absent, not stale.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/applications';
UPDATE ui.ui_surface SET label = 'Agent Apps Admin', value_groups = '[{"key":"navigation","label":"Navigation","sortOrder":100,"description":"Which sub-route of the agent-apps admin is rendering."},{"key":"dashboard","label":"Dashboard","sortOrder":150,"description":"Aggregate stat-tile counts and the featured / recently-updated app previews on the dashboard."},{"key":"apps_list","label":"Apps list","sortOrder":200,"description":"The full apps table''s filters, sort, and loaded rows on the Apps tab."},{"key":"app_detail","label":"App detail","sortOrder":300,"description":"The single agent app open in the edit/[id] admin shell — its identity, analytics, active tab, and timestamps."},{"key":"categories","label":"Categories","sortOrder":400,"description":"The category list and the category open for editing."},{"key":"executions","label":"Executions & errors","sortOrder":500,"description":"The Executions and Errors tabs: their filters, stats, rows, and the error open in the detail dialog."},{"key":"analytics","label":"Analytics","sortOrder":550,"description":"Platform-wide execution/cost totals and per-app rows."},{"key":"rate_limits","label":"Rate limits","sortOrder":600,"description":"The rate-limit table''s filters, stats, and rows."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/agents/agent-apps', intro = '<surface_intro>
This is an ADMIN surface covering the whole Agent Apps admin subtree at /administration/agents/agent-apps/**. It moderates every public agent-backed app on the platform (app.definition rows) — feature/verify/publish status, categories, execution history, per-app analytics, and rate limits.

admin_section tells you which sub-route is rendering: "dashboard" (overview stat tiles + featured/recent app previews), "apps" (the full filterable/sortable apps table), "edit" (one app''s admin + component-code shell), "categories" (the category list/editor), "executions" (execution log + error tabs), "analytics" (platform-wide aggregates), or "rate_limits" (per-identifier execution throttling).

How to read the values: each section''s group (dashboard_*, apps_list_*, selected_app_*, categories_*, executions_*/errors_*, analytics_*, rate_limits_*) is only populated when admin_section matches — everything else on this surface is absent, not stale.

What you may safely do: help the admin draft moderation notes, error resolutions, or category descriptions, summarize analytics or a suspicious rate-limit pattern, and explain what a row means. You never feature, verify, publish, delete, resolve, or unblock anything yourself — those are the admin''s own actions, which call updateAgentAppAdmin / resolveAgentAppError / unblockAgentAppRateLimit.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/agent-apps';
