-- Guard: manifest surfaces missing a ui_surface row
SELECT s.name FROM (VALUES ('matrx-admin/email'), ('matrx-admin/server-logs'), ('matrx-admin/sandbox')) AS s(name) LEFT JOIN ui.ui_surface u ON u.name = s.name WHERE u.name IS NULL;

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-admin/email', 'recipient_mode', 'Recipient mode', '"custom" when the admin is typing raw email addresses, "selected" when picking from the platform user list. Always present.', 'string', true, 8, 100, true, 'recipients'),
('matrx-admin/email', 'custom_emails_raw', 'Custom email addresses', 'The raw comma/newline-separated text in the custom-emails textarea. Empty when recipient_mode is "selected" or the field is untouched.', 'string', false, 120, 110, true, 'recipients'),
('matrx-admin/email', 'selected_user_ids', 'Selected user IDs', 'UUIDs of the platform users checked in the "Selected Users" picker. Preselected from `?userId=` when arriving via the Accounts "Email user" row action. Empty array when recipient_mode is "custom" or nobody is checked.', 'array', false, 200, 120, true, 'recipients'),
('matrx-admin/email', 'subject', 'Subject', 'The email subject line currently in the form. Empty until the admin types one or picks a template.', 'string', false, 60, 200, true, 'compose'),
('matrx-admin/email', 'message_body', 'Message body', 'The plain-text email body currently in the form. Empty until the admin types one or picks a template.', 'string', false, 600, 210, true, 'compose'),
('matrx-admin/email', 'custom_from', 'Custom from address', 'The optional override "From" address/display name typed under Advanced Options. Empty when unset (the default from-address applies).', 'string', false, 40, 220, true, 'compose'),
('matrx-admin/email', 'available_templates', 'Available templates', 'Quick-start email templates loaded from `/api/admin/email`, each with { id, name, subject, message }. Empty array while loading or if none are configured.', 'array', true, 800, 230, false, 'compose'),
('matrx-admin/email', 'is_sending', 'Sending in progress', 'True while a POST to /api/admin/email is in flight. Always present.', 'boolean', true, 5, 240, true, 'compose'),
('matrx-admin/email', 'last_send_result', 'Last send result', 'Outcome of the most recent send attempt: { success, msg }. Absent until the admin has clicked Send at least once this session.', 'object', false, 100, 250, true, 'compose'),
('matrx-admin/email', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/email', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/email', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/email', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/email', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/server-logs', 'selected_app', 'Selected app', 'App key of the service whose logs are shown, e.g. "ai-dream-server", "scraper-service-dev". Always present — comes from the [app] route segment.', 'string', true, 24, 100, true, 'app_selection'),
('matrx-admin/server-logs', 'selected_app_environment', 'Selected app environment', '"production" or "development" for the selected app, taken from the static app registry. Always present.', 'string', true, 12, 105, true, 'app_selection'),
('matrx-admin/server-logs', 'available_apps', 'Available apps', 'The static catalogue of services the viewer can switch to, each with { key, label, env }. Always present — does not depend on a fetch.', 'array', true, 400, 110, false, 'app_selection'),
('matrx-admin/server-logs', 'requested_line_count', 'Requested line count', 'Number of trailing log lines requested from Coolify for the current fetch (one of a fixed set: 50-10000). Always present.', 'number', true, 5, 200, true, 'fetch_state'),
('matrx-admin/server-logs', 'poll_interval_ms', 'Auto-refresh interval (ms)', 'How often the viewer re-fetches logs automatically; 0 means manual refresh only. Always present.', 'number', true, 6, 210, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_fetched_at', 'Logs fetched at', 'ISO timestamp of the last successful log fetch. Absent before the first fetch completes.', 'string', false, 25, 220, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_loading', 'Logs loading', 'True while a log fetch is in flight. Always present.', 'boolean', true, 5, 230, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_fetch_error', 'Fetch error', 'Error message from the last failed log fetch. Absent when the last fetch succeeded or none has run yet.', 'string', false, 150, 240, true, 'fetch_state'),
('matrx-admin/server-logs', 'log_filters', 'Active log filters', 'The parsed-log filter state applied to the fetched text: { levels, categories, urgencies, search, modules, modules_cleared, endpoints, endpoints_cleared, show_json_payloads }. levels/categories/urgencies are the SELECTED subsets of the log-rules enums — a full array means nothing is narrowed. modules/endpoints are allowlists: empty with the matching *_cleared false means "no narrowing", empty with it true means "show nothing". Always present — the viewer always has a filter object, even at defaults.', 'object', true, 400, 300, true, 'filters'),
('matrx-admin/server-logs', 'log_noise_excludes', 'Noise exclusion presets', 'Which built-in noise presets are toggled on (cloudFiles, healthChecks, admin, replaySweep, wakeListener, autoIngestListener) — persisted in localStorage across sessions. Always present.', 'object', true, 150, 310, false, 'filters'),
('matrx-admin/server-logs', 'view_mode', 'View mode', 'Layout mode of the log panel — "log-only" or a split/inspector mode alongside the JSON payload viewer. Always present.', 'string', true, 14, 320, true, 'filters'),
('matrx-admin/server-logs', 'log_view_range', 'Line range window', 'The Range panel''s window over the fetched lines, applied BEFORE the filters: { start_offset, display_count }. display_count is null when the window runs to the end. Always present — { start_offset: 0, display_count: null } means the whole fetched buffer is in play.', 'object', true, 50, 330, false, 'filters'),
('matrx-admin/server-logs', 'fetched_log_line_count', 'Fetched log line count', 'Total number of lines returned by the last fetch, before the range window and filters narrow them. Always present — 0 before the first fetch. This is the denominator in the toolbar''s "visible/fetched lines" readout.', 'number', true, 5, 395, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_line_count', 'Visible log line count', 'Number of parsed log lines currently visible after the range window and filters are applied. Always present — 0 when nothing matches or no logs are loaded. This is the numerator in the toolbar''s "visible/fetched lines" readout.', 'number', true, 5, 400, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_level_counts', 'Visible level counts', 'How many of the currently visible lines carry each log level, as { DEBUG, INFO, WARNING, ERROR, CRITICAL, UNKNOWN }. Every key is present, with 0 where no line matched. Always present — all zeros before the first fetch. Use this to answer "is anything erroring" without reading the log text.', 'object', true, 110, 405, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_lines', 'Visible log lines', 'Raw text of the log lines on screen right now — the lines left after the range window and filters, blank lines dropped, oldest first. TRUNCATED to a bounded TAIL (the newest lines) when the visible set is large; when that happens the text starts with a `[truncated: showing the last N of M …]` banner, so trust that banner over your own count. Absent when no lines are visible. NOTE: when `view_mode` is "raw" the panel shows unparsed text instead and `raw_logs` is what the admin is reading — this value still describes the parsed view behind it.', 'string', false, 18000, 408, true, 'log_view'),
('matrx-admin/server-logs', 'raw_logs', 'Raw log text', 'The unparsed log text returned by the last fetch for the selected app — what the "raw" view mode shows, with no range window, filters or parsing applied. TRUNCATED to a bounded tail like `visible_log_lines`, with the same banner. Bindable only — prefer `visible_log_lines` or a selected line for targeted questions. Absent before the first fetch.', 'string', false, 20000, 410, false, 'log_view'),
('matrx-admin/server-logs', 'selected_log_line', 'Selected log line', 'The single parsed log line the admin has clicked to inspect: { raw, timestamp, level, module, category, urgency }. Absent when nothing is selected.', 'object', false, 500, 420, true, 'log_view'),
('matrx-admin/server-logs', 'selected_line_range', 'Selected line range', 'The multi-line range the admin has marked with click / shift-click, as { anchor_line, tail_line, selected_count } using 1-based on-screen line numbers. tail_line is null when only the anchor is set. Absent when nothing is marked; the marked text itself arrives as the baseline `selection` value.', 'object', false, 60, 425, true, 'log_view'),
('matrx-admin/server-logs', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/server-logs', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/server-logs', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/server-logs', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/server-logs', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/sandbox', 'sandbox_active_count', 'Active instance count', 'Count of instances currently in a "creating", "starting", "ready", or "running" status among the loaded (filtered) set. Always present — 0 while loading or empty.', 'number', true, 4, 100, true, 'fleet_stats'),
('matrx-admin/sandbox', 'sandbox_total_count', 'Total instance count', 'Count of instances currently loaded (matching the active status filter, up to the 100-row page limit). Always present.', 'number', true, 4, 110, true, 'fleet_stats'),
('matrx-admin/sandbox', 'sandbox_unique_user_count', 'Unique user count', 'Number of distinct user_ids among the loaded instances. Always present.', 'number', true, 4, 120, true, 'fleet_stats'),
('matrx-admin/sandbox', 'sandbox_failed_count', 'Failed instance count', 'Count of instances with status "failed" among the loaded set. Always present.', 'number', true, 4, 130, true, 'fleet_stats'),
('matrx-admin/sandbox', 'sandbox_status_filter', 'Status filter', 'The active status filter chip: "all", or one of creating/starting/ready/running/stopped/failed/expired. Always present — defaults to "all".', 'string', true, 10, 200, true, 'instance_list'),
('matrx-admin/sandbox', 'sandbox_instances', 'Sandbox instances', 'The current page of sandbox instances (up to 100) matching the status filter, each with { id, sandbox_id, user_id, status, created_at, expires_at, tier, container_id, ttl_seconds, hot_path, cold_path }. Bindable rather than auto-context — this is per-user infrastructure data across the whole platform. Empty array when none match.', 'array', true, 6000, 210, false, 'instance_list'),
('matrx-admin/sandbox', 'sandbox_list_loading', 'List loading', 'True while the instance list is being (re)fetched. Always present.', 'boolean', true, 5, 220, true, 'instance_list'),
('matrx-admin/sandbox', 'sandbox_list_error', 'List error', 'Error message from the last failed fetch, stop, or delete action. Absent when the last action succeeded or none has run yet.', 'string', false, 150, 230, true, 'instance_list'),
('matrx-admin/sandbox', 'expanded_sandbox_instance_id', 'Expanded instance ID', 'UUID of the instance row the admin has expanded to see full detail. Absent when no row is expanded.', 'string', false, 36, 300, true, 'instance_detail'),
('matrx-admin/sandbox', 'expanded_sandbox_instance', 'Expanded instance detail', 'Full detail of the expanded row — { id, sandbox_id, user_id, status, created_at, expires_at, tier, container_id, ttl_seconds, hot_path, cold_path, stop_reason, last_heartbeat_at, config } — exactly the fields the detail panel renders. This is the ONE per-instance value in automatic context: `sandbox_instances` is bindable-only, so without it an agent knows a row is open but nothing about it. It stringifies past the 200-char default inline ceiling, so it arrives as a DEFERRED context item the agent retrieves on demand rather than inlined prose — verified working in a live run. Absent when no row is expanded, and also when the expanded id has dropped out of the loaded set (narrowing the status filter retires the row while the id stays set).', 'object', false, 700, 310, true, 'instance_detail'),
('matrx-admin/sandbox', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/sandbox', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/sandbox', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/sandbox', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/sandbox', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Upsert all manifest write targets
INSERT INTO ui.ui_surface_write_target (surface_name, name, label, description, value_type, mode, updates_value, group_key, sort_order, apply_policy) VALUES
('matrx-admin/email', 'email_draft', 'Email draft', 'Stages the email COPY into the compose form the admin is looking at. Nothing is sent and nothing leaves the building — the admin still presses "Send Email", and that press is never an agent action. Value: an object with AT LEAST ONE of { subject, message_body }. Each key REPLACES that whole field; omit a key to leave it exactly as the admin left it (nothing here appends — read the current draft back from the `subject` and `message_body` values first if you mean to extend rather than replace). `subject` — the subject line; a non-empty plain-text string, ONE line only (it is an email header, so line breaks are refused), at most 200 characters. `message_body` — the plain-text body; a non-empty plain-text string, at most 25000 characters. Real newlines are fine and are preserved as written. This form sends PLAIN TEXT, not HTML — markup arrives as literal characters, so write prose, not tags. Send both as plain text, not JSON and not JSON-encoded. To reuse a quick-start template, read `available_templates` and write that entry''s subject/message through this target so the admin can see and edit what lands. WHO the email goes to is NOT writable — recipient_mode, the typed address list, the selected users, and the From address have no write target on this surface. If the admin asks you to change the recipients, say that they set those themselves and describe what you would pick. Refused while is_sending is true — a send is already in flight against the OLD copy, so editing it would leave the form describing something nobody sent.', 'object', 'draft', NULL, 'compose', 300, 'ask')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, mode = EXCLUDED.mode, updates_value = EXCLUDED.updates_value, group_key = EXCLUDED.group_key, sort_order = EXCLUDED.sort_order, apply_policy = EXCLUDED.apply_policy, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'Email Users', value_groups = '[{"key":"recipients","label":"Recipients","sortOrder":100,"description":"Who the email is addressed to: custom typed addresses, or a set of selected platform users."},{"key":"compose","label":"Message","sortOrder":200,"description":"The subject/body being composed, the available templates, and the last send attempt''s outcome."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/users/email', intro = '<surface_intro>
This is an ADMIN surface: the Email Users compose tool at /administration/users/email, for sending a one-off email to either hand-typed addresses or selected platform users.

recipient_mode tells you whether custom_emails_raw or selected_user_ids is the live recipient list. subject and message_body are the draft; available_templates lists quick-start options the admin can pick from. is_sending is true only while a send POST is in flight; last_send_result reflects the LAST attempt only, never anything current or planned.

What you may safely do: help draft or improve subject/message copy, suggest a template, or reason about the selected recipients. The email_draft write target lets you put that copy straight into the form. You never send the email yourself — sending is the admin pressing "Send Email" — and you never choose the recipients or the From address: those have no write target here.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/email';
UPDATE ui.ui_surface SET label = 'Server Logs', value_groups = '[{"key":"app_selection","label":"App selection","sortOrder":100,"description":"Which backend service/environment the viewer is showing, and the catalogue of services it can switch between."},{"key":"fetch_state","label":"Fetch state","sortOrder":200,"description":"How many lines were requested, the auto-poll interval, when the log text was last fetched, and any fetch error."},{"key":"filters","label":"Filters & search","sortOrder":300,"description":"The active level/category/urgency/module/endpoint/search filters, the noise-exclusion presets, and the line-range window applied to the parsed log lines."},{"key":"log_view","label":"Log content","sortOrder":400,"description":"The parsed log lines currently visible after filtering, and the line (or range) the admin has selected for inspection."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/compute/server-logs', intro = '<surface_intro>
This is an ADMIN surface: the super-admin server log viewer at /administration/compute/server-logs/[app], showing live Coolify logs for one backend service (aidream, scraper-service, or matrx-ai, each with a production and development deployment).

The viewer fetches raw log text, parses it into lines with level/category/urgency/module, and lets the admin filter, search, and select a line for JSON-payload inspection. selected_app and selected_app_environment tell you which service/environment you are looking at; log_filters, log_noise_excludes and log_view_range describe what has been narrowed out; fetched_log_line_count vs visible_log_line_count tell you how much of the fetch survived that narrowing.

READ THE LOGS FROM visible_log_lines — it carries the actual text of the lines on screen. visible_log_level_counts answers "is anything erroring" without reading them. selected_log_line and selected_line_range tell you what the admin has singled out; the marked text arrives as the baseline "selection" value. Both visible_log_lines and raw_logs are capped to a TAIL of the newest lines and announce it with a "[truncated: ...]" banner — believe that banner rather than counting lines yourself, and say so when a question depends on lines that were cut.

What you may safely do: read the visible/selected log content and explain errors, summarize patterns, or suggest a better filter or search term. This surface is READ-ONLY BY DESIGN — it declares no write targets, and you cannot change a filter, restart, deploy, or modify the service being logged. The logs are the record of what happened; if you propose a filter or a fix, say it is a suggestion and never imply you applied it.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/server-logs';
UPDATE ui.ui_surface SET label = 'Sandbox Management', value_groups = '[{"key":"fleet_stats","label":"Fleet stats","sortOrder":100,"description":"Summary counts across all sandbox instances currently loaded: active, total, unique users, failed."},{"key":"instance_list","label":"Instance list","sortOrder":200,"description":"The filtered table of sandbox instances, the active status filter, and load/error state."},{"key":"instance_detail","label":"Expanded instance","sortOrder":300,"description":"The single instance row the admin has expanded, if any — its full detail (container, TTL, paths, config)."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'verified', readiness_note = NULL, url_pattern = '/administration/compute/sandbox', intro = '<surface_intro>
This is an ADMIN surface: the super-admin sandbox fleet console at /administration/compute/sandbox — every on-demand isolated agent-execution instance across every user, not just the current admin''s own.

sandbox_active_count / sandbox_total_count / sandbox_unique_user_count / sandbox_failed_count summarize the currently loaded (filtered) set; sandbox_status_filter tells you which status chip is active; sandbox_instances is the actual row data. expanded_sandbox_instance_id is set when the admin has drilled into one row''s full detail, and expanded_sandbox_instance carries that row itself (container id, TTL, hot/cold storage paths, stop reason, last heartbeat, config) — it is the only per-instance data in your automatic context, since sandbox_instances is bindable-only.

What you may safely do: read this fleet data to diagnose stuck/failed instances, summarize usage across users, or explain a status. This surface is READ-ONLY for agents — it declares no write targets, and there is nothing here you can change. Stopping, deleting, or minting SSH access are admin button actions — never assume one happened because it was discussed, and never offer to perform one. SSH credentials are never placed in this surface''s context; they are one-time secret material shown only in the admin''s own dialog.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/sandbox';

