-- Image Studio family surface registration: ui_surface rows + manifest value sync
-- for matrx-user/image-studio, image-generate, image-edit, image-annotate (+ images refresh).
-- Idempotent: ON CONFLICT upserts + plain UPDATEs. Generated by scripts/emit-surface-sync-sql.ts.

INSERT INTO ui.ui_surface (name, client_name, description, sort_order, is_active)
VALUES
  ('matrx-user/image-studio', 'matrx-user', 'Image Studio batch preset converter at /images/convert (fronted by the /images/studio landing).', 151, true),
  ('matrx-user/image-generate', 'matrx-user', 'Text-to-image generation at /images/generate (also fronts /images/ai-generate).', 152, true),
  ('matrx-user/image-edit', 'matrx-user', 'Single-image editor at /images/edit/[id] (Filerobot canvas, AI ops, versions); also opens as a modal.', 153, true),
  ('matrx-user/image-annotate', 'matrx-user', 'Screenshot markup at /images/annotate (marker.js annotations baked to PNG); also opens as a modal.', 154, true)
ON CONFLICT (name) DO NOTHING;

-- Guard: manifest surfaces missing a ui_surface row
SELECT s.name FROM (VALUES ('matrx-user/images'), ('matrx-user/image-studio'), ('matrx-user/image-generate'), ('matrx-user/image-edit'), ('matrx-user/image-annotate')) AS s(name) LEFT JOIN ui.ui_surface u ON u.name = s.name WHERE u.name IS NULL;

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-user/images', 'search_query', 'Search query', 'Text in the library search box; matches image file names and partial ids. Empty when the user is not searching.', 'string', false, 20, 300, true, 'library_query'),
('matrx-user/images', 'recents_only', 'Recents filter on', 'True when the Recents chip is active, restricting the list to images touched in the last 30 days. Always present; false by default.', 'boolean', true, 5, 305, true, 'library_query'),
('matrx-user/images', 'view_mode', 'View mode', 'How tiles are rendered: "cozy", "compact", or "list". Always present; persisted per user in localStorage.', 'string', true, 7, 310, true, 'library_query'),
('matrx-user/images', 'library_query_summary', 'Library query summary', 'Composite object of everything shaping the visible list: `{ search_query, recents_only, view_mode, selection_mode }`. Always present.', 'object', true, 160, 315, true, 'library_query'),
('matrx-user/images', 'visible_image_count', 'Visible image count', 'Number of image rows matching the current search and recents filter. Always present; zero on an empty view.', 'number', true, 4, 330, true, 'visible_images'),
('matrx-user/images', 'total_image_count', 'Total image count', 'Number of non-deleted image files in the user''s whole cloud library, ignoring search and filters. Always present.', 'number', true, 4, 335, true, 'visible_images'),
('matrx-user/images', 'visible_images', 'Visible images', 'Array of `{ id, name, path, mime_type, size, visibility, updated_at, public_url }` for the image rows in scope, newest first, capped at 200 entries to protect the context window. `public_url` appears only for verified-durable CDN URLs — never a signed URL. Empty array when nothing matches.', 'array', true, 8000, 340, false, 'visible_images'),
('matrx-user/images', 'visible_image_ids', 'Visible image IDs', 'Array of UUIDs for the image rows in scope, in display order, capped at 200. THE durable references — resolve bytes from these. Empty array when nothing matches.', 'array', true, 1500, 345, false, 'visible_images'),
('matrx-user/images', 'selected_image_ids', 'Selected image IDs', 'Array of UUIDs of every bulk-checkbox-selected image. Absent when nothing is selected.', 'array', false, 300, 360, true, 'image_selection'),
('matrx-user/images', 'selected_image_names', 'Selected image names', 'Array of file names matching `selected_image_ids`, in the same order. Absent when nothing is selected.', 'array', false, 300, 365, true, 'image_selection'),
('matrx-user/images', 'selected_count', 'Selected image count', 'Number of images in the bulk selection. Always present; zero when nothing is selected.', 'number', true, 3, 370, true, 'image_selection'),
('matrx-user/images', 'selected_images', 'Selected images', 'Composite array of `{ id, name, path, mime_type, size, visibility, updated_at, public_url }` for every bulk-selected image — enough for a batch agent to act without a second lookup. Absent when nothing is selected.', 'array', false, 900, 375, true, 'image_selection'),
('matrx-user/images', 'selection_mode', 'Picker selection mode', 'How the tab is being used: "none" (browse — clicking opens the viewer), "single", or "multiple" (the tab is acting as an image picker). Always present.', 'string', true, 8, 380, true, 'image_selection'),
('matrx-user/images', 'tree_status', 'Library load status', 'Load state of the cloud-files tree backing this library: "idle", "loading", "loaded", or "error". Always present; anything but "loaded" means the listing is incomplete.', 'string', true, 7, 390, true, 'library_status'),
('matrx-user/images', 'bulk_operation', 'Bulk operation in flight', 'The bulk action currently running: "download", "move", "visibility", or "delete". Empty when no bulk work is in flight.', 'string', false, 10, 395, true, 'library_status'),
('matrx-user/images', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/images', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/images', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/images', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/images', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/image-studio', 'source_file_count', 'Source file count', 'Number of images the user has dropped into the studio. Always present; zero on an empty workspace.', 'number', true, 3, 300, true, 'studio_sources'),
('matrx-user/image-studio', 'source_files', 'Source files', 'Array of `{ name, filename_base, mime_type, size, width, height, status, variant_count, metadata_status }` for every dropped image, capped at 50 entries. Files are browser-local — no cloud file id exists until the user saves. Empty array on an empty workspace.', 'array', true, 1500, 305, true, 'studio_sources'),
('matrx-user/image-studio', 'selected_preset_ids', 'Selected preset IDs', 'Array of preset ids (e.g. `og-image`, `favicon-32`) applied to every source file on Generate. Empty array when nothing is selected.', 'array', true, 200, 330, true, 'studio_settings'),
('matrx-user/image-studio', 'selected_preset_count', 'Selected preset count', 'Number of selected presets. Always present; zero when nothing is selected.', 'number', true, 3, 335, true, 'studio_settings'),
('matrx-user/image-studio', 'output_format', 'Output format', 'Global output format for generated variants: "webp", "avif", "jpeg", or "png". Always present.', 'string', true, 4, 340, true, 'studio_settings'),
('matrx-user/image-studio', 'output_quality', 'Output quality', 'Global encode quality 30-100 for lossy formats. Always present (PNG ignores it).', 'number', true, 3, 345, true, 'studio_settings'),
('matrx-user/image-studio', 'background_color', 'Background color', 'Hex fill color used when flattening transparency into JPEG/AVIF output. Always present.', 'string', true, 7, 350, true, 'studio_settings'),
('matrx-user/image-studio', 'resize_fit', 'Resize fit', 'How images fill each preset frame: "cover" (crop) or "contain" (letterbox). Always present.', 'string', true, 7, 355, true, 'studio_settings'),
('matrx-user/image-studio', 'resize_position', 'Crop anchor', 'Crop anchor used with cover fit: a named anchor (e.g. "center", "top") or a precise focal point serialized as "focal x%,y%". Always present.', 'string', true, 6, 360, true, 'studio_settings'),
('matrx-user/image-studio', 'studio_settings_summary', 'Settings summary', 'Composite object of everything shaping the next Generate: `{ selected_preset_ids, output_format, output_quality, background_color, resize_fit, resize_position }`. Always present.', 'object', true, 300, 365, true, 'studio_settings'),
('matrx-user/image-studio', 'total_variant_count', 'Planned variant count', 'Files × selected presets — how many variants the next Generate will produce. Always present; zero when files or presets are missing.', 'number', true, 4, 370, true, 'studio_output'),
('matrx-user/image-studio', 'generated_variant_count', 'Generated variant count', 'Number of variants already produced in this session across all files. Always present; zero before the first Generate.', 'number', true, 4, 375, true, 'studio_output'),
('matrx-user/image-studio', 'total_output_bytes', 'Total output bytes', 'Combined byte size of every generated variant. Always present; zero before the first Generate.', 'number', true, 9, 380, true, 'studio_output'),
('matrx-user/image-studio', 'last_save_result', 'Last save result', 'Result of the most recent Save to library: `{ folder_path, saved_count, failed_filenames }`. Absent until the user saves in this session.', 'object', false, 150, 385, true, 'studio_output'),
('matrx-user/image-studio', 'studio_error', 'Studio error', 'Human-readable message from the last failed Generate or Save. Absent when the last operation succeeded.', 'string', false, 80, 390, true, 'studio_output'),
('matrx-user/image-studio', 'is_processing', 'Generating variants', 'True while the server is producing variants for the dropped files. Always present.', 'boolean', true, 5, 400, true, 'studio_activity'),
('matrx-user/image-studio', 'is_saving', 'Saving to library', 'True while generated variants are being uploaded to the user''s cloud library. Always present.', 'boolean', true, 5, 405, true, 'studio_activity'),
('matrx-user/image-studio', 'is_describing', 'AI describe running', 'True while the AI Describe agent is generating metadata for one or more files. Always present.', 'boolean', true, 5, 410, true, 'studio_activity'),
('matrx-user/image-studio', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/image-studio', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/image-studio', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/image-studio', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/image-studio', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/image-generate', 'prompt', 'Image prompt', 'The text prompt describing the image to generate. Always present; empty string when the user has not typed yet.', 'string', true, 150, 300, true, 'generation_request'),
('matrx-user/image-generate', 'style', 'Style hint', 'Optional free-text style modifier (e.g. "editorial illustration"). Absent when the user left it blank.', 'string', false, 30, 305, true, 'generation_request'),
('matrx-user/image-generate', 'image_size', 'Image size', 'Aspect selection for generated images: "square", "portrait", "landscape", "wide", or "tall". Always present.', 'string', true, 9, 310, true, 'generation_request'),
('matrx-user/image-generate', 'image_count', 'Image count', 'How many images the next Generate produces (1-4). Always present.', 'number', true, 1, 315, true, 'generation_request'),
('matrx-user/image-generate', 'generation_request_summary', 'Request summary', 'Composite object of the full request: `{ prompt, style, image_size, image_count }`. Always present.', 'object', true, 220, 320, true, 'generation_request'),
('matrx-user/image-generate', 'result_count', 'Result count', 'Number of images produced by the last Generate in this session. Always present; zero before the first run.', 'number', true, 1, 330, true, 'generation_results'),
('matrx-user/image-generate', 'result_file_ids', 'Result file IDs', 'Array of `cld_files` UUIDs for the generated images, in display order. THE durable references — resolve bytes from these. Empty array before the first run.', 'array', true, 160, 335, true, 'generation_results'),
('matrx-user/image-generate', 'is_generating', 'Generation running', 'True while a Generate request is in flight. Always present.', 'boolean', true, 5, 360, true, 'generation_status'),
('matrx-user/image-generate', 'generation_enabled', 'Generation enabled', 'True when the Python generate endpoint is live for this build (backend capability flag). False renders the coming-soon state. Always present.', 'boolean', true, 5, 365, true, 'generation_status'),
('matrx-user/image-generate', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/image-generate', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/image-generate', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/image-generate', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/image-generate', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/image-edit', 'image_file_id', 'Image file id', 'cld_files UUID of the image being edited. Absent for url-sourced edits (e.g. an unsaved generation result) until the first save.', 'string', false, 36, 300, true, 'edit_image'),
('matrx-user/image-edit', 'image_file_name', 'Image file name', 'Display name of the image on the canvas — the live cloud-files name when the file id is known, otherwise the source-derived filename. Always present.', 'string', true, 40, 305, true, 'edit_image'),
('matrx-user/image-edit', 'source_dimensions', 'Source dimensions', 'Natural pixel size of the loaded image as `{ width, height }`. Absent until the image finishes decoding.', 'object', false, 30, 310, true, 'edit_image'),
('matrx-user/image-edit', 'presentation', 'Presentation', 'How the editor is mounted: "page" (the /images/edit/[id] route) or "modal" (opened from another surface). Always present.', 'string', true, 5, 330, true, 'edit_session'),
('matrx-user/image-edit', 'save_folder', 'Save folder', 'Cloud-library folder path where saves land (e.g. `Images/Edited`). Always present.', 'string', true, 20, 335, true, 'edit_session'),
('matrx-user/image-edit', 'edit_chain_file_id', 'AI-op chain file id', 'cld_files UUID of the latest AI-op result when edits are chaining against results instead of the untouched source (preserve-source mode). Absent otherwise.', 'string', false, 36, 340, true, 'edit_session'),
('matrx-user/image-edit', 'mask_active', 'Mask painting on', 'True while the mask-painting overlay is visible, constraining AI ops to a painted region. Always present.', 'boolean', true, 5, 345, true, 'edit_session'),
('matrx-user/image-edit', 'mask_has_pixels', 'Mask has pixels', 'True when the user has painted at least one mask stroke — AI ops will be region-constrained. Always present.', 'boolean', true, 5, 350, true, 'edit_session'),
('matrx-user/image-edit', 'is_saving', 'Saving', 'True while a save (version or new file) is in flight. Always present.', 'boolean', true, 5, 370, true, 'edit_activity'),
('matrx-user/image-edit', 'saving_variant_preset', 'Generating size variants', 'The asset preset (e.g. "social", "avatar") currently generating platform-size variants of this image. Absent when no variant job is running.', 'string', false, 10, 375, true, 'edit_activity'),
('matrx-user/image-edit', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/image-edit', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/image-edit', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/image-edit', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/image-edit', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/image-annotate', 'image_file_id', 'Image file id', 'cld_files UUID of the source screenshot. Absent for url-sourced images until the annotated copy is saved.', 'string', false, 36, 300, true, 'annotate_image'),
('matrx-user/image-annotate', 'image_file_name', 'Image file name', 'Filename of the screenshot being annotated, derived from its source. Always present.', 'string', true, 40, 305, true, 'annotate_image'),
('matrx-user/image-annotate', 'presentation', 'Presentation', 'How the annotator is mounted: "page" (the /images/annotate route) or "modal" (opened from another surface). Always present.', 'string', true, 5, 330, true, 'annotate_session'),
('matrx-user/image-annotate', 'save_folder', 'Save folder', 'Cloud-library folder path where the baked annotated PNG lands (e.g. `Images/Annotated`). Always present.', 'string', true, 20, 335, true, 'annotate_session'),
('matrx-user/image-annotate', 'is_saving', 'Saving', 'True while the flattened annotated image is being saved to the cloud library. Always present.', 'boolean', true, 5, 340, true, 'annotate_session'),
('matrx-user/image-annotate', 'ai_assist_running', 'AI assist running', 'The AI assist currently working on this screenshot: "redact" (PII redaction) or "faces" (face detection/blur). Absent when no assist is in flight.', 'string', false, 6, 345, true, 'annotate_session'),
('matrx-user/image-annotate', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-user/image-annotate', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-user/image-annotate', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-user/image-annotate', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-user/image-annotate', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'Images Library', value_groups = '[{"key":"library_query","label":"Library query and view","sortOrder":100,"description":"Search text, the recents filter, and the view density shaping the visible tiles."},{"key":"visible_images","label":"Visible images","sortOrder":200,"description":"The image rows the user can actually see after search and filters. Durable refs only."},{"key":"image_selection","label":"Selection","sortOrder":300,"description":"The bulk checkbox selection and the picker-mode selection state."},{"key":"library_status","label":"Library status","sortOrder":400,"description":"Load state of the underlying cloud-files tree and in-flight bulk work."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Completeness audit done against CloudImagesTab; registered, route-mapped, and DB-synced. Remaining gaps: no `data-surface-value` anchors on tiles, and no live non-matching-name binding test.', url_pattern = '/images/my-cloud', intro = '<surface_intro>
The user is in the Matrx image library — the image-only view of their cloud
files. A search box, a Recents (last 30 days) toggle, and a density switch
(cozy / compact / list) shape a grid of image tiles. Clicking a tile opens the
image viewer; checkboxes build a bulk selection that can be downloaded, moved to
another folder, re-scoped (personal / internal / public), or deleted. The same
component also runs as an image PICKER inside other flows — selection_mode tells
you which.

Read the values in three layers:
  1. WHAT shapes the view — library_query_summary (search_query, recents_only,
     view_mode).
  2. WHAT the user can see — visible_image_count / total_image_count and
     visible_images / visible_image_ids.
  3. WHAT they are pointed at — selected_image_ids / selected_images. A batch
     action always means the selection.

IMAGE REFERENCES ARE DURABLE, NEVER URLS. Identify every image by its UUID
(visible_image_ids, selected_image_ids). Bytes are fetched through the platform
file handler from that id. This surface never emits a signed/expiring URL or a
storage location; a public_url appears only for images with a verified permanent
CDN URL. If you need image content, ask for it by id.

There is no text editor here, so the text baselines are populated only when the
user highlighted something on the page.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/images';
UPDATE ui.ui_surface SET label = 'Image Studio', value_groups = '[{"key":"studio_sources","label":"Source images","sortOrder":100,"description":"The images the user has dropped into the studio, still browser-local until saved."},{"key":"studio_settings","label":"Conversion settings","sortOrder":200,"description":"Selected presets and the global format / quality / background / crop overrides."},{"key":"studio_output","label":"Generated output","sortOrder":300,"description":"Variant counts, output size, and the last save-to-library result."},{"key":"studio_activity","label":"Activity","sortOrder":400,"description":"In-flight processing, saving, and AI-describe work."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + ImageStudioShell emitter + describe-shortcut surfaceName wired. Remaining: no `data-surface-value` anchors, EmbeddedImageStudio mounts no provider, and no live non-matching-name binding test.', url_pattern = '/images/convert', intro = '<surface_intro>
The user is in the Image Studio batch converter. They drop one or more images
(browser-local files — not yet in their cloud library), select size presets or
curated bundles, tune the global format / quality / background / crop settings,
click Generate to produce every variant server-side, and finally save the
variants to their cloud library. An AI Describe action generates filenames,
alt text, and captions per image.

Read the values in three layers:
  1. WHAT the user brought — source_file_count / source_files (identified by
     name and slug; no cloud file ids exist until save).
  2. HOW it will be converted — studio_settings_summary and its constituent
     fields.
  3. WHAT came out — total/generated variant counts, total_output_bytes, and
     last_save_result (the durable folder + saved count after a save).

Source files are NOT durable cloud records while on this surface. Only after
"Save to library" do variants get cld_files rows; last_save_result tells you
where they landed. Never invent file ids for unsaved studio files.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/image-studio';
UPDATE ui.ui_surface SET label = 'Image Generate', value_groups = '[{"key":"generation_request","label":"Generation request","sortOrder":100,"description":"The prompt, style, size, and count shaping the next Generate."},{"key":"generation_results","label":"Generated results","sortOrder":200,"description":"The persisted image files produced by the last Generate."},{"key":"generation_status","label":"Status","sortOrder":300,"description":"In-flight state and backend capability."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + GenerateShellClient emitter wired. Remaining: /images/ai-generate hero mounts no provider (placeholder page), no `data-surface-value` anchors, no live non-matching-name binding test.', url_pattern = '/images/generate', intro = '<surface_intro>
The user is generating images from text. A prompt box, an optional style hint,
an aspect-size selector, and a count (1-4) feed the platform''s image
generation endpoint; results appear as tiles the user can take into Edit,
Annotate, or Avatar mode. Every result is already saved to their cloud
library.

Read generation_request_summary for what the user is asking for — helping
sharpen a prompt is the most valuable thing an agent can do here, especially
when prompt is empty or vague. result_file_ids are durable cloud file UUIDs;
resolve image bytes from those ids, never from URLs. generation_enabled false
means the backend endpoint has not shipped for this build — the user can
still draft prompts.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/image-generate';
UPDATE ui.ui_surface SET label = 'Image Editor', value_groups = '[{"key":"edit_image","label":"Image being edited","sortOrder":100,"description":"Identity and dimensions of the image on the editor canvas."},{"key":"edit_session","label":"Edit session","sortOrder":200,"description":"Presentation, save destination, AI-op chaining, and mask state for this session."},{"key":"edit_activity","label":"Activity","sortOrder":300,"description":"In-flight save and variant-generation work."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + EditModeShell emitter (covers page AND modal mounts). Remaining: /images/edit landing picker mounts no provider, no `data-surface-value` anchors, no live non-matching-name binding test.', url_pattern = '/images/edit/[id]', intro = '<surface_intro>
The user has one image open on the editor canvas: crop/rotate/filter tools,
AI operations (remove background, upscale, AI edit — optionally constrained
to a painted mask region), platform-size variant generation, and a versions
rail. Saves either version the source file or create a new file in
save_folder.

image_file_id is the durable cloud-file UUID when it exists; url-sourced
edits (an unsaved generation result) have none until the first save — never
invent one. mask_has_pixels true means the user has scoped AI work to a
specific region; respect that intent when suggesting operations. presentation
"modal" means the editor is open on top of another surface, invoked from it.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/image-edit';
UPDATE ui.ui_surface SET label = 'Image Annotate', value_groups = '[{"key":"annotate_image","label":"Image being annotated","sortOrder":100,"description":"Identity of the screenshot on the markup canvas."},{"key":"annotate_session","label":"Annotation session","sortOrder":200,"description":"Presentation, save destination, and in-flight AI assists."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + AnnotateModeShell emitter (covers page AND modal mounts). Remaining: the pre-source picker state mounts no provider, no `data-surface-value` anchors, no live non-matching-name binding test.', url_pattern = '/images/annotate', intro = '<surface_intro>
The user is marking up a screenshot: arrows, callout text, boxes, and
freehand strokes drawn over the image, then baked into a flat PNG on save.
The original image is never modified — the annotated copy lands in
save_folder. AI assists (PII redaction, face detection/blur) can pre-place
annotations.

image_file_id is the durable cloud-file UUID of the source when it exists;
url-sourced screenshots have none until the annotated copy is saved — never
invent one. presentation "modal" means the annotator is open on top of
another surface, invoked from it.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/image-annotate';
