-- Guard: manifest surfaces missing a ui_surface row
SELECT s.name FROM (VALUES ('matrx-public/p'), ('matrx-admin/server-logs'), ('matrx-admin/scheduling'), ('matrx-admin/growth-loop'), ('matrx-admin/reporting'), ('matrx-admin/utilities'), ('matrx-admin/documentation'), ('matrx-user/quick-data')) AS s(name) LEFT JOIN ui.ui_surface u ON u.name = s.name WHERE u.name IS NULL;

-- Upsert all manifest values
INSERT INTO ui.ui_surface_value (surface_name, name, label, description, value_type, always_available, typical_char_count, sort_order, auto_context, group_key) VALUES
('matrx-public/p', 'app_id', 'App ID', 'UUID of the published `app.definition` row being run (`app.id`). Always available — the page 404s before rendering if the slug/id does not resolve to a published, public app.', 'string', true, 36, 100, true, 'app_identity'),
('matrx-public/p', 'app_slug', 'App slug', 'The app''s public URL slug (`app.slug`), as used in `/p/[slug]`. Always available.', 'string', true, 40, 110, true, 'app_identity'),
('matrx-public/p', 'app_name', 'App name', 'Display name of the app (`app.name`). Always available.', 'string', true, 60, 120, true, 'app_identity'),
('matrx-public/p', 'agent_id', 'Bound agent ID', 'UUID of the `agent.definition` the app is bound to (`app.agent_id`) — the agent `launchAgentExecution` runs on submit. Always available.', 'string', true, 36, 130, false, 'app_identity'),
('matrx-public/p', 'agent_version_id', 'Pinned agent version ID', 'UUID of the pinned `agx_version` row when the app is NOT configured to use_latest (`app.agent_version_id`). Empty when the app tracks the agent''s latest published version.', 'string', false, 36, 140, false, 'app_identity'),
('matrx-public/p', 'shell_kind', 'Shell kind', 'Which top-level UI shell renders the app (`app.shell_kind`) — e.g. "chat", "form_to_result", "widget", "fully_custom". Always available. `?embed=widget` forces "widget" regardless of the row''s configured kind.', 'string', true, 16, 150, false, 'app_identity'),
('matrx-public/p', 'is_authenticated', 'Visitor is signed in', 'True when the visitor has a real Supabase session; false for an anonymous guest identified only by fingerprint. Always available.', 'boolean', true, 5, 200, true, 'visitor'),
('matrx-public/p', 'guest_fingerprint_id', 'Guest fingerprint ID', 'Browser fingerprint identifying an anonymous visitor across runs (`X-Fingerprint-ID`), used in place of a user id for guest rate limiting. Empty once the visitor is authenticated or before the fingerprint has resolved.', 'string', false, 40, 210, false, 'visitor'),
('matrx-public/p', 'guest_runs_remaining', 'Guest runs remaining', 'Free executions left for this anonymous guest before signup is required (from `useGuestLimit`). Meaningless once `is_authenticated` is true.', 'number', false, 2, 220, false, 'visitor'),
('matrx-public/p', 'user_input', 'User message', 'Free-text message the visitor typed for this run, passed as `runtime.userInput` to the agent. Empty for apps whose custom UI collects only form variables and no chat-style message.', 'string', false, 300, 300, true, 'run_input'),
('matrx-public/p', 'form_variable_values', 'Form variable values', 'The visitor''s submitted form values, validated and coerced against `app.variable_schema` (string/number/boolean per field, required fields defaulted or flagged). Object keyed by variable name. Empty object for apps with no declared variables.', 'object', false, 400, 310, true, 'run_input'),
('matrx-public/p', 'conversation_id', 'Conversation ID', 'UUID of the `cx_conversation` row created for this run, captured synchronously via `onConversationCreated` right after the launcher creates it. Empty until the visitor''s first submit of this page view.', 'string', false, 36, 400, true, 'run_state'),
('matrx-public/p', 'run_status', 'Run status', 'Status of the active/most-recent execution''s request: "streaming", "complete", "error", or empty before any run has started this page view.', 'string', false, 12, 410, false, 'run_state'),
('matrx-public/p', 'response_text', 'Response text', 'Accumulated streamed text of the current/most recent run, read live from Redux (`selectAccumulatedText`). Empty before the first run completes any output.', 'string', false, 2000, 420, false, 'run_state'),
('matrx-public/p', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-public/p', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-public/p', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-public/p', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-public/p', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/server-logs', 'selected_app', 'Selected app', 'App key of the service whose logs are shown, e.g. "ai-dream-server", "scraper-service-dev". Always present — comes from the [app] route segment.', 'string', true, 24, 100, true, 'app_selection'),
('matrx-admin/server-logs', 'selected_app_environment', 'Selected app environment', '"production" or "development" for the selected app, taken from the static app registry. Always present.', 'string', true, 12, 105, true, 'app_selection'),
('matrx-admin/server-logs', 'available_apps', 'Available apps', 'The static catalogue of services the viewer can switch to, each with { key, label, env }. Always present — does not depend on a fetch.', 'array', true, 400, 110, false, 'app_selection'),
('matrx-admin/server-logs', 'requested_line_count', 'Requested line count', 'Number of trailing log lines requested from Coolify for the current fetch (one of a fixed set: 50-10000). Always present.', 'number', true, 5, 200, true, 'fetch_state'),
('matrx-admin/server-logs', 'poll_interval_ms', 'Auto-refresh interval (ms)', 'How often the viewer re-fetches logs automatically; 0 means manual refresh only. Always present.', 'number', true, 6, 210, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_fetched_at', 'Logs fetched at', 'ISO timestamp of the last successful log fetch. Absent before the first fetch completes.', 'string', false, 25, 220, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_loading', 'Logs loading', 'True while a log fetch is in flight. Always present.', 'boolean', true, 5, 230, true, 'fetch_state'),
('matrx-admin/server-logs', 'logs_fetch_error', 'Fetch error', 'Error message from the last failed log fetch. Absent when the last fetch succeeded or none has run yet.', 'string', false, 150, 240, true, 'fetch_state'),
('matrx-admin/server-logs', 'log_filters', 'Active log filters', 'The parsed-log filter state applied to the fetched text: { levels, categories, urgencies, search, modules, modules_cleared, endpoints, endpoints_cleared, show_json_payloads }. levels/categories/urgencies are the SELECTED subsets of the log-rules enums — a full array means nothing is narrowed. modules/endpoints are allowlists: empty with the matching *_cleared false means "no narrowing", empty with it true means "show nothing". Always present — the viewer always has a filter object, even at defaults.', 'object', true, 400, 300, true, 'filters'),
('matrx-admin/server-logs', 'log_noise_excludes', 'Noise exclusion presets', 'Which built-in noise presets are toggled on (cloudFiles, healthChecks, admin, replaySweep, wakeListener, autoIngestListener) — persisted in localStorage across sessions. Always present.', 'object', true, 150, 310, false, 'filters'),
('matrx-admin/server-logs', 'view_mode', 'View mode', 'Layout mode of the log panel — "log-only" or a split/inspector mode alongside the JSON payload viewer. Always present.', 'string', true, 14, 320, true, 'filters'),
('matrx-admin/server-logs', 'log_view_range', 'Line range window', 'The Range panel''s window over the fetched lines, applied BEFORE the filters: { start_offset, display_count }. display_count is null when the window runs to the end. Always present — { start_offset: 0, display_count: null } means the whole fetched buffer is in play.', 'object', true, 50, 330, false, 'filters'),
('matrx-admin/server-logs', 'fetched_log_line_count', 'Fetched log line count', 'Total number of lines returned by the last fetch, before the range window and filters narrow them. Always present — 0 before the first fetch. This is the denominator in the toolbar''s "visible/fetched lines" readout.', 'number', true, 5, 395, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_line_count', 'Visible log line count', 'Number of parsed log lines currently visible after the range window and filters are applied. Always present — 0 when nothing matches or no logs are loaded. This is the numerator in the toolbar''s "visible/fetched lines" readout.', 'number', true, 5, 400, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_level_counts', 'Visible level counts', 'How many of the currently visible lines carry each log level, as { DEBUG, INFO, WARNING, ERROR, CRITICAL, UNKNOWN }. Every key is present, with 0 where no line matched. Always present — all zeros before the first fetch. Use this to answer "is anything erroring" without reading the log text.', 'object', true, 110, 405, true, 'log_view'),
('matrx-admin/server-logs', 'visible_log_lines', 'Visible log lines', 'Raw text of the log lines on screen right now — the lines left after the range window and filters, blank lines dropped, oldest first. TRUNCATED to a bounded TAIL (the newest lines) when the visible set is large; when that happens the text starts with a `[truncated: showing the last N of M …]` banner, so trust that banner over your own count. Absent when no lines are visible. NOTE: when `view_mode` is "raw" the panel shows unparsed text instead and `raw_logs` is what the admin is reading — this value still describes the parsed view behind it.', 'string', false, 18000, 408, true, 'log_view'),
('matrx-admin/server-logs', 'raw_logs', 'Raw log text', 'The unparsed log text returned by the last fetch for the selected app — what the "raw" view mode shows, with no range window, filters or parsing applied. TRUNCATED to a bounded tail like `visible_log_lines`, with the same banner. Bindable only — prefer `visible_log_lines` or a selected line for targeted questions. Absent before the first fetch.', 'string', false, 20000, 410, false, 'log_view'),
('matrx-admin/server-logs', 'selected_log_line', 'Selected log line', 'The single parsed log line the admin has clicked to inspect: { raw, timestamp, level, module, category, urgency }. Absent when nothing is selected.', 'object', false, 500, 420, true, 'log_view'),
('matrx-admin/server-logs', 'selected_line_range', 'Selected line range', 'The multi-line range the admin has marked with click / shift-click, as { anchor_line, tail_line, selected_count } using 1-based on-screen line numbers. tail_line is null when only the anchor is set. Absent when nothing is marked; the marked text itself arrives as the baseline `selection` value.', 'object', false, 60, 425, true, 'log_view'),
('matrx-admin/server-logs', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/server-logs', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/server-logs', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/server-logs', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/server-logs', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/scheduling', 'active_tab', 'Active tab', 'Which tab of the Scheduling admin console is showing: "overview", "tasks", "runs", "orphan_leases", "cron_tester", "scanner_health", or "templates". Derived from the pathname under /administration/automation/scheduling. Always present.', 'string', true, 15, 100, true, 'hub'),
('matrx-admin/scheduling', 'task_total_count', 'Total task count', 'Total number of scheduled tasks VISIBLE TO THE VIEWER (health summary; not a platform-wide figure — see D140). Absent outside the Overview tab and until the summary resolves.', 'number', false, 4, 200, true, 'overview'),
('matrx-admin/scheduling', 'task_enabled_count', 'Enabled task count', 'Number of the viewer''s scheduled tasks currently enabled (health summary). Absent outside the Overview tab and until the summary resolves.', 'number', false, 4, 210, true, 'overview'),
('matrx-admin/scheduling', 'task_due_next_hour_count', 'Tasks due next hour', 'Number of the viewer''s tasks whose next fire falls within the next hour (health summary). Absent outside the Overview tab and until the summary resolves.', 'number', false, 3, 220, true, 'overview'),
('matrx-admin/scheduling', 'runs_last_24h_count', 'Runs in last 24h', 'Runs recorded in the last 24 hours across the viewer''s tasks (health summary). Absent outside the Overview tab and until the summary resolves.', 'number', false, 4, 230, true, 'overview'),
('matrx-admin/scheduling', 'failures_last_24h_count', 'Failures in last 24h', 'Runs that failed in the last 24 hours (health summary) — the loud number the Overview stat tile warns on when non-zero. Absent outside the Overview tab.', 'number', false, 3, 240, true, 'overview'),
('matrx-admin/scheduling', 'orphan_lease_summary_count', 'Orphan lease count (summary)', 'Current count of orphaned leases from the health summary tile — the same figure the Orphan leases tab lists in full. Absent outside the Overview tab.', 'number', false, 3, 250, true, 'overview'),
('matrx-admin/scheduling', 'overview_load_error', 'Overview load error', 'Error message shown in the Overview tab''s destructive alert when the health summary query failed. Absent when the summary loaded fine, and outside the Overview tab.', 'string', false, 90, 260, true, 'overview'),
('matrx-admin/scheduling', 'task_row_count', 'Task row count', 'Number of scheduled tasks the Tasks tab fetched from the server (capped at 200 by the query). This is the RAW fetched count — the table''s own search box and column filters narrow what is on screen without changing it, and the page cannot read those. Absent outside the Tasks tab.', 'number', false, 3, 320, true, 'tasks'),
('matrx-admin/scheduling', 'run_status_filter', 'Run status filter', 'The Runs tab''s SERVER-side status filter: "any", or one of the RunStatus values (queued/claimed/running/success/failed/cancelled/skipped). Reported as "any" when the picker is on "Any status". Absent outside the Runs tab.', 'string', false, 9, 400, true, 'runs'),
('matrx-admin/scheduling', 'run_surface_filter', 'Run surface filter', 'The Runs tab''s SERVER-side originating-surface filter: "any", or one of the Surface enum values. Reported as "any" when the picker is on "Any surface". Absent outside the Runs tab.', 'string', false, 20, 410, true, 'runs'),
('matrx-admin/scheduling', 'run_row_count', 'Run row count', 'Number of runs the Runs tab fetched for the current status/surface filters (capped at 200 by the query). The table''s own search box narrows what is on screen without changing this. Absent outside the Runs tab.', 'number', false, 3, 420, true, 'runs'),
('matrx-admin/scheduling', 'orphan_lease_row_count', 'Orphan lease row count', 'Number of runs currently shown in the Orphan leases tab — claimed/running runs whose claim_expires_at is in the past. Absent outside the Orphan leases tab.', 'number', false, 3, 500, true, 'orphan_leases'),
('matrx-admin/scheduling', 'cron_expression', 'Cron expression', 'The 5-field cron expression currently in the Cron tester''s input (defaults to "0 9 * * 1-5"). Absent outside the Cron tester tab.', 'string', false, 20, 600, true, 'cron_tester'),
('matrx-admin/scheduling', 'cron_timezone', 'Cron timezone', 'IANA timezone selected in the Cron tester (defaults to the browser''s resolved timezone). Absent outside the Cron tester tab.', 'string', false, 20, 610, true, 'cron_tester'),
('matrx-admin/scheduling', 'cron_validation_error', 'Cron validation error', 'Validation error message for the current expression/timezone pair, if invalid. Absent when the expression is valid, and outside the Cron tester tab.', 'string', false, 80, 620, true, 'cron_tester'),
('matrx-admin/scheduling', 'cron_expression_human', 'Cron expression in words', 'The plain-English reading of the current expression that the tester renders under the input (cronstrue, e.g. "At 09:00 AM, Monday through Friday"). Absent when the expression is invalid or cannot be humanized, and outside the Cron tester tab.', 'string', false, 60, 625, true, 'cron_tester'),
('matrx-admin/scheduling', 'cron_next_fires', 'Cron next fires', 'ISO timestamps of the next N fires for the current valid expression (N is admin-configurable, up to 50). Empty array when the expression is invalid. Absent outside the Cron tester tab.', 'array', false, 400, 630, false, 'cron_tester'),
('matrx-admin/scheduling', 'scanner_running', 'Scanner running', 'Whether aidream''s matrx-scheduler scanner process is currently running, per its last polled status. Absent outside the Scanner health tab, or before the first poll resolves.', 'boolean', false, 5, 700, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_last_tick_at', 'Scanner last tick at', 'ISO timestamp of the scanner''s last completed tick. Absent outside the Scanner health tab, or before the first poll resolves.', 'string', false, 24, 710, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_started_at', 'Scanner started at', 'ISO timestamp the scanner process started, as shown beside the running/stopped badge. Absent outside the Scanner health tab, before the first poll resolves, or when the scanner is not running.', 'string', false, 24, 715, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_consecutive_errors', 'Scanner consecutive errors', 'Count of consecutive scanner tick errors, per the last polled status — the destructive badge fires when this is non-zero. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 3, 720, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_in_flight_count', 'Scanner in-flight count', 'Number of runs the scanner currently has claimed and in flight, per the last polled status. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 3, 730, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_last_tick_duration_ms', 'Scanner last tick duration', 'How long the scanner''s last tick took, in milliseconds. Absent outside the Scanner health tab, before the first poll resolves, or when the scanner reports no duration yet.', 'number', false, 4, 740, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_last_tick_claimed', 'Scanner claimed (last tick)', 'How many due runs the scanner claimed on its last tick. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 3, 750, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_last_tick_manual_claimed', 'Scanner manual claimed (last tick)', 'How many manually-triggered runs the scanner claimed on its last tick. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 3, 760, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_last_tick_expired_sweeps', 'Scanner expired sweeps (last tick)', 'How many expired claims the scanner swept on its last tick — the stat tile warns when this is non-zero. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 3, 770, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_total_runs_dispatched', 'Scanner total dispatched', 'Lifetime count of runs the scanner has dispatched since the process started. Absent outside the Scanner health tab, or before the first poll resolves.', 'number', false, 6, 780, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_error_message', 'Scanner recent error', 'The scanner''s own most recent error message, rendered in the "Recent error" alert. Absent when the scanner reports no error, outside the Scanner health tab, or before the first poll resolves.', 'string', false, 120, 790, true, 'scanner_health'),
('matrx-admin/scheduling', 'scanner_unreachable_error', 'Scanner unreachable error', 'Why the status poll itself failed — the message in the "Scanner unreachable" alert (backend down, or AIDREAM_SCHEDULER not enabled). Distinct from scanner_error_message, which is an error the scanner itself reported. Absent when the poll succeeded, and outside the Scanner health tab.', 'string', false, 120, 800, true, 'scanner_health'),
('matrx-admin/scheduling', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/scheduling', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/scheduling', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/scheduling', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/scheduling', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/growth-loop', 'loop_score', 'Loop score', 'Counts of connections by pipe health across the whole map: { live, partial, missing, total }. Always populated (derived from the static loop map, not user state).', 'object', true, 40, 100, true, 'loop_overview'),
('matrx-admin/growth-loop', 'open_gap_count', 'Open gap count', 'Number of gaps with status other than ''closed'' across the whole map. Always populated; zero when every gap is closed.', 'number', true, 3, 110, true, 'loop_overview'),
('matrx-admin/growth-loop', 'blocker_count', 'Blocker count', 'Number of open gaps with severity ''blocker''. Always populated; zero when none are open.', 'number', true, 3, 120, true, 'loop_overview'),
('matrx-admin/growth-loop', 'blockers_summary', 'Blockers', 'Every open blocker-severity gap: { id, title, lane, at }. Always populated — empty array when there are none. This is exactly the list shown in the canvas sidebar when nothing is selected.', 'array', true, 600, 130, true, 'loop_overview'),
('matrx-admin/growth-loop', 'stages_summary', 'Stages', 'Every pipeline stage in loop order: { id, label, maturity, open_gap_count }. Always populated (12 entries) — the full node list the canvas renders.', 'array', true, 700, 140, true, 'loop_overview'),
('matrx-admin/growth-loop', 'edges_summary', 'Connections', 'Every connection between stages: { id, from, to, label, health }, where `health` is the worst pipe state on that edge (live/partial/missing/n-a). Always populated — the full edge list the canvas renders.', 'array', true, 900, 150, true, 'loop_overview'),
('matrx-admin/growth-loop', 'selection_kind', 'Selection kind', '"stage" when a stage node is selected, "edge" when a connection arrow is selected, "none" when the user clicked the empty pane and nothing is selected. Always populated — tells you which of the selected_* values below apply.', 'string', true, 5, 200, true, 'selection'),
('matrx-admin/growth-loop', 'selected_stage_id', 'Selected stage ID', 'Machine id of the selected stage (e.g. "research", "analyze"). Empty unless selection_kind is "stage".', 'string', false, 12, 210, true, 'selection'),
('matrx-admin/growth-loop', 'selected_stage_detail', 'Selected stage detail', 'Full detail of the selected stage: { id, label, blurb, maturity, repos, stores, pipes: { code, human, ai } }, each pipe carrying { state, note, ref }. Empty unless selection_kind is "stage" — this is exactly what the sidebar renders.', 'object', false, 700, 220, true, 'selection'),
('matrx-admin/growth-loop', 'selected_edge_id', 'Selected connection ID', 'Id of the selected connection (e.g. "research->plan"). Empty unless selection_kind is "edge".', 'string', false, 24, 230, true, 'selection'),
('matrx-admin/growth-loop', 'selected_edge_detail', 'Selected connection detail', 'Full detail of the selected connection: { id, from, to, label, pipes: { code, human, ai } }, each pipe carrying { state, note, ref }. Empty unless selection_kind is "edge".', 'object', false, 500, 240, true, 'selection'),
('matrx-admin/growth-loop', 'selection_gaps', 'Gaps at selection', 'Gaps that live on the selected stage or edge: { id, title, severity, status, detail, lane }. Empty when nothing is selected or the selection has no gaps.', 'array', false, 500, 250, true, 'selection'),
('matrx-admin/reporting', 'reporting_section', 'Reporting section', 'Which child of the Reporting admin family is active: "hub", "events", "reports", "dead_ends", "unwired", or "lint_debt". Always present — each emitter declares which one it is.', 'string', true, 12, 100, true, 'navigation'),
('matrx-admin/reporting', 'events_action_prefix', 'Events action-prefix filter', 'The toolbar facet narrowing admin_recent_activity server-side: "all", "run.", "webhook.", or "file.". Present only on reporting_section=events.', 'string', false, 10, 200, true, 'events'),
('matrx-admin/reporting', 'events_auto_refresh', 'Events auto-refresh', 'Whether the 5-second auto-refresh poll is on. Present only on reporting_section=events.', 'boolean', false, 5, 205, true, 'events'),
('matrx-admin/reporting', 'events_rows', 'Events rows', 'The fetched platform.activity_log rows matching events_action_prefix (id, occurred_at, action, entity_type, entity_id, actor_id, organization_id, metadata), up to 200. Present only on reporting_section=events; empty array when none match.', 'array', false, 8000, 210, false, 'events'),
('matrx-admin/reporting', 'reports_catalog', 'Reports catalog', 'The admin-mode report registry entries actually shown (only entries with an adminHref): { id, label, href }. Present only on reporting_section=reports.', 'array', false, 1500, 300, false, 'reports_catalog'),
('matrx-admin/reporting', 'dead_ends_totals', 'Dead ends scan totals', 'The committed scan''s header numbers: { generatedAt, commit, findings, high, medium, low, filesWithFindings, filesScanned, allowlisted }. Present only on reporting_section=dead_ends.', 'object', false, 220, 400, true, 'dead_ends'),
('matrx-admin/reporting', 'dead_ends_bucket_filter', 'Dead ends active filter', 'The console''s current drill-down: { kind: "none"|"file"|"feature"|"rule"|"severity", value? }. "none" means the unfiltered findings table is shown. Present only on reporting_section=dead_ends.', 'object', false, 60, 405, true, 'dead_ends'),
('matrx-admin/reporting', 'dead_ends_worst_features', 'Dead ends worst features', 'Top offending features/route-groups ranked by finding count: { key, count, high }. Present only on reporting_section=dead_ends.', 'array', false, 1200, 410, false, 'dead_ends'),
('matrx-admin/reporting', 'dead_ends_worst_files', 'Dead ends worst files', 'Top offending files ranked by finding count: { key, count, high }. Present only on reporting_section=dead_ends.', 'array', false, 1200, 415, false, 'dead_ends'),
('matrx-admin/reporting', 'dead_ends_problems', 'Dead ends staleness warnings', 'Warnings from reconcileReport() about the committed snapshot (e.g. stale vs HEAD, allowlist rot). Empty array when the snapshot is healthy. Present only on reporting_section=dead_ends.', 'array', false, 200, 420, false, 'dead_ends'),
('matrx-admin/reporting', 'unwired_totals', 'Unwired scan totals', 'The committed scan''s header numbers: { generatedAt, commit, aidreamCommit, findings, lines, filesWithFindings, filesScanned, suppressed, byDetector, byRepository }. Present only on reporting_section=unwired.', 'object', false, 300, 500, true, 'unwired'),
('matrx-admin/reporting', 'unwired_bucket_filter', 'Unwired active filter', 'The console''s current drill-down filter (same shape family as dead_ends_bucket_filter — file/detector/repository or none). Present only on reporting_section=unwired.', 'object', false, 60, 505, true, 'unwired'),
('matrx-admin/reporting', 'unwired_worst_files', 'Unwired worst files', 'Top offending files ranked by implementation-line count: { key, findings, lines }. Present only on reporting_section=unwired.', 'array', false, 1200, 510, false, 'unwired'),
('matrx-admin/reporting', 'unwired_problems', 'Unwired scan partial-coverage warnings', 'The scan''s own `partial` list — detectors that could not run to completion this pass (e.g. an aidream checkout was unavailable). Empty array when the scan was complete. Present only on reporting_section=unwired.', 'array', false, 200, 520, false, 'unwired'),
('matrx-admin/reporting', 'lint_debt_totals', 'Lint debt scan totals', 'The committed scan''s header numbers: { generatedAt, commit, errors, filesWithFindings, filesScanned, byClass }, where byClass breaks down bug/correctness/doctrine/style counts. Present only on reporting_section=lint_debt.', 'object', false, 220, 600, true, 'lint_debt'),
('matrx-admin/reporting', 'lint_debt_bucket_filter', 'Lint debt active filter', 'The console''s current drill-down filter (same shape family as dead_ends_bucket_filter — file/feature/rule/class or none). Present only on reporting_section=lint_debt.', 'object', false, 60, 605, true, 'lint_debt'),
('matrx-admin/reporting', 'lint_debt_worst_files', 'Lint debt worst files', 'Top offending files ranked by error count: { key, count, real } — `real` is how many are bug/correctness class. Present only on reporting_section=lint_debt.', 'array', false, 1200, 610, false, 'lint_debt'),
('matrx-admin/reporting', 'lint_debt_worst_features', 'Lint debt worst features', 'Top offending features/route-groups ranked by error count: { key, count, real }. Present only on reporting_section=lint_debt.', 'array', false, 1200, 615, false, 'lint_debt'),
('matrx-admin/reporting', 'lint_debt_by_rule', 'Lint debt by rule', 'Every offending ESLint rule ranked by count: { rule, count, klass }. Present only on reporting_section=lint_debt.', 'array', false, 1500, 620, false, 'lint_debt'),
('matrx-admin/reporting', 'lint_debt_problems', 'Lint debt staleness warnings', 'Warnings from reconcileReport() about the committed snapshot (e.g. stale vs HEAD). Empty array when the snapshot is healthy. Present only on reporting_section=lint_debt.', 'array', false, 200, 625, false, 'lint_debt'),
('matrx-admin/reporting', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/reporting', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/reporting', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/reporting', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/reporting', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/utilities', 'utilities_section', 'Utilities section', 'Which child of the Utilities admin family is active: "hub", "all_routes", "blob_cache", "capture_inspector", "content_blocks", "message_templates", "local_storage", "markdown_tester", "server_cache", or "text_cleaner". Always present — each emitter declares which one it is.', 'string', true, 18, 100, true, 'navigation'),
('matrx-admin/utilities', 'all_routes_list', 'All routes list', 'Every route path scanned under app/(admin)/administration, sorted. Present only on utilities_section=all_routes.', 'array', false, 6000, 200, false, 'all_routes'),
('matrx-admin/utilities', 'blob_cache_l1_stats', 'Blob cache L1 stats', 'In-memory cache stats: { entryCount, totalBytes, budgetBytes }. Absent until the first refresh resolves. Present only on utilities_section=blob_cache.', 'object', false, 80, 300, true, 'blob_cache'),
('matrx-admin/utilities', 'blob_cache_l2_stats', 'Blob cache L2 stats', 'IndexedDB cache stats: { entryCount, totalBytes }. Absent until the first refresh resolves. Present only on utilities_section=blob_cache.', 'object', false, 50, 310, true, 'blob_cache'),
('matrx-admin/utilities', 'blob_cache_sw_status', 'Blob cache service worker status', 'The file-cache service worker''s state: { kind: "unsupported"|"disabled"|"registering"|"registered", scope?, controllerState? }. Present only on utilities_section=blob_cache.', 'object', false, 80, 320, true, 'blob_cache'),
('matrx-admin/utilities', 'capture_exchanges', 'Captured HTTP exchanges', 'The recorded fetch/stream exchanges (id, url, method, status, httpStatus, startedAt, durationMs), newest first, capped by the recorder''s ring buffer. Present only on utilities_section=capture_inspector; empty array before anything is captured.', 'array', false, 5000, 400, false, 'capture_inspector'),
('matrx-admin/utilities', 'capture_mode', 'Capture mode', 'Whether capture recording is currently on or off, and the recorder''s active mode label. Present only on utilities_section=capture_inspector.', 'string', false, 12, 405, true, 'capture_inspector'),
('matrx-admin/utilities', 'capture_selected_exchange', 'Selected capture exchange', 'The full record of the exchange selected for detail — id, request (url, method, headers, body), and response (status, headers, body/stream chunks). Absent until an exchange is selected. Present only on utilities_section=capture_inspector.', 'object', false, 3000, 410, false, 'capture_inspector'),
('matrx-admin/utilities', 'content_blocks_list', 'Content blocks list', 'Every loaded platform.content_blocks row (id, title, category, content, tags, skill associations). Present only on utilities_section=content_blocks.', 'array', false, 8000, 500, false, 'content_blocks'),
('matrx-admin/utilities', 'content_blocks_categories', 'Content blocks categories', 'The category tree used to organize content blocks (id, label, parent). Present only on utilities_section=content_blocks.', 'array', false, 1200, 505, false, 'content_blocks'),
('matrx-admin/utilities', 'content_blocks_filter', 'Content blocks filter', 'The list toolbar''s current state: { selectedCategory (a category id or "all"), searchTerm }. Present only on utilities_section=content_blocks.', 'object', false, 60, 510, true, 'content_blocks'),
('matrx-admin/utilities', 'content_blocks_selected_id', 'Selected content block', 'id of the content block open for editing, or absent when no editor/create dialog is open. Present only on utilities_section=content_blocks.', 'string', false, 36, 515, true, 'content_blocks'),
('matrx-admin/utilities', 'message_templates_list', 'Message templates list', 'Every loaded message_templates row (id, name, role, content, tags, is_active). Present only on utilities_section=message_templates.', 'array', false, 6000, 600, false, 'message_templates'),
('matrx-admin/utilities', 'message_templates_tags', 'Message templates all tags', 'The distinct tag set across all loaded templates, for the filter UI. Present only on utilities_section=message_templates.', 'array', false, 500, 605, false, 'message_templates'),
('matrx-admin/utilities', 'message_templates_filter', 'Message templates filter', 'The list toolbar''s current state: { selectedRole (a role name or "all"), searchTerm }. Present only on utilities_section=message_templates.', 'object', false, 60, 610, true, 'message_templates'),
('matrx-admin/utilities', 'message_templates_selected_id', 'Selected message template', 'id of the message template open for editing/preview, or absent when none is selected. Present only on utilities_section=message_templates.', 'string', false, 36, 615, true, 'message_templates'),
('matrx-admin/utilities', 'local_storage_modules', 'Local storage modules', 'The top-level module namespaces discovered in the browser''s localStorage tree. Present only on utilities_section=local_storage.', 'array', false, 400, 700, false, 'local_storage'),
('matrx-admin/utilities', 'local_storage_selected_module', 'Selected local storage module', 'The module namespace currently drilled into, or "" when browsing the top level. Present only on utilities_section=local_storage.', 'string', false, 30, 705, true, 'local_storage'),
('matrx-admin/utilities', 'local_storage_items', 'Local storage items', 'The key/value entries visible under local_storage_selected_module (raw, unparsed values). Present only on utilities_section=local_storage.', 'object', false, 2000, 710, false, 'local_storage'),
('matrx-admin/utilities', 'local_storage_editing_key', 'Local storage editing key', 'The key currently open in the raw-value editor, or absent when no editor is open. Present only on utilities_section=local_storage.', 'string', false, 60, 715, true, 'local_storage'),
('matrx-admin/utilities', 'markdown_tester_input', 'Markdown tester input', 'The raw markdown/JSON text typed into the sandbox''s editor pane. Empty string before anything is typed. Present only on utilities_section=markdown_tester.', 'string', false, 1500, 800, true, 'markdown_tester'),
('matrx-admin/utilities', 'markdown_tester_extraction_config', 'Markdown tester extraction config', 'The JSON-extraction sandbox''s current settings: { allowFuzzy, repairEnabled, maxResults, chunkStrategy, chunkDelayMs, minChunkSize, maxChunkSize }. Present only on utilities_section=markdown_tester.', 'object', false, 200, 810, true, 'markdown_tester'),
('matrx-admin/utilities', 'server_cache_items', 'Server cache items', 'The revalidation triggers offered on the page (id, title, description, endpoint) and each item''s last refresh result (loading, success, message, timestamp). Present only on utilities_section=server_cache.', 'array', false, 600, 900, false, 'server_cache'),
('matrx-admin/utilities', 'text_cleaner_input', 'Text cleaner input', 'The raw text pasted into the cleaner. Empty string before anything is typed. Present only on utilities_section=text_cleaner.', 'string', false, 1000, 1000, true, 'text_cleaner'),
('matrx-admin/utilities', 'text_cleaner_config', 'Text cleaner active config', 'The selected cleaning pattern/preset and any custom rule overrides. Present only on utilities_section=text_cleaner.', 'object', false, 300, 1010, true, 'text_cleaner'),
('matrx-admin/utilities', 'text_cleaner_output', 'Text cleaner output', 'The cleaned result of applying text_cleaner_config to text_cleaner_input. Empty string until a clean has run. Present only on utilities_section=text_cleaner.', 'string', false, 1000, 1020, true, 'text_cleaner'),
('matrx-admin/utilities', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/utilities', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/utilities', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/utilities', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/utilities', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-admin/documentation', 'documentation_section', 'Documentation section', 'Which part of the Feature Docs browser is active: "hub" (link directory), "codebase", "docs", "dotdirs" (the dot-dir picker), "dotdir_detail" (one dot-dir''s table), or "view" (a single rendered doc). Always present — each emitter declares which one it is.', 'string', true, 14, 100, true, 'navigation'),
('matrx-admin/documentation', 'feature_docs_zone', 'Feature docs zone', 'Which table zone the browser is scoped to: "codebase" (app/, features/, components/ — excludes docs/ and tooling dirs), "docs" (root docs/ only), or "dotdir" (one tooling dot-dir). Present on documentation_section=codebase|docs|dotdir_detail.', 'string', false, 10, 110, true, 'navigation'),
('matrx-admin/documentation', 'feature_docs_dot_dir', 'Feature docs dot-dir', 'The tooling dot-dir the table is scoped to (e.g. ".claude", ".agents"). Present only on documentation_section=dotdir_detail.', 'string', false, 20, 120, true, 'navigation'),
('matrx-admin/documentation', 'feature_docs_dot_dirs_list', 'Feature docs dot-dirs list', 'Every tooling dot-dir offered on the picker (e.g. ".claude", ".agents", ".codex"). Present only on documentation_section=dotdirs.', 'array', false, 120, 130, false, 'navigation'),
('matrx-admin/documentation', 'feature_docs_rows', 'Feature docs table rows', 'Every admin.feature_docs row matching the current zone (path, slug, title, area, content_hash, sync_base_hash, sync_base_commit, synced_at, updated_at, version, deleted_at). Present on documentation_section=codebase|docs|dotdir_detail.', 'array', false, 12000, 200, false, 'browser'),
('matrx-admin/documentation', 'feature_docs_table_filters', 'Feature docs table filters', 'The table''s current { sortField, sortDirection, filters } (per-column text filters, e.g. by path/title/area). Present on documentation_section=codebase|docs|dotdir_detail.', 'object', false, 150, 210, true, 'browser'),
('matrx-admin/documentation', 'current_doc_path', 'Current doc path', 'Repo-relative path of the doc open on the view page (e.g. "features/notes/FEATURE.md"). Present only on documentation_section=view.', 'string', false, 60, 300, true, 'doc_viewer'),
('matrx-admin/documentation', 'current_doc', 'Current doc', 'The full loaded admin.feature_docs record for current_doc_path: { id, path, slug, title, area, content, content_hash, sync_base_hash, sync_base_commit, synced_at, updated_at, version, metadata }. Present only on documentation_section=view.', 'object', false, 12000, 310, true, 'doc_viewer'),
('matrx-admin/documentation', 'selection', 'Current selection', 'The user''s currently selected text on the surface. Empty string when nothing is selected.', 'string', false, 200, 100, true, 'baseline'),
('matrx-admin/documentation', 'text_before', 'Text before selection', 'Text immediately preceding the selection within the same editable region. Empty when there is no selection or no preceding text.', 'string', false, 500, 110, true, 'baseline'),
('matrx-admin/documentation', 'text_after', 'Text after selection', 'Text immediately following the selection within the same editable region. Empty when there is no selection or no trailing text.', 'string', false, 500, 120, true, 'baseline'),
('matrx-admin/documentation', 'content', 'Primary content', 'The surface''s primary editable content (full document, full note, full file body). Use with care — can be large.', 'string', false, 5000, 200, true, 'baseline'),
('matrx-admin/documentation', 'context', 'Free-form context', 'Loose-shaped context blob a surface may emit (commonly an object with surface-specific keys). Prefer named SurfaceValues over stuffing things in here.', 'object', false, 1000, 9999, true, 'baseline'),
('matrx-user/quick-data', 'is_loading', 'Loading', 'True while the window''s table list is being fetched (get_user_tables). Always populated while the window is mounted.', 'boolean', true, 5, 100, true, 'table_picker'),
('matrx-user/quick-data', 'load_error', 'Load error', 'Message from a failed table-list fetch. Absent when the list loaded successfully or is still loading.', 'string', false, 80, 110, true, 'table_picker'),
('matrx-user/quick-data', 'table_count', 'Table count', 'Number of data tables available to pick from in this window. Zero while loading or when the user has no tables.', 'number', true, 4, 120, true, 'table_picker'),
('matrx-user/quick-data', 'tables_summary', 'Available tables', 'Every table offered in the picker dropdown, most-recently-updated first: { id, table_name, description, row_count, field_count, updated_at }. Empty array while loading or when the user has no tables.', 'array', true, 900, 130, true, 'table_picker'),
('matrx-user/quick-data', 'selected_table_id', 'Selected table ID', 'UUID of the table currently shown in the viewer. Empty until the picker has a table selected (auto-selects the most recently updated table once the list loads, or the caller''s requested table when the window was opened with one).', 'string', false, 36, 140, true, 'table_picker'),
('matrx-user/quick-data', 'selected_table_name', 'Selected table name', 'Name of the table named by `selected_table_id`, from `tables_summary`. Empty when no table is selected.', 'string', false, 60, 150, true, 'table_picker')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, always_available = EXCLUDED.always_available, typical_char_count = EXCLUDED.typical_char_count, sort_order = EXCLUDED.sort_order, auto_context = EXCLUDED.auto_context, group_key = EXCLUDED.group_key, updated_at = now();

-- Upsert all manifest write targets
INSERT INTO ui.ui_surface_write_target (surface_name, name, label, description, value_type, mode, updates_value, group_key, sort_order, apply_policy) VALUES
('matrx-admin/scheduling', 'cron_expression', 'Cron expression', 'Replaces the expression in the Cron tester''s input, so the page re-validates it and previews its next fires. Send a PLAIN TEXT STRING — not JSON, and not JSON-encoded — holding a standard 5-field cron expression in the order "minute hour day-of-month month day-of-week" (e.g. "0 9 * * 1-5" = weekdays at 9:00 in the selected timezone; "30 8 * * 1" = Mondays at 8:30; "0 */4 * * *" = every 4 hours). There is NO seconds field and @daily-style macros are not accepted. The value is checked with the SAME parser the page previews with and REFUSED with the parser''s own message if it will not parse, so nothing invalid can be staged. Ephemeral: this tester schedules nothing and persists nothing.', 'string', 'ui', 'cron_expression', 'cron_tester', 100, 'ask'),
('matrx-admin/scheduling', 'cron_timezone', 'Cron timezone', 'Replaces the timezone the Cron tester evaluates the expression in, which changes the previewed fire times. Send a PLAIN TEXT STRING — not JSON, and not JSON-encoded — holding one IANA timezone name. Only the zones this page''s picker can display are accepted: "America/Los_Angeles", "America/Denver", "America/Chicago", "America/New_York", "UTC", "Europe/London", "Europe/Paris", "Europe/Berlin", "Asia/Tokyo", "Australia/Sydney". US zone names like "Eastern"/"EST" or any other IANA zone are REFUSED, because the picker could not show them. Ephemeral: this tester schedules nothing and persists nothing.', 'string', 'ui', 'cron_timezone', 'cron_tester', 110, 'ask')
ON CONFLICT (surface_name, name) DO UPDATE SET label = EXCLUDED.label, description = EXCLUDED.description, value_type = EXCLUDED.value_type, mode = EXCLUDED.mode, updates_value = EXCLUDED.updates_value, group_key = EXCLUDED.group_key, sort_order = EXCLUDED.sort_order, apply_policy = EXCLUDED.apply_policy, updated_at = now();

-- Mirror url_pattern / intro / parent_surface_name (declared fields only)
UPDATE ui.ui_surface SET label = 'Public Agent App', value_groups = '[{"key":"app_identity","label":"App identity","sortOrder":100,"description":"Which published app.definition row is running and the agent it is bound to."},{"key":"visitor","label":"Visitor","sortOrder":200,"description":"Who is running the app: a signed-in user or an anonymous guest identified by browser fingerprint, plus the guest run-limit state."},{"key":"run_input","label":"Run input","sortOrder":300,"description":"What the visitor supplied for this run: the free-text message and the form variable values validated against the app''s variable_schema."},{"key":"run_state","label":"Run state","sortOrder":400,"description":"The resulting conversation and the live/streamed outcome of the current or most recent execution."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Manifest + emitter wired (runtime.surfaceName now passed to launchAgentExecution and a SurfaceRuntimeProvider mounted). Anonymous surface — no live agent-binding / Matrx-vs-matrix verification run yet; also covers only the CustomComponentRenderer path (component_code / template apps). The built-in shells in features/agent-apps/components/shells/ and AgentAppFullyCustomShell run their own execution paths and are NOT yet audited or wired to this surface.', url_pattern = '/p', intro = '<surface_intro>
You are bound to a PUBLISHED, PUBLIC agent app running for an anonymous or newly-arrived visitor at /p/[slug] — not the app''s builder/owner. App identity tells you which app.definition row and which agent are running. Visitor tells you whether this person is signed in or an anonymous guest tracked only by browser fingerprint, and how many free guest runs remain — anonymous guests are the common case here, never assume a logged-in user. Run input is what THIS visitor just submitted (a typed message and/or form variable values validated against the app''s schema); read it as their actual request, not a template. Run state is the resulting conversation and the live/streamed response for their run.
Treat this like any first-contact interaction with a stranger: no prior context about this person exists beyond what is declared here.
</surface_intro>', updated_at = now() WHERE name = 'matrx-public/p';
UPDATE ui.ui_surface SET label = 'Server Logs', value_groups = '[{"key":"app_selection","label":"App selection","sortOrder":100,"description":"Which backend service/environment the viewer is showing, and the catalogue of services it can switch between."},{"key":"fetch_state","label":"Fetch state","sortOrder":200,"description":"How many lines were requested, the auto-poll interval, when the log text was last fetched, and any fetch error."},{"key":"filters","label":"Filters & search","sortOrder":300,"description":"The active level/category/urgency/module/endpoint/search filters, the noise-exclusion presets, and the line-range window applied to the parsed log lines."},{"key":"log_view","label":"Log content","sortOrder":400,"description":"The parsed log lines currently visible after filtering, and the line (or range) the admin has selected for inspection."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Emitter wired and verified live (2026-08-12): CoolifyLogViewer.tsx mounts SurfaceRuntimeProvider and every declared value is populated from live render state via buildAdminServerLogsScope. Short of `verified` on two honest counts. (1) `raw_logs` and `visible_log_lines` are emitted as capped TAILS with a truncation banner, not in full — the 400ms Surface Context sampler JSON.stringify-fingerprints the whole scope, and a 10,000-line fetch is megabytes. (2) The DB mirror has not been re-synced since this pass added `fetched_log_line_count`, `visible_log_level_counts`, `visible_log_lines`, `log_view_range` and `selected_line_range` and reshaped `log_filters`; run the surfaces-admin sync to clear it. Write targets are RULED OUT by design, not pending — see the ruling in the file header.', url_pattern = '/administration/compute/server-logs', intro = '<surface_intro>
This is an ADMIN surface: the super-admin server log viewer at /administration/compute/server-logs/[app], showing live Coolify logs for one backend service (aidream, scraper-service, or matrx-ai, each with a production and development deployment).

The viewer fetches raw log text, parses it into lines with level/category/urgency/module, and lets the admin filter, search, and select a line for JSON-payload inspection. selected_app and selected_app_environment tell you which service/environment you are looking at; log_filters, log_noise_excludes and log_view_range describe what has been narrowed out; fetched_log_line_count vs visible_log_line_count tell you how much of the fetch survived that narrowing.

READ THE LOGS FROM visible_log_lines — it carries the actual text of the lines on screen. visible_log_level_counts answers "is anything erroring" without reading them. selected_log_line and selected_line_range tell you what the admin has singled out; the marked text arrives as the baseline "selection" value. Both visible_log_lines and raw_logs are capped to a TAIL of the newest lines and announce it with a "[truncated: ...]" banner — believe that banner rather than counting lines yourself, and say so when a question depends on lines that were cut.

What you may safely do: read the visible/selected log content and explain errors, summarize patterns, or suggest a better filter or search term. This surface is READ-ONLY BY DESIGN — it declares no write targets, and you cannot change a filter, restart, deploy, or modify the service being logged. The logs are the record of what happened; if you propose a filter or a fix, say it is a suggestion and never imply you applied it.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/server-logs';
UPDATE ui.ui_surface SET label = 'Scheduling', value_groups = '[{"key":"hub","label":"Scheduling hub","sortOrder":100,"description":"Which of the seven tabs the admin is currently on."},{"key":"overview","label":"Overview","sortOrder":200,"description":"Health counters for the sch_* spine visible to the viewer."},{"key":"tasks","label":"Tasks","sortOrder":300,"description":"The scheduled-task list loaded into the Tasks tab."},{"key":"runs","label":"Runs","sortOrder":400,"description":"The run list and its server-side status/surface filters."},{"key":"orphan_leases","label":"Orphan leases","sortOrder":500,"description":"Runs whose claim lease expired without completing."},{"key":"cron_tester","label":"Cron tester","sortOrder":600,"description":"The expression/timezone the admin is testing and its validation result."},{"key":"scanner_health","label":"Scanner health","sortOrder":700,"description":"Live status of aidream''s matrx-scheduler scanner process."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'All seven tabs emit live. The shell (SchedulingAdminLayoutClient) mounts the outer SurfaceRuntimeProvider and derives active_tab from the pathname; Overview, Tasks, Runs, Orphan leases and Scanner health publish their own slices through features/scheduling/lib/admin-scheduling-scope.ts, and only the MOUNTED tab''s slice is emitted. The Cron tester nests its own provider (features/scheduling/lib/cron-tester-surface.ts), wins that tab by depth, and carries the surface''s two write targets. Every value was checked against the live page and both write targets were verified with real agent runs (apply, decline, undeclared-target refusal, and invalid-value throws). Still short of `verified`: the DB value sync has NOT been applied, so ui_surface_value still carries the removed task_search/task_enabled_filter rows and none of the newly declared scanner_*/cron_expression_human/cron_preview_count/overview_load_error rows; and no page element carries a data-surface-value anchor for Locate. Templates (templates/page.tsx) is a hardcoded in-file SEEDS array with no backing table yet — the page''s own "Coming next" alert says a sch_template table + read RPC are pending — so it is deliberately NOT declared as page data here; declaring it would promise a value no real data source supplies.', url_pattern = '/administration/automation/scheduling', intro = '<surface_intro>
This is an ADMIN surface: the Scheduling console at /administration/automation/scheduling, a view over the sch_* spine (scheduled tasks, their runs, and the scanner that dispatches them).

active_tab tells you which of the seven tabs the admin is on and is always present. Only the MOUNTED tab''s values are emitted — every other tab''s values are absent, not stale, because each tab owns its own state.

READ THE COUNTS CORRECTLY: despite the console''s cross-user framing, scheduler.sch_task / sch_run have no live admin RLS clause (FOUND_DEFECTS D140), so every count and row here is the VIEWER''S OWN scheduled work, not the platform''s. Do not report these as fleet-wide numbers.

Overview carries the health counters. Tasks and Runs report how many rows the SERVER returned (each capped at 200); their tables also have their own search boxes and column filters, which narrow the screen without changing these counts and which the page cannot read — so never infer "what the admin is looking at" from them. Runs additionally exposes its two server-side filters. Orphan leases counts runs whose claim lease expired without completing — these should self-heal on the next scanner tick; a persistent nonzero count means something is wrong upstream. Scanner health mirrors aidream''s live scanner process state.

Templates has no backing data source yet (hardcoded starter examples pending a real table) and is deliberately undeclared.

Cron tester is a pure client-side scratch pad and the one place here you can WRITE. It validates an expression + timezone and previews the next fires; it reads no database and fires nothing. You may set cron_expression and cron_timezone (the admin confirms each change), then read cron_validation_error, cron_expression_human and cron_next_fires to check your own work. Everything else on this surface is read-only operational evidence: reason about it, report on it, and leave the changing to a person. Nothing in this console can enable, disable, re-cron or fail a real scheduled task — those stay human.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/scheduling';
UPDATE ui.ui_surface SET label = 'Growth Loop Map', value_groups = '[{"key":"loop_overview","label":"Loop overview","sortOrder":100,"description":"The whole map''s health, derived from loop-map.ts: pipe-state score, open gaps, blockers, and a compact summary of every stage and edge."},{"key":"selection","label":"Selection","sortOrder":200,"description":"The single stage or edge the user has clicked, and its detail. Empty when nothing is selected."}]'::jsonb, readiness = 'partial', readiness_note = 'Emitter wired in GrowthLoopCanvasInner and matches the component''s real state (the static overview + click selection), but not yet live-checked against the DB (no ui_surface row exists — the orchestrator seeds it) and never bound to a test agent for the Matrx-vs-matrix verification.', url_pattern = '/administration/knowledge/growth-loop', intro = '<surface_intro>
You are on the admin Growth Loop map: the twelve-stage pipeline (Research through Write-back) scored on THE THREE PIPES — code, human, and AI — per stage and per connection between stages. loop_score / open_gap_count / blocker_count / blockers_summary give the whole-map health; stages_summary and edges_summary list every node and arrow the canvas renders. The data itself is static (hand-maintained in loop-map.ts, not fetched) — the only thing that changes per view is which single stage or arrow the user has clicked. selection_kind tells you whether that is a stage, a connection, or nothing; selected_stage_detail / selected_edge_detail carry the full record for whichever one is selected, and selection_gaps lists the gaps sitting on it.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/growth-loop';
UPDATE ui.ui_surface SET label = 'Reporting Admin', value_groups = '[{"key":"navigation","label":"Reporting navigation","sortOrder":100,"description":"Which child tool of the Reporting admin family is active."},{"key":"events","label":"Events","sortOrder":200,"description":"The live platform.activity_log viewer: action-prefix filter, auto-refresh toggle, and the fetched rows."},{"key":"reports_catalog","label":"Reports catalog","sortOrder":300,"description":"The admin-mode report registry list (metadata only — each entry links to its own report page)."},{"key":"dead_ends","label":"No Dead Ends scoreboard","sortOrder":400,"description":"Door Law violations: committed scan totals, the active drill-down filter, worst offenders, and staleness warnings."},{"key":"unwired","label":"Unwired Work scoreboard","sortOrder":500,"description":"Purpose-built code with no runtime wiring: committed scan totals, the active drill-down filter, worst files, and staleness warnings."},{"key":"lint_debt","label":"ESLint debt scoreboard","sortOrder":600,"description":"Repo-wide ESLint error backlog classified bug/correctness/doctrine/style: committed scan totals, the active drill-down filter, worst offenders, and staleness warnings."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'stub', readiness_note = 'Manifest-only — vocabulary audited against the live pages, no runtime emitter wired yet. /administration/reporting itself is a static link directory (AdminDomainDirectory, no data, no values). Events has live filter/auto-refresh/row state with no provider mounted. The three scoreboards (dead-ends/unwired/lint-debt) each hold their bucket-drill useState inside a shared *Console component with no prop seam to publish from today — wiring all four emitters is real follow-up work.', url_pattern = '/administration/reporting', intro = '<surface_intro>
This is an ADMIN surface: the Reporting admin family at /administration/reporting, covering six unrelated super-admin reporting tools that happen to live under one hub.

reporting_section tells you which one is active: "hub" (static link directory, no data), "events" (a live platform.activity_log viewer with an action-prefix filter and optional auto-refresh), "reports" (the admin-mode catalog of platform-wide reports), or one of the three committed-snapshot scoreboards — "dead_ends" (No Dead Ends / Door Law violations), "unwired" (purpose-built code with no runtime wiring), "lint_debt" (repo-wide ESLint error backlog, classified bug/correctness/doctrine/style).

The three scoreboards share one vocabulary shape: a *_totals object (the scan''s header numbers), a *_bucket_filter object (the admin''s current drill-down — which file/feature/rule/detector/class they''re looking at, or none), a worst-offenders list, and a *_problems array of staleness warnings about the committed snapshot itself (these are NEVER live scans — a full run takes minutes, so each console reads a committed report.json that can go stale).

Only the values matching the current reporting_section are populated — everything else is absent, not stale. This surface has no write targets — every scoreboard''s action is "open the source line" (a real navigation, not an in-page mutation), and Events has no write affordance at all.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/reporting';
UPDATE ui.ui_surface SET label = 'Utilities Admin', value_groups = '[{"key":"navigation","label":"Utilities navigation","sortOrder":100,"description":"Which child tool of the Utilities admin family is active."},{"key":"all_routes","label":"All routes","sortOrder":200,"description":"The full scanned app/(admin)/administration route tree."},{"key":"blob_cache","label":"Blob cache","sortOrder":300,"description":"Browser file-cache diagnostics: L1 (in-memory) and L2 (IndexedDB) stats, and the file-cache service worker''s registration status."},{"key":"capture_inspector","label":"Capture inspector","sortOrder":400,"description":"Every captured HTTP exchange (request + response, streamed or plain), newest first, and the one selected for detail."},{"key":"content_blocks","label":"Content blocks","sortOrder":500,"description":"platform.content_blocks CRUD: the loaded blocks, categories, skill options, and current list filter/selection."},{"key":"message_templates","label":"Message templates","sortOrder":600,"description":"message_templates CRUD: the loaded templates, distinct tags, and the current role filter/search/selection."},{"key":"local_storage","label":"Local storage","sortOrder":700,"description":"Browser localStorage/cookie inspector: the module/feature namespace tree and the currently selected key''s raw value."},{"key":"markdown_tester","label":"Markdown tester","sortOrder":800,"description":"The markdown/streaming-render sandbox: the input text and the active preview/extraction mode."},{"key":"server_cache","label":"Server cache","sortOrder":880,"description":"Server-side revalidation triggers (e.g. the AI models cache) and each item''s last refresh result."},{"key":"text_cleaner","label":"Text cleaner","sortOrder":890,"description":"The text-cleaning sandbox: input text, the active cleaning pattern/config, and the cleaned output."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'stub', readiness_note = 'Manifest-only — vocabulary audited against the live pages, no runtime emitter wired yet. /administration/utilities itself is a static link directory (AdminDomainDirectory, no data, no values). kind-registry is deliberately excluded (own surface, matrx-admin/kind-registry). Every other child is its own independent client component tree (content-blocks and message-templates each carry 10+ useState hooks of CRUD/dialog state) with no shared provider seam — wiring an emitter per child is real follow-up work.', url_pattern = '/administration/utilities', intro = '<surface_intro>
This is an ADMIN surface: the Utilities admin family at /administration/utilities, covering eight unrelated developer/admin diagnostic tools that happen to live under one hub. The Shape System console at /administration/utilities/kind-registry is a SEPARATE surface (matrx-admin/kind-registry) — nothing about it lives here.

utilities_section tells you which one is active: "all_routes" (the full scanned app route tree), "blob_cache" (browser file-cache L1/IndexedDB stats + service-worker status), "capture_inspector" (every captured HTTP exchange, request and response), "content_blocks" (platform.content_blocks CRUD — skill-teachable content snippets), "message_templates" (message_templates CRUD — agent/system prompt templates by role), "local_storage" (browser localStorage/cookie inspector and editor), "markdown_tester" (a markdown/streaming-render sandbox), "server_cache" (server-side revalidation triggers), or "text_cleaner" (a text-cleaning/normalization sandbox).

Only the values matching the current utilities_section are populated — everything else is absent, not stale. Treat all rows here as live production/browser-local data: summarize, diagnose, explain, but never republish verbatim at scale. This surface has no write targets yet — content-blocks, message-templates, and local-storage all have real in-page CRUD forms, but nothing is wired for agent writes.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/utilities';
UPDATE ui.ui_surface SET label = 'Documentation Admin', value_groups = '[{"key":"navigation","label":"Documentation navigation","sortOrder":100,"description":"Which part of the Feature Docs browser is active."},{"key":"browser","label":"Feature docs browser","sortOrder":200,"description":"The codebase/docs/dotdir table''s loaded rows, sort, and column filters."},{"key":"doc_viewer","label":"Doc viewer","sortOrder":300,"description":"The single markdown doc open on the view page."},{"key":"baseline","label":"Generic baselines","sortOrder":9900}]'::jsonb, readiness = 'partial', readiness_note = 'Navigation (documentation_section/feature_docs_zone/feature_docs_dot_dir/feature_docs_dot_dirs_list) is wired and real via FeatureDocsShell. The doc viewer (current_doc_path/current_doc) is wired and real via FeatureDocViewerRuntime, nested inside the shell''s provider depth. feature_docs_rows and feature_docs_table_filters are declared (THE COMPLETENESS LAW) but NOT emitted — they live inside FeatureDocsTable''s own useState with no prop seam to publish from today; left for a follow-up pass.', url_pattern = '/administration/documentation', intro = '<surface_intro>
This is an ADMIN surface: the Feature Docs browser at /administration/documentation, over admin.feature_docs — markdown synced one-way from the repo (app/, features/, components/, docs/, and tooling dot-dirs like .claude/).

documentation_section tells you which part is active: "codebase"/"docs"/"dotdir_detail" (a sortable/filterable table of synced docs, scoped by feature_docs_zone and — for dotdir_detail — feature_docs_dot_dir), "dotdirs" (the picker listing every tooling dot-dir), or "view" (one doc''s full rendered markdown, in current_doc).

Only the values matching the current documentation_section are populated — everything else is absent, not stale. This surface has no write targets: feature_docs is a one-way sync target (repo markdown → DB), so there is nothing here for an agent to write back into — treat every doc as read-only reference material to summarize or answer questions from, and note its synced_at/sync_base_commit when currency matters.
</surface_intro>', updated_at = now() WHERE name = 'matrx-admin/documentation';
UPDATE ui.ui_surface SET label = 'Quick Data', value_groups = '[{"key":"table_picker","label":"Table picker","sortOrder":100,"description":"The list of the user''s data tables offered in this window and which one is currently open."}]'::jsonb, readiness = 'partial', readiness_note = 'Emitter wired in QuickDataSheet and reflects its real state (table picker + selection). Gap (COMPLETENESS LAW, not fabricated here): the deep table state — schema, visible rows, search, column filters, and the open cell/row editor — belongs to the `matrx-user/data-tables` surface and is only emitted by `UserTableViewer` when its host passes `emitSurfaceScope`, which `QuickDataWindow` deliberately does not (that provider is opt-in precisely to avoid shadowing a host surface — see `data-tables.manifest.ts`). QuickDataSheet has no lifted access to that nested state today, so it cannot be declared here without fabricating a value the component doesn''t hold. If deep table editing inside this window becomes a real use case, the fix is either (a) accept the deepest-wins nesting and pass `emitSurfaceScope` through, degrading quick-data''s own scope to invisible while a table is open, or (b) lift UserTableViewer''s search/filter/edit state out so QuickDataSheet can re-emit it under this surface''s own vocabulary.', overlay_id = 'quickDataWindow', url_pattern = '/quick-data', intro = '<surface_intro>
You are in the floating Quick Data window — a portable table picker a caller opened to browse the user''s data tables (from a markdown table/csv/json block, the data-review "send to" menu, or the user''s own quick actions) without leaving what they were doing. tables_summary lists every table available; selected_table_id / selected_table_name identify the one currently shown. This surface only covers the PICKER — schema, rows, and cell edits belong to the Data Tables surface and are not available here while embedded in this window.
</surface_intro>', updated_at = now() WHERE name = 'matrx-user/quick-data';
