/**
 * features/notes/redux/unsavedDraftNeverNotFound.test.ts
 *
 * THE DEFECT (verifier, 2026-09-26): press "+" or "New Note" on /notes, then
 * reload before typing — the new tab showed "We couldn't find this note".
 * A new note is a CLIENT-ONLY draft (`createAutogeneratedNote`, no database
 * row until the first edit), but the tab bar wrote its id into
 * `?tabs=&active=`, so a reload restored the id and `fetchNoteContent` asked
 * `workbench.notes` for a row that was never written. `NoteContentEditor`
 * renders the AccessGate "couldn't find" card exactly when the record is
 * absent and that read is in `error`.
 *
 * The seam: the REAL notes reducer creates the draft, the REAL URL writer the
 * tab bar uses (`noteTabsUrlParams`) turns the open tabs into the URL, and the
 * REAL restore rule + `fetchNoteContent` run against a fresh store as a reload
 * does. Only the Supabase client is mocked — it answers "no row", which is the
 * truth for a draft that was never saved.
 *
 * Use case: a clinic manager opens a new tab for the new-patient intake
 * checklist, then reloads the page before typing the first line.
 */

import { withClaims } from "@/test-utils/supabase-auth";

const schema = jest.fn();
const getSession = jest.fn();

jest.mock("@/utils/supabase/client", () => ({
  supabase: { schema, rpc: jest.fn(), auth: withClaims({ getSession }) },
}));
jest.mock("@/utils/auth/getUserId", () => ({
  requireUserId: () => "clinic-manager-1",
  getUserId: () => "clinic-manager-1",
}));
jest.mock("@/features/scopes/service/associationsService", () => ({
  associationsService: {
    listForSources: jest.fn(async () => ({ ok: true, data: { edges: [] } })),
    setTargets: jest.fn(async () => ({ ok: true, data: null })),
  },
}));

import { configureStore, type UnknownAction } from "@reduxjs/toolkit";
import { enableMapSet } from "immer";
import { createSlimRootReducer, type RootState } from "@/lib/redux/rootReducer";
import {
  createAutogeneratedNote,
  registerInstance,
  addInstanceTab,
  setInstanceActiveTab,
  upsertNoteFromServer,
} from "./slice";
import {
  fetchNoteContent,
  refetchNoteContent,
  refreshNoteContent,
} from "./thunks";
import { noteTabsUrlParams } from "../utils/tabUrlOrder";
import { initialTabsFromUrl } from "../initialTabsFromUrl";
import type { Note } from "../types";

enableMapSet();

const USER = "clinic-manager-1";
const ORG = "5c1a1c00-0000-4000-8000-00000000c11c";
const INSTANCE = "notes-workspace";
const INTAKE_DRAFT_ID = "8f0e6b52-3c1d-4d7a-9a51-0b7c2e4f9a10";
const SAVED_NOTE_ID = "3b9d2a41-7e55-4c08-8f2a-6d1e0c5b7a22";

function savedStaffRota(): Note {
  return {
    id: SAVED_NOTE_ID,
    content: "Front desk: Maria (Mon–Wed), Dev (Thu–Fri)",
    content_hash: null,
    created_at: "2026-09-20T15:00:00.000Z",
    created_by: USER,
    custom_fields: {},
    deleted_at: null,
    file_path: null,
    folder_id: null,
    folder_name: "Clinic operations",
    label: "Front desk rota",
    last_device_id: null,
    metadata: {},
    organization_id: ORG,
    position: 0,
    project_id: null,
    sync_version: 0,
    tags: [],
    task_id: null,
    updated_at: "2026-09-20T15:00:00.000Z",
    updated_by: null,
    version: 3,
    visibility: "personal",
  };
}

/** PostgREST chain: the draft id has no row; the saved rota does. */
interface NotesTableChain {
  select: jest.Mock<NotesTableChain, []>;
  eq: jest.Mock<NotesTableChain, [string, string]>;
  maybeSingle: jest.Mock<Promise<{ data: Note | null; error: null }>, []>;
}

function notesTable(): NotesTableChain {
  let requestedId: string | null = null;
  const chain: NotesTableChain = {
    select: jest.fn((): NotesTableChain => chain),
    eq: jest.fn((_column: string, value: string): NotesTableChain => {
      requestedId = value;
      return chain;
    }),
    maybeSingle: jest.fn(async () => ({
      data: requestedId === SAVED_NOTE_ID ? savedStaffRota() : null,
      error: null,
    })),
  };
  return chain;
}

function testRootReducer() {
  const slim = createSlimRootReducer();
  return (state: RootState | undefined, action: UnknownAction): RootState => {
    const next = slim(state, action);
    if (action.type === "test/seed-user") {
      return { ...next, userAuth: { ...next.userAuth, id: USER } };
    }
    return next;
  };
}

function freshStore() {
  const store = configureStore({
    reducer: testRootReducer(),
    middleware: (getDefault) => getDefault({ serializableCheck: false }),
  });
  store.dispatch({ type: "test/seed-user" });
  store.dispatch(registerInstance(INSTANCE));
  return store;
}

/** The facts `NoteContentEditor` branches on for one tab. */
function tabShowsCouldNotFind(state: RootState, noteId: string): boolean {
  return !state.notes.notes[noteId] && state.notes.contentLoadStatus[noteId] === "error";
}

let table: ReturnType<typeof notesTable>;
beforeEach(() => {
  jest.clearAllMocks();
  getSession.mockResolvedValue({ data: { session: { user: { id: USER } } }, error: null });
  table = notesTable();
  schema.mockReturnValue({ from: jest.fn(() => table) });
});

describe("a note that was never saved is never presented as 'couldn't find this note'", () => {
  it("reloading right after '+' (before typing) never looks the draft up in the database", async () => {
    // Before the reload: the saved rota is open, then "+" opens the intake draft.
    const before = freshStore();
    before.dispatch(upsertNoteFromServer({ note: savedStaffRota(), fetchStatus: "full" }));
    before.dispatch(addInstanceTab({ instanceId: INSTANCE, noteId: SAVED_NOTE_ID }));
    before.dispatch(
      createAutogeneratedNote({
        id: INTAKE_DRAFT_ID,
        userId: USER,
        folder: null,
        organizationId: ORG,
        instanceId: INSTANCE,
      }),
    );
    const inst = before.getState().notes.instances[INSTANCE];
    expect(inst.activeTabId).toBe(INTAKE_DRAFT_ID);

    // What the tab bar writes into the address bar.
    const url = noteTabsUrlParams({
      openTabs: inst.openTabs,
      activeTabId: inst.activeTabId,
      splitNoteId: inst.splitNoteId,
      notes: before.getState().notes.notes,
    });

    // The reload: a fresh store restores exactly what the URL names.
    const after = freshStore();
    const restored =
      initialTabsFromUrl({
        tabs: url.tabs ? url.tabs.split(",") : [],
        active: url.active,
        routeNoteId: null,
      }) ?? [];
    for (const noteId of restored) {
      after.dispatch(addInstanceTab({ instanceId: INSTANCE, noteId }));
      await after.dispatch(fetchNoteContent(noteId));
    }
    if (url.active) {
      after.dispatch(setInstanceActiveTab({ instanceId: INSTANCE, noteId: url.active }));
    }

    const state = after.getState();
    // The saved note still comes back on reload.
    expect(restored).toContain(SAVED_NOTE_ID);
    expect(state.notes.notes[SAVED_NOTE_ID]?.label).toBe("Front desk rota");
    // No restored tab is ever a "couldn't find this note" card.
    for (const noteId of state.notes.instances[INSTANCE].openTabs) {
      expect(tabShowsCouldNotFind(state, noteId)).toBe(false);
    }
    // The never-saved draft id is never read from workbench.notes.
    expect(table.eq).not.toHaveBeenCalledWith("id", INTAKE_DRAFT_ID);
  });

  it.each([
    ["fetchNoteContent", fetchNoteContent],
    ["refreshNoteContent (the Refresh button)", refreshNoteContent],
    ["refetchNoteContent (version restore)", refetchNoteContent],
  ] as const)(
    "%s on an open, never-saved draft keeps the draft and never reads the database",
    async (_name, thunk) => {
      const store = freshStore();
      store.dispatch(
        createAutogeneratedNote({
          id: INTAKE_DRAFT_ID,
          userId: USER,
          folder: null,
          organizationId: ORG,
          instanceId: INSTANCE,
        }),
      );

      const result = await store.dispatch(thunk(INTAKE_DRAFT_ID));

      expect(result.meta.requestStatus).toBe("fulfilled");
      expect(table.eq).not.toHaveBeenCalledWith("id", INTAKE_DRAFT_ID);
      const state = store.getState();
      expect(state.notes.notes[INTAKE_DRAFT_ID]?._isAutogenerated).toBe(true);
      expect(tabShowsCouldNotFind(state, INTAKE_DRAFT_ID)).toBe(false);
    },
  );
});
