/**
 * PDF Extractor — frontend type surface.
 *
 * Re-exports the OpenAPI-generated schemas the backend team ships at
 * `types/python-generated/api-types.ts`. Always import PDF request/response
 * shapes from this file rather than reaching directly into the generated
 * file — that keeps the import path stable when the generated layout changes.
 *
 * The generated file is regenerated by:
 *   `pnpm update-api-types` (against the staging backend)
 *   `pnpm update-api-types:local` (against http://localhost:8000)
 *
 * Do not edit `types/python-generated/api-types.ts` by hand.
 */

import type { components } from "@/types/python-generated/api-types";

type Schemas = components["schemas"];

// ── Source contract (pick one of: media | file | url | local_path) ─────────

/**
 * Reference to a media file. The client sends exactly ONE identifier on
 * the wire: `file_id` (cld_files row id) | `url` (https://…). Native
 * storage locations (s3://…) are server-only — never read or sent by the FE.
 * There is NO `cld_id` field — the backend silently drops unknown keys,
 * which used to 422 every cloud-sourced operation. Build sources with
 * `buildPdfSource` from `@/features/pdf/utils/source`.
 */
export type MediaRef = Schemas["MediaRef"];

// ── Page selection ─────────────────────────────────────────────────────────

/** 1-based page range. */
export type PdfPageRange = Schemas["PdfPageRange"];

/** Crop box used by `/crop-pages`. */
export type PdfCropBox = Schemas["PdfCropBox"];

// ── Manipulation requests (all return PDF blob) ────────────────────────────

export type ExtractPagesRequest = Schemas["ExtractPagesRequest"];
export type CropPagesRequest = Schemas["CropPagesRequest"];
export type RotatePagesRequest = Schemas["RotatePagesRequest"];
export type DeletePagesRequest = Schemas["DeletePagesRequest"];
export type MergePdfsRequest = Schemas["MergePdfsRequest"];
export type SplitPdfRequest = Schemas["SplitPdfRequest"];

// ── Pipeline / extraction results ──────────────────────────────────────────

/** Options for `process-with-ai` and `full-pipeline` (streaming JSONL). */
export type PdfPipelineOptions = Schemas["PdfPipelineOptions"];

/**
 * NOTE (2026-07): `extract-text` / `extract-text-remote` stream NDJSON now —
 * the old blocking `PdfResult` (and its `PdfPageText` / `PdfTextBlock` /
 * `PdfTextWord` / `PdfTextChunk` / `PdfPageSpan` satellites) no longer appear
 * in the OpenAPI schema. Per-page shapes arrive as typed stream events
 * (`PdfExtractStartedData` / `PdfPageExtractedData` / `PdfExtractCompleteData`
 * from `@/types/python-generated/stream-events`), consumed via
 * `streamPdfExtractText(Remote)` in `features/pdf-extractor/service/streamPdf.ts`.
 */

/** Structured report returned by `extract-tables` (per-table bbox, header, rows, markdown). */
export type PdfTablesReport = Schemas["PdfTablesReport"];
export type PdfExtractedTable = Schemas["PdfExtractedTable"];

// ── Phase 2 — render & advanced page ops ────────────────────────────────────

export type RenderPageRequest = Schemas["RenderPageRequest"];
export type RenderAllPagesRequest = Schemas["RenderAllPagesRequest"];
export type RenderThumbnailRequest = Schemas["RenderThumbnailRequest"];
export type ReorderPagesRequest = Schemas["ReorderPagesRequest"];
export type InsertPagesRequest = Schemas["InsertPagesRequest"];
export type DuplicatePagesRequest = Schemas["DuplicatePagesRequest"];
export type StudioRenderRequest = Schemas["StudioRenderRequest"];

/** Catalog returned by `GET /utilities/pdf/studio/presets`. */
export type PdfStudioCatalog = Schemas["PdfStudioCatalog"];
export type PdfStudioCategorySchema = Schemas["PdfStudioCategorySchema"];
export type PdfStudioPresetSchema = Schemas["PdfStudioPresetSchema"];
export type PdfStudioBundleSchema = Schemas["PdfStudioBundleSchema"];

// ── Phase 3 — layout analysis ───────────────────────────────────────────────

export type DetectRepeatedRegionsRequest =
  Schemas["DetectRepeatedRegionsRequest"];
export type StripRepeatedRegionsRequest =
  Schemas["StripRepeatedRegionsRequest"];
export type ClassifyPagesRequest = Schemas["ClassifyPagesRequest"];
export type ExtractReadingOrderRequest = Schemas["ExtractReadingOrderRequest"];

export type RepeatedRegion = Schemas["RepeatedRegion"];
export type RepeatedRegionBbox = Schemas["RepeatedRegionBbox"];
export type RepeatedRegionsReport = Schemas["RepeatedRegionsReport"];
export type StripRepeatedRegionsResultSchema =
  Schemas["StripRepeatedRegionsResultSchema"];

export type PageClassification = Schemas["PageClassification"];
export type LayoutClassificationReport = Schemas["LayoutClassificationReport"];

export type ReadingOrderBlock = Schemas["ReadingOrderBlock"];
export type ReadingOrderPage = Schemas["ReadingOrderPage"];
export type ReadingOrderReport = Schemas["ReadingOrderReport"];

// ── Phase 4 — redaction & privacy ───────────────────────────────────────────

export type RedactRegionsRequest = Schemas["RedactRegionsRequest"];
export type RedactPatternRequest = Schemas["RedactPatternRequest"];
export type RedactRepeatedRegionsRequest =
  Schemas["RedactRepeatedRegionsRequest"];
export type StripMetadataRequest = Schemas["StripMetadataRequest"];
export type ScrubRequest = Schemas["ScrubRequest"];
export type FlattenAnnotationsRequest = Schemas["FlattenAnnotationsRequest"];

export type RedactionRegion = Schemas["RedactionRegion"];
export type PdfRedactionPatternCatalog = Schemas["PdfRedactionPatternCatalog"];
export type PdfRedactionPatternEntry = Schemas["PdfRedactionPatternEntry"];
