import { open } from "./lib.mjs";
const OUT = process.env.WALK_OUT;
const { browser, page } = await open({ next: "/administration/intelligence/mandates/spaces.build" });
await page.waitForTimeout(6000);
await page.goto(page.url().split("#")[0] + "#bind");
await page.reload();
await page.waitForTimeout(12000);
await page.screenshot({ path: `${OUT}/admin-bind.png` });
console.log((await page.locator("body").innerText()).split("Holder").slice(0,1).join("").slice(-200));
await browser.close();
