import { open, originOf } from "./lib.mjs";
const { browser, page } = await open({ member: true, width: 1440, height: 900 });
await page.goto(`${originOf(page)}/spaces`, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(8000);
await page.getByRole("button", { name: /^New page$/ }).first().click();
await page.waitForTimeout(3000);
console.log(page.url());
console.log((await page.getByRole("dialog").allInnerTexts()).join("\n---\n"));
await page.screenshot({ path: `${process.env.S}/shots/org.png` });
await browser.close();
