import { open, newPage, act } from "./lib.mjs";
const S = process.env.S;
const { browser, page } = await open({ member: true, width: 1440, height: 900 });
const id = await newPage(page);
console.log("ID", id, page.url());
await page.waitForTimeout(2000);
await page.screenshot({ path: `${S}/shots/00-blank.png` });
console.log((await page.locator("body").innerText()).slice(0, 1500));
await act(page, async()=>{ await page.locator(".bn-editor").first().click(); await page.keyboard.type("/"); });
await page.waitForTimeout(800);
console.log("SLASH:", (await page.locator(".bn-suggestion-menu").innerText().catch(()=>"none")).replace(/\n+/g," | "));
await page.screenshot({ path: `${S}/shots/01-slash.png` });
await browser.close();
