import { start, S } from "./_h.tmp.mjs";
const { browser, page } = await start();
await page.setViewportSize({width:1440,height:1500});
await page.waitForTimeout(3000);
const db = page.locator('.bn-block-content[data-content-type="database"]').first();
await db.getByRole("button").evaluateAll(b=>b.map(x=>x.getAttribute("aria-label")||x.innerText)).then(x=>console.log("buttons:",x.join(" | ")));
await db.locator("button").nth(5).click().catch(()=>{});
await page.mouse.click(1091,507); await page.waitForTimeout(1200);
await page.screenshot({ path: `${S}/shots/19-settings.png`, clip:{x:850,y:380,width:590,height:700} });
console.log((await page.locator("[role=menu],[role=dialog],[data-radix-popper-content-wrapper]").allInnerTexts()).join("\n--\n").slice(0,800));
await browser.close();
