import { start, S } from "./_h.tmp.mjs";
const { browser, page } = await start();
await page.mouse.move(547,191); await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/shots/03a-hover.png`, clip:{x:480,y:120,width:500,height:300} });
await page.mouse.click(547,191); await page.waitForTimeout(1200);
await page.screenshot({ path: `${S}/shots/03b-click.png` });
console.log(await page.evaluate(()=>[...document.querySelectorAll("[role=dialog],[role=menu],[data-radix-popper-content-wrapper],[cmdk-root]")].map(e=>e.innerText.slice(0,200))));
await page.mouse.click(310,66); await page.waitForTimeout(1200);
await page.screenshot({ path: `${S}/shots/03c-headericon.png` });
await browser.close();
