import { start, S } from "./_h.tmp.mjs";
const { browser, page } = await start();
await page.setViewportSize({width:1440,height:1500});
await page.waitForTimeout(3000);
const db = page.locator('.bn-block-content[data-content-type="database"]').first();
await db.getByRole("button",{name:"View settings"}).click(); await page.waitForTimeout(700);
await page.getByText("Properties",{exact:true}).last().click(); await page.waitForTimeout(800);
await page.getByText(/^New property$/).first().click(); await page.waitForTimeout(1500);
await page.screenshot({ path: `${S}/shots/23-dialog.png` });
console.log(await page.evaluate(()=>[...document.querySelectorAll("[role=dialog] button,[role=dialog] input,[role=dialog] [role=combobox]")].map(b=>(b.tagName+":"+(b.getAttribute("aria-label")||b.innerText||b.placeholder||b.getAttribute("role"))).slice(0,40)).join(" | ")));
await browser.close();
