import { start, S } from "./_h.tmp.mjs";
const { browser, page } = await start();
await page.mouse.click(700,307); await page.keyboard.type("The Traveling SMM™ OS"); 
await page.waitForTimeout(5000);
await page.getByRole("button",{name:/Add cover/}).click(); await page.waitForTimeout(5000);
const reqs=[]; page.on("response",r=>{ if(r.request().method()!=="GET") reqs.push(r.status()+" "+r.url().slice(0,100)); });
await page.reload({waitUntil:"domcontentloaded"}); await page.locator(".bn-editor").first().waitFor(); await page.waitForTimeout(4000);
await page.screenshot({ path: `${S}/shots/06-afterreload.png` });
console.log(await page.title(), await page.locator("h1,[data-page-title],[contenteditable]").first().innerText().catch(()=>""));
await browser.close();
