import { start, S } from "./_h.tmp.mjs";
const { browser, page } = await start();
await page.setViewportSize({width:1440,height:1500});
await page.waitForTimeout(800);
await page.mouse.click(600,530); await page.waitForTimeout(400);
console.log("caret in:", await page.evaluate(()=>{const s=getSelection().anchorNode; if(!s) return null; const e=(s.nodeType==3?s.parentElement:s); const r=e.getBoundingClientRect(); return (e.closest("[data-content-type]")?.dataset.contentType)+" "+Math.round(r.x)+","+Math.round(r.y)}));
await page.keyboard.type("/"); await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/shots/08c.png`, clip:{x:284,y:440,width:1156,height:500} });
console.log(await page.evaluate(()=>[...document.querySelectorAll(".bn-editor [data-content-type]")].map(e=>e.dataset.contentType+":"+e.innerText.slice(0,15)).join(",")), await page.locator(".bn-suggestion-menu").count());
await page.waitForTimeout(6000);
await browser.close();
