/**
 * THE LIST — every place outside the /data screen that reads or writes the older tables
 * (`workbench.udt_dataset*` and their public doors), CUTOVER-PLAN rev 3 §1 (72 rows: F1–F30,
 * A1–A22, E1–E4, L1, D1–D15), plus the places the census itself found that the plan did not list.
 *
 * Every row says HOW it is known to be repointed — a check `census.ts` runs every time (an import
 * or call site that must be there, an older door that must NOT be there, a released tag, a live
 * read of the database) — or that it changes at the switch itself by design, or that it needs
 * nothing. Nothing here is a status someone typed: a `repointed` row whose checks fail is OPEN.
 *
 *   disposition `repointed`  → status `proven` when every proof passes, else `open`
 *   disposition `flip_time`  → status `flip_time` (repointed, archived or regenerated BY the flip;
 *                              does not block the switch). Any proof it carries must still pass.
 *   disposition `nothing`    → status `nothing` (out of scope, not the older store, or already
 *                              the replacement). Any proof it carries must still pass.
 *
 * `claims` are the runtime files (globs, per repo) this row answers for. The census scans every
 * runtime file in matrx-frontend, aidream, matrx-extend and matrx-local for older-door names (code
 * only, comments stripped); a file that names one and is claimed by no row is an UNLISTED finding,
 * and any unlisted finding keeps the switch's fact FALSE — a new integration nobody inventoried is
 * exactly the silent writer this census exists to catch.
 *
 * Lane CUTOVER-CENSUS, 2026-09-25. Edit a row only with the evidence that changed it.
 */

export type Repo = "matrx-frontend" | "aidream" | "matrx-extend" | "matrx-local";

export type Proof =
  /** `pattern` (regex, code only) appears in `file` — optionally only between `from` and `to`. */
  | { kind: "contains"; repo: Repo; file: string; pattern: string; from?: string; to?: string; says: string }
  /** `pattern` (regex, code only) appears in none of `files` (globs). */
  | { kind: "lacks"; repo: Repo; files: string[]; pattern: string; says: string }
  /** No runtime file of `repo` outside `except` (globs) matches `pattern` (regex, code only). */
  | { kind: "nowhere"; repo: Repo; pattern: string; except: string[]; says: string }
  /** No runtime file of `repo` imports a module matching `module` (regex on the import specifier). */
  | { kind: "no_importer"; repo: Repo; module: string; says: string }
  /** A release tag of `repo` contains `commit`. */
  | { kind: "released"; repo: Repo; commit: string; says: string }
  /** A live read: one row `(ok boolean, detail text)`. */
  | { kind: "db"; sql: string; says: string };

export interface Integration {
  id: string;
  repo: Repo | "database";
  what: string;
  /** CUTOVER-PLAN rev 3's "Today" column, for the record: Y / R / G / —. */
  plan: "Y" | "R" | "G" | "—" | "found";
  disposition: "repointed" | "flip_time" | "nothing";
  /** Why this disposition, in one line. */
  why: string;
  /** What the owner reads when this row is open: plain English, no paths. */
  plain: string;
  /** Who fixes it when it is open: the file(s) to change. */
  owner: string;
  claims?: Partial<Record<Repo, string[]>>;
  proofs?: Proof[];
}

/** Older-door names the scan looks for (code only). The tables, the pre-grid public doors, the
 *  older grid doors (D1) and the older change feed (F19). Workbench helpers that STAY (D3: the
 *  words resolver, access, archive/unarchive) are deliberately not here. */
export const OLDER_DOOR_PATTERN =
  "\\budt_dataset(?:s|_fields|_rows|_row_versions|_templates|_template_fields)\\b|\\b(?:" +
  [
    "_d31_impl_[a-z_]+", "add_column_to_user_table", "add_data_row_to_user_table",
    "append_rows_to_user_table", "cascade_table_security_settings", "create_new_user_table_dynamic",
    "create_user_table_with_fields", "delete_data_row_from_user_table", "delete_user_table",
    "export_user_table_as_csv", "get_full_table", "get_table_cell", "get_table_column", "get_table_row",
    "get_user_table_complete", "get_user_table_data_paginated(?:_v2)?", "get_user_tables",
    "inherit_table_security_on_insert", "list_table_columns", "list_table_rows",
    "list_udt_dataset_templates", "udt_backfill_autonumber", "udt_bulk_write", "udt_cast_jsonb_value",
    "udt_change_field_type", "udt_column_facets", "udt_delete_field", "udt_list_example_tables",
    "udt_set_field_format", "udt_set_table_row_actions", "udt_set_table_row_label", "udt_set_table_style",
    "udt_table_profile", "udt_upsert_cell", "udt_upsert_row", "udt_validate_cell_rules", "udt_validate_row",
    "update_data_row_in_user_table", "update_field_metadata", "update_user_table_[a-z_]+",
    "udt_row_change_events",
  ].join("|") +
  ")\\b";

const exists = (schema: string, fn: string) =>
  `select exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                   where n.nspname = '${schema}' and p.proname = '${fn}') as ok,
          '${schema}.${fn} is live on this database' as detail`;

/** The seam and the /data screen: allowed to name older doors (CUTOVER-PLAN §2 Step 7's allow-list). */
export const ALLOWED: Array<{ repo: Repo; claims: string[]; why: string }> = [
  {
    repo: "matrx-frontend",
    claims: [
      "app/(core)/data/**",
      "components/user-generated-table-data/**",
      "features/data-tables/**",
    ],
    why: "the /data screen and the seam (features/data-tables/service.ts + data-source/*), GRID-PORT's, retired at the archive",
  },
  {
    repo: "aidream",
    claims: ["packages/matrx-records/matrx_records/server/table_home.py"],
    why: "the server's one where-does-this-table-live helper (CUTOVER-PLAN §2 Step 1)",
  },
];

/** Files that match a door NAME but are not the older store (recorded so nobody re-finds them). */
export const NOT_THE_OLDER_STORE: Array<{ repo: Repo; claims: string[]; why: string }> = [
  {
    repo: "aidream",
    claims: [
      "aidream/api/routers/vault.py",
      "aidream/services/user_secrets/vault.py",
      "packages/matrx-orm/matrx_orm/secrets_battery/**",
    ],
    why: "the Vault's own `update_field_metadata` (a secret item's field), not the older tables' door",
  },
];

export const INTEGRATIONS: Integration[] = [
  // ── 1.1 matrx-frontend ────────────────────────────────────────────────────────────────────────
  {
    id: "F1", repo: "matrx-frontend", plan: "G", disposition: "repointed",
    what: "Every table picker (schedule form, agent resources, zip heatmap, append/save dialogs) lists both stores",
    why: "INTEG-CLIENTS: service.listTablesEverywhere over custom.table_list_everywhere (G9)",
    plain: "some table pickers still list only the older tables, so a copied table vanishes from them after the switch",
    owner: "matrx-frontend features/data-tables/service.ts (listTablesEverywhere) and each picker",
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/data-tables/service.ts", pattern: "table_list_everywhere", says: "the seam asks the one both-stores list" },
      ...[
        "features/scheduling/components/form/triggers/EventForm.tsx",
        "features/resource-manager/resource-picker/TablesResourcePicker.tsx",
        "app/(public)/free/zip-code-heatmap/components/TableDataSource.tsx",
        "components/mardown-display/blocks/json/AppendToTableDialog.tsx",
        "components/mardown-display/tables/SaveTableModal.tsx",
      ].map((file) => ({ kind: "contains" as const, repo: "matrx-frontend" as const, file, pattern: "listTablesEverywhere", says: `${file.split("/").pop()} lists both stores` })),
      { kind: "db", sql: exists("custom", "table_list_everywhere"), says: "the both-stores list door is live" },
    ],
  },
  {
    id: "F2", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Quick Data sheet lists both stores and opens a table where it lives",
    why: "INTEG-CLIENTS c046d8d7d7",
    plain: "the Quick Data window still reads only the older tables",
    owner: "matrx-frontend features/quick-actions/components/QuickDataSheet.tsx",
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/quick-actions/components/QuickDataSheet.tsx", pattern: "listTablesEverywhere", says: "lists both stores" },
      { kind: "contains", repo: "matrx-frontend", file: "features/quick-actions/components/QuickDataSheet.tsx", pattern: "LocatedTableViewer", says: "opens through the locating viewer" },
      { kind: "lacks", repo: "matrx-frontend", files: ["features/quick-actions/**"], pattern: OLDER_DOOR_PATTERN, says: "names no older door" },
    ],
  },
  {
    id: "F3", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Viewer hosts (window, modal, chat block, canvas, tool result) locate a table before mounting the grid",
    why: "INTEG-CLIENTS: LocatedTableViewer",
    plain: "a window, chat block or canvas still opens a copied table's older copy",
    owner: "matrx-frontend features/data-tables/components/LocatedTableViewer.tsx and each host",
    claims: {
      "matrx-frontend": [
        "features/window-panels/windows/UserTableWindow.tsx",
        "features/canvas/artifact-types/renderers/TableArtifact.tsx",
        "features/tool-call-visualization/**",
      ],
    },
    proofs: [
      {
        kind: "nowhere", repo: "matrx-frontend",
        pattern: "(?:from\\s*|import\\(\\s*)[\"'][^\"']*user-generated-table-data/UserTableViewer[\"']",
        except: ["components/user-generated-table-data/**", "app/(core)/data/**", "app/(dev)/**", "features/data-tables/components/LocatedTableViewer.tsx", "features/data-tables/components/SheetLayout.tsx"],
        says: "no host mounts the older grid by id without locating the table",
      },
      ...[
        "features/window-panels/windows/UserTableWindow.tsx",
        "components/mardown-display/tables/ViewTableModal.tsx",
        "features/canvas/artifact-types/renderers/TableArtifact.tsx",
        "features/tool-call-visualization/renderers/dataset/DatasetOverlay.tsx",
      ].map((file) => ({ kind: "contains" as const, repo: "matrx-frontend" as const, file, pattern: "LocatedTableViewer", says: `${file.split("/").pop()} mounts the locating viewer` })),
      { kind: "lacks", repo: "matrx-frontend", files: ["features/window-panels/windows/UserTableWindow.tsx"], pattern: "\\.from\\(\\s*[\"']udt_datasets", says: "the window no longer reads its title from the older table" },
    ],
  },
  {
    id: "F4", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Table births outside the grid (save from chat, JSON, zip heatmap, page extraction, function registry)",
    why: "INTEG-CLIENTS 66718c6afe: one birth, service.createTable, by where the organization keeps tables",
    plain: "saving something as a new table still creates it in the older tables",
    owner: "matrx-frontend features/data-tables/service.ts createTable",
    claims: { "matrx-frontend": ["utils/user-table-utls/**", "features/page-extraction/data-review/export-targets.ts"] },
    proofs: [
      {
        kind: "nowhere", repo: "matrx-frontend",
        pattern: "import\\s+\\{[^}]*\\b(?:createTable|addRow|addColumn|getTableDetails)\\b[^}]*\\}\\s*from\\s*[\"'][^\"']*user-table-utls/table-utils[\"']",
        except: ["features/data-tables/service.ts", "utils/user-table-utls/table-utils.ts", "components/user-generated-table-data/**", "app/(dev)/**"],
        says: "no runtime file imports an older birth or write door from table-utils",
      },
      {
        kind: "nowhere", repo: "matrx-frontend",
        pattern: "\\.rpc\\(\\s*[\"'`](?:create_new_user_table_dynamic|create_user_table_with_fields|add_data_row_to_user_table|append_rows_to_user_table|add_column_to_user_table)[\"'`]",
        except: ["features/data-tables/service.ts", "features/data-tables/data-source/**", "utils/user-table-utls/table-utils.ts", "components/user-generated-table-data/**", "app/(dev)/**"],
        says: "no runtime file calls an older birth door by name",
      },
    ],
  },
  {
    id: "F5", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Births from a CSV block, a canvas table, the content-IR studio",
    why: "INTEG-CLIENTS: create-dataset-from-table goes through service.createTable",
    plain: "saving a CSV or a canvas table still creates it in the older tables",
    owner: "matrx-frontend features/data-tables/create-dataset-from-table.ts",
    claims: { "matrx-frontend": ["components/mardown-display/blocks/csv/CsvBlock.tsx"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/data-tables/create-dataset-from-table.ts", pattern: "createTable", says: "births through the seam" },
      { kind: "lacks", repo: "matrx-frontend", files: ["features/data-tables/create-dataset-from-table.ts", "components/mardown-display/blocks/csv/CsvBlock.tsx"], pattern: "\\.rpc\\(|\\.from\\(\\s*[\"']udt_", says: "reaches no older door itself" },
    ],
  },
  {
    id: "F6", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Append / merge rows into an existing table from chat",
    why: "INTEG-CLIENTS: locateTable, then service.bulkWrite",
    plain: "adding rows from a chat answer still writes the older table",
    owner: "matrx-frontend features/data-tables/save-to-table.ts",
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/data-tables/save-to-table.ts", pattern: "locateTable\\(", says: "locates the table before writing" },
      { kind: "lacks", repo: "matrx-frontend", files: ["features/data-tables/save-to-table.ts", "components/mardown-display/blocks/json/AppendToTableDialog.tsx"], pattern: "\\.rpc\\(\\s*[\"'`]udt_bulk_write", says: "no direct older bulk write" },
    ],
  },
  {
    id: "F7", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Full table read used by the agent-resources picker and grid modals",
    why: "INTEG-CLIENTS 77001785e9: reads through the seam; utils/user-tables-rpc.ts is only response unwrappers",
    plain: "the agent-resources picker still reads whole tables from the older store",
    owner: "matrx-frontend features/resource-manager/resource-picker/TablesResourcePicker.tsx",
    claims: { "matrx-frontend": ["utils/user-tables-rpc.ts"] },
    proofs: [
      {
        kind: "nowhere", repo: "matrx-frontend",
        pattern: "\\.rpc\\(\\s*[\"'`](?:get_user_table_complete|get_user_table_data_paginated(?:_v2)?|get_full_table|get_user_tables)[\"'`]",
        except: ["features/data-tables/service.ts", "features/data-tables/data-source/**", "utils/user-table-utls/table-utils.ts", "components/user-generated-table-data/**", "app/(core)/data/**", "app/(dev)/**", "features/matrx-envelope/referenceResolvers.ts"],
        says: "no runtime file outside the seam calls an older read door",
      },
    ],
  },
  {
    id: "F8", repo: "matrx-frontend", plan: "Y", disposition: "repointed",
    what: "An agent's proposed list edit, applied on approval",
    why: "already the seam (service.bulkWrite); INTEG-CLIENTS 0a15e8fab0 proved it on a moved scope table",
    plain: "accepting an agent's proposed list change still writes the older table",
    owner: "matrx-frontend features/list-change-proposals/applyListChange.ts",
    claims: { "matrx-frontend": ["features/list-change-proposals/**", "features/content-ir/kinds/list-change-proposal.ts"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/list-change-proposals/applyListChange.ts", pattern: "bulkWrite", says: "writes through the seam" },
      { kind: "lacks", repo: "matrx-frontend", files: ["features/list-change-proposals/**"], pattern: "\\.rpc\\(\\s*[\"'`]udt_", says: "no direct older door" },
    ],
  },
  {
    id: "F9", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "The \"when a row changes, run an agent\" form",
    why: "INTEG-CLIENTS efe6e399ff: rowChangeScheduleFor; G8 on production 2026-09-25 00:22 UTC",
    plain: "the schedule form still builds row-change automations only for older tables",
    owner: "matrx-frontend features/scheduling/components/form/triggers/EventForm.tsx",
    claims: { "matrx-frontend": ["features/scheduling/components/form/triggers/EventForm.tsx"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/scheduling/components/form/triggers/EventForm.tsx", pattern: "rowChangeScheduleFor", says: "asks the table its change word" },
      { kind: "db", sql: "select exists (select 1 from public._schema_migrations where filename = 'gridprim_a_row_change_runs_the_agent_in_either_store.sql') as ok, 'G8 (a row change runs the agent in either store) is applied here' as detail", says: "G8 is applied" },
    ],
  },
  {
    id: "F10", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "@table / @table_row / @table_cell references in prompts",
    why: "INTEG-CLIENTS 7b8b3f8b61: the store answers first; the older arm only for tables it does not hold",
    plain: "a table reference in a prompt still reads the older copy",
    owner: "matrx-frontend features/matrx-envelope/referenceResolvers.ts",
    claims: { "matrx-frontend": ["features/matrx-envelope/referenceResolvers.ts"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/matrx-envelope/referenceResolvers.ts", pattern: "locateTable", says: "locates the table first" },
    ],
  },
  {
    id: "F11", repo: "matrx-frontend", plan: "G", disposition: "repointed",
    what: "Scope datasets provisioned from a template",
    why: "INTEG-CLIENTS 8f84843995 on GRID-PRIMITIVES G11 (custom.scope_table_provision)",
    plain: "a scope still makes its table in the older store",
    owner: "matrx-frontend features/scopes/service/scopesService.ts",
    claims: { "matrx-frontend": ["features/scopes/service/scopesService.ts"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/scopes/service/scopesService.ts", pattern: "scope_table_provision", says: "provisions in the store" },
      { kind: "db", sql: exists("custom", "scope_table_provision"), says: "G11 is live" },
    ],
  },
  {
    id: "F12", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "The organization's Tables page and table peeks",
    why: "INTEG-CLIENTS 8f84843995: both stores; the peek locates",
    plain: "the organization's Tables page still lists only older tables",
    owner: "matrx-frontend app/(core)/organizations/[orgId]/tables/page.tsx",
    claims: { "matrx-frontend": ["app/(core)/organizations/[orgId]/tables/page.tsx", "features/organizations/**"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "app/(core)/organizations/[orgId]/tables/page.tsx", pattern: "table_list_everywhere", says: "the page lists both stores" },
      { kind: "contains", repo: "matrx-frontend", file: "features/organizations/peek/kinds/DatasetPeek.tsx", pattern: "locateTable", says: "the peek locates" },
    ],
  },
  {
    id: "F13", repo: "matrx-frontend", plan: "R", disposition: "flip_time",
    what: "Entity registries naming udt_datasets (open, peek, share, icon, noun)",
    why: "the plan drops the dataset entries at the flip, keeping document/workbook/list entries",
    plain: "", owner: "matrx-frontend registries (at the flip)",
    claims: {
      "matrx-frontend": [
        "features/item-presentation/**", "utils/permissions/registry.ts", "features/sharing/resourceIcons.ts",
        "features/matrx-envelope/catalog-nouns.generated.ts", "features/canvas/services/canvasArtifactService.ts",
      ],
    },
  },
  {
    id: "F14", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "The \"shared with you\" email names the table",
    why: "INTEG-CLIENTS 62aa485999: the store answers first; the old emailService has no importer",
    plain: "a share email still names a table from the older store only",
    owner: "matrx-frontend features/sharing/service/sharedResourceDetails.ts",
    claims: { "matrx-frontend": ["features/sharing/service/sharedResourceDetails.ts", "features/sharing/emailService.ts"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/sharing/service/sharedResourceDetails.ts", pattern: "sharedStoreItem", says: "the store answers first" },
      { kind: "no_importer", repo: "matrx-frontend", module: "features/sharing/emailService$", says: "the older-only emailService is reached by nothing" },
    ],
  },
  {
    id: "F15", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "What an agent on the table screen is told and may write",
    why: "INTEG-CLIENTS 8f84843995: seam only; guard the-table-surface-writes-only-through-the-seam",
    plain: "an agent on the table screen is still told to write the older doors",
    owner: "matrx-frontend features/surfaces/manifests/data-tables.manifest.ts",
    claims: { "matrx-frontend": ["features/surfaces/manifests/data-tables.manifest.ts", "features/surfaces/manifests/quick-data.manifest.ts"] },
    proofs: [
      { kind: "lacks", repo: "matrx-frontend", files: ["features/surfaces/manifests/data-tables.manifest.ts", "features/surfaces/manifests/quick-data.manifest.ts", "features/data-tables/agent-context/**"], pattern: OLDER_DOOR_PATTERN, says: "names no older door in code (only in comments)" },
    ],
  },
  {
    id: "F16", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "\"Send to a table\" menu entries from chat, documents, extraction",
    why: "land in F4 / F6",
    plain: "a send-to-table menu entry still writes the older tables",
    owner: "matrx-frontend (follows F4 / F6)",
    claims: { "matrx-frontend": ["features/page-extraction/data-review/SendToMenu.tsx"] },
    proofs: [
      { kind: "lacks", repo: "matrx-frontend", files: ["features/page-extraction/data-review/SendToMenu.tsx", "components/agent-copy/alchemy-destinations.ts", "features/rich-document/actions/handlers/save.ts"], pattern: "\\.rpc\\(|\\.from\\(\\s*[\"']udt_", says: "reaches no older door itself" },
    ],
  },
  {
    id: "F17", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Public zip-code heatmap tool",
    why: "F1 + F4",
    plain: "the public zip-code heatmap still reads or saves older tables",
    owner: "matrx-frontend app/(public)/free/zip-code-heatmap",
    proofs: [
      { kind: "lacks", repo: "matrx-frontend", files: ["app/(public)/free/zip-code-heatmap/**"], pattern: OLDER_DOOR_PATTERN, says: "names no older door" },
    ],
  },
  {
    id: "F18", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Choice options editor",
    why: "INTEG-CLIENTS 8f84843995: suggestions through the seam",
    plain: "the choice editor still reads the older tables' facets",
    owner: "matrx-frontend lib/field-formats/ChoiceOptionsEditor.tsx",
    claims: { "matrx-frontend": ["lib/field-formats/**"] },
    proofs: [
      { kind: "lacks", repo: "matrx-frontend", files: ["lib/field-formats/**"], pattern: OLDER_DOOR_PATTERN, says: "names no older door in code" },
    ],
  },
  {
    id: "F19", repo: "matrx-frontend", plan: "R", disposition: "repointed",
    what: "Outbound webhooks on a table's changes",
    why: "INTEG-CLIENTS 8f84843995: store-table webhook (G4); older row.* labelled",
    plain: "a table webhook still listens only to older row events",
    owner: "matrx-frontend features/files/webhooks",
    claims: { "matrx-frontend": ["features/files/webhooks/**"] },
    proofs: [
      { kind: "contains", repo: "matrx-frontend", file: "features/files/webhooks/service.ts", pattern: "table_webhook_declare", says: "declares a store-table webhook" },
      { kind: "db", sql: exists("custom", "table_webhook_declare"), says: "G4 is live" },
    ],
  },
  {
    id: "F20", repo: "matrx-frontend", plan: "Y", disposition: "nothing",
    what: "The switch itself: where a table lives, the D3 value, the moved-tables knob",
    why: "stays through the flip; collapses to the store after",
    plain: "", owner: "—",
    claims: { "matrx-frontend": ["features/unified-data/whereThisTableLives.ts", "lib/knobs/unifiedDataCampaign.register.ts"] },
  },
  {
    id: "F21", repo: "matrx-frontend", plan: "—", disposition: "nothing",
    what: "Dev demo of templates + viewer", why: "dev only (app/(dev)); retires with F4's older doors",
    plain: "", owner: "—", claims: { "matrx-frontend": ["app/(dev)/**"] },
  },
  {
    id: "F22", repo: "matrx-frontend", plan: "—", disposition: "nothing",
    what: "CMS collections reuse the facet SHAPE", why: "census false positive; no older-store read",
    plain: "", owner: "—",
    claims: { "matrx-frontend": ["app/api/cms/collections/route.ts", "features/cms/services/cmsService.ts", "app/(core)/cms/**"] },
  },
  { id: "F23", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "Mandates console's udt_name (a catalogue column)", why: "not the store", plain: "", owner: "—" },
  { id: "F24", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "platform.saved_view for MatrxDataTable / CRM", why: "not the older store", plain: "", owner: "—" },
  { id: "F25", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "Documents (udt_documents)", why: "OUT of scope", plain: "", owner: "—" },
  {
    id: "F26", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "Workbooks (udt_workbooks)", why: "OUT of scope",
    plain: "", owner: "—", claims: { "matrx-frontend": ["components/mardown-display/tables/SendToWorkbookButton.tsx"] },
  },
  { id: "F27", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "Lists (udt_structured_lists)", why: "OUT of scope", plain: "", owner: "—" },
  { id: "F28", repo: "matrx-frontend", plan: "R", disposition: "flip_time", what: "Seeds and guards aimed at the older store (scripts/)", why: "retired or re-aimed at the flip; scripts are not runtime", plain: "", owner: "matrx-frontend scripts (at the flip)" },
  { id: "F29", repo: "matrx-frontend", plan: "R", disposition: "flip_time", what: "Generated types (types/database.types.ts, python-generated)", why: "regenerated after the flip", plain: "", owner: "matrx-frontend pnpm db-types (at the flip)" },
  { id: "F30", repo: "matrx-frontend", plan: "—", disposition: "nothing", what: "Migration history", why: "history is never edited", plain: "", owner: "—" },

  // ── 1.2 aidream ───────────────────────────────────────────────────────────────────────────────
  {
    id: "A1", repo: "aidream", plan: "R", disposition: "repointed",
    what: "The agents' `dataset` tool (list / get / search / create / add_rows / update_row / delete_row)",
    why: "INTEG-SERVER 11c39cdcf7 / 65df503f9b: dispatches by table_home through the host-wired store arm",
    plain: "the agents' dataset tool still reads and writes the older tables",
    owner: "aidream packages/matrx-ai/matrx_ai/tools/implementations/datasets_tools.py",
    claims: { aidream: ["packages/matrx-ai/matrx_ai/tools/implementations/datasets_tools.py"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "packages/matrx-ai/matrx_ai/tools/implementations/datasets_tools.py", pattern: "_store_arm\\(\\)", says: "the tool asks the store arm" },
      { kind: "contains", repo: "aidream", file: "aidream/package_integration.py", pattern: "dataset_store_arm\\s*=", says: "the server wires the store arm" },
    ],
  },
  {
    id: "A2", repo: "aidream", plan: "R", disposition: "repointed",
    what: "Workflow steps \"look up a row\" / \"save a row\"",
    why: "INTEG-SERVER 11d9bbb891: route by id through table_home",
    plain: "the workflow steps that look up or save a row still use the older tables",
    owner: "aidream aidream/graph_actions/data_table.py",
    claims: { aidream: ["aidream/graph_actions/data_table.py", "aidream/graph_actions/records.py"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "aidream/graph_actions/data_table.py", pattern: "table_home", says: "routes by table id" },
    ],
  },
  {
    id: "A3", repo: "aidream", plan: "G", disposition: "repointed",
    what: "Google Sheets import",
    why: "INTEG-SERVER c9e60ca156 on G10 (custom.table_sync)",
    plain: "a Google Sheets import still creates an older table",
    owner: "aidream aidream/services/google_sync/records.py",
    claims: { aidream: ["aidream/services/google_sync/**"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "aidream/services/google_sync/records.py", pattern: "organization_is_moved", says: "a moved organization imports into the store" },
      { kind: "db", sql: exists("custom", "table_sync"), says: "G10 is live" },
    ],
  },
  {
    id: "A4", repo: "aidream", plan: "—", disposition: "flip_time",
    what: "REST /datasets (13 routes), no caller in any client", why: "retired at the archive (answers 410)",
    plain: "", owner: "aidream api/routers/datasets.py (at the archive)",
    claims: { aidream: ["aidream/api/routers/datasets.py", "aidream/services/datasets/**"] },
    proofs: [
      { kind: "nowhere", repo: "matrx-frontend", pattern: "[\"'`]/(?:api/)?datasets(?:/|[\"'`?])", except: [], says: "no web-app caller" },
      { kind: "nowhere", repo: "matrx-extend", pattern: "[\"'`]/(?:api/)?datasets(?:/|[\"'`?])", except: [], says: "no extension caller" },
    ],
  },
  {
    id: "A5", repo: "aidream", plan: "R", disposition: "flip_time",
    what: "Raw SQL layer under A1 / A4 (user_data/*)", why: "the older arm of A1 until the archive; retired with A1/A4",
    plain: "", owner: "aidream user_data (at the archive)", claims: { aidream: ["user_data/**", "config/sql_queries/**"] },
  },
  {
    id: "A6", repo: "aidream", plan: "R", disposition: "repointed",
    what: "Server-side table references in prompts (@table_cell etc.)",
    why: "INTEG-SERVER f14dd94ffe: by id under the reader's principal",
    plain: "a table reference resolved on the server still reads the older copy",
    owner: "aidream aidream/services/references/resolvers.py",
    claims: { aidream: ["aidream/services/references/**"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "aidream/services/references/resolvers.py", pattern: "table_home", says: "resolves by table home" },
    ],
  },
  {
    id: "A7", repo: "aidream", plan: "Y", disposition: "nothing",
    what: "The one relation-words resolver, dispatching by store", why: "already dispatches; the older arm serves archived rows only",
    plain: "", owner: "—", claims: { aidream: ["packages/matrx-records/matrx_records/store/relation_words.py", "packages/matrx-ai/matrx_ai/tools/relation_words.py"] },
  },
  {
    id: "A8", repo: "aidream", plan: "R", disposition: "repointed",
    what: "The agent `data` tool's `dataset` resource",
    why: "INTEG-SERVER 1e880f9e68: dataset_tables hands a store table to the store",
    plain: "the agent data tool still lists and edits tables in the older store only",
    owner: "aidream aidream/services/agent_data/dataset_tables.py",
    claims: { aidream: ["aidream/services/agent_data/**"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "aidream/services/agent_data/writes.py", pattern: "dataset_tables", says: "the writes hand datasets to the store-aware module" },
      { kind: "contains", repo: "aidream", file: "aidream/services/agent_data/dataset_tables.py", pattern: "table_home", says: "per id, asks where it lives" },
    ],
  },
  {
    id: "A9", repo: "aidream", plan: "R", disposition: "nothing",
    what: "matrx-ai content-type adapter for datasets", why: "INTEG-SERVER: zero callers; retired with A5",
    plain: "the old dataset content adapter is called again by something",
    owner: "aidream packages/matrx-ai/matrx_ai/db/content_types/datasets.py",
    claims: { aidream: ["packages/matrx-ai/matrx_ai/db/content_types/datasets.py"] },
    proofs: [{ kind: "no_importer", repo: "aidream", module: "content_types[./]datasets$", says: "nothing imports it" }],
  },
  {
    id: "A10", repo: "aidream", plan: "R", disposition: "flip_time",
    what: "Boot schema guard naming every udt_* table", why: "its expectation changes in the same commit as the read-only step",
    plain: "", owner: "aidream startup/schema_check.py (at the flip)",
    claims: { aidream: ["aidream/startup/schema_check.py", "packages/matrx-ai/matrx_ai/db/db_requirements.py"] },
  },
  {
    id: "A11", repo: "aidream", plan: "—", disposition: "flip_time",
    what: "Generated ORM (models, managers, auto-config)", why: "regenerated; models stay (read-only tables still exist)",
    plain: "", owner: "aidream db/generate.py (at the flip)",
    claims: { aidream: ["db/models/**", "db/managers/workbench/**", "db/helpers/**", "db/expected_schema.json"] },
  },
  {
    id: "A12", repo: "aidream", plan: "G", disposition: "repointed",
    what: "The mover carries shares and saved views",
    why: "attributes.py _carry_shares / _carry_saved_views; D9 / D10 measure the result",
    plain: "copying a table still leaves its shares or saved views behind",
    owner: "aidream packages/matrx-records/matrx_records/movers/attributes.py",
    claims: { aidream: ["packages/matrx-records/matrx_records/movers/**"] },
    proofs: [
      { kind: "contains", repo: "aidream", file: "packages/matrx-records/matrx_records/movers/attributes.py", pattern: "async def _carry_shares", says: "the mover carries shares" },
      { kind: "contains", repo: "aidream", file: "packages/matrx-records/matrx_records/movers/attributes.py", pattern: "async def _carry_saved_views", says: "the mover carries saved views" },
    ],
  },
  {
    id: "A13", repo: "aidream", plan: "R", disposition: "repointed",
    what: "Campaign entry-point register", why: "INTEG-SERVER: A2 reason rewritten, suites registered",
    plain: "the server's campaign register still describes the workflow steps as routed by name",
    owner: "aidream aidream/services/unified_data_campaign/register.py",
    claims: { aidream: ["aidream/services/unified_data_campaign/**"] },
    proofs: [{ kind: "contains", repo: "aidream", file: "aidream/services/unified_data_campaign/register.py", pattern: "graph_actions/data_table\\.py", says: "A2 is registered" }],
  },
  {
    id: "A14", repo: "aidream", plan: "Y", disposition: "nothing",
    what: "The TS records client (door list, words arm)", why: "already the replacement",
    plain: "", owner: "—", claims: { aidream: ["apps/shared/records/**"] },
  },
  {
    id: "A15", repo: "aidream", plan: "—", disposition: "flip_time",
    what: "Shared types naming udt (design-system, associations, dashboard types)", why: "regenerated",
    plain: "", owner: "aidream apps/shared (at the flip)",
    claims: { aidream: ["apps/shared/design-system/**", "apps/shared/associations/**", "apps/dashboard/src/types/**"] },
  },
  { id: "A16", repo: "aidream", plan: "—", disposition: "nothing", what: "Picklists", why: "OUT of scope", plain: "", owner: "—" },
  { id: "A17", repo: "aidream", plan: "—", disposition: "nothing", what: "Documents / workbooks (udt_content)", why: "OUT of scope", plain: "", owner: "—" },
  { id: "A18", repo: "aidream", plan: "—", disposition: "nothing", what: "Dashboard saved views", why: "not the older store", plain: "", owner: "—" },
  { id: "A19", repo: "aidream", plan: "—", disposition: "nothing", what: "ORM tooling naming pg_stat_user_tables", why: "false positive", plain: "", owner: "—" },
  { id: "A20", repo: "aidream", plan: "R", disposition: "flip_time", what: "Guards whose baselines list udt paths (scripts/)", why: "re-baselined after the flip", plain: "", owner: "aidream scripts (at the flip)" },
  { id: "A21", repo: "aidream", plan: "Y", disposition: "nothing", what: "Relation-words seam wiring", why: "stays", plain: "", owner: "—" },
  {
    id: "A22", repo: "aidream", plan: "R", disposition: "flip_time",
    what: "Managers for the outside foreign keys", why: "follow D7",
    plain: "", owner: "aidream db/managers (follows D7)",
    claims: { aidream: ["db/managers/context/scope_dataset_instances.py", "db/managers/extend/wbx_pattern.py", "db/managers/platform/custom_field_definition.py"] },
  },

  // ── 1.3 matrx-extend ──────────────────────────────────────────────────────────────────────────
  {
    id: "E1", repo: "matrx-extend", plan: "R", disposition: "repointed",
    what: "The extension creates tables and appends scraped rows",
    why: "INTEG-CLIENTS 6caf145: records/tables.ts; released in v0.2.32+",
    plain: "the browser extension still creates tables and appends rows in the older store",
    owner: "matrx-extend src/lib/supabase/user-tables.ts + src/lib/records/tables.ts",
    claims: { "matrx-extend": ["src/lib/supabase/user-tables.ts", "src/lib/records/tables.ts", "src/hooks/use-user-tables.ts"] },
    proofs: [
      { kind: "contains", repo: "matrx-extend", file: "src/lib/supabase/user-tables.ts", pattern: "tablesLiveIn", says: "births by where the organization keeps tables" },
      { kind: "contains", repo: "matrx-extend", file: "src/lib/supabase/user-tables.ts", pattern: "appendStoreRows", says: "appends into the store" },
      { kind: "released", repo: "matrx-extend", commit: "6caf145", says: "the repoint is in a released version" },
    ],
  },
  {
    id: "E2", repo: "matrx-extend", plan: "R", disposition: "repointed",
    what: "Saved browser patterns write into their target table",
    why: "INTEG-CLIENTS: SaveAsPattern appends by home; the foreign key swap is D7 (at the flip)",
    plain: "a saved browser pattern still writes into the older table",
    owner: "matrx-extend src/features/showcase/components/SaveAsPattern.tsx",
    proofs: [
      { kind: "contains", repo: "matrx-extend", file: "src/features/showcase/components/SaveAsPattern.tsx", pattern: "lib/supabase/user-tables", says: "writes through the dispatching module" },
    ],
  },
  {
    id: "E3", repo: "matrx-extend", plan: "R", disposition: "repointed",
    what: "Error words and schema routing", why: "INTEG-CLIENTS: store refusals keep the store's sentence",
    plain: "the extension's error words still name only the older doors",
    owner: "matrx-extend src/lib/supabase/db-failure.ts",
    claims: { "matrx-extend": ["src/lib/supabase/db-failure.ts", "src/lib/supabase/schemas.ts"] },
    proofs: [{ kind: "contains", repo: "matrx-extend", file: "src/lib/supabase/db-failure.ts", pattern: "record_write_many|table_declare", says: "store refusals are named" }],
  },
  { id: "E4", repo: "matrx-extend", plan: "—", disposition: "flip_time", what: "/datasets REST types", why: "regenerated with A4", plain: "", owner: "matrx-extend types (at the archive)" },

  // ── 1.4 matrx-local ───────────────────────────────────────────────────────────────────────────
  { id: "L1", repo: "matrx-local", plan: "—", disposition: "flip_time", what: "Schema mirror snapshot lists udt_* (none mirrored)", why: "refresh the snapshot after the flip", plain: "", owner: "matrx-local schema_mirror (at the flip)" },

  // ── 1.5 the database ──────────────────────────────────────────────────────────────────────────
  { id: "D1", repo: "database", plan: "Y", disposition: "flip_time", what: "23 older grid doors public.udt_*", why: "revoked at the read-only step", plain: "", owner: "the read-only step" },
  { id: "D2", repo: "database", plan: "R", disposition: "flip_time", what: "26 pre-grid public doors (get_user_tables …)", why: "their callers are F4/F10/E1/A1; the doors are revoked at the read-only step", plain: "", owner: "the read-only step" },
  { id: "D3", repo: "database", plan: "Y", disposition: "nothing", what: "workbench words / access / archive / unarchive", why: "kept: they serve the archived copy and ARE the switch and its undo", plain: "", owner: "—" },
  { id: "D4", repo: "database", plan: "—", disposition: "nothing", what: "Shared access / guard bodies that mention udt_*", why: "read only", plain: "", owner: "—" },
  {
    id: "D5", repo: "database", plan: "G", disposition: "repointed",
    what: "context.provision_scope_dataset", why: "follows F11 (G11)",
    plain: "scopes still provision their tables in the older store",
    owner: "matrx-frontend migrations (G11)",
    proofs: [{ kind: "db", sql: exists("custom", "scope_table_provision"), says: "G11 is live" }],
  },
  { id: "D6", repo: "database", plan: "R", disposition: "flip_time", what: "Triggers on the older tables", why: "inert once writes are refused; the refusal trigger is added at the read-only step", plain: "", owner: "the read-only step" },
  {
    id: "D7", repo: "database", plan: "R", disposition: "flip_time",
    what: "Outside foreign keys (browser patterns, scope instances)",
    why: "platform-wide constraint swap after the last organization's switch (INTEG-CLIENTS designed and proved it on the clone); writes already route by where the table lives, so nothing breaks before it",
    plain: "", owner: "the platform-wide flip step",
  },
  {
    id: "D8", repo: "database", plan: "R", disposition: "repointed",
    what: "Row-change automations watching an older table are re-keyed to the copy",
    why: "the per-organization switch must re-key every `user_table_row` schedule of the tables it archives (and back on Switch back); no press step or mover does today",
    plain: "\"when a row changes, run an agent\" automations on an older table are not moved over when the switch is pressed, so they would go silent",
    owner: "matrx-frontend migrations — platform._cutover_seam_apply (FLIP-SEAMS press step) re-keys scheduler.sch_trigger for the archived ids; undo re-keys back",
    proofs: [
      {
        kind: "db",
        sql: `select pg_get_functiondef('platform._cutover_seam_apply(text,uuid,text,uuid,uuid)'::regprocedure) ~ 'sch_trigger' as ok,
                     format('the switch''s press step %s row-change schedules; %s enabled schedule(s) watch an older table today',
                            case when pg_get_functiondef('platform._cutover_seam_apply(text,uuid,text,uuid,uuid)'::regprocedure) ~ 'sch_trigger' then 're-keys' else 'does not re-key' end,
                            (select count(*) from scheduler.sch_trigger t where t.enabled and t.deleted_at is null and t.config ->> 'entity_type' = 'user_table_row')) as detail`,
        says: "the switch re-keys row-change automations",
      },
    ],
  },
  {
    id: "D9", repo: "database", plan: "G", disposition: "repointed",
    what: "Shares of older tables carried as grants on their copies",
    why: "A12 _carry_shares; measured here",
    plain: "some people an older table was shared with cannot open its copy",
    owner: "aidream packages/matrx-records/matrx_records/movers/attributes.py (_carry_shares)",
    proofs: [{
      kind: "db",
      sql: `select count(*) = 0 as ok, format('%s active share(s) of a copied older table have no grant on the copy', count(*)) as detail
              from iam.permissions p
              join workbench.udt_datasets d on d.id = p.resource_id and d.deleted_at is null
             where p.resource_type = 'dataset' and p.status = 'active' and not coalesce(p.is_public, false)
               and exists (select 1 from custom.record r where r.organization_id = d.organization_id and r.id = d.id and r.data_class = 'table' and r.deleted_at is null)
               and not exists (select 1 from iam.permissions q where q.resource_type = 'record' and q.resource_id = p.resource_id and q.status = 'active'
                                 and q.granted_to_user_id is not distinct from p.granted_to_user_id
                                 and q.granted_to_organization_id is not distinct from p.granted_to_organization_id)`,
      says: "every share of a copied table is carried",
    }],
  },
  {
    id: "D10", repo: "database", plan: "G", disposition: "repointed",
    what: "Saved views of older tables carried into the store's views",
    why: "A12 _carry_saved_views; measured here",
    plain: "a saved view of an older table is missing from its copy",
    owner: "aidream packages/matrx-records/matrx_records/movers/attributes.py (_carry_saved_views)",
    proofs: [{
      kind: "db",
      sql: `select count(*) = 0 as ok, format('%s saved view(s) of a copied older table have no view on the copy', count(*)) as detail
              from platform.saved_view v
              join workbench.udt_datasets d on d.id = v.subject_id and d.deleted_at is null
             where v.surface_key = 'matrx-user/data-tables' and v.deleted_at is null
               and exists (select 1 from custom.record r where r.organization_id = d.organization_id and r.id = d.id and r.data_class = 'table' and r.deleted_at is null)
               and not exists (select 1 from platform.saved_view w where w.surface_key = 'custom/records' and w.subject_id = d.id and w.deleted_at is null
                                 and w.definition -> 'moved_from' ->> 'view_id' = v.id::text)`,
      says: "every saved view of a copied table is carried",
    }],
  },
  { id: "D11", repo: "database", plan: "R", disposition: "flip_time", what: "platform.client_callable_door rows naming older doors", why: "removed at the read-only step / archive", plain: "", owner: "the read-only step" },
  { id: "D12", repo: "database", plan: "R", disposition: "flip_time", what: "Weekly trim of older row history", why: "paused for the undo window", plain: "", owner: "the read-only step" },
  {
    id: "D13", repo: "database", plan: "Y", disposition: "nothing",
    what: "The switches (older_tables_moved, custom/system_enabled)", why: "the press sets older_tables_moved; exists",
    plain: "", owner: "—",
    proofs: [{ kind: "db", sql: "select exists (select 1 from platform.feature_knob where feature = 'data_tables' and key = 'older_tables_moved') as ok, 'the moved-tables knob exists' as detail", says: "the knob exists" }],
  },
  { id: "D14", repo: "database", plan: "—", disposition: "nothing", what: "Lists / Workbooks / Documents tables", why: "OUT of scope", plain: "", owner: "—" },
  { id: "D15", repo: "database", plan: "—", disposition: "nothing", what: "associations / entity_grants / share_links", why: "0 rows reference a dataset (plan census)", plain: "", owner: "—" },

  // ── found by the census (not in the plan) ─────────────────────────────────────────────────────
  {
    id: "X1", repo: "aidream", plan: "found", disposition: "repointed",
    what: "Where a COPIED but not yet switched table is written",
    why: "copy mode (owner, 2026-09-23) leaves the older table live beside its same-id copy, but every integration asks only \"does the store hold a Table with this id?\" (server table_home, the web app's whereThisTableLives, the extension's store list) — so agents, workflow steps, chat appends and the extension write the COPY while the owner still works in the older table, and the readiness check (older edits after the copy) cannot see it. The rule must be: a live older table with this id is the writer until the switch archives it",
    plain: "for a table that has been copied but not switched, agents, workflow steps, chat and the browser extension write into the copy while you are still working in the older table",
    owner: "aidream packages/matrx-records/matrx_records/server/table_home.py; matrx-frontend features/unified-data/whereThisTableLives.ts (+ data-source/locate-table.ts); matrx-extend src/lib/records/tables.ts",
    proofs: [
      {
        kind: "contains", repo: "aidream", file: "packages/matrx-records/matrx_records/server/table_home.py",
        from: "async def table_home", to: "async def organization_is_moved",
        pattern: "udt_datasets|older_tables_moved|MOVED_KNOB|cutover_seam",
        says: "the server's answer asks whether the older table is still the live one",
      },
    ],
  },
];
