/**
 * Build the `matrx-user/notes` surface scope at trigger time.
 *
 * Returns a `() => SurfaceScopePayload` builder rather than a static object,
 * because the textarea's selection lives in the DOM (not React state) and the
 * caller wants the *current* selection at the moment the user clicks an
 * action — not a stale snapshot from the last render.
 *
 * Wire-up pattern (see `NoteContextMenuContent.executeAction`):
 *
 *   const buildSurfaceScope = useNotesSurfaceScope({ ... });
 *   ...
 *   await trigger(shortcutId, {
 *     scope: buildSurfaceScope(),
 *     sourceFeature: "notes",
 *     runtime: { surfaceName: "matrx-user/notes" },
 *   });
 */

import { useCallback } from "react";
import type { RefObject } from "react";

import { useAppSelector } from "@/lib/redux/hooks";
import { createNotesScope } from "@/features/surfaces/manifests/notes-editor.manifest";
import type { SurfaceScopePayload } from "@/features/surfaces/types";
import {
  selectAllFolders,
  selectInstanceSplitNoteId,
  selectInstanceTabs,
  selectNoteById,
  selectNoteIsAutogenerated,
  selectNoteIsDirtyById,
  selectNotesMap,
} from "@/features/notes/redux/selectors";
import { formatEditorSurroundContext } from "@/utils/format-editor-surround-context";

import {
  countWords,
  findCurrentHeading,
} from "@/features/notes/utils/markdown-headings";
import type { EditorMode } from "@/features/notes/components/NoteEditorCore";

const TEXT_NEIGHBOR_CHARS = 500;

export interface UseNotesSurfaceScopeParams {
  /**
   * NotesView instance id (per-pane state, owns tabs + split note). Optional
   * for callsites outside the multi-tab Notes view (overlays, embedded
   * editors); when absent the scope reports an empty tab list and no split.
   */
  instanceId?: string;
  /** Id of the note the user has open in the active tab. */
  noteId: string;
  /** Live note body — usually the in-flight buffer (`localContent`). */
  content: string;
  /** Reference to the editor textarea — selection is read live from the DOM. */
  textareaRef: RefObject<HTMLTextAreaElement | null>;
  /** Active note's editor mode (plain / split / preview / wysiwyg / markdown-split). */
  editorMode: EditorMode;
}

/**
 * Returns a stable function that snapshots the Notes surface state and emits a
 * `SurfaceScopePayload` for `matrx-user/notes`. The function is stable across
 * renders for a given (instanceId, noteId) — the live values are pulled from
 * Redux + the textarea DOM at call time.
 */
export function useNotesSurfaceScope(
  params: UseNotesSurfaceScopeParams,
): () => SurfaceScopePayload {
  const { instanceId, noteId, content, textareaRef, editorMode } = params;

  // Empty-string sentinel for selectors when no instance is bound (overlay use).
  const instanceKey = instanceId ?? "";

  const noteRecord = useAppSelector(selectNoteById(noteId));
  const isDirty = useAppSelector(selectNoteIsDirtyById(noteId));
  const isAutogenerated = useAppSelector(selectNoteIsAutogenerated(noteId));
  const openTabs = useAppSelector(selectInstanceTabs(instanceKey));
  const splitNoteId = useAppSelector(selectInstanceSplitNoteId(instanceKey));
  const allFolders = useAppSelector(selectAllFolders);
  const notesMap = useAppSelector(selectNotesMap);

  return useCallback(() => {
    const ta = textareaRef.current;
    const text = ta?.value ?? content ?? "";
    const selectionStart = ta?.selectionStart ?? 0;
    const selectionEnd = ta?.selectionEnd ?? selectionStart;
    const hasSelection = selectionEnd > selectionStart;
    const selectedText = hasSelection
      ? text.slice(selectionStart, selectionEnd)
      : "";

    const textBefore = text.slice(
      Math.max(0, selectionStart - TEXT_NEIGHBOR_CHARS),
      selectionStart,
    );
    const textAfter = text.slice(
      selectionEnd,
      Math.min(text.length, selectionEnd + TEXT_NEIGHBOR_CHARS),
    );

    const noteOpen = Boolean(noteId);
    const activeScopeKind: "selection" | "note" | "empty" = !noteOpen
      ? "empty"
      : hasSelection
        ? "selection"
        : "note";
    const activeText = !noteOpen ? "" : hasSelection ? selectedText : text;

    const { heading, sectionText } = findCurrentHeading(text, selectionStart);

    const tabs = openTabs ?? [];
    const openNotesSummary = tabs.map((id) => {
      const rec = notesMap[id];
      return {
        id,
        title: rec?.label ?? "",
        folder: rec?.folder_name ?? "",
        updated_at: rec?.updated_at ?? "",
      };
    });

    const currentFolder = noteRecord?.folder_name ?? "";
    const folderPeers = currentFolder
      ? Object.values(notesMap)
          .filter(
            (n) =>
              !n.is_deleted &&
              n.folder_name === currentFolder &&
              n.id !== noteId,
          )
          .map((n) => n.id)
      : [];

    const surround = formatEditorSurroundContext(text, {
      selectionStart,
      selectionEnd,
    });

    return createNotesScope({
      // Required (alwaysAvailable: true)
      active_scope_kind: activeScopeKind,
      open_note_ids: tabs,
      open_notes_summary: openNotesSummary,
      all_folder_names: allFolders,
      editor_mode: editorMode,
      is_split_pane_visible: splitNoteId != null,

      // Selection / scope mirror
      selection: selectedText || undefined,
      text_before: textBefore || undefined,
      text_after: textAfter || undefined,
      content: noteOpen ? text : undefined,
      active_text: activeText || undefined,
      current_heading: heading ?? undefined,
      current_section_text: sectionText ?? undefined,
      cursor_offset: noteOpen ? selectionStart : undefined,

      // Active-note identity & metadata
      current_note_id: noteOpen ? noteId : undefined,
      current_note_title: noteRecord?.label || undefined,
      current_note_folder: noteRecord?.folder_name || undefined,
      current_note_tags: noteRecord?.tags ?? undefined,
      current_note_word_count: noteOpen ? countWords(text) : undefined,
      current_note_updated_at: noteRecord?.updated_at || undefined,
      current_note_is_dirty: noteOpen ? isDirty : undefined,

      // Workspace context
      current_folder_note_ids: folderPeers.length ? folderPeers : undefined,

      // Editor / pane state
      is_new_note: noteOpen ? isAutogenerated : undefined,
      split_note_id: splitNoteId ?? undefined,

      // Legacy escape hatch — `formatEditorSurroundContext` output, kept so
      // shortcuts wired to the old `context` key keep working.
      context: surround,
    });
  }, [
    textareaRef,
    content,
    noteId,
    editorMode,
    noteRecord,
    isDirty,
    isAutogenerated,
    openTabs,
    splitNoteId,
    allFolders,
    notesMap,
  ]);
}
