"use client";

/**
 * Opener for the `agentContentSidebarWindow` overlay.
 *
 * - `useOpenAgentContentSidebarWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<AgentContentSidebarWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "agentContentSidebarWindow" as const;

export interface OpenAgentContentSidebarWindowOptions {
  initialAgentId?: string | null;
  /** TODO: tighten to `AgentContentTab` once that type is imported. */
  initialTab?: unknown;
}

export interface AgentContentSidebarWindowHandle {
  close: () => void;
}

export function useOpenAgentContentSidebarWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenAgentContentSidebarWindowOptions = {}): AgentContentSidebarWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            initialAgentId: opts.initialAgentId,
            initialTab: opts.initialTab,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function AgentContentSidebarWindowController(props: OpenAgentContentSidebarWindowOptions): null {
  const open = useOpenAgentContentSidebarWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.initialAgentId, props.initialTab]);
  return null;
}
