"use client";

/**
 * Opener for the `agentConnectionsWindow` overlay.
 *
 * - `useOpenAgentConnectionsWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<AgentConnectionsWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "agentConnectionsWindow" as const;

export interface OpenAgentConnectionsWindowOptions {
  /** TODO: tighten to `AgentConnectionsSection` once that type is imported. */
  initialSection?: unknown;
  /** TODO: tighten to `Scope` once that type is imported. */
  initialScope?: unknown;
  initialSelectedItemId?: string | null;
}

export interface AgentConnectionsWindowHandle {
  close: () => void;
}

export function useOpenAgentConnectionsWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenAgentConnectionsWindowOptions = {}): AgentConnectionsWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            initialSection: opts.initialSection,
            initialScope: opts.initialScope,
            initialSelectedItemId: opts.initialSelectedItemId,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function AgentConnectionsWindowController(props: OpenAgentConnectionsWindowOptions): null {
  const open = useOpenAgentConnectionsWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.initialSection, props.initialScope, props.initialSelectedItemId]);
  return null;
}
