"use client";

/**
 * Opener for the `agentGateWindow` overlay.
 *
 * - `useOpenAgentGateWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<AgentGateWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "agentGateWindow" as const;

export interface OpenAgentGateWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  conversationId: string;
  /** TODO: tighten to `OverlayId` once that type is imported. */
  downstreamOverlayId?: unknown;
}

export interface AgentGateWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenAgentGateWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenAgentGateWindowOptions): AgentGateWindowHandle => {
      const instanceId = opts.instanceId ?? `agentGateWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            conversationId: opts.conversationId,
            downstreamOverlayId: opts.downstreamOverlayId,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function AgentGateWindowController(props: OpenAgentGateWindowOptions): null {
  const open = useOpenAgentGateWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.conversationId, props.downstreamOverlayId]);
  return null;
}
