"use client";

/**
 * Opener for the `canvasViewerWindow` overlay.
 *
 * - `useOpenCanvasViewerWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<CanvasViewerWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "canvasViewerWindow" as const;

export interface OpenCanvasViewerWindowOptions {
  title?: string;
  initialShareToken?: string;
}

export interface CanvasViewerWindowHandle {
  close: () => void;
}

export function useOpenCanvasViewerWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenCanvasViewerWindowOptions = {}): CanvasViewerWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            title: opts.title,
            initialShareToken: opts.initialShareToken,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function CanvasViewerWindowController(props: OpenCanvasViewerWindowOptions): null {
  const open = useOpenCanvasViewerWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.title, props.initialShareToken]);
  return null;
}
