"use client";

/**
 * Opener for the `codeWorkspaceWindow` overlay.
 *
 * - `useOpenCodeWorkspaceWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<CodeWorkspaceWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "codeWorkspaceWindow" as const;

export interface OpenCodeWorkspaceWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  windowInstanceId: string;
  title?: string | null;
  /** TODO: tighten to `FilesystemAdapter` once that type is imported. */
  adapter?: unknown;
  /** TODO: tighten to `ProcessAdapter` once that type is imported. */
  process?: unknown;
  /** TODO: tighten to `React.ReactNode` once that type is imported. */
  rightSlot?: unknown;
  /** TODO: tighten to `React.ReactNode` once that type is imported. */
  farRightSlot?: unknown;
  hideChat?: boolean;
  hideHistory?: boolean;
}

export interface CodeWorkspaceWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenCodeWorkspaceWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenCodeWorkspaceWindowOptions): CodeWorkspaceWindowHandle => {
      const instanceId = opts.instanceId ?? `codeWorkspaceWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            windowInstanceId: opts.windowInstanceId,
            title: opts.title,
            adapter: opts.adapter,
            process: opts.process,
            rightSlot: opts.rightSlot,
            farRightSlot: opts.farRightSlot,
            hideChat: opts.hideChat,
            hideHistory: opts.hideHistory,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function CodeWorkspaceWindowController(props: OpenCodeWorkspaceWindowOptions): null {
  const open = useOpenCodeWorkspaceWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.windowInstanceId, props.title, props.adapter, props.process, props.rightSlot, props.farRightSlot, props.hideChat, props.hideHistory]);
  return null;
}
