"use client";

/**
 * Opener for the `codeEditorWindow` overlay.
 *
 * - `useOpenCodeEditorWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<CodeEditorWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "codeEditorWindow" as const;

export interface OpenCodeEditorWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  windowInstanceId: string;
  /** TODO: tighten to `CodeFile[]` once that type is imported. */
  files: unknown;
  fileIds?: string[];
  activeFileId?: string;
  title?: string | null;
  /** TODO: tighten to `"on" | "off"` once that type is imported. */
  defaultWordWrap?: unknown;
  autoFormatOnOpen?: boolean;
}

export interface CodeEditorWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenCodeEditorWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenCodeEditorWindowOptions): CodeEditorWindowHandle => {
      const instanceId = opts.instanceId ?? `codeEditorWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            windowInstanceId: opts.windowInstanceId,
            files: opts.files,
            fileIds: opts.fileIds,
            activeFileId: opts.activeFileId,
            title: opts.title,
            defaultWordWrap: opts.defaultWordWrap,
            autoFormatOnOpen: opts.autoFormatOnOpen,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function CodeEditorWindowController(props: OpenCodeEditorWindowOptions): null {
  const open = useOpenCodeEditorWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.windowInstanceId, props.files, props.fileIds, props.activeFileId, props.title, props.defaultWordWrap, props.autoFormatOnOpen]);
  return null;
}
