"use client";

/**
 * Opener for the `contentEditorWindow` overlay.
 *
 * - `useOpenContentEditorWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<ContentEditorWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "contentEditorWindow" as const;

export interface OpenContentEditorWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  windowInstanceId: string;
  callbackGroupId?: string | null;
  documentId?: string;
  documentTitle?: string;
  initialValue?: string;
  title?: string | null;
}

export interface ContentEditorWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenContentEditorWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenContentEditorWindowOptions): ContentEditorWindowHandle => {
      const instanceId = opts.instanceId ?? `contentEditorWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            windowInstanceId: opts.windowInstanceId,
            callbackGroupId: opts.callbackGroupId,
            documentId: opts.documentId,
            documentTitle: opts.documentTitle,
            initialValue: opts.initialValue,
            title: opts.title,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function ContentEditorWindowController(props: OpenContentEditorWindowOptions): null {
  const open = useOpenContentEditorWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.windowInstanceId, props.callbackGroupId, props.documentId, props.documentTitle, props.initialValue, props.title]);
  return null;
}
