"use client";

/**
 * Opener for the `contentEditorListWindow` overlay.
 *
 * - `useOpenContentEditorListWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<ContentEditorListWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "contentEditorListWindow" as const;

export interface OpenContentEditorListWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  windowInstanceId: string;
  callbackGroupId?: string | null;
  /** TODO: tighten to `ContentEditorSeedDocument[]` once that type is imported. */
  documents?: unknown;
  activeDocumentId?: string | null;
  listTitle?: string | null;
  title?: string | null;
}

export interface ContentEditorListWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenContentEditorListWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenContentEditorListWindowOptions): ContentEditorListWindowHandle => {
      const instanceId = opts.instanceId ?? `contentEditorListWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            windowInstanceId: opts.windowInstanceId,
            callbackGroupId: opts.callbackGroupId,
            documents: opts.documents,
            activeDocumentId: opts.activeDocumentId,
            listTitle: opts.listTitle,
            title: opts.title,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function ContentEditorListWindowController(props: OpenContentEditorListWindowOptions): null {
  const open = useOpenContentEditorListWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.windowInstanceId, props.callbackGroupId, props.documents, props.activeDocumentId, props.listTitle, props.title]);
  return null;
}
