"use client";

/**
 * Opener for the `curatedIconPickerWindow` overlay.
 *
 * - `useOpenCuratedIconPickerWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<CuratedIconPickerWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "curatedIconPickerWindow" as const;

export interface OpenCuratedIconPickerWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  callbackGroupId?: string | null;
}

export interface CuratedIconPickerWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenCuratedIconPickerWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenCuratedIconPickerWindowOptions = {}): CuratedIconPickerWindowHandle => {
      const instanceId = opts.instanceId ?? `curatedIconPickerWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            callbackGroupId: opts.callbackGroupId,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function CuratedIconPickerWindowController(props: OpenCuratedIconPickerWindowOptions): null {
  const open = useOpenCuratedIconPickerWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.callbackGroupId]);
  return null;
}
