"use client";

/**
 * Opener for the `emailDialog` overlay.
 *
 * - `useOpenEmailDialogBridge()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<EmailDialogBridgeController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "emailDialog" as const;

export interface OpenEmailDialogBridgeOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
}

export interface EmailDialogBridgeHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenEmailDialogBridge() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenEmailDialogBridgeOptions = {}): EmailDialogBridgeHandle => {
      const instanceId = opts.instanceId ?? `emailDialog-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function EmailDialogBridgeController(props: OpenEmailDialogBridgeOptions): null {
  const open = useOpenEmailDialogBridge();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open]);
  return null;
}
