"use client";

/**
 * Opener for the `filePreviewWindow` overlay.
 *
 * - `useOpenFilePreviewWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<FilePreviewWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "filePreviewWindow" as const;
let navigationRequestSequence = 0;

export interface OpenFilePreviewWindowOptions {
  fileId?: string | null;
  /** Optional 1-based page for PDF files. Ignored by non-PDF previewers. */
  pageNumber?: number | null;
}

export interface FilePreviewWindowHandle {
  close: () => void;
}

export function useOpenFilePreviewWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenFilePreviewWindowOptions = {}): FilePreviewWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            fileId: opts.fileId ?? null,
            pageNumber: opts.pageNumber ?? null,
            // A caller may re-open the same file/page after navigating away
            // inside the existing singleton window. This makes every open
            // call an explicit navigation request, even when the public
            // options are identical to the previous call.
            navigationRequestId: ++navigationRequestSequence,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function FilePreviewWindowController(
  props: OpenFilePreviewWindowOptions,
): null {
  const open = useOpenFilePreviewWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.fileId, props.pageNumber]);
  return null;
}
