"use client";

/**
 * Opener for the `imageViewer` overlay.
 *
 * - `useOpenImageViewerWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `openImageViewer(dispatch, payload)` — the imperative dispatcher, for call
 *   sites that already hold an `AppDispatch` and open the viewer from inside a
 *   callback where a hook cannot run (mirrors `openLiveRunWindowAction`).
 * - `<ImageViewerWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";
import type { AppDispatch } from "@/lib/redux/store";

const OVERLAY_ID = "imageViewer" as const;

export interface OpenImageViewerWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  images: string[];
  initialIndex?: number;
  alts?: string[];
  title?: string;
}

export interface ImageViewerWindowHandle {
  instanceId: string;
  close: () => void;
}

/**
 * Payload for the imperative dispatcher. Same shape as the hook's options —
 * kept as its own name because the 5 call sites that use it predate the
 * openers layer and read better with a `payload` noun.
 */
export interface OpenImageViewerPayload {
  images: string[];
  initialIndex?: number;
  alts?: string[];
  title?: string;
  /** Supply a stable id when you need multiple independent viewers open at once. */
  instanceId?: string;
}

/**
 * Imperative opener — dispatches `openOverlay` and nothing else. It never
 * imports `ImageViewerWindow`, so a caller gets the open path without pulling
 * `<WindowPanel>` and the rest of the window-panels chunk graph into its
 * bundle. `OverlayController`'s per-overlay `dynamic()` still owns the only
 * import of the component itself.
 *
 * Defaults `instanceId` to `"default"` so repeat clicks reuse ONE viewer
 * instead of stacking a new window per click.
 */
export function openImageViewer(
  dispatch: AppDispatch,
  payload: OpenImageViewerPayload,
) {
  dispatch(
    openOverlay({
      overlayId: OVERLAY_ID,
      instanceId: payload.instanceId ?? "default",
      data: {
        images: payload.images,
        initialIndex: payload.initialIndex ?? 0,
        alts: payload.alts,
        title: payload.title,
      },
    }),
  );
}

export function useOpenImageViewerWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenImageViewerWindowOptions): ImageViewerWindowHandle => {
      const instanceId = opts.instanceId ?? `imageViewer-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            images: opts.images,
            initialIndex: opts.initialIndex,
            alts: opts.alts,
            title: opts.title,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function ImageViewerWindowController(props: OpenImageViewerWindowOptions): null {
  const open = useOpenImageViewerWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.images, props.initialIndex, props.alts, props.title]);
  return null;
}
