"use client";

/**
 * Opener for the `imageUploaderWindow` overlay.
 *
 * - `useOpenImageUploaderWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<ImageUploaderWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "imageUploaderWindow" as const;

export interface OpenImageUploaderWindowOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  callbackGroupId?: string | null;
  /** TODO: tighten to `AssetPreset` once that type is imported. */
  preset?: unknown;
  folder?: string;
  title?: string | null;
  description?: string | null;
  currentUrl?: string | null;
  allowUrlPaste?: boolean;
}

export interface ImageUploaderWindowHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenImageUploaderWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenImageUploaderWindowOptions = {}): ImageUploaderWindowHandle => {
      const instanceId = opts.instanceId ?? `imageUploaderWindow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            callbackGroupId: opts.callbackGroupId,
            preset: opts.preset,
            folder: opts.folder,
            title: opts.title,
            description: opts.description,
            currentUrl: opts.currentUrl,
            allowUrlPaste: opts.allowUrlPaste,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function ImageUploaderWindowController(props: OpenImageUploaderWindowOptions): null {
  const open = useOpenImageUploaderWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.callbackGroupId, props.preset, props.folder, props.title, props.description, props.currentUrl, props.allowUrlPaste]);
  return null;
}
