"use client";

/**
 * Opener for the `quickNoteSaveWindow` overlay.
 *
 * - `useOpenQuickNoteSaveWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<QuickNoteSaveWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "quickNoteSaveWindow" as const;

export interface OpenQuickNoteSaveWindowOptions {
  initialContent?: string;
  defaultFolder?: string;
  /** TODO: tighten to `EditorMode` once that type is imported. */
  initialEditorMode?: unknown;
}

export interface QuickNoteSaveWindowHandle {
  close: () => void;
}

export function useOpenQuickNoteSaveWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenQuickNoteSaveWindowOptions = {}): QuickNoteSaveWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            initialContent: opts.initialContent,
            defaultFolder: opts.defaultFolder,
            initialEditorMode: opts.initialEditorMode,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function QuickNoteSaveWindowController(props: OpenQuickNoteSaveWindowOptions): null {
  const open = useOpenQuickNoteSaveWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.initialContent, props.defaultFolder, props.initialEditorMode]);
  return null;
}
