"use client";

/**
 * Opener for the `saveToNotes` overlay.
 *
 * - `useOpenQuickNoteSaveOverlay()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<QuickNoteSaveOverlayController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "saveToNotes" as const;

export interface OpenQuickNoteSaveOverlayOptions {
  /** Optional stable instance id. Omit to spawn a fresh instance. */
  instanceId?: string;
  initialContent: string;
  defaultFolder?: string;
  title?: string;
  /** TODO: tighten to `EditorMode` once that type is imported. */
  initialEditorMode?: unknown;
  /** TODO callback — wire via callback registry in stage 3. */
  onSaved?: (...args: unknown[]) => void;
}

export interface QuickNoteSaveOverlayHandle {
  instanceId: string;
  close: () => void;
}

export function useOpenQuickNoteSaveOverlay() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenQuickNoteSaveOverlayOptions): QuickNoteSaveOverlayHandle => {
      const instanceId = opts.instanceId ?? `saveToNotes-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          instanceId,
          data: {
            initialContent: opts.initialContent,
            defaultFolder: opts.defaultFolder,
            title: opts.title,
            initialEditorMode: opts.initialEditorMode,
            onSaved: opts.onSaved,
          },
        }),
      );
      return {
        instanceId,
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID, instanceId })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function QuickNoteSaveOverlayController(props: OpenQuickNoteSaveOverlayOptions): null {
  const open = useOpenQuickNoteSaveOverlay();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.initialContent, props.defaultFolder, props.title, props.initialEditorMode, props.onSaved]);
  return null;
}
