"use client";

/**
 * Opener for the `shareModalWindow` overlay.
 *
 * - `useOpenShareModalWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<ShareModalWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "shareModalWindow" as const;

export interface OpenShareModalWindowOptions {
  /** TODO: tighten to `ResourceType` once that type is imported. */
  resourceType: unknown;
  resourceId: string;
  resourceName: string;
  isOwner: boolean;
}

export interface ShareModalWindowHandle {
  close: () => void;
}

export function useOpenShareModalWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenShareModalWindowOptions): ShareModalWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            resourceType: opts.resourceType,
            resourceId: opts.resourceId,
            resourceName: opts.resourceName,
            isOwner: opts.isOwner,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function ShareModalWindowController(props: OpenShareModalWindowOptions): null {
  const open = useOpenShareModalWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.resourceType, props.resourceId, props.resourceName, props.isOwner]);
  return null;
}
