"use client";

/**
 * Opener for the `taskQuickCreateWindow` overlay.
 *
 * - `useOpenTaskQuickCreateWindow()` — imperative hook. Call to open with typed options;
 *   returns a handle with a `close()` method.
 * - `<TaskQuickCreateWindowController />` — declarative wrapper. Mount to open,
 *   unmount to close. Equivalent ergonomics to rendering a normal component.
 *
 * Generated by scripts/generate-overlay-controller.ts (`openers` mode).
 * Hand-edit freely after the initial seed; the script will not re-emit a
 * file that already exists unless invoked with --force.
 */

import { useCallback, useEffect } from "react";
import { useAppDispatch } from "@/lib/redux/hooks";
import { closeOverlay, openOverlay } from "@/lib/redux/slices/overlaySlice";

const OVERLAY_ID = "taskQuickCreateWindow" as const;

export interface OpenTaskQuickCreateWindowOptions {
  /** TODO: tighten to `TaskSourceInput` once that type is imported. */
  source?: unknown;
  /** TODO: tighten to `TaskPrePopulate` once that type is imported. */
  prePopulate?: unknown;
}

export interface TaskQuickCreateWindowHandle {
  close: () => void;
}

export function useOpenTaskQuickCreateWindow() {
  const dispatch = useAppDispatch();
  return useCallback(
    (opts: OpenTaskQuickCreateWindowOptions = {}): TaskQuickCreateWindowHandle => {
      dispatch(
        openOverlay({
          overlayId: OVERLAY_ID,
          data: {
            source: opts.source,
            prePopulate: opts.prePopulate,
          },
        }),
      );
      return {
        close: () => dispatch(closeOverlay({ overlayId: OVERLAY_ID })),
      };
    },
    [dispatch],
  );
}

/**
 * Declarative form. Renders nothing visible; opens the overlay on mount,
 * closes it on unmount. Use this when a caller wants to express overlay
 * state declaratively (the way they'd render a normal component).
 */
export function TaskQuickCreateWindowController(props: OpenTaskQuickCreateWindowOptions): null {
  const open = useOpenTaskQuickCreateWindow();
  useEffect(() => {
    const handle = open(props);
    return () => handle.close();
  }, [open, props.source, props.prePopulate]);
  return null;
}
