-- lane: ARGS-RULED
--
-- chair-step: it UPDATEs an existing registry column (platform.client_callable_door.argument_rules)
--   on eleven rows rather than inserting new ones, which the additive allow-list refuses by
--   name. Nothing is dropped, no body changes, no row of anybody's data is touched. The inverse
--   is migrations/inverse/argsruled_every_relation_argument_names_its_check_down.sql and it sets
--   all eleven back to NULL, which is exactly what they held before this file.
--
-- ARGS-RULED — EVERY ID ARGUMENT OF THE RELATION SURFACE NAMES WHAT IT IS CHECKED AGAINST.
--
-- Lane GUARD-STAMPS restated the per-argument ceiling at 236 on 2026-09-21 and wrote down what
-- it could not do: "the 232 unruled id arguments are still unruled … of eleven
-- `platform.relation_*` doors only four resolve the second id through
-- `custom.assert_client_may_open`, and `platform.relation_label` does not call
-- `platform.assert_relations_door` at all — so a rule generated from the pattern would be a
-- FALSE declaration, which is what lessons ledger 28 exists to stop."
--
-- This file rules the eleven, one door at a time, from each body — not from the family. The
-- readings are in common-docs PROGRESS-ARGS-RULED.md with the line of the body that carries
-- each one. Two of the twenty-three arguments were REAL HOLES and were closed first, by
-- migrations/campaign/argsruled_the_far_end_of_a_relation_is_decided_too.sql; this file
-- declares what is true AFTER that one, never before it.
--
-- WHAT A RULING IS HERE. `arguments.<name>.foreign` is the field the census reads
-- (`platform.definer_two_id_population`), and it says what a caller gets for an id they may not
-- hold. Three shapes, and no fourth:
--   * CHECKED — the body resolves the id through the ladder primitive that owns that kind of id
--     (a record → custom.assert_client_may_open / _may_change; an organization →
--     custom.assert_client_may_reach → iam.has_org_access; a Field → its Table's
--     custom.assert_may_know_table; any other entity token → iam.has_access).
--   * DERIVED — the id is resolved from a row the door has already decided about.
--   * NOT A LEAK, WITH THE REASON — the argument reaches no table predicate that could confer
--     access. One argument here is this, and only one: `platform.relation_unset(p_target_id)`.
--
-- Nothing is dropped and no body changes: this file writes one registry column on eleven rows.

set lock_timeout = '4s';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_field_id": {"type": "uuid", "position": 2, "check": "the Field row is read only within (organization_id = p_organization_id or data_class = ''kernel''); a miss raises 23503 ''there is no field % in this organization'', which is what a foreign field and an invented id both get. The Field is then put through its own TABLE''s ladder \u2014 custom.assert_may_know_table(p_organization_id, entity_definition_id, \u2026) \u2014 except for a kernel-class Field, which belongs to a standard table the platform itself declares and that nobody was ever shared.", "foreign": {"sqlstate": "23503", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "viewer on the Field''s Table"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_declaration';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_open(p_organization_id, <this>, ''platform.relation_delete_effects'', ''viewer'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "viewer"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_delete_effects';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_open(p_organization_id, <this>, ''platform.relation_field'', ''viewer'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "viewer"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_field';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_association_id": {"type": "uuid", "position": 2, "check": "the edge is resolved only within this organization AND with source_type = ''record''; anything else \u2014 a foreign edge, an invented id, an edge of another kind \u2014 returns the empty history and the read is never reached (ARGS-RULED 2026-09-21, migrations/campaign/argsruled_the_far_end_of_a_relation_is_decided_too.sql). A resolved source record then goes through custom.assert_client_may_open at viewer, so the history of an edge is decided at the reading threshold of the record it comes out of.", "foreign": {"note": "the empty history, byte-identical to an invented id", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21; the skipped branch it closes was found by reading, not measured live \u2014 see PROGRESS-ARGS-RULED.md", "entity": "agent_surface_binding", "access": "viewer on the source record"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_history';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_target_id": {"type": "uuid", "position": 3, "check": "BOTH ARMS DECIDE, and each decides before it reads. p_target_type = ''record'': custom.has_visibility(viewer) or platform.relation_withheld_label(). Every other entity token: iam.has_access(p_target_type, <this>, ''viewer'') or the same withheld sentence (ARGS-RULED 2026-09-21). Until that migration the second arm read the title column of whatever table p_target_type named, with no access decision and no organization in the WHERE clause, and handed back another tenant''s name.", "foreign": {"note": "platform.relation_withheld_label() \u2014 a sentence, never the title and never the id", "not_a_leak": true, "same_as_invented": true}, "verified": "live 2026-09-21 as test@test.com from the authenticated seat: red twin scripts/campaign-tests/argsruled_red.sql, green scripts/campaign-tests/argsruled_green.sql", "access": "viewer, asked of the kernel that owns the token"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_label';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_change(p_organization_id, <this>, ''platform.relation_on_delete'', ''editor'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist \u2014 this verb takes the pointer out of other people''s records, so it asks the WRITING threshold on the record whose deletion is being carried out", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "editor"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_on_delete';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_change(p_organization_id, <this>, ''platform.relation_set'', ''editor'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist; every TARGET in p_targets is separately put through custom.assert_client_may_open at viewer and custom.assert_may_know_table, so a link cannot be made to a record the caller may not see", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "editor"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_set';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_target_id": {"type": "uuid", "position": 3, "check": "p_target_type = ''record'': custom.assert_client_may_open at viewer before the document is copied \u2014 this is the strongest read on the surface, it takes the WHOLE document. Any other entity token: the id is never read here; it is passed to platform.relation_label, which decides it (ARGS-RULED 2026-09-21) and answers the withheld sentence when the caller may not hold it.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "access": "viewer"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_snapshot_of';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_change(p_organization_id, <this>, ''platform.relation_unset'', ''editor'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "editor"}, "p_target_id": {"type": "uuid", "position": 4, "check": "NOT CHECKED, AND IT CANNOT CONFER ACCESS. It reaches exactly one table predicate \u2014 `a.target_id = p_target_id` \u2014 inside an UPDATE already scoped to this organization, to the source record the caller was just asserted at EDITOR on, and to that record''s own role. The door reads nothing about the target and returns only a row count, and every edge that count could describe is one the same caller already reads in full through platform.relations_from on the same record.", "foreign": {"note": "a filter inside a statement the caller already holds; the body never reads the target", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "access": "none needed"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relation_unset';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_open(p_organization_id, <this>, ''platform.relations_from'', ''viewer'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "viewer"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relations_from';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_every_relation_argument_names_its_check.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "custom.assert_client_may_reach(p_organization_id, \u2026) \u2192 iam.has_org_access, on the first line and before any read; a non-member is refused 42501 ''You are not a member of that organization''", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the same wall is measured live by scripts/campaign-tests/argsruled_green.sql clause 1", "entity": "organization", "access": "member of the organization"}, "p_record_id": {"type": "uuid", "position": 2, "check": "custom.assert_client_may_open(p_organization_id, <this>, ''platform.relations_to'', ''viewer'', ''record'') \u2192 custom.has_visibility, decided before the record is admitted to exist", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "viewer"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'relations_to';
