-- lane: ARGS-RULED
--
-- chair-step: it UPDATEs an existing registry column (platform.client_callable_door.argument_rules)
--   on eight rows rather than inserting new ones, which the additive allow-list refuses by name.
--   Nothing is dropped, no body changes, no row of anybody's data is touched. The inverse is
--   migrations/inverse/argsruled_the_eighteen_doors_outside_the_store_down.sql and it restores
--   each of the eight to exactly what it held before (seven NULL; context.provision_scope_dataset
--   the 2026-09-17 declared-unchecked pair, which it is now allowed to stop declaring because the
--   body checks).
--
-- ARGS-RULED — THE DOORS OF THE 236 THAT DO NOT LIVE IN THE STORE.
--
-- Eighteen of the 236 two-id doors are outside schema `custom`: eleven `platform.relation_*`
-- (ruled by argsruled_every_relation_argument_names_its_check.sql), three more in `platform`,
-- three in `iam`, one in `context` and one in `scheduler`. This file rules the eight that were
-- not the relation family, each from its own body.
--
-- THREE OF THEM WERE REAL HOLES and were closed first, by
-- migrations/campaign/argsruled_three_doors_that_never_looked_at_the_caller.sql. This file
-- declares what is true AFTER that one, never before it:
--   * context.provision_scope_dataset  — made rows in whatever tenant the scope named
--   * platform.knob_snapshot           — resolved ANOTHER ACCOUNT's own settings
--   * platform.unified_data_store_set  — let the caller name somebody else as the actor
--
-- THE OTHER FIVE WERE ALREADY DECIDING, and the reading says which line does it and what a
-- caller gets for an id they may not hold. Four arguments across them are declared NOT A LEAK
-- with a reason the guard can verify — the argument reaches no table predicate that could
-- confer access: platform.emit_pending_assist(p_entity_id) and scheduler.sch_run_claim(
-- p_trigger_id) are pointers written onto the caller's own new row and never read; and
-- iam.record_visible_in_org(p_created_by) is a ROW COLUMN that the RLS predicate supplies from
-- the row it is filtering, in a function that reads nothing and returns a boolean.

set lock_timeout = '4s';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_scope_id": {"type": "uuid", "position": 2, "check": "iam.has_org_access(v_scope.organization_id) \u2014 the scope is resolved, then the CALLER is asked about the organization it belongs to, before the dataset, its fields, the instance row and the context value are made there (ARGS-RULED 2026-09-21). Until that migration this door made all four in whatever tenant the scope named, with no access decision at all, and both arguments carried a DECLARED {\"unchecked\": true} rule.", "foreign": {"sqlstate": "42501", "same_as_invented": false, "note": "a scope that does not resolve still answers null (a deleted scope legitimately does); a scope that resolves in another organization is refused 42501 by name"}, "verified": "static reading 2026-09-21; the ladder itself measured from test@test.com''s authenticated seat, scripts/campaign-tests/argsruled_green.sql clause 9. The door''s own arm carries the iam.is_trusted_backend escape a server lane needs and is therefore not measurable from a direct connection.", "entity": "scope", "access": "member of the scope''s organization"}, "p_item_id": {"type": "uuid", "position": 1, "check": "DERIVED. It is resolved from context.context_items and then bound to the scope: the body returns null unless item.scope_type_id = scope.scope_type_id, and the template it names must belong to the SCOPE''s organization or to the platform system organization. Everything it writes is keyed to v_scope.organization_id, which is the id the caller is now asked about.", "foreign": {"note": "null, identical to an invented item id", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "context_item", "access": "decided through p_scope_id"}}}'::jsonb
 where schema_name = 'context' and function_name = 'provision_scope_dataset';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_org": {"type": "uuid", "position": 2, "check": "iam.has_org_access(p_org) \u2014 the caller''s own membership, in the one expression this function is.", "foreign": {"sqlstate": null, "note": "false", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "organization", "access": "member"}, "p_user": {"type": "uuid", "position": 1, "check": "iam.has_org_access_for(p_user, p_org) \u2014 and the caller must already be in that organization. This is the platform''s PERSON ladder; it returns only a boolean and reads no row of anybody''s data. It is anon-callable, and for anon auth.uid() is null, so iam.has_org_access is false and the answer is false for every non-null person.", "foreign": {"note": "false", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "user_profile", "access": "both the caller and the named person are in that organization"}}}'::jsonb
 where schema_name = 'iam' and function_name = 'may_address_user_in_org';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 4, "check": "iam.effective_level(auth.uid(), p_resource_type, p_resource_id, p_organization_id) < iam.top_content_level() raises 42501, on the caller''s own identity, before the first read and before anything is written.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "organization", "access": "the top content level on the resource, in this organization"}, "p_resource_id": {"type": "uuid", "position": 3, "check": "the same one decision: iam.effective_level over (p_resource_type, p_resource_id, p_organization_id) at the top content level, and then iam.lane_of(...) must already be ''world''. A share is not a publish, and neither is an id.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "access": "top content level"}}}'::jsonb
 where schema_name = 'iam' and function_name = 'publish_binding_create';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "it scopes custom.visible_set(auth.uid(), \u2026) \u2014 the set of what THIS CALLER reaches in that organization, which is empty for a non-member. This function takes no principal argument on purpose (its own comment says why), so no id it is handed can make it answer about somebody else.", "foreign": {"note": "false \u2014 an empty set for a non-member", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "organization", "access": "whatever the caller holds"}, "p_table_id": {"type": "uuid", "position": 2, "check": "the same: it narrows the CALLER''s own visible set to one Table. It selects nothing of the Table''s contents.", "foreign": {"note": "false", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record"}, "p_id": {"type": "uuid", "position": 3, "check": "on the fallback arm it goes through the full ladder, custom.has_visibility(auth.uid(), ''record'', p_id, p_required); on every other arm it is only tested for membership of id lists the caller''s own set produced.", "foreign": {"note": "false", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "custom_record", "access": "the level asked for"}, "p_created_by": {"type": "uuid", "position": 5, "check": "NOT CHECKED, AND IT CANNOT CONFER ACCESS. This is a ROW COLUMN, supplied by the RLS predicate that calls this function from the row it is filtering. A client calling it directly and passing their own id gets back `true` \u2014 about arguments they invented \u2014 and the function reads no row of anybody''s data and returns nothing but a boolean. The rows it governs are reached through RLS, which supplies the real column.", "foreign": {"note": "a boolean about the caller''s own arguments; the body reads no row", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "user_profile", "access": "none needed"}}}'::jsonb
 where schema_name = 'iam' and function_name = 'record_visible_in_org';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "iam.has_org_access(p_organization_id) raises 42501 before the INSERT (closed by lane FIX-7B, re-verified from the seat by GUARD-STAMPS).", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "live 2026-09-21 by lane GUARD-STAMPS, as test@test.com", "entity": "organization", "access": "member"}, "p_entity_id": {"type": "uuid", "position": 9, "check": "NOT CHECKED, AND IT CANNOT CONFER ACCESS. It is stored as a pointer on an assist the caller raises FOR THEMSELF (user_id = auth.uid()) in an organization they were just asserted a member of. The body never reads it, never joins on it and never returns anything about it.", "foreign": {"note": "a pointer on the caller''s own assist row", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "access": "none needed"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'emit_pending_assist';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "iam.has_org_access(p_organization_id) (or iam.is_trusted_backend) raises 42501 before the first read and before existence \u2014 this door''s own comment explains why an organization''s configuration is not a stranger''s to read.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "organization", "access": "member"}, "p_user_id": {"type": "uuid", "position": 2, "check": "iam.may_address_user_in_org(p_user_id, p_organization_id) \u2014 the ladder that owns a person id \u2014 unless it IS the caller or the caller is a trusted backend (ARGS-RULED 2026-09-21). Until that migration this id went straight to platform.knob_resolve as the USER rung, so it resolved another account''s own overrides to anybody who named them.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21; the ladder measured from test@test.com''s authenticated seat, scripts/campaign-tests/argsruled_green.sql clauses 6 and 7. The door''s arm carries the iam.is_trusted_backend escape its organization arm already carried and is therefore not measurable from a direct connection.", "entity": "user_profile", "access": "both the caller and the named person are in that organization"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'knob_snapshot';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_organization_id": {"type": "uuid", "position": 1, "check": "platform.assert_may_operate_unified_data_ramp(p_organization_id, \u2026) on the first line: an owner or an administrator of THIS organization, or 42501 by name.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "organization", "access": "owner or administrator of the organization"}, "p_acting_user_id": {"type": "uuid", "position": 3, "check": "it must BE the caller, unless the caller is a trusted backend (ARGS-RULED 2026-09-21). It is written into the knob override''s audit trail as the person who flipped this organization''s data store; until that migration an administrator could record another administrator as having done it \u2014 the stamp-from-an-argument class GUARD-STAMPS closed on custom.portal_principal_bind the same day.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "user_profile", "access": "the caller''s own identity"}}}'::jsonb
 where schema_name = 'platform' and function_name = 'unified_data_store_set';

update platform.client_callable_door
   set argument_rules = '{"version": 1, "declared_by": "argsruled_the_eighteen_doors_outside_the_store.sql", "declared_at": "2026-09-21 lane ARGS-RULED, per-door reading of the body", "arguments": {"p_task_id": {"type": "uuid", "position": 1, "check": "the task is read, and then public.is_platform_admin() or iam.has_org_access(v_task.organization_id) raises 42501. A task in another organization and an invented id both answer P0002 ''That scheduled task no longer exists'' or the 42501, and neither answer carries anything off the row.", "foreign": {"sqlstate": "42501", "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "sch_task", "access": "member of the organization that owns the task"}, "p_trigger_id": {"type": "uuid", "position": 3, "check": "NOT CHECKED, AND IT CANNOT CONFER ACCESS. It is written into scheduler.sch_run.trigger_id on a run row the caller has just been admitted to create, in their own organization. The body never reads it, never joins on it and returns nothing about it.", "foreign": {"note": "a pointer on the run row the caller just claimed", "not_a_leak": true, "same_as_invented": true}, "verified": "static reading 2026-09-21", "entity": "workflow_trigger", "access": "none needed"}}}'::jsonb
 where schema_name = 'scheduler' and function_name = 'sch_run_claim';
