-- lane: DRILL-USAGE-PAGE
-- lock: platform
-- Written by aidream apps/shared/records/scripts/drill-sync.ts from: aidream/apps/shared/records/scripts/drill-definitions/ai_usage.drill.ts
-- Declared drill definitions, one function each (platform.drill_def__<key>()). Code, not data.

create or replace function platform.drill_def__ai_usage()
returns jsonb
language sql
immutable
set search_path to 'pg_catalog'
as $function$
  select $drill${"key":"ai_usage","label":"AI usage","grain":"one row per hour for each organization, person, agent, provider, model, app, feature, origin, manual or automated, and source","fact":"ai_usage_hourly","mode":"definer","lanes":["platform","organization","mine"],"lane_rules":{"platform":{"rule":"super_admin"},"organization":{"column":"organization_id","rule":"admin"},"mine":{"column":"person_id"}},"dimensions":[{"key":"organization","label":"Organization","from":"organization_id","kind":"relation","relation":{"token":"organization"}},{"key":"person","label":"Person","from":"person_id","kind":"relation","relation":{"token":"user","person":true}},{"key":"provider","label":"Provider","from":"provider","kind":"choice","cardinality":"low"},{"key":"model","label":"Model","from":"model","kind":"choice","cardinality":"medium"},{"key":"app","label":"App","from":"app","kind":"choice","cardinality":"low"},{"key":"feature","label":"Feature","from":"feature","kind":"choice","cardinality":"medium"},{"key":"agent","label":"Agent","from":"agent_id","kind":"relation","relation":{"token":"agent"},"cardinality":"medium"},{"key":"origin","label":"Origin","from":"origin","kind":"choice","cardinality":"low"},{"key":"trigger","label":"Manual or automated","from":"trigger","kind":"choice","cardinality":"low"},{"key":"source","label":"Source","from":"source","kind":"choice","cardinality":"low"},{"key":"at","label":"When","from":"bucket","kind":"time","grains":["year","quarter","month","week","day","hour"]}],"measures":[{"key":"cost","label":"Cost","op":"sum","of":"cost","unit":"usd","additive":true},{"key":"calls","label":"Calls","op":"sum","of":"calls","unit":"count","additive":true},{"key":"requests","label":"Requests","op":"sum","of":"requests","unit":"count","additive":true},{"key":"tokens_in","label":"Input tokens","op":"sum","of":"tokens_in","unit":"tokens","additive":true},{"key":"tokens_out","label":"Output tokens","op":"sum","of":"tokens_out","unit":"tokens","additive":true},{"key":"tokens_cached","label":"Cached tokens","op":"sum","of":"tokens_cached","unit":"tokens","additive":true},{"key":"unpriced_calls","label":"Calls with no price","op":"sum","of":"unpriced_calls","unit":"count","additive":true},{"key":"people","label":"People","op":"count_distinct","of":"person_id","unit":"count","additive":false}],"paths":[{"key":"who","label":"Who","levels":["organization","person"]},{"key":"what","label":"What","levels":["provider","model"]},{"key":"where","label":"Where","levels":["app","feature","agent"]},{"key":"when","label":"When","levels":["at:month","at:week","at:day","at:hour"]}],"detail":{"columns":["bucket","organization_id","person_id","provider","model","feature","cost","tokens_in","tokens_out"],"open":"/administration/billing/spend"},"default":{"by":["person"],"show":["cost","requests","tokens_in","tokens_out"],"sort":{"key":"cost","direction":"desc"},"window":{"key":"at","preset":"30d"},"path":"who"}}$drill$::jsonb;
$function$;

comment on function platform.drill_def__ai_usage() is
  'DRILL-STANDARD-DOOR: the declared drill definition "AI usage" (ai_usage), compiled from its *.drill.ts file by aidream apps/shared/records/scripts/drill-sync.ts. Code, not data: never edited by hand.';
