-- target: branch
--
-- w0_sync2_grant_surface_relevel — the branch's client EXECUTE surface, level with
-- production again.
--
-- Production revoked a batch of unwritten grants at 20:37 UTC today
-- (`0842_nobody_wrote_this_grant.sql`), and the branch kept them. Measured right after:
-- **424** function EXECUTE grants the BRANCH gives and production does not — 118 to
-- `anon` and 306 to `PUBLIC`. Every one of them lets a client role call something
-- production answers 42501 for, so every access proof a lane takes over one is measuring
-- a system that does not exist.
--
-- THE PUBLIC HALF WAS INVISIBLE UNTIL TODAY. `check:branch-schema-drift`'s grants clause
-- judged only `anon`, `authenticated` and `service_role`; both of the first two INHERIT a
-- PUBLIC grant, so revoking `anon` while leaving `PUBLIC` would have turned the check
-- green without moving the surface an inch. The clause now judges PUBLIC too, in the same
-- commit that generated this file.
--
-- PER FUNCTION, NOT PER ROW. Dropping a PUBLIC grant without restoring the explicit
-- `authenticated` / `service_role` grant production holds on the same function would trade
-- a looser branch for a TIGHTER one — a branch that denies a read production allows sends
-- the next lane to fix a defect that does not exist. So every function this file touches
-- gets production's client grant set restated in full: 424 revokes and 324 grants, all
-- from production's catalog, read SELECT-only.
--
-- Emitted as REVOKE/GRANT ... ON ROUTINE, because pg_proc holds procedures too and
-- ON FUNCTION dies on the first one.
--
-- GENERATED, not typed: `pnpm check:branch-schema-drift --sync-plan`.
--
--   uv run python db/apply_migrations.py --source campaign \
--     --only w0_sync2_grant_surface_relevel.sql \
--     --target branch --lane W0-SYNC --no-generate

revoke execute on routine "ai"."_validate_rules_envelope"(p_doc jsonb, p_where text) from public;
revoke execute on routine "ai"."audit_ui_enum_drift"() from public;
revoke execute on routine "ai"."jsonb_num"(n numeric) from public;
revoke execute on routine "ai"."jsonb_num"(n numeric) from "anon";
revoke execute on routine "api"."fetch_foreign_key_info"() from public;
revoke execute on routine "api"."fetch_foreign_key_info"() from "anon";
revoke execute on routine "api"."schema_table_column_relationships"(p_schema text) from public;
revoke execute on routine "api"."schema_table_column_relationships"(p_schema text) from "anon";
revoke execute on routine "api"."simple_foreign_key_info"() from public;
revoke execute on routine "api"."simple_foreign_key_info"() from "anon";
revoke execute on routine "audit"."effective_search_path"(p_proconfig text[]) from public;
revoke execute on routine "audit"."is_m2m_shape"(p_rel regclass) from public;
revoke execute on routine "billing"."period_reset"(p_period billing.meter_period) from public;
revoke execute on routine "billing"."period_start"(p_period billing.meter_period) from public;
revoke execute on routine "billing"."resolve_capability"(p_user uuid, p_capability text) from public;
revoke execute on routine "billing"."resolve_capability"(p_user uuid, p_capability text, p_org uuid) from public;
revoke execute on routine "billing"."resolve_effective_tier"(p_user uuid, p_org uuid) from public;
revoke execute on routine "billing"."resolve_limit"(p_org uuid, p_capability text, p_period billing.meter_period) from public;
revoke execute on routine "billing"."resolve_org_tier"(p_org uuid) from public;
revoke execute on routine "billing"."resolve_plan"(p_org uuid) from public;
revoke execute on routine "billing"."resolve_tier"(p_user uuid) from public;
revoke execute on routine "billing"."tier_max"(a billing.tier, b billing.tier) from public;
revoke execute on routine "billing"."tier_rank"(p_tier billing.tier) from public;
revoke execute on routine "canvas"."_require_actor"(p_user_id uuid) from "anon";
revoke execute on routine "chat"."_message_tool_call_ids"(p_content jsonb) from public;
revoke execute on routine "communication"."delivery_failure_sentence"(p_error_code text, p_channel text) from public;
revoke execute on routine "content_ir"."admission_enforced"() from public;
revoke execute on routine "content_ir"."assert_kind_admission"(p_organization_id uuid, p_kind text, p_version integer, p_context text) from public;
revoke execute on routine "content_ir"."check_kind_admission"(p_organization_id uuid, p_kind text, p_version integer) from public;
revoke execute on routine "content_ir"."compute_example_validation"(p_data jsonb, p_schema jsonb) from public;
revoke execute on routine "content_ir"."declare_kind_marker"(p_schema jsonb, p_slug text) from public;
revoke execute on routine "content_ir"."declare_kind_markers_deep"(p_schema jsonb, p_slug text) from public;
revoke execute on routine "content_ir"."evaluate_kind_activation"(p_kind_definition_id uuid) from public;
revoke execute on routine "content_ir"."owned_child_instances"(p_ids uuid[]) from public;
revoke execute on routine "content_ir"."stamp_markers_from_schema"(p_value jsonb, p_schema jsonb, p_root jsonb, p_depth integer) from public;
revoke execute on routine "content_ir"."strip_kind_deep"(p jsonb) from public;
revoke execute on routine "context"."_strip_sql_noise"(p_src text) from public;
revoke execute on routine "context"."parse_reference_fence"(p_value_text text) from public;
revoke execute on routine "context"."reference_item_ref_key"(p_type text, p_item jsonb) from public;
revoke execute on routine "context"."slugify"(p text) from public;
revoke execute on routine "context"."validate_reference_value"(p_item_id uuid, p_value_text text) from public;
revoke execute on routine "crm"."name_key"(p_name text) from public;
revoke execute on routine "esign"."_arm"() from public;
revoke execute on routine "esign"."_disarm"() from public;
revoke execute on routine "esign"."_privileged"() from public;
revoke execute on routine "esign"."_requester_actor_type"(p_consumer_key text) from public;
revoke execute on routine "files"."file_path_matches_parent"(p_file_id uuid) from public;
revoke execute on routine "files"."file_path_matches_parent"(p_file_id uuid) from "anon";
revoke execute on routine "files"."is_safe_webhook_url"(p_url text) from public;
revoke execute on routine "files"."is_safe_webhook_url"(p_url text) from "anon";
revoke execute on routine "files"."is_user_visible"(p_row files.files) from public;
revoke execute on routine "files"."is_user_visible"(p_row files.files) from "anon";
revoke execute on routine "files"."is_user_visible_path"(p_file_path text) from public;
revoke execute on routine "files"."is_user_visible_path"(p_file_path text) from "anon";
revoke execute on routine "files"."min_tombstone_retention_days"() from public;
revoke execute on routine "files"."min_tombstone_retention_days"() from "anon";
revoke execute on routine "files"."webhook_sign"(p_secret text, p_payload text) from public;
revoke execute on routine "files"."webhook_sign"(p_secret text, p_payload text) from "anon";
revoke execute on routine "hr"."_add_business_days"(p_start date, p_days integer, p_holidays date[], p_day_zero_counts boolean) from public;
revoke execute on routine "hr"."_applicability_verdict"(p_applicability jsonb, p_facts jsonb) from public;
revoke execute on routine "hr"."_approval_subject_required"(p_target_table text) from public;
revoke execute on routine "hr"."_door_spec"(p_token text) from public;
revoke execute on routine "hr"."_hours_text"(p_hours numeric) from public;
revoke execute on routine "hr"."_ics_escape"(p_text text) from public;
revoke execute on routine "hr"."_leave_blackout_hits"(p_rule jsonb, p_starts date, p_ends date) from public;
revoke execute on routine "hr"."_leave_config_parameters"(p_class text, p_policy jsonb) from public;
revoke execute on routine "hr"."_leave_deduction_clause"(p_fig jsonb) from public;
revoke execute on routine "hr"."_leave_floor_field"(p_field text, p_floor jsonb, p_configured jsonb, p_direction text, p_rule_status text, p_unverified jsonb, p_param_key text, p_sentence text) from public;
revoke execute on routine "hr"."_leave_hours_text"(p_hours numeric) from public;
revoke execute on routine "hr"."_leave_ledger_sentence"(p_entry_kind text, p_occurred_on date, p_starts_on date, p_ends_on date, p_request_state text, p_source_workweek_id uuid, p_leave_request_id uuid, p_hours_delta numeric, p_note text) from public;
revoke execute on routine "hr"."_leave_policy_constraint_violation"(p_constraint text, p_payload jsonb) from public;
revoke execute on routine "hr"."_leave_sentence"(p_fig jsonb) from public;
revoke execute on routine "hr"."_leave_span_is_costless"(p_span jsonb) from public;
revoke execute on routine "hr"."_leave_unknown_axes"(p_filters jsonb, p_allowed text[]) from public;
revoke execute on routine "hr"."_legality_envelope"(p_class text, p_rules jsonb) from public;
revoke execute on routine "hr"."_note_kind_caps"(p_note_kind text) from public;
revoke execute on routine "hr"."_org_row_less_protective"(p_class text, p_org jsonb, p_sys jsonb) from public;
revoke execute on routine "hr"."_punch_allowed_kinds"(p_state text) from public;
revoke execute on routine "hr"."_punch_attest_axis"(p_response jsonb, p_axis text, p_field text) from public;
revoke execute on routine "hr"."_punch_kind_rank"(p_kind text) from public;
revoke execute on routine "hr"."_punch_next_state"(p_state text, p_kind text, p_break_paid boolean) from public;
revoke execute on routine "hr"."_punch_refusal"(p_code text, p_message text, p_details jsonb) from public;
revoke execute on routine "hr"."_recompute_workweek_start"(p_employment_id uuid, p_local_work_date date) from public;
revoke execute on routine "hr"."_week_start_is_provisional"(p_employment_id uuid) from public;
revoke execute on routine "hr"."_wf_decision_words_short"(p_outcome text) from public;
revoke execute on routine "hr"."_wf_failure_sentence"(p_class text) from public;
revoke execute on routine "hr"."alert_recipients"(p_organization_id uuid, p_alert_family text, p_event_key text, p_scope_kind text, p_scope_id uuid, p_tier text) from public;
revoke execute on routine "hr"."compensation_as_of"(p_employment_id uuid, p_on date) from public;
revoke execute on routine "hr"."corrective_action_state"(p_outcome text, p_acknowledgement_kind text, p_acknowledged_at timestamp with time zone, p_follow_up_on date) from public;
revoke execute on routine "hr"."elapsed_hours"(p_start_local timestamp without time zone, p_end_local timestamp without time zone, p_tz text) from public;
revoke execute on routine "hr"."employment_as_of"(p_employee_id uuid, p_on date) from public;
revoke execute on routine "hr"."hr_links_without_employer"() from public;
revoke execute on routine "hr"."incident_next_step_sentence"(p_state text, p_follow_up_on date) from public;
revoke execute on routine "hr"."incident_state_label"(p_state text) from public;
revoke execute on routine "hr"."leave_notification_gap"() from public;
revoke execute on routine "hr"."leave_seal_door"(p_proname text, p_mode text) from public;
revoke execute on routine "hr"."manager_as_of"(p_employment_id uuid, p_on date) from public;
revoke execute on routine "hr"."normalize_org_jurisdiction_rule_parameters"(p_rule_class text, p_parameters jsonb) from public;
revoke execute on routine "hr"."org_chart_as_of"(p_organization_id uuid, p_on date) from public;
revoke execute on routine "hr"."org_jurisdiction_rule_validation_parameters"(p_rule_class text, p_parameters jsonb) from public;
revoke execute on routine "hr"."position_as_of"(p_employment_id uuid, p_on date) from public;
revoke execute on routine "hr"."primary_position_as_of"(p_employment_id uuid, p_on date) from public;
revoke execute on routine "hr"."punch_edit_notify_debt"() from public;
revoke execute on routine "hr"."punch_knobs_missing"() from public;
revoke execute on routine "iam"."_api_key_base62"(p_bytes bytea) from public;
revoke execute on routine "iam"."_client_grant_column_list"(p_rel regclass, p_excluded text[]) from public;
revoke execute on routine "iam"."_dd171_containment_filter"(p_has_vis boolean, p_alias text, p_joiner text) from public;
revoke execute on routine "iam"."_fk_check13"() from public;
revoke execute on routine "iam"."_fk_gap_orphans"() from public;
revoke execute on routine "iam"."_fk_high_orphans"() from public;
revoke execute on routine "iam"."_resolve_owner_column"(p_schema text, p_table text, p_pref text) from public;
revoke execute on routine "iam"."access_resolver_disagreements"(p_rows integer, p_token text, p_users integer) from public;
revoke execute on routine "iam"."auto_organization_name"(p_meta jsonb, p_email text) from public;
revoke execute on routine "iam"."canonical_certify"(p_schema text, p_table text, p_token text) from public;
revoke execute on routine "iam"."canonical_certify_ok"(p_schema text, p_table text, p_token text) from public;
revoke execute on routine "iam"."client_role_can_read"(p_rel regclass, p_role text) from public;
revoke execute on routine "iam"."component_original_lane"(p_schema text, p_table text, p_token text) from public;
revoke execute on routine "iam"."component_wider_than_parent"(p_principals uuid[], p_token text) from public;
revoke execute on routine "iam"."derive_organization_abbreviation"(p_name text, p_is_personal boolean) from public;
revoke execute on routine "iam"."entity_read_equivalence"(p_schema text, p_table text, p_token text, p_user uuid, p_limit integer, p_baseline text) from public;
revoke execute on routine "iam"."entity_read_kernel_expected"() from public;
revoke execute on routine "iam"."entity_read_kernel_fingerprint"() from public;
revoke execute on routine "iam"."entity_read_lane_correct"() from public;
revoke execute on routine "iam"."entity_read_lane_done"() from public;
revoke execute on routine "iam"."entity_read_lane_preflight"() from public;
revoke execute on routine "iam"."entity_read_probe_users"(p_limit integer) from public;
revoke execute on routine "iam"."generated_policy_names"() from public;
revoke execute on routine "iam"."is_trusted_backend"() from public;
revoke execute on routine "iam"."org_readable"(p_org uuid, p_token text) from public;
revoke execute on routine "iam"."platform_admin_read_prefix"(p_token text) from public;
revoke execute on routine "iam"."privacy_wall_read_lane_parity"(p_limit integer) from public;
revoke execute on routine "iam"."sweep_governance_guards"(IN p_lock_timeout text) from public;
revoke execute on routine "iam"."table_has_visibility"(p_schema text, p_table text) from public;
revoke execute on routine "iam"."token_is_parented_component"(p_token text) from public;
revoke execute on routine "iam"."unnest_uuids"(p_ids uuid[]) from public;
revoke execute on routine "iam"."unnest_uuids"(p_ids uuid[]) from "anon";
revoke execute on routine "iam"."verify_canonical"(p_schema text, p_table text, p_token text, p_variant text) from public;
revoke execute on routine "iam"."verify_canonical_ok"(p_schema text, p_table text, p_token text, p_variant text) from public;
revoke execute on routine "mandate"."generate_app_mandate_key"(p_slug text, p_name text) from public;
revoke execute on routine "mandate"."generate_shortcut_mandate_key"(p_label text, p_surface text) from public;
revoke execute on routine "mandate"."sanitize_app_segment"(p_seg text) from public;
revoke execute on routine "mandate"."sanitize_shortcut_segment"(p_seg text) from public;
revoke execute on routine "mandate"."shortcut_slug"(p_text text) from public;
revoke execute on routine "mandate"."shortcut_treatment_config"(p_row jsonb) from public;
revoke execute on routine "mandate"."validate_treatment_config"(p_tier text, p_config jsonb) from public;
revoke execute on routine "platform"."_cf_as_double"(p_value jsonb) from public;
revoke execute on routine "platform"."_cf_int_opt"(p_rules jsonb, p_name text) from public;
revoke execute on routine "platform"."_cf_num_opt"(p_rules jsonb, p_name text) from public;
revoke execute on routine "platform"."_cf_options"(p_definition jsonb) from public;
revoke execute on routine "platform"."_cf_pattern_fails"(p_value text, p_pattern text) from public;
revoke execute on routine "platform"."_cf_str_array"(p_value jsonb) from public;
revoke execute on routine "platform"."_cf_valid_date"(p_value text) from public;
revoke execute on routine "platform"."_cf_valid_datetime"(p_value text) from public;
revoke execute on routine "platform"."actor_declaration_report"() from public;
revoke execute on routine "platform"."actor_declaration_report"() from "anon";
revoke execute on routine "platform"."actor_system"() from public;
revoke execute on routine "platform"."actor_system"() from "anon";
revoke execute on routine "platform"."actor_tier"() from public;
revoke execute on routine "platform"."actor_tier"() from "anon";
revoke execute on routine "platform"."assert_no_stale_rowtype_triggers"() from public;
revoke execute on routine "platform"."cf_compact_json"(p_value jsonb) from public;
revoke execute on routine "platform"."cf_count_keys"(p_value jsonb) from public;
revoke execute on routine "platform"."cf_item_byte_size"(p_value jsonb) from public;
revoke execute on routine "platform"."cf_re_email"() from public;
revoke execute on routine "platform"."cf_re_url"() from public;
revoke execute on routine "platform"."cf_utf8_byte_length"(p_text text) from public;
revoke execute on routine "platform"."cf_ws_class"() from public;
revoke execute on routine "platform"."client_directive_notice_id"() from public;
revoke execute on routine "platform"."client_excluded_column_report"() from public;
revoke execute on routine "platform"."confirmation_stamp_coverage"() from public;
revoke execute on routine "platform"."confirmation_stamp_coverage_ok"() from public;
revoke execute on routine "platform"."custom_field_defs"(p_target_kind text, p_organization_id uuid, p_target_token text, p_definition_id uuid, p_include_archived boolean) from public;
revoke execute on routine "platform"."custom_field_index_expr"(p_field_type text, p_field_key text, p_column text) from public;
revoke execute on routine "platform"."custom_field_index_name"(p_definition_id uuid) from public;
revoke execute on routine "platform"."custom_reference_validity"(p_organization_id uuid, p_definitions jsonb, p_values jsonb) from public;
revoke execute on routine "platform"."dead_relation_read"(p_old text, p_new text) from public;
revoke execute on routine "platform"."declared_actor_agent"() from "anon";
revoke execute on routine "platform"."declared_actor_system"() from public;
revoke execute on routine "platform"."declared_actor_system"() from "anon";
revoke execute on routine "platform"."declared_actor_tier"() from public;
revoke execute on routine "platform"."declared_actor_tier"() from "anon";
revoke execute on routine "platform"."derive_data_class"(p_variant text, p_visibility text) from public;
revoke execute on routine "platform"."derive_list_scope"(p_variant text, p_class platform.data_class) from public;
revoke execute on routine "platform"."door_body_must_decide"() from public;
revoke execute on routine "platform"."extensibility_knob_int"(p_key text, p_organization_id uuid, p_target_token text, p_definition_id uuid) from public;
revoke execute on routine "platform"."find_custom_references_to"(p_organization_id uuid, p_target_token text, p_target_id uuid) from public;
revoke execute on routine "platform"."knob_resolve"(p_feature text, p_key text, p_organization_id uuid, p_user_id uuid, p_scopes jsonb) from public;
revoke execute on routine "platform"."knob_resolve"(p_feature text, p_key text, p_organization_id uuid, p_user_id uuid, p_scopes jsonb) from "anon";
revoke execute on routine "platform"."module_config"(p_org uuid, p_token text) from public;
revoke execute on routine "platform"."normalize_identity_args"(p_args text) from public;
revoke execute on routine "platform"."render_record_name"(p_template text, p_data jsonb, p_first_text_key text, p_id uuid) from public;
revoke execute on routine "platform"."resolve_custom_references"(p_organization_id uuid, p_definitions jsonb, p_values jsonb) from public;
revoke execute on routine "platform"."soft_delete_orphan_census"() from public;
revoke execute on routine "platform"."validate_custom_row"(p_target_kind text, p_organization_id uuid, p_values jsonb, p_target_token text, p_definition_id uuid, p_mode text, p_resolved jsonb) from public;
revoke execute on routine "platform"."validate_custom_values"(p_definitions jsonb, p_values jsonb, p_mode text, p_limits jsonb) from public;
revoke execute on routine "platform"."validate_custom_values"(p_definitions jsonb, p_values jsonb, p_mode text, p_limits jsonb) from "anon";
revoke execute on routine "public"."__dump_schema_ddl"(p_schema text) from public;
revoke execute on routine "public"."__dump_schema_ddl"(p_schema text) from "anon";
revoke execute on routine "public"."__dump_schema_routines"(p_schema text) from public;
revoke execute on routine "public"."__dump_schema_routines"(p_schema text) from "anon";
revoke execute on routine "public"."__migration_slot_guard_conformance"() from "anon";
revoke execute on routine "public"."_edu_access_mode"(p_scope context.scopes) from public;
revoke execute on routine "public"."_edu_access_mode"(p_scope context.scopes) from "anon";
revoke execute on routine "public"."_edu_is_assignable_token"(p_token text) from public;
revoke execute on routine "public"."_edu_is_assignable_token"(p_token text) from "anon";
revoke execute on routine "public"."_spend_ledger_registry"() from "anon";
revoke execute on routine "public"."_version_diff_json"(a jsonb, b jsonb) from public;
revoke execute on routine "public"."_version_diff_json"(a jsonb, b jsonb) from "anon";
revoke execute on routine "public"."add_enum_values"(p_type_name text, p_new_values text[]) from public;
revoke execute on routine "public"."add_enum_values"(p_type_name text, p_new_values text[]) from "anon";
revoke execute on routine "public"."agx_build_shortcut_menu"(p_placement_types text[]) from public;
revoke execute on routine "public"."agx_build_shortcut_menu"(p_placement_types text[]) from "anon";
revoke execute on routine "public"."agx_contract_hash"(p_contract jsonb) from public;
revoke execute on routine "public"."agx_contract_hash"(p_contract jsonb) from "anon";
revoke execute on routine "public"."agx_escape_regex"(p text) from public;
revoke execute on routine "public"."agx_escape_regex"(p text) from "anon";
revoke execute on routine "public"."agx_get_version_history"(p_agent_id uuid, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."agx_get_version_history"(p_agent_id uuid, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."agx_get_version_snapshot"(p_agent_id uuid, p_version_number integer) from public;
revoke execute on routine "public"."agx_get_version_snapshot"(p_agent_id uuid, p_version_number integer) from "anon";
revoke execute on routine "public"."agx_input_contract"(p_vars jsonb, p_slots jsonb) from public;
revoke execute on routine "public"."agx_input_contract"(p_vars jsonb, p_slots jsonb) from "anon";
revoke execute on routine "public"."agx_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_favorites_first boolean, p_archived text, p_filters jsonb, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."agx_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_favorites_first boolean, p_archived text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."agx_resolve_agent_address"(p_ids uuid[]) from "anon";
revoke execute on routine "public"."agx_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_category text, p_tags text[], p_model_id uuid, p_agent_type text, p_owner_email text, p_deep_hit boolean) from public;
revoke execute on routine "public"."agx_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_category text, p_tags text[], p_model_id uuid, p_agent_type text, p_owner_email text, p_deep_hit boolean) from "anon";
revoke execute on routine "public"."agx_since_bucket"(p_bucket text) from public;
revoke execute on routine "public"."agx_since_bucket"(p_bucket text) from "anon";
revoke execute on routine "public"."calculate_trending_score"(p_like_count integer, p_play_count integer, p_comment_count integer, p_share_count integer, p_fork_count integer, p_view_count integer, p_completion_rate numeric, p_created_at timestamp with time zone, p_featured boolean) from public;
revoke execute on routine "public"."calculate_trending_score"(p_like_count integer, p_play_count integer, p_comment_count integer, p_share_count integer, p_fork_count integer, p_view_count integer, p_completion_rate numeric, p_created_at timestamp with time zone, p_featured boolean) from "anon";
revoke execute on routine "public"."convert_frontend_to_db_fields"(input_json json) from public;
revoke execute on routine "public"."convert_frontend_to_db_fields"(input_json json) from "anon";
revoke execute on routine "public"."creator_normalize_handle"(p_handle text) from public;
revoke execute on routine "public"."creator_normalize_handle"(p_handle text) from "anon";
revoke execute on routine "public"."crm_inbound_evidence"(p_attributes jsonb) from public;
revoke execute on routine "public"."crm_inbound_evidence"(p_attributes jsonb) from "anon";
revoke execute on routine "public"."crm_inbound_label"(p_attributes jsonb) from public;
revoke execute on routine "public"."crm_inbound_label"(p_attributes jsonb) from "anon";
revoke execute on routine "public"."crm_inbox_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."crm_inbox_search_score"(p_query text, p_id uuid, p_party_name text, p_subject text, p_snippet text, p_list_name text, p_employer text, p_classification text, p_deep_hit boolean) from public;
revoke execute on routine "public"."crm_inbox_search_score"(p_query text, p_id uuid, p_party_name text, p_subject text, p_snippet text, p_list_name text, p_employer text, p_classification text, p_deep_hit boolean) from "anon";
revoke execute on routine "public"."crm_step_matches"(p_step integer, p_bucket text) from public;
revoke execute on routine "public"."crm_step_matches"(p_step integer, p_bucket text) from "anon";
revoke execute on routine "public"."cvx_audience"(p_provider text, p_source_app text, p_origin_class text, p_conversation_type text) from "anon";
revoke execute on routine "public"."cvx_search_score"(p_query text, p_id uuid, p_title text, p_description text, p_workspace text, p_source_feature text, p_source_app text, p_provider_account text, p_provider_session text, p_deep_hit boolean) from public;
revoke execute on routine "public"."cvx_search_score"(p_query text, p_id uuid, p_title text, p_description text, p_workspace text, p_source_feature text, p_source_app text, p_provider_account text, p_provider_session text, p_deep_hit boolean) from "anon";
revoke execute on routine "public"."cvx_size_band"(p_count integer) from public;
revoke execute on routine "public"."cvx_size_band"(p_count integer) from "anon";
revoke execute on routine "public"."cx_canvas_get_by_message"(p_message_id uuid) from public;
revoke execute on routine "public"."cx_canvas_get_by_message"(p_message_id uuid) from "anon";
revoke execute on routine "public"."cx_canvas_get_conversation_latest"(p_conversation_id uuid) from public;
revoke execute on routine "public"."cx_canvas_get_conversation_latest"(p_conversation_id uuid) from "anon";
revoke execute on routine "public"."cx_canvas_get_version_history"(p_canvas_id uuid) from public;
revoke execute on routine "public"."cx_canvas_get_version_history"(p_canvas_id uuid) from "anon";
revoke execute on routine "public"."cx_canvas_list_by_user"(p_user_id uuid, p_type text, p_is_favorited boolean, p_source_type text, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."cx_canvas_list_by_user"(p_user_id uuid, p_type text, p_is_favorited boolean, p_source_type text, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."cx_canvas_upsert"(p_user_id uuid, p_message_id uuid, p_artifact_index smallint, p_type text, p_title text, p_content jsonb, p_conversation_id uuid, p_source_type text) from public;
revoke execute on routine "public"."cx_canvas_upsert"(p_user_id uuid, p_message_id uuid, p_artifact_index smallint, p_type text, p_title text, p_content jsonb, p_conversation_id uuid, p_source_type text) from "anon";
revoke execute on routine "public"."dict_assert_access"(p_user_id uuid, p_level text, p_owner_id uuid) from public;
revoke execute on routine "public"."dict_assert_access"(p_user_id uuid, p_level text, p_owner_id uuid) from "anon";
revoke execute on routine "public"."dict_get_settings_for"(p_user_id uuid, p_level text, p_owner_id uuid) from public;
revoke execute on routine "public"."dict_get_settings_for"(p_user_id uuid, p_level text, p_owner_id uuid) from "anon";
revoke execute on routine "public"."dict_list_entries_for"(p_user_id uuid, p_level text, p_owner_id uuid) from public;
revoke execute on routine "public"."dict_list_entries_for"(p_user_id uuid, p_level text, p_owner_id uuid) from "anon";
revoke execute on routine "public"."dict_list_owners_for"(p_user_id uuid) from public;
revoke execute on routine "public"."dict_list_owners_for"(p_user_id uuid) from "anon";
revoke execute on routine "public"."dict_owner_org"(p_level text, p_owner_id uuid) from public;
revoke execute on routine "public"."dict_owner_org"(p_level text, p_owner_id uuid) from "anon";
revoke execute on routine "public"."dict_resolve_for"(p_user_id uuid, p_include_user boolean, p_all boolean, p_organization_ids uuid[], p_scope_type_ids uuid[], p_scope_ids uuid[]) from public;
revoke execute on routine "public"."dict_resolve_for"(p_user_id uuid, p_include_user boolean, p_all boolean, p_organization_ids uuid[], p_scope_type_ids uuid[], p_scope_ids uuid[]) from "anon";
revoke execute on routine "public"."dict_rollup_for"(p_level text, p_owner_id uuid) from public;
revoke execute on routine "public"."dict_rollup_for"(p_level text, p_owner_id uuid) from "anon";
revoke execute on routine "public"."edu_library_list_scoped"(p_scope text, p_search text, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."expand_archetype"(p_archetype text, p_choices jsonb) from public;
revoke execute on routine "public"."expand_archetype"(p_archetype text, p_choices jsonb) from "anon";
revoke execute on routine "public"."export_user_table_as_csv"(p_table_id uuid) from public;
revoke execute on routine "public"."export_user_table_as_csv"(p_table_id uuid) from "anon";
revoke execute on routine "public"."export_user_table_as_csv"(p_table_id uuid, p_sort_field text, p_sort_direction text) from public;
revoke execute on routine "public"."export_user_table_as_csv"(p_table_id uuid, p_sort_field text, p_sort_direction text) from "anon";
revoke execute on routine "public"."fetch_foreign_key_info"() from public;
revoke execute on routine "public"."fetch_foreign_key_info"() from "anon";
revoke execute on routine "public"."fn_get_user_usage_snapshot"(p_user_id uuid) from public;
revoke execute on routine "public"."fn_get_user_usage_snapshot"(p_user_id uuid) from "anon";
revoke execute on routine "public"."generate_canvas_content_hash"(content_data jsonb) from public;
revoke execute on routine "public"."generate_canvas_content_hash"(content_data jsonb) from "anon";
revoke execute on routine "public"."generate_invitation_code"() from public;
revoke execute on routine "public"."generate_invitation_code"() from "anon";
revoke execute on routine "public"."generate_invitation_token"() from public;
revoke execute on routine "public"."generate_invitation_token"() from "anon";
revoke execute on routine "public"."get_agent_conversations"(p_agent_id uuid, p_version_number integer, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."get_agent_conversations"(p_agent_id uuid, p_version_number integer, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."get_canvas_leaderboard"(p_canvas_id uuid, p_limit integer) from public;
revoke execute on routine "public"."get_canvas_leaderboard"(p_canvas_id uuid, p_limit integer) from "anon";
revoke execute on routine "public"."get_cx_conversation_bundle"(p_conversation_id uuid, p_message_limit integer, p_before_position smallint) from public;
revoke execute on routine "public"."get_cx_conversation_bundle"(p_conversation_id uuid, p_message_limit integer, p_before_position smallint) from "anon";
revoke execute on routine "public"."get_cx_conversation_source_facets"() from public;
revoke execute on routine "public"."get_cx_conversation_source_facets"() from "anon";
revoke execute on routine "public"."get_database_schema_json"() from public;
revoke execute on routine "public"."get_database_schema_json"() from "anon";
revoke execute on routine "public"."get_full_table"(ref jsonb) from public;
revoke execute on routine "public"."get_full_table"(ref jsonb) from "anon";
revoke execute on routine "public"."get_project_references"(p_project_id uuid) from public;
revoke execute on routine "public"."get_project_references"(p_project_id uuid) from "anon";
revoke execute on routine "public"."get_project_references_detailed"(p_project_id uuid, p_sample_limit integer) from public;
revoke execute on routine "public"."get_project_references_detailed"(p_project_id uuid, p_sample_limit integer) from "anon";
revoke execute on routine "public"."get_schema"() from public;
revoke execute on routine "public"."get_schema"() from "anon";
revoke execute on routine "public"."get_table_cell"(ref jsonb) from public;
revoke execute on routine "public"."get_table_cell"(ref jsonb) from "anon";
revoke execute on routine "public"."get_table_column"(ref jsonb) from public;
revoke execute on routine "public"."get_table_column"(ref jsonb) from "anon";
revoke execute on routine "public"."get_table_row"(ref jsonb) from public;
revoke execute on routine "public"."get_table_row"(ref jsonb) from "anon";
revoke execute on routine "public"."get_tables_and_columns"() from public;
revoke execute on routine "public"."get_tables_and_columns"() from "anon";
revoke execute on routine "public"."get_topic_overview"(p_topic_id uuid) from public;
revoke execute on routine "public"."get_topic_overview"(p_topic_id uuid) from "anon";
revoke execute on routine "public"."get_user_table_data_paginated"(p_table_id uuid, p_limit integer, p_offset integer, p_sort_field text, p_sort_direction text, p_search_term text) from public;
revoke execute on routine "public"."get_user_table_data_paginated"(p_table_id uuid, p_limit integer, p_offset integer, p_sort_field text, p_sort_direction text, p_search_term text) from "anon";
revoke execute on routine "public"."get_user_table_data_paginated_v2"(p_table_id uuid, p_limit integer, p_offset integer, p_sort_field text, p_sort_direction text, p_search_term text) from public;
revoke execute on routine "public"."get_user_table_data_paginated_v2"(p_table_id uuid, p_limit integer, p_offset integer, p_sort_field text, p_sort_direction text, p_search_term text) from "anon";
revoke execute on routine "public"."is_system_path"(p_path text) from public;
revoke execute on routine "public"."is_system_path"(p_path text) from "anon";
revoke execute on routine "public"."ivw_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."ivw_search_score"(p_query text, p_id uuid, p_title text, p_vision text, p_stage text, p_owner_email text) from public;
revoke execute on routine "public"."ivw_search_score"(p_query text, p_id uuid, p_title text, p_vision text, p_stage text, p_owner_email text) from "anon";
revoke execute on routine "public"."kg_simulated_scope_graph"(p_scope_id uuid) from public;
revoke execute on routine "public"."kg_simulated_scope_graph"(p_scope_id uuid) from "anon";
revoke execute on routine "public"."list_field_data_types"() from public;
revoke execute on routine "public"."list_field_data_types"() from "anon";
revoke execute on routine "public"."list_table_columns"(ref jsonb) from public;
revoke execute on routine "public"."list_table_columns"(ref jsonb) from "anon";
revoke execute on routine "public"."list_table_rows"(ref jsonb, limit_rows integer, offset_rows integer, order_by text, order_dir text) from public;
revoke execute on routine "public"."list_table_rows"(ref jsonb, limit_rows integer, offset_rows integer, order_by text, order_dir text) from "anon";
revoke execute on routine "public"."list_wizard_archetypes"() from public;
revoke execute on routine "public"."list_wizard_archetypes"() from "anon";
revoke execute on routine "public"."migration_slot"(p_filename text) from public;
revoke execute on routine "public"."migration_slot"(p_filename text) from "anon";
revoke execute on routine "public"."mkt_initiative_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."mkt_initiative_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."mkt_initiative_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_goal text, p_brand text) from public;
revoke execute on routine "public"."mkt_initiative_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_goal text, p_brand text) from "anon";
revoke execute on routine "public"."mkt_initiative_since_bucket"(p_bucket text) from public;
revoke execute on routine "public"."mkt_initiative_since_bucket"(p_bucket text) from "anon";
revoke execute on routine "public"."mtx_is_durable_media_url"(url text) from public;
revoke execute on routine "public"."mtx_is_durable_media_url"(url text) from "anon";
revoke execute on routine "public"."mtx_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_tags text[], p_owner_email text, p_extra_300 text[], p_extra_100 text[], p_deep_hit boolean) from public;
revoke execute on routine "public"."mtx_search_score"(p_query text, p_id uuid, p_name text, p_description text, p_tags text[], p_owner_email text, p_extra_300 text[], p_extra_100 text[], p_deep_hit boolean) from "anon";
revoke execute on routine "public"."owned_or_org_processed_document_ids"() from "anon";
revoke execute on routine "public"."research_topic_resource_manifest"(p_topic_id uuid) from "anon";
revoke execute on routine "public"."seo_rank_position_bucket"(p_position integer) from public;
revoke execute on routine "public"."seo_rank_position_bucket"(p_position integer) from "anon";
revoke execute on routine "public"."seo_rank_tracking_label"(p_engine text, p_search_type text) from public;
revoke execute on routine "public"."seo_rank_tracking_label"(p_engine text, p_search_type text) from "anon";
revoke execute on routine "public"."studio_session_metrics"(p_session_ids uuid[]) from public;
revoke execute on routine "public"."studio_session_metrics"(p_session_ids uuid[]) from "anon";
revoke execute on routine "public"."to_snake_case"(input_text text) from public;
revoke execute on routine "public"."to_snake_case"(input_text text) from "anon";
revoke execute on routine "public"."tool_executor_walk_parents"(p_name text) from public;
revoke execute on routine "public"."tool_executor_walk_parents"(p_name text) from "anon";
revoke execute on routine "public"."tool_resolve_bundle"(p_bundle_name text) from public;
revoke execute on routine "public"."tool_resolve_bundle"(p_bundle_name text) from "anon";
revoke execute on routine "public"."tool_surface_walk_parents"(p_surface_name text) from public;
revoke execute on routine "public"."tool_surface_walk_parents"(p_surface_name text) from "anon";
revoke execute on routine "public"."trx_duration_matches"(p_seconds numeric, p_bucket text) from public;
revoke execute on routine "public"."trx_duration_matches"(p_seconds numeric, p_bucket text) from "anon";
revoke execute on routine "public"."trx_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from public;
revoke execute on routine "public"."trx_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "public"."trx_search_score"(p_query text, p_id uuid, p_title text, p_description text, p_kind text, p_folder text, p_tags text[], p_owner_email text, p_deep_hit boolean) from public;
revoke execute on routine "public"."trx_search_score"(p_query text, p_id uuid, p_title text, p_description text, p_kind text, p_folder text, p_tags text[], p_owner_email text, p_deep_hit boolean) from "anon";
revoke execute on routine "public"."trx_words_matches"(p_words integer, p_bucket text) from public;
revoke execute on routine "public"."trx_words_matches"(p_words integer, p_bucket text) from "anon";
revoke execute on routine "public"."udt_column_facets"(p_table_id uuid, p_field_name text, p_limit integer, p_search_term text) from public;
revoke execute on routine "public"."udt_column_facets"(p_table_id uuid, p_field_name text, p_limit integer, p_search_term text) from "anon";
revoke execute on routine "public"."udt_table_profile"(p_table_id uuid, p_preview_values integer) from public;
revoke execute on routine "public"."udt_table_profile"(p_table_id uuid, p_preview_values integer) from "anon";
revoke execute on routine "public"."validate_slugs"(slug_array text[]) from public;
revoke execute on routine "public"."validate_slugs"(slug_array text[]) from "anon";
revoke execute on routine "public"."wfx_bucket_matches"(p_n bigint, p_bucket text) from public;
revoke execute on routine "public"."wfx_bucket_matches"(p_n bigint, p_bucket text) from "anon";
revoke execute on routine "public"."wfx_list_scoped"(p_scope text, p_org_id uuid, p_search text, p_deep boolean, p_sort text, p_dir text, p_favorites_first boolean, p_archived text, p_filters jsonb, p_limit integer, p_offset integer) from "anon";
revoke execute on routine "rag"."member_source_entity_token"(p_kind text) from public;
revoke execute on routine "scraper"."canonical_url"(u text) from public;
revoke execute on routine "seo"."_pack_band_recut"(p_old numeric) from public;
revoke execute on routine "seo"."_pack_geo_archetypes"(p_pack_id uuid, p_geo_places jsonb, p_geo_place_ids jsonb) from public;
revoke execute on routine "seo"."_pack_is_relative_value"(p_dimension_slug text, p_value text, p_label text) from public;
revoke execute on routine "seo"."_pack_site_value_id"(p_site_id uuid, p_scope text, p_dimension_slug text, p_value text) from public;
revoke execute on routine "seo"."_slugify"(p text) from public;
revoke execute on routine "seo"."assert_combo_shape"(p_site_id uuid, p_value_ids uuid[], p_effect text, p_amount numeric) from public;
revoke execute on routine "seo"."assert_safe_match_token"(p_token text, p_what text) from public;
revoke execute on routine "seo"."engine_schedule_resolve"(p_engine_slug text, p_site_ids uuid[]) from public;
revoke execute on routine "seo"."facet_dimension_readiness"(p_dimension_id uuid) from public;
revoke execute on routine "seo"."facet_site_slug"(p_site_id uuid, p_slug text) from public;
revoke execute on routine "seo"."facet_slugify"(p_text text) from public;
revoke execute on routine "seo"."fn_effective_stamps"(p_site_id uuid, p_keyword_ids uuid[]) from public;
revoke execute on routine "seo"."fn_merge_monthly"(p_old jsonb, p_new jsonb) from public;
revoke execute on routine "seo"."fn_normalize_phrase"(p text) from public;
revoke execute on routine "seo"."gsc_brand_aliases"(p_site_id uuid) from public;
revoke execute on routine "seo"."gsc_brand_generic_threshold"() from public;
revoke execute on routine "seo"."gsc_brand_hits"(p_site_id uuid) from public;
revoke execute on routine "seo"."gsc_dig_condition_passes"(p_op text, p_value numeric, p_threshold numeric) from public;
revoke execute on routine "seo"."gsc_dig_metric_value"(p_metric text, c_clicks bigint, c_imps bigint, c_ctr numeric, c_pos numeric, m_clicks bigint, m_imps bigint, m_ctr numeric, m_pos numeric) from public;
revoke execute on routine "seo"."gsc_effective_stamps"(p_site_id uuid, p_keyword_ids uuid[]) from public;
revoke execute on routine "seo"."gsc_keyword_class_map"(p_site_id uuid, p_keyword_ids uuid[]) from public;
revoke execute on routine "seo"."gsc_stamp_keyword_set"(p_site_id uuid, p_stamps jsonb) from public;
revoke execute on routine "seo"."gsc_topic_keyword_set"(p_topic_id uuid) from public;
revoke execute on routine "seo"."multi_location_knob"(p_key text, p_default numeric) from public;
revoke execute on routine "tool"."executor_walk_parents"(p_name text) from public;
revoke execute on routine "users"."normalize_preferences_jsonb"(p jsonb) from public;
revoke execute on routine "web"."crawl_cadence_min_gap_minutes"(p_cadence jsonb) from public;
revoke execute on routine "web"."cron_day_of_month_gap"(p_vals integer[]) from public;
revoke execute on routine "web"."cron_day_of_week_gap"(p_vals integer[]) from public;
revoke execute on routine "web"."cron_expand_field"(p_field text, p_lo integer, p_hi integer) from public;
revoke execute on routine "web"."cron_min_step"(p_vals integer[]) from public;
revoke execute on routine "web"."is_machine_resource_url"(page_url text) from public;
revoke execute on routine "web"."is_resource_content_type"(content_type_last text) from public;
revoke execute on routine "web"."matches_endpoint_rule"(page_url text, path_prefix text, query_param text) from public;
revoke execute on routine "web"."site_audit_rollup"(p_site_id uuid) from public;
revoke execute on routine "web"."site_audit_trend"(p_site_id uuid) from public;
revoke execute on routine "web"."site_gsc_daily"(p_site_id uuid, p_days integer) from public;
revoke execute on routine "web"."site_gsc_top_pages"(p_site_id uuid, p_days integer, p_limit integer) from public;
revoke execute on routine "web"."url_quality_metrics"(page_url text) from public;
revoke execute on routine "workflow"."unwatch_table"(p_table regclass) from public;

grant execute on routine "ai"."_validate_rules_envelope"(p_doc jsonb, p_where text) to "authenticated";
grant execute on routine "ai"."_validate_rules_envelope"(p_doc jsonb, p_where text) to "service_role";
grant execute on routine "ai"."audit_ui_enum_drift"() to "authenticated";
grant execute on routine "ai"."audit_ui_enum_drift"() to "service_role";
grant execute on routine "ai"."jsonb_num"(n numeric) to "service_role";
grant execute on routine "api"."fetch_foreign_key_info"() to "service_role";
grant execute on routine "api"."schema_table_column_relationships"(p_schema text) to "service_role";
grant execute on routine "api"."simple_foreign_key_info"() to "service_role";
grant execute on routine "audit"."effective_search_path"(p_proconfig text[]) to "authenticated";
grant execute on routine "audit"."effective_search_path"(p_proconfig text[]) to "service_role";
grant execute on routine "audit"."is_m2m_shape"(p_rel regclass) to "authenticated";
grant execute on routine "audit"."is_m2m_shape"(p_rel regclass) to "service_role";
grant execute on routine "billing"."period_reset"(p_period billing.meter_period) to "authenticated";
grant execute on routine "billing"."period_reset"(p_period billing.meter_period) to "service_role";
grant execute on routine "billing"."period_start"(p_period billing.meter_period) to "authenticated";
grant execute on routine "billing"."period_start"(p_period billing.meter_period) to "service_role";
grant execute on routine "chat"."_message_tool_call_ids"(p_content jsonb) to "authenticated";
grant execute on routine "chat"."_message_tool_call_ids"(p_content jsonb) to "service_role";
grant execute on routine "content_ir"."admission_enforced"() to "authenticated";
grant execute on routine "content_ir"."admission_enforced"() to "service_role";
grant execute on routine "content_ir"."assert_kind_admission"(p_organization_id uuid, p_kind text, p_version integer, p_context text) to "authenticated";
grant execute on routine "content_ir"."assert_kind_admission"(p_organization_id uuid, p_kind text, p_version integer, p_context text) to "service_role";
grant execute on routine "content_ir"."check_kind_admission"(p_organization_id uuid, p_kind text, p_version integer) to "authenticated";
grant execute on routine "content_ir"."check_kind_admission"(p_organization_id uuid, p_kind text, p_version integer) to "service_role";
grant execute on routine "content_ir"."compute_example_validation"(p_data jsonb, p_schema jsonb) to "authenticated";
grant execute on routine "content_ir"."compute_example_validation"(p_data jsonb, p_schema jsonb) to "service_role";
grant execute on routine "content_ir"."declare_kind_marker"(p_schema jsonb, p_slug text) to "authenticated";
grant execute on routine "content_ir"."declare_kind_marker"(p_schema jsonb, p_slug text) to "service_role";
grant execute on routine "content_ir"."declare_kind_markers_deep"(p_schema jsonb, p_slug text) to "authenticated";
grant execute on routine "content_ir"."declare_kind_markers_deep"(p_schema jsonb, p_slug text) to "service_role";
grant execute on routine "content_ir"."owned_child_instances"(p_ids uuid[]) to "authenticated";
grant execute on routine "content_ir"."owned_child_instances"(p_ids uuid[]) to "service_role";
grant execute on routine "content_ir"."stamp_markers_from_schema"(p_value jsonb, p_schema jsonb, p_root jsonb, p_depth integer) to "authenticated";
grant execute on routine "content_ir"."stamp_markers_from_schema"(p_value jsonb, p_schema jsonb, p_root jsonb, p_depth integer) to "service_role";
grant execute on routine "content_ir"."strip_kind_deep"(p jsonb) to "authenticated";
grant execute on routine "content_ir"."strip_kind_deep"(p jsonb) to "service_role";
grant execute on routine "context"."_strip_sql_noise"(p_src text) to "authenticated";
grant execute on routine "context"."_strip_sql_noise"(p_src text) to "service_role";
grant execute on routine "context"."parse_reference_fence"(p_value_text text) to "authenticated";
grant execute on routine "context"."parse_reference_fence"(p_value_text text) to "service_role";
grant execute on routine "context"."reference_item_ref_key"(p_type text, p_item jsonb) to "authenticated";
grant execute on routine "context"."reference_item_ref_key"(p_type text, p_item jsonb) to "service_role";
grant execute on routine "context"."slugify"(p text) to "authenticated";
grant execute on routine "context"."slugify"(p text) to "service_role";
grant execute on routine "context"."validate_reference_value"(p_item_id uuid, p_value_text text) to "authenticated";
grant execute on routine "context"."validate_reference_value"(p_item_id uuid, p_value_text text) to "service_role";
grant execute on routine "crm"."name_key"(p_name text) to "authenticated";
grant execute on routine "crm"."name_key"(p_name text) to "service_role";
grant execute on routine "esign"."_arm"() to "authenticated";
grant execute on routine "esign"."_arm"() to "service_role";
grant execute on routine "esign"."_disarm"() to "authenticated";
grant execute on routine "esign"."_disarm"() to "service_role";
grant execute on routine "esign"."_privileged"() to "authenticated";
grant execute on routine "esign"."_privileged"() to "service_role";
grant execute on routine "esign"."_requester_actor_type"(p_consumer_key text) to "authenticated";
grant execute on routine "esign"."_requester_actor_type"(p_consumer_key text) to "service_role";
grant execute on routine "hr"."_add_business_days"(p_start date, p_days integer, p_holidays date[], p_day_zero_counts boolean) to "authenticated";
grant execute on routine "hr"."_add_business_days"(p_start date, p_days integer, p_holidays date[], p_day_zero_counts boolean) to "service_role";
grant execute on routine "hr"."_applicability_verdict"(p_applicability jsonb, p_facts jsonb) to "authenticated";
grant execute on routine "hr"."_applicability_verdict"(p_applicability jsonb, p_facts jsonb) to "service_role";
grant execute on routine "hr"."_approval_subject_required"(p_target_table text) to "authenticated";
grant execute on routine "hr"."_approval_subject_required"(p_target_table text) to "service_role";
grant execute on routine "hr"."_door_spec"(p_token text) to "authenticated";
grant execute on routine "hr"."_door_spec"(p_token text) to "service_role";
grant execute on routine "hr"."_hours_text"(p_hours numeric) to "authenticated";
grant execute on routine "hr"."_hours_text"(p_hours numeric) to "service_role";
grant execute on routine "hr"."_ics_escape"(p_text text) to "authenticated";
grant execute on routine "hr"."_ics_escape"(p_text text) to "service_role";
grant execute on routine "hr"."_leave_blackout_hits"(p_rule jsonb, p_starts date, p_ends date) to "authenticated";
grant execute on routine "hr"."_leave_blackout_hits"(p_rule jsonb, p_starts date, p_ends date) to "service_role";
grant execute on routine "hr"."_leave_config_parameters"(p_class text, p_policy jsonb) to "authenticated";
grant execute on routine "hr"."_leave_config_parameters"(p_class text, p_policy jsonb) to "service_role";
grant execute on routine "hr"."_leave_deduction_clause"(p_fig jsonb) to "authenticated";
grant execute on routine "hr"."_leave_deduction_clause"(p_fig jsonb) to "service_role";
grant execute on routine "hr"."_leave_floor_field"(p_field text, p_floor jsonb, p_configured jsonb, p_direction text, p_rule_status text, p_unverified jsonb, p_param_key text, p_sentence text) to "authenticated";
grant execute on routine "hr"."_leave_floor_field"(p_field text, p_floor jsonb, p_configured jsonb, p_direction text, p_rule_status text, p_unverified jsonb, p_param_key text, p_sentence text) to "service_role";
grant execute on routine "hr"."_leave_hours_text"(p_hours numeric) to "authenticated";
grant execute on routine "hr"."_leave_hours_text"(p_hours numeric) to "service_role";
grant execute on routine "hr"."_leave_ledger_sentence"(p_entry_kind text, p_occurred_on date, p_starts_on date, p_ends_on date, p_request_state text, p_source_workweek_id uuid, p_leave_request_id uuid, p_hours_delta numeric, p_note text) to "authenticated";
grant execute on routine "hr"."_leave_ledger_sentence"(p_entry_kind text, p_occurred_on date, p_starts_on date, p_ends_on date, p_request_state text, p_source_workweek_id uuid, p_leave_request_id uuid, p_hours_delta numeric, p_note text) to "service_role";
grant execute on routine "hr"."_leave_policy_constraint_violation"(p_constraint text, p_payload jsonb) to "authenticated";
grant execute on routine "hr"."_leave_policy_constraint_violation"(p_constraint text, p_payload jsonb) to "service_role";
grant execute on routine "hr"."_leave_sentence"(p_fig jsonb) to "authenticated";
grant execute on routine "hr"."_leave_sentence"(p_fig jsonb) to "service_role";
grant execute on routine "hr"."_leave_span_is_costless"(p_span jsonb) to "authenticated";
grant execute on routine "hr"."_leave_span_is_costless"(p_span jsonb) to "service_role";
grant execute on routine "hr"."_leave_unknown_axes"(p_filters jsonb, p_allowed text[]) to "authenticated";
grant execute on routine "hr"."_leave_unknown_axes"(p_filters jsonb, p_allowed text[]) to "service_role";
grant execute on routine "hr"."_legality_envelope"(p_class text, p_rules jsonb) to "authenticated";
grant execute on routine "hr"."_legality_envelope"(p_class text, p_rules jsonb) to "service_role";
grant execute on routine "hr"."_note_kind_caps"(p_note_kind text) to "authenticated";
grant execute on routine "hr"."_note_kind_caps"(p_note_kind text) to "service_role";
grant execute on routine "hr"."_org_row_less_protective"(p_class text, p_org jsonb, p_sys jsonb) to "authenticated";
grant execute on routine "hr"."_org_row_less_protective"(p_class text, p_org jsonb, p_sys jsonb) to "service_role";
grant execute on routine "hr"."_punch_allowed_kinds"(p_state text) to "authenticated";
grant execute on routine "hr"."_punch_allowed_kinds"(p_state text) to "service_role";
grant execute on routine "hr"."_punch_attest_axis"(p_response jsonb, p_axis text, p_field text) to "authenticated";
grant execute on routine "hr"."_punch_attest_axis"(p_response jsonb, p_axis text, p_field text) to "service_role";
grant execute on routine "hr"."_punch_kind_rank"(p_kind text) to "authenticated";
grant execute on routine "hr"."_punch_kind_rank"(p_kind text) to "service_role";
grant execute on routine "hr"."_punch_next_state"(p_state text, p_kind text, p_break_paid boolean) to "authenticated";
grant execute on routine "hr"."_punch_next_state"(p_state text, p_kind text, p_break_paid boolean) to "service_role";
grant execute on routine "hr"."_punch_refusal"(p_code text, p_message text, p_details jsonb) to "authenticated";
grant execute on routine "hr"."_punch_refusal"(p_code text, p_message text, p_details jsonb) to "service_role";
grant execute on routine "hr"."_recompute_workweek_start"(p_employment_id uuid, p_local_work_date date) to "authenticated";
grant execute on routine "hr"."_recompute_workweek_start"(p_employment_id uuid, p_local_work_date date) to "service_role";
grant execute on routine "hr"."_week_start_is_provisional"(p_employment_id uuid) to "authenticated";
grant execute on routine "hr"."_week_start_is_provisional"(p_employment_id uuid) to "service_role";
grant execute on routine "hr"."_wf_decision_words_short"(p_outcome text) to "authenticated";
grant execute on routine "hr"."_wf_decision_words_short"(p_outcome text) to "service_role";
grant execute on routine "hr"."_wf_failure_sentence"(p_class text) to "authenticated";
grant execute on routine "hr"."_wf_failure_sentence"(p_class text) to "service_role";
grant execute on routine "hr"."alert_recipients"(p_organization_id uuid, p_alert_family text, p_event_key text, p_scope_kind text, p_scope_id uuid, p_tier text) to "authenticated";
grant execute on routine "hr"."alert_recipients"(p_organization_id uuid, p_alert_family text, p_event_key text, p_scope_kind text, p_scope_id uuid, p_tier text) to "service_role";
grant execute on routine "hr"."compensation_as_of"(p_employment_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."compensation_as_of"(p_employment_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."corrective_action_state"(p_outcome text, p_acknowledgement_kind text, p_acknowledged_at timestamp with time zone, p_follow_up_on date) to "authenticated";
grant execute on routine "hr"."corrective_action_state"(p_outcome text, p_acknowledgement_kind text, p_acknowledged_at timestamp with time zone, p_follow_up_on date) to "service_role";
grant execute on routine "hr"."elapsed_hours"(p_start_local timestamp without time zone, p_end_local timestamp without time zone, p_tz text) to "authenticated";
grant execute on routine "hr"."elapsed_hours"(p_start_local timestamp without time zone, p_end_local timestamp without time zone, p_tz text) to "service_role";
grant execute on routine "hr"."employment_as_of"(p_employee_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."employment_as_of"(p_employee_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."hr_links_without_employer"() to "authenticated";
grant execute on routine "hr"."hr_links_without_employer"() to "service_role";
grant execute on routine "hr"."incident_next_step_sentence"(p_state text, p_follow_up_on date) to "authenticated";
grant execute on routine "hr"."incident_next_step_sentence"(p_state text, p_follow_up_on date) to "service_role";
grant execute on routine "hr"."incident_state_label"(p_state text) to "authenticated";
grant execute on routine "hr"."incident_state_label"(p_state text) to "service_role";
grant execute on routine "hr"."leave_notification_gap"() to "authenticated";
grant execute on routine "hr"."leave_notification_gap"() to "service_role";
grant execute on routine "hr"."leave_seal_door"(p_proname text, p_mode text) to "authenticated";
grant execute on routine "hr"."leave_seal_door"(p_proname text, p_mode text) to "service_role";
grant execute on routine "hr"."manager_as_of"(p_employment_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."manager_as_of"(p_employment_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."normalize_org_jurisdiction_rule_parameters"(p_rule_class text, p_parameters jsonb) to "authenticated";
grant execute on routine "hr"."normalize_org_jurisdiction_rule_parameters"(p_rule_class text, p_parameters jsonb) to "service_role";
grant execute on routine "hr"."org_chart_as_of"(p_organization_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."org_chart_as_of"(p_organization_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."org_jurisdiction_rule_validation_parameters"(p_rule_class text, p_parameters jsonb) to "authenticated";
grant execute on routine "hr"."org_jurisdiction_rule_validation_parameters"(p_rule_class text, p_parameters jsonb) to "service_role";
grant execute on routine "hr"."position_as_of"(p_employment_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."position_as_of"(p_employment_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."primary_position_as_of"(p_employment_id uuid, p_on date) to "authenticated";
grant execute on routine "hr"."primary_position_as_of"(p_employment_id uuid, p_on date) to "service_role";
grant execute on routine "hr"."punch_edit_notify_debt"() to "authenticated";
grant execute on routine "hr"."punch_edit_notify_debt"() to "service_role";
grant execute on routine "hr"."punch_knobs_missing"() to "authenticated";
grant execute on routine "hr"."punch_knobs_missing"() to "service_role";
grant execute on routine "iam"."_api_key_base62"(p_bytes bytea) to "authenticated";
grant execute on routine "iam"."_api_key_base62"(p_bytes bytea) to "service_role";
grant execute on routine "iam"."_client_grant_column_list"(p_rel regclass, p_excluded text[]) to "authenticated";
grant execute on routine "iam"."_client_grant_column_list"(p_rel regclass, p_excluded text[]) to "service_role";
grant execute on routine "iam"."_dd171_containment_filter"(p_has_vis boolean, p_alias text, p_joiner text) to "authenticated";
grant execute on routine "iam"."_dd171_containment_filter"(p_has_vis boolean, p_alias text, p_joiner text) to "service_role";
grant execute on routine "iam"."_fk_check13"() to "authenticated";
grant execute on routine "iam"."_fk_check13"() to "service_role";
grant execute on routine "iam"."_fk_gap_orphans"() to "authenticated";
grant execute on routine "iam"."_fk_gap_orphans"() to "service_role";
grant execute on routine "iam"."_fk_high_orphans"() to "authenticated";
grant execute on routine "iam"."_fk_high_orphans"() to "service_role";
grant execute on routine "iam"."_resolve_owner_column"(p_schema text, p_table text, p_pref text) to "authenticated";
grant execute on routine "iam"."_resolve_owner_column"(p_schema text, p_table text, p_pref text) to "service_role";
grant execute on routine "iam"."access_resolver_disagreements"(p_rows integer, p_token text, p_users integer) to "authenticated";
grant execute on routine "iam"."auto_organization_name"(p_meta jsonb, p_email text) to "authenticated";
grant execute on routine "iam"."auto_organization_name"(p_meta jsonb, p_email text) to "service_role";
grant execute on routine "iam"."canonical_certify"(p_schema text, p_table text, p_token text) to "authenticated";
grant execute on routine "iam"."canonical_certify"(p_schema text, p_table text, p_token text) to "service_role";
grant execute on routine "iam"."canonical_certify_ok"(p_schema text, p_table text, p_token text) to "authenticated";
grant execute on routine "iam"."canonical_certify_ok"(p_schema text, p_table text, p_token text) to "service_role";
grant execute on routine "iam"."client_role_can_read"(p_rel regclass, p_role text) to "authenticated";
grant execute on routine "iam"."client_role_can_read"(p_rel regclass, p_role text) to "service_role";
grant execute on routine "iam"."component_original_lane"(p_schema text, p_table text, p_token text) to "authenticated";
grant execute on routine "iam"."component_original_lane"(p_schema text, p_table text, p_token text) to "service_role";
grant execute on routine "iam"."component_wider_than_parent"(p_principals uuid[], p_token text) to "authenticated";
grant execute on routine "iam"."component_wider_than_parent"(p_principals uuid[], p_token text) to "service_role";
grant execute on routine "iam"."derive_organization_abbreviation"(p_name text, p_is_personal boolean) to "authenticated";
grant execute on routine "iam"."derive_organization_abbreviation"(p_name text, p_is_personal boolean) to "service_role";
grant execute on routine "iam"."entity_read_equivalence"(p_schema text, p_table text, p_token text, p_user uuid, p_limit integer, p_baseline text) to "authenticated";
grant execute on routine "iam"."entity_read_equivalence"(p_schema text, p_table text, p_token text, p_user uuid, p_limit integer, p_baseline text) to "service_role";
grant execute on routine "iam"."entity_read_kernel_expected"() to "authenticated";
grant execute on routine "iam"."entity_read_kernel_expected"() to "service_role";
grant execute on routine "iam"."entity_read_kernel_fingerprint"() to "authenticated";
grant execute on routine "iam"."entity_read_kernel_fingerprint"() to "service_role";
grant execute on routine "iam"."entity_read_lane_preflight"() to "authenticated";
grant execute on routine "iam"."entity_read_lane_preflight"() to "service_role";
grant execute on routine "iam"."entity_read_probe_users"(p_limit integer) to "authenticated";
grant execute on routine "iam"."entity_read_probe_users"(p_limit integer) to "service_role";
grant execute on routine "iam"."generated_policy_names"() to "authenticated";
grant execute on routine "iam"."generated_policy_names"() to "service_role";
grant execute on routine "iam"."is_trusted_backend"() to "authenticated";
grant execute on routine "iam"."is_trusted_backend"() to "service_role";
grant execute on routine "iam"."org_readable"(p_org uuid, p_token text) to "authenticated";
grant execute on routine "iam"."org_readable"(p_org uuid, p_token text) to "service_role";
grant execute on routine "iam"."platform_admin_read_prefix"(p_token text) to "authenticated";
grant execute on routine "iam"."platform_admin_read_prefix"(p_token text) to "service_role";
grant execute on routine "iam"."privacy_wall_read_lane_parity"(p_limit integer) to "authenticated";
grant execute on routine "iam"."privacy_wall_read_lane_parity"(p_limit integer) to "service_role";
grant execute on routine "iam"."sweep_governance_guards"(IN p_lock_timeout text) to "authenticated";
grant execute on routine "iam"."sweep_governance_guards"(IN p_lock_timeout text) to "service_role";
grant execute on routine "iam"."table_has_visibility"(p_schema text, p_table text) to "authenticated";
grant execute on routine "iam"."table_has_visibility"(p_schema text, p_table text) to "service_role";
grant execute on routine "iam"."token_is_parented_component"(p_token text) to "authenticated";
grant execute on routine "iam"."token_is_parented_component"(p_token text) to "service_role";
grant execute on routine "iam"."verify_canonical"(p_schema text, p_table text, p_token text, p_variant text) to "authenticated";
grant execute on routine "iam"."verify_canonical"(p_schema text, p_table text, p_token text, p_variant text) to "service_role";
grant execute on routine "iam"."verify_canonical_ok"(p_schema text, p_table text, p_token text, p_variant text) to "authenticated";
grant execute on routine "iam"."verify_canonical_ok"(p_schema text, p_table text, p_token text, p_variant text) to "service_role";
grant execute on routine "mandate"."generate_app_mandate_key"(p_slug text, p_name text) to "authenticated";
grant execute on routine "mandate"."generate_app_mandate_key"(p_slug text, p_name text) to "service_role";
grant execute on routine "mandate"."generate_shortcut_mandate_key"(p_label text, p_surface text) to "authenticated";
grant execute on routine "mandate"."generate_shortcut_mandate_key"(p_label text, p_surface text) to "service_role";
grant execute on routine "mandate"."sanitize_app_segment"(p_seg text) to "authenticated";
grant execute on routine "mandate"."sanitize_app_segment"(p_seg text) to "service_role";
grant execute on routine "mandate"."sanitize_shortcut_segment"(p_seg text) to "authenticated";
grant execute on routine "mandate"."sanitize_shortcut_segment"(p_seg text) to "service_role";
grant execute on routine "mandate"."shortcut_slug"(p_text text) to "authenticated";
grant execute on routine "mandate"."shortcut_slug"(p_text text) to "service_role";
grant execute on routine "mandate"."shortcut_treatment_config"(p_row jsonb) to "authenticated";
grant execute on routine "mandate"."shortcut_treatment_config"(p_row jsonb) to "service_role";
grant execute on routine "mandate"."validate_treatment_config"(p_tier text, p_config jsonb) to "authenticated";
grant execute on routine "mandate"."validate_treatment_config"(p_tier text, p_config jsonb) to "service_role";
grant execute on routine "platform"."_cf_as_double"(p_value jsonb) to "authenticated";
grant execute on routine "platform"."_cf_as_double"(p_value jsonb) to "service_role";
grant execute on routine "platform"."_cf_int_opt"(p_rules jsonb, p_name text) to "authenticated";
grant execute on routine "platform"."_cf_int_opt"(p_rules jsonb, p_name text) to "service_role";
grant execute on routine "platform"."_cf_num_opt"(p_rules jsonb, p_name text) to "authenticated";
grant execute on routine "platform"."_cf_num_opt"(p_rules jsonb, p_name text) to "service_role";
grant execute on routine "platform"."_cf_options"(p_definition jsonb) to "authenticated";
grant execute on routine "platform"."_cf_options"(p_definition jsonb) to "service_role";
grant execute on routine "platform"."_cf_pattern_fails"(p_value text, p_pattern text) to "authenticated";
grant execute on routine "platform"."_cf_pattern_fails"(p_value text, p_pattern text) to "service_role";
grant execute on routine "platform"."_cf_str_array"(p_value jsonb) to "authenticated";
grant execute on routine "platform"."_cf_str_array"(p_value jsonb) to "service_role";
grant execute on routine "platform"."_cf_valid_date"(p_value text) to "authenticated";
grant execute on routine "platform"."_cf_valid_date"(p_value text) to "service_role";
grant execute on routine "platform"."_cf_valid_datetime"(p_value text) to "authenticated";
grant execute on routine "platform"."_cf_valid_datetime"(p_value text) to "service_role";
grant execute on routine "platform"."assert_no_stale_rowtype_triggers"() to "authenticated";
grant execute on routine "platform"."assert_no_stale_rowtype_triggers"() to "service_role";
grant execute on routine "platform"."cf_compact_json"(p_value jsonb) to "authenticated";
grant execute on routine "platform"."cf_compact_json"(p_value jsonb) to "service_role";
grant execute on routine "platform"."cf_re_email"() to "authenticated";
grant execute on routine "platform"."cf_re_email"() to "service_role";
grant execute on routine "platform"."cf_re_url"() to "authenticated";
grant execute on routine "platform"."cf_re_url"() to "service_role";
grant execute on routine "platform"."cf_ws_class"() to "authenticated";
grant execute on routine "platform"."cf_ws_class"() to "service_role";
grant execute on routine "platform"."client_directive_notice_id"() to "authenticated";
grant execute on routine "platform"."client_directive_notice_id"() to "service_role";
grant execute on routine "platform"."client_excluded_column_report"() to "authenticated";
grant execute on routine "platform"."client_excluded_column_report"() to "service_role";
grant execute on routine "platform"."custom_field_index_name"(p_definition_id uuid) to "authenticated";
grant execute on routine "platform"."custom_field_index_name"(p_definition_id uuid) to "service_role";
grant execute on routine "platform"."dead_relation_read"(p_old text, p_new text) to "authenticated";
grant execute on routine "platform"."dead_relation_read"(p_old text, p_new text) to "service_role";
grant execute on routine "platform"."derive_data_class"(p_variant text, p_visibility text) to "authenticated";
grant execute on routine "platform"."derive_data_class"(p_variant text, p_visibility text) to "service_role";
grant execute on routine "platform"."derive_list_scope"(p_variant text, p_class platform.data_class) to "authenticated";
grant execute on routine "platform"."derive_list_scope"(p_variant text, p_class platform.data_class) to "service_role";
grant execute on routine "platform"."module_config"(p_org uuid, p_token text) to "authenticated";
grant execute on routine "platform"."module_config"(p_org uuid, p_token text) to "service_role";
grant execute on routine "platform"."normalize_identity_args"(p_args text) to "authenticated";
grant execute on routine "platform"."normalize_identity_args"(p_args text) to "service_role";
grant execute on routine "platform"."render_record_name"(p_template text, p_data jsonb, p_first_text_key text, p_id uuid) to "authenticated";
grant execute on routine "platform"."render_record_name"(p_template text, p_data jsonb, p_first_text_key text, p_id uuid) to "service_role";
grant execute on routine "platform"."soft_delete_orphan_census"() to "authenticated";
grant execute on routine "platform"."soft_delete_orphan_census"() to "service_role";
grant execute on routine "rag"."member_source_entity_token"(p_kind text) to "authenticated";
grant execute on routine "rag"."member_source_entity_token"(p_kind text) to "service_role";
grant execute on routine "scraper"."canonical_url"(u text) to "authenticated";
grant execute on routine "scraper"."canonical_url"(u text) to "service_role";
grant execute on routine "seo"."_pack_band_recut"(p_old numeric) to "authenticated";
grant execute on routine "seo"."_pack_band_recut"(p_old numeric) to "service_role";
grant execute on routine "seo"."_pack_is_relative_value"(p_dimension_slug text, p_value text, p_label text) to "authenticated";
grant execute on routine "seo"."_pack_is_relative_value"(p_dimension_slug text, p_value text, p_label text) to "service_role";
grant execute on routine "seo"."_pack_site_value_id"(p_site_id uuid, p_scope text, p_dimension_slug text, p_value text) to "authenticated";
grant execute on routine "seo"."_pack_site_value_id"(p_site_id uuid, p_scope text, p_dimension_slug text, p_value text) to "service_role";
grant execute on routine "seo"."_slugify"(p text) to "authenticated";
grant execute on routine "seo"."_slugify"(p text) to "service_role";
grant execute on routine "seo"."facet_dimension_readiness"(p_dimension_id uuid) to "service_role";
grant execute on routine "seo"."facet_site_slug"(p_site_id uuid, p_slug text) to "authenticated";
grant execute on routine "seo"."facet_site_slug"(p_site_id uuid, p_slug text) to "service_role";
grant execute on routine "seo"."facet_slugify"(p_text text) to "authenticated";
grant execute on routine "seo"."facet_slugify"(p_text text) to "service_role";
grant execute on routine "seo"."fn_merge_monthly"(p_old jsonb, p_new jsonb) to "authenticated";
grant execute on routine "seo"."fn_merge_monthly"(p_old jsonb, p_new jsonb) to "service_role";
grant execute on routine "seo"."fn_normalize_phrase"(p text) to "authenticated";
grant execute on routine "seo"."fn_normalize_phrase"(p text) to "service_role";
grant execute on routine "seo"."gsc_brand_aliases"(p_site_id uuid) to "service_role";
grant execute on routine "seo"."gsc_brand_generic_threshold"() to "service_role";
grant execute on routine "seo"."gsc_brand_hits"(p_site_id uuid) to "service_role";
grant execute on routine "seo"."gsc_dig_condition_passes"(p_op text, p_value numeric, p_threshold numeric) to "service_role";
grant execute on routine "seo"."gsc_dig_metric_value"(p_metric text, c_clicks bigint, c_imps bigint, c_ctr numeric, c_pos numeric, m_clicks bigint, m_imps bigint, m_ctr numeric, m_pos numeric) to "service_role";
grant execute on routine "seo"."gsc_effective_stamps"(p_site_id uuid, p_keyword_ids uuid[]) to "authenticated";
grant execute on routine "seo"."gsc_effective_stamps"(p_site_id uuid, p_keyword_ids uuid[]) to "service_role";
grant execute on routine "seo"."gsc_keyword_class_map"(p_site_id uuid, p_keyword_ids uuid[]) to "authenticated";
grant execute on routine "seo"."gsc_keyword_class_map"(p_site_id uuid, p_keyword_ids uuid[]) to "service_role";
grant execute on routine "seo"."gsc_stamp_keyword_set"(p_site_id uuid, p_stamps jsonb) to "authenticated";
grant execute on routine "seo"."gsc_stamp_keyword_set"(p_site_id uuid, p_stamps jsonb) to "service_role";
grant execute on routine "seo"."gsc_topic_keyword_set"(p_topic_id uuid) to "service_role";
grant execute on routine "seo"."multi_location_knob"(p_key text, p_default numeric) to "authenticated";
grant execute on routine "seo"."multi_location_knob"(p_key text, p_default numeric) to "service_role";
grant execute on routine "tool"."executor_walk_parents"(p_name text) to "authenticated";
grant execute on routine "tool"."executor_walk_parents"(p_name text) to "service_role";
grant execute on routine "users"."normalize_preferences_jsonb"(p jsonb) to "authenticated";
grant execute on routine "users"."normalize_preferences_jsonb"(p jsonb) to "service_role";
grant execute on routine "web"."crawl_cadence_min_gap_minutes"(p_cadence jsonb) to "authenticated";
grant execute on routine "web"."crawl_cadence_min_gap_minutes"(p_cadence jsonb) to "service_role";
grant execute on routine "web"."cron_day_of_month_gap"(p_vals integer[]) to "authenticated";
grant execute on routine "web"."cron_day_of_month_gap"(p_vals integer[]) to "service_role";
grant execute on routine "web"."cron_day_of_week_gap"(p_vals integer[]) to "authenticated";
grant execute on routine "web"."cron_day_of_week_gap"(p_vals integer[]) to "service_role";
grant execute on routine "web"."cron_expand_field"(p_field text, p_lo integer, p_hi integer) to "authenticated";
grant execute on routine "web"."cron_expand_field"(p_field text, p_lo integer, p_hi integer) to "service_role";
grant execute on routine "web"."cron_min_step"(p_vals integer[]) to "authenticated";
grant execute on routine "web"."cron_min_step"(p_vals integer[]) to "service_role";
grant execute on routine "web"."is_machine_resource_url"(page_url text) to "authenticated";
grant execute on routine "web"."is_machine_resource_url"(page_url text) to "service_role";
grant execute on routine "web"."is_resource_content_type"(content_type_last text) to "authenticated";
grant execute on routine "web"."is_resource_content_type"(content_type_last text) to "service_role";
grant execute on routine "web"."matches_endpoint_rule"(page_url text, path_prefix text, query_param text) to "authenticated";
grant execute on routine "web"."matches_endpoint_rule"(page_url text, path_prefix text, query_param text) to "service_role";
grant execute on routine "workflow"."unwatch_table"(p_table regclass) to "authenticated";
grant execute on routine "workflow"."unwatch_table"(p_table regclass) to "service_role";
