/**
 * Opening a saved board never asks "which organization is this for".
 *
 * A note tile whose draft was never saved is started again on reload
 * (`NoteItemBody`, plan step "draft"). That restart used the "new note"
 * resolver, which asks the person when no organization is selected — on every
 * reload of a board that held an unsent note. The board names its own
 * organization; restoring files under it. A NEW note still asks.
 */
import { act } from "react";
import { createRoot } from "react-dom/client";

(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

async function mount(node: React.ReactElement) {
  const host = document.createElement("div");
  document.body.appendChild(host);
  const root = createRoot(host);
  await act(async () => {
    root.render(node);
  });
  await act(async () => {
    await new Promise((r) => setTimeout(r, 20));
  });
  return () => act(() => root.unmount());
}

const resolveOrganization = jest.fn(async () => "org-from-gate");
const initializeAutogeneratedNote = jest.fn((arg: unknown) => ({ type: "init", arg }));
const dispatched: { type: string; payload?: Record<string, unknown> }[] = [];
const created = () => dispatched.find((a) => a.type === "notes/createAutogeneratedNote")?.payload;

jest.mock("@/lib/redux/hooks", () => ({
  useAppDispatch: () => (action: { type: string; arg: unknown }) => {
    dispatched.push(action as never);
    return { unwrap: async () => action.arg };
  },
  useAppSelector: () => undefined,
  useAppStore: () => ({ getState: () => ({ userAuth: { id: "user-1" }, notes: { notes: {} }, appContext: { organization_id: "org-active" } }) }),
}));
jest.mock("@/features/notes/hooks/useNewNoteOrganization", () => ({
  useNewNoteOrganization: () => resolveOrganization,
}));
jest.mock("@/features/notes/redux/thunks", () => ({
  initializeAutogeneratedNote: (arg: unknown) => initializeAutogeneratedNote(arg),
}));
jest.mock("@/features/notes/redux/selectors", () => ({ selectNoteById: () => () => undefined }));
jest.mock("@/features/notes/service/notesApi", () => ({
  NotesAPI: { getById: jest.fn(async () => null), create: jest.fn() },
}));
jest.mock("@/features/notes/components/NoteWorkspace", () => ({ NoteWorkspace: () => null }));
jest.mock("@ai-matrx/design-system", () => ({ ErrorNotice: () => null }));

import { NoteItemBody } from "../items/NoteItemBody";
import { BoardOrganizationProvider } from "../items/board-organization";
import { noteDraftSource } from "../items/work-sources";
import type { NodeSource } from "../board/document";

const props = (source: NodeSource) => ({
  tileId: "t1",
  source,
  title: "Note",
  tier: "full" as never,
  interacting: false,
  onSource: jest.fn(),
});

describe("a restored note draft", () => {
  beforeEach(() => {
    resolveOrganization.mockClear();
    initializeAutogeneratedNote.mockClear();
    dispatched.length = 0;
  });

  it("files under the board's own organization and never asks", async () => {
    const source = noteDraftSource({ kind: "entity", entity: "note", id: "x" } as NodeSource, "11111111-1111-4111-8111-111111111111");
    const unmount = await mount(
      <BoardOrganizationProvider value="org-of-board">
        <NoteItemBody {...props(source)} />
      </BoardOrganizationProvider>,
    );
    expect(initializeAutogeneratedNote).toHaveBeenCalled();
    expect(resolveOrganization).not.toHaveBeenCalled();
    expect(initializeAutogeneratedNote.mock.calls[0][0]).toMatchObject({ organizationId: "org-of-board" });
    await unmount();
  });

  it("with no saved board it still goes through the gate", async () => {
    const source = noteDraftSource({ kind: "entity", entity: "note", id: "x" } as NodeSource, "11111111-1111-4111-8111-111111111111");
    const unmount = await mount(<NoteItemBody {...props(source)} />);
    expect(initializeAutogeneratedNote).toHaveBeenCalled();
    expect(resolveOrganization).toHaveBeenCalledTimes(1);
    await unmount();
  });
});

describe("a titled new note tile (an agent's board_add_items title)", () => {
  beforeEach(() => {
    resolveOrganization.mockClear();
    initializeAutogeneratedNote.mockClear();
    dispatched.length = 0;
  });

  it("starts its draft with that title and remembers it on the tile", async () => {
    const onSource = jest.fn();
    const unmount = await mount(
      <NoteItemBody
        {...props({ kind: "entity", entity: "note", id: null } as NodeSource)}
        title="Watering schedule"
        onSource={onSource}
      />,
    );
    // A new draft is in the store at once (no folder read, no gate): its label rides on that action.
    expect(initializeAutogeneratedNote).not.toHaveBeenCalled();
    expect(created()).toMatchObject({ label: "Watering schedule", folder: null, organizationId: "org-active" });
    expect(onSource.mock.calls[0][0]).toMatchObject({ meta: { draft: "1", label: "Watering schedule" } });
    await unmount();
  });

  it("a blank tile keeps the notes default name", async () => {
    const unmount = await mount(<NoteItemBody {...props({ kind: "entity", entity: "note", id: null } as NodeSource)} />);
    expect(created()).not.toHaveProperty("label");
    await unmount();
  });

  it("a reload starts the draft again with the remembered title", async () => {
    const source = noteDraftSource(
      { kind: "entity", entity: "note", id: null } as NodeSource,
      "11111111-1111-4111-8111-111111111111",
      "Watering schedule",
    );
    const unmount = await mount(
      <BoardOrganizationProvider value="org-of-board">
        <NoteItemBody {...props(source)} />
      </BoardOrganizationProvider>,
    );
    expect(initializeAutogeneratedNote.mock.calls[0][0]).toMatchObject({ label: "Watering schedule" });
    await unmount();
  });
});
