#!/usr/bin/env tsx
/**
 * Refresh the live-DB truth snapshot → scripts/schema-check/current-schema.json.
 *
 * The FE has no direct Postgres connection (PostgREST only), so it pulls truth
 * from the read-only `public.schema_truth_snapshot()` RPC (migration
 * `schema_truth_snapshot_rpc.sql`) — structural metadata only, no row data. Same
 * live DB the aidream backend reads, so the two snapshots agree.
 *
 *   pnpm check:schema:refresh        # pull live, rewrite the snapshot
 *
 * Falls back to ../aidream/db/schema_analysis/current_schemas.json if the DB is
 * unreachable. Exits non-zero only when it cannot produce a snapshot at all; the
 * committed snapshot keeps the offline checks working in between refreshes.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT = resolve(ROOT, "scripts/schema-check/current-schema.json");
const C = { reset: "\x1b[0m", dim: "\x1b[2m", red: "\x1b[31m", green: "\x1b[32m", yellow: "\x1b[33m", cyan: "\x1b[36m" };

function loadEnv(): { url: string; key: string } | null {
  let url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? process.env.SUPABASE_URL ?? "";
  let key =
    process.env.SUPABASE_SECRET_KEY ??
    process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
    process.env.SUPABASE_PUBLISHABLE_KEY ??
    "";
  if (!url || !key) {
    for (const f of [".env.local", ".env.production.local", ".env.production", ".env"]) {
      const p = resolve(ROOT, f);
      if (!existsSync(p)) continue;
      for (const line of readFileSync(p, "utf8").split("\n")) {
        const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.+?)\s*$/);
        if (!m) continue;
        const v = (m[2] ?? "").replace(/^['"]|['"]$/g, "");
        if (!url && (m[1] === "NEXT_PUBLIC_SUPABASE_URL" || m[1] === "SUPABASE_URL")) url = v;
        if (
          !key &&
          (m[1] === "SUPABASE_SECRET_KEY" ||
            m[1] === "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY" ||
            m[1] === "SUPABASE_PUBLISHABLE_KEY")
        )
          key = v;
      }
      if (url && key) break;
    }
  }
  return url && key ? { url, key } : null;
}

async function pullViaRpc(url: string, key: string): Promise<any | null> {
  const endpoint = `${url.replace(/\/$/, "")}/rest/v1/rpc/schema_truth_snapshot`;
  try {
    const res = await fetch(endpoint, {
      method: "POST",
      headers: {
        apikey: key,
        Authorization: `Bearer ${key}`,
        "Content-Type": "application/json",
        Accept: "application/json",
        "Content-Profile": "public",
        "Accept-Profile": "public",
      },
      body: "{}",
    });
    if (!res.ok) {
      console.error(`${C.yellow}[WARN]${C.reset} RPC schema_truth_snapshot failed (${res.status}). ${C.dim}${(await res.text()).slice(0, 200)}${C.reset}`);
      return null;
    }
    return await res.json();
  } catch (err) {
    console.error(`${C.yellow}[WARN]${C.reset} could not reach Supabase: ${String(err)}`);
    return null;
  }
}

function fromAidream(): any | null {
  const p = resolve(ROOT, "../aidream/db/schema_analysis/current_schemas.json");
  if (!existsSync(p)) return null;
  try {
    const raw = JSON.parse(readFileSync(p, "utf8"));
    const result = Array.isArray(raw) ? raw[0]?.result : raw?.result;
    if (!result?.schemas) return null;
    return {
      generated_at: "(aidream snapshot)",
      project: "txzxabzwovsujtloxrus",
      source: "aidream current_schemas.json",
      exposed_schemas: [],
      schemas: result.schemas,
      views: result.views ?? {},
    };
  } catch {
    return null;
  }
}

function write(snap: any, via: string): void {
  const nTables = Object.values(snap.schemas ?? {}).reduce((a: number, v: any) => a + v.length, 0);
  const payload = {
    _comment:
      "LIVE schema snapshot (tables + views + PostgREST-exposed schemas) — the truth scripts/schema-check diffs the code against. AUTOGENERATED by `pnpm check:schema:refresh` (pulls public.schema_truth_snapshot()). Do NOT hand-edit — refresh it.",
    generated_at: snap.generated_at ?? "unknown",
    project: snap.project ?? "txzxabzwovsujtloxrus",
    source: snap.source ?? via,
    exposed_schemas: snap.exposed_schemas ?? [],
    schemas: snap.schemas ?? {},
    views: snap.views ?? {},
  };
  writeFileSync(OUT, JSON.stringify(payload, null, 2) + "\n", "utf8");
  console.log(
    `${C.green}✓${C.reset} snapshot written → ${C.cyan}scripts/schema-check/current-schema.json${C.reset}  ` +
      `${C.dim}(${Object.keys(snap.schemas ?? {}).length} schemas, ${nTables} tables, ${(snap.exposed_schemas ?? []).length} exposed; via ${via})${C.reset}`,
  );
}

async function main(): Promise<number> {
  const env = loadEnv();
  if (env) {
    const snap = await pullViaRpc(env.url, env.key);
    if (snap?.schemas) {
      write(snap, "schema_truth_snapshot() RPC");
      return 0;
    }
  } else {
    console.error(`${C.yellow}[WARN]${C.reset} no Supabase URL/key in env or .env* — trying the aidream snapshot.`);
  }

  const aidream = fromAidream();
  if (aidream) {
    write(aidream, "aidream current_schemas.json");
    return 0;
  }

  console.error(
    `${C.red}[FAIL]${C.reset} could not refresh the snapshot (no DB reach, no aidream snapshot).\n` +
      `       The committed scripts/schema-check/current-schema.json (if any) still drives the checks.\n` +
      `       As an agent, you can refresh it via the Supabase MCP: select public.schema_truth_snapshot().`,
  );
  return 1;
}

main().then((code) => process.exit(code));
