/**
 * Shared types for the schema-truth-check orchestrator.
 *
 * The whole system answers one question: does the code still match the LIVE
 * database? Every check receives the same {@link Context} (the live snapshot +
 * the parsed repo) and returns {@link Finding}s. See ./FEATURE.md.
 */

export type Severity = "error" | "warn";

/** Provenance of the live-truth snapshot — surfaced so the report can say how fresh it is. */
export type SnapshotProvenance = "rpc" | "aidream" | "db-types" | "none";

/** The live database, as one offline-readable snapshot. The single source of truth. */
export interface Snapshot {
  generatedAt: string;
  /** Human-readable provenance, e.g. "schema_truth_snapshot() RPC (live)". */
  source: string;
  provenance: SnapshotProvenance;
  /** schema -> Set(table names) — base + partitioned-parent tables. */
  tables: Map<string, Set<string>>;
  /** schema -> Set(view names) — views/matviews; valid `.from()` targets, never "dead". */
  views: Map<string, Set<string>>;
  /** PostgREST-exposed schemas (pgrst.db_schemas). Empty when the snapshot can't see it. */
  exposedSchemas: Set<string>;
  /** relation name -> Set(schemas it lives in), tables AND views. Drives "X lives in {…}". */
  relationSchemas: Map<string, Set<string>>;
}

/** One row of scripts/dead-relations.json — a MOVED/RETIRED relation with human metadata. */
export interface DeadRelation {
  relation: string;
  old: string;
  newSchema: string;
  new: string;
  since: string;
  reason: string;
}

/** A first-party source file, read once and shared across every check. */
export interface CodeFile {
  /** Repo-relative path, posix-style. */
  path: string;
  ext: string;
  lines: string[];
  /** Set when the file is autogenerated (see generated-files.ts). */
  generated: GeneratedInfo | null;
}

/** Describes an autogenerated file: editing it is futile; the SOURCE must be regenerated. */
export interface GeneratedInfo {
  /** e.g. "Supabase database types". */
  label: string;
  /** What truly produces it, e.g. "the live Supabase database (project txzxabzwovsujtloxrus)". */
  source: string;
  /** The command that regenerates it, e.g. "pnpm db-types". */
  regen: string;
  /** One line on WHY a hand-edit won't survive. */
  why: string;
}

/** A single drift finding. */
export interface Finding {
  check: string;
  severity: Severity;
  message: string;
  /** "path:line" when it points at a specific spot. */
  location?: string;
  /** A concrete fix instruction. */
  fix?: string;
  /**
   * Set when the finding lives in (or concerns) an autogenerated file. The
   * orchestrator renders the loud "DO NOT EDIT — regenerate the source" banner
   * from this. Checks may set it explicitly; the orchestrator also auto-fills it
   * from `location` when that path is a known generated file.
   */
  generated?: GeneratedInfo;
}

/** The shared context handed to every check. */
export interface Context {
  root: string;
  snapshot: Snapshot;
  /** Every first-party source file (code + sql), read once. */
  codeFiles: CodeFile[];
  /** Schemas the FE asks `pnpm db-types` to generate (the `--schema X` list). */
  dbTypesSchemas: Set<string>;
  /** scripts/dead-relations.json, the annotated registry of known moves. */
  deadRelations: DeadRelation[];
  /** Old relation names from the dead-relations registry — the live-truth checks defer these. */
  deadOldNames: Set<string>;
  /** Whether to include WARN findings (the `--warn` flag). */
  warn: boolean;
}

export type Check = (ctx: Context) => Finding[];
