// Generated by scripts/generate-static-settings-control-index.ts. Do not edit.

export { settingsControlSearchId } from "@/components/official/settings/searchIdentity";

export type StaticSettingsControl = {
  tabId: string;
  label: string;
  description?: string;
  keywords?: string[];
  controlId: string;
};

export const staticSettingsControlIndex = [
  {
    "tabId": "general.language",
    "label": "Use my device's time zone",
    "controlId": "settings-control-time-zone-use-my-device-s-time-zone"
  },
  {
    "tabId": "general.language",
    "label": "Time zone",
    "description": "Where today starts for you.",
    "controlId": "settings-control-time-zone-time-zone"
  },
  {
    "tabId": "general.language",
    "label": "Voice input",
    "description": "Speech-to-text recognition language.",
    "controlId": "settings-control-language-defaults-voice-input"
  },
  {
    "tabId": "general.language",
    "label": "Text generation",
    "description": "Default language for generated text.",
    "controlId": "settings-control-language-defaults-text-generation"
  },
  {
    "tabId": "general.privacy",
    "label": "Desktop notifications",
    "description": "New-message banners on your desktop.",
    "controlId": "settings-control-notifications-desktop-notifications"
  },
  {
    "tabId": "general.privacy",
    "label": "Trash",
    "description": "Deleted items and when they go for good.",
    "controlId": "settings-control-your-data-trash"
  },
  {
    "tabId": "general.privacy",
    "label": "Auto knowledge-graph",
    "description": "Finds links in notes, tasks and files; you accept each one.",
    "controlId": "settings-control-knowledge-graph-auto-knowledge-graph"
  },
  {
    "tabId": "general.lists",
    "label": "Archived items",
    "description": "Archiving never deletes; this sets what lists show first.",
    "controlId": "settings-control-archived-items-archived-items"
  },
  {
    "tabId": "general.system",
    "label": "Announcements viewed",
    "description": "Unique announcement IDs you've dismissed.",
    "controlId": "settings-control-announcements-announcements-viewed"
  },
  {
    "tabId": "general.system",
    "label": "Feedback prompts seen",
    "description": "How many times the feedback callout has appeared.",
    "controlId": "settings-control-announcements-feedback-prompts-seen"
  },
  {
    "tabId": "appearance",
    "label": "Color mode",
    "description": "Device setting, light, or dark; every open tab follows it.",
    "controlId": "settings-control-theme-color-mode"
  },
  {
    "tabId": "appearance.theme",
    "label": "Color mode",
    "description": "Device setting, light, or dark; every open tab follows it.",
    "controlId": "settings-control-theme-color-mode"
  },
  {
    "tabId": "appearance.density",
    "label": "Color mode",
    "description": "Device setting, light, or dark; every open tab follows it.",
    "controlId": "settings-control-theme-color-mode"
  },
  {
    "tabId": "appearance.windows",
    "label": "Open windows",
    "controlId": "settings-control-status-open-windows"
  },
  {
    "tabId": "appearance.windows",
    "label": "Minimized",
    "controlId": "settings-control-status-minimized"
  },
  {
    "tabId": "appearance.windows",
    "label": "Visibility",
    "controlId": "settings-control-status-visibility"
  },
  {
    "tabId": "appearance.windows",
    "label": "Minimize all windows",
    "description": "Collapse every windowed panel into the tray.",
    "controlId": "settings-control-actions-minimize-all-windows"
  },
  {
    "tabId": "appearance.windows",
    "label": "Restore all windows",
    "description": "Bring every minimized window back to its previous size.",
    "controlId": "settings-control-actions-restore-all-windows"
  },
  {
    "tabId": "appearance.siteWorkbench",
    "label": "Saved bookmarks",
    "controlId": "settings-control-your-bookmarks-saved-bookmarks"
  },
  {
    "tabId": "appearance.siteWorkbench",
    "label": "Limit",
    "controlId": "settings-control-your-bookmarks-limit"
  },
  {
    "tabId": "ai.assistants",
    "label": "Assistant name",
    "description": "What the assistant calls itself.",
    "controlId": "settings-control-identity-assistant-name"
  },
  {
    "tabId": "ai.assistants",
    "label": "Put unsent drafts back",
    "description": "Restores unsent text after a reload or crash.",
    "controlId": "settings-control-composing-put-unsent-drafts-back"
  },
  {
    "tabId": "ai.assistants",
    "label": "Default AI model",
    "description": "Answers chat and drafting unless you pick another.",
    "controlId": "settings-control-model-default-ai-model"
  },
  {
    "tabId": "ai.textGeneration",
    "label": "Default AI model",
    "description": "Answers chat and drafting unless you pick another.",
    "controlId": "settings-control-model-style-default-ai-model"
  },
  {
    "tabId": "ai.textGeneration",
    "label": "Tone",
    "controlId": "settings-control-model-style-tone"
  },
  {
    "tabId": "ai.textGeneration",
    "label": "Creativity",
    "controlId": "settings-control-model-style-creativity"
  },
  {
    "tabId": "ai.textGeneration",
    "label": "Language",
    "controlId": "settings-control-model-style-language"
  },
  {
    "tabId": "ai.imageGeneration",
    "label": "Model",
    "description": "The AI Matrx default uses the platform's image model.",
    "controlId": "settings-control-output-model"
  },
  {
    "tabId": "ai.imageGeneration",
    "label": "Style",
    "description": "Pre-fills the style field; change it per image.",
    "controlId": "settings-control-output-style"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Which agents should appear?",
    "description": "Applies to the chat picker and history sidebar.",
    "controlId": "settings-control-agent-filter-which-agents-should-appear"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Tags",
    "description": "Show agents that have at least one of these tags.",
    "controlId": "settings-control-agent-filter-tags"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Categories",
    "description": "Show agents whose category matches one of these.",
    "controlId": "settings-control-agent-filter-categories"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Agents",
    "description": "Only these agents will show up.",
    "controlId": "settings-control-agent-filter-agents"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Default grouping",
    "description": "How history groups conversations on first load.",
    "controlId": "settings-control-history-sidebar-default-grouping"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Conversations per page",
    "description": "Conversations loaded per batch.",
    "controlId": "settings-control-history-sidebar-conversations-per-page"
  },
  {
    "tabId": "editor.codeWorkspace",
    "label": "Load per-tab type definitions",
    "description": "Typings for React, Lucide, shadcn and Node in code tabs.",
    "controlId": "settings-control-editor-type-environments-load-per-tab-type-definitions"
  },
  {
    "tabId": "editor.notes",
    "label": "Notes open in",
    "controlId": "settings-control-on-a-computer-notes-open-in"
  },
  {
    "tabId": "editor.notes",
    "label": "Notes open in",
    "controlId": "settings-control-on-a-phone-notes-open-in"
  },
  {
    "tabId": "devices",
    "label": "Microphone",
    "controlId": "settings-control-microphone-microphone"
  },
  {
    "tabId": "devices",
    "label": "Microphone access",
    "description": "Prompts once; the grant is remembered by your browser.",
    "controlId": "settings-control-microphone-microphone-access"
  },
  {
    "tabId": "devices",
    "label": "Speaker",
    "controlId": "settings-control-speaker-speaker"
  },
  {
    "tabId": "devices",
    "label": "Camera",
    "controlId": "settings-control-camera-camera"
  },
  {
    "tabId": "devices",
    "label": "Camera access",
    "description": "Prompts once; the camera turns off again immediately.",
    "controlId": "settings-control-camera-camera-access"
  },
  {
    "tabId": "devices",
    "label": "Preferred direction",
    "description": "On phones and tablets: front or rear camera by default.",
    "controlId": "settings-control-camera-preferred-direction"
  },
  {
    "tabId": "devices",
    "label": "Refresh device list",
    "description": "Re-scan after plugging in or removing a device.",
    "controlId": "settings-control-testing-tools-refresh-device-list"
  },
  {
    "tabId": "devices",
    "label": "Media controls",
    "description": "Live mic meter, speaker test tone, and camera preview.",
    "controlId": "settings-control-testing-tools-media-controls"
  },
  {
    "tabId": "voice.voices",
    "label": "Read-aloud speed",
    "description": "1.0 is natural pace; our default is 1.2.",
    "controlId": "settings-control-how-your-read-aloud-voice-speaks-read-aloud-speed"
  },
  {
    "tabId": "voice.voices",
    "label": "Read-aloud language",
    "controlId": "settings-control-how-your-read-aloud-voice-speaks-read-aloud-language"
  },
  {
    "tabId": "voice.voices",
    "label": "Read-aloud emotion",
    "description": "Read-aloud tone; live conversation is not affected.",
    "controlId": "settings-control-how-your-read-aloud-voice-speaks-read-aloud-emotion"
  },
  {
    "tabId": "voice.voices",
    "label": "Podcast hosts",
    "description": "Hosts are cast from the voice library below.",
    "controlId": "settings-control-voices-for-what-you-build-podcast-hosts"
  },
  {
    "tabId": "voice.voices",
    "label": "Speakers in an agent's speech script",
    "description": "Each speaker's voice is picked in the speech script editor.",
    "controlId": "settings-control-voices-for-what-you-build-speakers-in-an-agent-s-speech-script"
  },
  {
    "tabId": "voice.voices",
    "label": "Live voice agents you build",
    "description": "One of five live voices, set in the voice playground.",
    "controlId": "settings-control-voices-for-what-you-build-live-voice-agents-you-build"
  },
  {
    "tabId": "voice.input",
    "label": "Voices you hear",
    "description": "Read-aloud, live conversation and every other voice.",
    "controlId": "settings-control-voice-voices-you-hear"
  },
  {
    "tabId": "voice.input",
    "label": "Microphone & speaker",
    "description": "Choose which microphone and speaker AI Matrx uses.",
    "controlId": "settings-control-devices-microphone-speaker"
  },
  {
    "tabId": "communication.email",
    "label": "Sharing notifications",
    "description": "When someone shares a document, agent, or task with you.",
    "controlId": "settings-control-collaboration-sharing-notifications"
  },
  {
    "tabId": "communication.email",
    "label": "Organization invitations",
    "description": "When someone invites you to an organization.",
    "controlId": "settings-control-collaboration-organization-invitations"
  },
  {
    "tabId": "communication.email",
    "label": "Task notifications",
    "description": "Assignments, status changes, due-date reminders.",
    "controlId": "settings-control-collaboration-task-notifications"
  },
  {
    "tabId": "communication.email",
    "label": "Comment notifications",
    "description": "When someone comments on your tasks, canvases, or notes.",
    "controlId": "settings-control-collaboration-comment-notifications"
  },
  {
    "tabId": "communication.email",
    "label": "Message notifications",
    "description": "New direct messages and mentions.",
    "controlId": "settings-control-communication-message-notifications"
  },
  {
    "tabId": "communication.email",
    "label": "Resource updates",
    "description": "Changes to resources you follow.",
    "controlId": "settings-control-communication-resource-updates"
  },
  {
    "tabId": "communication.email",
    "label": "Weekly digest",
    "description": "A summary of the past week delivered Monday morning.",
    "controlId": "settings-control-digests-weekly-digest"
  },
  {
    "tabId": "communication.email",
    "label": "Message digest",
    "description": "Unread messages bundled instead of sent individually.",
    "controlId": "settings-control-digests-message-digest"
  },
  {
    "tabId": "communication.email",
    "label": "Product updates & marketing",
    "description": "Product announcements, launch emails, surveys.",
    "controlId": "settings-control-marketing-product-updates-marketing"
  },
  {
    "tabId": "communication.email",
    "label": "Apply email preferences",
    "controlId": "settings-control-save-apply-email-preferences"
  },
  {
    "tabId": "communication.video",
    "label": "Camera, microphone & speakers",
    "description": "Uses your saved device settings.",
    "controlId": "settings-control-devices-camera-microphone-speakers"
  },
  {
    "tabId": "communication.messaging",
    "label": "Notification sound",
    "description": "Play a sound when a new message arrives.",
    "controlId": "settings-control-sound-notification-sound"
  },
  {
    "tabId": "communication.messaging",
    "label": "Volume",
    "description": "How loud notification sounds should play.",
    "controlId": "settings-control-sound-volume"
  },
  {
    "tabId": "communication.messaging",
    "label": "Test sound",
    "description": "Play a sample at the current volume.",
    "controlId": "settings-control-sound-test-sound"
  },
  {
    "tabId": "communication.messaging",
    "label": "Desktop notifications",
    "description": "Your browser doesn't support the Notifications API.",
    "controlId": "settings-control-desktop-desktop-notifications"
  },
  {
    "tabId": "communication.messaging",
    "label": "Desktop notifications",
    "description": "Permission was denied at the browser level.",
    "controlId": "settings-control-desktop-desktop-notifications"
  },
  {
    "tabId": "communication.messaging",
    "label": "Desktop notifications",
    "description": "Needs browser permission; asked once.",
    "controlId": "settings-control-desktop-desktop-notifications"
  },
  {
    "tabId": "communication.messaging",
    "label": "Show desktop notifications",
    "description": "Display system banners for new messages.",
    "controlId": "settings-control-desktop-show-desktop-notifications"
  },
  {
    "tabId": "communication.messaging",
    "label": "Open your staff",
    "description": "The same conversation your texts and calls already use.",
    "controlId": "settings-control-your-staff-open-your-staff"
  },
  {
    "tabId": "learning.flashcards",
    "label": "Tutor voice",
    "description": "Your live conversation voice, Eve by default.",
    "controlId": "settings-control-tutor-tutor-voice"
  },
  {
    "tabId": "learning.flashcards",
    "label": "Intelligence",
    "description": "See or copy the deck generator and tutor agents.",
    "controlId": "settings-control-tutor-intelligence"
  },
  {
    "tabId": "organizations",
    "label": "Start-up organization",
    "description": "Opens when you have no last-used organization",
    "keywords": [
      "start-up",
      "startup",
      "organization",
      "open"
    ],
    "controlId": "settings-control-when-you-sign-in-start-up-organization"
  },
  {
    "tabId": "organizations",
    "label": "Switch organization when a link asks",
    "controlId": "settings-control-links-from-notifications-and-emails-switch-organization-when-a-link-asks"
  },
  {
    "tabId": "sandboxDefaults",
    "label": "Sandbox secrets and variables",
    "description": "Every sandbox you start reads them from your Vault.",
    "controlId": "settings-control-environment-variables-sandbox-secrets-and-variables"
  },
  {
    "tabId": "integrations.apiKeys",
    "label": "Name",
    "description": "What will use it, so you can tell your keys apart.",
    "controlId": "settings-control-new-key-name"
  },
  {
    "tabId": "integrations.apiKeys",
    "label": "Organization",
    "description": "Where the key works when a request names no organization.",
    "controlId": "settings-control-new-key-organization"
  },
  {
    "tabId": "integrations.apiKeys",
    "label": "Create key",
    "description": "Works until you revoke it or it hits your org's max age.",
    "controlId": "settings-control-new-key-create-key"
  },
  {
    "tabId": "admin.server",
    "label": "Server override",
    "description": "Which backend host API calls target.",
    "controlId": "settings-control-backend-server-server-override"
  },
  {
    "tabId": "admin.server",
    "label": "Custom server URL",
    "description": "Full origin, e.g. https://preview.matrxserver.com",
    "controlId": "settings-control-backend-server-custom-server-url"
  },
  {
    "tabId": "admin.server",
    "label": "Desktop instance",
    "description": "Desktop app for delegated tools; Auto keeps default routing.",
    "controlId": "settings-control-desktop-app-dev-override-desktop-instance"
  },
  {
    "tabId": "admin.server",
    "label": "Registered instances",
    "description": "Refresh aidream's registered desktop instances.",
    "controlId": "settings-control-desktop-app-dev-override-registered-instances"
  }
] satisfies readonly StaticSettingsControl[];
