-- INVERSE of migrations/campaign/argsruled_ninetyfive_doors_name_the_call_that_decides.sql.
--
-- It removes the `arguments` this lane merged in, and with them the rulings, by setting
-- argument_rules back to NULL on the 93 doors that held NULL before that file. The two that
-- already carried rules (custom.io_comment_write's family) keep theirs: this statement skips any
-- row whose argument_rules names a declared_by other than this lane's file.
--
-- With this applied the per-argument census rises by 95 and
-- `uv run python scripts/check_definer_bodies_decide_access.py` fails on the ceiling again.

set lock_timeout = '4s';

update platform.client_callable_door d
   set argument_rules = null
 where (d.schema_name, d.function_name) in (
   ('custom','agg_explain'),
   ('custom','anon_submissions'),
   ('custom','applicable_fields'),
   ('custom','bookings'),
   ('custom','checklist_declare'),
   ('custom','checklist_step_complete'),
   ('custom','checklist_step_refusal'),
   ('custom','checklist_template_shape'),
   ('custom','choice_census'),
   ('custom','comment_thread'),
   ('custom','computed_provenance'),
   ('custom','conversation_scope_bind'),
   ('custom','conversation_scope_unbind'),
   ('custom','dashboard_delete'),
   ('custom','dashboard_stuck'),
   ('custom','delete_preview'),
   ('custom','doc_renders'),
   ('custom','doc_signatures'),
   ('custom','doc_template_read'),
   ('custom','doc_templates'),
   ('custom','enrich_pin'),
   ('custom','enrichments'),
   ('custom','field_declare'),
   ('custom','field_dependants'),
   ('custom','history_prune'),
   ('custom','history_retention'),
   ('custom','history_retention_set'),
   ('custom','inbound_addresses'),
   ('custom','inbound_declare'),
   ('custom','io_export'),
   ('custom','io_import_begin'),
   ('custom','io_import_open'),
   ('custom','io_import_plan'),
   ('custom','io_imports'),
   ('custom','io_infer_column'),
   ('custom','migrate_choice_keys'),
   ('custom','migrate_delete'),
   ('custom','migrate_demote'),
   ('custom','migrate_merge'),
   ('custom','migrate_promote'),
   ('custom','migrate_purge'),
   ('custom','migrate_rename'),
   ('custom','migrate_reparent'),
   ('custom','migrate_retype'),
   ('custom','migrate_split'),
   ('custom','migrations'),
   ('custom','my_level'),
   ('custom','pipeline_board'),
   ('custom','pipeline_declare'),
   ('custom','pipeline_gate_preview'),
   ('custom','pipeline_pending'),
   ('custom','pipeline_read'),
   ('custom','pipeline_transition_refusal'),
   ('custom','promote_table'),
   ('custom','query_by_coordinates'),
   ('custom','query_table_homes'),
   ('custom','read_records'),
   ('custom','record_aggregate'),
   ('custom','record_as_of'),
   ('custom','record_delete'),
   ('custom','record_history'),
   ('custom','record_restore'),
   ('custom','record_restore_preview'),
   ('custom','record_stage_pending'),
   ('custom','record_table'),
   ('custom','record_update'),
   ('custom','record_values_versioned'),
   ('custom','record_write'),
   ('custom','relation_carry'),
   ('custom','relation_target_card'),
   ('custom','relation_targets'),
   ('custom','share_access'),
   ('custom','share_lane_set'),
   ('custom','share_people'),
   ('custom','sign_requests'),
   ('custom','subscription_declare'),
   ('custom','table_capacity'),
   ('custom','table_share_outside'),
   ('custom','table_share_outside_invite'),
   ('custom','table_stage_field'),
   ('custom','table_type_field'),
   ('custom','value_read'),
   ('custom','view_declare'),
   ('custom','work_has_assignment'),
   ('custom','work_instantiation_shape'),
   ('custom','work_record_states'),
   ('custom','work_slot_expire'),
   ('custom','work_slot_hold'),
   ('custom','work_slot_holds'),
   ('custom','work_slot_release'),
   ('custom','work_slots_declare'),
   ('custom','work_take_assignment'),
   ('custom','work_template_instantiate'),
   ('custom','work_template_shape'),
   ('custom','work_whose_turn'))
   and d.argument_rules ->> 'declared_by' = 'argsruled_ninetyfive_doors_name_the_call_that_decides.sql';
