-- chair-step: the inverse of migrations/campaign/drillledgerrecords_drill_declares_ai_usage.sql (lane DRILL-LEDGER-RECORDS) — drops the declared drill definition function(s) it created and puts back the ones it replaced (ai_usage) exactly as they were. No row of anybody's data is touched.
-- lane: DRILL-LEDGER-RECORDS
-- lock: platform
-- based-on: platform.drill_def__ai_usage() a788fd8873f608fe4ea65215755359f56653e98e5aeb91ed9a73379b30d8eb4b

create or replace function platform.drill_def__ai_usage()
returns jsonb
language sql
immutable
set search_path to 'pg_catalog'
as $function$
  select $drill${"key":"ai_usage","fact":"ai_usage_hourly","mode":"definer","grain":"one row per hour for each organization, person, agent, provider, model, app, feature, origin, manual or automated, and source","label":"AI usage","lanes":["platform","organization","mine"],"paths":[{"key":"who","label":"Who","levels":["organization","person"]},{"key":"what","label":"What","levels":["provider","model"]},{"key":"where","label":"Where","levels":["app","feature","agent"]},{"key":"when","label":"When","levels":["at:month","at:week","at:day","at:hour"]}],"detail":{"open":"/administration/billing/spend","columns":["bucket","organization_id","person_id","provider","model","feature","cost","tokens_in","tokens_out"]},"default":{"by":["person"],"path":"who","show":["cost","requests","tokens_in","tokens_out"],"sort":{"key":"cost","direction":"desc"},"window":{"key":"at","preset":"30d"}},"measures":[{"of":"cost","op":"sum","key":"cost","unit":"usd","label":"Cost","additive":true},{"of":"calls","op":"sum","key":"calls","unit":"count","label":"Calls","additive":true},{"of":"requests","op":"sum","key":"requests","unit":"count","label":"Requests","additive":true},{"of":"tokens_in","op":"sum","key":"tokens_in","unit":"tokens","label":"Input tokens","additive":true},{"of":"tokens_out","op":"sum","key":"tokens_out","unit":"tokens","label":"Output tokens","additive":true},{"of":"tokens_cached","op":"sum","key":"tokens_cached","unit":"tokens","label":"Cached tokens","additive":true},{"of":"unpriced_calls","op":"sum","key":"unpriced_calls","unit":"count","label":"Calls with no price","additive":true},{"of":"person_id","op":"count_distinct","key":"people","unit":"count","label":"People","additive":false}],"dimensions":[{"key":"organization","from":"organization_id","kind":"relation","label":"Organization","relation":{"token":"organization"}},{"key":"person","from":"person_id","kind":"relation","label":"Person","relation":{"token":"user","person":true}},{"key":"provider","from":"provider","kind":"choice","label":"Provider","cardinality":"low"},{"key":"model","from":"model","kind":"choice","label":"Model","cardinality":"medium"},{"key":"app","from":"app","kind":"choice","label":"App","cardinality":"low"},{"key":"feature","from":"feature","kind":"choice","label":"Feature","cardinality":"medium"},{"key":"agent","from":"agent_id","kind":"relation","label":"Agent","relation":{"token":"agent"},"cardinality":"medium"},{"key":"origin","from":"origin","kind":"choice","label":"Origin","cardinality":"low"},{"key":"trigger","from":"trigger","kind":"choice","label":"Manual or automated","cardinality":"low"},{"key":"source","from":"source","kind":"choice","label":"Source","cardinality":"low"},{"key":"at","from":"bucket","kind":"time","label":"When","grains":["year","quarter","month","week","day","hour"]}],"lane_rules":{"mine":{"column":"person_id"},"platform":{"rule":"super_admin"},"organization":{"rule":"admin","column":"organization_id"}}}$drill$::jsonb;
$function$;

comment on function platform.drill_def__ai_usage() is
  'DRILL-STANDARD-DOOR: the declared drill definition "AI usage" (ai_usage), compiled from its *.drill.ts file by aidream apps/shared/records/scripts/drill-sync.ts. Code, not data: never edited by hand.';
