-- INVERSE of migrations/campaign/switchsteptwo_e_the_lifecycle_registers_let_go_of_the_moved_tables.sql (lane SWITCH-STEP-TWO-RUN):
-- the 16 register rows come back exactly as production held them at 2026-10-01 21:35Z (9 lifecycle_reference_map, 6
-- lifecycle_entity_plan, 1 soft_delete_edge). Run it only after the move back (step-two-move.sh production down);
-- otherwise the rows name tables that are not there.
-- lane: SWITCH-STEP-TWO-RUN

insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_datasets", "delete_rank": 2, "feature_key": "lists-and-workbooks", "entity_token": "dataset", "owner_column": "created_by", "cascade_edges": 3, "blocking_edges": 0, "dangling_edges": 0, "mutating_edges": 1, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_structured_lists", "delete_rank": 1, "feature_key": "lists-and-workbooks", "entity_token": "structured_list", "owner_column": "created_by", "cascade_edges": 1, "blocking_edges": 1, "dangling_edges": 0, "mutating_edges": 0, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_dataset_fields", "delete_rank": 0, "feature_key": "lists-and-workbooks", "entity_token": "udt_dataset_fields", "owner_column": "created_by", "cascade_edges": 0, "blocking_edges": 0, "dangling_edges": 0, "mutating_edges": 0, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_dataset_row_versions", "delete_rank": 0, "feature_key": "(unregistered)", "entity_token": "udt_dataset_row_versions", "owner_column": "created_by", "cascade_edges": 0, "blocking_edges": 0, "dangling_edges": 0, "mutating_edges": 0, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_dataset_rows", "delete_rank": 0, "feature_key": "lists-and-workbooks", "entity_token": "udt_dataset_rows", "owner_column": "created_by", "cascade_edges": 0, "blocking_edges": 0, "dangling_edges": 0, "mutating_edges": 0, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_entity_plan select * from jsonb_populate_record(null::platform.lifecycle_entity_plan, '{"built_at": "2026-09-19T08:21:53.438971+00:00", "in_cycle": false, "entity_ref": "workbench.udt_structured_list_items", "delete_rank": 0, "feature_key": "lists-and-workbooks", "entity_token": "udt_structured_list_items", "owner_column": "created_by", "cascade_edges": 0, "blocking_edges": 0, "dangling_edges": 0, "mutating_edges": 0, "unmanaged_blockers": 0}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "1c80879f-e8ee-4b1b-87a7-7e87e8a9bf2a", "hazard": "mutates_survivor", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "extend.wbx_pattern", "guard_sql": "not exists (select 1 from extend.wbx_pattern c where c.target_user_table_id = {parent})", "on_delete": "set_null", "parent_ref": "workbench.udt_datasets", "child_token": "wbx_pattern", "child_column": "target_user_table_id", "cross_schema": true, "parent_token": "dataset", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "4baceb7b-aa4d-4705-8593-c1f68c0e164b", "hazard": "mutates_survivor", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_datasets", "guard_sql": "not exists (select 1 from workbench.udt_datasets c where c.project_id = {parent})", "on_delete": "set_null", "parent_ref": "workspace.projects", "child_token": "dataset", "child_column": "project_id", "cross_schema": true, "parent_token": "project", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "504dcc25-3770-47c7-be9f-779ce2089ad9", "hazard": "auto_deletes", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "context.scope_dataset_instances", "guard_sql": "not exists (select 1 from context.scope_dataset_instances c where c.dataset_id = {parent})", "on_delete": "cascade", "parent_ref": "workbench.udt_datasets", "child_token": null, "child_column": "dataset_id", "cross_schema": true, "parent_token": "dataset", "self_reference": false, "child_is_managed": false}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "71577f2b-52fa-4c8d-b2cf-2fb61a254c5e", "hazard": "mutates_survivor", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_datasets", "guard_sql": "not exists (select 1 from workbench.udt_datasets c where c.workbook_id = {parent})", "on_delete": "set_null", "parent_ref": "workbench.udt_workbooks", "child_token": "dataset", "child_column": "workbook_id", "cross_schema": false, "parent_token": "workbook", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "8f2bdbec-7bf6-4318-afcf-12f159ff262c", "hazard": "blocks", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "platform.custom_field_definition", "guard_sql": "not exists (select 1 from platform.custom_field_definition c where c.option_list_id = {parent})", "on_delete": "no_action", "parent_ref": "workbench.udt_structured_lists", "child_token": "custom_field_definition", "child_column": "option_list_id", "cross_schema": true, "parent_token": "structured_list", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "9ae1e106-4923-4227-8eb5-ed711109f35d", "hazard": "auto_deletes", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_dataset_rows", "guard_sql": "not exists (select 1 from workbench.udt_dataset_rows c where c.table_id = {parent})", "on_delete": "cascade", "parent_ref": "workbench.udt_datasets", "child_token": "udt_dataset_rows", "child_column": "table_id", "cross_schema": false, "parent_token": "dataset", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "c866e20f-268d-4f0d-b4c2-6e0f0627ba2c", "hazard": "auto_deletes", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_structured_list_items", "guard_sql": "not exists (select 1 from workbench.udt_structured_list_items c where c.list_id = {parent})", "on_delete": "cascade", "parent_ref": "workbench.udt_structured_lists", "child_token": "udt_structured_list_items", "child_column": "list_id", "cross_schema": false, "parent_token": "structured_list", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "d1938f9d-003d-4c7d-98b7-7d8728a87026", "hazard": "auto_deletes", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_dataset_fields", "guard_sql": "not exists (select 1 from workbench.udt_dataset_fields c where c.table_id = {parent})", "on_delete": "cascade", "parent_ref": "workbench.udt_datasets", "child_token": "udt_dataset_fields", "child_column": "table_id", "cross_schema": false, "parent_token": "dataset", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.lifecycle_reference_map select * from jsonb_populate_record(null::platform.lifecycle_reference_map, '{"id": "ea393a08-1ea8-4a48-bf64-805768c508ef", "hazard": "mutates_survivor", "source": "fk", "built_at": "2026-09-19T08:21:53.438971+00:00", "child_ref": "workbench.udt_datasets", "guard_sql": "not exists (select 1 from workbench.udt_datasets c where c.task_id = {parent})", "on_delete": "set_null", "parent_ref": "workspace.tasks", "child_token": "dataset", "child_column": "task_id", "cross_schema": true, "parent_token": "task", "self_reference": false, "child_is_managed": true}'::jsonb) on conflict do nothing;
insert into platform.soft_delete_edge select * from jsonb_populate_record(null::platform.soft_delete_edge, '{"id": "fd7b8c5f-ead6-41b4-8b6f-4e41a3c16d71", "action": "keep", "reason": "A dataset created while working on a task is the person''s data and outlives the task it was made for.", "child_table": "udt_datasets", "declared_at": "2026-09-12T05:22:58.581178+00:00", "declared_by": "matrx-frontend/migrations/task_hard_delete_door_closed.sql (DD-119)", "parent_noun": "task", "child_column": "task_id", "child_schema": "workbench", "parent_table": "tasks", "parent_column": "id", "parent_schema": "workspace"}'::jsonb) on conflict do nothing;
