// features/administration/custom-tables/codeNamedTableIds.ts — GENERATED by
// scripts/custom-tables/census-code-named-table-ids.mjs (2026-10-03, target production).
// Do not edit by hand: rerun the script. Every live custom table whose id a tracked file of a code
// repo names. The admin Custom Tables page never offers these for bulk archive.

export const CODE_NAMED_TABLE_IDS: ReadonlySet<string> = new Set([
  "00906c4d-958f-479f-b897-f246baba147d", // ZZZ APPROVAL-TAIL throwaway 90fc14f1 — safe to delete — Crews ac593e09
  "00fd38c5-d5ab-4bbc-936a-c177acd31ddb", // Ironclad Mobile Mechanic — High Desert Route — Crews 91e74bab
  "0158a1a6-9464-47c3-b55e-0b569a44d979", // Calder Approvals — Rincon Plumbing Crews 1790150940889
  "01a3ca5a-35cc-4741-b432-1b4ba4dbc846", // Rincon Plumbing Co — Carpinteria Branch — Jobs
  "02a6e890-8d74-46a0-96de-bea8d9bda058", // Cedar Ridge Dental — ZZZ UI-QUICK-1 Rincon-style Jobs — safe to delete
  "02f00d65-bf3b-49bb-995c-859926be8a4f", // Ironclad Mobile Mechanic — Customers
  "031d3690-4a02-4cee-a575-454ffd96c992", // Cedar Ridge Physical Therapy — Patient Visit Tracker
  "03c65ec6-4bae-4aa1-8eaa-d64098fec6b3", // Ironline Fitness — Company Profile
  "09ac14a1-497b-405f-82cd-afc60aedd870", // Ridgeline Physical Therapy — exercises_prescribed
  "0aaac5b1-f310-4f4f-bc6f-1e9b72594807", // Cedar Ridge Dental — Checklist steps
  "0ad6d841-fe7a-4fe1-b7d2-e1c9fe4e119a", // admin's Workspace — QME Some Case
  "0b113241-7e8b-4837-9bbe-1d2c355cdae9", // Cascade Electronics Recovery — Pickups
  "0b3ed937-fb0a-4ad5-9f1e-68708b4317ae", // Matrx System — Example: Teams by Department
  "0b5726b2-08ce-4c7f-a024-9d01a0a24b52", // Ridgeline Physical Therapy — Records UI Demo
  "0bd93465-61b4-45a4-9b87-9a2e9d70f956", // Other People — Person
  "0e108f31-5078-48ec-9a15-b492baa414ba", // Birchwood Avenue Renovation — quotes
  "0f9c8a0b-c8ab-481d-8070-fc1c689eb968", // Hands & Hope Alliance — pledges
  "106587fc-3b10-413e-bdd9-ff9a05891e72", // Ridgeline Physical Therapy — treatment_plans
  "10bd0c7d-4312-41ae-a0b8-9f980f682d16", // Arman's Org — EDM Microdata Auto
  "11111111-0000-4000-8000-000000000001", // Matrx System — Table
  "11111111-0000-4000-8000-000000000002", // Matrx System — Field
  "11111111-0000-4000-8000-000000000003", // Matrx System — Rule
  "11111111-0000-4000-8000-000000000004", // Matrx System — Organization
  "11111111-0000-4000-8000-000000000005", // Matrx System — Person
  "11111111-0000-4000-8000-000000000006", // Matrx System — File
  "11111111-0000-4000-8000-000000000007", // Matrx System — Presentation
  "11111111-0000-4000-8000-000000000008", // Matrx System — Widget
  "11111111-0000-4000-8000-000000000009", // Matrx System — Merge Field
  "11111111-0001-4000-8000-000000000001", // Matrx System — Merge Field Source
  "11111111-0001-4000-8000-000000000002", // Matrx System — Merge Field Semantic Type
  "11111111-0001-4000-8000-000000000003", // Matrx System — Merge Field Modifier
  "11111111-0001-4000-8000-000000000004", // Matrx System — Override Policy
  "11111111-0001-4000-8000-000000000009", // Matrx System — Merge Field Declaration
  "11111111-0004-4000-8000-000000000001", // Matrx System — Rule conformance shape
  "11111111-0005-4000-8000-000000000001", // Matrx System — Parity Choice
  "11111111-0005-4000-8000-000000000002", // Matrx System — Parity Line
  "11111111-0005-4000-8000-000000000003", // Matrx System — Parity Floor
  "112b16bf-3423-418f-8065-b8ffbe0e419c", // Fairview Shared Services — V7 T7 PurchaseOrder
  "177a5e1a-fb38-4ceb-afb2-f5afca573f3b", // admin's Workspace — matrx-frontend (LCP lcp-test-mu7c6pdn) — Known defects
  "17823eed-679f-463b-b475-4839c7d62541", // Cedar Ridge Physical Therapy — Clinic Supply Reorders
  "182fef5a-4ead-42a0-966b-e4e88fcd87a9", // Greenline Landscaping Crew — Jobs
  "197ed942-5f74-45af-83d6-14f6249e5411", // admin's Workspace — Birchwood Rooms — colour walk
  "1aaba65d-68de-457e-8a0c-0f2731161d13", // Castellano & Reyes, LLP — Matter
  "1ac8673d-f034-4359-977f-274dfb3c10ab", // admin's Workspace — Class
  "1c9bae6d-f8be-4999-a513-2194c97d44bc", // Wraithmoor Regional Museum of Art & Craft — Wraithmoor Regional Museum of Art & Craft: exhibitions
  "1d43e482-cf59-4d37-b55d-beff4fb63a02", // Riverside Clinic — New Patients
  "1d4ee462-631c-4587-96a2-d896a66e6344", // Kessler Lab for Applied Microbial Ecology — Kessler Lab for Applied Microbial Ecology: measurements
  "215e2e75-d04e-4c8a-b208-5be46488b18d", // Ironclad Mobile Mechanic — Service Calls
  "28189832-3180-5c57-83d4-6014bc2494e6", // Harbor Dental Group — Plan Type options
  "28876026-eabf-44de-b8c6-b4802c349338", // Rincon Plumbing Co — Truck 3 assignment sheet (2026-09-22 03:53Z)
  "28959114-c454-4784-b447-124e45d4f7ba", // Signal & Scale Podcast — Signal & Scale Podcast: edit_tasks
  "2a0fff28-25db-4adc-89f4-e402df1121f5", // Castellano & Reyes, LLP — Client
  "2ac98263-a4ab-49f4-a118-56f4b2bc6050", // Cedar Ridge Physical Therapy — Checklist steps
  "2f4c0d35-a510-4e38-b2b7-fbea0ff6afe0", // admin's Workspace — Pet
  "3260bbbe-aaa8-4148-a4d9-7ad880e7976d", // Rincon Plumbing Co — Camarillo Branch — September service board — Camarillo
  "335be3d6-39ed-4fe6-9725-c28952bc18c3", // Hands & Hope Alliance — donors
  "36502899-624c-47c8-b5af-f6f6cea8ae5e", // The Alvarado-Chen Kitchen — shopping_list_items
  "367f2b31-8741-464e-b477-204c129652a6", // Harbor Dental Group — Team Member
  "36c07712-b0f2-43f2-a1c8-712ae4a75739", // AI Matrx — Feature
  "377b783a-f18a-40c3-bf2b-7617691d0091", // Harbor Dental Group — Insurance Plan Accounts
  "37fd85b9-c25a-4b29-8048-e770bc8bd26f", // Titanium — Client
  "3994447a-eea4-43c4-a1f3-0ca9ebb1593e", // Ellie Sadeghi Personal — Pet
  "3b81bb2e-740e-4c6b-817c-b6c6f750a018", // Arman's Org — AI Model Benchmarks
  "3c5a879d-69b0-7d36-827a-c49760e4ff98", // Arman's Org — Countries by Continent
  "415c3e23-2f90-4c66-9040-b246fa1c4b36", // admin's Workspace — Rincon Plumbing — Customers
  "41ae4b2d-46e7-463d-94d9-b26c46b6f451", // Cedar Ridge Physical Therapy — Department
  "437ad3e2-0b61-4cc2-938c-db22fc5c5220", // Matrx System — Example: Product Catalog
  "43ab536e-489a-4d6c-9aea-1c86ea526844", // Cedar Ridge Physical Therapy — Team Member
  "449c3251-2810-4bde-9953-9a885a591b1a", // Trailhead & Torch Journeys — Trailhead & Torch Journeys: US National Parks
  "44c53bc3-f37f-4229-81ab-73aa4e2e3fa4", // Cedar Ridge Physical Therapy — Checklist steps — workflow state
  "45966ab1-961a-401a-af82-792ddcce2aaf", // Rincon Plumbing Co — Ojai Branch — Records UI Demo
  "46ae8d53-4068-4593-9439-fb2b656767f1", // Cedar Ridge Physical Therapy — Clinic Equipment Log
  "48efae0c-2cbb-40ef-aa41-fe5930c5c12f", // Cedar Ridge Physical Therapy — Body Areas choices
  "494df967-eb2a-4829-af4f-7ccd4a64ce91", // admin's Workspace — Table 1
  "4ddb39e5-8fa5-4236-b17b-ec2fe82e277a", // Arman's Org — AG Pickup Data
  "4f1dd630-ea3a-4587-81cf-fb97fd505480", // Cascade Electronics Recovery — Fresno Route — Bins
  "4f581d20-2b60-4cd4-9fb4-2ef9ca5ef874", // Cascade Electronics Recovery — Certificates Of Destruction
  "5155b79c-4c54-4694-b644-2e21ea6833b7", // AI Matrx — App
  "522c3ff1-7229-439c-be00-5b20492cc328", // Compass Route Relocation Advisors — October carrier rates
  "546065ea-95c2-46b3-a4e0-5b9cea963a16", // Ironline Fitness — Model Picks
  "5503f505-595e-4669-80bb-c34dbc5dfd3b", // Cascade Electronics Recovery — Client Sites
  "56e7c7b6-3831-4c0e-a5bd-655953eb865f", // Signal & Scale Podcast — Signal & Scale Podcast: Field Kinds Gallery
  "58eb395c-7e2e-458a-97ad-f583a720d3c5", // Pearlman Brown, and Wax, LLP — Matter
  "59038c18-552c-427b-b855-6268b853fd89", // Arman's Org — Vegas Events
  "5960d731-dadc-4517-b6ed-32f948fc9d6b", // Titanium — Tag
  "5a4077da-bd6b-4f34-982c-93bcc36b2210", // Ridgeline Physical Therapy — patients
  "5b5d2f87-ced4-43ac-8c36-d426dcb96c47", // Cedar Ridge Physical Therapy — Clinic Supplies Count
  "5ba50000-0000-4a00-8a00-000000000201", // Rincon Plumbing Co — Case
  "5ba83fdf-c24b-44b0-884b-8c44f549ed8d", // Ironline Fitness — Ironline Fitness: Members
  "5f6b8364-8c3a-48ca-a833-2905a88e6ee4", // The Alvarado-Chen Kitchen — recipes
  "60df8b1e-d63a-482d-9600-22469c93263c", // Ironline Fitness — members
  "611127f9-17c9-4b1e-be2e-2809f0a5d723", // Kessler Lab for Applied Microbial Ecology — Kessler Lab for Applied Microbial Ecology: protocols
  "65c38022-ac9e-477f-aa9a-0b08d8ff63d8", // Arman's Org — Page URL
  "6a18531b-60e8-4073-b2c0-2a23b7d63af5", // Kessler Lab for Applied Microbial Ecology — Kessler Lab for Applied Microbial Ecology: researchers
  "6a4b2950-935a-4c26-a3f6-0e1ab760d184", // Matrx System — Example: Team Directory
  "6a7822ca-859c-4903-87a3-c8243058dcc5", // Matrx System — scene options
  "6d3b427c-f272-4118-8f14-3f431c78c75c", // Cedar Ridge Physical Therapy — Patients
  "6dddb7c1-82e4-4b78-b1e1-dc1a3c5a7789", // Rincon Plumbing Co — Camarillo Branch — Stage
  "7363f01d-c78f-455d-90cd-44adc9ea7b26", // Signal & Scale Podcast — Signal & Scale Podcast: sponsors
  "7415b4a1-17ab-4fe5-afc6-ae4754ec7baf", // Alex Hart's Workspace — Jobs
  "7426c07f-6562-47b3-94dd-06f206dfdb6c", // Arman's Org — AI Matrx Dev Projects
  "746c2ed5-2c52-4e28-9b8d-192b897e9390", // admin's Workspace — Coding Platforms
  "7502ced3-da63-4018-9476-9b37ae7b1f71", // admin's Workspace — Model Picks
  "77459bea-c09f-4384-814e-2a17826c44b3", // Ironclad Mobile Mechanic — Service Calls
  "7929e197-cba4-4128-8445-870209dd0335", // Kessler Lab for Applied Microbial Ecology — Kessler Lab for Applied Microbial Ecology: experiments
  "7da1b1a6-a566-4b69-8b54-be817387be49", // admin's Workspace — Intake callback windows r3
  "8414e7e0-0668-5996-a19b-8b782621a716", // admin's Workspace — Regions options
  "85e30746-8f5e-4e4e-b24e-9c595c050ba7", // Signal & Scale Podcast — Companies
  "87013986-e75a-44e7-bc4a-124640c991d5", // Cedar Ridge Physical Therapy — Stock count, March 8800
  "89919d7d-cbbc-4600-8ea7-3f63db964631", // Cedar Ridge Physical Therapy — Treatment Rooms
  "8c67a085-197d-44c0-b2bb-ceeea9555303", // admin's Workspace — matrx-frontend (LCP test) — Known defects
  "8d6b5ea2-c7d0-47c3-a02a-63ab8eaf51e8", // Kessler Lab for Applied Microbial Ecology — Kessler Lab for Applied Microbial Ecology: publications
  "91712881-ef8a-4e9d-89ab-17be216b11bd", // AI Matrx — ZZZ Agent Review - Workflow Certification Log
  "92c5c8ea-5464-4297-ab36-0c1c74009537", // Ironclad Mobile Mechanic — Service Call Signups
  "96e0a4e8-fe35-42d0-b942-3a18218d1a95", // Ironclad Mobile Mechanic — Parts Used
  "992c3385-22b5-543d-b585-a7db2ea88d0b", // Arman's Org — Account Type options
  "9d1239e0-832a-4c3d-a2b0-722c57914907", // The Alvarado-Chen Kitchen — shopping_lists
  "9d4d652b-b3df-4574-86cc-fb39afebd180", // Cedar Ridge Physical Therapy — Front Desk Follow-ups
  "9f9241bc-7046-479a-a883-2133ef03cba8", // admin's Workspace — Countries by Continent
  "a1d011b4-a20f-4162-a0a5-f1251cf37c3b", // Harbor Dental Group — Insurance Carriers
  "a1fe654b-d31b-49c8-88c4-32483da5afb6", // admin's Workspace — Model Picks
  "a224d20e-33d8-4535-9653-e569469607d6", // Harbor Dental Group — Operatory Supply Orders
  "a2eacc8b-8d7c-4172-985d-b33888d95470", // Ironline Fitness — plans
  "a4820ec3-a065-4566-a33a-91d97462da3a", // Signal & Scale Podcast — Signal & Scale Podcast: episodes
  "a7294f90-a652-426a-b039-330228ba2bf1", // Arman's Org — Image Styles
  "a7511f92-ace2-41a1-af39-da8efe2585ec", // Cascade Electronics Recovery — Weights By Material
  "a9062928-111d-4b63-a405-9c998ce1493c", // Cedar Ridge Physical Therapy — Visit type choices
  "aa29dca8-65bd-4c7d-90b9-f7b25f0145f6", // admin's Workspace — ZZZ UI-QUICK-1 Rincon-style Jobs — safe to delete
  "aa3f1723-ba82-443b-b255-62adcaf74ebf", // Wraithmoor Regional Museum of Art & Craft — Wraithmoor Regional Museum of Art & Craft: objects
  "aa6b7748-2456-4f23-a772-853ecd963452", // Arman's Org — My Simple Table 3
  "abf4f43d-9877-41c1-8e47-29c26234557b", // Hands & Hope Alliance — campaigns
  "ac68e71f-086b-4de4-8591-6358a2fa8098", // admin's Workspace — V78 Widget2
  "ac738699-b61e-4078-a1f0-eaeb8c4eb730", // Birchwood Avenue Renovation — purchases
  "ad769621-04ba-499b-8414-dc48d589770e", // Ironclad Mobile Mechanic — Service Calls
  "adeb37a2-476e-451a-b4a4-7800303f550f", // Rincon Plumbing Co — Truck 1 dispatch backlog
  "af3b5de5-7cdd-4694-a67e-5d5e77ac9e09", // admin's Workspace — Multiplication
  "af3bfff6-a255-41e5-9ac2-879d53816163", // Rincon Plumbing Co — Jobs
  "b00bde4d-1adc-4682-88eb-57453aabf014", // Harbor Dental Group — Hygiene Recall Schedule
  "b1ff92ea-977a-4af8-aa35-4d637de98019", // Compass Route Relocation Advisors — Compass Route Relocation Advisors: US Large Airports
  "b3893755-a8e8-4aa5-9680-6bf7d32669eb", // Rincon Plumbing Co — Invoices
  "b79ba573-fb65-46f9-be54-e37d11ee4206", // Cedar Ridge Physical Therapy — Visits
  "bd7241b0-5236-45d4-a149-d9a5b673bf2d", // admin's Workspace — Coding Accounts (API proof)
  "bed86cb8-e32e-4cae-a9b3-0b7918791996", // Cedar Ridge Physical Therapy — Patient
  "bf2492e2-8f91-4c76-b248-52e374578d70", // Castellano & Reyes, LLP — Practice Team
  "c0b129d4-12bb-435d-8157-3e9da7659ad7", // Arman's Org — CIC Research
  "c1aabdc0-4d94-42d4-9ddc-91b68ef9c0a7", // Arman's Org — Coding Accounts
  "c1bb3352-c6d9-4f19-8737-80c92c97805c", // The Alvarado-Chen Kitchen — ingredients
  "c21979aa-dc75-4e62-81fa-7b49277649db", // Compass Route Relocation Advisors — October carrier rates (afternoon)
  "c6297d21-c281-4922-9e9d-2c5ab53ec9df", // Cedar Ridge Physical Therapy — Home Exercise Programs
  "ca0c7950-713a-4065-a2c1-f26297c4dee3", // Alex Hart's Workspace — Clients
  "caf6cf44-c379-47b4-ac2b-47412a7bda67", // Birchwood Avenue Renovation — rooms
  "cbed6e95-9276-4225-8402-8531a9d9da4b", // Greenline Landscaping Crew — Schedule
  "ce333886-9253-45e9-a7d5-807e4860d4cf", // Wraithmoor Regional Museum of Art & Craft — Wraithmoor Regional Museum of Art & Craft: makers
  "d06c65b5-5ee1-4799-8d86-523172fdfa62", // The Offside Rule — The Offside Rule: World Cup Finals
  "d239700c-8f2a-52dc-85af-f69b20300b97", // Arman's Org — Status options
  "d2f5059e-bb71-4741-aa1b-413acc4bb1c1", // Wraithmoor Regional Museum of Art & Craft — Wraithmoor Regional Museum of Art & Craft: provenance_records
  "d47b0578-6ad9-4e87-b729-5ae77871930b", // admin's Workspace — Warranty Claims
  "d9d9fd0b-1d1a-4f4c-9778-fa7c08bb3882", // Castellano & Reyes, LLP — Expert
  "dbc7cd48-7b46-4402-ac9d-e459a95f4598", // admin's Workspace — Rincon Plumbing — Service Calls
  "dd073d8c-f6cd-419e-8a81-7ce17cf50b81", // admin's Workspace — Table 1 · 2nd
  "e216a4de-3d73-4927-b31f-492c7b42c0c0", // Titanium — Department
  "e4a35317-9922-4ef4-be1e-f4b748dbe97c", // Ironline Fitness — classes
  "eeb30787-c3fa-4492-97f2-af907eb01bb2", // Castellano & Reyes, LLP — Practice Area
  "efb51c4f-ad00-41d0-9651-a5af7cbf89da", // Rincon Plumbing Co — Customers
  "f26647cc-68bd-4e83-a0e4-f355b62abd1e", // Signal & Scale Podcast — Signal & Scale Podcast: guests
  "f3b31e64-9b7f-4696-aad5-990dabc07bb3", // Harbor Draft Co — V7 every kind of column
  "f8aec271-f73f-49a6-91e7-fd934b3d9a98", // Fairview Shared Services — V7 T8 Shape
  "f9d61a79-0780-4cd2-9b58-3e2a25042714", // Ridgeline Physical Therapy — appointments
  "fa55b71b-e14a-48ac-9ded-f38a6e7af192", // Birchwood Avenue Renovation — contractors
  "fb5e8df1-7f82-467d-b83d-75567a91bdee", // Wraithmoor Regional Museum of Art & Craft — Wraithmoor Regional Museum of Art & Craft: loans
  "fc007161-f1c5-4ea9-9548-eefda0bc7d72", // admin's Workspace — Grid Parity Fixture
  "fdfe20b0-9788-47f1-90ef-9c2ad831021d", // Compass Route Relocation Advisors — Deals
  "fe025317-529a-4e13-b82b-cff8cf149d51", // Arman's Org — Workflow Certification Log
  "ffbddf5c-e5d8-417c-b82b-eff823f55fc4", // Ironclad Mobile Mechanic — Invoices
]);
