/** The resource picker's views (a null id is the picker's own menu). */
export type ResourcePickerViewId =
  | "cloud_browser"
  | "files"
  | "conversations"
  | "notes"
  | "tasks"
  | "workbooks"
  | "documents"
  | "tables"
  | "webpage"
  | "youtube"
  | "image_url"
  | "file_url"
  | "audio"
  | "google"
  | "context_values"
  | "connections"
  | "tools"
  | "skills"
  | null;
