select 'legacy cols left on batch tables' k, count(*)::text v from pg_attribute where attrelid in ('extend.wbx_demo'::regclass,'extend.wbx_guidance'::regclass,'extend.wbx_highlight'::regclass,'legal.wc_claim'::regclass,'education.study_structured_section'::regclass,'education.study_source_chunk'::regclass) and attname in ('is_deleted','is_public','owner_id') and not attisdropped
union all select 'worklist rows (batch tables, excl wc_claim.user_id)', count(*)::text from iam.legacy_column_worklist() where (schema_name,table_name) in (('extend','wbx_demo'),('extend','wbx_guidance'),('extend','wbx_highlight'),('education','study_structured_section'),('education','study_source_chunk')) or (schema_name,table_name,legacy_column)=('legal','wc_claim','is_public')
union all select 'worklist owner_id/is_public/is_deleted total', count(*)::text from iam.legacy_column_worklist() where legacy_column in ('owner_id','is_public','is_deleted')
union all select 'wbx_highlight indexes', string_agg(pg_get_indexdef(indexrelid), ' ; ' order by indexrelid::regclass::text) from pg_index where indrelid='extend.wbx_highlight'::regclass and pg_get_indexdef(indexrelid) like '%deleted_at%'
union all select 'study_source_chunk policies', string_agg(polname||': '||coalesce(pg_get_expr(polqual,polrelid),pg_get_expr(polwithcheck,polrelid)), ' ; ') from pg_policy where polrelid='education.study_source_chunk'::regclass and polname in ('read','ins')
union all select 'study_source_chunk fk/idx', (select string_agg(conname,',') from pg_constraint where conrelid='education.study_source_chunk'::regclass and contype='f')||' / '||(select string_agg(indexrelid::regclass::text,',') from pg_index where indrelid='education.study_source_chunk'::regclass)
union all select 'bridge fns gone', (to_regprocedure('extend._soft_delete_follows_deleted_at()') is null and to_regprocedure('legal._bridge_wc_claim_is_public()') is null)::text
union all select 'row counts demo/guid/hl/wc/sec/chunk', concat_ws('/', (select count(*) from extend.wbx_demo),(select count(*) from extend.wbx_guidance),(select count(*) from extend.wbx_highlight),(select count(*) from legal.wc_claim),(select count(*) from education.study_structured_section),(select count(*) from education.study_source_chunk))
union all select 'wbx_highlight live/deleted', concat_ws('/', (select count(*) from extend.wbx_highlight where deleted_at is null),(select count(*) from extend.wbx_highlight where deleted_at is not null))
union all select 'wc_claim visibility', (select string_agg(visibility::text||'='||n, ',') from (select visibility, count(*) n from legal.wc_claim group by 1) s)
union all select 'ddl_guard_log unacked on batch tables', (select count(*)::text||' '||coalesce(string_agg(distinct rule||':'||severity, ','),'') from platform.ddl_guard_log where acknowledged_at is null and object_ref ~ '(wbx_|wc_claim|study_)')
