// Central Lucide icon registry for shell nav + derived NavigationLink icons.
// Keep in sync with iconName strings in `constants/nav-data.ts`.

import type { LucideIcon } from "lucide-react";
import {
  AppWindow,
  Aperture,
  ArrowLeftRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Brain,
  Braces,
  BadgeDollarSign,
  BadgeCheck,
  Boxes,
  Building2,
  CalendarDays,
  CalendarClock,
  ChevronDown,
  ChevronLeft,
  Compass,
  ChevronRight,
  CircleHelp,
  CircleDollarSign,
  ChartNoAxesColumn,
  ClipboardCheck,
  Code2,
  Columns2,
  Container,
  Database,
  Eraser,
  Eye,
  FileBarChart,
  FileChartColumn,
  FileCheck2,
  FileInput,
  FileScan,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Flame,
  Folder,
  FolderKanban,
  FolderOpen,
  Gamepad2,
  GitCompareArrows,
  Globe,
  GraduationCap,
  Handshake,
  Hash,
  Headphones,
  HeartPulse,
  Images,
  Image,
  Layers,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutTemplate,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  ListTree,
  ListTodo,
  Loader2,
  LogIn,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  Mic,
  Network,
  Newspaper,
  NotebookPen,
  NotepadText,
  PanelLeft,
  PenLine,
  PenTool,
  Plug,
  Plus,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  Scale,
  ScanLine,
  ScanText,
  Scissors,
  Search,
  SearchCheck,
  Send,
  Settings,
  Share2,
  Shapes,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  SquareMousePointer,
  Star,
  Speech,
  Swords,
  Table,
  Target,
  TextCursorInput,
  Trash2,
  TrendingUp,
  User,
  Users,
  Video,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export const shellIconComponents = {
  Compass,
  AppWindow,
  Aperture,
  ArrowLeftRight,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Brain,
  Braces,
  BadgeDollarSign,
  BadgeCheck,
  Boxes,
  Building2,
  CalendarDays,
  CalendarClock,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleHelp,
  CircleDollarSign,
  ChartNoAxesColumn,
  ClipboardCheck,
  Code2,
  Columns2,
  Container,
  Database,
  Eraser,
  Eye,
  FileBarChart,
  FileChartColumn,
  FileCheck2,
  FileInput,
  FileScan,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FlaskConical,
  Flame,
  Folder,
  FolderKanban,
  FolderOpen,
  Gamepad2,
  GitCompareArrows,
  Globe,
  GraduationCap,
  Handshake,
  Hash,
  Headphones,
  HeartPulse,
  Images,
  Image,
  Layers,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LayoutPanelLeft,
  LayoutTemplate,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  ListTree,
  ListTodo,
  Loader2,
  LogIn,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareQuote,
  Mic,
  Network,
  Newspaper,
  NotebookPen,
  NotepadText,
  PanelLeft,
  PenLine,
  PenTool,
  Plug,
  Plus,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  Scale,
  ScanLine,
  ScanText,
  Scissors,
  Search,
  SearchCheck,
  Send,
  Settings,
  Share2,
  Shapes,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  SquareMousePointer,
  Star,
  Speech,
  Swords,
  Table,
  Target,
  TextCursorInput,
  Trash2,
  TrendingUp,
  User,
  Users,
  Video,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
} satisfies Record<string, LucideIcon>;

/** Icon names that are guaranteed to render in every main-shell surface. */
export type ShellIconName = keyof typeof shellIconComponents;

export function isShellIconName(name: string): name is ShellIconName {
  return Object.hasOwn(shellIconComponents, name);
}

/** Structured console diagnostic consumed by the global Error Inspector adapter. */
export class UnregisteredShellIconError extends Error {
  readonly code = "SHELL_ICON_UNREGISTERED";
  readonly iconName: string;
  readonly fallbackIconName = "CircleHelp";

  constructor(iconName: string) {
    super(`[shell-nav] Unregistered icon name: ${iconName}`);
    this.name = "UnregisteredShellIconError";
    this.iconName = iconName;
  }
}

/**
 * Normalizes persisted or external icon names before they enter typed shell
 * navigation. Unknown values stay visible as a help glyph instead of leaving
 * a blank hole in the menu.
 */
export function resolveShellIconName(
  name: string | null | undefined,
): ShellIconName {
  if (name && isShellIconName(name)) return name;
  if (name) console.error(new UnregisteredShellIconError(name));
  return "CircleHelp";
}
