import { openWalk, bodyText, sleep, until } from "../lib/harness.mjs";
const ctx = await openWalk("t3-explore");
const page = await ctx.page("admin");
const T = process.env.T;
const text = async () => (await page.locator("main").innerText().catch(() => "")).replace(/\s+/g, " ");
await ctx.goto(page, `/data-v2/${T}?view=sheet`);
await page.locator('[data-sheet-layout]').waitFor({ timeout: 120000 }).catch(()=>console.log("no sheet-layout"));
await sleep(4000);
console.log("BUTTONS", JSON.stringify(await page.locator("button:visible").allInnerTexts()));
await ctx.shot(page, "sheet");
console.log("HTMLsheet", (await page.locator('[data-sheet-layout]').first().evaluate(e=>e.outerHTML.slice(0,1500)).catch(()=>"-")));
await ctx.finish();
