import { buildNotesEditorContextData } from "./buildNotesEditorContextData";

const NOTE_ID = "22222222-2222-4222-8222-222222222222";

function build(overrides: Partial<Parameters<typeof buildNotesEditorContextData>[0]> = {}) {
  return buildNotesEditorContextData({
    noteId: NOTE_ID,
    content: "# Heading\nA persisted note body.",
    selectionStart: 0,
    selectionEnd: 0,
    editorMode: "plain",
    ...overrides,
  });
}

describe("notes agent context", () => {
  it("sends one canonical reference for a clean persisted note", () => {
    const scope = build();
    expect(scope.current_note).toEqual({
      __kind: "resource_ref",
      resource_type: "note",
      resource_id: NOTE_ID,
    });
    expect(scope.content).toBeUndefined();
    expect(scope.active_text).toBeUndefined();
    expect(scope.current_note_title).toBeUndefined();
  });

  it("carries an unsaved buffer inside the same reference", () => {
    const scope = build({ content: "unsaved body", isDirty: true });
    expect(scope.current_note).toEqual(
      expect.objectContaining({
        resource_id: NOTE_ID,
        overlay: { content: "unsaved body", is_dirty: true },
      }),
    );
    expect(scope.content).toBeUndefined();
  });

  it("uses the content escape hatch only for a new client-only note", () => {
    const scope = build({ noteId: "__phantom__", content: "new note", isAutogenerated: true });
    expect(scope.current_note).toBeUndefined();
    expect(scope.content).toBe("new note");
  });
});
