import pg from "pg";
import { loadBranchRef, loadBranchDbEnv } from "./lib/migration-target";
const ROOT = "/Users/armanisadeghi/code/matrx-frontend";
const env = loadBranchDbEnv(ROOT, loadBranchRef(ROOT));
const c = new pg.Client({ host: env.host, port: env.port, user: env.user, password: env.password, database: env.database, ssl: { rejectUnauthorized: false } });
await c.connect();
const mode = process.argv[2];
if (mode === "take") await c.query(`insert into campaign_watch.build_lock (lock_name, held_by, note) values ('platform','CI-FIX-3','impl-doors D11 + D16a') on conflict (lock_name) do nothing`);
if (mode === "release") await c.query(`delete from campaign_watch.build_lock where lock_name='platform' and held_by='CI-FIX-3'`);
const all = await c.query(`select lock_name, held_by from campaign_watch.build_lock order by lock_name`);
console.log("HELD NOW: " + JSON.stringify(all.rows));
await c.end();
