import { chromium } from "playwright";
import { readFileSync } from "node:fs";
const ORIGIN = "http://fts5c.localhost:3001";
const env = Object.fromEntries(readFileSync("/Users/armanisadeghi/code/matrx-frontend/.env.local","utf8").split("\n").map(l=>l.match(/^([A-Z_]+)=(.*)$/)).filter(Boolean).map(m=>[m[1],m[2].replace(/^["']|["']$/g,"")]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext({ viewport:{width:1440,height:1000}})).newPage();
const resume = async()=>{ if(page.url().includes("__dev-walk")){ await page.getByRole("button",{name:"Resume this preview"}).click(); await page.waitForURL(u=>!u.href.includes("__dev-walk"),{timeout:180000}); } };
const go = async p=>{ await page.goto(ORIGIN+p,{waitUntil:"domcontentloaded",timeout:180000}); await resume(); };
await go("/login");
await page.waitForSelector("#email",{timeout:90000}); await sleep(2000);
await page.fill("#email",env.AI_ADMIN_USERNAME); await page.fill("#password",env.AI_ADMIN_PASSWORD);
await page.click('button:has-text("Sign in")');
await page.waitForURL(u=>!u.pathname.startsWith("/login"),{timeout:90000}); await resume();
console.log("who", await page.evaluate(async()=>(await (await fetch("/api/whoami")).json())?.email));
await go("/data"); await sleep(8000);
const links = await page.evaluate(()=>[...document.querySelectorAll("a[href*='/data/']")].map(a=>a.getAttribute("href")+" | "+a.textContent.trim().slice(0,50)).slice(0,30));
console.log(links.join("\n"));
await page.screenshot({path:"/private/tmp/claude-501/-Users-armanisadeghi-code/67577819-d4bf-4669-972f-e5ba5c2428f7/scratchpad/data.png"});
await browser.close();
