/**
 * THE SURFACE INDEX GENERATOR + GUARD (BUNDLE-3).
 *
 * The browser's first load carries only the surface INDEX (`@ai-matrx/chat`
 * `SurfaceIndexEntry`: delivery fields of every surface); each manifest's BODY
 * (descriptions, groups, write targets, client tools, roles) loads lazily.
 * This script writes the compact index from the full registry, and checks it.
 *
 *   pnpm generate:surface-index        # write features/surfaces/manifests/generated/surface-index.generated.ts
 *   pnpm check:surface-index           # fail on any field-level drift, a broken budget, or a stale file
 *   pnpm check:surface-index --self-test   # prove the check goes RED on a one-value edit, then GREEN
 *
 * The check resolves the GENERATED index exactly as the browser does
 * (`createIndexedSurfaceSource`) and compares every indexed field of every
 * surface against the full registry's projection (`toSurfaceIndexEntry`) —
 * resolved values (inherited + baselines, provenance, groupKey), raw authored
 * value names, client-tool names, ancestry and children. Importing the full
 * registry also runs its registry-level assertions (reserved names, executor)
 * at build time.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { gzipSync } from "node:zlib";
import {
  createIndexedSurfaceSource,
  encodeSurfaceIndex,
  toSurfaceIndexEntry,
  type EncodedSurface,
} from "@ai-matrx/chat/surfaces/runtime/registry";
import { BASELINE_VALUES } from "@ai-matrx/chat/surfaces/manifests/_baseline.manifest";
import {
  RAW_MANIFESTS,
  getAllManifests,
  getManifest,
  getRawManifest,
  getSurfaceAncestry,
  getSurfaceChildren,
} from "@/features/surfaces/manifests/registry";

const ROOT = join(dirname(new URL(import.meta.url).pathname), "..");
const OUT = join(ROOT, "features/surfaces/manifests/generated/surface-index.generated.ts");
/** The first-load budget for the index module, gzip bytes. */
const INDEX_BUDGET_GZIP = 50 * 1024;

function render(encoded: readonly EncodedSurface[]): string {
  return (
    "// GENERATED by scripts/generate-surface-index.ts — never edit by hand.\n" +
    "// pnpm generate:surface-index rewrites it; pnpm check:surface-index guards it.\n" +
    'import type { EncodedSurface } from "@ai-matrx/chat/surfaces/runtime/registry";\n\n' +
    "export const SURFACE_INDEX: readonly EncodedSurface[] = " +
    JSON.stringify(encoded) +
    ";\n"
  );
}

function stable(value: unknown): string {
  return JSON.stringify(value, (_k, v) =>
    v && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => a.localeCompare(b)))
      : v,
  );
}

/** Field-by-field differences between the resolved generated index and the registry. */
export function compareIndex(encoded: readonly EncodedSurface[]): string[] {
  const source = createIndexedSurfaceSource({
    encoded,
    baselineValues: Object.values(BASELINE_VALUES),
    loadBody: () => undefined,
  });
  const problems: string[] = [];
  const expected = getAllManifests();
  const got = source.getAllIndexEntries();
  if (stable(got.map((e) => e.surfaceName)) !== stable(expected.map((m) => m.surfaceName))) {
    problems.push("surface list or order differs");
  }
  for (const full of expected) {
    const name = full.surfaceName;
    const want = toSurfaceIndexEntry(full, getRawManifest(name)) as unknown as Record<string, unknown>;
    const have = source.getIndexEntry(name) as unknown as Record<string, unknown> | undefined;
    if (!have) {
      problems.push(`${name}: missing from the index`);
      continue;
    }
    for (const key of new Set([...Object.keys(want), ...Object.keys(have)])) {
      if (key === "values") continue;
      if (stable(want[key]) !== stable(have[key])) {
        problems.push(`${name}.${key}: index ${stable(have[key])} ≠ registry ${stable(want[key])}`);
      }
    }
    const wv = want.values as Record<string, unknown>[];
    const hv = have.values as Record<string, unknown>[];
    if (wv.length !== hv.length) problems.push(`${name}.values: ${hv.length} ≠ ${wv.length}`);
    wv.forEach((v, i) => {
      for (const key of new Set([...Object.keys(v), ...Object.keys(hv[i] ?? {})])) {
        if (stable(v[key]) !== stable(hv[i]?.[key])) {
          problems.push(
            `${name}.values[${i}:${String(v.name)}].${key}: index ${stable(hv[i]?.[key])} ≠ registry ${stable(v[key])}`,
          );
        }
      }
    });
    if (stable(source.getSurfaceAncestry(name)) !== stable(getSurfaceAncestry(name))) {
      problems.push(`${name}: ancestry differs`);
    }
    if (stable(source.getSurfaceChildren(name)) !== stable(getSurfaceChildren(name))) {
      problems.push(`${name}: children differ`);
    }
  }
  return problems;
}

function build(): { encoded: EncodedSurface[]; text: string } {
  const encoded = encodeSurfaceIndex(RAW_MANIFESTS, getManifest);
  return { encoded, text: render(encoded) };
}

function check(text: string, encoded: readonly EncodedSurface[]): string[] {
  const problems = compareIndex(encoded);
  const gz = gzipSync(text).length;
  if (gz > INDEX_BUDGET_GZIP) problems.push(`index is ${gz} B gzip, over the ${INDEX_BUDGET_GZIP} B budget`);
  return problems;
}

function main(): void {
  const args = process.argv.slice(2);
  if (args.includes("--write")) {
    const { encoded, text } = build();
    const problems = check(text, encoded);
    if (problems.length) {
      console.error(problems.slice(0, 20).join("\n"));
      process.exit(1);
    }
    mkdirSync(dirname(OUT), { recursive: true });
    writeFileSync(OUT, text);
    console.log(`surface index: ${encoded.length} surfaces, ${text.length} B, ${gzipSync(text).length} B gzip → ${OUT}`);
    return;
  }
  if (args.includes("--self-test")) {
    const { encoded } = build();
    // RED: one inlined value's autoContext flipped in the generated data.
    const tampered = JSON.parse(JSON.stringify(encoded)) as EncodedSurface[];
    const row = tampered.find((s) => s[3].length > 0)!;
    (row[3][0] as unknown[])[2] = ((row[3][0] as number[])[2] ^ 2) as number;
    const red = compareIndex(tampered);
    // RED: a parent chain cut (inheritsFrom dropped).
    const cut = JSON.parse(JSON.stringify(encoded)) as EncodedSurface[];
    const child = cut.find((s) => typeof s[1].inheritsFrom === "string")!;
    delete child[1].inheritsFrom;
    const redChain = compareIndex(cut);
    const green = compareIndex(encoded);
    console.log(`self-test RED (value flag edit): ${red.length} problem(s) — ${red[0] ?? "none"}`);
    console.log(`self-test RED (parent chain cut): ${redChain.length} problem(s) — ${redChain[0] ?? "none"}`);
    console.log(`self-test GREEN (generated): ${green.length} problem(s)`);
    if (red.length === 0 || redChain.length === 0 || green.length !== 0) process.exit(1);
    return;
  }
  // Default: check the committed file.
  const { text: fresh } = build();
  let committed = "";
  try {
    committed = readFileSync(OUT, "utf8");
  } catch {
    console.error(`missing ${OUT} — run pnpm generate:surface-index`);
    process.exit(1);
  }
  const encoded = JSON.parse(committed.slice(committed.indexOf("= ") + 2, committed.lastIndexOf(";"))) as EncodedSurface[];
  const problems = check(committed, encoded);
  if (committed !== fresh) problems.push("generated file is stale — run pnpm generate:surface-index");
  if (problems.length) {
    console.error(`check:surface-index RED — ${problems.length} problem(s):\n` + problems.slice(0, 25).join("\n"));
    process.exit(1);
  }
  console.log(`check:surface-index GREEN — ${encoded.length} surfaces match field by field; ${gzipSync(committed).length} B gzip (budget ${INDEX_BUDGET_GZIP})`);
}

main();
