/**
 * registry.parity.test.ts — TS ↔ DB shareable-resource registry parity.
 *
 * The single source of truth is the Postgres table
 * `public.shareable_resource_registry`. The TS module
 * `utils/permissions/registry.ts` is a hand-mirrored copy so the FE doesn't
 * have to fetch it on every page load. This test is the forcing function that
 * keeps them locked together: if anyone adds/removes/changes a row in EITHER
 * the DB or the TS file without updating the other, this test fails loudly.
 *
 * Without this test, we already shipped one 'agent' bug to production where
 * the FE thought it was registered and the RPC didn't know about it. Don't
 * repeat that.
 *
 * The test reads the DB snapshot from a JSON file checked into the repo
 * (utils/permissions/__tests__/registry.db-snapshot.json). The snapshot is
 * regenerated by running:
 *
 *   pnpm tsx scripts/regen-shareable-registry-snapshot.ts
 *
 * That script is the ONE step required after applying a registry migration,
 * and the script itself fails if you forget to update the TS mirror first.
 *
 * Why a JSON snapshot instead of querying the live DB at test time?
 *  - Tests must run offline, in CI, on PR forks, in pre-commit hooks.
 *  - Live DB queries are flaky, slow, and require service-role credentials.
 *  - A committed snapshot is auditable in PR review: "this PR adds task to
 *    the registry" is visible in the diff of two files (the migration and
 *    the snapshot).
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  SHAREABLE_RESOURCE_REGISTRY,
  RESOURCE_TYPES,
  type ShareableResourceEntry,
} from "../registry";

interface DbRegistryRow {
  resource_type: string;
  table_name: string;
  id_column: string;
  owner_column: string;
  is_public_column: string | null;
  display_label: string;
  url_path_template: string;
  rls_uses_has_permission: boolean;
  is_active: boolean;
}

const SNAPSHOT_PATH = join(__dirname, "registry.db-snapshot.json");

function loadDbSnapshot(): DbRegistryRow[] {
  const raw = readFileSync(SNAPSHOT_PATH, "utf-8");
  const rows = JSON.parse(raw) as DbRegistryRow[];
  return rows.filter((r) => r.is_active);
}

function dbRowToEntry(row: DbRegistryRow): ShareableResourceEntry {
  return {
    resourceType: row.resource_type,
    tableName: row.table_name,
    idColumn: row.id_column,
    ownerColumn: row.owner_column,
    isPublicColumn: row.is_public_column,
    displayLabel: row.display_label,
    urlPathTemplate: row.url_path_template,
    rlsUsesHasPermission: row.rls_uses_has_permission,
  };
}

/**
 * The 8 DB-mirrored fields. The TS registry may carry FE-only routing fields
 * (`schemaName` / `physicalTable`, e.g. for `file` / `folder` after the 2026
 * `files`-schema move) that the DB `shareable_resource_registry` doesn't have.
 * Per-row exact-match comparison must therefore look ONLY at the DB fields and
 * tolerate FE-only extras.
 */
const DB_MIRRORED_KEYS = [
  "resourceType",
  "tableName",
  "idColumn",
  "ownerColumn",
  "isPublicColumn",
  "displayLabel",
  "urlPathTemplate",
  "rlsUsesHasPermission",
] as const satisfies readonly (keyof ShareableResourceEntry)[];

function pickDbFields(entry: ShareableResourceEntry): ShareableResourceEntry {
  const picked: Record<string, unknown> = {};
  for (const key of DB_MIRRORED_KEYS) {
    picked[key] = entry[key];
  }
  return picked as unknown as ShareableResourceEntry;
}

describe("shareable_resource_registry: TS ↔ DB parity", () => {
  const dbRows = loadDbSnapshot();
  const tsKeys = RESOURCE_TYPES.slice().sort();
  const dbKeys = dbRows.map((r) => r.resource_type).sort();

  it("the TS registry covers every active DB row", () => {
    const missingInTs = dbKeys.filter((k) => !tsKeys.includes(k as never));
    expect(missingInTs).toEqual([]);
  });

  it("the TS registry has no entries that are missing from the DB", () => {
    const missingInDb = tsKeys.filter((k) => !dbKeys.includes(k));
    expect(missingInDb).toEqual([]);
  });

  it.each(dbRows.map((row) => [row.resource_type, row]))(
    "%s: every column matches the DB row exactly",
    (_alias, dbRow) => {
      const tsEntry =
        SHAREABLE_RESOURCE_REGISTRY[
          dbRow.resource_type as keyof typeof SHAREABLE_RESOURCE_REGISTRY
        ];
      expect(tsEntry).toBeDefined();
      expect(pickDbFields(tsEntry)).toEqual(dbRowToEntry(dbRow));
    },
  );

  it("every entry has a non-empty url_path_template", () => {
    for (const entry of Object.values(SHAREABLE_RESOURCE_REGISTRY)) {
      expect(entry.urlPathTemplate.length).toBeGreaterThan(0);
    }
  });

  it("every per-instance entry's url_path_template contains {id}", () => {
    // Most registry entries deep-link to a specific record and MUST carry the
    // {id} placeholder. A few DB rows are list/settings surfaces with no
    // per-record route (scraper_preset → /scraper?tab=presets,
    // scraper_schedule → /scraper?tab=schedules,
    // user_analysis_preferences → /settings/analysis). Those legitimately have
    // no {id} in the DB registry (the source of truth). We derive the
    // expectation from the DB snapshot so the TS mirror is held to exactly the
    // same {id} contract the DB declares — never weaker, never stronger.
    for (const dbRow of dbRows) {
      const entry =
        SHAREABLE_RESOURCE_REGISTRY[
          dbRow.resource_type as keyof typeof SHAREABLE_RESOURCE_REGISTRY
        ];
      if (dbRow.url_path_template.includes("{id}")) {
        expect(entry.urlPathTemplate).toMatch(/\{id\}/);
      }
    }
  });

  it("table_name appears at most once across the registry (no duplicate canonicals)", () => {
    const seen = new Map<string, string>();
    for (const entry of Object.values(SHAREABLE_RESOURCE_REGISTRY)) {
      const prior = seen.get(entry.tableName);
      if (prior) {
        throw new Error(
          `Duplicate canonical table_name "${entry.tableName}" — used by both ` +
            `"${prior}" and "${entry.resourceType}". Only one alias may map to a given table.`,
        );
      }
      seen.set(entry.tableName, entry.resourceType);
    }
  });
});
