/**
 * TS ↔ Python parity for the per-page SEO CHECK layer (the verdicts).
 *
 * The fixture (`__fixtures__/page-checks-parity.json`) is GENERATED by the
 * Python implementation (`aidream packages/matrx-scraper/matrx_scraper/
 * seo_audit.py::run_page_checks`) — never hand-maintained. This test replays
 * the same evidence through `runPageChecks` and asserts identical output:
 * status, score, issue count, evidence payload, and the reasoning string
 * character for character (a reasoning string is a user-facing expert
 * sentence; a difference means one page gets two explanations).
 *
 * If this fails, one side changed without the other. Fix BOTH in the same
 * unit of work and regenerate:
 *
 *   .venv/bin/python packages/matrx-scraper/scripts/generate_page_checks_parity_fixture.py
 */

import {
  runPageChecks,
  type CheckMetaMetrics,
  type CheckOutcome,
  type HeadingEvidenceItem,
  type PageEvidence,
  type PageImageItem,
  type RedirectHop,
  type Remediation,
} from "./checks";
import parity from "./__fixtures__/page-checks-parity.json";

/** The Python `PageEvidence` dataclass, as serialized into the fixture. */
interface PythonEvidence {
  url: string;
  title: string | null;
  title_metrics: CheckMetaMetrics;
  description: string | null;
  description_metrics: CheckMetaMetrics;
  meta_robots: string | null;
  canonical_url: string | null;
  canonical_matches: boolean | null;
  noindex: boolean | null;
  nofollow: boolean | null;
  h1_count: number | null;
  headings: HeadingEvidenceItem[] | null;
  word_count: number | null;
  text_bytes: number | null;
  schema_types: string[] | null;
  image_count: number | null;
  images_missing_alt: number | null;
  image_items: PageImageItem[];
  http_status: number | null;
  redirect_chain: RedirectHop[];
  mixed_content: string[];
  response_headers: Record<string, string> | null;
  http_variant_probe: Record<string, unknown> | null;
  response_bytes: number | null;
  response_time_ms: number | null;
  ttfb_ms: number | null;
  pagination: Record<string, unknown>;
  hreflang: Record<string, unknown>[];
  structured_data: Record<string, unknown>;
  head_captured: boolean;
  lang: string | null;
  og: Record<string, string>;
  twitter: Record<string, string>;
  head_meta: Record<string, unknown> | null;
  lab_performance: PythonLabPerformance | null;
}

/** Python's `LabPerformance`, as `dataclasses.asdict` serializes it. */
interface PythonLabPerformance {
  strategy: string;
  observed_at: string | null;
  lcp_ms: number | null;
  tbt_ms: number | null;
  cls: number | null;
  delivery_savings_ms: number | null;
  delivery_audits: Record<string, number>;
  cache_static_bytes: number | null;
  cache_short_ttl_resources: Record<string, unknown>[];
}

interface PythonOutcome {
  status: string;
  score: number | null;
  reasoning: string;
  issue_count: number;
  evidence: Record<string, unknown> | null;
  /**
   * The typed one-click fix a blocked (`n_a`) check attaches. Part of parity:
   * if Python offers the user a button and the browser mirror does not, the
   * live audit becomes the dead end the binding exists to remove.
   */
  remediation: Remediation | null;
}

interface ParityCase {
  name: string;
  why: string;
  evidence: PythonEvidence;
  expected: Record<string, PythonOutcome>;
}

const fixture = parity as unknown as {
  check_names: string[];
  cases: ParityCase[];
};

/** snake_case wire shape → the camelCase TS evidence shape. */
function toPageEvidence(raw: PythonEvidence): PageEvidence {
  return {
    url: raw.url,
    title: raw.title,
    titleMetrics: raw.title_metrics,
    description: raw.description,
    descriptionMetrics: raw.description_metrics,
    metaRobots: raw.meta_robots,
    canonicalUrl: raw.canonical_url,
    canonicalMatches: raw.canonical_matches,
    noindex: raw.noindex,
    nofollow: raw.nofollow,
    h1Count: raw.h1_count,
    headings: raw.headings,
    wordCount: raw.word_count,
    textBytes: raw.text_bytes,
    schemaTypes: raw.schema_types,
    imageCount: raw.image_count,
    imagesMissingAlt: raw.images_missing_alt,
    imageItems: raw.image_items,
    httpStatus: raw.http_status,
    redirectChain: raw.redirect_chain,
    mixedContent: raw.mixed_content,
    responseHeaders: raw.response_headers,
    httpVariantProbe: raw.http_variant_probe,
    responseBytes: raw.response_bytes,
    responseTimeMs: raw.response_time_ms,
    ttfbMs: raw.ttfb_ms,
    pagination: raw.pagination,
    hreflang: raw.hreflang,
    structuredData: raw.structured_data,
    headCaptured: raw.head_captured,
    lang: raw.lang,
    og: raw.og,
    twitter: raw.twitter,
    headMeta: raw.head_meta,
    labPerformance: raw.lab_performance
      ? {
          strategy: raw.lab_performance.strategy,
          observedAt: raw.lab_performance.observed_at,
          lcpMs: raw.lab_performance.lcp_ms,
          tbtMs: raw.lab_performance.tbt_ms,
          cls: raw.lab_performance.cls,
          deliverySavingsMs: raw.lab_performance.delivery_savings_ms,
          deliveryAudits: raw.lab_performance.delivery_audits,
          cacheStaticBytes: raw.lab_performance.cache_static_bytes,
          cacheShortTtlResources: raw.lab_performance.cache_short_ttl_resources,
        }
      : null,
  };
}

function toWire(result: CheckOutcome): PythonOutcome {
  return {
    status: result.status,
    score: result.score,
    reasoning: result.reasoning,
    issue_count: result.issueCount,
    evidence: result.evidence,
    remediation: result.remediation,
  };
}

/**
 * The checks whose subject is a MEASUREMENT. With no evidence captured, each
 * must answer n_a (or fail on a genuinely absent required tag) — a pass would
 * be a silent lie. The checks left out below answer about an ABSENCE that is
 * itself the fact ("no robots directives", "no redirect chain", "no insecure
 * resources"), so a pass there is correct.
 */
const MEASURED_CHECKS = [
  "title_length",
  "meta_description_length",
  "h1_presence",
  "thin_content",
  "image_alt_presence",
  "canonical_conflicts",
  "broken_page_4xx",
  "server_error_5xx",
  "pagination_markup",
  "page_weight",
  "ttfb_server_response",
];

describe("per-page SEO checks TS ↔ Python parity", () => {
  it("fixture is non-trivial and covers every registered check", () => {
    expect(fixture.cases.length).toBeGreaterThanOrEqual(20);
    // Not a hard-coded count: the check set grows, and the order test below
    // is what pins TS to Python exactly.
    expect(fixture.check_names.length).toBeGreaterThanOrEqual(18);
    const names = fixture.cases.map((c) => c.name);
    expect(names).toContain("healthy_page");
    expect(names).toContain("all_evidence_missing");
  });

  it("TS registers exactly the Python check set, in the same order", () => {
    expect(Object.keys(runPageChecks({ url: "https://example.com" }))).toEqual(
      fixture.check_names,
    );
  });

  it.each(fixture.cases.map((c) => [c.name, c] as const))(
    "case %s matches Python for every check",
    (_name, testCase) => {
      const results = runPageChecks(toPageEvidence(testCase.evidence));
      const wire: Record<string, PythonOutcome> = {};
      for (const [key, value] of Object.entries(results)) {
        wire[key] = toWire(value);
      }
      expect(wire).toEqual(testCase.expected);
    },
  );

  it("a page with no evidence never silently passes a measured check", () => {
    const results = runPageChecks({ url: "https://example.com/nothing-known" });
    for (const key of MEASURED_CHECKS) {
      expect([key, results[key].status]).toEqual([
        key,
        expect.stringMatching(/^(n_a|fail)$/),
      ]);
    }
    // The two required tags are absent facts, not unmeasured ones.
    expect(results.title_presence.status).toBe("fail");
    expect(results.meta_description_presence.status).toBe("fail");
  });
});
