/**
 * THE PAGE-CLEANUP LIST — every page the 2026-10-03 unreachable-routes audit recommended KILL or
 * ASK (nothing in the app links to them), plus the redirect-only aliases and the empty shells as a
 * lower group. Generated once from that audit; the owner decides each row on /review/page-cleanup.
 *
 * `href` is what the row opens in a new tab: the page itself, or for a path with a [segment] the
 * nearest parent that is a real page (`note` says why), or null when nothing routes.
 *
 * GROUPS (2026-10-05, re-checked by reading every `orphan` row's page.tsx): `orphan` holds only
 * genuinely separate pages. A page that redirects, re-exports, or renders another page's component
 * (or a copy of it) under an old address is `forward`, with `target` naming that page — 8 rows moved
 * there from `orphan` (org-2, education notes /edit, six /rag/* copies of /knowledge/*), joining
 * the redirect-only aliases. `lower` is the empty shells.
 */

export type CleanupRecommendation = "KILL" | "ASK" | "ALIAS" | "SHELL";
export type CleanupGroup = "orphan" | "forward" | "lower";

export interface CleanupRow {
  path: string;
  area: string;
  what: string;
  rec: CleanupRecommendation;
  reason: string;
  group: CleanupGroup;
  href: string | null;
  note: string | null;
  /** `forward` rows: the page this old address sends people to or shows (→ target). */
  target: string | null;
  /** `orphan` rows: what deleting it takes away, read from its page.tsx imports (≤60 chars). */
  removes: string | null;
}

export const PAGE_CLEANUP_ROWS: readonly CleanupRow[] = [
  { path: "/organizations/[orgId]/org-2", area: "account / organizations", what: "Legacy alias of the org workspace", rec: "KILL", reason: "page says \"kept so old /org-2 links still resolve\"; same as /organizations/[orgId]", group: "forward", href: "/organizations", note: "needs a record id" , target: "/organizations/[orgId]", removes: null },
  { path: "/scopes/fade-lab", area: "account / scopes-context", what: "Header fade lab", rec: "KILL", reason: "lab page in core (UI experiment for scope headers); linked nowhere", group: "orphan", href: "/scopes/fade-lab", note: null , target: null, removes: "Page and its header fade experiment" },
  { path: "/google-analytics-youtube-review", area: "account / settings", what: "Google OAuth verification review page", rec: "ASK", reason: "probably intentionally unlinked (Google reviewers need a stable URL); confirm and keep", group: "orphan", href: "/google-analytics-youtube-review", note: null , target: null, removes: "Page and its Google review component" },
  { path: "/agents/[id]/shortcuts/old/edit/[shortcutId]", area: "agents / agent-shortcuts", what: "Legacy edit-shortcut route", rec: "KILL", reason: "same as /agents/[id]/shortcuts/[shortcutId]; nothing links the old copy", group: "orphan", href: "/agents", note: "needs a record id" , target: null, removes: "Page only; old editor still used in admin" },
  { path: "/agents/[id]/shortcuts/old/new", area: "agents / agent-shortcuts", what: "Legacy new-shortcut route (AgentNewShortcutLegacyRoute)", rec: "KILL", reason: "same as /agents/[id]/shortcuts/new; nothing links the old copy", group: "orphan", href: "/agents", note: "needs a record id" , target: null, removes: "Page only; old editor still used in admin" },
  { path: "/agent-lists", area: "agents / agent-tools", what: "Agent lists hub (ListsHubView, todos and plans agents write)", rec: "ASK", reason: "real page, zero inbound links; unclear whether it belongs under Chat/AI Work or is superseded", group: "orphan", href: "/agent-lists", note: null , target: null, removes: "Page and the lists hub view in the chat package" },
  { path: "/chat/message-templates/edit/[id]", area: "communications / message-templates", what: "Old template edit page (TemplateEditor)", rec: "KILL", reason: "same as /chat/message-templates/[id]?mode=edit, which is the linked editor since the 2026-09-27 page pass", group: "orphan", href: "/chat/message-templates", note: "needs a record id" , target: null, removes: "Page only; its editor stays for new templates" },
  { path: "/messages-showcase", area: "communications / messaging", what: "Messages showcase (login-gated)", rec: "ASK", reason: "showcase page in core; only linked from the unreachable /messages/admin map; keep as demo or move to (dev)", group: "orphan", href: "/messages-showcase", note: null , target: null, removes: "Page and its showcase demo component" },
  { path: "/commerce/intake/v2/instant", area: "industries / commerce", what: "Isolated iPhone-style intake rebuilds (v2 instant, v3, v3 instant)", rec: "ASK", reason: "FEATURE.md says they replace /commerce/intake only after Arman approves; owner must pick winner or kill", group: "orphan", href: "/commerce/intake/v2/instant", note: null , target: null, removes: "Page only; v2 intake code stays for /v2" },
  { path: "/commerce/intake/v3", area: "industries / commerce", what: "Isolated iPhone-style intake rebuilds (v2 instant, v3, v3 instant)", rec: "ASK", reason: "FEATURE.md says they replace /commerce/intake only after Arman approves; owner must pick winner or kill", group: "orphan", href: "/commerce/intake/v3", note: null , target: null, removes: "Page; v3 intake code too if v3 instant goes" },
  { path: "/commerce/intake/v3/instant", area: "industries / commerce", what: "Isolated iPhone-style intake rebuilds (v2 instant, v3, v3 instant)", rec: "ASK", reason: "FEATURE.md says they replace /commerce/intake only after Arman approves; owner must pick winner or kill", group: "orphan", href: "/commerce/intake/v3/instant", note: null , target: null, removes: "Page only; v3 intake code stays for /v3" },
  { path: "/education/notes/[id]/edit", area: "industries / education", what: "Note editor route (EduNoteWorkspace)", rec: "KILL", reason: "same as /education/notes/[id]; nothing links /edit", group: "forward", href: "/education/notes", note: "needs a record id" , target: "/education/notes/[id]", removes: null },
  { path: "/education/notes/new", area: "industries / education", what: "Create-a-note-then-open page", rec: "KILL", reason: "superseded: the Notes home creates inline and opens /education/notes/[id]", group: "orphan", href: "/education/notes/new", note: null , target: null, removes: "Page and its create-note component" },
  { path: "/intelligence/[feature]/unassigned", area: "intelligence / mandates", what: "Domain \"unassigned\" intelligence bucket", rec: "ASK", reason: "only reachable by the [feature] route redirecting; confirm it is still wanted", group: "orphan", href: "/intelligence", note: "needs a record id" , target: null, removes: "Page only; shared intelligence views stay" },
  { path: "/compare/old", area: "knowledge / rag", what: "Index of old Knowledge pages kept for side-by-side review", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old", note: null , target: null, removes: "Page and its list of old/new pairs" },
  { path: "/compare/old/data-stores", area: "knowledge / rag", what: "Restored copy of the old Data Stores list", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/data-stores", note: null , target: null, removes: "Page only; Data Stores stays live" },
  { path: "/compare/old/graph-demo", area: "knowledge / rag", what: "Restored flow-animation demo", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/graph-demo", note: null , target: null, removes: "Page only; the flow animation stays live" },
  { path: "/compare/old/knowledge-home", area: "knowledge / rag", what: "Restored old Knowledge home", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/knowledge-home", note: null , target: null, removes: "Page and its restored old home copy" },
  { path: "/compare/old/libraries", area: "knowledge / rag", what: "Restored old Libraries list", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/libraries", note: null , target: null, removes: "Page and its restored Libraries copy" },
  { path: "/compare/old/library-catalog", area: "knowledge / rag", what: "Restored old Library catalog list", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/library-catalog", note: null , target: null, removes: "Page only; Library catalog stays live" },
  { path: "/compare/old/rag", area: "knowledge / rag", what: "Table of the old /rag/* family and their new homes", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/rag", note: null , target: null, removes: "Page only" },
  { path: "/compare/old/sources", area: "knowledge / rag", what: "Restored old Sources page", rec: "ASK", reason: "review-only scaffolding from 2026-09-29 and the index itself has no link; kill when the Knowledge hub is signed off", group: "orphan", href: "/compare/old/sources", note: null , target: null, removes: "Page and its restored Sources copy" },
  { path: "/rag", area: "knowledge / rag", what: "Old Knowledge home (RagHomePage)", rec: "KILL", reason: "same as /knowledge; old /rag family from before the H6a hub move", group: "orphan", href: "/rag", note: null , target: null, removes: "Page and the old Knowledge home component" },
  { path: "/rag/admin", area: "knowledge / rag", what: "Old Knowledge admin map", rec: "KILL", reason: "same as /knowledge/admin", group: "forward", href: "/rag/admin", note: null , target: "/knowledge/admin", removes: null },
  { path: "/rag/data-stores", area: "knowledge / rag", what: "Old Data Stores page", rec: "KILL", reason: "same as /knowledge/data-stores", group: "forward", href: "/rag/data-stores", note: null , target: "/knowledge/data-stores", removes: null },
  { path: "/rag/flow", area: "knowledge / rag", what: "Old pipeline flow page", rec: "KILL", reason: "same as /knowledge/flow", group: "forward", href: "/rag/flow", note: null , target: "/knowledge/flow", removes: null },
  { path: "/rag/library", area: "knowledge / rag", what: "Old Sources page", rec: "KILL", reason: "same as /knowledge/library, which re-exports this file: move the page into /knowledge/library first, then delete", group: "forward", href: "/rag/library", note: null , target: "/knowledge/library", removes: null },
  { path: "/rag/library-catalog", area: "knowledge / rag", what: "Old Library catalog page", rec: "KILL", reason: "same as /knowledge/library-catalog", group: "forward", href: "/rag/library-catalog", note: null , target: "/knowledge/library-catalog", removes: null },
  { path: "/rag/repositories", area: "knowledge / rag", what: "Old Repositories page", rec: "KILL", reason: "same as /knowledge/repositories", group: "forward", href: "/rag/repositories", note: null , target: "/knowledge/repositories", removes: null },
  { path: "/masterwork/[id]/drip", area: "masterwork / drip", what: "Daily Drip answer page", rec: "ASK", reason: "only a dialog (DailyDripDialog) exists in-app; route probably entered from a notification, confirm", group: "orphan", href: "/masterwork", note: "needs a record id" , target: null, removes: "Page and its answer form; texted links break" },
  { path: "/images/profile-photo", area: "media / images", what: "Profile photo tab", rec: "ASK", reason: "not in the images route list or menu; may duplicate /images/avatar", group: "orphan", href: "/images/profile-photo", note: null , target: null, removes: "Page only; the profile photo tab stays" },
  { path: "/_flash-cards", area: "more (games/old)", what: "old flash-card and SSR test pages from the pre-App-Router layout", rec: "KILL", reason: "underscore folder is private in Next, so these never route; dead files (keep only the _flash-cards/ai modals that components/flashcard-app imports)", group: "orphan", href: null, note: "never routes" , target: null, removes: "Dead files; keep its ai modals folder" },
  { path: "/_flashcard", area: "more (games/old)", what: "old flash-card and SSR test pages from the pre-App-Router layout", rec: "KILL", reason: "underscore folder is private in Next, so these never route; dead files (keep only the _flash-cards/ai modals that components/flashcard-app imports)", group: "orphan", href: null, note: "never routes" , target: null, removes: "Dead files only" },
  { path: "/_flashcard/[category]", area: "more (games/old)", what: "old flash-card and SSR test pages from the pre-App-Router layout", rec: "KILL", reason: "underscore folder is private in Next, so these never route; dead files (keep only the _flash-cards/ai modals that components/flashcard-app imports)", group: "orphan", href: null, note: "never routes" , target: null, removes: "Dead files only" },
  { path: "/_flashcard/[category]/[id]", area: "more (games/old)", what: "old flash-card and SSR test pages from the pre-App-Router layout", rec: "KILL", reason: "underscore folder is private in Next, so these never route; dead files (keep only the _flash-cards/ai modals that components/flashcard-app imports)", group: "orphan", href: null, note: "never routes" , target: null, removes: "Dead files only" },
  { path: "/podcast/studio/create-a", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-a", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-b", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-b", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-c", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-c", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-d", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-d", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-dense", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-dense", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/create-e", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-e", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-f", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-f", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-refine", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-refine", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-reimagine", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-reimagine", note: null , target: null, removes: "Page and its variant code in the podcasts feature" },
  { path: "/podcast/studio/create-sharp", area: "publish / podcasts", what: "Create-episode bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/create, which is the canonical page the menu uses", group: "orphan", href: "/podcast/studio/create-sharp", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-a", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-a", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-b", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-b", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-c", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-c", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-d", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-d", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-dense/[id]", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio", note: "needs a record id" , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-e", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-e", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-f", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio/run-f", note: null , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-refine/[id]", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio", note: "needs a record id" , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-reimagine/[id]", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio", note: "needs a record id" , target: null, removes: "Page and its own components folder" },
  { path: "/podcast/studio/run-sharp/[id]", area: "publish / podcasts", what: "Episode-run bake-off variant", rec: "KILL", reason: "design variant of /podcast/studio/run, linked only from sibling variants", group: "orphan", href: "/podcast/studio", note: "needs a record id" , target: null, removes: "Page and its own components folder" },
  { path: "/registered-results", area: "workflows / workflow-runtime", what: "Internal viewers for workflow-registered outputs (index, events, sitemap)", rec: "ASK", reason: "(transitional) internal viewers, untouched since 2026-06, no inbound links; likely superseded by workflow run views", group: "orphan", href: "/registered-results", note: null , target: null, removes: "Page only" },
  { path: "/registered-results/events-viewer", area: "workflows / workflow-runtime", what: "Internal viewers for workflow-registered outputs (index, events, sitemap)", rec: "ASK", reason: "(transitional) internal viewers, untouched since 2026-06, no inbound links; likely superseded by workflow run views", group: "orphan", href: "/registered-results/events-viewer", note: null , target: null, removes: "Page and its events viewer component" },
  { path: "/registered-results/sitemap-viewer", area: "workflows / workflow-runtime", what: "Internal viewers for workflow-registered outputs (index, events, sitemap)", rec: "ASK", reason: "(transitional) internal viewers, untouched since 2026-06, no inbound links; likely superseded by workflow run views", group: "orphan", href: "/registered-results/sitemap-viewer", note: null , target: null, removes: "Page and its sitemap viewer component" },
  { path: "/workflows/bakeoff", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: null , target: null, removes: "Picker page only" },
  { path: "/workflows/bakeoff/dense-2/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/dense/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/refine-2/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/refine/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/reimagine-2/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/reimagine/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/sharp-2/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/workflows/bakeoff/sharp/[id]", area: "workflows / workflow-runtime", what: "Workflow run console bake-off (picker and 8 design variants)", rec: "KILL", reason: "its own header says \"test scaffolding, not product\"; linked only from its own picker", group: "orphan", href: "/workflows/bakeoff", note: "needs a record id" , target: null, removes: "Page and its variant code in workflow runtime" },
  { path: "/detail", area: "workspace", what: "Detail primitive showcase (record opened as window, panel and page)", rec: "ASK", reason: "demo surface living in (core) by design; move to (dev) demos or link from Admin > UI", group: "orphan", href: "/detail", note: null , target: null, removes: "Page only; showcase stays in demos" },
  { path: "/administration/agents/system-agents/shortcuts/agents", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/administration/agents/system-agents/shortcuts/agents", note: null , target: null, removes: null },
  { path: "/administration/agents/system-agents/shortcuts/apps", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/administration/agents/system-agents/shortcuts/apps", note: null , target: null, removes: null },
  { path: "/administration/agents/system-agents/shortcuts/categories", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/administration/agents/system-agents/shortcuts/categories", note: null , target: null, removes: null },
  { path: "/administration/agents/system-agents/shortcuts/content-blocks", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/administration/agents/system-agents/shortcuts/content-blocks", note: null , target: null, removes: null },
  { path: "/administration/agents/system-agents/shortcuts/lineage", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/administration/agents/system-agents/shortcuts/lineage", note: null , target: null, removes: null },
  { path: "/administration/compute/server-logs", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to ", group: "forward", href: "/administration/compute/server-logs", note: null , target: null, removes: null },
  { path: "/administration/documentation/feature-docs", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /administration/documentation/feature-docs/codebase", group: "forward", href: "/administration/documentation/feature-docs", note: null , target: "/administration/documentation/feature-docs/codebase", removes: null },
  { path: "/administration/knowledge/podcasts", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /administration/knowledge/podcasts/shows", group: "forward", href: "/administration/knowledge/podcasts", note: null , target: "/administration/knowledge/podcasts/shows", removes: null },
  { path: "/administration/preview", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /administration/preview/unified-management", group: "forward", href: "/administration/preview", note: null , target: "/administration/preview/unified-management", removes: null },
  { path: "/agents/battle/open", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /agents/battle", group: "forward", href: "/agents/battle/open", note: null , target: "/agents/battle", removes: null },
  { path: "/agents/browse", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/agents/browse", note: null , target: null, removes: null },
  { path: "/chat", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /chat/new", group: "forward", href: "/chat", note: null , target: "/chat/new", removes: null },
  { path: "/chat/talk", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /chat/new", group: "forward", href: "/chat/talk", note: null , target: "/chat/new", removes: null },
  { path: "/education/fastfire/capture-test", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /administration/education/fastfire-capture-test", group: "forward", href: "/education/fastfire/capture-test", note: null , target: "/administration/education/fastfire-capture-test", removes: null },
  { path: "/education/flashcards-2", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/education/flashcards-2", note: null , target: null, removes: null },
  { path: "/education/flashcards/progress", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /education/progress", group: "forward", href: "/education/flashcards/progress", note: null , target: "/education/progress", removes: null },
  { path: "/files/[...path]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /files/all", group: "forward", href: "/files", note: "needs a record id" , target: "/files/all", removes: null },
  { path: "/knowledge/visualization", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/knowledge/visualization", note: null , target: null, removes: null },
  { path: "/mandates/id/[id]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to personMandateRecordHref(storedMandateKey(data.mandate_key", group: "forward", href: "/mandates", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/[brandId]/intelligence", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brandCompetitors(brandId", group: "forward", href: "/marketing", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/[brandId]/planning", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brandInitiatives(brandId", group: "forward", href: "/marketing", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/admin/keyword-data-quality", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.dataQuality(", group: "forward", href: "/marketing/admin/keyword-data-quality", note: null , target: null, removes: null },
  { path: "/marketing/ads", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/ads", note: null , target: null, removes: null },
  { path: "/marketing/ai-visibility", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/ai-visibility", note: null , target: null, removes: null },
  { path: "/marketing/approvals", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.approvals(", group: "forward", href: "/marketing/approvals", note: null , target: null, removes: null },
  { path: "/marketing/audience", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/audience", note: null , target: null, removes: null },
  { path: "/marketing/automations", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.automations(", group: "forward", href: "/marketing/automations", note: null , target: null, removes: null },
  { path: "/marketing/backlink-valuation", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/backlink-valuation", note: null , target: null, removes: null },
  { path: "/marketing/capabilities", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.siteCapabilities(address.brandSeg, address.siteSeg),", group: "forward", href: "/marketing/capabilities", note: null , target: null, removes: null },
  { path: "/marketing/competitors", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/competitors", note: null , target: null, removes: null },
  { path: "/marketing/connections/bing", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to marketingRoutes.connectionsBing(", group: "forward", href: "/marketing/connections/bing", note: null , target: null, removes: null },
  { path: "/marketing/connections/google/read-only", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to `${marketingRoutes.connectionsGoogle()}/read-only`", group: "forward", href: "/marketing/connections/google/read-only", note: null , target: null, removes: null },
  { path: "/marketing/connections", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.connections(", group: "forward", href: "/marketing/connections", note: null , target: null, removes: null },
  { path: "/marketing/content-plan/nodes/[nodeId]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to `${marketingRoutes.brandContentPlanSite(address.brandSeg, address.siteSeg)}?node", group: "forward", href: "/marketing/content-plan", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/content-plan", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/content-plan", note: null , target: null, removes: null },
  { path: "/marketing/content-studio", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/content-studio", note: null , target: null, removes: null },
  { path: "/marketing/cost", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.cost(", group: "forward", href: "/marketing/cost", note: null , target: null, removes: null },
  { path: "/marketing/discovery/youtube", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.youtubeDiscovery(", group: "forward", href: "/marketing/discovery/youtube", note: null , target: null, removes: null },
  { path: "/marketing/discovery/youtube/videos/[videoId]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to marketingRoutes.youtubeVideo(videoId", group: "forward", href: "/marketing/discovery/youtube", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/email", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/email", note: null , target: null, removes: null },
  { path: "/marketing/initiatives/[id]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/initiatives", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/initiatives", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/initiatives", note: null , target: null, removes: null },
  { path: "/marketing/keyword-intelligence", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/keyword-intelligence", note: null , target: null, removes: null },
  { path: "/marketing/keyword-research", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/keyword-research", note: null , target: null, removes: null },
  { path: "/marketing/local", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to location ? marketingRoutes.brandLocation(seg, location) : marketingRoutes.brandL", group: "forward", href: "/marketing/local", note: null , target: null, removes: null },
  { path: "/marketing/monitoring", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/monitoring", note: null , target: null, removes: null },
  { path: "/marketing/outreach", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/outreach", note: null , target: null, removes: null },
  { path: "/marketing/pr", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/pr", note: null , target: null, removes: null },
  { path: "/marketing/ranks", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.ranksRollup(", group: "forward", href: "/marketing/ranks", note: null , target: null, removes: null },
  { path: "/marketing/search-console", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.siteSearchConsole(address.brandSeg, address.siteSeg),", group: "forward", href: "/marketing/search-console", note: null , target: null, removes: null },
  { path: "/marketing/sites", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to /marketing/brands", group: "forward", href: "/marketing/sites", note: null , target: "/marketing/brands", removes: null },
  { path: "/marketing/social", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to marketingRoutes.brands(", group: "forward", href: "/marketing/social", note: null , target: null, removes: null },
  { path: "/organizations/[orgId]/projects/[projectId]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to `/projects/${projectId}`", group: "forward", href: "/organizations", note: "needs a record id" , target: "/projects/[projectId]", removes: null },
  { path: "/organizations/[orgId]/projects/[projectId]/settings", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/organizations", note: "needs a record id" , target: null, removes: null },
  { path: "/organizations/[orgId]/projects", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Linked in-app; goes to `/projects?org_filter=${orgId}`", group: "forward", href: "/organizations", note: "needs a record id" , target: "/projects?org_filter=[orgId]", removes: null },
  { path: "/rag/visualization", area: "redirect-only aliases", what: "Redirect-only alias", rec: "KILL", reason: "Old URL only; audit says worth killing pre-launch", group: "forward", href: "/rag/visualization", note: null , target: null, removes: null },
  { path: "/research/tags/[tagId]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to `/research/topics/${response.data.topic_id}/tags/${tagId}`", group: "forward", href: "/research", note: "needs a record id" , target: "/research/topics/[topicId]/tags/[tagId]", removes: null },
  { path: "/research/topics/[topicId]/documents", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to `/research/topics/${topicId}/document`", group: "forward", href: "/research/topics", note: "needs a record id" , target: "/research/topics/[topicId]/document", removes: null },
  { path: "/scopes/manage", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /scopes", group: "forward", href: "/scopes/manage", note: null , target: "/scopes", removes: null },
  { path: "/scraper/[id]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /scraper", group: "forward", href: "/scraper", note: "needs a record id" , target: "/scraper", removes: null },
  { path: "/settings/data", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to /trash", group: "forward", href: "/settings/data", note: null , target: "/trash", removes: null },
  { path: "/shapes/id/[id]", area: "redirect-only aliases", what: "Redirect-only alias", rec: "ALIAS", reason: "Old URL only; goes to shapeDetailHref(data.kind", group: "forward", href: "/shapes", note: "needs a record id" , target: null, removes: null },
  { path: "/notes", area: "empty shells", what: "Notes page that renders nothing", rec: "SHELL", reason: "The notes layout hosts the app; the page returns null", group: "lower", href: "/notes", note: null , target: null, removes: null },
  { path: "/notes/[id]", area: "empty shells", what: "Note page that renders nothing", rec: "SHELL", reason: "The notes layout hosts the app; the page returns null", group: "lower", href: "/notes", note: "needs a record id" , target: null, removes: null },
  { path: "/agents/new/studio", area: "empty shells", what: "Agent Studio placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/agents/new/studio", note: null , target: null, removes: null },
  { path: "/marketing/[brandId]/content/studio", area: "empty shells", what: "Content studio placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/marketing", note: "needs a record id" , target: null, removes: null },
  { path: "/marketing/[brandId]/socials", area: "empty shells", what: "Socials placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/marketing", note: "needs a record id" , target: null, removes: null },
  { path: "/agent-connections/hooks", area: "empty shells", what: "Hooks placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/agent-connections/hooks", note: null , target: null, removes: null },
  { path: "/agent-connections/sub-agents", area: "empty shells", what: "Sub-agents placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/agent-connections/sub-agents", note: null , target: null, removes: null },
  { path: "/hr/me/documents", area: "empty shells", what: "My documents placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/hr/me/documents", note: null , target: null, removes: null },
  { path: "/hr/me/schedule", area: "empty shells", what: "My schedule placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/hr/me/schedule", note: null , target: null, removes: null },
  { path: "/hr/me/training", area: "empty shells", what: "My training placeholder", rec: "SHELL", reason: "Coming-soon placeholder; the promise is tracked in the registry", group: "lower", href: "/hr/me/training", note: null , target: null, removes: null },
];
