import { withClaims } from "@/test-utils/supabase-auth";

const schema = jest.fn();
const getSession = jest.fn();
const requireUserId = jest.fn();
const listForSources = jest.fn();
const toastError = jest.fn();
const toastErrorAlreadyCaptured = jest.fn();

// `admitAutogeneratedFolder` asserts the initiating user through
// `getClaimsUser(supabase)` → `auth.getClaims()` BEFORE it creates the folder,
// so the fake needs that door or the RPC below is never reached.
jest.mock("@/utils/supabase/client", () => ({ supabase: { schema, auth: withClaims({ getSession }) } }));
jest.mock("@/utils/auth/getUserId", () => ({ requireUserId }));
jest.mock("@/features/scopes/service/associationsService", () => ({ associationsService: { listForSources } }));
jest.mock("@/lib/toast", () => ({
  toast: { error: (...a: unknown[]) => toastError(...a), dismiss: jest.fn(), success: jest.fn() },
  toastErrorAlreadyCaptured: (...a: unknown[]) => toastErrorAlreadyCaptured(...a),
  recordToast: { success: jest.fn(), error: jest.fn() },
}));
jest.mock("@/hooks/use-mobile", () => ({ useIsMobile: () => false }));
jest.mock("@/components/ui/dialog", () => ({
  Dialog: ({ children }: { children: React.ReactNode }) => <>{children}</>,
  DialogContent: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  DialogDescription: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  DialogFooter: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  DialogHeader: ({ children }: { children: React.ReactNode }) => <div>{children}</div>,
  DialogTitle: ({ children }: { children: React.ReactNode }) => <h1>{children}</h1>,
}));
jest.mock("@/components/ui/drawer", () => ({ Drawer: ({ children }: { children: React.ReactNode }) => <>{children}</>, DrawerContent: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DrawerDescription: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DrawerFooter: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DrawerHeader: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, DrawerTitle: ({ children }: { children: React.ReactNode }) => <h1>{children}</h1> }));
jest.mock("@/components/ui/button", () => ({ Button: ({ children, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) => <button {...props}>{children}</button> }));
jest.mock("@/components/ui/label", () => ({ Label: ({ children }: { children: React.ReactNode }) => <label>{children}</label> }));
jest.mock("@/components/ui/scroll-area", () => ({ ScrollArea: ({ children }: { children: React.ReactNode }) => <div>{children}</div> }));
jest.mock("@ai-matrx/design-system", () => ({ Input: (props: React.InputHTMLAttributes<HTMLInputElement>) => <input {...props} /> }));

import { configureStore } from "@reduxjs/toolkit";
import { enableMapSet } from "immer";
import { Provider } from "react-redux";
import { act } from "react";
import { createRoot } from "react-dom/client";
import notesReducer from "../redux/slice";
import appContextReducer, { makeAppContextState } from "@/lib/redux/slices/appContextSlice";
import { FolderQuickPick } from "./FolderQuickPick";
import { NOTE_FOLDER_CROSS_ORG_MESSAGE } from "../utils/writeErrors";
import type { UserAuthState } from "@/lib/redux/slices/userAuthSlice";

enableMapSet();
(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT: boolean }).IS_REACT_ACT_ENVIRONMENT = true;

const ORG_A = "11111111-1111-4111-8111-111111111111";
const ORG_B = "22222222-2222-4222-8222-222222222222";
const USER = "33333333-3333-4333-833333333333";

function chain(result: unknown) {
  const value = { select: jest.fn(), eq: jest.fn(), is: jest.fn(), upsert: jest.fn(), insert: jest.fn(), maybeSingle: jest.fn(), single: jest.fn() };
  for (const method of ["select", "eq", "is", "upsert", "insert"] as const) value[method].mockReturnValue(value);
  value.maybeSingle.mockResolvedValue(result);
  value.single.mockResolvedValue(result);
  return value;
}

function store() {
  const userAuth = (state: Pick<UserAuthState, "id"> = { id: USER }) => state;
  return configureStore({
    reducer: { notes: notesReducer, appContext: appContextReducer, userAuth },
    preloadedState: { appContext: makeAppContextState({ organization_id: ORG_A, orgBootstrapResolved: true }) },
    middleware: (defaults) => defaults({ serializableCheck: false }),
  });
}

describe("FolderQuickPick legacy cross-org folder collision", () => {
  beforeEach(() => {
    jest.clearAllMocks();
    requireUserId.mockReturnValue(USER);
    getSession.mockResolvedValue({ data: { session: { user: { id: USER } } }, error: null });
    listForSources.mockResolvedValue({ ok: true, data: { edges: [] } });
  });

  it("keeps typed input, says a sentence and raises a toast when the database refuses a legacy org-B collision", async () => {
    // The refusal the DATABASE raises while the retired org-blind key is live
    // (workbench.note_folder_get_or_create) — the exact code and text, as
    // PostgREST hands it to the client.
    const rpc = jest.fn().mockResolvedValue({
      data: null,
      error: {
        code: "23505",
        message: "notes_folder_cross_org_legacy_key: this person already owns a folder with this name in another organization, and the retired (created_by, name) key is still live.",
      },
    });
    schema.mockReturnValue({ rpc, from: jest.fn(() => chain({ data: null, error: null })) });
    const configured = store();
    const host = document.createElement("div");
    const root = createRoot(host);
    await act(async () => { root.render(<Provider store={configured}><FolderQuickPick instanceId="collision" /></Provider>); });
    const open = [...host.querySelectorAll("button")].find((button) => button.title === "Create a new folder");
    await act(async () => { open?.dispatchEvent(new MouseEvent("click", { bubbles: true })); });
    const input = host.querySelector("input") as HTMLInputElement;
    await act(async () => {
      Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, "value")?.set?.call(input, "Reserved name");
      input.dispatchEvent(new Event("input", { bubbles: true }));
      input.dispatchEvent(new Event("change", { bubbles: true }));
    });
    await act(async () => {
      (host.querySelector("form") as HTMLFormElement).requestSubmit();
      await new Promise((resolve) => setTimeout(resolve, 0));
    });
    expect(configured.getState().notes.notes).toEqual({});
    expect(rpc).toHaveBeenCalledWith("note_folder_get_or_create", { p_organization_id: ORG_A, p_name: "Reserved name" });
    // The person reads a sentence, never the database's code …
    expect(host.textContent).toContain(NOTE_FOLDER_CROSS_ORG_MESSAGE);
    expect(host.textContent).not.toContain("notes_folder_cross_org_legacy_key");
    // … and the failure is ANNOUNCED by the shared boundary, not left to the surface.
    const announced = [...toastError.mock.calls, ...toastErrorAlreadyCaptured.mock.calls].map((c) => c[0]);
    expect(announced).toContain(NOTE_FOLDER_CROSS_ORG_MESSAGE);
    expect(input.value).toBe("Reserved name");
    expect((host.querySelector('button[type="submit"]') as HTMLButtonElement).disabled).toBe(false);
    await act(async () => { root.unmount(); });
  });
});
