"use client";

// Layer 6: NotesView — Instance wrapper.
// Registers a unique notes instance on mount, cleans up on unmount.
// Renders sidebar + tab bar + active note editor.
// Can be used as full page, floating window, or single-note embed.
// ZERO PROP DRILLING — each child receives only an instanceId or noteId.

import React, {
  useEffect,
  useRef,
  useCallback,
  useState,
  useMemo,
  useId,
} from "react";
import dynamic from "next/dynamic";
import {
  FileText,
  SplitSquareHorizontal,
  PilcrowRight,
  Columns,
  Eye,
  X,
} from "lucide-react";
import {
  usePanelRef,
  type Layout,
  type OnPanelResize,
} from "react-resizable-panels";
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { ensureScopeTree } from "@/features/scopes/redux/thunks/ensureScopeTree";
import { useParams, useSearchParams } from "next/navigation";
import { useIsMobile } from "@/hooks/use-mobile";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";
import {
  PanelLeftTapButton,
  HistoryTapButton,
  RetryTapButton,
  LoadingTapButton,
} from "@/components/icons/tap-buttons";
import { TapTargetButtonGroup } from "@/components/icons/TapTargetButton";
import PageHeaderRightPortal from "@/features/shell/components/header/PageHeaderRightPortal";
import {
  normalizeNoteEditorMode,
  usePreferredDefaultEditorMode,
  NOTES_SPLIT_MIN_WIDTH_PX,
} from "../hooks/usePreferredDefaultEditorMode";
import { useMediaQuery } from "@/hooks/use-media-query";

const MobileNotesView = dynamic(() => import("./mobile/MobileNotesView"), {
  ssr: false,
});

const NoteVersionHistory = dynamic(
  () =>
    import("@/features/notes/components/NoteVersionHistory").then((mod) => ({
      default: mod.NoteVersionHistory,
    })),
  { ssr: false },
);
import {
  registerInstance,
  unregisterInstance,
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  reorderInstanceTabs,
  createAutogeneratedNote,
  setNoteEditorMode,
  openFindReplace,
  navigateFindMatch,
  closeSplit,
  markTabInteraction,
} from "../redux/slice";
import { orderTabsActiveFirst } from "../utils/tabUrlOrder";
import {
  fetchNotesList,
  fetchSharedNotesList,
  fetchNoteContent,
  refreshNoteContent,
  saveNote,
} from "../redux/thunks";
import { selectOrganizationId } from "@/lib/redux/slices/appContextSlice";
import {
  selectInstanceActiveTab,
  selectInstanceTabs,
  selectInstanceSplitNoteId,
  selectNoteEditorMode,
  selectNoteLabel,
} from "../redux/selectors";
import PageHeader from "@/features/shell/components/header/PageHeader";
import { NotesInstanceProvider } from "../context/NotesInstanceContext";
import { NotePresenceBanner } from "./NotePresenceBanner";
import { NoteContentEditor } from "./NoteContentEditor";
import { NoteCleanupButton } from "./cleanup/NoteCleanupButton";
import { NoteMetadataBar } from "./NoteMetadataBar";
import { NoteStatsFooter } from "./NoteStatsFooter";
import { NoteTabBar } from "./NoteTabBar";
import { NoteSidebar } from "./NoteSidebar";
import { FolderQuickPick } from "./FolderQuickPick";
import { cn } from "@/lib/utils";

export interface NotesViewConfig {
  /** Show the sidebar with folder tree (default: true) */
  showSidebar?: boolean;
  /** Show the tab bar (default: true) */
  showTabs?: boolean;
  /** Lock to a single note — no tabs, no sidebar (default: null) */
  singleNote?: string | null;
  /** Custom instance ID (default: auto-generated) */
  instanceId?: string;
  /** Tabs to restore from DB session (skips URL hydration for these) */
  initialTabs?: string[];
  /** Active tab to restore from DB session */
  initialActiveTab?: string | null;
  /**
   * Skip shell PageHeader / right portal (Utilities overlay, embeds).
   * Renders the same chrome as an inline toolbar instead.
   */
  hidePageHeader?: boolean;
  /**
   * When false, NoteTabBar won't read/write `?tabs=` URL params.
   * Default true on the /notes route; overlays/windows should pass false.
   */
  syncUrl?: boolean;
}

export interface NotesViewProps {
  config?: NotesViewConfig;
  className?: string;
  /** Persisted sidebar/main split (percentages), read from the cookie by the
   *  server layout so the first paint matches — see app/(core)/notes/layout.tsx. */
  sidebarLayout?: Layout;
}

export function NotesView({
  config,
  className,
  sidebarLayout,
}: NotesViewProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);
  const isMobile = useIsMobile();

  const showSidebar = config?.showSidebar ?? true;
  const showTabs = config?.showTabs ?? true;
  const hidePageHeader = config?.hidePageHeader ?? false;
  const syncUrl = config?.syncUrl ?? !hidePageHeader;
  const [showHistory, setShowHistory] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const singleNote = config?.singleNote ?? null;

  // ── Resizable + collapsible left sidebar (react-resizable-panels v4) ──
  // The library owns the size; we mirror only the collapsed BOOLEAN for the
  // toggle icon, and persist the split to a cookie the server layout reads.
  const sidebarPanelRef = usePanelRef();
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);

  const toggleSidebar = () => {
    const panel = sidebarPanelRef.current;
    if (!panel) return;
    if (panel.isCollapsed()) panel.expand();
    else panel.collapse();
  };

  const trackSidebarCollapse: OnPanelResize = (next, _id, prev) => {
    if (prev === undefined) return;
    const wasCollapsed = prev.asPercentage === 0;
    const isCollapsed = next.asPercentage === 0;
    if (wasCollapsed !== isCollapsed) setSidebarCollapsed(isCollapsed);
  };

  const persistShellLayout = (layout: Layout) => {
    document.cookie =
      `panels:notes-shell=${encodeURIComponent(JSON.stringify(layout))}` +
      `; path=/; max-age=31536000; SameSite=Lax`;
  };

  // ── URL param hydration: read ?tabs= and ?active= on mount ────────
  const searchParams = useSearchParams();
  const urlTabs = useMemo(
    () => searchParams.get("tabs")?.split(",").filter(Boolean) ?? [],
    [searchParams],
  );
  const urlActive = searchParams.get("active");

  // ── Route param: /notes/[id] deep-link ─────────────────────────────
  // Works from any descendant of the /notes layout — when the URL is
  // /notes/abc (or /notes/abc/diff) this returns { id: "abc" }, otherwise {}.
  const routeParams = useParams<{ id?: string | string[] }>();
  const routeNoteId =
    typeof routeParams?.id === "string" ? routeParams.id : null;

  // Config props win over URL params. When syncUrl is false (overlays /
  // embeds), never hydrate from the page's ?tabs= — that would steal the
  // /notes workspace into Quick Notes / Utilities.
  const initialTabs =
    config?.initialTabs ??
    (syncUrl
      ? urlTabs.length > 0
        ? urlTabs
        : routeNoteId
          ? [routeNoteId]
          : undefined
      : undefined);
  const initialActiveTab =
    config?.initialActiveTab ??
    (syncUrl ? (urlActive ?? routeNoteId) : undefined);

  // ── Generate or use provided instance ID ──────────────────────────
  const generatedInstanceId = useId();
  const instanceId =
    config?.instanceId ?? `notes-${generatedInstanceId.replaceAll(":", "")}`;

  // ── Register instance on mount, unregister on unmount ─────────────
  useEffect(() => {
    dispatch(registerInstance(instanceId));
    return () => {
      dispatch(unregisterInstance(instanceId));
    };
  }, [dispatch, instanceId]);

  // ── Restore tabs from config props, URL params, or DB session ──────
  // `?active=` wins over the /notes/[id] path segment. Tabs are stored
  // active-first so reload + shareable URLs keep the focused note.
  const restoredFromDbRef = useRef(false);
  useEffect(() => {
    if (restoredFromDbRef.current) return;
    if (!initialTabs || initialTabs.length === 0) return;
    restoredFromDbRef.current = true;

    const activeId =
      initialActiveTab && initialTabs.includes(initialActiveTab)
        ? initialActiveTab
        : initialTabs[0];
    const ordered = orderTabsActiveFirst(initialTabs, activeId);

    ordered.forEach((noteId) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    });
    dispatch(reorderInstanceTabs({ instanceId, tabs: ordered }));
    dispatch(setInstanceActiveTab({ instanceId, noteId: activeId }));
    // Only run once on mount — initialTabs/initialActiveTab are stable.
  }, [dispatch, instanceId]);

  // ── Fetch notes list + scope data on mount ──────────────────────────
  const orgId = useAppSelector(selectOrganizationId);
  const fetchedRef = useRef(false);
  useEffect(() => {
    if (!fetchedRef.current && userId) {
      fetchedRef.current = true;
      dispatch(fetchNotesList());
      dispatch(fetchSharedNotesList());
    }
  }, [dispatch, userId]);

  // Share grants/revokes live in iam.permissions — refresh the shared list
  // when the tab becomes visible so revoked notes leave the sidebar.
  // Min-interval gated: `focus` + `visibilitychange` both fire on every tab
  // switch, and each refetch is a full-list hydration — unthrottled, rapid
  // alt-tabbing (or a user returning to an already-struggling tab) re-fired
  // the storm and made the 2026-07 freeze look unrecoverable.
  const lastSharedRefreshRef = useRef(0);
  useEffect(() => {
    if (!userId) return undefined;
    const MIN_REFRESH_INTERVAL_MS = 30_000;
    const onVisible = () => {
      if (document.visibilityState !== "visible") return;
      const now = Date.now();
      if (now - lastSharedRefreshRef.current < MIN_REFRESH_INTERVAL_MS) return;
      lastSharedRefreshRef.current = now;
      void dispatch(fetchSharedNotesList());
    };
    document.addEventListener("visibilitychange", onVisible);
    window.addEventListener("focus", onVisible);
    return () => {
      document.removeEventListener("visibilitychange", onVisible);
      window.removeEventListener("focus", onVisible);
    };
  }, [dispatch, userId]);

  useEffect(() => {
    if (fetchedRef.current && orgId) {
      // Ensure the canonical scope tree is loaded so the new scope pickers
      // (EntityScopeTagger / EntityTargetPicker) and the active-context
      // surface have data. No-op if already `ready` (no refetch policy).
      dispatch(ensureScopeTree());
    }
  }, [dispatch, orgId]);

  // ── Single note mode: set active immediately ──────────────────────
  useEffect(() => {
    if (singleNote) {
      dispatch(addInstanceTab({ instanceId, noteId: singleNote }));
      dispatch(setInstanceActiveTab({ instanceId, noteId: singleNote }));
      dispatch(fetchNoteContent(singleNote));
    }
  }, [dispatch, instanceId, singleNote]);

  // ── Route-param deep link (/notes/[id]) ────────────────────────────
  // Ensure the path id is open as a tab. Do NOT steal focus from `?active=`
  // on first paint — that was wiping the focused tab on every reload.
  // Client-side navigations that change [id] still make the new path active.
  //
  // `urlActive` is read via ref, NOT a dep: NoteTabBar rewrites `?active=`
  // via history.replaceState on every tab action, which Next syncs back into
  // useSearchParams. With urlActive in the deps this effect re-ran per tab
  // action, re-adding the route note's tab after the user closed it and
  // re-dispatching a fetch — a per-action dispatch cascade (2026-07 freeze
  // class amplifier).
  const urlActiveRef = useRef(urlActive);
  useEffect(() => {
    urlActiveRef.current = urlActive;
  }, [urlActive]);
  const prevRouteNoteIdRef = useRef<string | null | undefined>(undefined);
  useEffect(() => {
    if (!syncUrl || singleNote || !routeNoteId) return;

    const prev = prevRouteNoteIdRef.current;
    if (prev === routeNoteId) return;
    prevRouteNoteIdRef.current = routeNoteId;

    dispatch(addInstanceTab({ instanceId, noteId: routeNoteId }));
    dispatch(fetchNoteContent(routeNoteId));

    // First mount: only activate the path id when there is no ?active=
    if (prev === undefined) {
      if (!urlActiveRef.current) {
        dispatch(setInstanceActiveTab({ instanceId, noteId: routeNoteId }));
      }
      return;
    }

    // Client-side /notes/A → /notes/B: path is the intentional focus change
    dispatch(setInstanceActiveTab({ instanceId, noteId: routeNoteId }));
  }, [dispatch, instanceId, routeNoteId, singleNote, syncUrl]);

  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const openTabs = useAppSelector(selectInstanceTabs(instanceId));
  const splitNoteId = useAppSelector(selectInstanceSplitNoteId(instanceId));
  const splitNoteLabel = useAppSelector(
    splitNoteId ? selectNoteLabel(splitNoteId) : () => null,
  );
  const preferredDefaultMode = usePreferredDefaultEditorMode();
  const isNarrowViewport = useMediaQuery(
    `(max-width: ${NOTES_SPLIT_MIN_WIDTH_PX - 1}px)`,
  );
  const canShowWideModes = !isNarrowViewport;
  const editorMode = normalizeNoteEditorMode(
    useAppSelector(
      activeTabId ? selectNoteEditorMode(activeTabId) : () => undefined,
    ),
    preferredDefaultMode,
  );

  const setMode = useCallback(
    (mode: string) => {
      if (activeTabId) dispatch(setNoteEditorMode({ id: activeTabId, mode }));
    },
    [dispatch, activeTabId],
  );

  // ── Refresh: refetch list + force-refetch every open tab ──────────
  // Mirrors the route-start fetches so the user can pull the latest server
  // state on demand (e.g. after editing on another device).
  const handleRefresh = useCallback(async () => {
    if (isRefreshing) return;
    setIsRefreshing(true);
    try {
      const work: Promise<unknown>[] = [
        dispatch(fetchNotesList()).unwrap(),
        dispatch(fetchSharedNotesList()).unwrap(),
      ];
      if (orgId) {
        // Explicit user refresh → force-refresh the canonical scope tree.
        work.push(dispatch(ensureScopeTree({ refresh: true })));
      }
      for (const noteId of openTabs ?? []) {
        work.push(dispatch(refreshNoteContent(noteId)).unwrap());
      }
      await Promise.allSettled(work);
    } finally {
      setIsRefreshing(false);
    }
  }, [dispatch, isRefreshing, openTabs, orgId]);

  // ── Keyboard shortcuts ───────────────────────────────────────────
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const mod = e.ctrlKey || e.metaKey;

      // Ctrl+S — save active note
      if (mod && e.key === "s") {
        e.preventDefault();
        if (activeTabId) dispatch(saveNote(activeTabId));
        return;
      }

      // Ctrl+W — close active tab
      if (mod && e.key === "w") {
        e.preventDefault();
        if (activeTabId) {
          dispatch(markTabInteraction({ instanceId }));
          dispatch(removeInstanceTab({ instanceId, noteId: activeTabId }));
        }
        return;
      }

      // Ctrl+F — open find bar (and re-focus + select-all if already open).
      // We explicitly exclude Shift here so the Ctrl+Shift+F handler below
      // owns the "global search" shortcut and the two cannot double-fire.
      // `e.key` honours CapsLock (caps→"F"), so normalize before comparing.
      const keyLower = e.key.length === 1 ? e.key.toLowerCase() : e.key;
      if (mod && !e.altKey && !e.shiftKey && keyLower === "f") {
        e.preventDefault();
        // Standard behavior: if there's a non-empty selection in the
        // currently-focused textarea/input, seed the find query with it.
        // We only pull single-line selections; multi-line selections are
        // usually unintentional for a find query, so we ignore them.
        const active = document.activeElement;
        let prefillQuery: string | undefined;
        if (
          active instanceof HTMLTextAreaElement ||
          active instanceof HTMLInputElement
        ) {
          const { selectionStart, selectionEnd, value } = active;
          if (
            selectionStart != null &&
            selectionEnd != null &&
            selectionEnd > selectionStart
          ) {
            const selected = value.slice(selectionStart, selectionEnd);
            if (selected.length > 0 && !selected.includes("\n")) {
              prefillQuery = selected;
            }
          }
        }
        dispatch(
          openFindReplace({ instanceId, showReplace: false, prefillQuery }),
        );
        return;
      }

      // Ctrl+Shift+F / Cmd+Shift+F — open find in GLOBAL scope. Mirrors
      // VS Code's "Search across files". We also flip the advanced rows on
      // (include/exclude inputs) inside `openFindReplace` when scope=global.
      if (mod && e.shiftKey && !e.altKey && keyLower === "f") {
        e.preventDefault();
        const active = document.activeElement;
        let prefillQuery: string | undefined;
        if (
          active instanceof HTMLTextAreaElement ||
          active instanceof HTMLInputElement
        ) {
          const { selectionStart, selectionEnd, value } = active;
          if (
            selectionStart != null &&
            selectionEnd != null &&
            selectionEnd > selectionStart
          ) {
            const selected = value.slice(selectionStart, selectionEnd);
            if (selected.length > 0 && !selected.includes("\n")) {
              prefillQuery = selected;
            }
          }
        }
        dispatch(
          openFindReplace({
            instanceId,
            showReplace: false,
            scope: "global",
            prefillQuery,
          }),
        );
        return;
      }

      // Ctrl+H (Win/Linux) or Cmd+Option+F (Mac) — open find+replace
      if (
        (e.ctrlKey && !e.metaKey && e.key === "h") ||
        (e.metaKey && e.altKey && e.key === "f")
      ) {
        e.preventDefault();
        dispatch(openFindReplace({ instanceId, showReplace: true }));
        return;
      }

      // F3 / Cmd+G — next match. Shift+F3 / Cmd+Shift+G — previous.
      // Standard "find again" shortcuts across browsers, VS Code, and macOS.
      if (e.key === "F3" || (e.metaKey && !e.ctrlKey && e.key === "g")) {
        e.preventDefault();
        dispatch(
          navigateFindMatch({
            instanceId,
            direction: e.shiftKey ? "prev" : "next",
          }),
        );
        return;
      }

      // Ctrl+Tab — cycle to next tab
      if (mod && e.key === "Tab") {
        e.preventDefault();
        if (openTabs && openTabs.length > 1 && activeTabId) {
          const idx = openTabs.indexOf(activeTabId);
          const next = openTabs[(idx + 1) % openTabs.length];
          dispatch(markTabInteraction({ instanceId }));
          dispatch(setInstanceActiveTab({ instanceId, noteId: next }));
          dispatch(fetchNoteContent(next));
        }
        return;
      }
    };

    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [dispatch, instanceId, activeTabId, openTabs]);

  const modeBtnClass = (mode: string) =>
    cn(
      "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer",
      "[&_svg]:w-3.5 [&_svg]:h-3.5",
      editorMode === mode
        ? "bg-[var(--matrx-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
        : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
    );

  // Main editor column — shared by the sidebar-shown (resizable panel) and the
  // sidebar-hidden (full-width) layouts. h-full/w-full so it fills either one.
  const mainArea = (
    <div className="flex h-full w-full min-w-0 min-h-0">
      <div className="flex-1 flex flex-col min-w-0 min-h-0">
        {/* Layer 4: Tab bar (top) */}
        {showTabs && !singleNote && (
          <NoteTabBar instanceId={instanceId} syncUrl={syncUrl} />
        )}

        {/* Presence indicator (shared with the window view) */}
        <NotePresenceBanner instanceId={instanceId} />

        {/* Layer 1: Content editor (fills available space) */}
        {activeTabId ? (
          splitNoteId ? (
            /* ── Split view: two editors side-by-side ─────────── */
            <div className="flex-1 flex min-h-0">
              <div className="flex-1 flex flex-col min-w-0 min-h-0">
                <NoteContentEditor noteId={activeTabId} />
              </div>
              <div className="w-px bg-border shrink-0" />
              <div className="flex-1 flex flex-col min-w-0 min-h-0">
                <div className="flex items-center justify-between px-2 py-0.5 border-b border-border bg-muted/30 shrink-0">
                  <span className="text-[0.625rem] font-medium truncate text-muted-foreground">
                    {splitNoteLabel ?? "Split Note"}
                  </span>
                  <button
                    onClick={() => dispatch(closeSplit(instanceId))}
                    className="flex items-center justify-center w-4 h-4 rounded-sm text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
                    title="Close split"
                  >
                    <X className="w-3 h-3" />
                  </button>
                </div>
                <NoteContentEditor noteId={splitNoteId} />
              </div>
            </div>
          ) : (
            <NoteContentEditor noteId={activeTabId} />
          )
        ) : (
          <FolderQuickPick instanceId={instanceId} />
        )}

        {/* Layer 2: chrome (folder/context/tags) + stats footer (metrics only) */}
        {activeTabId && (
          <>
            <NoteMetadataBar noteId={activeTabId} />
            <NoteStatsFooter noteId={activeTabId} standalone />
          </>
        )}
      </div>
    </div>
  );

  // ── Render ─────────────────────────────────────────────────────────
  const headerChrome = (
    <div className="flex w-full min-w-0 items-center gap-0">
      {/* Left — sidebar toggle (shell owns far-left hamburger) */}
      {showSidebar && !singleNote ? (
        <PanelLeftTapButton
          variant="transparent"
          onClick={toggleSidebar}
          ariaLabel={sidebarCollapsed ? "Show sidebar" : "Hide sidebar"}
          tooltip={sidebarCollapsed ? "Show sidebar" : "Hide sidebar"}
        />
      ) : (
        <div className="w-9 shrink-0" aria-hidden />
      )}

      {/* Center — view / style modes only */}
      <div className="flex min-w-0 flex-1 items-center justify-center">
        {activeTabId && (
          <div className="matrx-glass-thin-border flex items-center gap-0.5 rounded-full p-0.5">
            <button
              type="button"
              className={modeBtnClass("plain")}
              onClick={() => setMode("plain")}
            >
              <FileText /> Edit
            </button>
            {canShowWideModes && (
              <>
                <button
                  type="button"
                  className={modeBtnClass("split")}
                  onClick={() => setMode("split")}
                >
                  <SplitSquareHorizontal /> Split
                </button>
                <button
                  type="button"
                  className={modeBtnClass("wysiwyg")}
                  onClick={() => setMode("wysiwyg")}
                >
                  <PilcrowRight /> Rich
                </button>
                <button
                  type="button"
                  className={modeBtnClass("markdown-split")}
                  onClick={() => setMode("markdown-split")}
                >
                  <Columns /> MD Split
                </button>
              </>
            )}
            <button
              type="button"
              className={modeBtnClass("preview")}
              onClick={() => setMode("preview")}
            >
              <Eye /> Preview
            </button>
          </div>
        )}
      </div>

      {hidePageHeader ? (
        <TapTargetButtonGroup className="shrink-0 pr-1">
          {activeTabId && (
            <>
              <HistoryTapButton
                variant="group"
                onClick={() => setShowHistory((v) => !v)}
                ariaLabel="Versions"
                tooltip="Version history"
                className={showHistory ? "text-primary" : undefined}
              />
              <NoteCleanupButton noteId={activeTabId} asTapGroup />
            </>
          )}
          {isRefreshing ? (
            <LoadingTapButton
              variant="group"
              disabled
              ariaLabel="Refreshing…"
            />
          ) : (
            <RetryTapButton
              variant="group"
              onClick={handleRefresh}
              ariaLabel="Refresh notes"
              tooltip="Refresh notes list and open tabs"
            />
          )}
        </TapTargetButtonGroup>
      ) : (
        <div className="w-9 shrink-0" aria-hidden />
      )}
    </div>
  );

  return (
    <NotesInstanceProvider value={instanceId}>
      {isMobile ? (
        // Deep link to /notes/[id] (e.g. a shared link opened on a phone)
        // must land straight in the editor, matching desktop — the mobile
        // view manages its own list/editor state independent of the tab
        // redux the desktop split uses, so it needs the route id explicitly.
        <MobileNotesView singleNoteId={singleNote ?? routeNoteId} />
      ) : (
        <div
          className={
            hidePageHeader
              ? `flex h-full w-full min-h-0 flex-col ${className ?? ""}`
              : `flex h-full w-full min-h-0 ${className ?? ""}`
          }
        >
          {hidePageHeader ? (
            <div className="flex h-10 shrink-0 items-center border-b border-border/40 px-1">
              {headerChrome}
            </div>
          ) : (
            <>
              <PageHeader>{headerChrome}</PageHeader>
              <PageHeaderRightPortal>
                <TapTargetButtonGroup>
                  {activeTabId && (
                    <>
                      <HistoryTapButton
                        variant="group"
                        onClick={() => setShowHistory((v) => !v)}
                        ariaLabel="Versions"
                        tooltip="Version history"
                        className={showHistory ? "text-primary" : undefined}
                      />
                      <NoteCleanupButton noteId={activeTabId} asTapGroup />
                    </>
                  )}
                  {isRefreshing ? (
                    <LoadingTapButton
                      variant="group"
                      disabled
                      ariaLabel="Refreshing…"
                    />
                  ) : (
                    <RetryTapButton
                      variant="group"
                      onClick={handleRefresh}
                      ariaLabel="Refresh notes"
                      tooltip="Refresh notes list and open tabs"
                    />
                  )}
                </TapTargetButtonGroup>
              </PageHeaderRightPortal>
            </>
          )}

          {/* Layer 4/5: collapsible + resizable sidebar | main editor column.
              react-resizable-panels v4 owns the size; cookie persists the split
              (read server-side in app/(core)/notes/layout.tsx for a flash-free
              first paint). Sidebar hidden (singleNote / showSidebar=false) →
              just the main area, no group. */}
          {showSidebar && !singleNote ? (
            <ResizablePanelGroup
              id="notes-shell"
              orientation="horizontal"
              defaultLayout={sidebarLayout}
              onLayoutChanged={persistShellLayout}
              className="min-h-0 flex-1"
            >
              <ResizablePanel
                id="notes-sidebar"
                panelRef={sidebarPanelRef}
                collapsible
                collapsedSize={0}
                defaultSize="220px"
                minSize="180px"
                maxSize="42%"
                onResize={trackSidebarCollapse}
                style={{ overflow: "hidden", height: "100%" }}
              >
                <div className="flex h-full flex-col min-h-0 border-r border-border">
                  <NoteSidebar instanceId={instanceId} />
                </div>
              </ResizablePanel>
              <ResizableHandle
                withHandle
                disabled={sidebarCollapsed}
                className={cn(
                  sidebarCollapsed && "pointer-events-none opacity-0",
                )}
              />
              <ResizablePanel
                id="notes-main"
                minSize="40%"
                style={{ overflow: "hidden", height: "100%" }}
              >
                {mainArea}
              </ResizablePanel>
            </ResizablePanelGroup>
          ) : (
            mainArea
          )}

          {/* Version history — resizable MatrxDynamic panel (desktop) / Drawer (mobile) */}
          {activeTabId && (
            <NoteVersionHistory
              noteId={activeTabId}
              open={showHistory}
              onOpenChange={setShowHistory}
              onVersionRestored={() => {
                dispatch(fetchNoteContent(activeTabId));
              }}
            />
          )}
        </div>
      )}
    </NotesInstanceProvider>
  );
}
