"use client";

// Layer 6: NotesView — Instance wrapper.
// Registers a unique notes instance on mount, cleans up on unmount.
// Renders sidebar + tab bar + active note editor.
// Can be used as full page, floating window, or single-note embed.
// ZERO PROP DRILLING — each child receives only an instanceId or noteId.

import React, {
  useEffect,
  useRef,
  useCallback,
  useState,
  useMemo,
} from "react";
import dynamic from "next/dynamic";
import {
  FileText,
  SplitSquareHorizontal,
  PilcrowRight,
  Columns,
  Eye,
  History,
  RefreshCw,
  X,
} from "lucide-react";
import { ensureScopeTree } from "@/features/scopes/redux/thunks/ensureScopeTree";
import { useParams, useSearchParams } from "next/navigation";
import { useIsMobile } from "@/hooks/use-mobile";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUser } from "@/lib/redux/slices/userSlice";

const MobileNotesView = dynamic(() => import("./mobile/MobileNotesView"), {
  ssr: false,
});

const NoteVersionHistory = dynamic(
  () =>
    import("@/features/notes/components/NoteVersionHistory").then((mod) => ({
      default: mod.NoteVersionHistory,
    })),
  { ssr: false },
);
import {
  registerInstance,
  unregisterInstance,
  setInstanceActiveTab,
  addInstanceTab,
  removeInstanceTab,
  createAutogeneratedNote,
  setNoteEditorMode,
  openFindReplace,
  navigateFindMatch,
  closeSplit,
  markTabInteraction,
} from "../redux/slice";
import {
  fetchNotesList,
  fetchNoteContent,
  refreshNoteContent,
  saveNote,
} from "../redux/thunks";
import { selectOrganizationId } from "@/lib/redux/slices/appContextSlice";
import {
  selectOtherUsersActive,
  selectActiveNoteEditedByOthers,
  selectInstanceActiveTab,
  selectInstanceTabs,
  selectInstanceSplitNoteId,
  selectNoteEditorMode,
  selectNoteLabel,
} from "../redux/selectors";
import PageHeader from "@/features/shell/components/header/PageHeader";
import { RichDocumentActionSurface } from "@/features/rich-document/RichDocumentActionSurface";
import { NoteReferenceCopyButton } from "./NoteReferenceCopyButton";
import { NotesInstanceProvider } from "../context/NotesInstanceContext";
import { NoteContentEditor } from "./NoteContentEditor";
import { NoteMetadataBar } from "./NoteMetadataBar";
import { NoteTabBar } from "./NoteTabBar";
import { NoteSidebar } from "./NoteSidebar";
import { FolderQuickPick } from "./FolderQuickPick";
import { cn } from "@/lib/utils";

export interface NotesViewConfig {
  /** Show the sidebar with folder tree (default: true) */
  showSidebar?: boolean;
  /** Show the tab bar (default: true) */
  showTabs?: boolean;
  /** Lock to a single note — no tabs, no sidebar (default: null) */
  singleNote?: string | null;
  /** Custom instance ID (default: auto-generated) */
  instanceId?: string;
  /** Tabs to restore from DB session (skips URL hydration for these) */
  initialTabs?: string[];
  /** Active tab to restore from DB session */
  initialActiveTab?: string | null;
}

export interface NotesViewProps {
  config?: NotesViewConfig;
  className?: string;
}

export function NotesView({ config, className }: NotesViewProps) {
  const dispatch = useAppDispatch();
  const { id: userId } = useAppSelector(selectUser);
  const isMobile = useIsMobile();

  const showSidebar = config?.showSidebar ?? true;
  const showTabs = config?.showTabs ?? true;
  const [showHistory, setShowHistory] = useState(false);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const singleNote = config?.singleNote ?? null;

  // ── URL param hydration: read ?tabs= and ?active= on mount ────────
  const searchParams = useSearchParams();
  const urlTabs = useMemo(
    () => searchParams.get("tabs")?.split(",").filter(Boolean) ?? [],
    [searchParams],
  );
  const urlActive = searchParams.get("active");

  // ── Route param: /notes/[id] deep-link ─────────────────────────────
  // Works from any descendant of the /notes layout — when the URL is
  // /notes/abc (or /notes/abc/diff) this returns { id: "abc" }, otherwise {}.
  const routeParams = useParams<{ id?: string | string[] }>();
  const routeNoteId =
    typeof routeParams?.id === "string" ? routeParams.id : null;

  // Config props win over URL params, URL params win over route id for the
  // _initial_ tab set. The route id is also enforced as the active tab in a
  // dedicated effect below so client-side nav between /notes/[id] routes works.
  const initialTabs =
    config?.initialTabs ??
    (urlTabs.length > 0 ? urlTabs : routeNoteId ? [routeNoteId] : undefined);
  const initialActiveTab = config?.initialActiveTab ?? urlActive ?? routeNoteId;

  // ── Generate or use provided instance ID ──────────────────────────
  const instanceIdRef = useRef(
    config?.instanceId ??
      `notes-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
  );
  const instanceId = instanceIdRef.current;

  // ── Register instance on mount, unregister on unmount ─────────────
  useEffect(() => {
    dispatch(registerInstance(instanceId));
    return () => {
      dispatch(unregisterInstance(instanceId));
    };
  }, [dispatch, instanceId]);

  // ── Restore tabs from config props, URL params, or DB session ──────
  const restoredFromDbRef = useRef(false);
  useEffect(() => {
    if (restoredFromDbRef.current) return;
    if (!initialTabs || initialTabs.length === 0) return;
    restoredFromDbRef.current = true;

    initialTabs.forEach((noteId) => {
      dispatch(addInstanceTab({ instanceId, noteId }));
      dispatch(fetchNoteContent(noteId));
    });

    const activeId =
      initialActiveTab && initialTabs.includes(initialActiveTab)
        ? initialActiveTab
        : initialTabs[0];
    dispatch(setInstanceActiveTab({ instanceId, noteId: activeId }));
    // Only run once on mount — initialTabs/initialActiveTab are stable
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dispatch, instanceId]);

  // ── Fetch notes list + scope data on mount ──────────────────────────
  const orgId = useAppSelector(selectOrganizationId);
  const fetchedRef = useRef(false);
  useEffect(() => {
    if (!fetchedRef.current && userId) {
      fetchedRef.current = true;
      dispatch(fetchNotesList());
    }
  }, [dispatch, userId]);

  useEffect(() => {
    if (fetchedRef.current && orgId) {
      // Ensure the canonical scope tree is loaded so the new scope pickers
      // (EntityScopeTagger / EntityTargetPicker) and the active-context
      // surface have data. No-op if already `ready` (no refetch policy).
      dispatch(ensureScopeTree());
    }
  }, [dispatch, orgId]);

  // ── Single note mode: set active immediately ──────────────────────
  useEffect(() => {
    if (singleNote) {
      dispatch(addInstanceTab({ instanceId, noteId: singleNote }));
      dispatch(setInstanceActiveTab({ instanceId, noteId: singleNote }));
      dispatch(fetchNoteContent(singleNote));
    }
  }, [dispatch, instanceId, singleNote]);

  // ── Route-param deep link (/notes/[id]) ────────────────────────────
  // Ensures the route id is opened as a tab and made active on every change.
  // Handles initial mount on /notes/abc and client-side nav /notes/abc → /notes/xyz
  // (same layout, so NotesView stays mounted). singleNote takes precedence.
  useEffect(() => {
    if (singleNote || !routeNoteId) return;
    dispatch(addInstanceTab({ instanceId, noteId: routeNoteId }));
    dispatch(setInstanceActiveTab({ instanceId, noteId: routeNoteId }));
    dispatch(fetchNoteContent(routeNoteId));
  }, [dispatch, instanceId, routeNoteId, singleNote]);

  const activeTabId = useAppSelector(selectInstanceActiveTab(instanceId));
  const activeNoteLabel = useAppSelector(
    activeTabId ? selectNoteLabel(activeTabId) : () => null,
  );
  const openTabs = useAppSelector(selectInstanceTabs(instanceId));
  const splitNoteId = useAppSelector(selectInstanceSplitNoteId(instanceId));
  const splitNoteLabel = useAppSelector(
    splitNoteId ? selectNoteLabel(splitNoteId) : () => null,
  );
  const othersActive = useAppSelector(selectOtherUsersActive);
  const activeNoteEditedByOthers = useAppSelector(
    selectActiveNoteEditedByOthers,
  );
  const editorMode =
    useAppSelector(
      activeTabId ? selectNoteEditorMode(activeTabId) : () => "plain",
    ) ?? "plain";

  const setMode = useCallback(
    (mode: string) => {
      if (activeTabId) dispatch(setNoteEditorMode({ id: activeTabId, mode }));
    },
    [dispatch, activeTabId],
  );

  // ── Refresh: refetch list + force-refetch every open tab ──────────
  // Mirrors the route-start fetches so the user can pull the latest server
  // state on demand (e.g. after editing on another device).
  const handleRefresh = useCallback(async () => {
    if (isRefreshing) return;
    setIsRefreshing(true);
    try {
      const work: Promise<unknown>[] = [dispatch(fetchNotesList()).unwrap()];
      if (orgId) {
        // Explicit user refresh → force-refresh the canonical scope tree.
        work.push(dispatch(ensureScopeTree({ refresh: true })));
      }
      for (const noteId of openTabs ?? []) {
        work.push(dispatch(refreshNoteContent(noteId)).unwrap());
      }
      await Promise.allSettled(work);
    } finally {
      setIsRefreshing(false);
    }
  }, [dispatch, isRefreshing, openTabs, orgId]);

  // ── Keyboard shortcuts ───────────────────────────────────────────
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      const mod = e.ctrlKey || e.metaKey;

      // Ctrl+S — save active note
      if (mod && e.key === "s") {
        e.preventDefault();
        if (activeTabId) dispatch(saveNote(activeTabId));
        return;
      }

      // Ctrl+W — close active tab
      if (mod && e.key === "w") {
        e.preventDefault();
        if (activeTabId) {
          dispatch(markTabInteraction({ instanceId }));
          dispatch(removeInstanceTab({ instanceId, noteId: activeTabId }));
        }
        return;
      }

      // Ctrl+F — open find bar (and re-focus + select-all if already open).
      // We explicitly exclude Shift here so the Ctrl+Shift+F handler below
      // owns the "global search" shortcut and the two cannot double-fire.
      // `e.key` honours CapsLock (caps→"F"), so normalize before comparing.
      const keyLower = e.key.length === 1 ? e.key.toLowerCase() : e.key;
      if (mod && !e.altKey && !e.shiftKey && keyLower === "f") {
        e.preventDefault();
        // Standard behavior: if there's a non-empty selection in the
        // currently-focused textarea/input, seed the find query with it.
        // We only pull single-line selections; multi-line selections are
        // usually unintentional for a find query, so we ignore them.
        const active = document.activeElement;
        let prefillQuery: string | undefined;
        if (
          active instanceof HTMLTextAreaElement ||
          active instanceof HTMLInputElement
        ) {
          const { selectionStart, selectionEnd, value } = active;
          if (
            selectionStart != null &&
            selectionEnd != null &&
            selectionEnd > selectionStart
          ) {
            const selected = value.slice(selectionStart, selectionEnd);
            if (selected.length > 0 && !selected.includes("\n")) {
              prefillQuery = selected;
            }
          }
        }
        dispatch(
          openFindReplace({ instanceId, showReplace: false, prefillQuery }),
        );
        return;
      }

      // Ctrl+Shift+F / Cmd+Shift+F — open find in GLOBAL scope. Mirrors
      // VS Code's "Search across files". We also flip the advanced rows on
      // (include/exclude inputs) inside `openFindReplace` when scope=global.
      if (mod && e.shiftKey && !e.altKey && keyLower === "f") {
        e.preventDefault();
        const active = document.activeElement;
        let prefillQuery: string | undefined;
        if (
          active instanceof HTMLTextAreaElement ||
          active instanceof HTMLInputElement
        ) {
          const { selectionStart, selectionEnd, value } = active;
          if (
            selectionStart != null &&
            selectionEnd != null &&
            selectionEnd > selectionStart
          ) {
            const selected = value.slice(selectionStart, selectionEnd);
            if (selected.length > 0 && !selected.includes("\n")) {
              prefillQuery = selected;
            }
          }
        }
        dispatch(
          openFindReplace({
            instanceId,
            showReplace: false,
            scope: "global",
            prefillQuery,
          }),
        );
        return;
      }

      // Ctrl+H (Win/Linux) or Cmd+Option+F (Mac) — open find+replace
      if (
        (e.ctrlKey && !e.metaKey && e.key === "h") ||
        (e.metaKey && e.altKey && e.key === "f")
      ) {
        e.preventDefault();
        dispatch(openFindReplace({ instanceId, showReplace: true }));
        return;
      }

      // F3 / Cmd+G — next match. Shift+F3 / Cmd+Shift+G — previous.
      // Standard "find again" shortcuts across browsers, VS Code, and macOS.
      if (e.key === "F3" || (e.metaKey && !e.ctrlKey && e.key === "g")) {
        e.preventDefault();
        dispatch(
          navigateFindMatch({
            instanceId,
            direction: e.shiftKey ? "prev" : "next",
          }),
        );
        return;
      }

      // Ctrl+Tab — cycle to next tab
      if (mod && e.key === "Tab") {
        e.preventDefault();
        if (openTabs && openTabs.length > 1 && activeTabId) {
          const idx = openTabs.indexOf(activeTabId);
          const next = openTabs[(idx + 1) % openTabs.length];
          dispatch(markTabInteraction({ instanceId }));
          dispatch(setInstanceActiveTab({ instanceId, noteId: next }));
          dispatch(fetchNoteContent(next));
        }
        return;
      }
    };

    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [dispatch, instanceId, activeTabId, openTabs]);

  const modeBtnClass = (mode: string) =>
    cn(
      "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer",
      "[&_svg]:w-3.5 [&_svg]:h-3.5",
      editorMode === mode
        ? "bg-[var(--matrx-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
        : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
    );

  // ── Render ─────────────────────────────────────────────────────────
  return (
    <NotesInstanceProvider value={instanceId}>
      {isMobile ? (
        <MobileNotesView />
      ) : (
        <div className={`flex h-full w-full min-h-0 ${className ?? ""}`}>
          {/* ── Header center: View mode buttons (portaled into shell header) */}
          <PageHeader>
            <div className="matrx-glass-thin-border flex items-center gap-0.5 rounded-full p-0.5">
              {activeTabId && (
                <>
                  <button
                    className={modeBtnClass("plain")}
                    onClick={() => setMode("plain")}
                  >
                    <FileText /> Edit
                  </button>
                  <button
                    className={cn(modeBtnClass("split"), "max-lg:hidden")}
                    onClick={() => setMode("split")}
                  >
                    <SplitSquareHorizontal /> Split
                  </button>
                  <button
                    className={cn(modeBtnClass("wysiwyg"), "max-lg:hidden")}
                    onClick={() => setMode("wysiwyg")}
                  >
                    <PilcrowRight /> Rich
                  </button>
                  <button
                    className={cn(
                      modeBtnClass("markdown-split"),
                      "max-lg:hidden",
                    )}
                    onClick={() => setMode("markdown-split")}
                  >
                    <Columns /> MD Split
                  </button>
                  <button
                    className={modeBtnClass("preview")}
                    onClick={() => setMode("preview")}
                  >
                    <Eye /> Preview
                  </button>
                  <div className="w-px h-4 bg-border/30 mx-0.5" />
                  <button
                    className={cn(
                      "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer [&_svg]:w-3.5 [&_svg]:h-3.5",
                      showHistory
                        ? "bg-[var(--matrx-glass-bg-active)] text-[var(--shell-nav-text-hover)]"
                        : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
                    )}
                    onClick={() => setShowHistory((v) => !v)}
                  >
                    <History /> History
                  </button>
                  <div className="w-px h-4 bg-border/30 mx-0.5" />
                </>
              )}
              <button
                className={cn(
                  "flex items-center gap-1 px-2.5 py-0.5 text-[0.6875rem] font-medium rounded-full transition-colors cursor-pointer [&_svg]:w-3.5 [&_svg]:h-3.5",
                  isRefreshing
                    ? "text-[var(--shell-nav-text-hover)]"
                    : "text-[var(--shell-nav-text)] hover:text-[var(--shell-nav-text-hover)]",
                )}
                onClick={handleRefresh}
                disabled={isRefreshing}
                title={
                  isRefreshing
                    ? "Refreshing…"
                    : "Refresh notes list and open tabs"
                }
                aria-label="Refresh notes"
              >
                <RefreshCw className={cn(isRefreshing && "animate-spin")} />{" "}
                Refresh
              </button>
            </div>
            {/* Active note's action bar — fed remotely by the primary
                NoteContentEditor (preview/split modes register here).
                Renders nothing in plain/wysiwyg modes (no provider). */}
            {activeTabId && (
              <div className="ml-auto flex items-center gap-0.5 shrink-0 max-lg:hidden">
                <NoteReferenceCopyButton
                  noteId={activeTabId}
                  label={activeNoteLabel ?? undefined}
                />
              </div>
            )}
            {activeTabId && (
              <RichDocumentActionSurface
                surfaceId={`note-detail-${activeTabId}`}
                variant="bar"
                fallback={null}
              />
            )}
          </PageHeader>

          {/* Layer 5: Sidebar */}
          {showSidebar && !singleNote && (
            <div className="w-[280px] shrink-0 border-r border-border flex flex-col min-h-0 max-lg:hidden">
              <NoteSidebar instanceId={instanceId} />
            </div>
          )}

          {/* Main content area */}
          <div className="flex-1 flex min-w-0 min-h-0">
            {/* Editor column */}
            <div className="flex-1 flex flex-col min-w-0 min-h-0">
              {/* Layer 4: Tab bar (top) */}
              {showTabs && !singleNote && (
                <NoteTabBar instanceId={instanceId} />
              )}

              {/* Presence indicator */}
              {activeTabId && activeNoteEditedByOthers && (
                <div className="flex items-center gap-2 px-4 py-1 bg-amber-500/10 border-b border-amber-500/20 shrink-0">
                  <span className="relative flex h-2 w-2">
                    <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75" />
                    <span className="relative inline-flex rounded-full h-2 w-2 bg-amber-500" />
                  </span>
                  <span className="text-[0.6875rem] text-amber-700 dark:text-amber-300">
                    Another user is editing this note
                  </span>
                </div>
              )}
              {othersActive && !activeNoteEditedByOthers && (
                <div className="flex items-center gap-2 px-4 py-0.5 bg-blue-500/5 border-b border-blue-500/10 shrink-0">
                  <span className="relative flex h-1.5 w-1.5">
                    <span className="relative inline-flex rounded-full h-1.5 w-1.5 bg-blue-500" />
                  </span>
                  <span className="text-[0.625rem] text-blue-600/70 dark:text-blue-400/70">
                    Other users are active in notes
                  </span>
                </div>
              )}

              {/* Layer 1: Content editor (fills available space) */}
              {activeTabId ? (
                splitNoteId ? (
                  /* ── Split view: two editors side-by-side ─────────── */
                  <div className="flex-1 flex min-h-0">
                    {/* Left pane — active tab. Actions feed the header bar. */}
                    <div className="flex-1 flex flex-col min-w-0 min-h-0">
                      <NoteContentEditor
                        noteId={activeTabId}
                        actionsSurfaceId={`note-detail-${activeTabId}`}
                      />
                    </div>
                    {/* Resize divider */}
                    <div className="w-px bg-border shrink-0" />
                    {/* Right pane — split note */}
                    <div className="flex-1 flex flex-col min-w-0 min-h-0">
                      <div className="flex items-center justify-between px-2 py-0.5 border-b border-border bg-muted/30 shrink-0">
                        <span className="text-[0.625rem] font-medium truncate text-muted-foreground">
                          {splitNoteLabel ?? "Split Note"}
                        </span>
                        <button
                          onClick={() => dispatch(closeSplit(instanceId))}
                          className="flex items-center justify-center w-4 h-4 rounded-sm text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors"
                          title="Close split"
                        >
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                      <NoteContentEditor noteId={splitNoteId} />
                    </div>
                  </div>
                ) : (
                  <NoteContentEditor
                    noteId={activeTabId}
                    actionsSurfaceId={`note-detail-${activeTabId}`}
                  />
                )
              ) : (
                <FolderQuickPick instanceId={instanceId} />
              )}

              {/* Layer 2: Metadata bar (bottom — folder, tags, status) */}
              {activeTabId && <NoteMetadataBar noteId={activeTabId} />}
            </div>
          </div>

          {/* Version history — resizable MatrxDynamic panel (desktop) / Drawer (mobile) */}
          {activeTabId && (
            <NoteVersionHistory
              noteId={activeTabId}
              open={showHistory}
              onOpenChange={setShowHistory}
              onVersionRestored={() => {
                dispatch(fetchNoteContent(activeTabId));
              }}
            />
          )}
        </div>
      )}
    </NotesInstanceProvider>
  );
}
