"use client";

/**
 * NotesAssistStrip — the /notes page's inline assist chips.
 *
 * Runs the deterministic unorganized-notes sweep (notes-assists-producer.ts)
 * once per user per browser session over ALREADY-LOADED Redux state (list +
 * scope assignments — zero extra reads), then renders this surface's pending
 * assists through the canonical per-page AssistStrip (never a forked chip
 * component). The same rows also appear in the global AssistsDock; deciding
 * a chip in either place clears both — one ledger, one slice.
 */

import { useEffect } from "react";
import { useAppDispatch, useAppSelector } from "@/lib/redux/hooks";
import { selectUserId } from "@/lib/redux/selectors/userSelectors";
import { AssistStrip } from "@/features/assists/components/AssistStrip";
import {
  selectAllNotesList,
  selectNoteScopeAssignments,
  selectNoteScopesLoaded,
  selectNotesListStatus,
} from "@/features/notes/redux/selectors";
import {
  NOTES_ASSIST_SURFACE,
  produceNotesAssists,
} from "@/features/notes/notes-assists-producer";

/** One sweep per user per browser session — revisiting /notes must not
 * re-run the scan (or re-emit) on every mount. Module-scoped on purpose. */
const sweptUsers = new Set<string>();

export function NotesAssistStrip({ className }: { className?: string }) {
  const dispatch = useAppDispatch();
  const userId = useAppSelector(selectUserId);
  const notes = useAppSelector(selectAllNotesList);
  const assignments = useAppSelector(selectNoteScopeAssignments);
  const scopesLoaded = useAppSelector(selectNoteScopesLoaded);
  const listStatus = useAppSelector(selectNotesListStatus);

  useEffect(() => {
    // Both halves must be loaded — sweeping before scope assignments arrive
    // would call every note unorganized (a false-positive factory).
    if (!userId || listStatus !== "loaded" || !scopesLoaded) return;
    if (sweptUsers.has(userId)) return;
    sweptUsers.add(userId);

    const assigned = new Set(assignments.map((a) => a.entity_id));
    const unorganized = notes
      .filter(
        (n) =>
          !assigned.has(n.id) &&
          !n.project_id &&
          !n.task_id &&
          (!n.tags || n.tags.length === 0) &&
          (!n.folder_name || n.folder_name === "Draft") &&
          // Blank autogenerated shells don't count as a pileup.
          Boolean((n.label ?? "").trim() || (n.content ?? "").trim()),
      )
      .map((n) => ({
        id: n.id,
        label: (n.label ?? "").trim() || "Untitled note",
      }));
    void produceNotesAssists({ userId, unorganized, dispatch });
  }, [userId, listStatus, scopesLoaded, notes, assignments, dispatch]);

  return <AssistStrip surfaceName={NOTES_ASSIST_SURFACE} className={className} />;
}
