import { chromium } from 'playwright';
const HOST = 'wave2edu.localhost:3001';
const STATE = '/Users/armanisadeghi/code/matrx-frontend/.wave2-scratch/state.json';
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, storageState: STATE });
const page = await context.newPage();
await page.goto(`http://${HOST}/education/game/host`, { waitUntil: 'load', timeout: 60000 });
await page.waitForTimeout(3000);
const createBtn = page.getByRole('button', { name: /Create room/i });
await createBtn.scrollIntoViewIfNeeded();
await createBtn.click();
await page.waitForTimeout(1500);
const dialog = page.getByRole('dialog');
const orgBtn = dialog.getByRole('button', { name: "admin's Workspace" });
await orgBtn.click();
await page.waitForTimeout(500);
console.log('aria-pressed after click:', await orgBtn.getAttribute('aria-pressed'));
const continueBtn = dialog.getByRole('button', { name: /^Continue$/i });
console.log('continue disabled?', await continueBtn.isDisabled());
await continueBtn.click();
await page.waitForTimeout(2500);
console.log('url after continue', page.url());
await page.screenshot({ path: '/Users/armanisadeghi/code/matrx-frontend/.wave2-scratch/after-continue.png' });
await browser.close();
