"use client";

import { useEffect, useRef } from "react";
import { MousePointerClick } from "lucide-react";
import { cn } from "@/lib/utils";
import MarkdownStream from "@/components/MarkdownStream";

interface Props {
  text: string;
  isStreaming: boolean;
  modelId?: string | null;
  title?: string;
  className?: string;
}

/**
 * Renders streaming LLM output with a typewriter caret and a model footer.
 * Auto-scrolls to bottom while streaming so the latest words stay in view.
 */
export function StreamingTextPanel({
  text,
  isStreaming,
  modelId,
  title = "Generating report",
  className,
}: Props) {
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current && isStreaming) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [text, isStreaming]);

  if (!text && !isStreaming) return null;

  return (
    <div
      className={cn(
        "rounded-xl border border-border/60 bg-card/60 backdrop-blur-sm overflow-hidden",
        className,
      )}
    >
      <div className="flex items-center justify-between gap-2 px-3 py-2 border-b border-border/40 bg-gradient-to-r from-primary/5 to-transparent">
        <div className="flex items-center gap-1.5 text-[11px] font-semibold">
          <MousePointerClick className="h-3 w-3 text-primary" />
          <span>{title}</span>
        </div>
        {isStreaming && (
          <span className="flex items-center gap-1 text-[10px] text-primary">
            <span className="h-1.5 w-1.5 rounded-full bg-primary animate-pulse" />
            Streaming
          </span>
        )}
      </div>
      <div
        ref={scrollRef}
        className="max-h-[32rem] overflow-y-auto p-3"
      >
        <div className="prose prose-sm dark:prose-invert max-w-none prose-p:text-[13px] prose-p:leading-relaxed prose-headings:text-sm prose-headings:font-semibold prose-h1:text-base prose-h2:text-[15px]">
          <MarkdownStream
            content={text}
            isStreamActive={isStreaming}
            hideCopyButton
          />
          {isStreaming && (
            <span
              className="inline-block w-1.5 h-3.5 bg-primary/70 align-middle ml-0.5 animate-pulse"
              aria-hidden="true"
            />
          )}
        </div>
      </div>
      {modelId && (
        <div className="px-3 py-1.5 border-t border-border/40 bg-muted/20 text-[10px] text-muted-foreground tabular-nums">
          Generated by{" "}
          <span className="font-mono text-foreground/70">{modelId}</span>
        </div>
      )}
    </div>
  );
}
